### ISSUE TITLE
Pairing chests with code into a double chest does not work

### ISSUE THREAD

**Issue by MrIrishMiner** [iTXTech/Genisys#1000]
#### Issue description

Several times I have attempted to pair chests when placing both of them down with no luck.

#### Steps to reproduce the issue

 1. Write a small plugin to place down two chests and pair them.
 2. Test it out.

#### OS and versions

* Genisys:1.1dev-a685f20
* PHP: 7.0.3
* OS: Windows 7

#### Crashdump, backtrace or other files
```
       $entity = $event->getEntity();
        $lvl = $entity->getLevel();
        if ($entity instanceof Player) {
            $x = $entity->getX();
            $y = $entity->getY();
            $z = $entity->getZ();
            $this->getServer()->getScheduler()->scheduleDelayedTask(new Bomb($this, $entity), 20 * 30);
            $inventory = $entity->getInventory()->getContents();
            $event->setDrops(array(Item::get(Item::AIR)));
            $entity->getLevel()->setBlock(new Vector3($x, $y, $z), new Block(Block::CHEST), true, true);
            $entity->getLevel()->setBlock(new Vector3($x+1, $y, $z), new Block(Block::CHEST));
            $nbt = new CompoundTag("", [new ListTag("Items", []), new StringTag("id", Tile::CHEST), new IntTag("x", $x), new IntTag("y", $y), new IntTag("z", $z)]);
            $nbt->Items->setTagType(NBT::TAG_Compound);
            $tile = Tile::createTile("Chest", $entity->getLevel()->getChunk($x >> 4, $z >> 4), $nbt);
            $chest2 = $lvl->getTile(new Vector3($x+1, $y, $z));
            $chest = $lvl->getTile(new Vector3($x, $y, $z));
            if($chest instanceof Chest) {
                if (!$chest->isPaired()) {
                    if ($chest2 instanceof Chest) {
                        if (!$chest2->isPaired()) {
                            $chest->pairWith($chest2);
                            $chest2->pairWith($chest);
                            $chest->saveNBT();
                            $chest->spawnToAll();
                            $chest2->spawnToAll();
                            $chest->getInventory()->setContents($inventory);

                        }
                    }
                }
            }
        }
```

**Comment by MrIrishMiner** [comment]
The event is death event by the way.

**Comment by Muqsit** [comment]
Are you saying you aren't able to make double chests?

**Comment by MrIrishMiner** [comment]
Yes

**Comment by Muqsit** [comment]
Are you sure you're on the latest version of Genisys? Try removing ask your plugins and see if they problem still exists. It seems fine for me!

**Comment by MrIrishMiner** [comment]
Key words, setting chests and pairing with code.

**Comment by PeratX** [comment]
You don't need to spawnToAll because it is done by Genisys

**Comment by PeratX** [comment]
By the way , the face(damage) of these two chests must same

**Comment by PeratX** [comment]
I suggest you to use Chest::place to do the work!

**Comment by MrIrishMiner** [comment]
Tried using it, got tons of errors. Could you tell me what's wrong with it?C is use pocketmine\block\Chest as C;  `$item = Item::get(Item::CHEST);
            $block = Block::get(Block::CHEST);
            $target = Block::get(Block::AIR);
            $x = $player->x;
            $y = $player->y;
            $z = $player->z;
            $inventory = $player->getInventory()->getContents();
            $armor = $player->getInventory()->getArmorContents();
            $chest1 = new C();
            $chest2 = new C();
            $chest1->place($item, $block, $target, 0 ,$x, $y, $z);
            $chest2->place($item, $block, $target, 0 ,$x+1, $y, $z);`
