### ISSUE TITLE
Fix jenkins PLS

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#1001]

**Comment by Muqsit** [comment]
Jenkins server is actually up and running. Maybe you are living far away from the jenkins' server's host?

**Comment by Driesboy** [comment]
jenkins is running but dont work!

**Comment by ishitatsuyuki** [comment]
Use GitLab today.

**Comment by Driesboy** [comment]
ok

**Comment by Muqsit** [comment]
![er](https://cloud.githubusercontent.com/assets/15074389/15446834/d39977bc-1f34-11e6-888d-c26fc3a653f8.PNG)
Actually, it does work! It's just that you're kinda living far away from the server's host!
Try using proxy or something, the server may be transferred to a better host in the future :)

**Comment by ishitatsuyuki** [comment]
@Muqsit I broke the build by a mistake in CommandSender, and jenkins is jammed since I can't cancel that. I have contacted the admin for jenkins.
