### ISSUE TITLE
Jenkins builder stuck on build #394

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1004]
#### Issue description
The Jenkins server has been stuck on build #394 for the last 5 hours

https://jenkins.mcper.cn/job/Genisys-master/394/console

**Comment by ishitatsuyuki** [comment]
Can you check closed issue before opening.

**Comment by dktapps** [comment]
@ishitatsuyuki oh sorry lol

**Comment by Bidou0418** [comment]
still stuck
