### ISSUE TITLE
Text on signs are dissapear after sign creation

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#1006]
When I create sign with text, text are dissapear after sign creation.
This is very annoying...

#### Steps to reproduce the issue
1) Create many signs with text.
2) Some signs will empty.

#### OS and versions
* Genisys: build 393
* PHP: 7
* OS: Windows 7

**Comment by Driesboy** [comment]
that bug is since 0.12.0 pocketmine

**Comment by Muqsit** [comment]
Yeah, it's a pocketmine bug.

**Comment by PeratX** [comment]
Known issue. Already list in PM bugs.
