### ISSUE TITLE
PvP is not working

### ISSUE THREAD

**Issue by PhilipphatesPHP7** [iTXTech/Genisys#1007]
#### Issue description
I had removed all plugins and in the server.properties pvp is "on".
The spawn-protection is also 0. But i cant hit player.

#### OS and versions

* Genisys: 393
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Ozelord757** [comment]
Same :c

**Comment by PhilipphatesPHP7** [comment]
Genisys....
You must set the difficult to 1 ...
