### ISSUE TITLE
Number of players

### ISSUE THREAD

**Issue by ScandiePlay** [iTXTech/Genisys#1009]
#### Issue description
When I type /list, server returns me a valid number of players and a list of names.
When I type /status, server returns wrong number of online players.

For example: in /list - 14 / 60, in /status - 20 / 60.

#### OS and versions
* Genisys: 5feed45 (downloaded from GitLab)
* PHP: 7
* OS: Ubuntu 14.04

P.S. Maybe, because of it, there is an issue #1003. I don't know, how to solve all these issues.

**Comment by Muqsit** [comment]
Or what if you gained 4 players more by the time you typed /status? :/

Anyways, this is highly unlikely to happen because both the commands use the same way to get the number of online players.

**Comment by MrIrishMiner** [comment]
When players leave on my server, when you see the list at the pause menu, they are still on.

**Comment by ScandiePlay** [comment]
@Muqsit , I can send a screenshot, if you want.

**Comment by Shamil0402** [comment]
Player list on pause menu never updating when you playing on server, it's updating only when you joining to server.

**Comment by ScandiePlay** [comment]
@Muqsit , here are the screenshots (I have Russian language, so, I'll translate some of the words) of /list and /status commands, and a list of my plugins.

1st screenshot: "Число игроков" - Number of players (at the top of an image), there are 38 / 60.
![screenshot_2016-05-22-11-14-05](https://cloud.githubusercontent.com/assets/17462298/15453065/1d299da0-200f-11e6-8f8b-e4eaab81de7a.png)

2nd screenshot: "Сейчас 15 / 60 игроков на сервере" - "There are 15 / 60 players"; this time, don't say that 23 players went out of the server when I was writing /list.
![screenshot_2016-05-22-11-14-16](https://cloud.githubusercontent.com/assets/17462298/15453075/53a24fbc-200f-11e6-89ce-11f66eeae17b.png)

3rd screenshot: my list of plugins, I have 24 plugins, as you can see. Some of them are written by me, but I'm sure that this problem isn't caused by them.
![screenshot_2016-05-22-11-14-33](https://cloud.githubusercontent.com/assets/17462298/15453081/b043d9f2-200f-11e6-8af0-65a9c7d0e056.png)

**Comment by ScandiePlay** [comment]
And, in the main menu of MCPE, there were 14 / 60 players before I logged in.

**Comment by ishitatsuyuki** [comment]
Here is some possible causes:
1. There are some 'ghost' players. (This is our fault then)
2. There are some players that are invisible. They may be in spectator mode? A plugin can also do that.

**Comment by ScandiePlay** [comment]
@ishitatsuyuki , nobody has a spectator mode. Maybe, someone has, but not 23 players (difference between /list-players, and /status-players) - that's impossible.

**Comment by jojoe77777** [comment]
> Or what if you gained 4 players more by the time you typed /status? :/
> 
> Anyways, this is highly unlikely to happen because both the commands use the same way to get the number of online players.

@Muqsit Actually, not quite. Look at this:

https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/command/defaults/ListCommand.php#L48-L53

https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/command/defaults/StatusCommand.php#L49

The status command just counts how many players are online, but list doesn't show people who are vanished to you. Not sure if that is the cause though.
