### ISSUE TITLE
Fire spread problem

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#1015]
fire spread enabled in genisys.yml
in protected area;
does not burn blocks of wood but will burn down trees and start sand on fire.
In some situation sand even burns indefinitely...
fire also spreads and burns down sandstone steps if adjacent to a netherrack block on fire.
I haven't tested all options, however it is clear that this needs to be reviewed.
in unprotected area;
fire does not burn down trees, but lit sand burns indefinitely...

Genisys 396

**Comment by PeratX** [comment]
This is not our fault. Please look at our code.

**Comment by Gamecrafter** [comment]
@PeratX Not everyone knows how to read code... :stuck_out_tongue:

**Comment by Bidou0418** [comment]
no worries
prob pocketmine bug
