### ISSUE TITLE
Memory increases till overload

### ISSUE THREAD

**Issue by Moocow9m** [iTXTech/Genisys#1016]
#### Issue description
After any amount of players join, the ram goes up steadily even when they log off till about 1134MB then I get the message Cant keep up, is the server overloaded? only once then it just lags horribly. only way i found to fix it was to shut down server and restart it every time.

#### Steps to reproduce the issue

1. have player join.
2. Wait.

### OS and versions

* Genisys: 1.1dev-400
* PHP: 7
* OS: Windows

**Comment by ishitatsuyuki** [comment]
Just like MCPC, the garbage collector kicks in and ruin everything. Increase max-memory.

**Comment by Moocow9m** [comment]
#Main thread soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 main-limit: 1000

 #Main thread hard memory limit in megabytes. Set to 0 to disable
 #This will stop the server when the limit is surpassed
 main-hard-limit: 6144

**Comment by Moocow9m** [comment]
my hard limit is high

**Comment by ishitatsuyuki** [comment]
Your soft limit is low

**Comment by Moocow9m** [comment]
But shouldn't go back down when players leave not up when no one is on?

**Comment by Moocow9m** [comment]
Because with it always increasing it will just eat up ram till it does hit the hard limit...
