### ISSUE TITLE
Deprecated: sendTip() error

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#1017]
#### Issue description
Deprecated: sendTip() should no longer be used in phar:///home/nml32/pocketmine/PocketMine-MP.phar/src/pocketmine/Player.php on line 3910

#### Steps to reproduce the issue
Happens when people logon

#### OS and versions
* Genisys: Genisys 1.1dev-400 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.x alpha (protocol version 70)

* PHP: 7
* OS: Linux

#### Crashdump, backtrace or other files
NA
Paste here
```

**Comment by PeratX** [comment]
Check your plugin! Do not use SendTip any more

**Comment by NML32** [comment]
I'm trying to figure out what plugin would be causing the error. I thought it may be CustomAlerts but I disabled the plugin and I'm still getting the error. 

Still looking

**Comment by ishitatsuyuki** [comment]
You are stupid enough by not understanding 'deprecated'...

**Comment by NML32** [comment]
@ishitatsuyuki thanks for that comment as usual your comments are always very helpful.

**Comment by SurvivalHive** [comment]
@NML32 
he's right

**Comment by PeratX** [comment]
He is not FRIENDLY

**Comment by katnussssss** [comment]
@NML32 Savage but totally true I mean there here to help yet they dont think about it

**Comment by NML32** [comment]
K, I'm not a coder but maybe someone here can tell me what should be used in place of sendtip().

I'm sure the error is from MyPots plugin. I found this in the code.

$event->getPlayer()->sendTip($popup);

**Comment by NML32** [comment]
nvm, I changed sendtip to sendpopup and all seems good.
