### ISSUE TITLE
Water does not naturally generate

### ISSUE THREAD

**Issue by Wellonamed** [iTXTech/Genisys#1018]
#### Issue description
A game-breaking world generation problem which cause water to not generate. In fact; Rivers, Lakes, Swampland, etc. simply appear as some sort of weird flatlands which are, most of the time, covered in dandelions and red flowers.

#### Steps to reproduce the issue
1. Create a fresh, new world.
2. Venture a for a while until you come upon an oddly, almost perfect, flatland covered in flowers.

#### OS and versions
* Genisys: 1.1dev-391
* PHP: 7.0.3
* OS: iPhone 5S (iOS 9.3.1). Server hosted by VirtualGladiators with the Cow Egg plan.

#### Crashdump, backtrace or other files
```
Image1: https://i.imgur.com/MQa2fU4.png
Image2: https://i.imgur.com/12MLHK6.png
Image3: https://i.imgur.com/M1d0Bho.png
Image4: https://i.imgur.com/OLKyzcm.png
Image5: https://i.imgur.com/XDZ1qXq.png
Image6: https://i.imgur.com/Qvy9keW.png
Image7: https://i.imgur.com/1uMO8C5.png
```

**Comment by Muqsit** [comment]
Oh, OceanBiome might be extending something else!

**Comment by Wellonamed** [comment]
Also, the only passive animals that seems to spawn are cows.

**Comment by PeratX** [comment]
Are you using a mobile device to hold a server?

**Comment by Wellonamed** [comment]
No, I was just confused by those "OS and versions" things. It's actually hosted on VirtualGladiators. Am I the only one for which this is happening?

**Comment by Muqsit** [comment]
I can't assure this problem so could you go to the water-less place and type /biome get and send the biome's ID?

**Comment by Wellonamed** [comment]
It said that the biome ID was 0.

**Comment by Bidou0418** [comment]
I havent tested lately but I was also getting this a few weeks ago...
I was trying to test a water not flowing to another block when broken bug and i noticed no water areas were generated when generating a new map.
Water areas(lakes) seamed to be replaced by grasslands.

**Comment by elvisw** [comment]
The water still does not naturally generate  in new version.
