### ISSUE TITLE
possible fix for Slapper crash?

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Genisys#102]
The ImagicalMine Team solved the slapper crash in their server code (*PlayerInventory.php*):
https://github.com/robske110/ImagicalMine/commit/c903bd4b69f4d8b60897d6e14602dabea973f088

Can you also remark the lines in Genisys release? (of course only if it doesn't produce new errors)

**Comment by xpyctum** [comment]
You can do pull request.

**Comment by CrayonDing** [comment]
Oh.But it produces new errors
