### ISSUE TITLE
hunger bug kick player join server

### ISSUE THREAD

**Issue by iTCMega** [iTXTech/Genisys#1021]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
[Server thread/CRITICAL]: Error: "Call to a member function setAttribute() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 4324

```

**Comment by iTCMega** [comment]
new version

**Comment by iTCMega** [comment]
[Server thread/CRITICAL]: Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 4324

**Comment by PeratX** [comment]
Step to reproduce please.

**Comment by PeratX** [comment]
No details, close.
