### ISSUE TITLE
Animals and Mobs Will Burn Under Sunlight Sometimes

### ISSUE THREAD

**Issue by FocusedSG** [iTXTech/Genisys#1022]
#### Issue description
Not only the zombies, animals will also burn under the sunlight sometimes.

#### Steps to reproduce the issue
Simply spawn some animals with mob AI true.

#### OS and versions

* Genisys: #404
* PHP: 7
* OS: Windows 10

**Comment by PeratX** [comment]
Known issue and AIs will be rewritten in summer
