### ISSUE TITLE
ScoreboardStats....

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#1023]
![screenshot_2016-05-23-13-23-31](https://cloud.githubusercontent.com/assets/10086234/15467896/93014b38-20e9-11e6-856c-9d18b33d998b.png)
scoreboard down after update, and began to disappear when you switch slots.

UPDATE: I changed sendTip to sendPopup in my plugin, but it not comfortable, a part of scoreboard cropped...

In console 
Deprecated: sendTip() should no longer be used in phar://C:/Users/▒▒▒▒▒▒/Desktop/Genisys/Genisys.phar/src/pocketmine/Player.php on line 3910
#### Steps to reproduce the issue
1) Install my plugin  and join to server
https://yadi.sk/d/Bh5jXG9qrv4Mj
2) See in console

* Genisys: build 402
* PHP: 7
* OS: Windows 7

**Comment by robske110** [comment]
MCPE issue

**Comment by Shamil0402** [comment]
Why sendTip outdated?

**Comment by MrIrishMiner** [comment]
They deprecated sendTip() in 0.14.2, so you can only use sendPopup() now.

**Comment by CrayonDing** [comment]
Please use SendPopup()

**Comment by Shamil0402** [comment]
:(

sendPopup is very bad

**Comment by CrayonDing** [comment]
but MCPE deprecated Tip

**Comment by Shamil0402** [comment]
I noticed it in 0.14.2+
