### ISSUE TITLE
Enchanted Weapon

### ISSUE THREAD

**Issue by FocusedSG** [iTXTech/Genisys#1026]
#### Issue description
When holding a enchanted weapon, tapping another block will cause the selected box in the hotbar to select another box.
#### Steps to reproduce the issue
Enchant a sword, hold it and tap on a block.
#### OS and versions

* Genisys: #404
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files

**Comment by PeratX** [comment]
Known issue. Already listed in W10 Edition bugs.
