### ISSUE TITLE
0.15.0 update?

### ISSUE THREAD

**Issue by CaptainDuck** [iTXTech/Genisys#1027]
Hi! I just want to know if u guys have made or working on a compatible 15.0, I was just saying that when 15.0 has officially released.. We don't have to wait for the Phar :D

**Comment by Muqsit** [comment]
![g](https://cloud.githubusercontent.com/assets/15074389/15469066/82290b8c-20f0-11e6-9dce-8c3e1371a7e4.PNG)

**Comment by Muqsit** [comment]
We will update Genisys as soon as 0.15 comes out, don't worry :)

**Comment by CaptainDuck** [comment]
Ohh okay, thx :D

**Comment by RobertoGamerYT2** [comment]
When updated Genisys Official Minecraft 0.15.0 .
