### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#103]
Please add EVENT_SOUND_NOTE

**Comment by seetch** [comment]
:+1:

**Comment by PeratX** [comment]
Do you mean the note box sound?

**Comment by MrDoni98** [comment]
[To Note](https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/level/sound/NoteblockSound.php)
public function __construct(Vector3 $pos, $pitch = 0){
		parent::__construct($pos, LevelEventPacket::EVENT_SOUND_NOTE, $pitch);
}

[To LevelEventPacket](https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/network/protocol/LevelEventPacket.php)

const EVENT_SOUND_NOTE

**Comment by xpyctum** [comment]
@MrDoni98 you can do a pull request.

**Comment by GalvinGao** [comment]
Do a pull request. Not a issue. Close issue.
