### ISSUE TITLE
Enchant books!

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1032]
#### Issue description

Find errors in console

#### Steps to reproduce the issue

I don't know.

#### OS and versions

* Genisys: Genisys_1.1dev-404.phar
* PHP: 7.0.2 (Genisys) x64
* OS: Ubuntu 14.04.4 LTS

#### Crashdump, backtrace or other files
```
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
23.05 17:32:48 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249
23.05 17:32:48 [Server] INFO Warning: Illegal offset type in phar:///Genisys_1.1dev.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246
```

**Comment by MrIrishMiner** [comment]
Did you try to enchant something? And then this happened?

**Comment by gaoyichuan** [comment]
Please tell us what you did when this happened. It seemed that you used a unavailable enchantment

**Comment by PeratX** [comment]
Step to reproduce please.

**Comment by flyingbananapeel** [comment]
I'm having the same issue.

I'm able to enchant weapons and tools but not books. When trying to enchant books no enchantment are displayed as options to choose.

Console displays the following errors:

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Warning: Illegal offset type in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 246

Warning: Invalid argument supplied for foreach() in phar://C:/Users/PMServer/Desktop/Genisys/Genisys.389.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 249

Running most current Genisys with build 407 (this started with build 389) on Windows 8.1

**Comment by MrIrishMiner** [comment]
Books do not work as far as I know in this latest update. But thank you very much for pointing out why it was happening. :D

**Comment by flyingbananapeel** [comment]
Can you enchant books in 0.14.2?

This is for a Minecraft summer camp. Need to know if I should keep my devices at 0.14.2 or update them to 0.14.3.

Thanks
