### ISSUE TITLE
With Redstone you can only open doors with levers on the floor

### ISSUE THREAD

**Issue by Troctor** [iTXTech/Genisys#1033]
#### Issue description
With Redstone you can only open doors with levers on the floor

#### Steps to reproduce the issue
attempt to use redstone to power a door without a lever on the floor

#### OS and versions
* Genisys: This server is running Genisys 1.1dev "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.x alpha (protocol version 70)
* PHP: 7.0.3
* OS:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

#### Crashdump, backtrace or other files
N/A

**Comment by PeratX** [comment]
Redstone improvement is already listed in ToDo list

**Comment by PeratX** [comment]
Include in #854 .
