### ISSUE TITLE
Login Spam

### ISSUE THREAD

**Issue by BobbyTowers** [iTXTech/Genisys#1034]
#### Issue description

It spams this every so often. 

Deprecated: sendTip() should no longer be used in phar://C:/Users/Bobby-Foo/Documents/MCPE SQL/PocketMine-MP.phar/src/pocketmine/Player.php on line 3910

#### Steps to reproduce the issue

It shows it when players first login.

#### OS and versions

* Genisys: 404
* PHP: 7.0.3
* OS: Win 7

#### Crashdump, backtrace or other files

Nope

**Comment by SurvivalHive** [comment]
please read and understand the message: 

Deprecated: sendTip()

**Comment by BobbyTowers** [comment]
I took out all of my plugins and im still getting this.

**Comment by Efforto** [comment]
Try to update to the latest source, and try again

**Comment by BobbyTowers** [comment]
Fixed @PeratX
