### ISSUE TITLE
sendTip error

### ISSUE THREAD

**Issue by BobbyTowers** [iTXTech/Genisys#1037]
Issue description

Please look at this, I removed all of my plugins and i'm still getting this.

Deprecated: sendTip() should no longer be used in phar://C:/Users/Bobby-Foo/Documents/MCPE SQL/PocketMine-MP.phar/src/pocketmine/Player.php on line 3910

Steps to reproduce the issue

It shows it when players first login.

OS and versions

Genisys: 404
PHP: 7.0.3
OS: Win 7
Crashdump, backtrace or other files

Nope

**Comment by Efforto** [comment]
PLEASE DO NOT OPEN ANY ISSUE! TRY TO UPDATE GENISYS TO THE LATEST SOURCE!

**Comment by dog194** [comment]
#1031

**Comment by BobbyTowers** [comment]
Fixed @PeratX
