### ISSUE TITLE
When a Player in survival mode quit the Server and enter again,he loses his stuff

### ISSUE THREAD

**Issue by SoyPro** [iTXTech/Genisys#1039]
#### OS and versions

* Genisys: 407-dev "ikaros" API 2.0.0 (protocol 70)
* PHP: 7
* OS: android

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Follow the template. Your server is possibly outdated.

**Comment by SoyPro** [comment]
No i have the newest versión why are you closing?

**Comment by ishitatsuyuki** [comment]
Write your version. The people who say they have the latest is possibly outdated.

**Comment by SoyPro** [comment]
Ok i have genysis 407dev. Its de lastest version right?

**Comment by SoyPro** [comment]
Thanks, tell me this if you have fix it and i can open my Server again

**Comment by SoyPro** [comment]
I have android

**Comment by PeratX** [comment]
Network problem. Do not use android to hold your server (not recommended)
