### ISSUE TITLE
TNT is load server.

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#1040]
#### Issue description
When I set ONLY 500 tnt and ingnite their, TPS falls bellow 1.

On screenshots only 328 tnt...

On first screenshot I show primordial TPS.

#### Steps to reproduce the issue
1) place many tnt (500)
2) write /status or see in console

#### OS and versions

* Genisys: build 407
* PHP: 7
* OS: windows 7
* CPU intel core i5 6400 (4 cores 2.8GHZ/3.2GHZ)
* 8 GB RAM

![screenshot_2016-05-24-22-13-32](https://cloud.githubusercontent.com/assets/10086234/15516884/9104f694-21fd-11e6-870e-f768bd7de311.png)
![screenshot_2016-05-24-22-13-56](https://cloud.githubusercontent.com/assets/10086234/15516904/9ed49c8e-21fd-11e6-99dc-57ddba90b148.png)

**Comment by PeratX** [comment]
Average TPS is more accurate.

**Comment by gaoyichuan** [comment]
You can try to explode 500 TNTs in singleplayer...

**Comment by Muqsit** [comment]
*ONLY 500 TNTS* "ONLY" ""ONLY""
