### ISSUE TITLE
Async 

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#1041]
#### Issue description

I tried to make a pull request that fixed this but went unanswered.

Undefined index: phar://C:/Users/admin/Downloads/PocketMine-MP/Genisys.phar/src/pocketmine/scheduler/AsyncTask.php on line 129

#### Steps to reproduce the issue

const MYSQLI_KEY = "CyberParadoX.database.Async.SQLite3";
$sqli = $this->getFromThreadStore(self::MYSQLI_KEY); // error here
		if($sqli !== null){
			return $sqli;
		}
#### OS and versions

* Genisys: 407
* PHP: 7
* OS: windows

#### Crashdump, backtrace or other files
```
Notice: Undefined index: CyberParadoX.database.Async.SQLite3 in phar://C:/Users/admin/Downloads/PocketMine-MP/Genisys.phar/src/pocketmine/scheduler/AsyncTask.php on line 129

```

**Comment by XxDXM-hippiexX** [comment]
Note that after it runs once it will not show the error bc below the null check i have 

`$sqli = StatsDataBase::createsqliInstance(self::SQL);
$this->saveToThreadStore(self::MYSQLI_KEY, $sqli);`

**Comment by PeratX** [comment]
Full code please.

**Comment by XxDXM-hippiexX** [comment]
`<?php

namespace DXM_Hippie\CyberParadoX\Task\Async;

use pocketmine\scheduler\AsyncTask;
use DXM_Hippie\CyberParadoX\database\StatsDataBase;

abstract class AsyncQueryTask extends AsyncTask{
    
	const MYSQLI_KEY = "CyberParadoX.database.Async.SQLite3";
        const SQL = "C:PocketMine-MP\plugins\CyberParadoX\Stats\players.db";
        
	protected function __construct(){
	}
       /**
        * @return SQLite3
        */
	protected function getMysqli(){
		$sqli = $this->getFromThreadStore(self::MYSQLI_KEY);
		if($sqli !== null){
			return $mysqli;
		}
		$sqli = StatsDataBase::createMysqliInstance(self::SQL);
		$this->saveToThreadStore(self::MYSQLI_KEY, $sqli);
                return $sqli;
	}
}`

**Comment by XxDXM-hippiexX** [comment]
Dont you see the problem in the pm code?..

`public function getFromThreadStore($identifier){
		global $store;
                return $this->isGarbage() ? null : $store[$identifier];
	}`

**Comment by XxDXM-hippiexX** [comment]
`public function getFromThreadStore($identifier){`
		`global $store;`
                `return $this->isGarbage() ? null : $store[$identifier] ?? null;`
	`}`

**Comment by PeratX** [comment]
After execute, it will mark Garbage

**Comment by XxDXM-hippiexX** [comment]
It has been commented out..

`public function run(){
		$this->result = null;
		$this->isGarbage = false;

		if($this->cancelRun !== true){
			try{
				$this->onRun();
			}catch(\Throwable $e){
				$this->crashed = true;
				$this->worker->handleException($e);
			}
		}

		$this->isFinished = true;
		//$this->setGarbage();
	}`
