### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#1042]
Jenkins build 326
https://cloud.githubusercontent.com/assets/15706847/15533359/084ecb98-226d-11e6-8b91-36f89478bd83.jpg
https://cloud.githubusercontent.com/assets/15706847/15533375/127bc2ec-226d-11e6-8d7d-4f84bfc9031a.jpg

**Comment by flaxues** [comment]
You are just running out of memory...

**Comment by Driesboy** [comment]
please follow the template!
