### ISSUE TITLE
enchanted armor for mobs

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#1044]
Enhancement;

Would be nice to have more challenging mobs...
Enchanted armor and weapons for mobs could help improve gameplay.

Perhaps limiting monster spawner to 10 active mobs could also help gameplay without consuming too many resources. 

Functional rail system is greatly missed
 
Inserting Piston mechanism is also something i have been waiting for.

**Comment by Skyladd** [comment]
Pistons arent even added yet. When 0.15.0 comes out they will, but also the Genisys devs are students so wait until they have more free time and i bet they will add everything we can dream of
