### ISSUE TITLE
Chests in creative

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#1046]
Sometimes items that put in creative are dissapearing when I open chest again.

#### Steps to reproduce the issue
1) Turn on Gamemode 1
2) Put into chest some items
3) Open a chest again
#### OS and versions
* Genisys: build 407
* PHP: 7
* OS: Windows 7

**Comment by Shamil0402** [comment]
I recorded a short video.

https://youtu.be/rhTTQ8yjNKI

**Comment by Shamil0402** [comment]
If you have problem with resolution, I reuploaded video.

https://youtu.be/ol-EPaQL7n4

**Comment by Adam1609** [comment]
That's bug in this chest creative. I feel that something is wrong with creative....

**Comment by RainMa22** [comment]
look at genisys.yml

**Comment by Efforto** [comment]
Well, Youtube is blocked by GFW and ...We can"t see it. Can you upload it to a cloud drive? Like OneDrive or sth.

**Comment by PeratX** [comment]
Fixed with hotbar.
