### ISSUE TITLE
sendTip error. 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#1048]
I keep getting this msg on console. 

Deprecated: sendTip() should no longer be used in /home/Tolo/server2/src/pocketmine/Player.php on line 3912

version: Genisys_1.1dev-408.phar

**Comment by dog194** [comment]
Deprecated: sendTip() should no longer be used

**Comment by Tolo0** [comment]
a solution would be nice 😅

**Comment by Tolo0** [comment]
iv checked all my plugins and disabled all that have tip msg. and I'm still getting the error. any advice?

**Comment by Tolo0** [comment]
can you not revert the changes you made? so many plugins course this issue. and it's making my server lagg. this  issue shouldn't be closed.

**Comment by ishitatsuyuki** [comment]
We don't support outdated plugins. It's not a reason to complain.
