### ISSUE TITLE
Win10 Fixes?

### ISSUE THREAD

**Issue by scot99** [iTXTech/Genisys#1050]
#### Issue description
Possible to add patches to genisys branch?

#### Steps to reproduce the issue
Win10 client

#### OS and versions
• Genisys:dev-406
• PHP:7.0.3
• OS:Raspbian GNU/Linux 8 (jessie) - debian

#### Crashdump, backtrace or other files

Looks like extremeheat has made good progress attempting to fix the win10 client connectivity issues, any chance you could use the patches here to help fix the issue? - https://github.com/PocketMine/PocketMine-MP/issues/4079

**Comment by PeratX** [comment]
It is already listed in W10 Edition Bug.

**Comment by dog194** [comment]
That issue do not provide a solution.
