### ISSUE TITLE
Not getting damaged standing ontop of the cactus.

### ISSUE THREAD

**Issue by FocusedSG** [iTXTech/Genisys#1053]
#### Issue description
When you are standing ontop a cactus, you will not be damaged. But the sides will.

#### Steps to reproduce the issue
Place a cactus on a sand, set gamemode to survival and stand on the cactus.

#### OS and versions

* Genisys: #413
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files

**Comment by jojoe77777** [comment]
PE 0.14.3 singleplayer also has this issue... Maybe a client hitbox problem?

**Comment by PeratX** [comment]
I have checked code, no problem. Maybe client side's issue.

**Comment by jojoe77777** [comment]
> I have checked code, no problem. Maybe client side's issue.

My guess is the client-side hitbox changed in 0.14.3 so the clients float a bit above the cactus block.

**Comment by PeratX** [comment]
Try a var_dump with the position of player and the block.

**Comment by dktapps** [comment]
Seems fixed as of 0.15.0. Tested on Win10 and Android both. Closing.
