### ISSUE TITLE
memory issue with the new update of genisys 405 :/

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#1054]
26.05 18:51:13 [Server] INFO Warning: include(phar:///jar/versions/Genisys/Genisys405.phar/src/pocketmine/entity/FallingSand.php): failed to open stream: phar error: internal corruption of phar "/jar/versions/Genisys/Genisys405.phar" (actual filesize mismatch on file "src/pocketmine/entity/FallingSand.php") in phar:///jar/versions/Genisys/Genisys405.phar/src/spl/BaseClassLoader.php on line 128 26.05 18:51:13 [Server] INFO Warning: include(): Failed opening 'phar:///jar/versions/Genisys/Genisys405.phar/src/pocketmine/entity/FallingSand.php' for inclusion (include_path='.:') in phar:///jar/versions/Genisys/Genisys405.phar/src/spl/BaseClassLoader.php on line 128 26.05 18:51:13 [Server] INFO Warning: include(phar:///jar/versions/Genisys/Genisys405.phar/src/spl/ClassNotFoundException.php): failed to open stream: phar error: internal corruption of phar "/jar/versions/Genisys/Genisys405.phar" (actual filesize mismatch on file "src/spl/ClassNotFoundException.php") in phar:///jar/versions/Genisys/Genisys405.phar/src/spl/BaseClassLoader.php on line 128 26.05 18:51:13 [Server] INFO Warning: include(): Failed opening 'phar:///jar/versions/Genisys/Genisys405.phar/src/spl/ClassNotFoundException.php' for inclusion (include_path='.:') in phar:///jar/versions/Genisys/Genisys405.phar/src/spl/BaseClassLoader.php on line 128 26.05 18:51:13 [Server] Server thread/CRITICAL Error: "Class 'ClassNotFoundException' not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 131 26.05 18:51:13 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump 26.05 18:51:13 [Multicraft] Server shut down (starting) 26.05 18:51:13 [Multicraft] Restarting crashed server in 5 seconds 26.05 18:51:13 [Multicraft] Stopping server!

**Comment by mote166** [comment]
New issue please help me 



26.05 19:36:10 [Multicraft] Received start command 26.05 19:36:10 [Multicraft] Loading server properties 26.05 19:36:10 [Multicraft] Starting server! 26.05 19:36:10 [Multicraft] Loaded config for "Genisys Build 405 0.14.3" 26.05 19:36:10 [Multicraft] Failed to write to PID file: [Errno 28] No space left on device 26.05 19:36:10 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 32001 26.05 19:36:10 [Server] INFO Warning: require_once(phar:///jar/versions/Genisys/Genisys405.phar/src/pocketmine/PocketMine.php): failed to open stream: phar error: internal corruption of phar "/jar/versions/Genisys/Genisys405.phar" (actual filesize mismatch on file "src/pocketmine/PocketMine.php") in /jar/versions/Genisys/Genisys405.phar on line 1 26.05 19:36:10 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///jar/versions/Genisys/Genisys405.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /jar/versions/Genisys/Genisys405.phar on line 1 26.05 19:36:10 [Multicraft] Server shut down (starting) 26.05 19:36:10 [Multicraft] Restarting crashed server in 5 seconds 26.05 19:36:10 [Multicraft] Looks like a crash, check the server console. Return value: 255 26.05 19:36:10 [Multicraft] Server stopped

**Comment by mote166** [comment]
Tell me if you know a way to fix this please .

**Comment by flaxues** [comment]
phar error: internal corruption of phar

**Comment by flaxues** [comment]
You tried to re-download the .phar?

**Comment by mote166** [comment]
No i didn't

**Comment by PeratX** [comment]
Broken phar, redownload it.

**Comment by mote166** [comment]
But how ?

**Comment by gaoyichuan** [comment]
.....Delete your existing phar and download it again.
