### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by NikeboyHU** [iTXTech/Genisys#1056]
#### Issue description

Syntax error
#### Steps to reproduce the issue

Server crash
#### OS and versions

* Genisys: latest released
* PHP: 7.0.4
* OS: Ubuntu Linux 16.04 LTS (+Multicraft)

#### Crashdump, backtrace or other files
```
Paste here
```
If server close crashing in plugindisabler.php:
26.05 20:26:50 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected identifier (T_STRING), expecting variable (T_VARIABLE)" (EXCEPTION) in "/src/pocketmine/event/plugin/PluginDisableEvent" at line 40

**Comment by andris155** [comment]
Replace server file if server stopped.
Genisys: latest released = invaild issue.
