### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by flash586** [iTXTech/Genisys#106]
This repository not worked (jenkins)

**Comment by CrayonDing** [comment]
I can use it..It works

**Comment by flash586** [comment]
This work? http://jenkins.mcper.cn:8181/job/iTX-Genisys/

**Comment by CrayonDing** [comment]
No.We changed the domain name. http://mcper.cn:8080/job/Genisys/.

**Comment by flash586** [comment]
When been stable build?

**Comment by happy163** [comment]
We are adding a lot of new features, we will launch a stable build as soon as possible.

**Comment by 573834746** [comment]
不是php7就没法使用它了对么T_T

**Comment by 573834746** [comment]
我的手机没有授权不可以将它升级为php7怎么办。。。

**Comment by xpyctum** [comment]
@573834746 Write on english, please..

**Comment by CrayonDing** [comment]
@573834746 PHP7与授权无关。然而，我不清楚现在PHP7是否能在手机上用

**Comment by PeratX** [comment]
@573834746 PHP7 can work on arm devices. You can compile it by yourself(we don't have much time) and remember to use cross compile.

**Comment by 573834746** [comment]
@CrayonDing 不授权不能更改系统文件，而php7的文件不就是要放进手机根目录那啥啥啥的么
