### ISSUE TITLE
PlayerCommandPreProcessEvent error

### ISSUE THREAD

**Issue by ankitmaharjan252** [iTXTech/Genisys#1060]
#### Issue description

I was creating a plugin to ban commands and i used PlayerCommandPreProcessEvent and it showed me
https://gyazo.com/07e06169f63cc9cbb5d3cf160e000f07

#### OS and versions

* Genisys: 416
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by jojoe77777** [comment]
PlayerCommandPreprocessEvent not PlayerCommandPreProcessEvent

**Comment by ishitatsuyuki** [comment]
```
PlayerCommandPreProcessEvent
                ^
ERROR: wrong spell
```

**Comment by ankitmaharjan252** [comment]
Thanks it worked
