### ISSUE TITLE
The animal species only cow

### ISSUE THREAD

**Issue by hentai-mew** [iTXTech/Genisys#1061]
and zombie.   
Other animals do not implemented yet?

* Genisys: latest(jenkins build:416)
* PHP:7
* OS: Official docker container(iTXTech/docker-env-genisys)

The config file genisys.yml -> ai: enable :true,and sub properties all true.

**Comment by dog194** [comment]
right.  not implemented yet.

**Comment by Bidou0418** [comment]
I noticed same here
cows even spawn in water and deep desert.
Is anyone working on the implementation or its just on the list of things to do?

**Comment by dog194** [comment]
almost all the developers are student. wait for summer holidays

**Comment by Skyladd** [comment]
The mobs were written by a 3rd party. I have a friend working on a new AI as we speak. Just wait

**Comment by Bidou0418** [comment]
cool

**Comment by Bidou0418** [comment]
@Skyladd 
keep me up to date pls
