### ISSUE TITLE
Players can't chat without using /say command

### ISSUE THREAD

**Issue by xXMarlonJrXx** [iTXTech/Genisys#1065]
Players can't chat. When the players chat the Console always display this message:
[Server] Warning: yaml_parse(): scanning error encountered during parsing: found unexpected document indicator (line 7, column 1), context while scanning a quoted scalar (line 6, column 10) in phar:///storage/sdcard1/PocketMine/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 143
[Server] Warning: yaml_parse(): scanning error encountered during parsing: found character that cannot start any token (line 9, column 15), context while scanning for the next token (line 9, column 15) in phar:///storage/sdcard1/PocketMine/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 143
Version:1.1dev416
PHP 7
Android

**Comment by ishitatsuyuki** [comment]
Your config is broken.

**Comment by xXMarlonJrXx** [comment]
I downloaded the Phar from this site

**Comment by ishitatsuyuki** [comment]
So what? Saying again: your configuration is broken.

**Comment by gaoyichuan** [comment]
Remove your config files (*.yml) and than start the server, it will help you generate new config

**Comment by xXMarlonJrXx** [comment]
Thanks
