### ISSUE TITLE
Enhancements: Using a better format

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1067]
It would be amazing if you could switch to using JSON instead of TXT or YAML.
whitelist.txt -> whitelist.json
banned-players.txt -> banned-players.json
banned-ips.txt -> banned-ips.json
ops.txt -> ops.json

It's not a big deal, but it would be kinda good if you did it. Thanks :+1:

**Comment by gaoyichuan** [comment]
@iTXTech/developers Have a talk ablou it

**Comment by Muqsit** [comment]
Nice idea. Is json the fastest reading format?

**Comment by gaoyichuan** [comment]
All the formats have similar performace

**Comment by ishitatsuyuki** [comment]
No sense. It's just increasing the size.
