### ISSUE TITLE
Chunk unload, or item despawn not work?

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1069]
#### Issue description

I write /lagg clear and clear 900+ items (wow)

#### Steps to reproduce the issue

/lagg clear (Clearlag plugin)

#### OS and versions

* Genisys: b416
* PHP: 7.0.2 x64
* OS: Ubuntu 14

#### Crashdump, backtrace or other files
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/15630441/6161a18a-253b-11e6-9be4-1432f35e07c9.PNG)

![image](https://cloud.githubusercontent.com/assets/8324198/15630442/818848a6-253b-11e6-904e-e6914cad42eb.png)

**Comment by FocusedSG** [comment]
Multicraft is for MCPE or MCPC?

**Comment by flaxues** [comment]
@FocusedSG MultiCraft can be used for almost everything :P

**Comment by andris155** [comment]
![13329773_1019249388157869_1832614759_n](https://cloud.githubusercontent.com/assets/8324198/15635406/fc662dfc-25dd-11e6-84c9-b8510abb669f.jpg)

**Comment by Bidou0418** [comment]
plugin issue most likely
deactivate your Genisys.yml mobgenerate.

**Comment by andris155** [comment]
/lagg clear - clear items, exp orbs... (used this)
/lagg killmobs - clear mobs (not used this)

**Comment by Bidou0418** [comment]
I use time commander plugin with clear lag

**Comment by PeratX** [comment]
plugin's problem. I use FCleaner written by @FENGberd

**Comment by Driesboy** [comment]
where you find that plugin?

**Comment by andris155** [comment]
I don't find FCleaner plugin.

**Comment by Driesboy** [comment]
same
