### ISSUE TITLE
Converting .zip to .phar

### ISSUE THREAD

**Issue by FocusedSG** [iTXTech/Genisys#1071]
I converted Genisys.phar to Genisys.zip using an online converter. May I know is there a way to convert it back to Genisys.phar? I uses it to edit something to make a plugin to work. Thanks.

**Comment by dog194** [comment]
No, this is not our work. Plz look for solution throw the website you using. Or redownload a phar

**Comment by dog194** [comment]
Also maybe you can just unpack the zip . and use the code directly .

**Comment by faxard** [comment]
Zróbcie zip to phar
