### ISSUE TITLE
Error "Failed loading", the server to crash.

### ISSUE THREAD

**Issue by FUGAMARU** [iTXTech/Genisys#1072]
#### Issue description

Error "Failed loading", the server to crash.
https://gyazo.com/cb7e7d0c41f3655d4bcd0affffe45348
#### OS and versions

* Genisys:1.1dev(1409 th commit version)
* PHP:php_7.0.3_linux_arm
* OS:Ubuntu 14.04.4 LTS 64bit

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by FUGAMARU** [comment]
[CrashDump_Sun_May_29-22.42.38-JST_2016.zip](https://github.com/iTXTech/Genisys/files/288361/CrashDump_Sun_May_29-22.42.38-JST_2016.zip)

Sorry,I forgot to upload the CrashDump.

**Comment by PeratX** [comment]
如果你会中文可以使用中文交流（从截图上看出）

**Comment by gaoyichuan** [comment]
Edit your php.ini and comment the line like 'extension=opcache.so' out.
