### ISSUE TITLE
Unable to eat Enchanted Golden Apple or Golden Carrot with full hunger or not.

### ISSUE THREAD

**Issue by FocusedSG** [iTXTech/Genisys#1075]
#### Issue description
I tried to eat an Enchanted Golden Apple and a Golden Carrot, but it will just keep munching and not eating them.

#### Steps to reproduce the issue
Get a Enchanted Golden Apple ~~or Golden Carrot~~ and try to eat them with full hunger or not.

#### OS and versions

* Genisys: #416
* PHP: 7
* OS: Hosted on Windows 10, tested using Android and IOS.

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by SuperDude36** [comment]
Same, I have this issue as well.

**Comment by xxFlare** [comment]
Working on a fix. :)

**Comment by TheProest35YT** [comment]
Same here even on Many other Genisys Servers like [ RagingPE ]

**Comment by dktapps** [comment]
Golden Carrots are not supposed to be able to be eaten with full hunger regardless.

**Comment by dktapps** [comment]
Big update coming to the food system shortly which will fix this.
