### ISSUE TITLE
Chest replaced by sand when made to fall above chest

### ISSUE THREAD

**Issue by diamond-gold** [iTXTech/Genisys#1076]
#### Issue description

Chest will be replaced by sand/gravel when sand/gravel is made to land above chest

#### Steps to reproduce the issue
Put a chest, put a sand/gravel 2 blocks above the chest so that the sand/gravel falls on the chest

#### OS and versions

* Genisys: Latest commit 7a8d00e 
* PHP:7
* OS:win 8.1

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by gaoyichuan** [comment]
Confirmed in the latest version

**Comment by flaxues** [comment]
Having this problem too with this people can duplicate their items...
