### ISSUE TITLE
Jenkins Builder has been doing nothing for the last 3 days

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1077]
When looking to update my Genisys today, I noticed that the Jenkins builder hasn't done any builds since 416, despite several commits in the 3 days since. Are you guys aware of this?

**Comment by ishitatsuyuki** [comment]
Wow, you are right. Can you use GitLab CI in the mean time?

**Comment by dktapps** [comment]
sure, no problem

**Comment by gaoyichuan** [comment]
Next time Jenkins has any problem, please directly contact me, don't submit any issue

**Comment by dktapps** [comment]
OK will do
