### ISSUE TITLE
If destroy-block-particle: false blockbreak sound not work.

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1078]
#### Issue description

If destroy-block-particle: false blockbreak sound not work.

#### Steps to reproduce the issue

Set Genisys.yml destroy-block-particle: false

#### OS and versions

* Genisys: b416
* PHP: 7.0.4 x64
* OS: Windows 10

#### Crashdump, backtrace or other files
```
none
```

**Comment by ishitatsuyuki** [comment]
Because sound is technically particle.
