### ISSUE TITLE
Exp orb freezing.

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1079]
#### Issue description

Exp orb freezing

#### Steps to reproduce the issue

Drop exp bottles.

#### OS and versions

* Genisys: b416
* PHP: 7.0.4 x64
* OS: Windows 10

#### Crashdump, backtrace or other files
https://www.youtube.com/watch?v=NydNN244_QU

**Comment by andris155** [comment]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/15656817/35dcc7c6-26ab-11e6-9319-4e45aac3df5f.PNG)

**Comment by Tolo0** [comment]
not sure if this has been fixed yet. but I've had to disable experience on my server becos it makes my server freze. and then I have to reboot the dedicated server.

**Comment by xxFlare** [comment]
Confirmed this. It's a problem when XP despawns but does does not despawn from players screen (hence why you can't pick it up).

**Comment by dktapps** [comment]
Seems to be resolved as of 0.15.0 update. Closing.
