### ISSUE TITLE
simplexml_load_file() error Linux

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1080]
#### Issue description

simplexml_load_file() works perfectly - Windows 10
simplexml_load_file() - not work Linux

#### Steps to reproduce the issue

Start server used simplexml_load_file() plugin

#### OS and versions

* Genisys: Genisys: b416
* PHP: 7.0.4 x64
* OS: Ubuntu 14

#### Crashdump, backtrace or other files
```
29.05 00:00:12 [Server] Server thread/CRITICAL Could not execute task MineMarket\ScheduleTask: Call to undefined function MineMarket\simplexml_load_file()
```

**Comment by PeratX** [comment]
extension error, do not report.
