### ISSUE TITLE
Minecart bugs

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1081]
#### Issue description

Minecart bugs:
minecart-moving-type: 1
minecart-moving-type: 0

#### Steps to reproduce the issue

Place Minecart and ride if minecart-moving-type: 1, or minecart-moving-type: 0.

#### OS and versions

* Genisys: b416
* PHP: 7.0.4 x64
* OS: Windows 10

#### Crashdump, backtrace or other files
https://www.youtube.com/watch?v=ZtyTBxtvMQo

**Comment by PeratX** [comment]
It is not functional yet, already in ToDo List, do not report.

**Comment by Nitrofish** [comment]
I don't see this on the ToDo list in the ReadMe. I have built an extensive mine system with carts and no way to use them. When can we expect carts to work?
