### ISSUE TITLE
Serious error. 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#1083]
new error on console. 

Notice: Undefined offset: 3 in /home/Tolo/server2/src/pocketmine/block/Wood2.php on line 38

Notice: Undefined variable: logger in /home/Tolo/server2/src/pocketmine/network/RakLibInterface.php on line 147
[22:27:19] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to a member function logException() on unknown

Version: Genisys_1.1dev-418.phar

**Comment by Tolo0** [comment]
new error again 

Notice: Undefined offset: 0 in /home/Tolo/server2/src/pocketmine/Player.php on line 3507

Notice: Undefined variable: logger in /home/Tolo/server2/src/pocketmine/network/RakLibInterface.php on line 147
[00:03:32] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to a member function logException() on unknown

**Comment by Tolo0** [comment]
![Uploading Screenshot_20160530-231332.png…]()

**Comment by PeratX** [comment]
if you start a server normally, it will not throw these errors.

**Comment by Tolo0** [comment]
![screenshot_20160530-231332](https://cloud.githubusercontent.com/assets/13458191/15659511/b7c663ba-26c3-11e6-928a-86f9d7ad87f8.png)

**Comment by Tolo0** [comment]
it's not a error from starting the server. it happens like 15 min after

**Comment by Muqsit** [comment]
Ate you modifying genisys?

**Comment by Tolo0** [comment]
nope never
