### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by TheEpicCooldeal** [iTXTech/Genisys#1085]
#### Issue description
You are not able to chat "easily" after updating to 0.14.3 Genisys you can type a message once and then try to type in the chat box, nothing will happen, I've tested it on SinglePlayer and it works just fine. 

#### OS and versions

* Genisys: Genisys 1.1dev-418 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.x alpha (protocol version 70)
* PHP: I took the "bin" folder after installing using the Genisys installer.
* OS: Minecraft Windows 10 Edition Beta

#### Crashdump, backtrace or other files
```
I do not have any files at the moment.
```

**Comment by Muqsit** [comment]
This is NOT a fault with Genisys. This is MC Win 10 Edition's major bug. Once you break a block on your private world or on any server, chat will be disabled. Again, this not only happens on servers, but also on private worlds!

**Comment by SleepSpace9** [comment]
_Hint_: Press **TAB** key when this happens, then chat inputs are possible again.
