### ISSUE TITLE
error on stop server

### ISSUE THREAD

**Issue by K099** [iTXTech/Genisys#1086]
#### Issue description
error on stop server

#### OS and versions

* Genisys: Build #419
* PHP: 7.0.7
* OS: Ubuntu

#### Crashdump, backtrace or other files
![try](https://cloud.githubusercontent.com/assets/19483521/15672923/b8985ff6-275d-11e6-88ed-59fe192b2185.PNG)

**Comment by PeratX** [comment]
Nothing is wrong,just ignore it

**Comment by Muqsit** [comment]
Happens only with PHP 7.0.7
