### ISSUE TITLE
Client IP

### ISSUE THREAD

**Issue by FocusedSG** [iTXTech/Genisys#1087]
#### Issue description
When players joined my server, they will have the same IP Address but different port. May I know is this Genisys's fault or my PC's fault? If it is my PC's fault, may I know how to fix it? Thanks

#### OS and versions

* Genisys: #421
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Closing for insufficient description. Are you behind a proxy?

**Comment by FocusedSG** [comment]
No, I'm using my home network. I just port forwarded my IPv4 IP

**Comment by ishitatsuyuki** [comment]
First, at least provide some part of the IP. Your router may act like a proxy and hide the address.

**Comment by FocusedSG** [comment]
119.74.**.***

**Comment by FocusedSG** [comment]
119.74.23.194

**Comment by FocusedSG** [comment]
Because of this issue, I can't use Alias plugin and some other plugins

**Comment by ishitatsuyuki** [comment]
It depends on your environment. Are the players joining from the same network? Your players' ISP may route all traffic to 1 IP.

**Comment by FocusedSG** [comment]
No, players are joining using other network.

**Comment by FocusedSG** [comment]
jdjdBoyLP [/119.74.23.194:1028] logged out due to client disconnect

**Comment by FocusedSG** [comment]
this is what i meant

**Comment by PeratX** [comment]
Your network's problem. (maybe NAT or proxy)
