### ISSUE TITLE
Raklib crash

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1089]
#### Issue description

Raklib crashed randomly

#### Steps to reproduce the issue

I don't know.

#### OS and versions

* Genisys: b416
* PHP: 7.0.2 x64
* OS: Ubuntu 14

#### Crashdump, backtrace or other files
```
01.06 20:08:17 [Server] INFO Notice: Undefined variable: logger in phar:///Genisys_1.1dev.phar/src/pocketmine/network/RakLibInterface.php on line 147
01.06 20:08:17 [Server] Server thread/CRITICAL [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to a member function logException() on unknown
```

**Comment by lastrolo** [comment]
I saw this too. It was fixed yesterday. 

https://github.com/iTXTech/Genisys/commit/bb6eea8d3c493231a3e801a51af8861d530cb223
