### ISSUE TITLE
php7 for apple computers

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#109]
please add php7 for apple computers

**Comment by CrayonDing** [comment]
But all of us don't have apple computers.And why don't you google it.

**Comment by CrayonDing** [comment]
https://www.google.com.hk/?gws_rd=ssl#safe=strict&q=php7+mac

**Comment by Driesboy** [comment]
what

**Comment by CrayonDing** [comment]
Yes.The main developers are students,we are not rich to buy a apple computer.In China,apple computers are very very expensive.

**Comment by Driesboy** [comment]
/Users/Ronny/Desktop/dries/Lobby 2/start.sh: line 54: /Users/Ronny/Desktop/dries/Lobby 2/bin/php5/bin/php: cannot execute binary file
/Users/Ronny/Desktop/dries/Lobby 2/start.sh: line 54: /Users/Ronny/Desktop/dries/Lobby 2/bin/php5/bin/php: Undefined error: 0

**Comment by CrayonDing** [comment]
Did you change the start.sh?

**Comment by Driesboy** [comment]
no

**Comment by Driesboy** [comment]
i have rename the php7 to php5

**Comment by Driesboy** [comment]
/Users/Ronny/Desktop/dries/Lobby 2/start.sh: line 72: /Users/Ronny/Desktop/dries/Lobby 2/bin/php5/bin/php: cannot execute binary file
/Users/Ronny/Desktop/dries/Lobby 2/start.sh: line 72: /Users/Ronny/Desktop/dries/Lobby 2/bin/php5/bin/php: Undefined error: 0

**Comment by Driesboy** [comment]
thx

**Comment by Driesboy** [comment]
i will help you to fix this

**Comment by CrayonDing** [comment]
Thx.

**Comment by Driesboy** [comment]
can i help to support php 5 and you and the rest do php7

**Comment by Driesboy** [comment]
ps: i use the php binary from itxtech Genisys-php

**Comment by Driesboy** [comment]
please help

**Comment by PeratX** [comment]
https://github.com/PeratX/php-build-scripts Try it

**Comment by GalvinGao** [comment]
If you're question is answered or have a solution please reply so the issue can close or not. Thanks.

@Driesboy

**Comment by markkrueg** [comment]
I installed Genisys on Mac OS X El Capitan (10.11.2) using the following procedure:

1) Install Xcode so that you have compilers (This can be done from the Apple app store).
2) Install needed support binaries using brew. 
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install wget install autoconf automake libtool
```
3) Make a folder where you would like to install Genisys. In Terminal, cd to that folder.
4) Compile PHP7 using PeratX script. 
```
wget https://raw.githubusercontent.com/PeratX/php-build-scripts/php7/compile.sh
```
5) Download current Genisys (confirm link to current Genisys by looking at http://mcper.cn:8080/job/Genisys/ )
```
wget http://mcper.cn:8080/job/Genisys/lastSuccessfulBuild/artifact/releases/Genisys_1.0dev-36.phar
```
6) Download current start script and start Genisys
```
wget https://raw.githubusercontent.com/iTXTech/Genisys/master/start.sh
bash ./start.sh
```
7) Follow the instructions to choose your language and Genisys will start. Note that it often segfaults. Just run it again using:
```
bash ./start.sh
```
You may have to do this 5 or 6 times before it stays running. This is the same on Linux; it's just something we have to live with until the PHP7 branch becomes more stable.

**Comment by Driesboy** [comment]
wow

**Comment by Driesboy** [comment]
can you take photo's

**Comment by Driesboy** [comment]
wget: not found

**Comment by flaxues** [comment]
http://osxdaily.com/2012/05/22/install-wget-mac-os-x/

**Comment by Driesboy** [comment]
thx

**Comment by markkrueg** [comment]
If wget is not found, you missed step 2. Repeat step 2 and try again. If step 2 is failing; re-do step 1.

**Comment by markkrueg** [comment]
I have simplified my instructions; and will even be adding a screenshot shortly (if github lets me). There was a typo in step 2 (which is now step 1). That may be why your wget didn't install. Try again.

**Comment by Driesboy** [comment]
Thx

**Comment by Driesboy** [comment]
PHP downloading 7.0

**Comment by markkrueg** [comment]
Edited my post again. Removed libtool from "brew install" because apple already includes it as part of the dev tools.

**Comment by Driesboy** [comment]
working :+1:

**Comment by markkrueg** [comment]
@Driesboy Awesome! 

Any way we could open up the github wiki for Genisys so I could make a page for this?

**Comment by Driesboy** [comment]
yes

**Comment by BookWorm29** [comment]
Whenever I try to do the command
wget http://mcper.cn:8080/job/Genisys/lastSuccessfulBuild/artifact/releases/Genisys_1.0dev-36.phar

it gives me --2016-04-29 10:42:44--  (try: 5)  http://mcper.cn:8080/job/Genisys/lastSuccessfulBuild/artifact/releases/Genisys_1.0dev-36.phar
Connecting to mcper.cn|183.60.111.91|:8080... failed: Operation timed out.
Retrying.

--2016-04-29 10:44:04--  (try: 6)  http://mcper.cn:8080/job/Genisys/lastSuccessfulBuild/artifact/releases/Genisys_1.0dev-36.phar
Connecting to mcper.cn|183.60.111.91|:8080... failed: Operation timed out.
Retrying.
 etc over and over. help please?

**Comment by markkrueg** [comment]
@BookWorm29 That link is outdated. I have updated the instructions with the new link.

Genisys admins: May I have access to the Wiki so that I can add installation pages for each OS?

**Comment by ishitatsuyuki** [comment]
@markkrueg We already have installer for Windows and Docker tutorial for OS X and Linux. No need.

**Comment by BookWorm29** [comment]
@markkrueg It still doesn't work... Did you accidentally copy down the wrong link?

**Comment by markkrueg** [comment]
@BookWorm29 Thanks; try again now.

**Comment by BookWorm29** [comment]
@markkrueg I hate to be a constant downer... But it still isn't working. Maybe it's just my computer

**Comment by markkrueg** [comment]
Works for me; maybe mcper.cn is blocked for you?

<img width="400" alt="screen shot 2016-05-09 at 1 21 55 pm" src="https://cloud.githubusercontent.com/assets/12489897/15126912/3d0a1e4a-15e9-11e6-8277-247c26700121.png">

**Comment by BookWorm29** [comment]
Hm.... Maybe... But why would that be?

**Comment by gaoyichuan** [comment]
Oops.. Maybe that's fault of GFW..

**Comment by gaoyichuan** [comment]
Since jenkins server is inside China mainland

**Comment by gaoyichuan** [comment]
Try https://jenkins.mcper.cn/

**Comment by BookWorm29** [comment]
Yeah I can't connect... Is there any other link that would work?

**Comment by Muqsit** [comment]
Try using a VPN?

**Comment by BookWorm29** [comment]
Yeah, but where would I find a free vpn into China...

**Comment by dog194** [comment]
find any free vpn that can connect to jenkins server. No only in China. Japan? USA ?
