### ISSUE TITLE
Fire Bug

### ISSUE THREAD

**Issue by MrIrishMiner** [iTXTech/Genisys#1091]
#### Issue description

When you try to "break" the fire, even though it doesn't show up, you can walk through it and still get burnt. 
#### Steps to reproduce the issue

Light a flint and steel on the ground, break the fire, walk through it.
#### OS and versions

* Genisys:1.1dev-a685f20
* PHP: 7.0.3
* OS: Windows 7 Professional

#### Crashdump, backtrace or other files
```
```

**Comment by dog194** [comment]
break by hand?
There is a known bug that fire block cannot be break by hand.

**Comment by MrIrishMiner** [comment]
I fixed it using PlayerInteractEvent and then getting the block above it. But yes this is a bug.

**Comment by MrIrishMiner** [comment]
I did mean break by hand :D

**Comment by PeratX** [comment]
No way to fix

**Comment by MrIrishMiner** [comment]
Could I make a pull request on how I fixed it?

**Comment by dog194** [comment]
Yes, you can. But if is not an appropriate way. Maybe will not be accepted

**Comment by IrishUHC** [comment]
The way I did it was with PlayerInteractEvent, I could find another way, but we'll see.
