### ISSUE TITLE
0.15.0

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#1094]
Changelog :
![ckai2wmuuaevuds](https://cloud.githubusercontent.com/assets/15629214/15769422/8a015396-298d-11e6-9575-1e999c8ac66f.jpg)

show u guys wht changes :)

**Comment by EpicSteve33** [comment]
Also a version and protocol bump should happen soon so 0.15.0 players can join

**Comment by ImagicalGamer** [comment]
"Yay" more updates

**Comment by MrDoni98** [comment]
0.15.0 CURRENT_PROTOCOL=81

**Comment by ishitatsuyuki** [comment]
That's less important than the tons of protocol changes.

**Comment by Pub4Game** [comment]
In 0.15.0 a lot of changes in the protocols. Almost all protocols have been changed.

**Comment by lolcraftboy** [comment]
@dog194  its full released

**Comment by dktapps** [comment]
@lolcraftboy I think we got the point.

**Comment by lolcraftboy** [comment]
o oke

**Comment by Taki21** [comment]
Protocol is not 81 (what i heard) but 90 something...

**Comment by Driesboy** [comment]
> why?

**Comment by ByZikenPE** [comment]
Hope it Will be soon :( i was 60-100 player on My server i have 20 now :(

**Comment by EnderKenji** [comment]
Please update asap :3

**Comment by daniktheboss** [comment]
Imagicalmine seemed to fix the problem of not able to join... I didn't check it yet but they said they did

**Comment by dktapps** [comment]
The official ImagicalMine project is dead, so I find that unlikely. And the Inactive-To-Reactive fork ... well, remotevase doesn't have a clue what he/she is doing with that code.

**Comment by daniktheboss** [comment]
Well he is saying it works???

**Comment by dktapps** [comment]
That's because he copied code from Steadfast, which will cause issues if it works at all. It's not as simple as guessing the magic number.

**Comment by daniktheboss** [comment]
Ohhh I see. Is genisys close to finishing 1.2?

**Comment by dktapps** [comment]
I can't comment on that one. Plus 0.15.1 beta has just started.

**Comment by daniktheboss** [comment]
Oh ok... and the imagicalmine 0.15 version still does not connect. Lol

**Comment by daniktheboss** [comment]
0.15.1 is out on the Google play! I think it's beta

**Comment by Muqsit** [comment]
LBSG 0.15 keeps crashing too so it's no use copying from SF2

**Comment by daniktheboss** [comment]
True... so it's better to write a new one from scratch? Then using some stuff from sf2?

**Comment by daniktheboss** [comment]
Well, imagicalmine is really close to making it official! They got the protocol now.

**Comment by gaoyichuan** [comment]
Wait for us.. We have the 0.15.0 branch and we keep developing..

**Comment by daniktheboss** [comment]
Ok!! Great! Glad to hear that!

**Comment by daniktheboss** [comment]
Update: imagicalmine got server to recognize that people are joining and shows player joined in world... but logs me off due to timeout

**Comment by KairusDarkSeeker** [comment]
lmao just Copy the source code from https://github.com/Hydreon/Steadfast2 and Genisys will work on 0.15.0 :P

**Comment by KairusDarkSeeker** [comment]
and ya just change the branch to mcpe15 and u will see Steadfast's minecraft aversion

**Comment by atTheDisco** [comment]
0.15.1 alpha build 1 is out :(

**Comment by dktapps** [comment]
Can people not read? We're already working on 0.15. And please *read* earlier comments before posting your own.

**Comment by SurvivalHive** [comment]
i hate this spamming so much... i can understand if some developers stop working because of so much stupid questions....  " 0.15 is out please fix " shit... let the guys do this hard work and wait like all the others -.- but stop spamming shit...

**Comment by dktapps** [comment]
@SurvivalHive is right. The spam doesn't help us in the slightest. Don't forget that the devs have many other commitments, just like any other people.

**Comment by CLiu13** [comment]
I have a branch that I am currently testing for 0.15.0. Eveyrthing works fine except that the player logs out due to timeout.

**Comment by Pub4Game** [comment]
PM updated to 0.15.0

**Comment by CLiu13** [comment]
Yes, I am implementing their fixes into Genisys.

**Comment by CLiu13** [comment]
My branch works, just tested it out. There is an error message that I am currently working on fixing, but it does not appear to affect anything. I will be submitting a PR very soon.

**Comment by CrayonDing** [comment]
Please try the newest build.I have merged from PM.

**Comment by xxFlare** [comment]
@CrayonDing Make $this->protocol = $packet->protocol1;

$this->protocol = $packet->protocol;

in player.php

**Comment by daniktheboss** [comment]
Can't join... newest build

**Comment by CrayonDing** [comment]
Done.Thanks

**Comment by xxFlare** [comment]
@CrayonDing Something is wrong with packets. The server is handling everything right but a packet seems not-changed. Hmmm.

**Comment by ZizzyZizzy** [comment]
Login timeout with build #466 changes manually patched in Player.php.

**SteadFast does not work correctly either.** While you can join, breaking blocks doesn't create a drop and there are many other bugs.

**Comment by xxFlare** [comment]
@ZizzyZizzy Steadfast works, they designed it to be fast - so they disabled that.

**Comment by Troctor** [comment]
also note there are leads on every player, and player movement doesn't update. @CrayonDing

**Comment by daniktheboss** [comment]
Yea movement and leads and many worlds

**Comment by ZizzyZizzy** [comment]
@xxFlare Did not know that, thanks. ..Genisys fanboy.

**Comment by daniktheboss** [comment]
Are u going to fix the bugs tomorow? Please work on the multiworld support! That's the main thing that every server needs!

**Comment by gaoyichuan** [comment]
@daniktheboss Mulitworld support is the thing that a plugin should do.

**Comment by daniktheboss** [comment]
No you do /world "world" and you crash .. that's a plugin error?

**Comment by gaoyichuan** [comment]
@daniktheboss You think /world is Genisys' command? Check src/pocketmine/command/SimpleCommandMap.php and you will find yourself an idiot.

**Comment by daniktheboss** [comment]
Oh lol ... sorry my bad haha.. ok I will try to update it...

**Comment by EnderKenji** [comment]
Seems ImagicalMine about to finish the fixes for 0.15.0 ._.

**Comment by JUSTaMod** [comment]
Who gives a shit about what ImagicalMine is doing? This chat is for the iTXTech team and their work on Genisys, if you wanna go congratulate IMine leave this chat.

**Comment by SuperDude36** [comment]
Where download for 0.15.0 Genisys?

**Comment by dktapps** [comment]
@JUSTaMod I couldn't have said it better myself. Very well said.

**Comment by gaoyichuan** [comment]
@SuperDude36 https://jenkins.mcper.cn

**Comment by KairusDarkSeeker** [comment]
:/ y cant i hit players??
