### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by xHFx** [iTXTech/Genisys#1098]
#### Issue description

segmentation fault after ./start.sh
#### OS and versions

* Genisys: 1,1
* PHP: php-7
* OS: Ubuntu 14.04 64 bit

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
This is a PHP extension bug. Search closed issues first before opening a new one.

**Comment by xHFx** [comment]
So whats the fix ?

**Comment by ishitatsuyuki** [comment]
So you're such a stupid guy not checking closed issue?

**Comment by xHFx** [comment]
I checked closed tickets didnt see any solutions !

**Comment by ishitatsuyuki** [comment]
https://github.com/iTXTech/Genisys/issues/974#issuecomment-219882197

**Comment by xHFx** [comment]
Im sorry :( but dont have to be a asshole never know who your talking to never forget that pussy
