### ISSUE TITLE
Summon DataTags

### ISSUE THREAD

**Issue by JUSTaMod** [iTXTech/Genisys#1099]
Not sure if it's just me, but I can't add any DataTags using the summon command, it will just summon the original entity. If the DatsTags are not implemented yet, please add them.

**Comment by ishitatsuyuki** [comment]
Yes, this is not implemented.

**Comment by JUSTaMod** [comment]
Do you have plans on adding them in the future? Summon tags would be great.

**Comment by gaoyichuan** [comment]
Not implemented. Maybe in the future

**Comment by PeratX** [comment]
Maybe implement the metadata

**Comment by JUSTaMod** [comment]
:( you didn't even add them yet. Why u gotta close. You'll forget now. Mark my words.

**Comment by PeratX** [comment]
It is working now. Try /summon Arrow ~ ~ ~ {Potion:8}

**Comment by JUSTaMod** [comment]
oh. i missed the commit over vacation. Thanks. lol.
