### ISSUE TITLE
Crops Wont Grow

### ISSUE THREAD

**Issue by yungtechboy1** [iTXTech/Genisys#11]

**Comment by astersx** [comment]
Use bone meal or just wait =))

**Comment by PeratX** [comment]
@yungtechboy1 You can turn it on in pocketmine.yml

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 2
 #Radius of chunks around a player to tick
 tick-radius: 3
 light-updates: false
 clear-tick-list: true

**Comment by yungtechboy1** [comment]
dose light-updates turn it on?

**Comment by yungtechboy1** [comment]
It was per-tick: 20....

**Comment by PeratX** [comment]
@yungtechboy1 Well,2 is enough.
