### ISSUE TITLE
Docker Install Issues !

### ISSUE THREAD

**Issue by xHFx** [iTXTech/Genisys#1100]
#### Issue description

root@s89299:~/server# docker run -it --name genisys-production -p 19132:19132/udp -v </root/server/>:/srv/genisys/genisys.phar itxtech/docker-env-genisys
bash: :/srv/genisys/genisys.phar: No such file or directory

#### OS and versions

* Genisys: 1.1dev-7ef485f
* PHP: 7.0
* OS: Ubuntu 14.04 64 bit

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
So you're stupid enough to not insert the absolute path to the phar right?

**Comment by xHFx** [comment]
What ... ? && What ?

**Comment by ishitatsuyuki** [comment]
docker run -it --name genisys-production -p 19132:19132/udp -v **<absolute path to genisys.phar>**:/srv/genisys/genisys.phar itxtech/docker-env-genisys

**Comment by ishitatsuyuki** [comment]
You have to remove the < >

**Comment by gaoyichuan** [comment]
Also you have to download a phar and put it inside the path
