### ISSUE TITLE
Water bucket(flowing water) or Lava Bucket, takes forever to dissipate.

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#1104]
Any chance someone can fix this.
Would be nice if removing the initial water or lava source block could quickly dissipate the flowing water or lava...
I often need to reload my map to correct this problem. 
The worst is when is when players deliberately or accidentally place a bucket of water or lava over a high place and it spreads and multiplies sideways and downwards. (example a mountain top).
-Perhaps a temp. solution would be if only still water and lava came out of a bucket... 
-Perhaps limiting the spread to 5-6 blocks from initial block could also help...

**Comment by dog194** [comment]
Maybe you should use plugins to disable flowing water.

**Comment by Bidou0418** [comment]
@dog194 
Can you please keep the issue open.
I have used world protect to ban the bucket of water and lava but then that creates other issues...
(cant grow crops, cant create lakes or rivers, or lava lakes...)
I encourage players to grow and sell their crops and/or build small water sources or lava sources for various reasons.,,

**Comment by ishitatsuyuki** [comment]
No, WorldEdit should work.

**Comment by Bidou0418** [comment]
hum, let me check 
@ishitatsuyuki 
whos version is up to date? LDX?

**Comment by dog194** [comment]
A known plugin can solve all problems (But i forgot the name). The plugin disables flowing water and lava. So players can use buckets and put water.

**Comment by Bidou0418** [comment]
@dog194 
is it worldedit like ishitatsuyuki wrote?
