### ISSUE TITLE
0.15.0 beta branch problems

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1105]
#### Issue description
I cannot join a server running a Genisys phar from the 0.15 branch

#### Steps to reproduce the issue
Update server to 1.2dev-95c3663
Attempt to join server on 0.15.0 alpha build 1

#### OS and versions
* Genisys:  1.2dev-95c3663 (downloaded from GitLab-CI)
* PHP: 7.0.4
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Warning: unpack(): Type n: not enough input, need 2, have 0 in phar://C:/Users/Admin/Downloads/Genisys/Genisys_1.2dev-95c3663.phar/src/pocketmine/utils/Binary.php on line 262

Warning: unpack(): Type n: not enough input, need 2, have 0 in phar://C:/Users/Admin/Downloads/Genisys/Genisys_1.2dev-95c3663.phar/src/pocketmine/utils/Binary.php on line 262
[12:45:08] [Server thread/INFO]: [/192.168.1.65:19132] logged out due to Outdated server!
```

**Comment by ishitatsuyuki** [comment]
Idiot. Topic branch is not for production use.

**Comment by dktapps** [comment]
@ishitatsuyuki calm down, I'm aware of that, I'm simply testing your developments on a private server.

**Comment by ishitatsuyuki** [comment]
For code review, we use PRs. Please don't open any issue for incomplete codes.

**Comment by RobertoGamerYT2** [comment]
When updated Genisys Official Minecraft 0.15.0 .
