### ISSUE TITLE
Fill Command

### ISSUE THREAD

**Issue by Nitrofish** [iTXTech/Genisys#1107]
#### Issue description
Fill command does not seem to work

#### Steps to reproduce the issue
Tried to use 
/fill -17 3 36 -14 5 32 Sand

It wrote on the device screen that it worked and I got the following in my console: 2016-06-04 [08:52:31] [Server thread/INFO]: **[DamageInc] Nitrofish:  /fill -17 3 36 -14 5 32 Sand

but nothing actually happened or got filled. Now no matter what xyz I use, it just returns the following: 
usage: /fill < x1 > < y1 > < z1 > < x2 > < y2 > < z2 > < TileName > [ DataValue ] [ OldBloxkHandling ] [ DataTag ]

Even if I use the same XYZ that it said worked with Dirt, or Stone, etc.

#### OS and versions
* Genisys: 1.1dev-431 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.x alpha (protocol version 70)
* PHP: 7.0.4
* OS: Windows 10 Pro

Plugins Running: 
Plugins (14): DevTools v1.10.0, EssentialsPE v2.0.0, FactionsPro v1.3.2, iProtector v3.1b, ManyWorlds v2.1.0, MassiveEconomy v1.0 R3, PocketDockConsole v0.0.14, PurePerms v1.3.7, SexyMOTD v1.0.0, SignShop v2.0.0build3, SimpleAuth v1.7.2, SimpleAuthHelper v2.0.2b, SignWarp v1.6.0, SimpleWarp v2.1.1

**Comment by gaoyichuan** [comment]
Yes, it doesn't work. Will fix soon

**Comment by JUSTaMod** [comment]
Is the cave command working yet too? I haven't checked recently.

**Comment by Nitrofish** [comment]
I think it mentions somewhere that the cave command has not been implemented yet @JUSTaMod

**Comment by FocusedSG** [comment]
cave command has been added and it is working perfectly, I've tried. Do '/help cave' to see the usage

**Comment by Nitrofish** [comment]
When i type that it returns the following: ommands.gave.usage so there is a c missing from the permission it looks like. Any idea how to fix that?

**Comment by gaoyichuan** [comment]
@Nitrofish Your version is outdated. It's fixed long long ago

**Comment by ImagicalGamer** [comment]
@gaoyichuan Nope not fixed when running in-game, if I run the command on console it returns the help menu for /cave, if I run it in-game it returns ommands.cave.usage (Using latest GitLab Build)

**Comment by Nitrofish** [comment]
Same here. I am using latest build. "Genisys version 1.1dev-431 "Ikaros" (API 2.0.0)"

**Comment by Nitrofish** [comment]
Could I get an idea when /fill might be fixed please?

**Comment by mad-hon** [comment]
I have a fix, hoping to submit a pull request soon

**Comment by Nitrofish** [comment]
That's great news @mad-hon I desperately need this functionality. Thanks for the effort.

**Comment by PeratX** [comment]
Fixed
