### ISSUE TITLE
Hopper

### ISSUE THREAD

**Issue by ImagicalGamer** [iTXTech/Genisys#1108]
Why does ImagicalMine have hoppers and Genisys doesn't? Those would be a cool feature

**Comment by dog194** [comment]
Because they are ImagicalMine and we are Genisys.

**Comment by ImagicalGamer** [comment]
Can they be added to Genisys?

**Comment by ImagicalGamer** [comment]
EDIT: I know it's possible, but can someone?

**Comment by daniktheboss** [comment]
Yea that would be aweasome!

**Comment by xHFx** [comment]
Please

**Comment by xHFx** [comment]
https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/block/Hopper.php

**Comment by gaoyichuan** [comment]
No, our redstone system is different from IM

**Comment by Muqsit** [comment]
ImagicalMine hoppers don't work. I tested it.

**Comment by PeratX** [comment]
Included in Redstone rewrite. #854
