### ISSUE TITLE
help me plz with the eror

### ISSUE THREAD

**Issue by lolcraftboy14** [iTXTech/Genisys#1109]
#### OS and versions

* Genisys: 431
* PHP:  7.0.4
* OS: windows 7

#### Crashdump, backtrace or other files
```
Paste here
```
Warning: require_once(phar://C:\Users\Dell\.VirtualBox\Desktop\genisys\genisys.phar/src/pocketmine/PocketMine.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "C:/Users/Dell/.VirtualBox/Desktop/genisys/genisys.phar" file "src/pocketmine/PocketMine.php" in C:\Users\Dell\.VirtualBox\Desktop\genisys\genisys.phar on line 1
Fatal error: require_once(): Failed opening required 'phar://C:\Users\Dell\.VirtualBox\Desktop\genisys\genisys.phar/src/pocketmine/PocketMine.php' (include_path='.;.\ext') in C:\Users\Dell\.VirtualBox\Desktop\genisys\genisys.phar on line 1
bin\php\php.exe: Exit 255

y cant get it to fix it can you help plz

**Comment by ishitatsuyuki** [comment]
Stop spamming like this. Use Gitter for questions instead. Next time you do this you will get blocked.

**Comment by lolcraftboy14** [comment]
@ishitatsuyuki why y dont spam???????????

**Comment by gaoyichuan** [comment]
It's very clear that your phar is broken
