### ISSUE TITLE
If lot create sign, they will be empty.

### ISSUE THREAD

**Issue by Pub4Game** [iTXTech/Genisys#1110]
#### Issue description

I think everything is clear from the title.
#### Steps to reproduce the issue
Create more 400 sign.

#### OS and versions

* Genisys: Jenkins [ #431](https://jenkins.mcper.cn/job/Genisys-master/431/)
* PHP: 7
* OS: Windows 10

**Comment by gaoyichuan** [comment]
It's perfectly unclear
