### ISSUE TITLE
Memeory

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1114]
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes)
File: /src/pocketmine/utils/Config
Line: 132
Type: E_ERROR

Code:
[123] 				$extension = explode(".", basename($this->file));
[124] 				$extension = strtolower(trim(array_pop($extension)));
[125] 				if(isset(Config::$formats[$extension])){
[126] 					$this->type = Config::$formats[$extension];
[127] 				}else{

**Comment by MCPEPluginer16** [comment]
How fix it

**Comment by Skyladd** [comment]
There are memory leaks. Simply restart the server. Mob AI has a big part in the issue, try disabling it in the config file

**Comment by MCPEPluginer16** [comment]
Restart and dont work

**Comment by flaxues** [comment]
What is your memory limit in pocketmine.yml? how much ram does your server/host have?

**Comment by MCPEPluginer16** [comment]
1024 Memory

**Comment by flaxues** [comment]
How much ram does your hosting have?

**Comment by NML32** [comment]
I've been getting lots of out of memory on my server too.

**Comment by gaoyichuan** [comment]
Your memory is full. Restart your server or increase your memory linit

**Comment by Bidou0418** [comment]
install Restartme and select to restart when ram goes over 1024?

**Comment by MCPEPluginer16** [comment]
Update my ram to 1024 but agin restart

**Comment by flaxues** [comment]
@Bidou0418 If you do this your server will just restart if it reaches 1024mb ram so it has no point to use it...

**Comment by Bidou0418** [comment]
@flaxues 
i've got global soft memory set at 2000 and main thread soft memoty set at 2000 with actual 2048ram.
if for some reason i go over, restartme ensures my server is reset and restarted, preventing down time.
restartme also restarts my server 4 times per day with time commander.
seems to work well so far.
Do you recommend a different setting?
