### ISSUE TITLE
Cave Command

### ISSUE THREAD

**Issue by Nitrofish** [iTXTech/Genisys#1115]
#### Issue description
When issuing the /cave command a cave is not genrated and the following is displayed on the device screen: Usage: ommand.cave.usage

#### Steps to reproduce the issue
Type /cave in game

#### OS and versions
* Genisys: 1.1dev-434
* PHP: 7
* OS: Windows 10 Pro

#### Crashdump, backtrace or other files
```
Notice: Undefined offset: 0 in phar://C:/Users/Admin/Documents/GenisysPM/Genisys.phar/src/pocketmine/command/defaults/CaveCommand.php on line 38
```

**Comment by maxicusj** [comment]
in which build is it fixed? I tried out all of your build branches -- in all of them I am still getting the same error.
