### ISSUE TITLE
Nether portal problem

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#1118]
Portal does not always get created in the nether.
Player often appears in the air or in lava when using portal to go to the nether.
Player often gets stuck in the portal and cant move
It may work once in a while but its very rare...

Genisys 435

**Comment by PeratX** [comment]
Auto generate nether door has not implemented yet.

**Comment by Bidou0418** [comment]
it did generate at first.
problem is after you delete the nether once, it no longer generates.
anyway, nothing having to do with portals works properly

**Comment by gaoyichuan** [comment]
No,.we don't have the code to generate it
