### ISSUE TITLE
Plugswork Partnership [NOT AN ISSUE]

### ISSUE THREAD

**Issue by deotern** [iTXTech/Genisys#1122]
First, sorry for mis-using this Issue Tracker..
But I've found no other way to contact u guys...

To, iTX or Genisys Team Members,
I'm here to request partnership between Genisys (iTX) and Plugswork
Okay, Plugswork is actually a plugin, a powerful and unified plugin with Graphical Control Panel. With Plugswork, users are not longer needed to edit config.yml, Plugswork uses a Graphical Control Panel instead of config.yml files
See more details:
https://plugswork.com
https://github.com/deotern/Plugswork

I coded Plugswork to help the community, so I hope u guys can accept this partnership request to promote Plugswork to the world :) 
By partnership, i will start code a new version of Plugswork to adapt the API in Genisys, makes Plugswork Plugin customized available for Genisys :) This will definitely makes Genisys even better
All I need you to do is, recognize Plugswork as an official plugin of Genisys. Thats all :)

Last, i truly hope iTX or Genisys team can response and accept this partnership :)
Thank you

**Comment by ishitatsuyuki** [comment]
You are free to use the code. My opinion is to have no explicit partnership.

**Comment by deotern** [comment]
@ishitatsuyuki 
Using what code? LOL :P Plugswork is coded on my own without stealing anybody's code... :P Im requesting partnership just to promote Plugswork, not to copy the code or something xD :smile:

**Comment by ishitatsuyuki** [comment]
No, we don't promote any other projects: open source projects don't do such a thing.
Shut up if you just want a free ad.

**Comment by PeratX** [comment]
@deotern Sorry for his impolite. You can code your project as you wish. If you need any help, you can contact us via gitter.
