### ISSUE TITLE
RakLibInterface crash

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#1123]
#### Issue description

Raklib crashes when a error show up on the console

#### Steps to reproduce the issue

I don't know yet

#### OS and versions

* Genisys: Build 435
* PHP: 7
* OS: Debian

#### Crashdump, backtrace or other files
```
Notice: Undefined offset: 3 in phar:///home/matthew/daemon/Genisys.phar/src/pocketmine/block/Wood2.php on line 38
[21:23:38] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\block\Wood2::getName() must be of the type string, null returned" (EXCEPTION) in "/src/pocketmine/block/Wood2" at line 38
[21:23:38] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Return value of pocketmine\block\Wood2::getName() must be of the type string, null returned
```

**Comment by Muqsit** [comment]
Wood2::getName() is type string. You must have modified Wood2?

**Comment by flaxues** [comment]
I didn't modify anything

**Comment by corytortoise** [comment]
I have the same error somewhat, the first line is exactly the same, but the second and third are entirely different. I am using the same build of genisys, I believe, but I am on Ubuntu.
![screenshot_2016-06-11-20-00-31-1](https://cloud.githubusercontent.com/assets/18385576/15989690/2fee5104-3033-11e6-8dbf-c3e25a7f47b8.png)

**Comment by ishitatsuyuki** [comment]
@corytortoise you're outdated for sure.

**Comment by GlitchPlayer** [comment]
He said he has the same build...

**Comment by ishitatsuyuki** [comment]
@Glitch_Player I'm pretty sure he's a noob, since I have fixed that issue already.

**Comment by corytortoise** [comment]
Oops... I'm sorry. I wasn't on the latest build.

**Comment by ishitatsuyuki** [comment]
Your map has been corrupt.
