### ISSUE TITLE
Glitchy toolbar

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#1128]
item selection toolbar is very glitchy since a week or so.
when you select an item it doesnt get selected sometimes and sometimes the selected item toggles from one slot to the other. it even freezes once in a while from continuously toggling from one item to the other.

* Genisys: ver 435
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
Ckeck your NETWORK
