### ISSUE TITLE
Failed loading

### ISSUE THREAD

**Issue by EpicSteve33** [iTXTech/Genisys#113]
epicsteve33@epicsteve-desktop:~/Desktop/Servers/KingdomCraft/1$ ./start.sh
Failed loading /var/lib/jenkins/jobs/PHP-PocketMine-Linux/workspace/compile/linux/32bit/bin/php7/lib/php/extensions/no-debug-zts-20141001/opcache.so:  /var/lib/jenkins/jobs/PHP-PocketMine-Linux/workspace/compile/linux/32bit/bin/php7/lib/php/extensions/no-debug-zts-20141001/opcache.so: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
epicsteve33@epicsteve-desktop:~/Desktop/Servers/KingdomCraft/1$

**Comment by EpicSteve33** [comment]
It's not a question I can't run my server with genisys at all anymore can somebody please help like my server has been down all week I can't get any work done on the server because ever day a new problem keeps happening

**Comment by mixailenko5** [comment]
I fixed this error today
