### ISSUE TITLE
Redstone Lamps don't work, and redstone will not activate on certain blocks

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1135]
#### Issue description

Redstone lamps will not light up, and on some blocks, such as wood or logs, redstone won't activate at all.
#### Steps to reproduce the issue

Place a redstone torch and then some redstone. Works, right? Now do the same on some block such as wood, doesn't work. Also try lighting up a redstone lamp.
#### OS and versions

* Genisys: 1.1dev-ed69af7
* PHP: 7
* OS: Android

#### Crashdump, backtrace or other files
```
http://imgur.com/CZjZdeG
http://imgur.com/oHgJZcQ
```

**Comment by xxFlare** [comment]
Yes. The redstone API is not perfect. It's a work in progress. I'll make a PR request for this soon.

**Comment by robske110** [comment]
api?

**Comment by PeratX** [comment]
News: aabbcc is rewriting Redstone System with full charge system. He has completed RedstoneWire and RedstoneBlock, I think this will update in early July (now he is going to have the final exam!)
