### ISSUE TITLE
Mobs should not use a CallBackTask

### ISSUE THREAD

**Issue by xxFlare** [iTXTech/Genisys#1137]
#### Issue description

Hi, the mob API is fine - That's not what this is about. The problem is CallBackTask should not be used for updating mob movments. In fact, Shoghi wanted to get rid of CallBackTasks.

Maybe we should find a different way to do this like a repeating task.

#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
CallbackTasks will be removed in MobAIs' write.
