### ISSUE TITLE
Hits are too strong

### ISSUE THREAD

**Issue by SavionLegendZzz** [iTXTech/Genisys#1139]
#### Issue description

hits are too strong you can hit people 3 times are they are dead

#### Steps to reproduce the issue

You and 2 players can pvp and both have diamond armor and a diamond sword and you can 3 hit a player and they die

#### OS and versions

* Genisys: Genisys 1.1dev-b15bcc1 "Ikaros" 
* PHP: PHP7
* OS: Linux

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
More detail.

**Comment by SavionLegendZzz** [comment]
Get full diamond armor and a diamond sword and you can 3 hit a player and
they are dead

**Comment by ishitatsuyuki** [comment]
It's Minecraft. That's all.

**Comment by SavionLegendZzz** [comment]
OH HELL NO THIS AINT MINECRAFT WHEN NETHERBOX ADDED THAT ARMOR UPDATE EVERYTHING GOT SCREWED SMH

**Comment by dog194** [comment]
version
PHP

**Comment by SavionLegendZzz** [comment]
PHP7 and latest version

**Comment by Muqsit** [comment]
You can kill a naked player with diamond sword in 3 hits. What's wrong?

**Comment by ishitatsuyuki** [comment]
Edit your post: 'latest' is too broad. Write a specific version from /version.

**Comment by SavionLegendZzz** [comment]
Done. I might help also.

**Comment by dog194** [comment]
Just tested. Nothing wrong with 449, check your version again or give me more detail.
I test one player wear 4 Diamond armors
one player use diamond sword.

**Comment by dog194** [comment]
And coz new Armors Durability System
I change the damage calculating way.
So check the plugins you using at the same time

**Comment by Muqsit** [comment]
Can we close this "issue"? This doesn't seem to be an issue at all. Everything is fine
