### ISSUE TITLE
Cannot open shared object file

### ISSUE THREAD

**Issue by Akharote1** [iTXTech/Genisys#114]
`/usr/bin/php/php.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127`
I recently decided to try Genisys. I download the php7 binaries and the latest phar from jenkins. However whenever I run start.cmd, I get the above error.. I really want to try Genisys and would appreciate if anyone could guide me through the process.
Note: I have tried installing the msvcr110.dll file.. 
Thanks in advance,
Akharote1

**Comment by happy163** [comment]
Please download and install Visual C++ Redistributable for Visual Studio 2015. You can find this in Microsoft's official website.

**Comment by RandomAltThingy** [comment]
How to do on Linux?
