### ISSUE TITLE
Nether a little dull :(

### ISSUE THREAD

**Issue by scot99** [iTXTech/Genisys#1141]
#### Issue description

Nether seems lacking - nether fortress does not generate, only blocks are netherrack

#### Steps to reproduce the issue

Enter nether, mine/wander for ever....

#### OS and versions

* Genisys: 1.1dev-449
* PHP: 7.0.6
* OS: Debian 8

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by xHFx** [comment]
This isnt an issues more of an request to better the generation of the nether ... pointless

**Comment by scot99** [comment]
Wow, what a mature response, thanks. You do realise that without people like me running your (rather limited) server, it's going to die out, right? - Time to try Realms.

**Comment by dog194** [comment]
Wow then just try Realms. You don't really know what is Pocketmine and what is Genisys.

**Comment by xHFx** [comment]
Time to try Realms. 

- ps max players 10 , no plugins , invite only , shit
