### ISSUE TITLE
RakLib Network Interface Error

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1142]
I have this bug and nobody can join. It says this: Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed

**Comment by flaxues** [comment]
Just a tip: Follow the issue style they won't help you if you don't follow it :)

**Comment by ishitatsuyuki** [comment]
Closing for insufficient details. Follow the template, post the full error.

**Comment by GlitchPlayer** [comment]
I know this error. Most likely network error. I get this when I dont
portforward or someone uses the same port

**Comment by dktapps** [comment]
I sometimes get this when I try and start a server when Minecraft is running in the background on my machine. As @GlitchPlayer said, it's usuallly when something is already using that port. Try opening your server on a different port.

**Comment by SuperDude36** [comment]
Ok, thanks! You guys are cool!

**Comment by GlitchPlayer** [comment]
No problem ^_^
