### ISSUE TITLE
Dupe armor

### ISSUE THREAD

**Issue by isoz** [iTXTech/Genisys#1146]
#### Issue description
After a player is killed by another player, the armor drops and the killed player also receives a set of armor making duplication possible. I havent changed anything other than updating genisys so I believe its genisys causing this.

#### Steps to reproduce the issue
Get killed by another player while wearing armor, you will drop your armor on death and will still have your armor.

#### OS and versions

* Genisys: latest
* PHP: 7.0.3
* OS: Ubuntu 14.04

PS: I don't know which exact version caused this but I'm running 431 now and it's fine.

**Comment by dog194** [comment]
I will have look. You can use a older version first.

**Comment by dog194** [comment]
Or you can ues keep-inventory first, I will try to locate the problem.

**Comment by isoz** [comment]
@dog194 please... I'm already using keep-inventory...

**Comment by dog194** [comment]
@isoz. well I cannot test this problem by myself now(coz need a player attack another player.) You can test using the brunch dog194-try. Or wait until i find another device.

**Comment by HuaYoyuDoge** [comment]
is happen to me too

**Comment by markkrueg** [comment]
I have confirmed this bug.

**Comment by markkrueg** [comment]
Confirmed fixed.
