### ISSUE TITLE
Drop block will break chest

### ISSUE THREAD

**Issue by pilock** [iTXTech/Genisys#115]
If drop block fall into the chest,The chest will be break. Such as sand, red sand,gravel

**Comment by Jelly9912** [comment]
Yea, this is really annoying

**Comment by mixailenko5** [comment]
@pilock  I fixed it - https://github.com/iTXTech/Genisys/commit/88dfb8389dd31edf562dab0164526a22c96173ef#diff-7ea620a204b028c0086783ef508aad57

**Comment by kennethgomad03** [comment]
Anyone please help me to convert pocketmine.php to phar using linux

**Comment by BlackShadow1** [comment]
Use ./start.sh @kennethgomad03
