### ISSUE TITLE
Minecraft Education Edition

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys#1151]
Released Minecraft Education Edition, you will give some support Genisys this new Minecraft? if so. the version is 0.14.2 Minecraft Education

**Comment by mixailenko5** [comment]
@RedstoneAlmeida Hi. I have not seen you for a long time.

**Comment by RedstoneAlmeida** [comment]
Sorry, I'm Ocupped recently

**Comment by gaoyichuan** [comment]
We don't know anything about this version.. Would you please give more information?

**Comment by JUSTaMod** [comment]
There's 4 editions of McPe: Education Edition, VR Edition, Windows 10 Beta Edition, and normal Pocket Edition... Found the logos while editing MC's files... Never thought they actually made them tho... Interesting.
![image](https://cloud.githubusercontent.com/assets/19740292/16027287/bd038daa-31a2-11e6-825f-e97e227ebc72.png)
![image](https://cloud.githubusercontent.com/assets/19740292/16027288/bd1352a8-31a2-11e6-98d8-ecc4d40c4aed.png)
![image](https://cloud.githubusercontent.com/assets/19740292/16027289/bd154f7c-31a2-11e6-9770-88ea94eedad8.png)
![image](https://cloud.githubusercontent.com/assets/19740292/16027290/bd192c64-31a2-11e6-80cf-a1e3e710ca86.png)

**Comment by JUSTaMod** [comment]
http://services.minecraftedu.com/wiki/Main_Page
If I where you @gaoyichuan I wouldn't bother trying to add support.

**Comment by dschwartz783** [comment]
Different editions of Minecraft? I guess it's now officially a Microsoft product. :(

**Comment by corytortoise** [comment]
MinecraftEdu isn't for mobile devices though, and it's meant for the multiplayer to stay close-sourced. I don't see why this issue exists.

**Comment by GlitchPlayer** [comment]
Also, Mojang only make those support. Lmao

**Comment by dktapps** [comment]
"Modifications and multiplayer servers are currently not supported in Education Edition." source: http://minecraft.gamepedia.com/Education_Edition

I think this issue may as well be closed.
