### ISSUE TITLE
Time does not stay set at 0

### ISSUE THREAD

**Issue by Dog2puppy** [iTXTech/Genisys#1153]
I hate my server having the night, so I did /time set 0 and /time stop yet, nothing happens. I am running 1.1 dev. My server host is Netherbox.

**Comment by JUSTaMod** [comment]
I don't have this issue. May have been fixed by a newer dev build of genisys. Try it out, 
Gitlab- https://gitlab.com/itxtech/genisys/pipelines
Or at
Jenkins- https://jenkins.mcper.cn/job/Genisys-master/

**Comment by CrayonDing** [comment]
Please use newest build.
![Alt text](http://imageshack.com/a/img922/5783/moFMR1.png)

**Comment by xxFlare** [comment]
I can't confirm this - Are you using the latest version?

**Comment by ABAxStorm** [comment]
@CrayonDing With a server host such as NetherBox we cannot 'get' a newer version of Genisys, NetherBox has to release it.

**Comment by ABAxStorm** [comment]
@JUSTaMod NetherBox only lets you choose which server jar you want (PM, IM, Genius).

**Comment by JUSTaMod** [comment]
Complain to netherbox then. Don't fill up the geniysy's issues section, even if it where an issue that had to be fixed and was patched, your not going to get the update.
Someone close this.
