### ISSUE TITLE
Binary.php error on join (0.15)

### ISSUE THREAD

**Issue by evolvedtm** [iTXTech/Genisys#1154]
#### Issue description
When a player tries to join the server, they get kicked with a message "Outdated Server" and an error appears on the console

#### OS and versions

* Genisys: 1.2dev
* PHP: 7
* OS: Ubuntu 14.04 64bit

#### Crashdump, backtrace or other files
```

Warning: unpack(): Type n: not enough input, need 2, have 0 in /root/Downloads/Genisys-0.15.0/src/pocketmine/utils/Binary.php on line 262

```

**Comment by PeratX** [comment]
Ignore it
