### ISSUE TITLE
Non - php build

### ISSUE THREAD

**Issue by KubixQ** [iTXTech/Genisys#116]
Can anyone give me non - php7 Genisys build, I must test php 7  on anthoner server, I uploaded php7 build to server and I can't find anywhere Genisys php5 build. XD

**Comment by KubixQ** [comment]
php5 build*

**Comment by xpyctum** [comment]
Use php7, it's more faster then php5 and more stable.

**Comment by KubixQ** [comment]
Ok, I test it on my other server.
Never mind, I finded xD
