### ISSUE TITLE
Date on 0.15 Update ?

### ISSUE THREAD

**Issue by xHFx** [iTXTech/Genisys#1160]
#### Issue description

Was wondering if there was an ETA on when you will be posting the first build for 0.15
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dktapps** [comment]
We'll release it when it works. That's all that needs to be said.

**Comment by xHFx** [comment]
Thank you @dktapps

**Comment by ishitatsuyuki** [comment]
No asking for ETA, next time you will get banned.

**Comment by xHFx** [comment]
ig
