### ISSUE TITLE
0.15.0 release?

### ISSUE THREAD

**Issue by AomSkr** [iTXTech/Genisys#1163]
#### OS and versions

* Genisys:14
* PHP:7
* OS: ubuntu14.02

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by GlitchPlayer** [comment]
Bruh.... This is spamming

**Comment by dog194** [comment]
#1094

**Comment by dktapps** [comment]
Check existing issues before opening a new one.

**Comment by gaoyichuan** [comment]
CAN YOU GUYS HAVE A LOOK AT THE ISSUE TEMPLETE AND OPEN ISSUES???
