### ISSUE TITLE
0.15.0 update

### ISSUE THREAD

**Issue by Adam1609** [iTXTech/Genisys#1165]
#### Issue description
This is not an update. It's just asking to update protocol of Minecraft PE 0.15.0

#### Steps to reproduce the issue
No Steps Provided!

#### OS and versions

* Genisys: v1.1
* PHP: 7.0
* OS: Windows Server 2012

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
Check existing issues before opening a new one.

**Comment by dktapps** [comment]
I think this is the eighth issue like this that we've closed so far (not including PRs). The spam!
