### ISSUE TITLE
How to install Genisys 1.0 Dev (php7) on CentOS 6?

### ISSUE THREAD

**Issue by KubixQ** [iTXTech/Genisys#117]
^^->Thread says all <-^^

**Comment by xpyctum** [comment]
pizdec...

**Comment by KubixQ** [comment]
?

**Comment by PeratX** [comment]
https://github.com/PeratX/php-build-scripts compile.sh

**Comment by GalvinGao** [comment]
You might want to go to __**https://www.pocketmine.net/**__ to look for tips. Just replace the __PocketMine-MP.phar__.

**Comment by KubixQ** [comment]
@GalvinGao pocketmine is on the php5

**Comment by GalvinGao** [comment]
Ok. I messed it up lol...
