### ISSUE TITLE
Oops?

### ISSUE THREAD

**Issue by ImWalla** [iTXTech/Genisys#1171]
WHAT DOES OOOPPSSS MEAN?!? Sorry for screaming, im too hyped.

**Comment by CrayonDing** [comment]
I forgot adding a file at first.

**Comment by ImWalla** [comment]
Hold the phone, i know you guys are getting a ton of questions about 0.15.0. But does this mean Genisys is getting closer to release an official build for 0.15.0? @CrayonDing

**Comment by CrayonDing** [comment]
Yes.We are doing that.

**Comment by ImWalla** [comment]
:D
