### ISSUE TITLE
15.0 issues at a glance.

### ISSUE THREAD

**Issue by LordJoshie** [iTXTech/Genisys#1173]
#### Issue description

3 noticeable issues off the hop.

auto login doesnt work. 
leads between players. tethered.
rain rain rain... weather doesnt seem to work properly.

#### Steps to reproduce the issue

just login.

#### OS and versions

* Genisys: #1835695	c1464435 	master
* PHP: 7
* OS: ubuntu

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Adam1609** [comment]
Wait the minute. The latest version is failing. Of course login is error. Just wait till next update of Genisys

**Comment by dktapps** [comment]
Rain has been an issue since a long time before 0.15. And Jenkins is only failing because the build script needs updating. Use GitLab in the meantime.

**Comment by LordJoshie** [comment]
noo... i use gitlab phars... the latest wasnt a fail. just, I use HereAuth & its not remembering logins.

**Comment by Adam1609** [comment]
SimpleAuth does work for me!

**Comment by dktapps** [comment]
@LordJoshie I was talking to @Adam1609 about GitLab. As for plugins this is not our issue. Plugins should be kept up to date.

**Comment by LordJoshie** [comment]
HereAuth worked before 15.0. 

I can show u the error. lol

**Comment by LordJoshie** [comment]
![_20160616_054859](https://cloud.githubusercontent.com/assets/17371144/16112672/6286bcb8-3386-11e6-9b39-8c5cc2328526.JPG)

**Comment by LordJoshie** [comment]
something to do with custom alerts... but... HereAuth doesn't auto login anymore.

**Comment by dktapps** [comment]
The first is not a Genisys issue but because your plugin is out of date.

**Comment by KillerXtream** [comment]
Isn't $additionalChar needed anymore?

**Comment by Adam1609** [comment]
Got some error:
 Error: "Undefined class constant 'pocketmine\network\protocol\Info::REMOVE_PLAYER_PACKET'" (EXCEPTION) in "/GlxNPC_v1.0.0.phar/src/FNPC/npc/NPC" at line 430
The player packet is error, using the latest version.

**Comment by KillerXtream** [comment]
FNPC v1.0.0 ehh, there's FNPC v1.1.0

**Comment by LordJoshie** [comment]
whats fnpc?

**Comment by KillerXtream** [comment]
Error: "Undefined class constant 'pocketmine\network\protocol\Info::REMOVE_PLAYER_PACKET'" (EXCEPTION) in "/GlxNPC_v1.0.0.phar/src/FNPC/npc/NPC" at line 430

A plugin

**Comment by LordJoshie** [comment]
duh..... what's the acronym fnpc mean?

**Comment by Adam1609** [comment]
I think that, the PlayerJoinEvent may involved in this plugin error I copied. That's why HereAuth didn't auto login like before. Same error in 0.12

**Comment by andris155** [comment]
```
Notice: Undefined property: pocketmine\network\protocol\LoginPacket::$additionalChar in D:\Minecraft Szerverek\Genisys\src\pocketmine\Player.php on line 2568
[11:11:06] [Server thread/INFO]: Google[/192.168.1.122:19132] logged in with entity id 2 at (world, 128, 64, 128)
[11:11:07] [Server thread/INFO]: Google csatlakozott a játékhoz
[11:11:18] [Server thread/INFO]: Google elhagyta a játékot
[11:11:18] [Server thread/INFO]: Google lost connection: timeout
```

**Comment by Muqsit** [comment]
@KillerXtream @andris155 
Do you get it when you're using https://github.com/Muqsit/Genisys

**Comment by LordJoshie** [comment]
ill test this

**Comment by Muqsit** [comment]
Dont test it now, test it in 2 mins

**Comment by LordJoshie** [comment]
...why?

**Comment by LordJoshie** [comment]
...well, less console errors. 
but still doesn't login proper.

**Comment by dktapps** [comment]
I'd recommend to set `mobgenerate` to false until we fix this issue, and do not use spawn eggs.
Also, [this](https://github.com/Muirfield/pocketmine-plugins/releases/tag/GrabBag-2.5.0) plugin may come in useful. Say `et nuke` from the terminal to remove all mobs.

**Comment by LordJoshie** [comment]
or use clearlagg & do /clearlagg clearall....   I use time commander to automatically do this every 15min. 


my mob gen is off btw... cuz it only spawns cows & hostiles at night. 
doesn't seem to spawn pigs/sheep/chickens. :/

**Comment by CLiu13** [comment]
For the lead problem, I believe Steadfast2 found // is working on a solution.

**Comment by Tolo0** [comment]
the lead problem is funny lol. I get custom alerts error to sins version 15 update.

![screenshot_20160616-125123](https://cloud.githubusercontent.com/assets/13458191/16115789/3c8c40ce-33c1-11e6-8542-6882347b4205.png)

**Comment by XxDXM-hippiexX** [comment]
@LordJoshie HereAuth never remembered logins for me..well it did but after a server reboot you need to login once then it will remember until the next reboot.

**Comment by isoz** [comment]
CustomAlerts you just have to change from protocol1 to protocol in the source...

**Comment by LordJoshie** [comment]
Isoz, t.y     &  hippie, I never had an issue with HereAuth. :(

**Comment by intagaming** [comment]
Same problem.
Picture just in case:

![untitled](https://cloud.githubusercontent.com/assets/16471365/16122544/b44218b4-3411-11e6-9d50-046ac0e37d77.png)

**Comment by dktapps** [comment]
We're aware of the issue. It's happening to everyone, not just Genisys. We're working on it.

**Comment by Muqsit** [comment]
#1179 ?

**Comment by Adam1609** [comment]
Custom Alert's join message issue. And it effect on Genisys, right?

**Comment by isoz** [comment]
All you have to do is edit protocol1 to portocol like I said above... @Adam1609 Please read...

**Comment by daniktheboss** [comment]
Hey players in my server somtimes crash... like log of due to timeout or client disconnect and then join back and say they crashed ..... no errors on server logs. ..

**Comment by daniktheboss** [comment]
another server log... "Notice: Undefined property: pocketmine\level\Level::$z in C:\Users\Daniil\Desktop\Genisys\src\pocketmine\level\Level.php on line 817

Notice: Trying to get property of non-object in C:\Users\Daniil\Desktop\Genisys\src\pocketmine\level\Level.php on line 817"

**Comment by KairusDarkSeeker** [comment]
My MCPE crashes when I was joining the server, and LoginPacket.php gone which will make ur mcpe crash cuz MSpawns use LoginPocket ffs bring login packet back!

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/network/protocol/LoginPacket.php

What is this, if not the login packet? The crash issue is actually mob-related and a fix is currently waiting to be merged.

Please make sure you have your facts straight before making stupid comments in future.

**Comment by Moonneko** [comment]
Can turn off the snow. My server í very lagg

**Comment by kabluinc** [comment]
@Moonneko Yup same issue as mine.

**Comment by dktapps** [comment]
I'm investigating the weather issues, please be patient. As for the leads, the 0.15-bugfixes branch has these fixed, with the exception of some custom mobs.

**Comment by Muqsit** [comment]
Auto login works for me - SimpleAuth
Leads is fixed
That remains only the weather bug, right?

**Comment by dktapps** [comment]
Leads aren't fully fixed, I'm getting problems when switching worlds.

**Comment by lolcraftboy** [comment]
@dktapps  y have it to

**Comment by kabluinc** [comment]
leads arnt fixed yet for mobs right? cos all leads still connect to NPCs

**Comment by dktapps** [comment]
Leads still WIP, please be patient. If you could give me a link to a plugin which has this issue, that would be very helpful.

**Comment by dktapps** [comment]
Meaning a plugin that adds custom mobs.

**Comment by kabluinc** [comment]
https://github.com/PocketMine-PHP7/Slapper-PHP7

**Comment by kabluinc** [comment]
sorry for the hassle

**Comment by dktapps** [comment]
thanks very much

**Comment by kabluinc** [comment]
np

**Comment by SzczepanPolska** [comment]
[
![image](https://cloud.githubusercontent.com/assets/16169053/16162036/fa33deb0-34d0-11e6-991b-14bd952d6f5f.jpeg)
](url)
Sooo....

**Comment by kabluinc** [comment]
@SzczepanPolska Try using the 0.15 bug fixes branch which fixes that and some other issues

**Comment by kabluinc** [comment]
@SzczepanPolska Try using [This](https://github.com/iTXTech/Genisys/tree/0.15-bugfixes) branch. it fixes that and some other issues

**Comment by jojoe77777** [comment]
@kabluinc Instead of linking people to that repo, why not the official one?! https://github.com/PMPlugins/Slapper Updated to php7

**Comment by kabluinc** [comment]
Leashes are fixed with the latest version of slappers from @jojoe77777s repository. Thanks allot for the link.

**Comment by LordJoshie** [comment]
I deleted my Genisys.yml & started my server.... closed server. Edited the new Genisys.yml...all seems fine now.   My weather is disabled as preference, so as far as I know you can successfully turn off the weather by deleting the Genisys.yml & starting/stopping the server to recreate the Genisys.yml... edit it and ur good.

the leads were fixed, block update & player movement fixed.   thank you very skilled devs for that.
just waiting for ...the already NOT recommend login/auth plugin HereAuth to start working like it did before, with automatic login on recognized devices... cuz something about that doesn't function anymore after 15.0 :/ wubwub

I'd close this issue, if you guys suggest I should.
