### ISSUE TITLE
join the world,it crash the games :/

### ISSUE THREAD

**Issue by HuaYoyuDoge** [iTXTech/Genisys#1176]
#### Issue description
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [12:08:42] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [12:08:42] [Server thread/INFO]: 
[Server] 
[Server] 		 PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
[Server] 		 Version: 1.2dev-c146443
[Server] 		 Target client Version: v0.15.0.0 alpha
[Server] 		 Latest source code is available at https://github.com/iTXTech/Genisys
[Server] 		 Donate link: http://pl.zxda.net/plugins/203.html
[Server] 		 如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
[Server] 		
[Server] 
[Server] [12:08:42] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [12:08:42] [Server thread/INFO]: Loading genisys.yml...
[Server] [12:08:42] [Server thread/INFO]: Loading server properties...
[Server] [12:08:42] [Server thread/INFO]: Selected English (zh) as the base language
[Server] [12:08:42] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.0.0 alpha
[Server] [12:08:42] [Server thread/INFO]: Starting remote control listener
[Server] [12:08:42] [Server thread/INFO]: RCON running on 0.0.0.0:19133
[Server] [12:08:42] [Server thread/INFO]: Opening server on 0.0.0.0:19133
[Server] [12:08:43] [Server thread/INFO]: This server is running Genisys version 1.2dev-c146443 "Ikaros" (API 2.0.0)
[Server] [12:08:43] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
[Server] 
[Server] Warning: Invalid argument supplied for foreach() in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/plugin/PluginDescription.php on line 116
[Server] [12:08:46] [Server thread/INFO]: Loading TapToDo v2.2.1
[Server] [12:08:46] [Server thread/INFO]: Loading EconomyAPI v2.0.9
[Server] [12:08:46] [Server thread/INFO]: Loading KillCheck v0.1
[Server] [12:08:46] [Server thread/INFO]: Loading Slapper v1.2.9.4_PHP7
[Server] [12:08:46] [Server thread/INFO]: Loading BuildUHCJericMD v2.2.1
[Server] [12:08:46] [Server thread/INFO]: Loading ParticlesPlus v0.0.2
[Server] [12:08:46] [Server thread/INFO]: Loading Kits v0.1
[Server] [12:08:46] [Server thread/INFO]: Loading WorldEdit v3.2
[Server] [12:08:46] [Server thread/INFO]: Loading WorldProtect v2.2.0
[Server] [12:08:46] [Server thread/INFO]: Loading Lightning_Strike v2
[Server] [12:08:46] [Server thread/INFO]: [Lightning_Strike] Preparing For StartUp... STAND BY
[Server] 
[Server] Warning: Invalid argument supplied for foreach() in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/plugin/PluginDescription.php on line 116
[Server] 
[Server] Warning: Invalid argument supplied for foreach() in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/plugin/PluginDescription.php on line 116
[Server] [12:08:46] [Server thread/INFO]: Loading BlockBoost v1.0.0
[Server] [12:08:46] [Server thread/INFO]: Loading SignPortal v1.1.2
[Server] [12:08:46] [Server thread/INFO]: Loading source plugin TimeCM v2
[Server] [12:08:46] [Server thread/INFO]: Loading SimpleWarp v2.1.0
[Server] [12:08:46] [Server thread/INFO]: Enabling KillCheck v0.1
[Server] [12:08:46] [Server thread/INFO]: [KillCheck] Plugin loaded! v_0.1 By Artide
[Server] [12:08:46] [Server thread/INFO]: Enabling WorldProtect v2.2.0
[Server] [12:08:46] [Server thread/INFO]: [WorldProtect] Enabled 7 features
[Server] [12:08:46] [Server thread/INFO]: Enabling BlockBoost v1.0.0
[Server] [12:08:46] [Server thread/INFO]: BlockBoost Activate v1.0.0
[Server] [12:08:47] [Server thread/INFO]: Preparing level "AceSpawn"
[Server] [12:08:48] [Server thread/INFO]: Preparing level "nerther"
[Server] [12:08:48] [Server thread/INFO]: Enabling TapToDo v2.2.1
[Server] [12:08:48] [Server thread/INFO]: Enabling EconomyAPI v2.0.9
[Server] [12:08:49] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] [12:08:49] [Server thread/INFO]: Enabling Slapper v1.2.9.4_PHP7
[Server] [12:08:49] [Server thread/INFO]: Enabling BuildUHCJericMD v2.2.1
[Server] [12:08:49] [Server thread/INFO]: [BuildUHCJericMD] BuildUHC by JMD version 2.2.0
[Server] [12:08:49] [Server thread/INFO]: Preparing level "a1"
[Server] [12:08:49] [Server thread/INFO]: [TapToDo] Reloading blocks due to level a1 loaded...
[Server] [12:08:50] [Server thread/INFO]: Preparing level "house"
[Server] [12:08:50] [Server thread/INFO]: [TapToDo] Reloading blocks due to level house loaded...
[Server] [12:08:52] [Server thread/INFO]: Enabling ParticlesPlus v0.0.2
[Server] [12:08:52] [Server thread/INFO]: Enabling Kits v0.1
[Server] [12:08:52] [Server thread/INFO]: Enabling WorldEdit v3.2
[Server] [12:08:52] [Server thread/INFO]: Enabling Lightning_Strike v2
[Server] [12:08:54] [Server thread/INFO]: [Lightning_Strike] Lightning Strike RUNNING Made By MichaelM04
[Server] [12:08:54] [Server thread/INFO]: Enabling SignPortal v1.1.2
[Server] [12:08:54] [Server thread/INFO]: Enabling TimeCM v2
[Server] [12:08:54] [Server thread/INFO]: Enabling SimpleWarp v2.1.0
[Server] [12:08:55] [Server thread/NOTICE]: Your genisys.yml needs update
[Server] [12:08:55] [Server thread/NOTICE]: Current Version: 14 Latest Version: 15
[Server] [12:08:56] [Server thread/INFO]: Starting GS4 status listener
[Server] [12:08:56] [Server thread/INFO]: Setting query port to 19133
[Server] [12:08:56] [Server thread/INFO]: Query running on 0.0.0.0:19133
[Server] [12:08:56] [Server thread/INFO]: Default game type: Survival Mode
[Server] [12:08:56] [Server thread/INFO]: Done (19.593s)! For help, type "help" or "?"
>version
[Server] [12:09:05] [Server thread/INFO]: This server is running Genisys 1.2dev-c146443 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)
[Server] 
[Server] Notice: Undefined property: pocketmine\network\protocol\LoginPacket::$additionalChar in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/Player.php on line 2568
[Server] [12:10:33] [Server thread/INFO]: Huayoyu[/192.168.1.86:19132] [ClientID: -1.2672003166521E+18] logged in with entity id 2 at (AceSpawn, 1018, 7, -1661)
[Server] [12:10:33] [Server thread/INFO]: There are 1/3 players online:
[Server] [12:10:33] [Server thread/INFO]: Huayoyu
[Server] [12:10:36] [Server thread/INFO]: Huayoyu joined the game
[Server] [12:10:43] [Server thread/INFO]: Huayoyu left the game
[Server] [12:10:43] [Server thread/INFO]: Huayoyu[/192.168.1.86:19132] logged out due to timeout
[Server] [12:10:43] [Server thread/INFO]: There are 0/3 players online:
[Server] [12:10:43] [Server thread/INFO]: 
[Server] Notice: Undefined property: pocketmine\network\protocol\LoginPacket::$additionalChar in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/Player.php on line 2568
[Server] [12:11:38] [Server thread/INFO]: Huayoyu[/192.168.1.86:53843] [ClientID: -1.2672003166521E+18] logged in with entity id 36 at (AceSpawn, 1018, 7, -1661)
[Server] [12:11:38] [Server thread/INFO]: There are 1/3 players online:
[Server] [12:11:38] [Server thread/INFO]: Huayoyu
[Server] [12:11:40] [Server thread/INFO]: Huayoyu joined the game
[Server] [12:11:51] [Server thread/INFO]: Huayoyu left the game
[Server] [12:11:51] [Server thread/INFO]: Huayoyu[/192.168.1.86:53843] logged out due to timeout

#### Steps to reproduce the issue
When i join the server,it crash my games 

#### OS and versions
* Genisys: latest for 0.15 version
* PHP: 7
* OS:

#### Crashdump, backtrace or other files
```
nope
```

**Comment by dktapps** [comment]
Read existing issues before opening a new one. #1173

**Comment by HuaYoyuDoge** [comment]
btw,what wrong?i just rebord this issuses?any fking problems!

**Comment by ishitatsuyuki** [comment]
It's duplicate, which is not allowed.

**Comment by daniktheboss** [comment]
You know how much issues like this are open? That's what pissed the devs off!

**Comment by ishitatsuyuki** [comment]
You will be blocked if you continue to spam.
