### ISSUE TITLE
0.15.0.0 players can't join!

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#1182]
[Server] Server thread/INFO logged out due to Login timeout
 16.06 20:54:38 [Server] INFO Notice: Undefined property: pocketmine\network\protocol\LoginPacket::$additionalChar in phar:///jar/versions/Genisys/Genisys471.phar/src/pocketmine/Player.php on line 2568

**Comment by dktapps** [comment]
Please provide more information about this. And the `$additionalChar` is a known issue.

**Comment by dktapps** [comment]
Closing for not following issue template.
