### ISSUE TITLE
deop forces lower-case player names; Unable to deop a player with upper-case letters.

### ISSUE THREAD

**Issue by ZizzyZizzy** [iTXTech/Genisys#1188]
#### Issue description
Somehow I managed to get a player name with upper-case characters in ops.txt. (Cannot re-produce how I did this. I swear it was a copy/paste from console log to console.)

Attempting to deop that same player shows successful, but that player is NOT removed from ops.txt. They have to be removed manually.

#### Steps to reproduce the issue
1. Add a player name to ops.txt, but change some characters to upper-case.
2. Try to deop them from the console or in-game with another op account.

 #### OS and versions
* Genisys:
Genisys 1.2dev-471 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)
* PHP:
PHP 7.1.0-dev (cli) (built: Feb 18 2016 12:40:46) ( ZTS )
* OS:
CentOS 6.7

#### Crashdump, backtrace or other files
N/A

**Comment by XFuryMCPE** [comment]
I will attempt to fix this.

**Comment by XFuryMCPE** [comment]
wait.. Why do you even edit your ops.txt and add uppercase characters? Don't do that if you don't want that to happen..

**Comment by ZizzyZizzy** [comment]
I didn't. I'm pretty sure it happened when I was screwing around with different 0.15 builds, trying to get one to work. (It might have been from ClearSky php7-0.15.)

I copied the username from the console after the player logged in, then pasted it in the Multicraft command text box to op them. The name happened to have upper-case chars in it and that's how it was written to the ops.txt file.

**Comment by corytortoise** [comment]
If it's a server host you were using, I believe issues you come across while using their "command text box" means you should be talking to your host about the issue, not iTX-Tech. (Especially if you aren't sure you were using Genisys.)

**Comment by ZizzyZizzy** [comment]
It was my own server with my own Multicraft license.

The command text box just meant the Multicraft console where you issue commands to the java process in a friendly GUI. Genisys still processes the command as it normally would.

**Comment by corytortoise** [comment]
Ah,  I misunderstood you. My apologies.

**Comment by dktapps** [comment]
Actually I think you'll fnd that op names are case-insensitive. This should therefore not be an issue.

**Comment by ZizzyZizzy** [comment]
@dktapps The reason I opened the bug report in the first place was because de-opping a player with upper-case characters in their name (as stored in ops.txt, NOT a plugin) does NOT work. Have you tried to replicate? It takes about 2 minutes to try this for yourself:

# cat ops.txt 
someguy
ZizzyZizzy

* from the console:
deop ZizzyZizzy
17.06 09:34:49 [Server] Server thread/INFO [CONSOLE: De-opped zizzyzizzy]
17.06 09:34:49 [Multicraft] Skipped 6 lines due to rate limit (30/s)
17.06 09:34:19 [Server] Startup Done (0.748s)! For help, type "help" or "?"

(notice how the server changed the player name to lowercase)

# cat ops.txt 
someguy
ZizzyZizzy


* console:
deop someguy
17.06 09:36:03 [Server] Server thread/INFO [CONSOLE: De-opped someguy]

# cat ops.txt 
ZizzyZizzy

**Comment by dktapps** [comment]
I'll investigate this. It shouldn't be difficult to fix.

**Comment by flaxues** [comment]
17.06 09:34:49 [Server] Server thread/INFO [CONSOLE: De-opped zizzyzizzy]
17.06 09:34:49 [Multicraft] Skipped 6 lines due to rate limit (30/s)

Why does it skip 6 lines could you set the rate limit higher so we can see those lines?

You can edit it in settings -> show advanced options -> Limit number of console lines per second to...

**Comment by ZizzyZizzy** [comment]
That was just 6 lines of information messages about the server starting. When I deopped someguy, the line you see is the only line shown.
