### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by Artur0022** [iTXTech/Genisys#119]
''Warning: require_once(phar:///test/PocketMine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: internal corruption of phar "/test/PocketMine-MP.phar" (truncated manifest header) in /test/PocketMine-MP.phar on line 1

Fatal error: require_once(): Failed opening required 'phar:///test/PocketMine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /test/PocketMine-MP.phar on line 1''

This error appeared in the Assembly room 7,8,9,10,12... What is it? How to fix it?

**Comment by Artur0022** [comment]
This error appeared in the Assembly number 7,8,9,10,12... What is it? How to fix it*

**Comment by PocketKiller** [comment]
your network downloaded .phar badly.

**Comment by Artur0022** [comment]
What? How to download it correctly? Loaded with Jenkins ...

**Comment by PocketKiller** [comment]
The Jenkins is hosted on China, so the one who hosted it should get a Global CDN

**Comment by xpyctum** [comment]
Bad download speed from CN

**Comment by Artur0022** [comment]
Ok... Thanks, the first error is gone ... But there is now Segmentation fault

**Comment by Artur0022** [comment]
http://i75.fastpic.ru/big/2016/0121/73/8082d37075740ce5d821b48d1d158d73.png

**Comment by PocketKiller** [comment]
do you have any other servers running?

**Comment by Artur0022** [comment]
Yes there is, but on the other VDS. There I have a server on this 7th kernel version, and the later gives me again this error //Sorry for the lexical mistakes...

**Comment by MrDoni98** [comment]
@Artur0022 I do the same thing if start.sh is DO_LOOP = "no" if DO_LOOP = "yes" it writes to the console:
PocketMine-iTX Genisys is a fork of PocketMine-MP.
		   Powered by iTX Technologies LLC.
		   Version: 1.0dev-12
		   Client Version: 0.13.1 alpha
		   You could get the lastest code on https://github.com/iTXTech/Genisys
		   Donate link: http://pl.zxda.net/plugins/203.html
		   如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。

**Comment by MrDoni98** [comment]
although I have the latest version of Genisos

**Comment by Artur0022** [comment]
But this is clearly not my shortcoming . This defect of the nucleus. Frankly speaking - it is a bug

**Comment by CrayonDing** [comment]
@xpyctum  I just used CDN to improve download speed.So now maybe faster.
