### ISSUE TITLE
Unable to open chests in Adventure Mode.

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1197]
#### Issue description

If you try to open any chests in a server while your gamemode is switched to "Adventure Mode," it won't open. However, it works fine in Survival Mode.
#### Steps to reproduce the issue

Go on your server.
Place a chest.
Switch to Adventure Mode and tap the chest.
Now, switch to Survival Mode and tap the chest.
#### OS and versions

* Genisys: 1.2-dev72a2812
* PHP: 7
* OS: Moto G (Android 5.1)

#### Crashdump, backtrace or other files
```
N/A
```

**Comment by MCPEPIG** [comment]
Its not supposed to.

**Comment by dktapps** [comment]
I think this is intended. Closing.

**Comment by gaoyichuan** [comment]
Players in Adventure Mode should be able to open chests...

**Comment by JUSTaMod** [comment]
Can we make up our minds on this??? This is the third or fourth Adv. mode chest-opening issue submit.

**Comment by dktapps** [comment]
@gaoyichuan I tested this in PC and it seems you're right. My bad.

**Comment by Striker209** [comment]
Same when you try to catch a PlayerInteractEvent :
- If the player is in adventure mode, he has to long press the target otherwise it won't call the event
- If the player is in survival mode, he can click OR long press the target
