### ISSUE TITLE
Problems with rain

### ISSUE THREAD

**Issue by Yupai** [iTXTech/Genisys#1199]
#### Issue description
I can not turn off the rain. I put in Genisys.yml weather: false, but it does not work. Am I doing something wrong?

#### OS and versions

* Genisys: 1.2
* PHP: 7
* OS: Linux

**Comment by Adam1609** [comment]
Try to install NoWeather plugin.

**Comment by dktapps** [comment]
Check existing issue before opening a new one. #1180

**Comment by Yupai** [comment]
Thank you!
