### ISSUE TITLE
can Fix this?

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#120]
![image](https://cloud.githubusercontent.com/assets/6584811/12489918/9c262b6c-c094-11e5-84b2-f72aeedadd1c.png)

**Comment by PeratX** [comment]
Minecart....

**Comment by xpyctum** [comment]
@PeratX Okay, how delete them? I'm didn't find him.

**Comment by PeratX** [comment]
New option in genisys.yml can turn off minecart
