### ISSUE TITLE
Help: How do I update?

### ISSUE THREAD

**Issue by KDOA808** [iTXTech/Genisys#1202]
#### Issue description
I can't know where to put .phar to update the server
http://image.prntscr.com/image/87bc01056c3c4db59b5457dfbb7ba815.png

#### Steps to reproduce the issue
1. Open Wincsp
2. Login to my vps
3. Home/me/s2

I don't know where to put Genisys.phar to update the server on some third parties it usually in this path

#### OS and versions

* Genisys: Genisys 1.2dev "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)

* PHP: 7
* OS: Linux ubuntu 14.0.4

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
No questions in issue tracker. Read README until you understand where to put it.

**Comment by KDOA808** [comment]
@ishitatsuyuki ok i understnand
