### ISSUE TITLE
Crashdump and old maps

### ISSUE THREAD

**Issue by SirOptic** [iTXTech/Genisys#1205]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```
18.06 07:33:02 [Server] INFO Notice: Undefined property: pocketmine\network\protocol\LoginPacket::$additionalChar in phar:///Genisys.phar/src/pocketmine/Player.php on line 2570

1Issue When teleporting to old maps server crashes and closes or sometimes it takes you out of mc to home screen
2issue/enchant doesnt work
3issue alot of lagg spikes
4issue mobs dont seem to turn off?
5Issue

**Comment by ishitatsuyuki** [comment]
Closing for not writing version. Yours is outdated.

**Comment by dktapps** [comment]
@ishitatsuyuki you beat me to it
