### ISSUE TITLE
Clients crashing upon joining. 

### ISSUE THREAD

**Issue by HotshotHD** [iTXTech/Genisys#1207]
Whenever a client joins the game just crashes, if they are lucky enough to join that is. Most of the time clients simply can't connect to the server due to timeout.

**Comment by dktapps** [comment]
Please see open issue before opening another. Also make sure your server is up to date.

**Comment by HotshotHD** [comment]
It is up to date. But I realized that the problem comes from my Lobby world. If I change the lobby to another world, everything is fine, but the lobby I use causes clients to crash . Why is that?

**Comment by dktapps** [comment]
@HotshotHD either an MCAnvil problem or your world may be corrupted.
