### ISSUE TITLE
PvP and movement

### ISSUE THREAD

**Issue by SavionLegendZzz** [iTXTech/Genisys#1209]
#### Issue description

Movement is laggy asf and PvP is still fucked i dont know why that dog kid fucking did that update but its horrible and no one likes it atleast make an option to disable it. And movement is laggy and i have like 21 players online with 3gbs

#### Steps to reproduce the issue

Play on a server that runs genisys

#### OS and versions

* Genisys: 1.2-dev ikaros
* PHP: Php7
* OS: Linux

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Muqsit** [comment]
At least your world isn't crashing!

**Comment by dktapps** [comment]
You'd do better to swear less and be less abusive. Closing.
