### ISSUE TITLE
Collection of old jenkins

### ISSUE THREAD

**Issue by flash586** [iTXTech/Genisys#121]
Where can I get collection on the last working php5? # 145 appears

**Comment by astersx** [comment]
So latest builds dont work with php5.   :0?

**Comment by flash586** [comment]
They not work on php5 and php7

**Comment by astersx** [comment]
LOL so RIP php5?  -.-' 
I will no more come to genisys github page!!!

**Comment by flash586** [comment]
-_- stupid troll see! Php7 not work and php5 not work!

**Comment by astersx** [comment]
I understand,  i dont care about php7....  I only use php5 :+1: !!!!

**Comment by flash586** [comment]
Can share me latest build?

**Comment by PeratX** [comment]
check the php5 branch

**Comment by flash586** [comment]
You can me give latest worked build of core?

**Comment by CrayonDing** [comment]
https://github.com/iTXTech/Genisys/tree/php5
