### ISSUE TITLE
0.15.0.0 iprotector pvp protection not work

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1211]
#### Issue description

Not work iprotector pvp protection

#### Steps to reproduce the issue

hit players god: true zones.

#### OS and versions

* Genisys: Genisys_1.2dev-478.phar	
* PHP: 7.0.2 Linux x64
* OS: Ubuntu

#### Crashdump, backtrace or other files
```
none
```

**Comment by CLiu13** [comment]
Related to https://github.com/iTXTech/Genisys/issues/1186

**Comment by flaxues** [comment]
It does work since the other player doesn't get damaged or sees the damage motion. Only the attacker sees it...

**Comment by dktapps** [comment]
@flaxues thank you. Closing.
