### ISSUE TITLE
Local Server

### ISSUE THREAD

**Issue by kaitododoyt** [iTXTech/Genisys#1213]
I have problems with local server of Genisys(i dont have the port 19132 open). I can see the server, but i cant connect

**Comment by ishitatsuyuki** [comment]
You will got banned if you continue to not follow the template.

**Comment by kaitododoyt** [comment]
sorry, im dont know perfectly english, can you reopen?

**Comment by ishitatsuyuki** [comment]
No, because you didn't follow the template.
