### ISSUE TITLE
Windows 10 Creative

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/Genisys#1219]
In Windows10 is it not possible to take something out of the creative inventory!
My Genisys version:
This server is running Genisys 1.2dev-474 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)
Reproduce: Go in creative mode with Windows 10 edition and take an item out!

**Comment by dktapps** [comment]
One: you didn't follow the issue template. Two: your Genisys version is out of date. Closing.
