### ISSUE TITLE
hacks and bancid

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#122]
Hi! Can somehow add a counter for speed mod? 
And bancid dont really work,  player can log in again,  it only kick them!!!

**Comment by GalvinGao** [comment]
Mod... Either I don't know speed mod is what, but the sort of 'mod' things won't be included in the core.

The bancid may be fix. Thanks for reporting.

@PeratX The bancid is just kick players. Plz fix it. Thx.

**Comment by PeratX** [comment]
@astersx /bancid <Player's ClientID> not name! If you want to bancid by name ,try /bancidbyname <OnlinePlayerName>

**Comment by GalvinGao** [comment]
Issue is __not__ a issue but a __user mistake__. Closing issue.
