### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1220]
require_once(phar:///jar/versions/Genisys/Genisys478.phar/src/pocketmine/PocketMine.php): failed to open stream: phar error: internal corruption of phar "/jar/versions/Genisys/Genisys478.phar" (actual filesize mismatch on file "src/pocketmine/PocketMine.php") in /jar/versions/Genisys/Genisys478.phar on line 1
19.06 22:22:29 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///jar/versions/Genisys/Genisys478.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /jar/version

**Comment by flaxues** [comment]
Corrupted .phar 

Just re-download it!
