### ISSUE TITLE
How to change default weather in biome world

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#1221]
sorry if this is the wrong place to ask this but how would you change a map so that it rains by default rather than snow? i think i slightly remember reading somewhere its something to do with /biome? if so how would i use it to change the default weather of a specific world. The world is a biome, non-flat world.

Many thanks,

**Comment by JUSTaMod** [comment]
You can change the biome from a snow biome to a grasslands biome or something, just select an area with /biome pos1    /biome pos2    /biome set # 

However, it would be a nice addition to change the temperature of a selected biome area, as I'm pretty sure there is temperature data for each biome in normal Minecraft.

**Comment by ishitatsuyuki** [comment]
Closing for question.

**Comment by JUSTaMod** [comment]
just ignore my second comment. sure.

**Comment by kabluinc** [comment]
Thanks allot
