### ISSUE TITLE
Command /spawn

### ISSUE THREAD

**Issue by samalero** [iTXTech/Genisys#1228]
#### Issue description
Please add command /spawn

#### Steps to reproduce the issue
-

#### OS and versions

* Genisys: fe28aea
* PHP: 7
* OS: Win8.1

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
What?
Non-vanilla command. Closing.

**Comment by samalero** [comment]
But necessary as oxygen!)

**Comment by ishitatsuyuki** [comment]
Use a plugin. It's not a reason.

**Comment by TheDiamondYT1** [comment]
/bancid isint vanilla either so i have no idea wtf you are on about @ishitatsuyuki

**Comment by gaoyichuan** [comment]
@iTXTech/developers Have a vote here
