### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by Artur0022** [iTXTech/Genisys#123]
Segmentation fault ... what could be the error is connected ?

**Comment by PeratX** [comment]
Any more info?

**Comment by Artur0022** [comment]
http://ipic.su/img/img7/fs/Snimokekrana(131).1453467143.png

**Comment by PocketKiller** [comment]
show your server folder

**Comment by Artur0022** [comment]
mixailenko5 = GOD php ОН убрал этот чертов баг!

**Comment by MrDoni98** [comment]
@Artur0022 я тоже мучился

**Comment by Artur0022** [comment]
MrDoni98 мы с ним сидели в вк и выясняли в чем проблема...

**Comment by xpyctum** [comment]
Когда всё нормально.

**Comment by mixailenko5** [comment]
@xpyctum  это зависит скорее всего от ОС. Ведь на ОС Windows проблемы с сегментацией не было, а на моемLinux Ubuntu +

**Comment by xpyctum** [comment]
А я на Debian тестил.
