### ISSUE TITLE
QUESTION: Synapse..

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1231]
Did you guys give up on the Synapse proxy..? You haven't touched it in weeks :/

**Comment by ishitatsuyuki** [comment]
No question here. Shut up since we're busy on the 0.15.

**Comment by JUSTaMod** [comment]
Get. F'in rekt son.

**Comment by XFuryMCPE** [comment]
You don't need to be an ass about it, it was just a question.

**Comment by legoboy0215** [comment]
LMAO.
