### ISSUE TITLE
Php5

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1232]
Can you update php5 i have mcg76 hg plugin but is in php5 you can?

**Comment by ishitatsuyuki** [comment]
PHP5 is unsupported.

**Comment by JUSTaMod** [comment]
These "issues" just get worse and worse. How do you guys stop your heads from exploding?

**Comment by dktapps** [comment]
@JUSTaMOD laugh

**Comment by flaxues** [comment]
@MCPEPluginer16 Just update the plugin to PHP7
