### ISSUE TITLE
0.15.0 bug

### ISSUE THREAD

**Issue by RainMa22** [iTXTech/Genisys#1233]
Apple system use 0.15.0 can not do many things at Survival mode.
If you are using Apple system 0.15.0 get in to a Genisys(PC) server,you can't open chests,craft someting and destroy block.
PC Genisys_1.2dev-485.phar	
PHP7
PC
Please comment below if you experience any issues not described here.

**Comment by PeratX** [comment]
Sorry I don't have an iOS device. Can you check if you have any Permission plugins

**Comment by JUSTaMod** [comment]
I can confirm IOS works fine with normal Genisys, no plugins. (And with plugins of course, but that's different for everyone.)

**Comment by Driesboy** [comment]
wrong it work in IOS!

**Comment by RainMa22** [comment]
@JUSTaMod  I am sure it is Survival mode.
