### ISSUE TITLE
Weather in Pocketmine SRC ?

### ISSUE THREAD

**Issue by xHFx** [iTXTech/Genisys#1234]
#### Issue description

Hello I wanted to know where can I find the hardcoded weather function in Genisys

 Edit

What initiates the weather file so I can remove the function so I can disable weather

#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by daniktheboss** [comment]
"Facepalm".... spammers... why do u keep on opening issues? Why can u just comment on the open issues??

**Comment by xHFx** [comment]
there is no open issues for this

**Comment by daniktheboss** [comment]
#1180

**Comment by JUSTaMod** [comment]
#1180

**Comment by PeratX** [comment]
Check #1180 and I am already working on this

**Comment by xHFx** [comment]
Thats not what Im asking where in genisys does it initiate for wheather to even be triggered

**Comment by legoboy0215** [comment]
Why not just look through the code yourself? And the bug was fixed.

**Comment by daniktheboss** [comment]
Lol ikr! If I have a problem I either wait for it to be fixed or try to fix it ny self (always fail) lol
