### ISSUE TITLE
Client does not update using worldedit

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#1236]
I need to log out of server and log back in for changes to take effect.

**Comment by ishitatsuyuki** [comment]
Block updates are known problem. Closing for duplicate.

**Comment by robske110** [comment]
I 'hacked' this here: https://github.com/ClearSkyTeam/ClearSky/commit/bec1a7b854c04502dac242f507c3f869a5000555
Maybe we should add sth in pocketmine.yml/whateverconfigfile to let the user choose to either overload (DDOS the clients) the network with that or random blocks stuck around.
