### ISSUE TITLE
Memory and Raklib issue

### ISSUE THREAD

**Issue by FaanMaario** [iTXTech/Genisys#1239]
#### Issue description

Sometimes, the memory starts bugging and because of that the Raklib crashes. I have enough memory for my server, and I don't know why it happends.
#### Steps to reproduce the issue

Everytime I start my server, after 10-20 min, the problem begins.
#### OS and versions

* Genisys: Genisys1.2dev489 (running by source)
* PHP: PHP7
* OS: Linux

#### Crashdump, backtrace or other files
```
mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 31457280) (tried to allocate 69632 bytes) in /home/mcpe-3/src/raklib/server/UDPServerSocket.php on line 59
[36m[18:36:01] [m[31m[Server thread/EMERGENCY]: RakLib crashed![m
[36m[18:36:01] [m[31m[Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed
```

**Comment by Muqsit** [comment]
Wait..Which Linux flavor?

**Comment by ishitatsuyuki** [comment]
Out of memory.

**Comment by legoboy0215** [comment]
This issue is very hard to solve. It is either plugin, world or Genisys problem. Most likely world or plugin.
