### ISSUE TITLE
[Idea] Add the ban more..

### ISSUE THREAD

**Issue by seetch** [iTXTech/Genisys#124]
Hi, long time I want you to do the command  /ban with several parameters.

/ban nick reason banned until 
banned until - time ban 

just do it! just do it!

**Comment by MrDoni98** [comment]
+

**Comment by BogdanMakarchuk** [comment]
++

**Comment by gaoyichuan** [comment]
+1 for this

**Comment by egr7v8** [comment]
+

**Comment by CrayonDing** [comment]
OK.I will try adding it.

**Comment by GalvinGao** [comment]
+

**Comment by CrayonDing** [comment]
please try the newest version
