### ISSUE TITLE
/time stop does not work

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1243]
#### Issue description

If you do /time stop to stop the time, it doesn't stop it, just continues.
#### Steps to reproduce the issue

Go on a Genisys server
Do /time set 0 and /time stop
Watch time continue normally.
#### OS and versions

* Genisys: 1.2-dev1e804e4
* PHP: 7
* OS: Android

#### Crashdump, backtrace or other files
```
N/A
```

**Comment by ishitatsuyuki** [comment]
Outdated version.
