### ISSUE TITLE
Names with spaces support?

### ISSUE THREAD

**Issue by daniktheboss** [iTXTech/Genisys#1244]
### Issue description
Ok it might be impossible but can u make that genisys supports names with spaces? Many people with xbox live has spaces in name.

#### Steps to reproduce the issue
Login to Xbox live and sever with space in name.

#### OS and version
* Genisys: latest 
* PHP: 7 
* OS: win 10

#### Crashdump, backtrace or other files
Name name-> logged out due to invalid name

**Comment by SleepSpace9** [comment]
For security reason I would not support names with blank spaces. Otherwise you could do some hacking with hard coded server commands.

**Comment by Muqsit** [comment]
There will be issues if spaces were add. Eg: If you use "Johnny Appleseed". $sender->getName() might take it as two words, "Johnny" and "Appleseed". There might be similar issues in PM API. Plus, PC servers don't have this too!
