### ISSUE TITLE
FloatingTextParticle no longer working

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Genisys#1245]
#### Issue description

There is only a shadow where the text should be. Server-side issue : InPvP fixed it (using MiNET)
(Was working with 0.14.3)

#### Steps to reproduce the issue

Spawn a FloatingTextParticle

#### OS and versions

* Genisys: Genisys version 1.2dev "Ikaros" (API 2.0.0)
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by kabluinc** [comment]
could it be something to do with this? https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/Player.php#L1428
something @jojoe77777 referenced in his slapper repository

**Comment by Guillaume351** [comment]
@kabluinc I tried to add this tag, but it didn't work :/

**Comment by EnderKenji** [comment]
Hopefully this will be fixed very soon ._. Cuz its important tho

**Comment by seetch** [comment]
I have statistics players on the server  through the FloatingTex Particle and he stopped working, please fix.
