### ISSUE TITLE
Pressure Plate/button issue

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1247]
#### Issue description

Whenever I got under a button or touch a button/pressure plate, it looks like I am standing inside a block
#### Steps to reproduce the issue

1.) Place a pressure plate on a fence
2.) stand under/next to pressure plate
3.) Notice me senpai
#### OS and versions

* Genisys: 1.2dev
* PHP: 7.0.4
* OS: Linux Mint 64-bit

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dktapps** [comment]
MCPE bug, see https://bugs.mojang.com/browse/MCPE-14544
