### ISSUE TITLE
Original Genisys Binary File

### ISSUE THREAD

**Issue by Pav155** [iTXTech/Genisys#1248]
Hello, I am using Genisys and I very like it but I need original binary file but I can not find it and on the internet too... :( Please, help me. I found only PocketMine-MP but I am not sure it is good and latest version. If anyone know how to get the original Genisys binary file or latest PocketMine-MP binary file, let me know there. Thanks all!

**Comment by dktapps** [comment]
https://jenkins.mcper.cn/job/Genisys-master/

**Comment by dktapps** [comment]
Try reading the description next time.

**Comment by Pav155** [comment]
Yes but I need "bin" file and it is not there :/, sorry, I am maybe idiot...

**Comment by ishitatsuyuki** [comment]
Only Docker installation is supported. Otherwise build it yourself.
