### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by Pav155** [iTXTech/Genisys#1249]
Sorry dktapps and all from Genisys team but I did not find it on the website you wrote me. Yes, I am maybe idiot..., sorry :/ but I did not find there "bin" file. I tried everything...today 2 hours, Docker too, installer.sh but nothing works (Linux). I really do not know what to do. Sure, you can ban me for this stupid issue :(.

**Comment by dktapps** [comment]
Continue to issue-spam and you will be banned.

**Comment by Pav155** [comment]
:-) I found it! Bye, thanks.
