### ISSUE TITLE
Can't start latest build

### ISSUE THREAD

**Issue by flash586** [iTXTech/Genisys#125]
What is it problem? https://goo.gl/photos/g4QPn42qxmi8U6kD8 I have this file in directory, but I see way is not correct.

**Comment by Driesboy** [comment]
you dont have the php7 file

**Comment by flash586** [comment]
I checked. I have.

**Comment by Driesboy** [comment]
do you have the latest start.sh

**Comment by flash586** [comment]
Yes

**Comment by Driesboy** [comment]
and named to php7

**Comment by flash586** [comment]
Yes, sir

**Comment by Driesboy** [comment]
ok

**Comment by flash586** [comment]
Ок? You can't help me?
22 янв. 2016 г. 19:07 пользователь "Driesboy" <notifications@github.com>
написал:

**Comment by mixailenko5** [comment]
flash586, i fixed it https://github.com/iTXTech/Genisys/commit/ac856b94754b3823d77149fd354d574272ff1ea3#diff-2d1e10be627862670b5dbf088e1c5196

**Comment by mixailenko5** [comment]
Its fix segmentation error

**Comment by haniokasai** [comment]
latest build is still compilimg?

**Comment by flash586** [comment]
Yes

**Comment by PeratX** [comment]
Fixed...
