### ISSUE TITLE
How to install on linux

### ISSUE THREAD

**Issue by daniktheboss** [iTXTech/Genisys#1250]
Not really an issue but how do u install genisys on Linux x32?

**Comment by ishitatsuyuki** [comment]
Thank you for spamming. Goodbye, you will be banned.

**Comment by 1wowjustwow** [comment]
Are u kidding me??? I just opened 2 issues! And I really didn't know how to install on linux! So I just needed help from u guys! The guy who needed the "bin" opened 2 issues and u just answered his question??? Wow

**Comment by 1wowjustwow** [comment]
U could have said #308!!!!

**Comment by gaoyichuan** [comment]
**NO SUPPORT REQUEST HERE!!**
