### ISSUE TITLE
Floating Text .... 

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#1252]
# Floating Text Bug
#### Issue description
There have leads on floating texts.
![image](https://cloud.githubusercontent.com/assets/15629214/16300317/e7dd7f64-3971-11e6-9a02-9df6b4dc0023.png)
it happens on MCPE and MC Win10

#### Steps to reproduce the issue
When u join server? lol there will have a lead on FloatingText. 
You can checkout ConflictPE Servers to see whts going on.
KitPVP: pvp.conflictpe.net : 19132

#### OS and versions

* Genisys: 1.2dev-495
* PHP: 7
* OS: Win10 & Android

**Comment by dktapps** [comment]
I'll fix it in a second.

**Comment by Driesboy** [comment]
i have a fix

**Comment by dktapps** [comment]
@EnderKenji Would you like to try https://gitlab.com/itxtech/genisys/builds/1975130/artifacts/download please?

**Comment by EnderKenji** [comment]
working well @dktapps Thanks for the fix

**Comment by Driesboy** [comment]
what floating text plugin you use

**Comment by Driesboy** [comment]
can you send?
