### ISSUE TITLE
Player Network Send and Player Network Receive give a lot lagg

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#1254]
#### Issue description

see this: https://timings.aikar.co/?url=17743316
#### Steps to reproduce the issue

/timings on
/timings paste

#### OS and versions

* Genisys:496
* PHP:7.0
* OS:windows

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
CLOSED DUPLICATE #1059

**Comment by Driesboy** [comment]
Oops sorry
Op 23-jun.-2016 15:05 schreef "Tatsuyuki Ishi" <notifications@github.com>:
