### ISSUE TITLE
Are you adding mcrypt into php?

### ISSUE THREAD

**Issue by samalero** [iTXTech/Genisys#1255]
#### Issue description
When start server from docker:
```
Notice: Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' in phar:///srv/genisys/genisys.phar/src/pocketmine/utils/Utils.php on line 215

Notice: Use of undefined constant MCRYPT_MODE_ECB - assumed 'MCRYPT_MODE_ECB' in phar:///srv/genisys/genisys.phar/src/pocketmine/utils/Utils.php on line 215
```
Although such a server does not affect the operation ....

#### Steps to reproduce the issue
start server from docker

#### OS and versions

* Genisys:  9f7393d
* PHP: 7
* OS: Debian Jessie

#### Crashdump, backtrace or other files
```

```

**Comment by samalero** [comment]
and sqlite
```
Warning: SQLite3Stmt::execute(): Unable to execute statement: unable to open database file in phar:///srv/genisys/plugins/essentialsTP_v1.1.0.phar/src/essentialsTP/essentialsTP.php on line 83

Warning: SQLite3Stmt::execute(): Unable to execute statement: unable to open database file in phar:///srv/genisys/plugins/essentialsTP_v1.1.0.phar/src/essentialsTP/essentialsTP.php on line 90

Warning: SQLite3Stmt::execute(): Unable to execute statement: unable to open database file in phar:///srv/genisys/plugins/essentialsTP_v1.1.0.phar/src/essentialsTP/essentialsTP.php on line 97
```

although essentials_tp.db file there.

**Comment by Pav155** [comment]
I have original bin files from Genisys and it is running great... I think, you are using it worse or I do not know. I did not try it using Docker because I did not want to have problems with install so I find original and latest way to install Genisys bin files.

**Comment by samalero** [comment]
Docker is better in that it provides ready php binaries and starts the server in a separate container. But I would like to understand why these messages appear.

**Comment by ishitatsuyuki** [comment]
We're planning to switch to OpenSSL, which is included and faster. The SQLite problem is likely due to your faulty permissions, try delete the file and let the server to create that.
