### ISSUE TITLE
[0.15] Entity-related client crash

### ISSUE THREAD

**Issue by Heroata** [iTXTech/Genisys#1256]
#### OS and versions

* Genisys: 1.2
* PHP: 7
* OS: Mac OS X

    I know, problem's temp fix is published at [here](https://github.com/iTXTech/Genisys/issues/1206). But  I found the main reason so I want to post this issue. I saw somebody saying the reason is unknown blocks. 

    It is not an unknown block problem. There is a block id problem on 125 and 126 ids [126(pc) instead of 158(pe)] but the main reason is this entity.

![image](https://cloud.githubusercontent.com/assets/10375421/16317667/c42f4386-3994-11e6-9f00-f477d782ba56.png)

 I'm not a master of MCEdit and dunno what are this red entities. When you select and delete this "entities", client is no longer crashing. Maybe wrong but I thought main developers don't know the main reason (because they saying it's a unknown block problem) so they didn't fix it that's why I'm submiting this issue. If I'm wrong, sorry.. and sorry for my bad english.

**Comment by XFuryMCPE** [comment]
Interesting.

**Comment by legoboy0215** [comment]
Slabs...

The red stuff are tile entities like chests, sign.

**Comment by gaoyichuan** [comment]
So could you give us more information about the red entites? What's their id? Are their tiles?

**Comment by Heroata** [comment]
I have no idea what are they. Now I'm gonna enter to map from pc and explore them :p

**Comment by Heroata** [comment]
They are red and entity. Thats what I know. I can't select them easily as normal blocks on mcedit.

**Comment by legoboy0215** [comment]
They are either signs, chests, stuff with inventories I believe.

**Comment by Adam1609** [comment]
So that's why the client always crash because of PC's undefined block!

**Comment by Heroata** [comment]
I'm sure they are not chests and signs or a block.

**Comment by CubeFromSpace** [comment]
MCedit is supposed to be used for Minecraft PC, not PE

**Comment by CubeFromSpace** [comment]
@Heroata they most likely are. Either that or they are regular entities such as pigs or cows

**Comment by Heroata** [comment]
But they aren't any entity when I scanned with EntityManager or ClearLagg

**Comment by CubeFromSpace** [comment]
Then try looking at the locations of the unknown entities in the real game.

**Comment by Driesboy** [comment]
netherchests!

**Comment by dktapps** [comment]
I'm investigating this. I have a world in which I still frequently crash when I join even when the unrecognized block problem is not involved. I generally have to remove all entities before I can join again.

**Comment by legoboy0215** [comment]
Weird though. This has NEVER happened to me.

**Comment by dktapps** [comment]
I'm getting frequent crashes on join while working with potions. I don't know if it's a coincidence or if the two are related

**Comment by CubeFromSpace** [comment]
Brewing stands are block entities, along with any block that can hold items. (not just chests)

**Comment by dktapps** [comment]
@CubeFromSpace interesting. There's only one problem with that theory - I wasn't using a brewing stand.

**Comment by ChavoJoker** [comment]
@Heroata @dktapps I did the same thing in mcedit but I found a another way to fix my issue. You must have ClearLagg plugin for this to work.
1. Downgrade your server to 14.3 (I used IM since the service I use only offers that old version)
2. Downgrade your minecraft app to 14.3 as well
3. When all set up, go in game and in EVERY section of your map (especially where you crash) do the command to clear the enitities and mobs
4. Upgrade back to 0.15 then go to your section where it used to crash your game and it shouldn't crash anymore

This worked for me since I never crashed in a section of a map before the update came

**Comment by CubeFromSpace** [comment]
@chavojoker you can' downgrade Minecraft PE.

**Comment by Muqsit** [comment]
@CubeFromSpace You can. Suck it, iOS xD
@ChavoJoker Are you sure? I have already tried this and it didn't work!

**Comment by dktapps** [comment]
I think there may be some confusion here. This is _a_ problem, not _the_ problem. Attempting to render unknown blocks is one problem. This is another. I think I'll update the title.

**Comment by ChavoJoker** [comment]
@Muqsit when you downgraded to 14.3, did you do the clearlagg command more than once in every section of your map?
@CubeFromSpace I don't know if you were trying to put the letter "t" in "can" in your message or if you were asking a question

**Comment by Muqsit** [comment]
@ChavoJoker yes.
/clearlagg killmobs
/lagg clear

On every chunk, more than once.


Btw, the red blocks are mobs.
https://github.com/mcedit/mcedit/wiki/FAQ

**Comment by ChavoJoker** [comment]
@Muqsit I do "/clearlagg clearall" but if it's the same for you and it doesn't solve your problem then I guess there is some block/entity you got to get rid of. Yeah I realized later that they were mobs xD one was a wolf when I downgraded to 14.3

**Comment by Muqsit** [comment]
@ChavoJoker Did that, didn't work. But thanks anyways!

**Comment by Heroata** [comment]
I used clearlagg and entitymanager and no luck with any of them. It says 0 mobs bla bla deleted..

**Comment by Heroata** [comment]
Sorry Im new at github. @ChavoJoker I'm gonna try it and report to you.

**Comment by ChavoJoker** [comment]
@Heroata okay good luck :)

**Comment by PeratX** [comment]
I think this is BlockEntity without Block, and this will cause client crash.

**Comment by Muqsit** [comment]
I finally fixed my issue by removing all update blocks from the spawn. 👌

Took me 2 hours.

**Comment by ChavoJoker** [comment]
@Muqsit update blocks? What type of blocks are those? (I can be slow sometimes forgive me). Also did you do it by downgrading server?

**Comment by Muqsit** [comment]
Beacons

**Comment by Muqsit** [comment]
Yeah I downgraded the server to 14.3, then removed the update blocks then upgraded back to 15...it was a pain but worth it lol

**Comment by ChavoJoker** [comment]
@Muqsit That's great that you fixed your problem :D and yeah dedicated to keep your map alive is well worth it :)

**Comment by Heroata** [comment]
@Muqsit how did you remove all update blocks?

**Comment by ChavoJoker** [comment]
@Heroata You could try to go back to mc edit and and select the area or maybe the whole map and then click on "Delete Tile Ticks" those should remove update blocks

**Comment by Heroata** [comment]
@ChoveJoker ok but when I select all map or an area, how do I understand is the removing proccess completed?

**Comment by Heroata** [comment]
@ChavoJoker oh there was no loading popup when I do delete entities. So asked. Ty

**Comment by RocoWayne** [comment]
There is a solution at least?

**Comment by Heroata** [comment]
I wasnt here for half month. Is this issue fixed naturally?
