### ISSUE TITLE
Crashing?

### ISSUE THREAD

**Issue by SavionLegendZzz** [iTXTech/Genisys#1257]
#### Issue description

So when i join the BUHC gamemode on my server and kill someone i crash. I coded it so it would unload the world then replace it.

#### Steps to reproduce the issue

Join my server [mg.obliviouspe.net:19132] join buhc1v1[BuildUHC1v1] and kill a player
#### OS and versions

* Genisys: 1.2-dev
* PHP: php 7
* OS: Linux

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Version too broad. No crashdump. Closing.
