### ISSUE TITLE
Some mobs shouldn't despawn (leak-fix branch)

### ISSUE THREAD

**Issue by Thecraftdu34** [iTXTech/Genisys#1258]
Hello, with the last update "memory-leak-fix · c7b56cd3   latest
Despawn entities that are not in the vicinity of players" slapper despawn and didn't respawn so slapper it's deleted.

**Comment by ABAxStorm** [comment]
Update your Slapper plugin by visiting their GitHub.

**Comment by ishitatsuyuki** [comment]
It's not a supported branch. Use a appropriate title.

**Comment by jojoe77777** [comment]
> Update your Slapper plugin by visiting their GitHub.
Nothing wrong with Slapper.

**Comment by dktapps** [comment]
I'm aware of this issue. To be honest it wasn't unexpected.

**Comment by Thecraftdu34** [comment]
It's not fixed. You plan to solve it?

**Comment by dktapps** [comment]
@Thecraftdu34 no, I plan to leave it unfixed and just waste the time I spent on it. Do think before asking stupid questions.

**Comment by Thecraftdu34** [comment]
Good mentality. You didn't have the notion of respect.

**Comment by dktapps** [comment]
@Thecraftdu34 I have respect for people who don't waste my time asking stupid questions.
