### ISSUE TITLE
Windows 10 Crafting is very buggy!

### ISSUE THREAD

**Issue by austina1212** [iTXTech/Genisys#1261]
#### Issue description
Hello, My issue is that when crafting in windows 10 the items un-craft themselfs... 

#### Steps to reproduce the issue
Put Items in crafting table to make a item... then craft! (Then Check inventory!)

#### OS and versions

* Genisys: Build #501
* PHP: 7
* OS: Centos 7

#### Crashdump, backtrace or other files
```
*There Was no crash dump*
```

**Comment by JUSTaMod** [comment]
#444 
They know.

**Comment by gaoyichuan** [comment]
duplicate with #444
