### ISSUE TITLE
(Not) Enchanted Golden Apple 

### ISSUE THREAD

**Issue by corytortoise** [iTXTech/Genisys#1262]
#### Issue description
I assume this is not a very large issue, and isn't a priority, but I have noticed that any Enchanted Golden Apples in servers do not glimmer or glow like Enchanted items are supposed to. Also, it shares the same name as a regular Golden Apple.

#### Steps to reproduce the issue
1) Give or craft an Enchanted Golden Apple and a regular Golden Apple. Notice that they look exactly the same.

#### OS and versions
* Genisys: Genisys 1.2dev "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0.0 alpha (protocol version 81)
* PHP: 7
* OS: Linux/Ubuntu

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by gaoyichuan** [comment]
Yes, I got this bug too

**Comment by gaoyichuan** [comment]
@dktapps The issue is that the golden apples show exactly the same in your item bar. You can try to give them and you will find the issue

**Comment by dktapps** [comment]
@gaoyichuan I made 2 commits, everything except the name is fixed now. The name still showing as "Golden Apple" is an MCPE bug.

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/commit/579d2b609effb6fd5d9e405654fb18e855d40fbb
https://github.com/iTXTech/Genisys/commit/fb2be3a7d2c2e38802b739b15649043f383cd4d6
