### ISSUE TITLE
Nether sky

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#1263]
#### Issue description
When you die in the nether and spawn on a diffrent world tthe sky is still red. Btw its pretty awesome :) 

#### Steps to reproduce the issue
Make a nether portal, then go to the nether. Die and respawn on diffrent world the sky is still red

#### OS and versions

* Genisys: #629 
* PHP:latest
* OS:windows 10

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Adam1609** [comment]
This is exactly the problem when I can't go to nether because of lag, and when I spawn back, the sky is red!

**Comment by dktapps** [comment]
I can't reproduce this. Also "latest" is not a valid version. Please update your version.

**Comment by GlitchPlayer** [comment]
I can reproduce this, Confirmed

**Comment by TheClimbing** [comment]
Right now I'm on vacation and can't tell exactly which is my version. But i installed Genisys from source two days ago. I guess since someone can reproduce it its a valid issue?

**Comment by Dog2puppy** [comment]
When I had first setup my server, I was playing around, went to the nether, and when I was in the nether, it looked EXACTLY like the world I made the portal in, the only differnce was the sky was red.

**Comment by TheClimbing** [comment]
I see there is the cannot reproduce tag.Ok lets try it like this ammm first goo to the nether in creative mode then do "/kill" and respawn now your main world will have the nether sky.

**Comment by TheClimbing** [comment]
Ok it seems the last updates have some backfire because now when i die in the nether using the "/kil" command i just tap respawn aaand nothing happens im sitting there unable to do anything except leave and join the server again

**Comment by dktapps** [comment]
@TheClimbing I can reproduce _that_ bug, yes. Currently unsure if it's an MCPE bug or not. For some reason the client does not send the Respawn action when you're in the Nether. Under investigation.

**Comment by dktapps** [comment]
Please update to the latest build and test again. https://github.com/iTXTech/Genisys/commit/1ba57d4a53af9014e8d9478983ee09b1f287ff4d fixes the problem with dying and not respawning, it may fix other things too.

**Comment by ZedCee** [comment]
Couldn't reproduce the red skies error, however the issue with dying in the nether can definitely be reproduced.  Among other issues this caused was an inability to execute any commands after dying then /mw tp out of the world; got mobility back but no command line control.  Going to test the fix now.

**Comment by dktapps** [comment]
@ZedCee I _did_ say _update_ and test... :P

**Comment by ZedCee** [comment]
@dktapps :dunce  Yes... yes I suppose you did :laughing: 
Guess I'm just covering bases, OSes play funny with their differences.
Or I'm probably just excited to start helping out  :smile:

**Comment by ZedCee** [comment]
@TheClimbing @GlitchPlayer @Dog2puppy @Adam1609 
Are you still experiencing issues with this?  If not, I think the issue can be closed. 
If any report the issue still exists, I will reopen this issue.  
I liked the idea of a red sky so much, I set my nether to normal2 generation, but in my many deaths back and forth still haven't been able to reproduce it.

**Comment by GlitchPlayer** [comment]
Yep. Not happening anymore

**Comment by ZedCee** [comment]
@GlitchPlayer Thanks for checking in.  Helps speed development along and give us a heads up.
