### ISSUE TITLE
Armor damage

### ISSUE THREAD

**Issue by SavionLegendZzz** [iTXTech/Genisys#1266]
#### Issue description

Not an issue a request. Please add an option to disable armor taking damage because i run a minigames server and this is a problem.
#### OS and versions

* Genisys: 1.2-dev
* PHP: php7
* OS: Linux

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by gaoyichuan** [comment]
That should be a plugin's task. Not something a vanlia server should do

**Comment by SavionLegendZzz** [comment]
Well the genisys fucking added it so armor takes damage and theres no way i can stop it

**Comment by dog194** [comment]
@SavionLegendZzz  Plz provide the conflicting minigame plugins. Then i will have a look.

**Comment by SavionLegendZzz** [comment]
@dog194 there is nothing wrong with my plugins just add a option to disable armor damage

**Comment by GlitchPlayer** [comment]
It cant!! Its not like a mod or modified server software. Plugins are the
one who modifies it. Create a plugin that disables armor
