### ISSUE TITLE
what is it

### ISSUE THREAD

**Issue by RainMa22** [iTXTech/Genisys#1267]
what is this
![img_20160624_151358](https://cloud.githubusercontent.com/assets/20056243/16352390/408ff9a2-3a2b-11e6-911d-ce9be43966a9.jpg)
![img_20160624_151411](https://cloud.githubusercontent.com/assets/20056243/16352391/40a46018-3a2b-11e6-9ff6-f9d9a9df1beb.jpg)
![img_20160624_151416](https://cloud.githubusercontent.com/assets/20056243/16352392/40b573bc-3a2b-11e6-94be-c850b5a3cfd9.jpg)
![img_20160624_151420](https://cloud.githubusercontent.com/assets/20056243/16352393/40c72652-3a2b-11e6-9bc2-c0e171bdd895.jpg)
I just open the server and come in to server so it happen.

Genisys_1.2dev-508.phar	(PC)

PHP7
pe0.15

**Comment by corytortoise** [comment]
I assume giving the entire error would be more useful, and did anything happen because of this, as far as you know?

**Comment by RainMa22** [comment]
I don't know

**Comment by ishitatsuyuki** [comment]
Your CPU is too weak. It's due to overload.

Can't you just right click and copy?

**Comment by gaoyichuan** [comment]
@ishitatsuyuki I think this was fixed long long ago by ignoring the error..

**Comment by dktapps** [comment]
Looks like we missed one. I'll fix this in a second.
