### ISSUE TITLE
Login TimeOut

### ISSUE THREAD

**Issue by AkramYTaM** [iTXTech/Genisys#1268]
Hi

My server has equiped to Genisys 15.X 

With à one bug has appared 

This bug is "LOGIN TIMEOUT" 

On my server is 0 plugin 

How fix this bug??

AkramYTa 

(Sorry for my bad english)

**Comment by ishitatsuyuki** [comment]
Closing for not following template.

**Comment by AkramYTaM** [comment]
Bonjour 

Merci d'avoir contacter notre owner

nous vous répondrons très vite

TheEnormusFR

Hello

Thanks for contact owner: AkramYTa

TheEnormusFR
