### ISSUE TITLE
Login TimeOut

### ISSUE THREAD

**Issue by AkramYTaM** [iTXTech/Genisys#1269]
Hi 

I have one server hosted on HostMyServers 

With i have adding Genisys 15.0 with a one bug was appared 

With on RCON this bug is Login TimeOut 

I have 0 plugins 

Help me for fix this bug

Information for my Genisys is here: 
* Genisys: 15.X 
* PHP:7.0
* OS: LINUX SERVER HOSTED ON HOSTMYSERVERS

**Comment by PeratX** [comment]
What is with on RCON

**Comment by gaoyichuan** [comment]
@PeratX  I think he means with RCON on

**Comment by ishitatsuyuki** [comment]
Closing for not following template. Provide more information.

**Comment by flaxues** [comment]
I think you need to contact your hosting about this...
