### ISSUE TITLE
Players keep disconnected sometimes

### ISSUE THREAD

**Issue by TonyWAV** [iTXTech/Genisys#1271]
#### Issue description

Sometimes the server laggs when 80-90+ players join and need to restart the this software again to remove the lagg.
#### OS and versions

* Genisys: latest
* PHP: latest
* OS: windows server 2012

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by flaxues** [comment]
Could you maybe post a timings?

/timings on

and when it begins to lagg do this:

/timings paste

and paste the aikar.co link here!

**Comment by Driesboy** [comment]
same i cannot host 70p without lagg

**Comment by gaoyichuan** [comment]
Use a plugin to automatically restart the server is the best solution

**Comment by Driesboy** [comment]
i use that

**Comment by flaxues** [comment]
I can run a server with a average of 100 players without lagg... Just network lag (long distance)

**Comment by Driesboy** [comment]
i have alot of minigames 👍

**Comment by ishitatsuyuki** [comment]
Closing in favor of #1059.
