### ISSUE TITLE
monster block set monster bags 0.15.0

### ISSUE THREAD

**Issue by kamata4649** [iTXTech/Genisys#1272]
#### OS and versions

* Genisys:latest
* PHP:7.0.4
* OS:ubuntu 14

-------------------------bugs--------------------------

monster spawn block bags.
monster spawn block many many set World in teleport the Player crash.
![screenshot_20160626-004458](https://cloud.githubusercontent.com/assets/17876451/16357673/1b8b4cb6-3b38-11e6-8652-a35461262467.png)

```

**Comment by dktapps** [comment]
Already reported. #1180

**Comment by gaoyichuan** [comment]
I can't quite understand you, if you can speak Chinese than use it
