### ISSUE TITLE
monster block set the monster bugs 0.15.0

### ISSUE THREAD

**Issue by kamata4649** [iTXTech/Genisys#1273]
#### Issue description
monster block bugs
monster block on rope bugs.

日本語 --Japanese--
モンスターブロックにモンスターを入れると
縄が回転します
それを多数設置しますとクラッシュします

#### Steps to reproduce the issue
monster block set ↓
monster block on monster egg set.

日本語 --Japanese--
モンスターブロックを設置
モンスターブロックにモンスターを入れる

#### OS and versions

* Genisys:latest
* PHP:latest
* OS:ubuntu

#### Crashdump, backtrace or other files
```


```

**Comment by ishitatsuyuki** [comment]
'latest' is invalid. Write a number.

**Comment by kamata4649** [comment]
I have written

**Comment by ishitatsuyuki** [comment]
WRITE A NUMBER OR GIT HASH

**Comment by gaoyichuan** [comment]
What's #1180? Where did you got it?
