### ISSUE TITLE
Memory leak chapter 2

### ISSUE THREAD

**Issue by WolfTroll** [iTXTech/Genisys#1278]
#### OS and versions

* Genisys: v1.2dev-520
* PHP:7.0.3
* OS:linux

#### Crashdump, backtrace or other files
```
Genisys Crash Dump Mon Jun 27 08:43:58 ACT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/Player
Line: 4444
Type: E_ERROR

Code:
[4435] 	public static function getChunkCacheFromData($chunkX, $chunkZ, $payload, $ordering = FullChunkDataPacket::ORDER_COLUMNS){
[4436] 		$pk = new FullChunkDataPacket();
[4437] 		$pk->chunkX = $chunkX;
[4438] 		$pk->chunkZ = $chunkZ;
[4439] 		$pk->order = $ordering;
[4440] 		$pk->data = $payload;
[4441] 		if(Network::$BATCH_THRESHOLD >= 0){
[4442] 			$pk->encode();
[4443] 			$batch = new BatchPacket();
[4444] 			$batch->payload = zlib_encode(Binary::writeInt(strlen($pk->getBuffer())) . $pk->getBuffer(), ZLIB_ENCODING_DEFLATE, Server::getInstance()->networkCompressionLevel);
[4445] 			$batch->encode();
[4446] 			$batch->isEncoded = true;
[4447] 			return $batch;
[4448] 		}
[4449] 		return $pk;
[4450] 	}
[4451] 
[4452] 
[4453] }
[4454] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.2dev #520 [Protocol 81; API 2.0.0]
uname -a: Linux centos7.is.cc 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
WorldEdit 3.2 by ByZikenPE for API(s) 1.13.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
iProtector 3.1a by LDX for API(s) 1.9.0
SuperKits 1.3.0 by WolfTroll for API(s) 1.13.0, 1.13.1, 2.0.0
HereAuthFS 2.0.0 by Wolf-Edit for API(s) 2.0.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
RandomMOTD 0.1 by Taki21 for API(s) 1.14.0
SignTP 1 by remote_vase for API(s) 1.0.0, 2.0.0, 3.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
1vs1 1 by WolfTroll for API(s) 1.0.0, 1.1.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

```

**Comment by dktapps** [comment]
Another one? Dear God. I'm gonna spend the rest of my life fixing these.

**Comment by dktapps** [comment]
How long did it take to crash? As in what was the uptime?

**Comment by WolfTroll** [comment]
Exactly 10-12 minutes.

**Comment by dktapps** [comment]
o.o

**Comment by WolfTroll** [comment]
It is the only one who came . Before it closed faster but that are already fixed :)

**Comment by WolfTroll** [comment]
Now only this problem

**Comment by PeratX** [comment]
Check your plugins! Try to disable 'MSpawns'

**Comment by dktapps** [comment]
@WolfTroll I had a feeling there would be more leaks. PHP is so horrible for this kind of thing. It's like an onion.

**Comment by dktapps** [comment]
I'm going to see if I can make crashdumps more informative

**Comment by WolfTroll** [comment]
Hey. MSpawn off already. Waiting the crash or fix

**Comment by dktapps** [comment]
@WolfTroll Do you have debug.commands turned on in pocketmine.yml?

**Comment by WolfTroll** [comment]
debug:
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables /status, /gc
 commands: true

**Comment by dktapps** [comment]
yep
When the memory usage gets to 500MB or so, run /dumpmemory. Put the output into a zip file and send me a link.

**Comment by WolfTroll** [comment]
@PeratX disable Mspawn not work.
Run /dumpmemory say: "usage: /dumpmemory 981A22"

**Comment by dktapps** [comment]
@WolfTroll yeah. Type in `/dumpmemory 981A22`. When it finishes, there will be a memory dump folder in your Genisys folder. Compress that, upload it and send me a link to it

**Comment by WolfTroll** [comment]
http://www.mediafire.com/?qyuom0sv6afptw8 sorry for waiting

**Comment by dktapps** [comment]
@WolfTroll No problem. Thanks very much.

**Comment by dktapps** [comment]
@WolfTroll Please, could you try removing the Slapper plugin from your server?

**Comment by WolfTroll** [comment]
Ohh :( ok. Already delete.

**Comment by WolfTroll** [comment]
In 15 minutes coment post

**Comment by WolfTroll** [comment]
Not fixed. New error

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/Server
Line: 2248
Type: E_ERROR

Code:
[2239] 			if($p->isConnected()){
[2240] 				$targets[] = $this->identifiers[spl_object_hash($p)];
[2241] 			}
[2242] 		}
[2243] 
[2244] 		if(!$forceSync and $this->networkCompressionAsync){
[2245] 			$task = new CompressBatchedTask($str, $targets, $this->networkCompressionLevel);
[2246] 			$this->getScheduler()->scheduleAsyncTask($task);
[2247] 		}else{
[2248] 			$this->broadcastPacketsCallback(zlib_encode($str, ZLIB_ENCODING_DEFLATE, $this->networkCompressionLevel), $targets);
[2249] 		}
[2250] 
[2251] 		Timings::$playerNetworkTimer->stopTiming();
[2252] 	}
[2253] 
[2254] 	public function broadcastPacketsCallback($data, array $identifiers){
[2255] 		$pk = new BatchPacket();
[2256] 		$pk->payload = $data;
[2257] 		$pk->encode();
[2258] 		$pk->isEncoded = true;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.2dev #520 [Protocol 81; API 2.0.0]
uname -a: Linux centos7.is.cc 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by dktapps** [comment]
Okay. Can you send me your server folder please (without the `worlds` folder and the `players` folder)?  It'll be faster that way.

**Comment by WolfTroll** [comment]
Plugins?

**Comment by WolfTroll** [comment]
And bin folder?

**Comment by dktapps** [comment]
@WolfTroll The whole server folder, yes. Just don't include the worlds folder or the players folder

**Comment by WolfTroll** [comment]
Folder bin have dats of PHP7  send?

**Comment by dktapps** [comment]
@WolfTroll yes, just send me the whole thing

**Comment by JUSTaMod** [comment]
I'm starting to feel bad for you @dktapps these memory issues seem to be a frickin' pain.

**Comment by dktapps** [comment]
@JUSTaMod yes they certainly are. It looks like I've only peeled the first layer off our onion. But hey, nobody's forcing me to do this.

**Comment by JUSTaMod** [comment]
@WolfTroll i noticed you have worldedit. Where on planet earth did you find that?? I can't manage to get any worldediting plugins working.

**Comment by WolfTroll** [comment]
@JUSTaMod  haha new world edit.  XD. Waiting, Uploading files. Mi connection is bad

**Comment by dktapps** [comment]
@WolfTroll how big are the files? xD

**Comment by WolfTroll** [comment]
@dktapps downloading for comprime. In 1 minutes upload.

**Comment by dktapps** [comment]
@JUSTaMod I have a modified copy of mcg76's WorldEdit that works on PHP7, I can send you it if you want. 

(Also, I'm working on a WE plugin myself that's tailor-made for Genisys)

**Comment by dktapps** [comment]
@WolfTroll ok no problem

**Comment by JUSTaMod** [comment]
@dktapps holy hell mate. That would be great.

**Comment by dktapps** [comment]
@JUSTaMod 
[MCG76_WorldEdit_v0.5.2.phar.zip](https://github.com/iTXTech/Genisys/files/335529/MCG76_WorldEdit_v0.5.2.phar.zip)
I had to put in a zip because GitHub won't let me upload PHARs. But there you go

**Comment by WolfTroll** [comment]
Sorry. Here link of server data: http://www.mediafire.com/?ddsr9894hkl3g6v

**Comment by Muqsit** [comment]
I and @CraftYourBukkit fixed these memory crashdumps by increasing the main-hard-limit from default 1024 to around 4-6 GB. It worked! 1GB RAM isn't enough for hosting PocketMine servers. If you haven't touched your pocketmine.yml file yet, you'd better have a look into it.

**Comment by WolfTroll** [comment]
Ohh, why?

**Comment by WolfTroll** [comment]
@Muqsit  But there are people who have more than 10GB and have the same error. Like the old low memory

**Comment by dktapps** [comment]
@WolfTroll I've examined your files and I have to conclude that there is no memory leak here. You _cannot_ expect to be able to host 11 worlds and 40~50 players with 1GB RAM. 1GB simply is not enough for that many players and worlds.

**Comment by JUSTaMod** [comment]
oh thank christ for that. lol. No real issue.
