### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by flash586** [iTXTech/Genisys#128]
See this problem https://goo.gl/photos/nxTaQ82iDNsywV3Z8

**Comment by GalvinGao** [comment]
For some reason, we are in China that we can't use google service. I'm saving it via VPN to GitHub so guys in China can see it.

Here's the original image:

![Original Image](http://i8.tietuku.com/14ba0b579b452174.jpg)

**Comment by GalvinGao** [comment]
@PeratX @PocketKiller Please check out
= this issue

**Comment by CrayonDing** [comment]
Please try the newest version.
