### ISSUE TITLE
Snow does not remove

### ISSUE THREAD

**Issue by DeathRaven359** [iTXTech/Genisys#1280]
Snow covers are unable to be removed. You can break the bock, but when the chunks reload, or when you rejoin, it is back.

This is extremely difficult to manage for servers that have snow themed lobbies.

As well, sometimes the snow block turns into snow cover, and cannot be replaced.

I have barely any plugins on, and the plugins I do have have nothing to do with snow's properties.

**Comment by ChavoJoker** [comment]
hey @DeathRaven359 nice to see you again! I had that issue as well but @kabluinc told me a fix which was to type `/biome` then select the 2 positions where the snow is un-removable, after that type `/biome set 1` :)

**Comment by PeratX** [comment]
@DeathRaven359  @ChavoJoker 's solution is right, it is related to biome
