### ISSUE TITLE
HereAuth doesn't work with the latest build

### ISSUE THREAD

**Issue by ChavoJoker** [iTXTech/Genisys#1283]
#### Issue description

As soon as I join it crashes the server. This has not happened before I used the latest build of Genisys. Before I was using `Genisys 1.2 build #518`and everything was fine
#### Steps to reproduce the issue

Join with the latest HereAuth plugin
#### OS and versions

* Genisys:Genisys 1.2dev-523
* PHP:7
* OS:
* Plugin: HereAuth v1.0-Beta.174

#### Crashdump, backtrace or other files
```
27.06 15:01:47 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::getSkinName()" (EXCEPTION) in "/HereAuth_Beta v1.0-Beta.174.phar/src/HereAuth/User/User" at line 176
```

**Comment by ChavoJoker** [comment]
Not even the latest SimpleAuth plugin works! which is 1.7.2 :(

**Comment by ishitatsuyuki** [comment]
Blame @Intyre. He changed the API.

**Comment by ChavoJoker** [comment]
just now he updated the api??? because HereAuth was working on 0.15 before the build 523 came out

**Comment by GlitchPlayer** [comment]
Genisys is now using skinId instead of skinName. Tell, PEMapModder about
this

**Comment by ChavoJoker** [comment]
@GlitchPlayer thank you! I will tell him ASAP. I do not want players impersonating me at my server :(

**Comment by GlitchPlayer** [comment]
Sure

**Comment by robske110** [comment]
And because of this you leave backup reference, deprecated functions there -_-

**Comment by flaxues** [comment]
PEMapModder stopped with the mcpe/pocketmine community... So you can't tell it to him (unless you know him irl)

**Comment by ChavoJoker** [comment]
@flaxues Okay got it and plus I figured out how to change SkinName to skinId in the plugin so it works at my server.....for now
