### ISSUE TITLE
Chests.

### ISSUE THREAD

**Issue by IrishUHC** [iTXTech/Genisys#1284]
#### Issue description

I made code to pair chests and they do pair, but they don't rename and they don't show a double chest inventory or show a large chest, until you relog. I will provide the code for you to test.
#### Steps to reproduce the issue

1) Write code to set two chests down next to each other and create tiles, etc.
2) Observe what happens.
3) Relog
#### OS and versions

* Genisys:1.2dev-86e91e6
* PHP: PHP7
* OS: Windows 7 Home Premium

#### Crashdump, backtrace or other files
```
        $player = $event->getPlayer();
        $x= $player->x;
        $y = $player->y;
        $z = $player->z;
        
        $player->getLevel()->setBlock(new Vector3($x, $y, $z), Block::get(Block::CHEST));

        $nbt = new CompoundTag("", [
            new ListTag("Items", []),
            new StringTag("id", Tile::CHEST),
            new IntTag("x", $x),
            new IntTag("y", $y),
            new IntTag("z", $z)
        ]);
        $nbt->Items->setTagType(NBT::TAG_Compound);
        Tile::createTile("Chest", $player->getLevel()->getChunk($x >> 4, $z >> 4), $nbt);
        $ti = $player->getLevel()->getTile(new Vector3($x, $y, $z));
        $player->getLevel()->addTile($ti);

        $player->getLevel()->setBlock(new Vector3($x+1, $y, $z), Block::get(Block::CHEST));
        $inv = $player->getInventory()->getContents();
        $nbt = new CompoundTag("", [
            new ListTag("Items", []),
            new StringTag("id", Tile::CHEST),
            new IntTag("x", $x+1),
            new IntTag("y", $y),
            new IntTag("z", $z)
        ]);
        $nbt->Items->setTagType(NBT::TAG_Compound);
        Tile::createTile("Chest", $player->getLevel()->getChunk($x+1 >> 4, $z >> 4), $nbt);
        $t = $player->getLevel()->getTile(new Vector3($x+1, $y, $z));
        $player->getLevel()->addTile($t);
        if($ti instanceof Chest){
            if($t instanceof Chest){
                $t->spawnToAll();
                $t->pairWith($ti);
                $ti->spawnToAll();
                $ti->pairWith($t);
                $ti->saveNBT();
                $t->saveNBT();
                $t->setName($player->getName()."'s Inventory");
                //tried using this, didn't work.
                $player->getLevel()->save();
                $player->getLevel()->saveChunks();
                
            }
        }
```

**Comment by PeratX** [comment]
you forget to spawnTo($player)

**Comment by IrishUHC** [comment]
Ok, sorry I thought spawnToAll() did that. <3

**Comment by IrishUHC** [comment]
It worked for a second, but seems to no longer be working. And yes spawnToAll() calls spawnToPlayer($player), so that shouldn't affect it.
`
$nbt = new CompoundTag("", [
            new ListTag("Items", []),
            new StringTag("id", Tile::CHEST),
            new IntTag("x", $x),
            new IntTag("y", $y),
            new IntTag("z", $z)
        ]);
        $nbt->Items->setTagType(NBT::TAG_Compound);
        Tile::createTile("Chest", $player->getLevel()->getChunk($x >> 4, $z >> 4), $nbt);
        $ti = $player->getLevel()->getTile(new Vector3($x, $y, $z));
        $player->getLevel()->addTile($ti);

        $player->getLevel()->setBlock(new Vector3($x+1, $y, $z), Block::get(Block::CHEST));
        $inv = $player->getInventory()->getContents();
        $helmet = $player->getInventory()->getHelmet();
        $chestplate = $player->getInventory()->getChestplate();
        $leggings = $player->getInventory()->getLeggings();
        $boots = $player->getInventory()->getBoots();
        $nbt = new CompoundTag("", [
            new ListTag("Items", []),
            new StringTag("id", Tile::CHEST),
            new IntTag("x", $x+1),
            new IntTag("y", $y),
            new IntTag("z", $z)
        ]);
        $nbt->Items->setTagType(NBT::TAG_Compound);
        Tile::createTile("Chest", $player->getLevel()->getChunk($x+1 >> 4, $z >> 4), $nbt);
        $t = $player->getLevel()->getTile(new Vector3($x+1, $y, $z));
        $player->getLevel()->addTile($t);
        if($ti instanceof Chest){
            if($t instanceof Chest){
                $t->pairWith($ti);
                $ti->pairWith($t);
                $t->setName($player->getName()."'s Inventory");
                $ti->setName($player->getName()."'s Inventory");
                $ti->spawnTo($player);
                $t->spawnTo($player);
                $ti->spawnToAll();
                $t->spawnToAll();
                $ti->saveNBT();
                $t->saveNBT();
            }
        }
`

**Comment by flaxues** [comment]
Isn't
```
Tile::createTile
```
replaced by
```
BlockEntity::createBlockEntity
```
etc. ??

**Comment by flaxues** [comment]
So it should be...
```
<?php

    $nbt = new CompoundTag("", [
        new ListTag("Items", []),
        new StringTag("id", BlockEntity::CHEST),
        new IntTag("x", $x),
        new IntTag("y", $y),
        new IntTag("z", $z)
    ]);
    $nbt->Items->setTagType(NBT::TAG_Compound);
    BlockEntity::createBlockEntity("Chest", $player->getLevel()->getChunk($x >> 4, $z >> 4), $nbt);
    $ti = $player->getLevel()->getgetBlockEntity(new Vector3($x, $y, $z));
    $player->getLevel()->addgetBlockEntity($ti);

    $player->getLevel()->setBlock(new Vector3($x+1, $y, $z), Block::get(Block::CHEST));
    $inv = $player->getInventory()->getContents();
    $helmet = $player->getInventory()->getHelmet();
    $chestplate = $player->getInventory()->getChestplate();
    $leggings = $player->getInventory()->getLeggings();
    $boots = $player->getInventory()->getBoots();
    $nbt = new CompoundTag("", [
        new ListTag("Items", []),
        new StringTag("id", getBlockEntity::CHEST),
        new IntTag("x", $x+1),
        new IntTag("y", $y),
        new IntTag("z", $z)
    ]);
    $nbt->Items->setTagType(NBT::TAG_Compound);
    BlockEntity::createBlockEntity("Chest", $player->getLevel()->getChunk($x+1 >> 4, $z >> 4), $nbt);
    $t = $player->getLevel()->getgetBlockEntity(new Vector3($x+1, $y, $z));
    $player->getLevel()->addgetBlockEntity($t);
    if($ti instanceof Chest){
        if($t instanceof Chest){
            $t->pairWith($ti);
            $ti->pairWith($t);
            $t->setName($player->getName()."'s Inventory");
            $ti->setName($player->getName()."'s Inventory");
            $ti->spawnTo($player);
            $t->spawnTo($player);
            $ti->spawnToAll();
            $t->spawnToAll();
            $ti->saveNBT();
            $t->saveNBT();
            $ti->getInventory()->addItem($helmet);
            $ti->getInventory()->addItem($chestplate);
            $ti->getInventory()->addItem($leggings);
            $ti->getInventory()->addItem($boots);
            $ti->getInventory()->setContents($inv);
            $ti->getInventory()->addItem(Item::get(Item::GOLDEN_APPLE, 2, 1)->setCustomName(TF::GOLD."Golden Head"));
        }
        $event->setDrops([Item::get(Item::AIR)]);
    }
```
Or am i wrong?

**Comment by IrishUHC** [comment]
Tile is still supported.
