### ISSUE TITLE
Text Format issue

### ISSUE THREAD

**Issue by spideyroc1** [iTXTech/Genisys#1285]
#### Issue description
Text format appears to put the message in this format and is colorless although the first line is colored: (Puts o's with lines avove under the message)
/f about
ōōōōōō

(Code at the bottom at the bottom)

#### Steps to reproduce the issue
Run factionspro 1.5.3b on genisys and type /f help

#### OS and versions

* Genisys:This server is running Genisys 1.2dev-518 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0 alpha (protocol version 81)
* PHP: 7
* OS: ubuntu 14.04

#### Crashdump, backtrace or other files
```
$sender->sendMessage(TextFormat::BLUE . "FactionsPro Help Page 1 of 2" . TextFormat::RED . 
									"\n/f about
									\n/f accept
									\n/f create <name>
									\n/f del
									\n/f demote <player>
									\n/f deny
									\n/f desc <description>");
```

**Comment by jojoe77777** [comment]
Try changing the code to this and see if it fixes it:
```$sender->sendMessage(TextFormat::BLUE . "FactionsPro Help Page 1 of 2"  .        
                                    "\n" . TextFormat::RED . "/f about " . TextFormat::RESET . "
                                    \n" . TextFormat::RED . "/f accept " . TextFormat::RESET . "
                                    \n" . TextFormat::RED . "/f create <name> " . TextFormat::RESET . "
                                    \n" . TextFormat::RED . "/f del " . TextFormat::RESET . "
                                    \n" . TextFormat::RED . "/f demote <player> " . TextFormat::RESET . "
                                    \n" . TextFormat::RED . "/f deny " . TextFormat::RESET . "
                                    \n" . TextFormat::RED . "/f desc <description>");```

**Comment by spideyroc1** [comment]
Thanks, but it is still doing the same thing, this is weird.

**Comment by spideyroc1** [comment]
I tried replacing textformat with the § instead but it still does it

**Comment by gaoyichuan** [comment]
Maybe try to send the different color messages seperately?

**Comment by spideyroc1** [comment]
I did try that

**Comment by flaxues** [comment]
```
use pocketmine\utils\TextFormat;
```
Did you do this in the first place? ^

```
$sender->sendMessage($this->formatMessage("§1FactionsPro Help Page 1 of 2")  .              
                                    "\n" . §4 . "/f about " . TextFormat::RESET . "       
                                    \n" . §4 . "/f accept " . TextFormat::RESET . "       
                                    \n" . §4 . "/f create <name> " . TextFormat::RESET . "     
                                    \n" . §4 . "/f del " . TextFormat::RESET . "       
                                    \n" . §4 . "/f demote <player> " . TextFormat::RESET . "       
                                    \n" . §4 . "/f deny " . TextFormat::RESET . "       
                                    \n" . §4 . "/f desc <description>")
```

If so try this ^

**Comment by jojoe77777** [comment]
@flaxues That won't work, the §4's aren't in quotes...

**Comment by Muqsit** [comment]
This is what will happen if you don't end your text with §r

So if you want the text to be:
"§bHello, §ewelcome to my server!"

You must type it as:
"§bHello, §ewelcome to my server!§r"

**Comment by jojoe77777** [comment]
@Muqsit It's about the \n's being affected by color codes.

**Comment by Muqsit** [comment]
Reset the format before \n. It wont show weird o's

**Comment by spideyroc1** [comment]
Just want to thank you guys for helping me fix it!
