### ISSUE TITLE
The rain did not extinguish the flames.

### ISSUE THREAD

**Issue by samalero** [iTXTech/Genisys#1286]
#### Issue description

When the storm fire to ground the rain did not extinguish the flames.

#### Steps to reproduce the issue

Watched while playing.

#### OS and versions

* Genisys: a2f4995
* PHP: 7.0.6
* OS: Debian Jessie

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by rcsupermanjob** [comment]
No code (:

**Comment by samalero** [comment]
@rcsupermanjob And what code should be? -_-

**Comment by CubeFromSpace** [comment]
Maybe there is code for $isRainingontile or something like that, and fire should search for $israiningontile and extinguish after 30-60 ticks. In other words, add a new boolean value or search for an existing one

**Comment by JUSTaMod** [comment]
That's almost a slap in the face. You close it, then he opens it and assigns you to it. LOL

**Comment by dog194** [comment]
PeratX: Fire again(remember to turn on firespread option)
