### ISSUE TITLE
FloatingTex not work 0.15.0

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#1289]
#### OS and versions

* Genisys:
* PHP:
* OS:

**Comment by jojoe77777** [comment]
Update to the latest version and try again.

**Comment by MrDoni98** [comment]
i use latest version...

**Comment by jojoe77777** [comment]
Define "not work". What happens?

**Comment by MrDoni98** [comment]
it does not appear

**Comment by dktapps** [comment]
No version supplied. Closing for not following template.

**Comment by MrDoni98** [comment]
.

**Comment by Muqsit** [comment]
It works on my server.

**Comment by MrDoni98** [comment]
TagBlock in your work?

**Comment by Pub4Game** [comment]
Just the author of the plugin needs to update it. FloatText works.

**Comment by MrDoni98** [comment]
о, спасибо))
