### ISSUE TITLE
how to get a Nether Door ?

### ISSUE THREAD

**Issue by silence8620** [iTXTech/Genisys#129]
i can't go to Nether, because simple obsidian door in fire can't open,(我不能去地狱，因为简单的黑曜石门无法用火点亮)

**Comment by PocketKiller** [comment]
its not implemented.

**Comment by silence8620** [comment]
thank you ,but another core (ImagicalMine) plemented nether door?  if you join in Imagical Mine program, please tell me how to get  Nether? (sorry,i'm Chinses , i'm english is very bad)

**Comment by CrayonDing** [comment]
So if you can't speak English,you can speak Chinese.Most of us could understand Chinese(大哥英文不好就用中文咯，反正这边的主要开发者大部分都是国人

**Comment by CrayonDing** [comment]
没法开地狱门请从genisys.yml中打开地狱选项。
![image](https://cloud.githubusercontent.com/assets/16436272/12528870/55c9ba92-c1e0-11e5-9ea1-5271c88d5ee2.png)

**Comment by xpyctum** [comment]
@CrayonDing No, many users who understand english

**Comment by dog194** [comment]
@xpyctum  If someone does not good at English but still try to type in English, It would bring some mistake..And this is what we try to avoid. Also this will make the issue more difficult to deal with. So we recommend user use the native language. BTW until now, although in Githut many of us using English, the majority of users can just speak Chinese.

**Comment by PeratX** [comment]
ImagicalMine's nether is copied from Genisys

**Comment by silence8620** [comment]
谢谢你们各位，英语本人还在加深语法，很抱歉。
@PeratX 从ImagicalMine里面也进不去地狱，而且yml文件是空的，也没法编辑，不知道这个核心的地狱选项在何处？好像开发者说并没有加入~。~
谢谢。

**Comment by PeratX** [comment]
genisys.yml nether.enable: true

**Comment by silence8620** [comment]
@PeratX 进去之后没有地图，是一片火，玩家也被烧着，也看不到方块。

**Comment by silence8620** [comment]
@PeratX 为什么现在的Genisys核心只有不到1MB？以前都是2MB+

**Comment by CrayonDing** [comment]
@silence8620 因为现在没有加密了。

**Comment by silence8620** [comment]
刚刚去下载itx的php7，下载完之后无法打开？现在最新的核心要求php7，如何安装啊各位大哥，新手T^T，非常感谢大家的帮助

**Comment by silence8620** [comment]
下完之后里面只有1个文件，连接是https://github.com/iTXTech/PHP-Genisys

**Comment by silence8620** [comment]
我就点的旁边的DownloadZip，下完之后只有1个cygwin-console-helper.exe，然后什么都没有了，重复下载也是这样

**Comment by CrayonDing** [comment]
没下完。亲测没问题

**Comment by silence8620** [comment]
@CrayonDing 等过2天换台服务器再试下，谢谢！
