### ISSUE TITLE
[BlockEntity update] sign command warp

### ISSUE THREAD

**Issue by MaryVictoria** [iTXTech/Genisys#1295]
warp sign command can't teleport, nothing happen when tap, but when i use command /warp name it worked, im using EssentialsPE, also in AdvancedKits sign nothing happen when tap..

**Comment by Driesboy** [comment]
just what i say @PeratX it dont work!

**Comment by MaryVictoria** [comment]
im using latest version 527

**Comment by MaryVictoria** [comment]
i try also signwarp plugin didnt work

**Comment by Driesboy** [comment]
i know my parkour plugin even dont work

**Comment by dktapps** [comment]
@PeratX This is since the BlockEntity update

**Comment by Tolo0** [comment]
having same problem sins 527 build.
