### ISSUE TITLE
How do I compile the git to make a phar?

### ISSUE THREAD

**Issue by spideyroc1** [iTXTech/Genisys#1299]
#### Issue description
How do I compile Genisys using Netbeans or any other IDE

#### Steps to reproduce the issue
Become me, spideyroc1, and not understand how to do it.

#### OS and versions

* Genisys: The newest github commit
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Sorry i'm new to this ;)
```

**Comment by gaoyichuan** [comment]
```
$ php src/pocketmine/PocketMine.php #Run the server
```
Then type 'ms' in the server console
