### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#13]
Can you tell me please why /status report not in english? Can i change it to english?

**Comment by dog194** [comment]
well. Because the Genisys was power by Chinese and used by Chinese only in the past. So the word shown in Chinese. Maybe you can make a Pull request for adding english as an selection.

**Comment by PeratX** [comment]
@dog194 's answer is right.

**Comment by dog194** [comment]
/status
----服务器状态(server status)----
服务器人数(online players)：xx/xx
运行时间(Running time)：xxH xxM xxS
平均TPS(average TPS)：xx(x.xx%)
瞬时TPS(instantaneous TPS)：xx(x.xx%)
网络上传(instantaneous network upload speed): x.xx KB/s
网络下载(instantaneous network download speed): x.xx KB/s
线程总数(Total threads):
主线程内存(The main threads memory)：
总内存(Total  memory)：
总虚拟内存(Total  virtual memory)：
堆栈内存(stack memory)：
系统最大内存(The installed memory)：
世界 “world” ：xxx区块，xx实体，xxxtiles.时间 x.xx毫秒
Level “level name” ：xxx Block xxx Mods Time x.xx millisecond
I am not a English native speaker. So maybe some translations are wrong.
