### ISSUE TITLE
"bin\php\php.exe: Exit 127" Error

### ISSUE THREAD

**Issue by SkaterAlex** [iTXTech/Genisys#1300]
#### Issue
For some reason, when I open the software it will come up with a error like this...
`bin\php\php.exe: Exit 127`
I don't know why it happens, but it's annoying! And the only way I found it fix it, is to open a close it many times until it doesn't say it.

#### Steps to reproduce the issue
It's simple to do, just install it and open it. (That's what I did.)

#### OS and versions
* Genisys: Genisys 1.2dev-531 "Ikaros"
* PHP: I don't know?
* OS: Windows 10 

#### Crashdump, backtrace or other files
![untitled-1](https://cloud.githubusercontent.com/assets/17804322/16438571/5073381c-3df4-11e6-9b3a-ca332e709c11.png)

**Comment by ishitatsuyuki** [comment]
PHP bug.
