### ISSUE TITLE
New blocks

### ISSUE THREAD

**Issue by Misat11** [iTXTech/Genisys#1301]
#### Issue description
In Genisys you are missing a lot of new blocks of version 0.15.0.

#### OS and versions
Genisys: 1.2dev-532
PHP: 7
OS: Linux Ubuntu 14.04

**Comment by ishitatsuyuki** [comment]
Too broad. Please enumerate.

**Comment by Misat11** [comment]
piston, sticky piston, observer
and some: items carrot on a stick, horse armor, leads, name tags, fire charge and 
mobs: horse

**Comment by dktapps** [comment]
I can add these easily, but there's not much point because they won't be any use until the functionality behind them is implemented.

**Comment by kabluinc** [comment]
can they be added then just like in pocketmine minecarts are there but cant be placed.

**Comment by Muqsit** [comment]
@kabluinc You can just /give it to yourself.

**Comment by kabluinc** [comment]
i was meaning adding new items to the invebtory but not needing them to be implemented like clearsky has done https://github.com/ClearSkyTeam/ClearSky/blob/php7-0.15/src/pocketmine/item/Item.php

**Comment by dktapps** [comment]
I think it's long past time we made the move to JSON based creative inventories anyway. This can be done at the same time.

**Comment by Misat11** [comment]
that minecarts not minecarts, but fast cars, and not traveling on rails

**Comment by PeratX** [comment]
@dktapps You forgot to edit Block.php!

**Comment by dktapps** [comment]
@PeratX xD, I'm working on it

**Comment by dktapps** [comment]
The creative inventory has been updated. Working on various other things.

**Comment by dktapps** [comment]
Okay. Update on the above: I had to remove enchanted books (#1334). I'll re-add them as soon as I can.

**Comment by dktapps** [comment]
Hoppers coming very soon

**Comment by Froz3n907** [comment]
I'm having an issue getting pistons to place. I've verified I'm on the latest version. Is this just lack of functionality?

**Comment by ishitatsuyuki** [comment]
@Froz3n907 No question here. Go chat.

**Comment by Muqsit** [comment]
@dktapps I think this issue can be closed now?

**Comment by ishitatsuyuki** [comment]
This is too abstract and we are improving. Closing.
