### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by legoboy0215** [iTXTech/Genisys#1302]
#### Issue description
IDK what even happens. Server crashes randomly with this memory leak

#### Steps to reproduce the issue
Nothing. Wait and the server crashes some time.
#### OS and versions

* Genisys: 1.2
* PHP: 7.0.6
* OS: Ubuntu

#### Crashdump, backtrace or other files
```
Genisys Crash Dump Wed Jun 29 06:11:59 EDT 2016

Error: Allowed memory size of 6442450944 bytes exhausted (tried to allocate 4096 bytes)
File: /src/pocketmine/level/Level
Line: 1375
Type: E_ERROR

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Loaded plugins:
加载的插件:
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
HereAuth 1.0-Dev#218 by PEMapModder for API(s) 2.0.0
LegoCore 3.0.0 by Legoboy for API(s) 2.0.0
ChatParser 1.0.0 by Legoboy for API(s) 2.0.0
AdvancedKits 5.0 by luca28pet for API(s) 2.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
Lobby 1.0.0 by Legoboy for API(s) 2.0.0
Vote 1.0.0 by Legoboy for API(s) 2.0.0
LegoHG 4.0 by Legoboy for API(s) 2.0.0
SkyWars 1.0.0 by Legoboy for API(s) 2.0.0
PureChat 1.4.0-BETA-01 by 64FF00 for API(s) 1.13.0, 2.0.0
```

**Comment by ishitatsuyuki** [comment]
Please make sure that you hadn't host too much players or worlds.

**Comment by dktapps** [comment]
I think I'm going to make crashdumps more informative again. Also this is only a partial crashdump.

**Comment by robske110** [comment]
6GB ram should be enough though

**Comment by legoboy0215** [comment]
Why? 5 players and 4 worlds, only 3 are loaded.

**Comment by dktapps** [comment]
Full crashdump please

**Comment by legoboy0215** [comment]
That is the full one...

**Comment by legoboy0215** [comment]
No, I'm not kidding. Backtrace is messed up too.

**Comment by legoboy0215** [comment]
Oh wait. 
```
Genisys Crash Dump Wed Jun 29 06:11:59 EDT 2016

Error: Allowed memory size of 6442450944 bytes exhausted (tried to allocate 4096 bytes)
File: /src/pocketmine/level/Level
Line: 1375
Type: E_ERROR

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Loaded plugins:
加载的插件:
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
HereAuth 1.0-Dev#218 by PEMapModder for API(s) 2.0.0
LegoCore 3.0.0 by Legoboy for API(s) 2.0.0
ChatParser 1.0.0 by Legoboy for API(s) 2.0.0
AdvancedKits 5.0 by luca28pet for API(s) 2.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
Lobby 1.0.0 by Legoboy for API(s) 2.0.0
Vote 1.0.0 by Legoboy for API(s) 2.0.0
LegoHG 4.0 by Legoboy for API(s) 2.0.0
SkyWars 1.0.0 by Legoboy for API(s) 2.0.0
PureChat 1.4.0-BETA-01 by 64FF00 for API(s) 1.13.0, 2.0.0
```

**Comment by dktapps** [comment]
that's better. Could you edit your main post so it's all in the same place?

**Comment by legoboy0215** [comment]
Yes.

**Comment by dktapps** [comment]
There should be more. You're missing a piece that should look something like this:
```
Genisys version: 1.2dev #0 [Protocol 81; API 2.0.0]
uname -a: Windows NT DESKTOP-4CUH8HC 10.0 build 10586 (Windows 10) i586
PHP version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win
```

**Comment by robske110** [comment]
Looks like one of your plugins is mass calling getBlock() ?

**Comment by legoboy0215** [comment]
@dktapps Yes but I never get that.

**Comment by legoboy0215** [comment]
I just took this from another of my crashdumps:

```
Genisys version: 1.2dev #51 [Protocol 81; API 2.0.0]
uname -a: Linux legoboy0215 2.6.32-042stab116.1 #1 SMP Wed May 4 16:21:02 MSK 2016 x86_64
PHP version: 7.0.6
Zend version: 3.0.0
OS : Linux, linux
```

**Comment by dktapps** [comment]
huh
You're definitely up-to-date yes?

**Comment by legoboy0215** [comment]
No.

**Comment by legoboy0215** [comment]
But recent commits do not fix anything except code style and stuff.

**Comment by ishitatsuyuki** [comment]
Have you get the memory leak fix?

**Comment by legoboy0215** [comment]
Yes.

**Comment by Muqsit** [comment]
@ishitatsuyuki @legoboy0215
The only way I can reproduce this is by:

Setting main-hard-limit to 1024 in pocketmine.yml

Using plugins such as MagicWE or MinrReset and editing a very large area so as to make the server lag.

Then the server crashes..

**Comment by robske110** [comment]
As already stated earlier, this is caused because of massive plugin calling to level functions

**Comment by CubeFromSpace** [comment]
@legoboy0215 maybe it is the plugins on the server, such as pureperms and purechat, those are big plugins.

**Comment by Muqsit** [comment]
@robske110 right, didn't see it lol.
@CubeFromSpace you are right. And that's why I'm still using the 40KB PurePerms plugin.

**Comment by KillerXtream** [comment]
<offtopic> Hey muq, get on Gitter, need to talk with ya!

**Comment by legoboy0215** [comment]
Non of my plugins mass calls get blocks...

**Comment by legoboy0215** [comment]
8 GB RAM, 8CPUS VPS.

**Comment by Muqsit** [comment]
@KillerXtream Twitter: @muqsitrayyan
Sorry, I'm new to Gitter :3

**Comment by PeratX** [comment]
Some plugins will cause memory leak. (such as LVIP)

**Comment by PeratX** [comment]
php7 is more sensitive on memory leak!

**Comment by legoboy0215** [comment]
Why do they cause memory leaks? Any specific code to check for?

**Comment by legoboy0215** [comment]
Why? This is a Genisys issue.

**Comment by legoboy0215** [comment]
@PeratX @dktapps I got 20+ more crashdumps because of this.

**Comment by robske110** [comment]
May you simply test it without your plugin?

**Comment by Driesboy** [comment]
yes i dont have this

**Comment by legoboy0215** [comment]
@robske110 I have no idea how to do that. No plugins = no players.

**Comment by robske110** [comment]
Well then we cannot really help you. What would help would either throwing an exception on the getBlock function to get a stack trace.

**Comment by legoboy0215** [comment]
All my exceptions all return something above.

**Comment by robske110** [comment]
Just try to manually throw an exception on the function call. If there's still no backtrace you may need xdebug.
