### ISSUE TITLE
Absorption effect doesn't give player extra hearts

### ISSUE THREAD

**Issue by kaitododoyt** [iTXTech/Genisys#1306]
#### Issue description
No extra hearths on health bar

#### Steps to reproduce the issue
Eat a Golden apple

#### OS and versions
* Genisys: Dev_537
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Nothing
```

**Comment by Driesboy** [comment]
and notch apple or enchantend golden apple

**Comment by Efforto** [comment]
= =Yeah, I think @PeratX  hasn't wrote and done this yet.

**Comment by dktapps** [comment]
The absorption effect? Yeah, just tested it.

**Comment by XFuryMCPE** [comment]
https://github.com/iTXTech/Genisys/pull/1349 ? This might work.. hopefully :D
