### ISSUE TITLE
Permissions! PurePersms!

### ISSUE THREAD

**Issue by Infernus101** [iTXTech/Genisys#1307]
PurePerms not working, Cant give any special permission or remove any permission, there r only two groups, OP and Guest, can't give different permission to Admins!

**Comment by dog194** [comment]
Closing for not following template.
PS, I think you should find some plugins to solve your problem.

**Comment by Infernus101** [comment]
which plugins? name some!!

**Comment by Driesboy** [comment]
FOLLOW THE TEMPLATE!

**Comment by Infernus101** [comment]
Whats the template?
