### ISSUE TITLE
Item Enchantment display name

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#1308]
Just wonder, but seriously: If i enchant an item for example Bow Power IV and trying to show up $item->getNamedTag()->display->Name->getValue() then:
`Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$display`
Without any enchantment it was available.
Where was the Blue color + Item name located at? 
Also, if i do $item->setCustomName("asd") to the Bow Enchanted, then it will be available. But after swapping with any slot in the inventory, it will disappear, and even the (BlueColor)Bow didn't change to "asd"

**Comment by PeratX** [comment]
It is not by custom name. It is by the enchantment, display by client not by server. So ,your change will not take effect.

**Comment by intagaming** [comment]
Absolutely no.
![image](https://cloud.githubusercontent.com/assets/16471365/16522831/3d22c6ba-3fca-11e6-8c59-cd14c4082e0f.png)
That's MCPE 0.15.0
See the Changed name of the item?
No way i can do that in PM. setCustomName() just doesn't work.

**Comment by intagaming** [comment]
@PeratX i mean how to change the name of Enchanted item though ? Cause with latest version of Genisys i still can't change it with setCustomName()
