### ISSUE TITLE
PurePerms Permission

### ISSUE THREAD

**Issue by Infernus101** [iTXTech/Genisys#1310]
PurePerms not giving permission to Guest or any other Rank, Only OP or default permission works!

* Genisys: 1.2dev-542 
* PHP: 7
* OS: Windows 10

**Comment by dktapps** [comment]
Closing for issue spamming and not following template. This is a plugin issue. Continue to spam and you will be banned.

**Comment by Infernus101** [comment]
What is the template?

**Comment by flaxues** [comment]
@Infernus101 When you make a new issue... You get a text you need to fill in thats the template!

It should look like this:


#### Issue description


#### Steps to reproduce the issue


#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```
