### ISSUE TITLE
Random freeze

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#1313]
#### Issue description

if i am playing on my server...
some times my server random freeze.
i dont use sleep()
my server port: 19133

#### Steps to reproduce the issue

set up  your server on 19133

#### OS and versions

* Genisys: 547
* PHP: 7.0.4
* OS: windows server 2012

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by intagaming** [comment]
Maybe your plugin did something take too long? Or your hdd/ssd usage just up to 100%, or even Redstone..

**Comment by PeratX** [comment]
Check your plugin. I have tested without plugin, a weak, 20 players average, no restart and everything is fine.

**Comment by Driesboy** [comment]
i have 10 plugins
the only giant plugin is SW_Svile but i have it on my giant server and i dont have the same bug

**Comment by emiel2210** [comment]
Ik my server is freezing too :(

**Comment by kabluinc** [comment]
mine freezes too. sometimes after 10 hours sometimes within 10 minutes of starting server. whole server and console freezes.

**Comment by PeratX** [comment]
Plugin Error! My plugin list: ：AshMan v1.0.1, DisableFlow v1.0.0, EconomyAPI v2.0.9, EconomyLand v2.0.9_Doggy_b1216, EconomySell v2.0.7, EconomyShop v2.0.7, FTeleport v1.0.1, ItemCloud v1.3_Doggy, Protection v2.5.5, sendtip v1.0.0_zhy, EconomyPShop v2.0.1

Never get freeze.

**Comment by Driesboy** [comment]
doggy?

**Comment by biswarm22** [comment]
I don't have this problem and have LOTS of plugins. @Driesboy I have been on your server and i have experienced the freeze, but I think it only happenes in the hub

**Comment by Driesboy** [comment]
i know 
i still have fix it

**Comment by Muqsit** [comment]
Um this is happening with my server too, I think it's one of the plugins

**Comment by Driesboy** [comment]
its fixed for me

**Comment by kabluinc** [comment]
@Driesboy how did you fix it?

**Comment by legoboy0215** [comment]
How? I have the same issue with only 8 plugins.
