### ISSUE TITLE
-question- How to allocate ram?

### ISSUE THREAD

**Issue by Meepster99** [iTXTech/Genisys#1315]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Meepster99** [comment]
Hello, and before I say anything, I am sorry if this is not the right place to say this, but how does one allocate more ram to the server?

**Comment by dktapps** [comment]
Increase `main-hard-limit` in pocketmine.yml

**Comment by Meepster99** [comment]
Thanks so much
