### ISSUE TITLE
Continous error in console, getAttribute() on null

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#1316]
#### Issue description
This error keeps spamming in console every now and again and requires a restart. `] [Server thread/CRITICAL]: Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 4324`

#### Steps to reproduce the issue
Happens randomly

#### OS and versions

* Genisys: Genisys 1.2dev-#0
* PHP: 7.0.3
* OS: Windows 10

#### Crashdump, backtrace or other files
no crashing just spamming console with that error

**Comment by dktapps** [comment]
Strange. Have you updated? I closed a similar issue before.

**Comment by dktapps** [comment]
Also there is nothing _on_ 4324, just a comment.

**Comment by kabluinc** [comment]
might be a plugin issue then?

**Comment by dktapps** [comment]
most likely. Please update and see if it still happens.

**Comment by kabluinc** [comment]
after updating to latest build, it now shows this instead `[Server thread/CRITICAL]: Error: "Call to a member function clearAll() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 1339`
somehow, iv found out that the error stops temporarily when I unload the world. most likely a problem with the sw plugin I use.

Thanks for your help

**Comment by dktapps** [comment]
I would expect so. I can't reproduce this at all

**Comment by SavionLegendZzz** [comment]
I get this issue when i kick players during PlayerJoinEvent

**Comment by kabluinc** [comment]
Yea this happens with some plugins wherea player joins the game and leaves before the match ends. the next time they join, the console is spamming with those errors
