### ISSUE TITLE
Players cant place blocks if another player is spectator

### ISSUE THREAD

**Issue by kaitododoyt** [iTXTech/Genisys#1317]
#### Issue description
Players cant place block if an spectator is in the same place of event

#### Steps to reproduce the issue
try to place block in the same place of spectator player

#### OS and versions
* Genisys: 549
* PHP:7
* OS: Windows 10

#### Crashdump, backtrace or other files
```
Maybe isn´t a bug, but its possible to change?
```

**Comment by PeratX** [comment]
Player in Spectator will not spawn, Check your plugins
