### ISSUE TITLE
Drops

### ISSUE THREAD

**Issue by Muqsit** [iTXTech/Genisys#132]
Grass/Tall Grass never drop seeds...

**Comment by mixailenko5** [comment]
Ok. I see this.

**Comment by Muqsit** [comment]
Yay :$

**Comment by mixailenko5** [comment]
If you use hoe ?

**Comment by PocketKiller** [comment]
not implemented i think.

**Comment by Muqsit** [comment]
The hoe thing is gonna be discontinued in MCPC 1.9 so it would be cool if you do the same...that will give the server a PC-feel.
