### ISSUE TITLE
getHelmet() on null

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#1320]
#### Issue description

error in console: could not tick level ..... call to a member function getHelmet() on null
#### Steps to reproduce the issue

/

#### OS and versions

* Genisys: 555 
* PHP: 7.0.4
* OS: windows

#### Crashdump, backtrace or other files
```
error in console: could not tick level ..... call to a member function getHelmet() on null
in src/pocketmine/entity/human at line 349
```

**Comment by atTheDisco** [comment]
Yes, I have this problem

**Comment by IrishUHC** [comment]
This is an issue with the respiration enchantment. I just checked the code, and I'll make a pull request about it soon

**Comment by dktapps** [comment]
@dog194

**Comment by dog194** [comment]
oh. can you give me more detail? i will try to fix this as soon as possible.

**Comment by IrishUHC** [comment]
@dog194 If a person has no helmet on, I think this causes the crash. so testing if the helmet isn't null before getting the enchantments would do the trick I think :)

**Comment by dog194** [comment]
@IrishUHC . yea, I forget this. :(

**Comment by atTheDisco** [comment]
@dog194 I'm getting this error when the player exits the game

> [05:21:22] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getHelmet() on null
> [05:21:22] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getHelmet() on null
> [05:21:22] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getHelmet() on null
> [05:21:22] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getHelmet() on null
> [05:21:22] [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getHelmet() on null
>

**Comment by IrishUHC** [comment]
he already fixed this, I believe?

**Comment by Moonneko** [comment]
Same ussue !

**Comment by dog194** [comment]
Still buggy using #563?

**Comment by Driesboy** [comment]
i will test

**Comment by Driesboy** [comment]
new error call to a member function getArmorContent() on null
in entitydamageevent at line 120
