### ISSUE TITLE
console gets spammed when players place blocks

### ISSUE THREAD

**Issue by MhikeiMPC** [iTXTech/Genisys#1326]
#### Issue description
It shows a message when players place blocks and it spams the console

Notice: Undefined index: 00000000674a2c97000000002c8c5b54 in phar://O:/Users/Apple/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php on line 2271

#### Steps to reproduce the issue
try to have a player place a block

#### OS and versions

* Genisys: This server is running Genisys 1.2dev-549 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0 alpha (protocol version 81)

* PHP: 7
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

Notice: Undefined index: 00000000674a2c97000000002c8c5b54 in phar://O:/Users/Apple/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php on line 2271
version

**Comment by dktapps** [comment]
Closing due to Outdated version
