### ISSUE TITLE
The rain will not extinguish the flames.

### ISSUE THREAD

**Issue by samalero** [iTXTech/Genisys#1330]
#### Issue description

The rain will not extinguish the flames.

#### Steps to reproduce the issue

I watch the flame when there is rain. 

#### OS and versions

* Genisys: 082cbb8
* PHP: 7.0.6
* OS: Debian Jessie

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
Do you open the fire-spread in Genisys.yml?

**Comment by samalero** [comment]
Upd: Lightning with fire - false, but lightning still ignites.

**Comment by samalero** [comment]
no value of fire-spread is false

**Comment by dog194** [comment]
Then open it.  extinguish the flames need this option
99032146a2def719e8b52f8061c8cb8227a0c952

**Comment by samalero** [comment]
open but is not working. And lightning with fire - false, but lightning still ignites.

**Comment by samalero** [comment]
Upd: option lightning with fire is working.

**Comment by dog194** [comment]
So, check your setting in Genisys.yml. Then test again.

**Comment by samalero** [comment]
I checked three times. I can give the address of the test server that you look.

**Comment by dog194** [comment]
Just tested, The fire Block can extinguish automatically. But the speed still need to be improved.(We wil do that in the future.)

**Comment by samalero** [comment]
From the beginning the flame faded before the end of the rain. Even after several periods of rain is still not faded.

P.S.: Flames came first lightning flashes.

**Comment by PeratX** [comment]
Turn on fire-spread in genisys.yml.
