### ISSUE TITLE
Creative Inventory has no items in if the player joins in creative mode

### ISSUE THREAD

**Issue by samalero** [iTXTech/Genisys#1334]
#### Issue description

When I open creative menu, i don`t see items. It helps only switches to Creative mode.

#### Steps to reproduce the issue

After a few minutes after server On this bug appears.

#### OS and versions

* Genisys: 44fe545c821fd6e3b5156344e8060ec1a029369f
* PHP: 7.0.6
* OS: Debian Jessie

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dktapps** [comment]
Is this since the inventory update with the new items?

**Comment by samalero** [comment]
Yes, before it was not.

**Comment by samalero** [comment]
P.S.: Menu from a part works, but eventually blocks disappear.

**Comment by dktapps** [comment]
_Why_ enchanted books caused issues, I can't honestly say. But they have been temporarily removed.
