### ISSUE TITLE
$player->sendMessage("öäü")

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [iTXTech/Genisys#1336]
#### Issue description
if you send a player a message like $player->sendMessage("Möge der bessere...");
the chat only shows you "M".

#### Steps to reproduce the issue
$player->sendMessage("äüöüä")

#### OS and versions

* Genisys: 1.2dev
* PHP: 7
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
This is a client side issue, report it to Mojang.

**Comment by Goodstuff4UonYT** [comment]
When I write "öäü" in the chat it works. Still ja client side issue?
