### ISSUE TITLE
Lagg

### ISSUE THREAD

**Issue by LordJoshie** [iTXTech/Genisys#1339]
#### Issue description

On first join, no lag.. two-three min later, start developing lag. relog, no lag. 
#### Steps to reproduce the issue

just play a map for a bit, see what I mean.
#### OS and versions

* Genisys: 8f99 
* PHP: 7.0.3
* OS: Linux 

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Driesboy** [comment]
Its already reported!
Close this

**Comment by LordJoshie** [comment]
My apologies. I assumed this may have been a different issue.

**Comment by LordJoshie** [comment]
But uhm... just saying. A post from may about 'lag spikes' is NOT relevant to this issue, with a gradual developing lagg, which is miraculously cleared with a simple relog.
