### ISSUE TITLE
Creating mode of inventory can't use

### ISSUE THREAD

**Issue by nishuo** [iTXTech/Genisys#1340]
#### Issue description
 Create mode, you can not use items in the column items, into the items column, flashing immediately disappeared. Can only use the current display of the 9 squares of items. Can be discarded, but not lost (unlimited). This makes me very distressed, even the creation of the building can not be put, then the game can not play the game.

#### Steps to reproduce the issue

Create the use of items
#### OS and versions

* Genisys:1.2dev #0 [Protocol 81; API 2.0.0]
* PHP:7.0.8
* OS:Liunx CenOS 6.5
* Zend version: 3.0.0
* Client OS:Minecraft: Windows 10 Edition Beta

**Comment by dktapps** [comment]
#1337
