### ISSUE TITLE
Grass doesnt spread - Latest SRC folder as of 02/07/2016 20:24 GMT

### ISSUE THREAD

**Issue by alicheek** [iTXTech/Genisys#1342]
No Logs to Put in just a couple of issues ive noticed.

Grass doesn't seem to spread on the server basically running default configs appart from more ram and enabling mobs and making it more chunks are processed per tick.

Dont know if this is a known issue or not.

Thanks for the amazing work guys honestly is the best working pocket server software ive seen in a long time! :)

**Comment by PeratX** [comment]
Grass will spread on my server -_-

**Comment by PeratX** [comment]
Lightlevel must >= 9
