### ISSUE TITLE
Bug health

### ISSUE THREAD

**Issue by LewBr** [iTXTech/Genisys#1344]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace, Plugins list or other files
```
$player->setMaxHealth($hearts * 20);
$player->setHealth($hearts * 1);
```
![image](https://cloud.githubusercontent.com/assets/17750435/16543034/de181bfe-40c1-11e6-926d-e538cf5eef20.png)

**Comment by ishitatsuyuki** [comment]
At least write your version.

**Comment by PeratX** [comment]
Close for not flow template. Also you code is wrong

**Comment by LewBr** [comment]
thats because when i will to change the health to 1 and thats happen

**Comment by ishitatsuyuki** [comment]
Oh, seems I'm talking with a '!?:m/#*g@)' language user.

DESCRIBE PROPERLY

**Comment by LewBr** [comment]
sorry, did you have a problem? or you are so noob? did you don't understand that i can not good english?

**Comment by LewBr** [comment]
i just report a problem whit the genisys and you are so ignorant...

**Comment by LewBr** [comment]
whit the others!!
