### ISSUE TITLE
Synapse bug.(Error: Call on null) Do not use Synapse now. wait for fixing.

### ISSUE THREAD

**Issue by Moonneko** [iTXTech/Genisys#1345]
#### Crashdump, backtrace, Plugins list or other files

Error: Call to a member function getItemInHand() on null
File: /src/pocketmine/entity/Human
Line: 481
Type: notice

Code:
[472] 			$pk->eid = $this->getId();
[473] 			$pk->x = $this->x;
[474] 			$pk->y = $this->y;
[475] 			$pk->z = $this->z;
[476] 			$pk->speedX = $this->motionX;
[477] 			$pk->speedY = $this->motionY;
[478] 			$pk->speedZ = $this->motionZ;
[479] 			$pk->yaw = $this->yaw;
[480] 			$pk->pitch = $this->pitch;
[481] 			$pk->item = $this->getInventory()->getItemInHand();
[482] 			$pk->metadata = $this->dataProperties;
[483] 			$player->dataPacket($pk);
[484] 
[485] 			$this->sendLinkedData();
[486] 
[487] 			$this->inventory->sendArmorContents($player);
[488] 
[489] 			if(!($this instanceof Player)){
[490] 				$this->server->removePlayerListData($this->getUniqueId(), [$player]);
[491] 			}

Backtrace:
#0 /src/pocketmine/Player(992): pocketmine\Player->spawnTo(synapse\Player Player(38))
#1 /src/pocketmine/Player(951): pocketmine\Player->doFirstSpawn(boolean)
#2 /src/pocketmine/Player(2041): pocketmine\Player->sendNextChunk(boolean)
#3 /src/pocketmine/Server(2988): pocketmine\Player->checkNetwork(boolean)
#4 /src/pocketmine/Server(2679): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2557): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(2122): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\Administrator\Desktop\lob\Genisys.phar/, string C:\Users\Administrator\Desktop\lob\, string C:\Users\Administrator\Desktop\lob\plugins\, string unknown)
#8 (1): require_once(string phar://C:/Users/Administrator/Desktop/lob/Genisys.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.2dev #579 [Protocol 81; API 2.0.0]
uname -a: Windows NT WIN-Q5446PQIS47 6.1 build 7601 (Windows Server 2008 R2 Enterprise Edition Service Pack 1) i586
PHP version: 7.0.1
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 1 minutes 9 seconds
Number of loaded worlds: 4
Players online: 20/150

: Plugins (24): 1vs1 v0.0.5, AlwaysSpawn v2.2.2, AntiCheat v2.1.3, EconomyAPI v2.0.9, EconomyShop v2.0.7, Functions v1.0, iProtector v3.1a, ManyWorlds v2.0.3, MoneyBlock v1.0.0, MSpawns v1.5, NoSpam v0.1, PurePerms v1.3.7, SignPortal v1.1.2, SimpleAuth v1.7.2, TapToDo v2.2, TimeCapsule v1.1.1, VoteReward v2.1, WorldProtect v2.1.0, CustomAlerts v1.6, SynapseTransfer v1.0.0, TapSign v, SimpleAuthHelper v2.0.4, PureChat v1.4.0, SimpleWarp v2.0.3

**Comment by dog194** [comment]
When this start happens? and do you add/delete some plugins when this happen?

**Comment by Moonneko** [comment]
when player hold item join in server. server will be crash. All player join Synapse server. i think synapse errol. sorry my bad english

**Comment by Moonneko** [comment]
i tried run server without plugins. but same issues

**Comment by dog194** [comment]
paste the Crashdump. and give us as more detail as you can.
such as, when it crash.
what do you do before it crash.
and is join a general server or a Synapse server?
and some other things.

**Comment by MattWAnderson** [comment]
Same error here, forwarding players from Synapse to a hub:

Genisys Crash Dump Sun Jul 3 00:11:20 EDT 2016

Error: Call to a member function getItemInHand() on null
File: /src/pocketmine/entity/Human
Line: 481
Type: notice

Code:
[472] 			$pk->eid = $this->getId();
[473] 			$pk->x = $this->x;
[474] 			$pk->y = $this->y;
[475] 			$pk->z = $this->z;
[476] 			$pk->speedX = $this->motionX;
[477] 			$pk->speedY = $this->motionY;
[478] 			$pk->speedZ = $this->motionZ;
[479] 			$pk->yaw = $this->yaw;
[480] 			$pk->pitch = $this->pitch;
[481] 			$pk->item = $this->getInventory()->getItemInHand();
[482] 			$pk->metadata = $this->dataProperties;
[483] 			$player->dataPacket($pk);
[484] 
[485] 			$this->sendLinkedData();
[486] 
[487] 			$this->inventory->sendArmorContents($player);
[488] 
[489] 			if(!($this instanceof Player)){
[490] 				$this->server->removePlayerListData($this->getUniqueId(), [$player]);
[491] 			}

Backtrace:
#0 /src/pocketmine/Player(992): pocketmine\Player->spawnTo(synapse\Player Player(4))
#1 /src/pocketmine/Player(951): pocketmine\Player->doFirstSpawn(boolean)
#2 /src/pocketmine/Player(2041): pocketmine\Player->sendNextChunk(boolean)
#3 /src/pocketmine/Server(2988): pocketmine\Player->checkNetwork(boolean)
#4 /src/pocketmine/Server(2679): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2557): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(2122): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/tcagame/admin/5/PocketMine-MP.phar/, string /home/tcagame/admin/5/, string /home/tcagame/admin/5/plugins/, string unknown)
#8 (1): require_once(string phar:///home/tcagame/admin/5/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.2dev #573 [Protocol 81; API 2.0.0]
uname -a: Linux Server.PocketMiners.com 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 22 seconds
Number of loaded worlds: 1
Players online: 4/256

Loaded plugins:
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0
PMCommands 1.1 by Legoburner73 for API(s) 1.9.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
SW_svile 0.6 by svile for API(s) 1.13.0
NameCorrector 1.0.0#build010 by PEMapModder for API(s) 1.8.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
essentialsTP 1.5 by  for API(s) 2.0.0
SecretSauce 1 by HostingItAll for API(s) 2.0.0
SAMMY 1.5.15 by Humerus,HostingItAll for API(s) 1.9.0
SammyExtras 1 by aliuly for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by dog194** [comment]
Synapse bug.(Error: Call on null) Do not use Synapse now. wait for fixing.

**Comment by kabluinc** [comment]
still happening, no plugins used
