### ISSUE TITLE
Crash without error

### ISSUE THREAD

**Issue by mixailenko5** [iTXTech/Genisys#1346]
crash occurred without reason . And everything is good after restarting . What could it be?

Genisys Crash Dump Sat Jul 2 01:40:20 CDT 2016

Error: 
File: 
Line: 
Type: 

Code:
[1] 
[2] 
[3] 
[4] 
[5] 
[6] 
[7] 
[8] 
[9] 
[10] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #416 [Protocol 70; API 2.0.0]
uname -a: Linux localhost 3.10.17 #1 SMP PREEMPT Thu Mar 24 14:16:45 CST 2016 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

**Comment by ishitatsuyuki** [comment]
Seems it's corrupting more in crashdump now. @dktapps please take a look.

**Comment by dktapps** [comment]
@ishitatsuyuki this happened before anyway. (With backtrace #0)

**Comment by dktapps** [comment]
Also your version is a LOT out of date.
