### ISSUE TITLE
Economy PShop

### ISSUE THREAD

**Issue by Infernus101** [iTXTech/Genisys#1348]
#### Issue description
Itemcloud says 'Shop Owner doesn't own a Itemcloud account even though the player has and is online too, checked it myself! and thatswhy player can't can't buy from other player's shop

#### Steps to reproduce the issue
 I dont know

#### OS and versions

* Genisys: Genisys 1.2dev-581 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.15.0 alpha (protocol version 81)
* PHP: 7
* OS: Windows 10 

#### Crashdump, backtrace, Plugins list or other files
```
None
```

**Comment by dog194** [comment]
Ask help from onebone. no here

**Comment by Infernus101** [comment]
wtf

**Comment by dktapps** [comment]
Okay, I've had enough of you. I've already had to ban you from Gitter.

**Comment by PeratX** [comment]
DO NOT REPORT PLUGIN ISSUE HERE. CONTACT THE AUTHOR OF THE PLUGIN.

**Comment by dktapps** [comment]
Banned.
