### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#135]
Error: Argument 1 passed to pocketmine\item\Item::get() must be of the type integer, string given, called in /root/classic/src/pocketmine/nbt/NBT.php on line 111
File: /src/pocketmine/item/Item
Line: 1147
Type: notice

Code:
[1138] 		foreach(Item::$creative as $i => $d){
[1139] 			if($item->equals($d, !$item->isTool())){
[1140] 				return $i;
[1141] 			}
[1142] 		}
[1143] 
[1144] 		return -1;
[1145] 	}
[1146] 
[1147] 	public static function get(int $id, $meta = 0, int $count = 1, $tags = "") : Item{

**Comment by xpyctum** [comment]
hule tak?

**Comment by MrDoni98** [comment]
xz

**Comment by MrDoni98** [comment]
в нагрузку ))
 Error: "Call to undefined method pocketmine\network\rcon\RCONInstance::kill()" (EXCEPTION) in "/src/pocketmine/network/rcon/RCON" at line 74
[20:15:50] [Server thread/EMERGENCY]: Crashed while crashing, killing process

**Comment by mixailenko5** [comment]
@xpyctum я помню, что ты делал коммит где добавлял перед переменными в функциях указатели на тип данных. Я так делать не советую, так как вот тебе пример тому. Так же после таких указателей множество поагинов не работают. Указатели необязательны в пхп7.

**Comment by PeratX** [comment]
I think this is caused by a plugin.

**Comment by MrDoni98** [comment]
@PeratX 
Error: Argument 1 passed to pocketmine\item\Item::get() must be of the type integer, string given, called in /root/classic/src/pocketmine/nbt/NBT.php on line 111
File: /src/pocketmine/item/Item
Line: 1147
Type: notice

Code:
[1138] 		foreach(Item::$creative as $i => $d){
[1139] 			if($item->equals($d, !$item->isTool())){
[1140] 				return $i;
[1141] 			}
[1142] 		}
[1143] 
[1144] 		return -1;
[1145] 	}
[1146] 
[1147] 	public static function get(int $id, $meta = 0, int $count = 1, $tags = "") : Item{

**Comment by flaxues** [comment]
What plugins do you use?

**Comment by MrDoni98** [comment]
EconomyAPI v2.0.8, EconomySell v2.0.6, EconomyShop v2.0.6, EconomyJob v2.0.4, ServerAuth v0.1, PurePerms v1.2.2, vgapi v0.1 beta, RegionGuard vultra, AdvancedKits v4.1, PureChat v1.3.4-INDEV

**Comment by flaxues** [comment]
Do you know when it happens?

**Comment by MrDoni98** [comment]
when a player is teleported to spawn

**Comment by flaxues** [comment]
Ok move all you're plugins to a directory outside the server directory but keep vgapi and RegionGuard. And look if the crash is still happening

**Comment by mixailenko5** [comment]
And run yours server without plugins.

**Comment by MrDoni98** [comment]
@mixailenko5 I deleted all the plugins the same result

**Comment by mixailenko5** [comment]
Can you tun server without folder "worlds" and "players". If you want you can rename this folders, and after test rename to "worlds" and "players" again.

**Comment by mixailenko5** [comment]
run*

**Comment by MrDoni98** [comment]
without a map working, but in the last build of all it was okay

**Comment by flaxues** [comment]
So if you put everything back plugins, worlds and players you don't get this crash anymore?

**Comment by PocketKiller** [comment]
this is about PHP i think.

**Comment by PocketKiller** [comment]
where foreach($something as $somethingelse => $i) there is a problem.

**Comment by PocketKiller** [comment]
also caused on Level.php at line 1631

**Comment by MrDoni98** [comment]
Argument 2 passed to pocketmine\item\Item::get() must be of the type integer, null given, called in /root/classic/src/pocketmine/inventory/CraftingManager.php on line 604
File: /src/pocketmine/item/Item
Line: 1141
[1141] 	public static function get(int $id, int $meta = 0, int $count = 1, $tags = "") : Item{

**Comment by MrDoni98** [comment]
Thank you for the question almost resolved ...
Crash stopped, but I figured out the reason.Error for Anvil world.
![Generator](http://storage7.static.itmages.ru/i/16/0125/h_1453734034_7541487_dff582c5b2.jpg)

**Comment by MrDoni98** [comment]
The result was a funny world

**Comment by flaxues** [comment]
Looks cool

**Comment by flaxues** [comment]
If you don't have this crashes anymore you can just close it :P
