### ISSUE TITLE
Crash when changing levels

### ISSUE THREAD

**Issue by Skull3x** [iTXTech/Genisys#1350]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace, Plugins list or other files
```
There is no crash dump, just an issue that I keep experiencing for some unknown reason
```

**Comment by dktapps** [comment]
At least provide some information if you expect us to fix it.

**Comment by Skull3x** [comment]
It's hard to explain, it just happens. I have nothing to tell you but that. No errors in console ir anything, I downloaded a map from a resourceful website and use manyworlds to warp to it and I instantly crash when my chunks load
