### ISSUE TITLE
Crash when changing levels - repost

### ISSUE THREAD

**Issue by Skull3x** [iTXTech/Genisys#1351]
I'm reposting this issue since I didn't provide enough much needed information

No errors in console or anything, I downloaded a map from a resourceful website and use manyworlds to warp to it and I instantly crash when my chunks load.

Any way this can be fixed in the future?

**Comment by Driesboy** [comment]
follow the template!

**Comment by IrishUHC** [comment]
There are clients crashes with unknown blocks, could this be the source of your problem? Beetroots? Some 1.8 blocks, lots of 1.9 blocks, etc.

**Comment by dktapps** [comment]
Closing for not following template. Continue to spam and you'll be banned.
