### ISSUE TITLE
Spawn protection won't work anymore

### ISSUE THREAD

**Issue by FaanMaario** [iTXTech/Genisys#1352]
#### Issue description

I have changed my spawn protect to 100 blocks, I reboot my server and now my spawn protection won't work even if I reset server.properties

#### OS and versions

* Genisys: 1.2dev-93f32ac1 
* PHP: php7
* OS: GNU/Linux

#### Crashdump, backtrace, Plugins list or other files
```
Nothing
```

**Comment by dktapps** [comment]
Why are you using the W10 builds? Not for production use.

**Comment by FaanMaario** [comment]
Oh sorry, I make a typo; it's 93f32ac1

**Comment by PeratX** [comment]
Oh, this is nothing with 93f32ac

**Comment by PeratX** [comment]
Checked nothing is wrong. Spawn Protection will not limit Op.
