### ISSUE TITLE
Console Notice "Undefined offset: -1 in Potion.php on line 157

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Genisys#1355]
#### Issue description
The console is occasionally showing a notice:
``` "Notice: Undefined offset: -1 in phar:///usr/games/pocketmine-mp/Genisys_1.2dev.phar/src/pocketmine/item/Potion.php on line 157"````

#### Steps to reproduce the issue
I only saw the notice at console, I don't know which action triggered it.

#### OS and versions
* Genisys: Build 5​82
* PHP: PHP 7.0.3 (cli) (built: Feb  7 2016 21:08:57) ( ZTS )
* OS: Ubuntu 14.04.4 LTS

#### Crashdump, backtrace, Plugins list or other files
*only a notice*

**Comment by PeratX** [comment]
You are trying to use an unknown Potion.
