### ISSUE TITLE
Husks burn in daylight

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1356]
#### Issue description

Husks in 0.15.0 do not burn in daylight on singleplayer, while in Genisys they burn during the day.
#### OS and versions

* Genisys: 1.2dev
* PHP: 7.0.4
* OS: Windows 10 Insider Preview

#### Crashdump, backtrace, Plugins list or other files
```
Paste here
```

**Comment by dktapps** [comment]
Their AI is exactly the same as Zombie. I'll fix this
