### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nishuo** [iTXTech/Genisys#1357]
#### Issue description

Normal game, pop-up server close, see the back-end have serious error
#### OS and versions

* Genisys:1.2dev (run from source)
* PHP:7.0.8
* OS:Liunx CentOS 6.5

#### Crashdump, backtrace, Plugins list or other files
```
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 86016 bytes)
File: /src/pocketmine/Player
Line: 4457
Type: E_ERROR

Code:
[4448] 	public static function getChunkCacheFromData($chunkX, $chunkZ, $payload, $ordering = FullChunkDataPacket::ORDER_COLUMNS){
[4449] 		$pk = new FullChunkDataPacket();
[4450] 		$pk->chunkX = $chunkX;
[4451] 		$pk->chunkZ = $chunkZ;
[4452] 		$pk->order = $ordering;
[4453] 		$pk->data = $payload;
[4454] 		if(Network::$BATCH_THRESHOLD >= 0){
[4455] 			$pk->encode();
[4456] 			$batch = new BatchPacket();
[4457] 			$batch->payload = zlib_encode(Binary::writeInt(strlen($pk->getBuffer())) . $pk->getBuffer(), ZLIB_ENCODING_DEFLATE, Server::getInstance()->networkCompressionLevel);
[4458] 			$batch->encode();
[4459] 			$batch->isEncoded = true;
[4460] 			return $batch;
[4461] 		}
[4462] 		return $pk;
[4463] 	}
[4464] 
[4465] 
[4466] }
[4467] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

```

**Comment by dktapps** [comment]
Mem leak

**Comment by legoboy0215** [comment]
Memory leak.

**Comment by dktapps** [comment]
Please post a full crashdump.

**Comment by nishuo** [comment]
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 86016 bytes)
File: /src/pocketmine/Player
Line: 4457
Type: E_ERROR

Code:
[4448] 	public static function getChunkCacheFromData($chunkX, $chunkZ, $payload, $ordering = FullChunkDataPacket::ORDER_COLUMNS){
[4449] 		$pk = new FullChunkDataPacket();
[4450] 		$pk->chunkX = $chunkX;
[4451] 		$pk->chunkZ = $chunkZ;
[4452] 		$pk->order = $ordering;
[4453] 		$pk->data = $payload;
[4454] 		if(Network::$BATCH_THRESHOLD >= 0){
[4455] 			$pk->encode();
[4456] 			$batch = new BatchPacket();
[4457] 			$batch->payload = zlib_encode(Binary::writeInt(strlen($pk->getBuffer())) . $pk->getBuffer(), ZLIB_ENCODING_DEFLATE, Server::getInstance()->networkCompressionLevel);
[4458] 			$batch->encode();
[4459] 			$batch->isEncoded = true;
[4460] 			return $batch;
[4461] 		}
[4462] 		return $pk;
[4463] 	}
[4464] 
[4465] 
[4466] }
[4467] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

**Comment by legoboy0215** [comment]
Maybe for a temp solution lower the network compression level?

**Comment by dktapps** [comment]
@legoboy0215 of course

**Comment by nishuo** [comment]
@dktapps @legoboy0215  network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable.
 batch-threshold: 256
 #Compression level used when sending batched packets. Higher = Uses More CPU, Less = M$
 compression-level: 2

**Comment by dktapps** [comment]
Your stated version is not valid. Please write a Jenkins build number or GitLab hash

**Comment by legoboy0215** [comment]
Set it to something like 128

**Comment by dktapps** [comment]
No, leave that alone. I can't diagnose the problem if you change the symptoms

**Comment by nishuo** [comment]
Genisys 1.2dev “Ikaros”  API version 2.0.0 支 Minecraft：PE v0.15.0 alpha （Protocol version 81）
@dktapps

**Comment by dktapps** [comment]
I need to fix that damn backtrace too, it seems to crash the crashdump -_-

**Comment by nishuo** [comment]
- -！ Thank you for you two

**Comment by dktapps** [comment]
Hmm, are you running from src instead of phar?

**Comment by nishuo** [comment]
Yes, I use git clone

**Comment by dktapps** [comment]
And you're definitely updated to the latest commit yes?

**Comment by nishuo** [comment]
sure

**Comment by legoboy0215** [comment]
@dktapps I believe it is because xDebug is not installed.

**Comment by dktapps** [comment]
@legoboy0215 shut up and leave the bugfixing to the people who know how. That's nonsense.

**Comment by legoboy0215** [comment]
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/CrashDump.php#L125
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/PocketMine.php#L352-L357
If xDebug isn't installed it uses this:
```
$e = new \Exception();
$trace = $e->getTrace();
```
Which doesn't return the actual trace like xDebug does.

**Comment by dktapps** [comment]
@legoboy0215 that's nonsense. The zero backtrace is a random bug. And if we start running xdebug on production builds that's going to cause huge performance issues. xdebug is for testing only.

**Comment by PeratX** [comment]
喜闻乐见→_→看看你插件

**Comment by dktapps** [comment]
Hmm. It'd be good if I could set it up to automatically dump memory when the limit is reached.

**Comment by dktapps** [comment]
Okay. @nishuo Could you update to the latest build please? Then, when the server is at high memory usage, say around 800~900MB, run /dumpmemory. It'll dump a bunch of files into the `memory_dump/memoryDump_<date>` folder in your server folder. Compress the memory dump, upload it somewhere and post a link so I can examine it. Thanks.

**Comment by XxDXM-hippiexX** [comment]
I disabled async-chunk-request in the genisys.yml and i think this stopped..not positive yet though.

**Comment by nishuo** [comment]
@dktapps Thank you！

**Comment by andris155** [comment]
Big Thanks!!!!!! I disabled async-chunk-request fixed this bug!!!!!!!

**Comment by Muqsit** [comment]
Yeah, if you have low cpu cores, async tasks can eat up your memory real quick!

**Comment by dktapps** [comment]
Hmm. I'll investigate this.

**Comment by FaanMaario** [comment]
I think I have again the same issue, but now with a lot of lags spikes. :/

**Comment by EpicSteve33** [comment]
I still have this issue on my server and "async-chunk-request" is set to false in the genisys.yml, i run a small server and it crashes every hour or so even when no players are active and the crash dumb I have given is from today and the server has crashed at least 5 times today please fix this somehow

```
Genisys Crash Dump Wed Aug 3 16:04:01 ACT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65536 bytes)
File: /src/pocketmine/Player
Line: 4425
Type: E_ERROR

Code:
[4416] 	public static function getChunkCacheFromData($chunkX, $chunkZ, $payload, $ordering = FullChunkDataPacket::ORDER_COLUMNS){
[4417] 		$pk = new FullChunkDataPacket();
[4418] 		$pk->chunkX = $chunkX;
[4419] 		$pk->chunkZ = $chunkZ;
[4420] 		$pk->order = $ordering;
[4421] 		$pk->data = $payload;
[4422] 		if(Network::$BATCH_THRESHOLD >= 0){
[4423] 			$pk->encode();
[4424] 			$batch = new BatchPacket();
[4425] 			$batch->payload = zlib_encode(Binary::writeInt(strlen($pk->getBuffer())) . $pk->getBuffer(), ZLIB_ENCODING_DEFLATE, Server::getInstance()->networkCompressionLevel);
[4426] 			$batch->encode();
[4427] 			$batch->isEncoded = true;
[4428] 			return $batch;
[4429] 		}
[4430] 		return $pk;
[4431] 	}
[4432] 
[4433] 
[4434] }
[4435] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: d7570abcc21706eda463da215e97be2c1a4d501f [Protocol 82; API 2.0.0]
uname -a: Linux server.kingdomcraft.net 2.6.32-042stab108.6 #1 SMP Thu Jul 9 13:40:24 MSK 2015 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 58 minutes 39 seconds
Number of loaded worlds: 6
Players online: 3/200

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ZipPluginLoader 1.1.3 by aliuly for API(s) 2.0.0
HereAuth 1.0-Dev#229 by PEMapModder for API(s) 2.0.0
KingdomCore 0.3 by EpicSteve33 for API(s) 2.0.0
SurvivalGames 0.1dev by EpicSteve33 for API(s) 1.0.0, 2.0.0, 3.0.0
SignPortal 1.1.2 by 99leonchang for API(s) 2.0.0
SW_svile 0.6dev by svile for API(s) 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
```

**Comment by dktapps** [comment]
@EpicSteve33 Please could you follow the instructions in [this](https://github.com/iTXTech/Genisys/issues/1357#issuecomment-230752569) post? That would be very helpful. Thank you.

**Comment by EpicSteve33** [comment]
@dktapps I will try but I am not awake when it crashes most of the time so ill try my best to catch it at 800-900

**Comment by Muqsit** [comment]
No, this is nothing to do with chunks being corrupted or anything of that way.

`Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65536 bytes)`
just means that it tried to allocate 1073741824 bytes (1073 MB or a little more than 1 GB) of RAM but couldn't. By default, in your pocketmine.yml, `main-hard-limit` is set to `1024`. I think you must increase it to `4096` or how much ever RAM you are able to donate to run PocketMine.
`

**Comment by legoboy0215** [comment]
@Muqsit But this is a memory leak.

**Comment by EpicSteve33** [comment]
After removing a plugin my server stopped crashing so idk why

**Comment by legoboy0215** [comment]
Which plugin?

**Comment by yhzx233** [comment]
@EpicSteve33 Which plugin?
