### ISSUE TITLE
When stop server in ssh

### ISSUE THREAD

**Issue by flash586** [iTXTech/Genisys#136]
https://goo.gl/photos/fLy8DmS1FBG398SA9

**Comment by flash586** [comment]
And this issue https://goo.gl/photos/udxJjYy28x3u9GJm7

**Comment by flash586** [comment]
and please tell me what is wrong here? https://goo.gl/photos/rFHSECTmPZJs3m5N6 where is event crafting?

**Comment by PeratX** [comment]
Sorry Google is blocked in China...

**Comment by flash586** [comment]
How I can upload image?

**Comment by flash586** [comment]
![screenshot_20160124-015632](https://cloud.githubusercontent.com/assets/14042336/12533843/aeeb83d6-c248-11e5-95bc-b48afc738fee.png)
1

**Comment by flash586** [comment]
![screenshot_20160124-025153](https://cloud.githubusercontent.com/assets/14042336/12533850/dfe66708-c248-11e5-9e31-2240894e446e.png)
2

**Comment by flash586** [comment]
![screenshot_20160124-025330](https://cloud.githubusercontent.com/assets/14042336/12533852/f027105e-c248-11e5-9022-a1673ba8c713.png)
3

**Comment by flash586** [comment]
Sorry, I can't load in mobile version

**Comment by flash586** [comment]
3 screenshots errors

**Comment by flash586** [comment]
accidentally closed

**Comment by GalvinGao** [comment]
Please try to disable **ALL** plugins and start the server.

**Comment by flash586** [comment]
only problem with event crafting refers to plugins
24 янв. 2016 г. 4:40 пользователь "GalvinGao" <notifications@github.com>
написал:

**Comment by GalvinGao** [comment]
Ok. Confirmed that it is a **bug**.

**Comment by PeratX** [comment]
The first issue has fixed.The second has confirmed no problem.The third is caused by a plugin.

**Comment by flash586** [comment]
but where did he go this event? (3)
24 янв. 2016 г. 11:49 пользователь "Khan Noonien Singh" <
notifications@github.com> написал:
