### ISSUE TITLE
Can't join

### ISSUE THREAD

**Issue by cpdough18** [iTXTech/Genisys#1361]
#### Issue description
Any version of mcpe I use won't let me join all versions say outdated even versions that aren't updated for genisys yet like 0.15.1

#### OS and versions

* Genisys: 0.15.0 alpha specific unknown
* PHP:7
* OS: netherbox hosting is unknown

#### Crashdump, backtrace, Plugins list or other files
```
Paste here
```

**Comment by dktapps** [comment]
Go complain to your host. This is not our issue.

**Comment by cpdough18** [comment]
Actually it is because all my console logs says it is a mcpe version problem
