### ISSUE TITLE
Genisys problem

### ISSUE THREAD

**Issue by cpdough18** [iTXTech/Genisys#1362]
Issue description

Any version of mcpe I use won't let me join all versions say outdated even versions that aren't updated for genisys yet like 0.15.1

Steps to reproduce the issue

OS and versions

Genisys: 0.15.0 alpha specific unknown
PHP:7
OS: netherbox hosting is unknown
Crashdump, backtrace, Plugins list or other files

It is ur problem because my hoster said its problem with mcpe version
Paste here

**Comment by dktapps** [comment]
Continue to spam and you'll be banned. This is not a Genisys fault. Go ask your host to update.
