### ISSUE TITLE
Cactus damage bug

### ISSUE THREAD

**Issue by mixailenko5** [iTXTech/Genisys#1367]
Cactus kills the player very quickly. In the original MCPE cactus kill the player slower. Fix it please. If player damage by other player this bug happened too.

**Comment by dog194** [comment]
The cooldown is 0.5s.
is it too short? I dont know in original MCPE it should be.

**Comment by mixailenko5** [comment]
![image](https://cloud.githubusercontent.com/assets/12220551/16588643/8dd459d2-42d8-11e6-8dc3-35edd3e22896.png)
 @dog194  Cactus killed me for 2 seconds)

**Comment by dog194** [comment]
just test. it works fine (0.5s cooldown.)do you use any  plugin?although it call the event several in 1s. but it attack 2 times only

**Comment by mixailenko5** [comment]
@dog194  see it https://github.com/mixailenko5/PluginMaker_not_official_tests/blob/master/Minecraft%20-%20Pocket%20Edition-2016-07-05_18-30-26.mp4 . "Plugin" - is fully empty plugin.

**Comment by mixailenko5** [comment]
@dog194  and i use the last build of Genisys. I download it from Jenkins today
