### ISSUE TITLE
MobAI Not Working

### ISSUE THREAD

**Issue by gaoyichuan** [iTXTech/Genisys#137]
When I spawn a zombie with the zombie egg. It just stands there and does nothing. Also confirmed on spiders and villagers.

**Comment by gaoyichuan** [comment]
BTW, I pulled the repo on my server and run it. So it must be the latest version.

**Comment by GalvinGao** [comment]
Confirmed as a **Need to Add - To-Do List - Feature**

**Comment by gaoyichuan** [comment]
@GalvinGao Well, I throught MobAI has been added.

**Comment by GalvinGao** [comment]
Ok... I'm just made a mistake......

- Confirme as **Fixed**

**Comment by GalvinGao** [comment]
... I dont mean to close

**Comment by gaoyichuan** [comment]
I found the configure file genisys.yml and I found it's completely my fault. Close it.
文档中是否应该增加有关这些配置的说明？

**Comment by GalvinGao** [comment]
Yeah and i've just add it at #139 .
