### ISSUE TITLE
Damage bug!

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#1372]
#### Issue description

If i hit a player he become damage but icant see it he is not red and no knockback
#### Steps to reproduce the issue

Install #603 or later

#### OS and versions

* Genisys: #603
* PHP: 7.0.8
* OS: Linux

#### Crashdump, backtrace, Plugins list or other files
```
Paste here
```

**Comment by dktapps** [comment]
Argh! I _said_ this would happen!

**Comment by erkam2002** [comment]
Ok...

**Comment by FaanMaario** [comment]
Yeah I have the same problem, I thought that it was a plugin, but apparently not :p

**Comment by dktapps** [comment]
It's the PvP flags in the adventure settings packet. Not sure how to fix it without API changes or breaking something else. @PeratX ?

**Comment by dog194** [comment]
@dktapps  revert this ecd95591b98bae56d703815003730c403e6e5414

**Comment by dktapps** [comment]
@dog194 is that what's causing the problem? I can't see anything wrong with it...

**Comment by dog194** [comment]
@dktapps right, You can make a brunch to have a test. @PeratX  change this without enough consideration. He use an unappropriate way to add public function attack() in Human.php
So the bug of attack cooldown and Knowback are create.
You can try to fix, or revert as a temp fixing. I will contact PeratX tomorrow. XD It's 1:21 AM in China now.

**Comment by dktapps** [comment]
@dog194 I'll let @PeratX fix the mess :P
