### ISSUE TITLE
rehealthing issue

### ISSUE THREAD

**Issue by FuxonPlayz** [iTXTech/Genisys#1375]
#### Issue description
when i disable hunger in genisys.yml and when my players get hurt they cant reheal

#### Steps to reproduce the issue
enable hunger in genisys.yml

#### OS and versions

* Genisys: build 604 from Jenkins
* PHP: 7.0
* OS: Linux

#### Crashdump, backtrace, Plugins list or other files
```
none
```

**Comment by PeratX** [comment]
You disabled hunger and server will not calculate heal
