### ISSUE TITLE
Feature Request: Ride Animals

### ISSUE THREAD

**Issue by GlitchPlayer** [iTXTech/Genisys#1376]
#### Issue description

This is a feature request or more of "Enhancement" I have no idea where should I request. But so far as I know. Issues tab in github is also available for feature request.

Riding in animals with saddles. If you guys are still busy in fixing bugs. This issue can wait. So far in my understanding. This feature could be used for plugins that ride pets.
#### Steps to reproduce the issue

NOPE
#### OS and versions

- Genisys: 607
- PHP: 7
- OS: Windows 10
#### Crashdump, backtrace, Plugins list or other files

```
Paste here
```

**Comment by PeratX** [comment]
What do you mean? Tap an animal with saddle and you are riding on it?

**Comment by dktapps** [comment]
Horses need to be added first :P

**Comment by PeratX** [comment]
xD

**Comment by GlitchPlayer** [comment]
But we had pigs :)

**Comment by GlitchPlayer** [comment]
Yes PetraX

**Comment by ImagicalGamer** [comment]
@dktapps I can provide a 10GB test server if you would like for all of iTX-Tech to use with MultiCraft?

**Comment by ZedCee** [comment]
I saw this plugin a while back, had about 5 minutes of fun eclectically moving around, then had to take a break.  Maybe there's something here worth investigating?  If anything it may tide you over in the meantime.
https://github.com/WEDeach/RidePig

**Comment by CubeFromSpace** [comment]
There has to be a data somewhere for if you are riding something. If not, then it is hard to make a new NBT for the game

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/tree/mobs

Will be working on riding mobs and jockeys very soon. I figure they don't _need_ AI to be initially rideable; they are basically vehicles.
