### ISSUE TITLE
Fps lags

### ISSUE THREAD

**Issue by Marttinek** [iTXTech/Genisys#1377]
Hi , I opened the server , I have a small spawn , and are big lag on it ( fps) Genysis lags mcpe ? ... Sorry for the English , I'm from Polish.

**Comment by dog194** [comment]
Please follow the template.otherwise we will close this issue.

**Comment by PeratX** [comment]
Do not use too much particles, sounds or entities, they will cause that, this is not server's fault.
You can upgrade you phone too!
