### ISSUE TITLE
RedStone Not Working

### ISSUE THREAD

**Issue by gaoyichuan** [iTXTech/Genisys#138]
Well, another one...
Redstone aren't working at all.

**Comment by GalvinGao** [comment]
Please take some screenshot so that we can believe that because seems like works on my server. And please say that **WHAT IS NOT WORKING** (example: Redstone Torch cannot be automatically turn off when powered.)

**Comment by gaoyichuan** [comment]
I found the configure file genisys.yml and I found it's completely my fault. Close it.
