### ISSUE TITLE
SUGGESTION: Method to check if players are logged into XBox live?

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1384]
I want all players of my server to be using Xbox live so I can get rid of auth plugins, is that possible?

**Comment by gaoyichuan** [comment]
Well, neither XBOX live nor Mojang provided an API for it, it may be difficult. :(

**Comment by dktapps** [comment]
This requires encryption support, which impacts on the performance. PHP is slow enough already.

**Comment by PeratX** [comment]
Write C extension! :(

**Comment by XFuryMCPE** [comment]
Just make it a feature that can be turned on and off..?

**Comment by FaanMaario** [comment]
That'll be awesome, but much slower :/

**Comment by HimbeersaftLP** [comment]
If u want do make it, I'd recommend to wait until xbox live auth has been added to all OSes, because otherwise Fire Phone/Tab users and Windows Phone users won't be able to join anymore.

**Comment by Vaivez66** [comment]
I think BrokenLens already did it... If BrokenLens can, it means it's still possible...

**Comment by GlitchPlayer** [comment]
BrokenLens made windows 10 user unable to join their servers :(
