### ISSUE TITLE
Genisys memory bugs pls fix!

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1385]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/16636075/1d9a56f4-43d6-11e6-9294-48db8b71c54e.PNG)

**Comment by Adam1609** [comment]
They are fixing this. Please patient!

**Comment by gaoyichuan** [comment]
#1357

**Comment by dktapps** [comment]
Minimal CPU usage, but lots of memory leaked. This is new.
