### ISSUE TITLE
NoteblockSound not working

### ISSUE THREAD

**Issue by undrfined** [iTXTech/Genisys#1387]
#### Issue description
When i try to add NoteblockSound to level nothing happens on client side BUT Noteblock working properly.

#### Steps to reproduce the issue
Add NoteblockSound to level.

#### OS and versions
* Genisys: 615
* PHP: 7
* OS: Windows 7

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
...
```

**Comment by PeratX** [comment]
You must have a noteblock in the position where you want to add NoteblockSound
