### ISSUE TITLE
closeWindow() bug

### ISSUE THREAD

**Issue by AvivShopen** [iTXTech/Genisys#1388]
#### Issue description
players hotbar gone when using closeWindow()

#### Steps to reproduce the issue
when im using closeWindow() players hotbar dissappears.
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by dktapps** [comment]
Closing for not following template. Supply versions as the template asks you to.

**Comment by AvivShopen** [comment]
I edited the issue

**Comment by dktapps** [comment]
Your version is a long way out of date.

**Comment by AvivShopen** [comment]
I updated to 620 still same

**Comment by AvivShopen** [comment]
its wierd because in 0.14.3 it was all good, maybe a client bug?

**Comment by dktapps** [comment]
actually, you're wrong. This happened as early as 0.14.1, and yes it is a client bug. It happens in singleplayer too.

**Comment by AvivShopen** [comment]
i tested it out now and it works perfectly in 0.14.3, its never happend to me in single player, but who knows... BTW, when players taps the x button to exit the chest, its not seems that the player hotbar is gone, ill check the code
