### ISSUE TITLE
Call to a member function setContents() on null

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1389]
Error: Call to a member function sendContents() on null
File: /src/pocketmine/Player
Line: 1038
Type: notice

Code:
[1029] 		if($this->getHealth() <= 0){
[1030] 			$pk = new RespawnPacket();
[1031] 			$pos = $this->getSpawn();
[1032] 			$pk->x = $pos->x;
[1033] 			$pk->y = $pos->y;
[1034] 			$pk->z = $pos->z;
[1035] 			$this->dataPacket($pk);
[1036] 		}
[1037] 
[1038] 		$this->inventory->sendContents($this);
[1039] 		$this->inventory->sendArmorContents($this);
[1040] 	}
[1041] 
[1042] 	protected function orderChunks(){
[1043] 		if($this->connected === false){
[1044] 			return false;
[1045] 		}
[1046] 
[1047] 		Timings::$playerChunkOrderTimer->startTiming();
[1048] 

Backtrace:
#0 /src/pocketmine/Player(2043): pocketmine\Player->sendNextChunk(boolean)
#1 /src/pocketmine/Server(2990): pocketmine\Player->checkNetwork(boolean)
#2 /src/pocketmine/Server(2681): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(2559): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(2124): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/1/root/PocketMine-MP.phar/, string /root/1/root/, string /root/1/root/plugins/, string unknown)
#6 (1): require_once(string phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.2dev #620 [Protocol 81; API 2.0.0]
uname -a: Linux ast.localdomain 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 23 seconds
Number of loaded worlds: 7
Players online: 23/90

**Comment by dktapps** [comment]
_Most_ of our issues are Genisys problems. Please give a more descriptive title.

**Comment by dog194** [comment]
Also please paste your plugins list and Genisys.yml setting. And do not forget to delet some Privacy Information you think in Genisys.yml(Such as Key IP ID and some others)

**Comment by TDMidkwhatisxd** [comment]
Try opkick for im plugins , it give this crash!!  On older versions is working well!!
I made another plugin , using 3 plugins code , so i just took the code. (If "i made another plugin" is wrong please correct me )

Someone got op (haaacks xdxd) , and opkick did its job , kicked the op but soon after server crashed!!

**Comment by TDMidkwhatisxd** [comment]
Sorry for double post , now im fine with new plugin

**Comment by TDMidkwhatisxd** [comment]
<?php

namespace OpKick;

use pocketmine\plugin\PluginBase;
use pocketmine\event\Listener;
use pocketmine\event\player\PlayerJoinEvent;

class OpKick extends PluginBase implements Listener {
    public function onEnable(){
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }
    public function onJoin(PlayerJoinEvent $event){
        if ($event->getPlayer()->isOp()){
            $event->getPlayer()->kick();
        }
    }
}



If u think is plugin fault, look at code

**Comment by diamond-gold** [comment]
You should not kick the player at PlayerJoinEvent, cancel PlayerLoginEvent instead

**Comment by TDMidkwhatisxd** [comment]
I know , but it worked until i update to last genisys version!! I only submit this issue becouse i think is a glich or something that may break some plugins :D  !!

**Comment by TDMidkwhatisxd** [comment]
It seems all plugins that kick onjoin event crash server!! Why wont fix it?
I wanted to use antifly plugin , that auto temp ban!!
But if banned players join , server crash , becouse is onjoin event!!
