### ISSUE TITLE
enchantment.enable-anvil and enchantment.enable-enchanting-table don't work

### ISSUE THREAD

**Issue by jerryzooyoyo** [iTXTech/Genisys#1391]
#### Issue description

In `genisys.yml`, `enchantment.enable-anvil` and `enchantment.enable-enchanting-table` don't work.
Althougn they have been set to `false`, players still can use them.
Tested by my phone, ASUS ZenFone and Samsung Galaxy.
And the players in my server also tested.
#### Steps to reproduce the issue

Close the server.
Set `enchantment.enable-anvil` and `enchantment.enable-enchanting-table` in `genisys.yml` to `false`.
Restart the server.
But players still can use Anvils and Enchanting tables.
#### OS and versions

* Genisys: Latest version, the commit is"Changed default async-workers to prevent crash on servers which enabled super-threading technology", `ec7dab2`

* PHP: 7.0.4
* OS: Windows, Server 2012

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by PeratX** [comment]
Tested. It worked. Modify file when server is off.

**Comment by jerryzooyoyo** [comment]
@PeratX I have found how I made mistakes !
Thanks for looking this issue and testing.
Sorry, I didn't look into the file clearly.:(

**Comment by PeratX** [comment]
You are welcome
