### ISSUE TITLE
High loads

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1394]
Normaly i have loads 0.50-2.0  using top in linux console!!
These days , i see loads 6 in top !! And ofcourse console inactive!!

I wanna to know if is a ddos attack (im not good at this) !! Becouse it last few minutes , then all is operational again! Ddos is not supposed to last for hours?

Im really sorry if i broke any rule with this question!!

But i wanna make sure if is ddos or genisys fault :)

After answer u can close this if is useless!!

**Comment by dktapps** [comment]
Closing for not following template. And see #1059

**Comment by TDMidkwhatisxd** [comment]
It happens 2-3 times /day  , i use 3.5ghz cpu , 2 cores    .... I  hardly think that genisys can  cause 6 load.
Anyway thx for answer :)
