### ISSUE TITLE
Leads connected to all NPC's

### ISSUE THREAD

**Issue by HotshotHD** [iTXTech/Genisys#1398]
Leads are connected from the player, to all NPC's in the server. Not sure if this is a genisys bug, mcpe bug, or plugin bug.

**Comment by XFuryMCPE** [comment]
It's a plugin bug.

**Comment by XFuryMCPE** [comment]
You're super outdated.. we discuessed that a month ago

**Comment by HotshotHD** [comment]
What's the solution

**Comment by intagaming** [comment]
Solution is go to github and keep up to date.
Slapper has been updated to remove leads between NPCs and player since 1.2.9.5 .

**Comment by gaoyichuan** [comment]
This should be fixed long long ago

**Comment by HotshotHD** [comment]
I don't use slapper.

**Comment by intagaming** [comment]
Measure the lead packet. See commits in Slapper.

**Comment by HotshotHD** [comment]
Alright, thanks.
