### ISSUE TITLE
Vip Slots (feature request)

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1399]
Hi!! I wonder , why to no add vip slots to genisys !! I mean , those in whitelist to be able to join wen server is full!  
So , is posible to allow whitelisted players to connect wen server is full?

**Comment by CrayonDing** [comment]
Why don't you use a plugin to do that.

**Comment by TDMidkwhatisxd** [comment]
i dont know any , and one i used crashed :(

**Comment by ImagicalGamer** [comment]
Using a plugin you can allow whitelisted players to join when the server is full!

**Comment by CrayonDing** [comment]
I found this https://forums.pocketmine.net/plugins/vipslots.841/ in PM forums.Maybe you can try

**Comment by TDMidkwhatisxd** [comment]
I know it , dont work :( , well i tryed long ago !!

**Comment by intagaming** [comment]
What if i say VIPSlots works very well with me ?
![image](https://cloud.githubusercontent.com/assets/16471365/16676228/7f54d942-44f2-11e6-82fe-db8158647d1f.png)

**Comment by gaoyichuan** [comment]
Closed & locked: it's a plugin issue
