### ISSUE TITLE
Inventory update

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#14]
Hi!!  inventory update hard or just at an action!!!
I sell 64 diamonds,  they still in inventory,  if i click them or try to use they gone!!  So they should be gone after i sell them.
I sell 1 diamond,  i need to drop and take back to show 63 diamonds.

What im trying to say is that the inventory update really hard :D.

Good luck!!!  :)

**Comment by PeratX** [comment]
EconomySell?

**Comment by dog194** [comment]
确实会这样，用Esell 卖完需要自己打开背包点一下触发23333(Zhy服-Doggy)
Right, I have the same problem in the server own by ZhyMc. Used EconomySell. In fact, i think is not a very big problem. But it'd be better if this can be fixed.

**Comment by PeratX** [comment]
@astersx We will fix it.Thx for your report!
