### ISSUE TITLE
Problem with opcache.enable_cli

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#1401]
#### Issue description

In php.ini:
If i leave this "1" (On), then i can't open PocketMine with the same port twice if i open 2 of them with different port. For example i open 2 server 19131 and 19132, then i close 19131 and wait 1 minute then open 19131 again, and we have 3 case: Console shows nothing - error 127 or Segment fault.
Also, 

> opcache.enable_cli boolean
> Enables the opcode cache for the CLI version of PHP. This is mostly useful for testing and debugging.

If it's for Debugging then what if i disable it for Production? 
[http://stackoverflow.com/questions/25044817/zend-opcache-opcache-enable-cli-1-or-0-what-does-it-do](url)

> Leave it off. It's primarily there for use while debugging issues with OPcache itself.
> 
> The opcache.enable_cli option enables PHP OPcache when running PHP scripts from the command line (using the php command). However, keep in mind that the OPcache extension works by storing cached opcodes in the memory of the current process. This is only useful when the process that's running PHP is going to be handling multiple requests that can reuse these opcodes, like in a web server or under FastCGI. For a process like the PHP CLI, which runs one "request" and exits, it just wastes memory and time.

#### Steps to reproduce the issue

As above.

#### OS and versions

* Genisys: 620
* PHP: 7.0.4
* OS: Windows 10

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Nothing
```

**Comment by PeratX** [comment]
PHP's issue.
