### ISSUE TITLE
removeItem bug

### ISSUE THREAD

**Issue by Harviy** [iTXTech/Genisys#1408]
#### Issue description
item changed the name it, but not remove

$item = Item::get(276, 0, 1);
$item->setCustomName("Magic Sword");
$player->getInventory()->addItem($item);
no problem, but
$player->getInventory()->removeItem(Item::get(276));
not remove, please help

#### OS and versions

* Genisys: 1.2dev
* PHP: 7.0.4
* OS: Android

**Comment by PeratX** [comment]
You need to sendSlot after removeItem

**Comment by Harviy** [comment]
I tried but is working.
Rename item not remove.
