### ISSUE TITLE
How to setup Synapse

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#1409]
Sorry if this issue is completely off-topic but how exactly do you setup synapse. 

from the genisys.yml do we enter the server ip and port of the current server or of the server we will transfer to? I have tried doing both but it still says `[SynapseClient thread/ERROR]: Socket error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

[21:13:59] [SynapseClient thread/ERROR]: Synapse connection has disconnected unexpectedly`
I akso have the synapse transfer plugin installed but cant find any tutorial anywhere on how to get this working.

Thanks allot

**Comment by PeratX** [comment]
See Synapse Wiki.
