### ISSUE TITLE
Can't Download??

### ISSUE THREAD

**Issue by FactionsPe** [iTXTech/Genisys#1413]
Says when I try to download the installer that is failed because Visual C++ 2015 package was not found. How do I fix this?

**Comment by FactionsPe** [comment]
Also whenever I just download it all at the top of the page when I go to open it  is says can't find valid  version of download.

**Comment by FactionsPe** [comment]
And I have visual c++ downloaded on my pc but it keeps bringing up that error

**Comment by PeratX** [comment]
Go to microsoft.com to downlaod. Do not post any issue which not follow the template.

**Comment by dktapps** [comment]
@PeratX this is my bad I think, I'll fix it later :/

**Comment by dktapps** [comment]
I think I broke it when I added the new PHP packages
