### ISSUE TITLE
Random Banning?

### ISSUE THREAD

**Issue by BobbyTowers** [iTXTech/Genisys#1414]
#### Issue description

I have some players getting randomly banned. No one but ME the owner is op and all permissions have been checked. I removed all my plugins and it still happens.

#### Steps to reproduce the issue

Have players login.

#### OS and versions
* Genisys: 623
* PHP: 7.0.8
* OS: Win 7

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by BobbyTowers** [comment]
http://pastebin.com/pX6Ebvn9

**Comment by gaoyichuan** [comment]
**logged out due to Kicked by admin** Are you blind?

**Comment by BobbyTowers** [comment]
@gaoyichuan no asshole. No one is Admin dick. I'm the only person that can ban.

**Comment by dktapps** [comment]
I don't think there's any need for that.

**Comment by Muqsit** [comment]
@BobbyTowers Stop disrespecting Genisys Members and frickin check your banned-players.txt -.-

**Comment by BobbyTowers** [comment]
@Muqsit yeah because I didn't check that first. You guys need to be more helpful and stop blowing people off.

**Comment by dktapps** [comment]
Okay, that's enough. Banning @BobbyTowers

**Comment by dktapps** [comment]
People like you take far too much for granted.
