### ISSUE TITLE
Random Banning?

### ISSUE THREAD

**Issue by BobbyTowers** [iTXTech/Genisys#1415]
Issue description

I have some players getting randomly banned. No one but ME the owner is op and all permissions have been checked. I removed all my plugins and it still happens.

NO ONE CAN BAN BUT ME @gaoyichuan you asshole

Steps to reproduce the issue

Have players login.

OS and versions

Genisys: 623
PHP: 7.0.8
OS: Win 7
Crashdump, backtrace, memory dumps, plugins list or other files

http://pastebin.com/pX6Ebvn9

**Comment by dog194** [comment]
plugins list

**Comment by dog194** [comment]
banned-players.txt 
ops.txt

**Comment by BobbyTowers** [comment]
I removed all of my plugins.

Banned-cids: is blank and has no players

Banned-ip: is blank and has no players

ops: just has me the Owner and only OP BobbyTowers

Banned-players: # Updated 07/08/16 23:14 by Genisys 1.2dev-623
# victim name | ban date | banned by | banned until | reason

**Comment by dog194** [comment]
removed all of my plugins.?
What is this?
[Cmd] Doctor_Who_Fan> /p home
[S-Member] Doctor_Who_Fan > bad wolf
[RandomItem] Random item given! (295:0)
[ChestRefill] Chests have been reset.

**Comment by BobbyTowers** [comment]
Sorry that was before I removed them

**Comment by dog194** [comment]
Then re-test again and post new log.
And check enable-rcon=off in server.properties

**Comment by BobbyTowers** [comment]
ok will do

**Comment by BobbyTowers** [comment]
Ok so I think I fixed it. I deleted the banned-cids.txt, banned-ips.txt, banned-players.txt, genisys.yaml, ops.txt, pocketmine.yaml, server.txt, server.yaml and white-list.
