### ISSUE TITLE
Hot bar bug is back..

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#1419]
#### Issue description

The hot bar bug is back and worse than ever...

#### Steps to reproduce the issue

put stuff in your inventory..seems to always happen.
#### OS and versions

* Genisys: 626
* PHP: 7
* OS: windows

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by dktapps** [comment]
What's "the hotbar bug"? Be more informative.

**Comment by XxDXM-hippiexX** [comment]
I figured it was so common i didnt need to explain..lol Well..it shows the same item in multiple slots on your screen, so you may think your holding a sword when you pvp but really your hitting them with bread or something in the other player view. When it is glitched items in the hot bar will switch spots sometimes i think this is from holding a 'glitched' item and interacting with blocks/players. At first i thought it was a but with the new armor calculation system bc it would take 1000 hits to kill something then realized its the hot bar bug.

**Comment by XxDXM-hippiexX** [comment]
There was a creative inventory "hot bar fix" recently..maybe that was the cause?

**Comment by dktapps** [comment]
hmm. I've noticed the same thing actually, mainly on Win10. And you may be right, I'll look into it

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/commit/d1db7b6cf2f011eb0df65da7ea384721ce9deaf1
This is the commit you're referring to?

**Comment by dktapps** [comment]
Possibly #1395 may fix this problem too

**Comment by XxDXM-hippiexX** [comment]
I think so! i think there is a conflict of sorts bc i also had my inventory cleared once but it all came back when i relogged.

**Comment by XxDXM-hippiexX** [comment]
Im not sure if this is related..but ive also had a no gui bug..not sure how that happened. Only happened to me once but i have had reports of it.

**Comment by dktapps** [comment]
that's a client bug

**Comment by XxDXM-hippiexX** [comment]
d1db7b6 didnt fix it..seemed slightly better though lol

**Comment by PeratX** [comment]
Fixed
