### ISSUE TITLE
set language to chs is Invalid

### ISSUE THREAD

**Issue by zhouruixi** [iTXTech/Genisys#142]
Even I set language to chs ,but it still be English in Console.

The language setting in  pocketmine.yml is still  language: "eng",I change it to "chs",it works well

**Comment by CrayonDing** [comment]
请先关服，再更改语言。

**Comment by zhouruixi** [comment]
我是在测试genisys玩，全新无插件开服 ./php.exe Genisys*.phar ，我会无聊到没事开issue玩？

**Comment by zhouruixi** [comment]
在linux也试了，一个样！@CrayonDing
