### ISSUE TITLE
erro Ram is different on serevrs from multicraft

### ISSUE THREAD

**Issue by DavidJBrockway** [iTXTech/Genisys#1421]
#### Issue description

I have multicarft i setup a pocketmine srever 2 gb but used this har i set the momorey to 2 gb in mb it is 2000 mb and when i run status in game this happend.

09.07 14:41:12 [Server] Server thread/INFO Uptime: 14 seconds
09.07 14:41:12 [Server] Server thread/INFO Current TPS: 20 (1.68%)
09.07 14:41:12 [Server] Server thread/INFO Network upload: 309.66 kB/s
09.07 14:41:12 [Server] Server thread/INFO Network download: 8.92 kB/s
09.07 14:41:12 [Server] Server thread/INFO Thread count: 10
09.07 14:41:12 [Server] Server thread/INFO Main thread memory: 30 MB.
09.07 14:41:12 [Server] Server thread/INFO Total memory: 105 MB.
09.07 14:41:12 [Server] Server thread/INFO Total virtual memory: 1,007 MB.
09.07 14:41:12 [Server] Server thread/INFO Heap memory: 2 MB.
09.07 14:41:12 [Server] Server thread/INFO Maximum memory (system): 1,007 MB.
09.07 14:41:12 [Server] Server thread/INFO World "world": 56 chunks, 1 entities, 0

help me 
#### OS and versions

* Genisys:
* PHP:
* OS (server):
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by PeratX** [comment]
This means there is still a lot of unused ram.

**Comment by dktapps** [comment]
Maximum memory (system) = 1007 MB is the maximum memory full-stop, including unused memory. That means either a bug or your host is lying to you.
