### ISSUE TITLE
Network Notice

### ISSUE THREAD

**Issue by Prisane** [iTXTech/Genisys#1424]
#### Issue description

this error suddenly appears..

#### OS and versions

* Genisys: Last source
* PHP: 7
* OS (server): Lunix 
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

![whatsapp-image-20160710](https://cloud.githubusercontent.com/assets/13530796/16712903/412c6a06-469e-11e6-951a-2a7e8125167c.jpeg)

**Comment by robske110** [comment]
This is apparently appearing since today, i had it too (at CS but that doesn't matter)
Maybe someone figured out how to get raklib into a constant Error loop

**Comment by robske110** [comment]
BTW it hurts the system badly with overflowing the terminal message cache (RAM dies lol)
![screenshot](https://cloud.githubusercontent.com/assets/16020100/16714679/ec640268-46ca-11e6-87fc-7b55fdaea899.png)

**Comment by robske110** [comment]
It's been compressed though

**Comment by robske110** [comment]
Again: THIS MAY BE AN ATTACK

**Comment by flaxues** [comment]
Got this too... It just happens randomly

**Comment by robske110** [comment]
Wtf, why is this closed
