### ISSUE TITLE
Generated cacti and sugarcane are far too tall

### ISSUE THREAD

**Issue by starterdragon** [iTXTech/Genisys#1425]
#### Issue description
Generator Issue, once I tried to generate a new Infinite world I always get the same world, plus stackable plants (so far I only saw cactus and sugar cane) are way too high.

#### Steps to reproduce the issue
generate a new infinite world using server.properties :

pvp=on
difficulty=1
generator-settings=
level-name=forest
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off

#### OS and versions
* Genisys: Genisys_1.2dev-630.phar
* PHP: 7
* OS (server): Windows 7
* Game version: 0.15.X

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Crashdump, backtrace, memory dumps : N/A
Screenshot : (I'll try to get one and edit this later)
```

**Comment by dktapps** [comment]
If you want different worlds you need to use a different seed. As for the sugarcane/cacti, that's a bug, I've seen it myself.

**Comment by Yoyu666** [comment]
catus is tall! XD

**Comment by PeratX** [comment]
Yes, you need to use a different seed.

**Comment by dktapps** [comment]
Something else I should mention: sugarcane should only spawn on blocks directly adjacent to water, and cacti should have 1 block clearance on each side. Currently cacti can spawn right next to blocks and sugarcane can spawn diagonally adjacent to water.
