### ISSUE TITLE
more likely an enhancement

### ISSUE THREAD

**Issue by starterdragon** [iTXTech/Genisys#1426]
#### Issue description
Please Optimize these:
Enchanting using Enchantment table.
Creating Map with an Empty Map.
Piston and Sticky Piston functionality.
Brewing (I didn't actually tested brewing yet)
colored leather armors and tipped arrow feature with Cauldron

ps: I know there are more lots bug and issues that are needed to be fixed, consider this as a suggestion not a priority, thanks.
pss: I don't know if this is a duplicate issue, please delete this if that is the case.
#### Steps to reproduce the issue
N/A

#### OS and versions
* Genisys: 1.2_Dev-630
* PHP: 7
* OS (server): Win 7
* Game version: 0.15.*

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
N/A
```

**Comment by dktapps** [comment]
yes, this is a duplicate.
