### ISSUE TITLE
few minutes after joining synapse server, pause button frozen

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#1428]
when u join a server connected with synapse and play for 1 minute, the pause function of the game freezes and if you press pause or your back key, mcpe freezes. does not happen when not using synapse.

#### Steps to reproduce the issue
play on a server with synapse for 1 minute and press pause

#### OS and versions

* Genisys:genisys 1.2-#0
* PHP:7.0.8
* OS (server): Windows 10
* Game version: 0.15

#### Crashdump, backtrace, memory dumps, plugins list or other files
no error just client freezes

**Comment by PeratX** [comment]
Known issue, do not report again.

**Comment by kabluinc** [comment]
seems fixed after updating to latest build.
