### ISSUE TITLE
Feature Request: Mesa Biome

### ISSUE THREAD

**Issue by KennFatt** [iTXTech/Genisys#1431]
#### Issue description

Add Mesa Biome for DEFAULT level generator. some of my players request this. thank you.
#### Steps to reproduce the issue

nope
#### OS and versions

- Genisys: 1.2dev
- PHP: 7.0
- OS (server): -
- Game version: 0.15.2
#### Crashdump, backtrace, memory dumps, plugins list or other files

```

---
```

**Comment by Aericio** [comment]
:D (i still wont use genisys if they add mesa)

**Comment by ZedCee** [comment]
I don't really understand PHP very well, but couldn't this be achieved by stacking clayblock_color_[0-9, a-z, etc] in a manner stacked similar to the Desert gen?

_For instance:_
```
...
clayblock_color_1
clayblock_color_1
clayblock_color_1
clayblock_color_a
clayblock_color_a
clayblock_color_a
clayblock_color_2
clayblock_color_2
clayblock_color_2
clayblock_color_b
clayblock_color_3
clayblock_color_3
...
```
Where color_a could be at random a colour from a grand colour scheme, potentially being color_[1, 2 or another].  Namespace a colour scheme chooser that picks from a few schemes at random and applies it to layer gen like the hilarious desert one.

Just an idea I had in my head for an approach, maybe there's some merit to it.  I've had a few in regards to world gen; glad to see the uptake on the 'normal2' Nukkit gen.

**Comment by Aericio** [comment]
Mesa biome would be a nice feature (-_-)

**Comment by thebigsmileXD** [comment]
@nycru

**Comment by Aericio** [comment]
Readme.md
> Note: You may not copy our generator without NycuRO's permission. Other than that, everything is open-source and may be edited.
:)

**Comment by Muqsit** [comment]
@thebigsmileXD @Aericio That generator sucks and is very inaccurate.

His idea (P.S. Already coded same idea ages ago for my server, still use it):
![ca7mf7fxiaamaoq](https://cloud.githubusercontent.com/assets/15074389/16894207/7bcf6e78-4b04-11e6-8c07-a36561a946b2.jpg)

How it should actually be looking like:
![2013-11-09_06 13 02](https://cloud.githubusercontent.com/assets/15074389/16894208/84c5dd50-4b04-11e6-89f2-d11f535110e1.jpg)

**Comment by Aericio** [comment]
Its inaccurate, but its something.

**Comment by thebigsmileXD** [comment]
@Aericio Totally true.

**Comment by Muqsit** [comment]
Yeah, but you can't even call it mesa. Mesa doesn't have all the clay variants!

**Comment by thebigsmileXD** [comment]
@Muqsit uhm.. i thought it does

**Comment by thebigsmileXD** [comment]
https://www.digminecraft.com/getting_started/biome_mesa.php

**Comment by Muqsit** [comment]
@thebigsmileXD Yeah but now you know it doesn't. :#

*Feel free to use my shitty mesa biome generator*
http://forums.cosmicpe.me/MesaBiome.php

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/16894295/5265f9c8-4b52-11e6-88bd-ad4dc7fbf01c.png)

**Comment by Aericio** [comment]
I will use it with pleasure :D

**Comment by Muqsit** [comment]
http://forums.rumbencraft.me/generate.txt

**Comment by Muqsit** [comment]
But I swear, it's very inaccurate. Don't even try directly mt_rand ing the Block::get line. It will be even more crappier.
![erw](https://cloud.githubusercontent.com/assets/15074389/16894311/84d3ffae-4b07-11e6-8535-2143af4199d6.PNG)

**Comment by Aericio** [comment]
You'll probably get it near-perfect with tweaking the code a little, but its literally almost not really the same as Nycu's version

**Comment by Muqsit** [comment]
Yeah, I coded this in February according to my tweet. I'll try generating the *actual* Mesa biome when I'm free from my server's suffering.

**Comment by CubeFromSpace** [comment]
@KennanFatt I'm thinking that you need more than nine values for the generator because it might just be loading the nine that you specify. There may need to be many more layers than 9 to make a Mesa biome.

**Comment by CubeFromSpace** [comment]
Also note that you would need to add increased gold generation. And mine shafts. Unless that isn't a feature either

**Comment by thebigsmileXD** [comment]
There are not even normal things like ravines or villages or desert tempels/springs yet. I don't think minecrafts will come too fast.

**Comment by dktapps** [comment]
@thebigsmileXD Did you mean mine_carts_? I always mis-type that too :D

**Comment by thebigsmileXD** [comment]
@dktapps corrected, lol.
