### ISSUE TITLE
Slapper with a lead?

### ISSUE THREAD

**Issue by Mike4l6** [iTXTech/Genisys#1436]
#### Issue description

The issue is that when I use the Slapper plugin everytime theres a entity it puts out this code and somehow holds a lead to every entity that I spawned with slapper

Notice: Undefined property: slapper\entities\SlapperHuman::$skinName in phar://C:/Users/alex/Documents/PocketMine-MP/plugins/Slapper_v1.2.9.4.phar/src/slapper/entities/SlapperHuman.php on line 40

I have version
Slapper_v1.2.9.4
#### OS and versions

* Genisys:
* PHP:
* OS (server):
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by PeratX** [comment]
This is because of the new skin API (also in PocketMine-MP). Please contact the author of this plugin.

**Comment by jojoe77777** [comment]
Update the plugin, it was fixed a while ago.
