### ISSUE TITLE
Map that worked on 0.14.3 doesn't work on 0.15.0

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#1439]
I tried install my old map, and faced with the problem of https://github.com/iTXTech/Genisys/issues/1423

#### Steps to reproduce the issue
1)Install my map https://yadi.sk/d/2iLcKQCYtEccT
2)Go into maps territory

#### OS and versions

* Genisys: #630
* PHP: 7
* OS (server): Windows server 2012 R2
* Game version: 0.15.2.1

**Comment by dktapps** [comment]
#1206

**Comment by Shamil0402** [comment]
But it working on 0.14.3
