### ISSUE TITLE
Chunks crash the client

### ISSUE THREAD

**Issue by Skull3x** [iTXTech/Genisys#1441]
#### Issue description
I have recently downloaded a few maps that I wanted to use and when I teleported to the level and my chunks loaded by a certian distance that my client on both Windows 10 and PE would crash some how. 

#### Steps to reproduce the issue
I'm sure some of you have experienced this before by taking a specific level and warping to it and just crashing as soon as some chunks load. I have tried deleting all unknown blocks in MCPE using my PC client but I failed in resolving this issue. Any other ideas?

#### OS and versions

* Genisys:
* PHP: latest
* OS (server):  Windows 10 Pro

**Comment by ZedCee** [comment]
It's  erroneous and unknown blocks.
**The issue is client side** and until there's tools to fix it, we wait for Mojang.
See the many responses here for this exact issue:
https://github.com/PocketMine/PocketMine-MP/issues/4216

**Comment by Skull3x** [comment]
Thank You

**Comment by dktapps** [comment]
#1206
