### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#145]
This error happens when running build 24 or above build 23 is working

**Comment by flaxues** [comment]
I think it has to do something with this commit:
https://github.com/iTXTech/Genisys/commit/e7c29c12bf8e825ed529e4439035cf0557402b6f

**Comment by MrDoni98** [comment]
@flaxues yes.

**Comment by mixailenko5** [comment]
@flaxues PeratX canselled this code

**Comment by PeratX** [comment]
But I do not know why ?

**Comment by mixailenko5** [comment]
PeratX, i too. But we knows how to fix it. And if you want test core on linux use koding.com . Tehre are i was fixing segmentation
