### ISSUE TITLE
Redstone Block is not solid

### ISSUE THREAD

**Issue by diamond-gold** [iTXTech/Genisys#1454]
#### Issue description
TNT fall through Redstone Block & players 'dragged' down when walking on it (detected as flying)

#### Steps to reproduce the issue
Put redstone block >5 blocks above ground and walk on it/light tnt on it

#### OS and versions

* Genisys: Latest commit 6ee70ae
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Seems you're correct. I have reproduced this.
