### ISSUE TITLE
Biome Colour Blending Breaks on imported worlds

### ISSUE THREAD

**Issue by ZedCee** [iTXTech/Genisys#1455]
#### Issue description

_Imported worlds:_
Biome colour mapping on imported maps does not blend on the biome grass, leaves, or water colours leaving square patches of colour.  

_Worlds generated by a server:_
This occurred once in a past version with the default generator on a now deleted map, but I cannot reproduce with the present version.  However leaf colours do not change at all (though this may not be implemented).
#### Steps to reproduce the issue
- Import a map generated using a genuine MC generator or derivative of.
- Explore.
#### OS and versions
- Genisys:  1.2dev-90c31fc
- PHP: 7.0.6
- Server OS: Linux
- Client OS: iOS
- Game version: 0.15.2

![img_8305](https://cloud.githubusercontent.com/assets/20411465/16831775/c95c15d8-4974-11e6-95f1-1b18551f363d.PNG)

**Comment by PeratX** [comment]
Use /biome command to reset biome.

**Comment by ZedCee** [comment]
/biome does not properly address the issue; biomes appear to register fine.
Solid coloured grass is one driving point to imported maps.  Redrawing kilometres of map is not ideal and comes with no Perlin noise.  Is this issue client-side, or related to temperature and weather management?

**Comment by dktapps** [comment]
PC maps aren't fully supported. This is just one issue that happens as a result of using a PC world. Others include leashed mobs which burn when they spawn (mobs generated with the map).

**Comment by ZedCee** [comment]
Well it's clear that they aren't fully supported.  It would be nice, however, to know how exactly this error occurs in the grass rendering and what makes it _impossible_ to fix.
As for mobs, that's obviously related to the differing NBT string lengths and handling on PC vs PE.

**Comment by dktapps** [comment]
My money is on this is/was an Anvil world, right?
