### ISSUE TITLE
Glowing Obsidian does not glow until local lighting is updated

### ISSUE THREAD

**Issue by ZedCee** [iTXTech/Genisys#1456]
#### Issue description
Glowing Obsidian only glows after a light source is added/or broken nearby.  A ominous glow emits around the blocks, but produces no light, nor do the blocks glow.

#### Steps to reproduce the issue

- Place Glowing Obsidian in a dark place.
- Place torch, watch your Obsidian glow.
- Remove torch, it will glow for you and any players that were nearby when activated until death or teleport.

#### OS and versions
* Genisys: 1.2dev-90c31fc
* PHP: 7.0.6
* Server OS: Linux
* Client OS: iOS and Android
* Game version: 0.15.2

![img_8308](https://cloud.githubusercontent.com/assets/20411465/16833006/2f4482b2-497b-11e6-9432-8239f4458a27.PNG)

![img_8309](https://cloud.githubusercontent.com/assets/20411465/16833058/827c4302-497b-11e6-9d9a-fab19b4effb5.PNG)

**Comment by jerryzooyoyo** [comment]
So does the red stone lamp.
If you use a world editing system to add a glowing red stone lamp, same problem above.

**Comment by PeratX** [comment]
That's because they do not calculate block light.

**Comment by ZedCee** [comment]
It's likely relevant to note that "light-updates" are true

@PeratX Thanks.  It was rather late here.
