### ISSUE TITLE
this keeps on spamming my console and crashes the server .

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#1460]
Deprecated: Hotbar linkage should never be changed unless requested by the client in phar:///jar/versions/Genisys/Genisys_1.2dev-2f4c8db.phar/src/pocketmine/inventory/PlayerInventory.php on line 73

i didn't change anything this just popped up on the console =/ . any ideas ?

**Comment by mote166** [comment]
it also says this " no windo open ; dropped an item ?" i didn't change anything the last thing i did is added mcg76 block hunt plugin

**Comment by gaoyichuan** [comment]
Plugin issue, the plugin developer used a deprecated method. Contact him

**Comment by mote166** [comment]
ITS MCG76 he never responds ! tell me a fix plz

**Comment by dktapps** [comment]
DO NOT USE THE WIN10 BRANCH BUILDS UNLESS YOU ARE TESTING DEVELOPMENTS. Make sure you are using a build from the master branch.
