### ISSUE TITLE
Diamond sword bug

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1461]
<!--

15.07 02:30:57 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:57 [Server] INFO Transfer for other inventory type
15.07 02:30:57 [Server] INFO Added a transaction concerning slot number 1
15.07 02:30:57 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:57 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO Transferring items in this inventory
15.07 02:30:58 [Server] INFO Added a transaction concerning slot number 0
15.07 02:30:58 [Server] INFO Received MobEquipmentPacket
15.07 02:30:58 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#23409 (8) {
15.07 02:30:58 [Server] INFO ["eid"]=>
15.07 02:30:58 [Server] INFO int(0)
15.07 02:30:58 [Server] INFO ["item"]=>
15.07 02:30:58 [Server] INFO string(23) "Item Sandstone (24:0)x1"
15.07 02:30:58 [Server] INFO ["slot"]=>
15.07 02:30:58 [Server] INFO int(9)
15.07 02:30:58 [Server] INFO ["selectedSlot"]=>
15.07 02:30:58 [Server] INFO int(0)
15.07 02:30:58 [Server] INFO ["isEncoded"]=>
15.07 02:30:58 [Server] INFO bool(false)
15.07 02:30:58 [Server] INFO ["channel"]=>
15.07 02:30:58 [Server] INFO int(0)
15.07 02:30:58 [Server] INFO ["offset"]=>
15.07 02:30:58 [Server] INFO int(18)
15.07 02:30:58 [Server] INFO ["buffer"]=>
15.07 02:30:58 [Server] INFO string(36) "1b0000000000000000001801000000000900"
15.07 02:30:58 [Server] INFO }
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Multicraft] Skipped 84 lines due to rate limit (30/s)
15.07 02:30:58 [Server] INFO Transfer for other inventory type
15.07 02:30:58 [Server] INFO Added a transaction concerning slot number 2
15.07 02:30:58 [Server] INFO Transferring items in this inventory
15.07 02:30:58 [Server] INFO Added a transaction concerning slot number 1
15.07 02:30:58 [Server] INFO Received MobEquipmentPacket
15.07 02:30:58 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#64908 (8) {
15.07 02:30:58 [Server] INFO ["eid"]=>
15.07 02:30:58 [Server] INFO int(0)
15.07 02:30:58 [Server] INFO ["item"]=>
15.07 02:30:58 [Server] INFO string(33) "Item Diamond Chestplate (311:0)x1"
15.07 02:30:58 [Server] INFO ["slot"]=>
15.07 02:30:58 [Server] INFO int(10)
15.07 02:30:58 [Server] INFO ["selectedSlot"]=>
15.07 02:30:58 [Server] INFO int(1)
15.07 02:30:58 [Server] INFO ["isEncoded"]=>
15.07 02:30:58 [Server] INFO bool(false)
15.07 02:30:58 [Server] INFO ["channel"]=>
15.07 02:30:58 [Server] INFO int(0)
15.07 02:30:58 [Server] INFO ["offset"]=>
15.07 02:30:58 [Server] INFO int(18)
15.07 02:30:58 [Server] INFO ["buffer"]=>
15.07 02:30:58 [Server] INFO string(36) "1b0000000000000000013701000000000a01"
15.07 02:30:58 [Server] INFO }
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:58 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:59 [Multicraft] Skipped 28 lines due to rate limit (30/s)
15.07 02:30:59 [Server] INFO Transferring items in this inventory
15.07 02:30:59 [Server] INFO ignoring slot change
15.07 02:30:59 [Server] INFO Received MobEquipmentPacket
15.07 02:30:59 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#33375 (8) {
15.07 02:30:59 [Server] INFO ["eid"]=>
15.07 02:30:59 [Server] INFO int(0)
15.07 02:30:59 [Server] INFO ["item"]=>
15.07 02:30:59 [Server] INFO string(19) "Item Stone (1:0)x38"
15.07 02:30:59 [Server] INFO ["slot"]=>
15.07 02:30:59 [Server] INFO int(14)
15.07 02:30:59 [Server] INFO ["selectedSlot"]=>
15.07 02:30:59 [Server] INFO int(5)
15.07 02:30:59 [Server] INFO ["isEncoded"]=>
15.07 02:30:59 [Server] INFO bool(false)
15.07 02:30:59 [Server] INFO ["channel"]=>
15.07 02:30:59 [Server] INFO int(0)
15.07 02:30:59 [Server] INFO ["offset"]=>
15.07 02:30:59 [Server] INFO int(18)
15.07 02:30:59 [Server] INFO ["buffer"]=>
15.07 02:30:59 [Server] INFO string(36) "1b0000000000000000000126000000000e05"
15.07 02:30:59 [Server] INFO }
15.07 02:30:59 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:59 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:59 [Server] Server thread/INFO DrGamerSA joined the game
15.07 02:30:59 [Server] INFO last update time less than 10 ticks ago
15.07 02:30:59 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:00 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:00 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:00 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:00 [Server] INFO no window open; dropped an item?
15.07 02:31:00 [Multicraft] Skipped 38 lines due to rate limit (30/s)
15.07 02:31:00 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:00 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:00 [Server] INFO Received MobEquipmentPacket
15.07 02:31:00 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#36198 (8) {
15.07 02:31:00 [Server] INFO ["eid"]=>
15.07 02:31:00 [Server] INFO int(0)
15.07 02:31:00 [Server] INFO ["item"]=>
15.07 02:31:00 [Server] INFO string(18) "Item Dirt (3:0)x64"
15.07 02:31:00 [Server] INFO ["slot"]=>
15.07 02:31:00 [Server] INFO int(14)
15.07 02:31:00 [Server] INFO ["selectedSlot"]=>
15.07 02:31:00 [Server] INFO int(2)
15.07 02:31:00 [Server] INFO ["isEncoded"]=>
15.07 02:31:00 [Server] INFO bool(false)
15.07 02:31:00 [Server] INFO ["channel"]=>
15.07 02:31:00 [Server] INFO int(0)
15.07 02:31:00 [Server] INFO ["offset"]=>
15.07 02:31:00 [Server] INFO int(18)
15.07 02:31:00 [Server] INFO ["buffer"]=>
15.07 02:31:00 [Server] INFO string(36) "1b0000000000000000000340000000000e02"
15.07 02:31:00 [Server] INFO }
15.07 02:31:00 [Server] INFO Transferring items in this inventory
15.07 02:31:00 [Server] INFO ignoring slot change
15.07 02:31:00 [Server] INFO Received MobEquipmentPacket
15.07 02:31:00 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#44742 (8) {
15.07 02:31:00 [Server] INFO ["eid"]=>
15.07 02:31:00 [Server] INFO int(0)
15.07 02:31:00 [Server] INFO ["item"]=>
15.07 02:31:00 [Server] INFO string(19) "Item Stone (1:0)x37"
15.07 02:31:00 [Server] INFO ["slot"]=>
15.07 02:31:01 [Multicraft] Skipped 140 lines due to rate limit (30/s)
15.07 02:31:01 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:01 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:01 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:01 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO out transaction executing
15.07 02:31:02 [Server] INFO in transaction executing
15.07 02:31:02 [Server] INFO Transferring items in this inventory
15.07 02:31:02 [Server] INFO ignoring slot change
15.07 02:31:02 [Server] INFO Received MobEquipmentPacket
15.07 02:31:02 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#29954 (8) {
15.07 02:31:02 [Server] INFO ["eid"]=>
15.07 02:31:02 [Server] INFO int(0)
15.07 02:31:02 [Server] INFO ["item"]=>
15.07 02:31:02 [Server] INFO string(19) "Item Stone (1:0)x35"
15.07 02:31:02 [Server] INFO ["slot"]=>
15.07 02:31:02 [Server] INFO int(14)
15.07 02:31:02 [Server] INFO ["selectedSlot"]=>
15.07 02:31:02 [Server] INFO int(5)
15.07 02:31:02 [Server] INFO ["isEncoded"]=>
15.07 02:31:02 [Server] INFO bool(false)
15.07 02:31:02 [Server] INFO ["channel"]=>
15.07 02:31:02 [Server] INFO int(0)
15.07 02:31:02 [Server] INFO ["offset"]=>
15.07 02:31:02 [Server] INFO int(18)
15.07 02:31:02 [Server] INFO ["buffer"]=>
15.07 02:31:02 [Server] INFO string(36) "1b0000000000000000000123000000000e05"
15.07 02:31:02 [Multicraft] Skipped 34 lines due to rate limit (30/s)
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:02 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:03 [Server] INFO out transaction executing
15.07 02:31:03 [Server] INFO Slot count changed by 1
15.07 02:31:03 [Server] INFO in transaction executing
15.07 02:31:03 [Server] INFO Received MobEquipmentPacket
15.07 02:31:03 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#52411 (8) {
15.07 02:31:03 [Server] INFO ["eid"]=>
15.07 02:31:03 [Server] INFO int(0)
15.07 02:31:03 [Server] INFO ["item"]=>
15.07 02:31:03 [Server] INFO string(28) "Item Diamond Sword (276:0)x1"
15.07 02:31:03 [Server] INFO ["slot"]=>
15.07 02:31:03 [Server] INFO int(9)
15.07 02:31:03 [Server] INFO ["selectedSlot"]=>
15.07 02:31:03 [Server] INFO int(0)
15.07 02:31:03 [Server] INFO ["isEncoded"]=>
15.07 02:31:03 [Server] INFO bool(false)
15.07 02:31:03 [Server] INFO ["channel"]=>
15.07 02:31:03 [Server] INFO int(0)
15.07 02:31:03 [Server] INFO ["offset"]=>
15.07 02:31:03 [Server] INFO int(18)
15.07 02:31:03 [Server] INFO ["buffer"]=>
15.07 02:31:03 [Server] INFO string(36) "1b0000000000000000011401000000000900"
15.07 02:31:03 [Server] INFO }
15.07 02:31:03 [Server] INFO Transferring items in this inventory
15.07 02:31:03 [Server] INFO ignoring slot change
15.07 02:31:03 [Server] INFO Received MobEquipmentPacket
15.07 02:31:03 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#24388 (8) {
15.07 02:31:03 [Server] INFO ["eid"]=>
15.07 02:31:03 [Multicraft] Skipped 142 lines due to rate limit (30/s)
15.07 02:31:03 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:03 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:03 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:03 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:04 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:04 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:04 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:04 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:04 [Server] INFO Transferring items in this inventory
15.07 02:31:04 [Server] INFO ignoring slot change
15.07 02:31:04 [Server] INFO Transferring items in this inventory
15.07 02:31:04 [Server] INFO ignoring slot change
15.07 02:31:04 [Server] INFO no window open; dropped an item?
15.07 02:31:04 [Server] INFO Received MobEquipmentPacket
15.07 02:31:04 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#46045 (8) {
15.07 02:31:04 [Server] INFO ["eid"]=>
15.07 02:31:04 [Server] INFO int(0)
15.07 02:31:04 [Server] INFO ["item"]=>
15.07 02:31:04 [Server] INFO string(28) "Item Diamond Sword (276:0)x1"
15.07 02:31:04 [Server] INFO ["slot"]=>
15.07 02:31:04 [Server] INFO int(10)
15.07 02:31:04 [Server] INFO ["selectedSlot"]=>
15.07 02:31:04 [Server] INFO int(1)
15.07 02:31:04 [Server] INFO ["isEncoded"]=>
15.07 02:31:04 [Server] INFO bool(false)
15.07 02:31:04 [Server] INFO ["channel"]=>
15.07 02:31:04 [Server] INFO int(0)
15.07 02:31:04 [Server] INFO ["offset"]=>
15.07 02:31:04 [Server] INFO int(18)
15.07 02:31:04 [Server] INFO ["buffer"]=>
15.07 02:31:04 [Multicraft] Skipped 92 lines due to rate limit (30/s)
15.07 02:31:04 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:04 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:05 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:05 [Server] INFO Transferring items in this inventory
15.07 02:31:05 [Server] INFO ignoring slot change
15.07 02:31:05 [Server] INFO Received MobEquipmentPacket
15.07 02:31:05 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#62454 (8) {
15.07 02:31:05 [Server] INFO ["eid"]=>
15.07 02:31:05 [Server] INFO int(0)
15.07 02:31:05 [Server] INFO ["item"]=>
15.07 02:31:05 [Server] INFO string(29) "Item Oak Wood Planks (5:0)x50"
15.07 02:31:05 [Server] INFO ["slot"]=>
15.07 02:31:05 [Server] INFO int(15)
15.07 02:31:05 [Server] INFO ["selectedSlot"]=>
15.07 02:31:05 [Server] INFO int(6)
15.07 02:31:05 [Server] INFO ["isEncoded"]=>
15.07 02:31:05 [Server] INFO bool(false)
15.07 02:31:05 [Server] INFO ["channel"]=>
15.07 02:31:05 [Server] INFO int(0)
15.07 02:31:05 [Server] INFO ["offset"]=>
15.07 02:31:05 [Server] INFO int(18)
15.07 02:31:05 [Server] INFO ["buffer"]=>
15.07 02:31:05 [Server] INFO string(36) "1b0000000000000000000532000000000f06"
15.07 02:31:05 [Server] INFO }
15.07 02:31:05 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:05 [Server] INFO Slot count changed by 10
15.07 02:31:05 [Server] INFO in transaction failed
15.07 02:31:05 [Server] INFO Slot count changed by 1
15.07 02:31:05 [Server] INFO in transaction failed
15.07 02:31:05 [Server] INFO Slot count changed by 10
15.07 02:31:05 [Multicraft] Skipped 140 lines due to rate limit (30/s)
15.07 02:31:05 [Server] INFO Transferring items in this inventory
15.07 02:31:05 [Server] INFO ignoring slot change
15.07 02:31:05 [Server] INFO Received MobEquipmentPacket
15.07 02:31:05 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#38478 (8) {
15.07 02:31:05 [Server] INFO ["eid"]=>
15.07 02:31:05 [Server] INFO int(0)
15.07 02:31:05 [Server] INFO ["item"]=>
15.07 02:31:05 [Server] INFO string(19) "Item Stone (1:0)x31"
15.07 02:31:05 [Server] INFO ["slot"]=>
15.07 02:31:05 [Server] INFO int(14)
15.07 02:31:05 [Server] INFO ["selectedSlot"]=>
15.07 02:31:05 [Server] INFO int(5)
15.07 02:31:05 [Server] INFO ["isEncoded"]=>
15.07 02:31:05 [Server] INFO bool(false)
15.07 02:31:05 [Server] INFO ["channel"]=>
15.07 02:31:05 [Server] INFO int(0)
15.07 02:31:05 [Server] INFO ["offset"]=>
15.07 02:31:05 [Server] INFO int(18)
15.07 02:31:05 [Server] INFO ["buffer"]=>
15.07 02:31:05 [Server] INFO string(36) "1b000000000000000000011f000000000e05"
15.07 02:31:05 [Server] INFO }
15.07 02:31:05 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:06 [Server] INFO Transferring items in this inventory
15.07 02:31:06 [Server] INFO ignoring slot change
15.07 02:31:06 [Server] INFO Received MobEquipmentPacket
15.07 02:31:06 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#33948 (8) {
15.07 02:31:06 [Server] INFO ["eid"]=>
15.07 02:31:06 [Server] INFO int(0)
15.07 02:31:06 [Server] INFO ["item"]=>
15.07 02:31:06 [Server] INFO string(29) "Item Oak Wood Planks (5:0)x49"
15.07 02:31:06 [Multicraft] Skipped 262 lines due to rate limit (30/s)
15.07 02:31:06 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO Received MobEquipmentPacket
15.07 02:31:07 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#65492 (8) {
15.07 02:31:07 [Server] INFO ["eid"]=>
15.07 02:31:07 [Server] INFO int(0)
15.07 02:31:07 [Server] INFO ["item"]=>
15.07 02:31:07 [Server] INFO string(23) "Item Red Wool (35:14)x1"
15.07 02:31:07 [Server] INFO ["slot"]=>
15.07 02:31:07 [Server] INFO int(13)
15.07 02:31:07 [Server] INFO ["selectedSlot"]=>
15.07 02:31:07 [Server] INFO int(4)
15.07 02:31:07 [Server] INFO ["isEncoded"]=>
15.07 02:31:07 [Server] INFO bool(false)
15.07 02:31:07 [Server] INFO ["channel"]=>
15.07 02:31:07 [Server] INFO int(0)
15.07 02:31:07 [Server] INFO ["offset"]=>
15.07 02:31:07 [Server] INFO int(18)
15.07 02:31:07 [Server] INFO ["buffer"]=>
15.07 02:31:07 [Server] INFO string(36) "1b0000000000000000002301000e00000d04"
15.07 02:31:07 [Server] INFO }
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:07 [Server] INFO Transferring items in this inventory
15.07 02:31:07 [Server] INFO ignoring slot change
15.07 02:31:07 [Server] INFO Received MobEquipmentPacket
15.07 02:31:07 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#65335 (8) {
15.07 02:31:07 [Multicraft] Skipped 177 lines due to rate limit (30/s)
15.07 02:31:07 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:08 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:08 [Server] INFO Transferring items in this inventory
15.07 02:31:08 [Server] INFO ignoring slot change
15.07 02:31:08 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:08 [Server] INFO Transferring items in this inventory
15.07 02:31:08 [Server] INFO ignoring slot change
15.07 02:31:08 [Server] INFO Received MobEquipmentPacket
15.07 02:31:08 [Server] INFO object(pocketmine\network\protocol\MobEquipmentPacket)#29567 (8) {
15.07 02:31:08 [Server] INFO ["eid"]=>
15.07 02:31:08 [Server] INFO int(0)
15.07 02:31:08 [Server] INFO ["item"]=>
15.07 02:31:08 [Server] INFO string(29) "Item Oak Wood Planks (5:0)x47"
15.07 02:31:08 [Server] INFO ["slot"]=>
15.07 02:31:08 [Server] INFO int(15)
15.07 02:31:08 [Server] INFO ["selectedSlot"]=>
15.07 02:31:08 [Server] INFO int(6)
15.07 02:31:08 [Server] INFO ["isEncoded"]=>
15.07 02:31:08 [Server] INFO bool(false)
15.07 02:31:08 [Server] INFO ["channel"]=>
15.07 02:31:08 [Server] INFO int(0)
15.07 02:31:08 [Server] INFO ["offset"]=>
15.07 02:31:08 [Server] INFO int(18)
15.07 02:31:08 [Server] INFO ["buffer"]=>
15.07 02:31:08 [Server] INFO string(36) "1b000000000000000000052f000000000f06"
15.07 02:31:08 [Server] INFO }
15.07 02:31:08 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:08 [Server] INFO Transferring items in this inventory
15.07 02:31:08 [Server] INFO ignoring slot change
15.07 02:31:08 [Server] INFO Received MobEquipmentPacket
15.07 02:31:08 [Multicraft] Skipped 155 lines due to rate limit (30/s)
15.07 02:31:08 [Server] INFO last update time less than 10 ticks ago
15.07 02:31:09 [Server] INFO out transaction executing
15.07 02:31:09 [Server] INFO in transaction failed
15.07 02:31:09 [Server] INFO Transferring items in this inventory
15.07 02:31:09 [Server] INFO Slot count changed by -1
15.07 02:31:09 [Server] INFO Added a transaction concerning slot number 2

**Comment by gaoyichuan** [comment]
One of your plugins has a var_dump() inside its code. Find it

**Comment by MCPEPluginer16** [comment]
Need delete the plugin or?

**Comment by dktapps** [comment]
@gaoyichuan actually it's because he's using the Win10 branch. @MCPEPluginer16 do not use the Win10 branch unless you are testing changes.

**Comment by gaoyichuan** [comment]
@dktapps Oh, I see. So the var_dump is added by you?

**Comment by dktapps** [comment]
@gaoyichuan yes
