### ISSUE TITLE
MCPE Crashed

### ISSUE THREAD

**Issue by DayBrYT** [iTXTech/Genisys#1462]
The PocketMine Modified No Supports maps installed
You Join In The Map And Crashe Your MCPE
 nobody can put maps of mini-games or Spawn
 the pc and android
PHP7
0.15.X
Android
PC
...

**Comment by ishitatsuyuki** [comment]
You open an issue not following the guideline and get banned.

**Comment by dktapps** [comment]
#1206 . Try searching existing issues before opening a new one
