### ISSUE TITLE
Splash Potion of Swiftness gives you insane speed

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1463]
My friend and I were messing with speed potions throwing them around and we suddenly got a huge speed boost
#### Steps to reproduce the issue

Grab a speed 2 potion and you throw it

#### OS and versions

* Genisys: 1.2dev
* PHP: 7.0.4
* Server OS: Ubuntu 64 bit
* Game version:  0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Confirmed, only applies to splash one.

**Comment by TheAppleGamer** [comment]
Yep! Sorry I should have been more specific on which potions lol

**Comment by CubeFromSpace** [comment]
Check this line of code in src/pocketmine/entity/effect:

if($this->id === Effect::SPEED){
				$attr = $entity->getAttributeMap()->getAttribute(Attribute::MOVEMENT_SPEED);
				if($modify and $oldEffect !== null){
					$speed = $attr->getValue() / (1 + 0.2 * $oldEffect->getAmplifier());
				}else{
					$speed = $attr->getValue();
				}
				$speed *= (1 + 0.2 * $this->amplifier);
				$attr->setValue($speed);

**Comment by CubeFromSpace** [comment]
I'm not as good at php as all of you, but I know syntax for tons of languages. If I'm wrong, blame me entirely.

**Comment by TheAppleGamer** [comment]
Doesn't work, I tried.
