### ISSUE TITLE
division by zero warning ? ( version : b5cd177 )

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#1464]
Warning: Division by zero in phar:///jar/versions/Genisys/Genisys_git-b5cd177.phar/src/pocketmine/utils/VectorIterator.php on line 122 15.07 20:05:12 [Server] INFO Warning: Division by zero in phar:///jar/versions/Genisys/Genisys_git-b5cd177.phar/src/pocketmine/utils/VectorIterator.php on line 127 15.07 20:05:12 [Server] INFO Warning: Division by zero in phar:///jar/versions/Genisys/Genisys_git-b5cd177.phar/src/pocketmine/utils/VectorIterator.php on line 129 15.07 20:05:12 [Server] INFO Warning: Division by zero in phar:///jar/versions/Genisys/Genisys_git-b5cd177.phar/src/pocketmine/utils/VectorIterator.php on line 174

**Comment by dktapps** [comment]
Outdated build and you ignored the template. Closing.
