### ISSUE TITLE
I know how ForceOP works

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1467]
Warning: file_put_contents(/root/1/root/ops.txt): failed to open stream: Permission denied in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/scheduler/FileWriteTask.php on line 38

Warning: file_put_contents(/root/1/root/ops.txt): failed to open stream: Permission denied in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208                                                                                
Warning: file_put_contents(/root/1/root/ops.txt): failed to open stream: Permission denied in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/scheduler/FileWriteTask.php on line 38

Warning: file_put_contents(/root/1/root/ops.txt): failed to open stream: Permission denied in phar:///root/1/root/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208

OPHack attack !! I blocked Ops.txt to get these errors from hackers

**Comment by dog194** [comment]
close for not following the temple. If you still spawn sth like this,

**Comment by TDMidkwhatisxd** [comment]
-_- , as expected for genisys , nvm

**Comment by gaoyichuan** [comment]
That's interesting. Can you provide the thing for us?

**Comment by TDMidkwhatisxd** [comment]
My servers , was constantly attacked by ForceOP !! I just blocked Ops.txt weeks ago, and today got this error!! I did nothing in console, just checking status , then i saw many of this error , i have command tracker plugin , so nobody used any command !!!
