### ISSUE TITLE
https://github.com/iTXTech/Genisys/commit/95bc1bef38afed777c7302254bffc76e73b75d44

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#1469]
"copying is not allowed" Sure it is. Look at your license ;)

**Comment by ishitatsuyuki** [comment]
Sure, we have the exception:

```
License

Most of the code in this repository was written by the PocketMine team and is licensed under GPLv3. Some AI is proprietary, copying is prohibited.
```

See README.

**Comment by thebigsmileXD** [comment]
But the Readme doesn't matter, in judging the License does.

**Comment by SkygridRex** [comment]
@ishitatsuyuki Dan cry like a kid. Have you see that
https://github.com/ClearSkyTeam/ClearSky
Look readme

**Comment by caspervanneck** [comment]
wtf @SkygridRex .........

**Comment by thebigsmileXD** [comment]
@SkygridRex as long as your language doesn't improve i see nothing.
