### ISSUE TITLE
server shutting down and a api warning whenever someone joins 

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#1473]
Server] Server thread/WARNING API Server Returned Error Message: Monthly Request Limit Reached when mote tried to connect 16.07 21:49:30 [Server] Server thread/CRITICAL Shutting down server to prevent blacklisting on API Database

**Comment by dktapps** [comment]
Closing for not following template. Again. Will you learn?

**Comment by mote166** [comment]
sorry :3
