### ISSUE TITLE
Tipped arrows (suggestion) (missing feature)

### ISSUE THREAD

**Issue by CubeFromSpace** [iTXTech/Genisys#1474]
#### Issue description

I saw nothing for tipped arrows in cauldron.php or arrow.php or src/Pocketmine/block anywhere.
#### Steps to reproduce the issue

Look at the code
#### OS and versions

* Genisys: Latest build (in repo)
* PHP: php7
* Server OS: W10
* Game version: 15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Look under enisys/src/pocketmine/entity/Projectile.php
Arrows with potions.  They were recently added.

**Comment by CubeFromSpace** [comment]
Ok. Sorry.
