### ISSUE TITLE
Players "hack" servers

### ISSUE THREAD

**Issue by FaanMaario** [iTXTech/Genisys#1475]
#### Issue description

Players can "DDOS" servers usings some mods and can restart servers. 
I don't know if it can be blocked by the server software to prevent from modded players.
#### Steps to reproduce the issue

use some apps like Ip tools pro or packets generator
#### OS and versions

* Genisys: Genisys 1.2dev-b6b3aeb8
* PHP: php7
* Server OS: GNU/Linux
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Not enough information. There's no point telling us unless you're going to tell us _how_ so it can be fixed. Do stop wasting our time.

**Comment by flaxues** [comment]
Wait you want to report this a "hack" but won't tell us the app name they use? Whats that kind of logic?? lolz

**Comment by dktapps** [comment]
@flaxues exactly

**Comment by FaanMaario** [comment]
@flaxues I don't want to tell here, because some people can use it for bad things.

But, nevermind. There's the list:
- Ip tools pro
- packets generator

**Comment by dterweij** [comment]
Thats teh thing,, nobody can protect against DDOS attacks. It is not a hack but something everyone can do if you own a lot of hacked servers to start something :)
You could also call the simple tool everyone have "PING" dangerous. Start a ping from 1 mil systems to one destination and you have a DDOS aswell.
You can only protect your servers from freezing by a DDOS attack to shutdown your server for a while or turn off the UTP port on the switch.

I suggest genisys dev's, don't do anything. Close the issue. Whatever you implement, is does not help protecting a DDOS attack :)
