### ISSUE TITLE
/give command and kits lag 

### ISSUE THREAD

**Issue by biswarm22** [iTXTech/Genisys#1476]
#### Issue description

When you do /kit /give it lags to give you the item. The server is not laggy and works perfectly. This happened after updating to the new genisys build
#### Steps to reproduce the issue

Do /give and it will lag to give you item

#### OS and versions

* Genisys: 612d644ce9d9d16775867c1fefbf8c30ab5176e2
* PHP: 7
* Server OS: Windows 10
* Game version: Pocketedition 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

None
```
```

**Comment by biswarm22** [comment]
Test: go to my McPe server 
IP: mcbluicraft.tk
Port: 19132
Create account
Do /kit starter
And nothing show up in inventory for 5 min
After 5 min it show in inventory

**Comment by CubeFromSpace** [comment]
Is /kit a plugin?

**Comment by CubeFromSpace** [comment]
This issue doesnt apply to Genysis or Pocketmine's API and this should be closed. No offense.

**Comment by PeratX** [comment]
This is a plugin issue.

**Comment by biswarm22** [comment]
@PeratX sorry about that I looked at previous issues and found this one #1470 , this is exactly what happens with me. Sorry
