### ISSUE TITLE
Relogging on PC worlds puts players back at spawn

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1477]
#### Issue description

A client who is having troubles with his server came and talked to me about whenever his players relog they are back at spawn, and it only happens on PC worlds. We made sure it worked on regular pocketmine worlds and no issue, and it is not any plugins.
#### Steps to reproduce the issue

1.) Add a pc world to your server (I can provide you a nice little world https://drive.google.com/file/d/0B_HvyppFc-DxdW92dkxmMVBjNzA/view?usp=sharing)
2.) Join the server and run to a different spot and then relog.
3.) There is the issue!
#### OS and versions

* Genisys: 1.2dev
* PHP: 7.0.4
* Server OS: Linux
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by PeratX** [comment]
Folder name must same as map name

**Comment by TheAppleGamer** [comment]
It is, it just always tps everyone back to the spawnpoint after relogging
