### ISSUE TITLE
Strange Hotbar Bug

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1478]
#### Issue description

When you press on an item in creative, it will also switch other items in different slots of your hotbar to that item. 

#### Steps to reproduce the issue

Go in Creative and open up your inventory
Tap on blocks/items

#### OS and versions

* Genisys: 1.2dev-649 "Kyrios"
* PHP: 7
* Server OS: Unknown (Hosted by NetherBox)
* Game version: MCPE 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

Video of bug: https://youtu.be/OkuJlgTmY9c
```
Server is hosted by NetherBox, I cannot update Genisys versions myself. 
```

**Comment by ishitatsuyuki** [comment]
Strange... why you have 9 slots!?

**Comment by ABAxStorm** [comment]
@ishitatsuyuki idk

**Comment by ishitatsuyuki** [comment]
Well, what's your platform(iOS or Android)? Currently we only know that most device got 8 slots, and it's likely to be hardcoded in the server.

**Comment by ZedCee** [comment]
This is a widely known issue with more fixes on the horizon.
There should be a release including Win10 support, along with a redesign of the hotbar handling.

@ishitatsuyuki Seems it's a available resolution thing. My girlfriends got it too for her android.  I can get more or less with my gui size.

**Comment by ishitatsuyuki** [comment]
Seems it changed at 0.15.2 or some point. It was fixed at 0.15.0.

**Comment by ABAxStorm** [comment]
@ishitatsuyuki Running on Android 5.1.

**Comment by ABAxStorm** [comment]
@ZedCee Thanks!

**Comment by ZedCee** [comment]
@ishitatsuyuki Just double checked, I have 9 as well on iOS. That last slot actually ends up a bit problematic at times and sometimes copies the items from the first slot or vice versa.
Changing res does nothing about it now I guess, used to change it to six.

**Comment by dktapps** [comment]
It varies from device to device. My Nox emulator has 9 slots. And the hotbar is ludicrously buggy right now anyway. This and various other issues will be eliminated in the upcoming Win10 update.
