### ISSUE TITLE
Strength effect multiplies attack speed

### ISSUE THREAD

**Issue by kaitododoyt** [iTXTech/Genisys#1484]
#### Issue description
Insane Atack Speed cause of Strength effect, Players say "Hack"

#### Steps to reproduce the issue
Give effect 5 to player and then it have a High atack speed

#### OS and versions
* Genisys: Genisys git-1f0d0e9 "Kyrios"
* PHP: 7
* Server OS: Windows
* Game version: Android

**Comment by ZedCee** [comment]
1f0d0e9 is an unsupported branch and can have bugs not present in in the master branch.
However tested on 0909f53 I can confirm an increase in attack speed.  
We'll take a further look into this.

**Comment by CubeFromSpace** [comment]
Maybe attack speed is linked to attack power. Just throwing that out there.

**Comment by PeratX** [comment]
There is no attack speed control in Genisys. In vanilla MCPE too.
