### ISSUE TITLE
Cant close play on Player PreLogin, Login, or Join Event

### ISSUE THREAD

**Issue by ItzBulkDev** [iTXTech/Genisys#1487]
So im making a custom plugin to ban people (separately from default ban)
Genisys isn't letting me close the player onPreLogin or any of the methods used in the title

Here is the code I'm using:
```
public function onJoin(PlayerPreLoginEvent $event){
    $name = $event->getPlayer()->getName();
    $ip = $event->getPlayer()->getAddress();
    if($this->getConfig()->exists(strtolower($name))) {
        $m = $this->getConfig()->get($name);
        $event->getPlayer()->close('', "§cYou are Banned!\n§c" . $m);
    }
    if($this->getConfig()->exists($ip)){
        $m = $this->getConfig()->get($ip);
        $event->getPlayer()->close('', "§cYou are IP Banned!\n§c" . $m);
    }
}
```

I've tried by doing it with every user that joins and still doesnt work. Help

**Comment by ItzBulkDev** [comment]
I've tried removing my Auth plugin, still wont work

**Comment by ZedCee** [comment]
Issue tickets are for problems with the Genisys server, not custom plugin development.
There are variances in the api among servers, which is found in the documentation.
You also avoided the provided Issue template which provides any necessary information to help with issues, even though this technically is not an issue with Genisys, but with your plugin.

I recommend you ask on gitter.im/iTXTech/Genisys for further answers to your question.

**Comment by ItzBulkDev** [comment]
pretty sure its Genisys fault bc i even tried kick method but okay

**Comment by ZedCee** [comment]
Test the server sans your plugins (aka vanilla), if the problem persists, then it may be a bug.
Then I would suggest an issue ticket following the template provided.

**Comment by FaigerSYS** [comment]
Try to use PlayerLoginEvent

**Comment by TDMidkwhatisxd** [comment]
$event->getPlayer()->kick("banned");
