### ISSUE TITLE
Issue with big trees

### ISSUE THREAD

**Issue by yar2001** [iTXTech/Genisys#1488]
Warning: Division by zero in phar://C:/Users/Administrator/Desktop/Genisys/Genisys.phar/src/pocketmine/utils/VectorIterator.php on line 122

我与我的玩家们在服务器中，但是出现了一个错误导致无法正常游戏，已经出现很多次了。这让我的服务器不能正常运作！
机翻
My players are playing, but after this error led to the jump service, has been a lot of times! This makes my server not functioning properly.
MT

**Comment by Crypthu** [comment]
Yes :( im delete php and no problem :)

**Comment by Adam1609** [comment]
Does VectorIterator.php involved in mob spawner's leashes bug?

**Comment by yar2001** [comment]
I tried so many times that I might have found the problem. When I was alone on the server, I was planting trees. General oak tree seedlings will generate a very common tree, but sometimes will generate some special huge trees, and then a few minutes will be reported to the wrong:

Warning: Division by zero in phar://C:/Users/Administrator/Desktop/Genisys/Genisys.phar/src/pocketmine/utils/VectorIterator.php on line 122

Warning: Division by zero in phar://C:/Users/Administrator/Desktop/Genisys/Genisys.phar/src/pocketmine/utils/VectorIterator.php on line 127

 Such a problem has occurred three times, hoping to quickly repair!

**Comment by yar2001** [comment]
In addition, since the use of ITX, my world will always have some strange snow. How should I get rid of it?

**Comment by gaoyichuan** [comment]
@PeratX Your big tree generation caused this issue.

**Comment by Yoyu666** [comment]
@yar2001 你可以用command /biome 来改 :3

**Comment by yar2001** [comment]
@Yoyu666 所在的生物群系是12，也就是冰原。我并不介意有积雪，但是我的服务器中的积雪很明显是不真实的（或者说会自动产生，并且极不稳定，过一会就消失了），清理积雪不会产生雪球，并且重进服务器还会再次生成，也不会有破坏粒子产生。这些积雪并不是真正像原版机制中的“下雪”产生的。因此在积雪系统稳定之前，能不能设置一个开关关闭这个功能呢？

**Comment by boybook** [comment]
这是一个0.15的客户端的特性，与服务器无关。雪是你的游戏单机方面生成的，并不存在于服务器中。

**Comment by biswarm22** [comment]
Is this fixed? Sorry, i cant read Chinese/Japanese/Korean.

**Comment by Yoyu666** [comment]
use google dude!
