### ISSUE TITLE
add tur.ini language file

### ISSUE THREAD

**Issue by SuperAdam47** [iTXTech/Genisys#1492]
WARNİNG ALARM!! LARGE OPEN WAS DETECTED. The Turkish language was not found.

**Comment by ishitatsuyuki** [comment]
Closing. Invalid. Stop spamming.

**Comment by SuperAdam47** [comment]
this is first not spam

**Comment by dktapps** [comment]
@SuperAdam47 did you actually _read_ the warnings before opening this issue?
