### ISSUE TITLE
Anvils

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1496]
#### Issue description
Anvils do not work, they don't fix items, or apply enchantments when put in with a book.

#### Steps to reproduce the issue
Take a item put in in a anvil with a enchanted enchanted book that fits the item.

#### OS and versions

* Genisys: I think gitlab 12?
* PHP: 7
* Server OS: Mac? Idk what Server OS is.
* Game version: 0.15.0

#### Crashdump, backtrace, memory dumps, plugins list or other files
No crash dumps :)

**Comment by dktapps** [comment]
Duplicate of #888
