### ISSUE TITLE
2016.7.21 one-Report

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1497]
[Server thread/CRITICAL]: Could not execute task pocketmine\scheduler\CallbackTask: Call to a member function getItemInHand() on null
[12:11:22] [Server thread/CRITICAL]: Error: "Call to a member function getItemInHand() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 340

玩家类中的getItemInHand函数错误了原因值不能为null。。。
生物还是那样，0.15的东西大部分没有添加只是个空壳。
itx也变懒了啊。
服务器没有安装任何插件，只是进行压力测试。懒的说英文了
发帖时间凌晨1点13

**Comment by ZedCee** [comment]
Too lazy to fill out a proper template either. 
Without the proper information, we are unable diagnose what's actually wrong.

Errors like the above are typically related to plugins.
