### ISSUE TITLE
Invisible Lava

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1498]
#### OS and versions

* Genisys: 1.2dev 
* PHP: 7.0.4
* Server OS: LXDE
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Improperly Formatted Issue Ticket - Lacks Information
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
