### ISSUE TITLE
Feature Request: mobgenerate diversification

### ISSUE THREAD

**Issue by yar2001** [iTXTech/Genisys#1499]
#### Issue description
Can iTX only auto generate zombie and cow?  I didn’t find any other mob in my server . I think it can generate more than that! Like sheep, chicken, pig, creeper and skeleton
#### Steps to reproduce the issue
Nothing...
#### OS and versions
* Genisys: 1.2dev
* PHP:7.0.4
* Server OS: Win server 2012
* Game version: win10 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files
...

**Comment by dktapps** [comment]
This is already listed in the ToDo list in the README.
