### ISSUE TITLE
weather

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#15]
I dont see weather change,  and i did
/weather world rain
/weather rain
/weather rain 100
/weather world rain 100

So what is the correct command? I was trying all :(,  
I dont understand chinese so i dont understand what i miss :(

**Comment by ZhyMC** [comment]
ok we will check that and  give u a response

**Comment by astersx** [comment]
Thank you!!!  And this server is the best i ever tested,  i use it on my main server!!!! Good Job :+1:

**Comment by PeratX** [comment]
@astersx You are wrong with the weather code! 1 is rainy!

**Comment by PeratX** [comment]
/weather world 1 will change world into rainy.

**Comment by ZhyMC** [comment]
That's funny

**Comment by dog194** [comment]
I am sure that @ZhyMC do not know this. XD

**Comment by ZhyMC** [comment]
@dog194 =-=

**Comment by dog194** [comment]
hhh (interesting) :D

**Comment by astersx** [comment]
wow,  i didnt know  this,  and what is permision for rain? Any player can use this command -.-'

**Comment by astersx** [comment]
So,  how i make it snow?

**Comment by PeratX** [comment]
@astersx Change your chunk biome temperature

**Comment by astersx** [comment]
How i cange chunk biomes?

**Comment by PeratX** [comment]
@astersx Later I will at /biome command to it. Now you can modify it be MCEdit

**Comment by astersx** [comment]
is not op command tested

**Comment by astersx** [comment]
If i wanna prove u come in my sv and do /weather,  i banned that command with world protect so i need be online too to unban

**Comment by PeratX** [comment]
@astersx Fixed!

**Comment by astersx** [comment]
Ok :)
