### ISSUE TITLE
Message incorrect: Client is Outdated should read Server is Outdated

### ISSUE THREAD

**Issue by willotheblessed** [iTXTech/Genisys#1504]
I am trying to sign in a 0.15.3 client on the 0.15.0 Alpha server. It says my client is outdated, but the opposite is true. This message is confusing, not sure how to fix. The server message should be more helpful.

**Comment by ZedCee** [comment]
Without knowing what your Genisys version, OS, PHP, and Client OS are the issue cannot begin to be solved.  
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.  
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
