### ISSUE TITLE
Error Loading pocketmine.yml

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1506]
#### Issue description
Server won't turn on and gives me this message: 
Server thread/CRITICAL]: pocketmine\utils\ServerException: "This version is not supported, put enable-testing: true under pocketmine.yml server section to run this build at " (EXCEPTION) in "/src/pocketmine/Server" at line 1839
[16:21:55] [Server thread/DEBUG]: #0 (1): require_once(string phar:///Users/superserver/Factions/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

#### Steps to reproduce the issue
idk how

#### OS and versions
Pocket Edition
-->
* Genisys: #3759586  w10-done-properly  d89f80d5
* PHP: 7
* Server OS: Genisys
* Game version: 0.15.0

**Comment by ishitatsuyuki** [comment]
Please read the message. This branch is unsupported.

**Comment by flaxues** [comment]
The master branch is the only officially supported branch. All other branches are in testing and may be unstable. Do not use builds from other branches unless you are sure you understand the risks.

Source: README.MD

I do not know why it's called README but maybe you know ^_^

**Comment by dktapps** [comment]
@flaxues :D

**Comment by SuperDude36** [comment]
Does anyone know what happened to Jenkins? I got a Genisys 630 build out of the trash so I guess I'm good :)

**Comment by dktapps** [comment]
Jenkins expired. Use GitLab instead. Links are in the README.
