### ISSUE TITLE
bow bug ?

### ISSUE THREAD

**Issue by msr0** [iTXTech/Genisys#1508]
I thought bow behavair is crazy
I want you to format to mcpe single types

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
