### ISSUE TITLE
minecarts doesn't follow rails even when setted in Genisys.yml 

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#1510]
if i set the minecarts to be free moving they actually work but if i set them to follow rails and ride them they don't move and in third person view it shows me sitting above the minecart by 1 block high .

Steps to reproduce the issue :

set 'minecart-moving-type' to 1 in genisys.yml then restart the server and place a normal rail and then place a minecart and ride it .

OS and versions

* Genisys: Genisys git-b5cd177
* PHP: 7.0.2
* Server OS: linux
* Game version: android

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
```

**Comment by gaoyichuan** [comment]
This function is still WIP, and it's inside the TODO list.

**Comment by mote166** [comment]
@gaoyichuan k thx for responding and plz fix it asap cuz i really need it for my server ( so is everyone else ) .
