### ISSUE TITLE
Retrieving the items in place is difficult

### ISSUE THREAD

**Issue by SuperAdam47** [iTXTech/Genisys#1511]
#### OS and versions

* Genisys:yes
* PHP:7.0.8
* Server OS:windows
* Game version: 0.0#

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by GlitchPlayer** [comment]
Such a descriptive issue...

**Comment by ishitatsuyuki** [comment]
Improperly Formatted Issue Ticket - Lacks Information
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by SuperAdam47** [comment]
Yerdeki eşyaları alabilmek için dibine gelmemiz gerekiyor. Bu mesafeyi birazcık uzatabilir misiniz?
