### ISSUE TITLE
Windows machine not able to connect to server running on same machine

### ISSUE THREAD

**Issue by willotheblessed** [iTXTech/Genisys#1512]
#### Issue description
During a previous build it was possible to connect my windows 10 Minecraft to the pocket edition server running on that _same_ machine (this was during 0.14.3). Now I can not connect.

#### Steps to reproduce the issue
Start a server on a windows machine.
Start up Windows 10 Minecraft on same machine.
Try to connect. (you'll receive and error, with no response from server)

#### OS and versions
Genisys-7c6bb58
* PHP: 7.0
* Server OS: Windows 10
* Game version: 0.15.3

**Comment by dktapps** [comment]
Try the wiki before opening an issue, and search already-closed issues.
