### ISSUE TITLE
Enable mob spawning in specific worlds 

### ISSUE THREAD

**Issue by biswarm22** [iTXTech/Genisys#1513]
#### Issue description

cannot enable/disable mob spawning in specific worlds
#### Steps to reproduce the issue

cant customize mon spawning
#### OS and versions

* Genisys: cd2d9684bb3ed1947e8e9d7844deb3f099731805
* PHP: 7
* Server OS: Windows Server 2012 
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Quite a few changes and revisions to revolutionize Genisys that are in discussion.  This one is a favourite one of mine.  For now this will be on hold, but stay tuned.  

I'll be pressing about this one quite a bit...  @dktapps...

**Comment by ryanarp1** [comment]
Is there a world or version that will spawn monsters and animals? Do I need to be farther away from spawn point?

**Comment by ZedCee** [comment]
You can spawn mobs in all worlds by turning on in the genisys.yml config file. 
```
ai:
  mobgenerate: true
```
This is can not yet be enabled or disabled per world.

**Comment by ryanarp1** [comment]
I enabled this, do I need to run a reload command afterwards?

**Comment by ZedCee** [comment]
Restart the server and the changes will take effect.

**Comment by biswarm22** [comment]
@ZedCee Is there a way to enable it in one world and disable it in another?

**Comment by ZedCee** [comment]
@biswarm22 At present there is no way to enable or disable mobs per world.  That being said, there is discussion about some large changes to Genisys. One of which being further customization per world, something I too have been pressing for.  These changes could break a few things, but open worlds of possibilities in the future and are set to revolutionize Genisys. Presently we are on gitter.im and Mattermost, stay tuned there to hear more as we begin work on some of these changes.

**Comment by muzzy182uk** [comment]
Hi I have recently installed genysis on windows server 2012 r2 essentials I am running it headless through task manager. It created the world but no ai spawns have been created friendly or other wize I used the latest phar and looking at the yml file there is no entry for ai this is version 23

**Comment by JackNoordhuis** [comment]
The mob AI has been removed from Genisys. Please regenerate your genisys.yml configuration file to see the latest options.

**Comment by AndresKiros** [comment]
Is there anyway at all to enable mob spawning? Does anyone know if a plugin can do that?
They dont need to have ai.
