### ISSUE TITLE
Text sometimes vanishes off signs

### ISSUE THREAD

**Issue by DurianCube** [iTXTech/Genisys#1514]
#### Issue description
Sometime when u type a text on a sign (color or not) it will disappearing and the sign will be like a blank sign without any text. Sometimes it working but everytimes i typing text it will disappearing . 
(Sorry for my broken english)

#### Steps to reproduce the issue
1) Place a sign (try testing type text with this format full text on the sign [with color and no color] and typing text using color and non color
2) Type a text 
3) See the sign , sometimes it work but for me its everytime it wont work

#### OS and versions

*Genisys: cd2d968
*PHP: 7
*Server OS: Windows Server 2012
*Game version: 0.15.2

**Comment by GlitchPlayer** [comment]
Yup, I can confirm.

**Comment by ZedCee** [comment]
Upon initial testing I am unable to recreate this.  Do you have any sign related plugins installed?  I am also running the on a linux platform. Let us look into this.

@dktapps How about you, can you recreate?

**Comment by GlitchPlayer** [comment]
Maybe I can recreate this. This is one of the few problems we have.

**Comment by biswarm22** [comment]
It happens to me when you type a line of the sign too long

**Comment by DurianCube** [comment]
I don't have any plugins thats related with sign . I try this on ever server that's (with plugins and don't have any plugin)

**Comment by ABAxStorm** [comment]
Happens to me, also.

**Comment by TDMidkwhatisxd** [comment]
This issue was for long time!! But it happens randomly, so i dont care xd!!!

**Comment by dktapps** [comment]
This is an old, old, old bug from the days of PocketMine. I've been meaning to investigate this.

**Comment by dschwartz783** [comment]
This "stuff randomly not working" seems to be a recurring thing. Any chance the inventory bug could be related?

**Comment by dktapps** [comment]
@dschwartz783 the game changes. Simple.

**Comment by dschwartz783** [comment]
@dktapps Not meant as a criticism. I know that things break sometimes, but it seems there are at leas a couple issues that seem to randomly occur, which is an interesting coincidence.

**Comment by ZedCee** [comment]
@dschwartz783 It's the nature of computing and open-source programming.

Being said, @dktapps actually discovered a sure fire way to reproduce this error, making it not random at all.  I used this to reproduce it on my server.

_Any lines with several spaces between two words or characters could disappear the text from the sign.  This was related to restricting character per line, rather than by sign width._

There are actually a great deal of bugs from the PM base and it takes time to squash them all.

**Comment by dktapps** [comment]
@ZedCee It's fixed.
