### ISSUE TITLE
GearVR connectivity issue

### ISSUE THREAD

**Issue by badvision** [iTXTech/Genisys#1515]
#### Issue description
GearVR Minecraft can see server, cannot connect.  No messages appear on the server-side indicating a problem.  Also, server doesn't seem to readily show up unless added manually.  After 30 seconds, client does indicate a green status on the server but attempts to connect fail.  The Android client (2D) connects with zero issues on the same wifi network.

#### Steps to reproduce the issue
Attempt to connect to server using Minecraft VR 0.15.2 on a Galaxy VR (Note, Galaxy, etc)

#### OS and versions
* Genisys: Genisys-cd2d968 "Kyrios" (API 2.0.0)
* PHP: PHP 7.0.8
* Server OS: OSX; 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
* Game version: 0.15.2 (Gear VR, current version)

#### Crashdump, backtrace, memory dumps, plugins list or other files
Unfortunately there is no log activity when this problem occurs so I can't provide anything useful here (I know -- that sucks doesn't it?   Is there a debug mode I can enable?)

**Comment by ZedCee** [comment]
None of the developers actually have access to a GearVR system, thus it is an unsupported client.  Actually I was a bit taken there by this issue and I'm sorry to admit no development has actually taken place with GearVR.  Sounds cool though.  Like to hear someone else weigh in on this so I'll leave the issue open for now, but it will likely be closed, or considered as an enhancement for the far future.

**Comment by ZedCee** [comment]
@dktapps Know much about GearVR? :laughing:

**Comment by badvision** [comment]
Well, oddly enough I had it working previously with an older build -- just not sure which.  Were there any major changes to the networking implementation side of things over the last month?

**Comment by ZedCee** [comment]
There have been some large protocol changes since the release of 0.15.x.
This has caused quite a few new issues.  Presently there is an unsupported version that may fix some of those, but as for GearVR I personally can't say.  We'll have to wait to hear more.

**Comment by badvision** [comment]
If you need a tester, please don't hesitate to point me to the build. :)  Also, if there is a way to enable some kind of verbose debug logging, I'm happy to oblige and return some logs to you.

**Comment by dktapps** [comment]
@ZedCee no, I'm not rich enough :P 
The issues seen in VR Edition are pretty much the same as those with Windows 10 Edition Beta. #1337

**Comment by dktapps** [comment]
You might try method 2 listed [here](https://github.com/iTXTech/Genisys/wiki/FAQs#i-cannot-connect-to-servers-hosted-on-the-same-computer-with-windows-10-edition-beta-how-can-i-fix-this).

**Comment by biswarm22** [comment]
@dktapps Haha same here. @badvision You are soooooo lucky having VR lol

**Comment by ZedCee** [comment]
@badvision Did the method provided help with your issue?  Can we close this issue?

**Comment by badvision** [comment]
Thanks for following up @dktapps and @ZedCee -- I'm not sure how method 2 listed applies to VR since it's an Android app, but it's possible it.  Are you implying there is some kind of text file with settings I can modify on the android file system?  I'm happy to look but I'm kind of doubtful it would be a workable solution.

**Comment by dktapps** [comment]
@badvision yes.

**Comment by badvision** [comment]
I'll do you one better: I'll do a full directory listing and post it here so you have it for your reference and can compare with the standard Android version (non-vr) -- would that be at all helpful?

**Comment by badvision** [comment]
![image](https://cloud.githubusercontent.com/assets/5144198/17272203/f5346870-5655-11e6-9235-a2c519bc88a2.png)
Well how do you like that???  I'll report back on the contents of the text files.  Getting interesting.  Thanks for sticking with me through this one, folks.

**Comment by badvision** [comment]
options.txt does have "dev_uselocalserver:0" in it as suggested -- changing to 1 and reporting back.

Other things of note: All files are plain-text and colon-delimited so it's highly probable they're identical to other ports.  The VR options.txt has other menu-controllable settings but also has other goodies like CONTROLLER MAPPING which is good to know because the default controls are a little strange if you're used to, for example, the XBox version or whatever.  Kind of cryptic and no comments to provide a hint but I suppose anyone with time and patience could figure that bit out.

**Comment by badvision** [comment]
It did not work unfortunately.  Also, there was an update pushed out to 0.15.4 and the GearVR client now says it cannot connect because the server version is outdated.  I guess we can close this and I'll just wait for 0.15.4 support. :/  We still learned a few things here, namely the settings file is fairly similar.

**Comment by badvision** [comment]
Final note -- current build of w10-done-properly works GREAT.  Connects well and plugins working too.  Now to go work on that live-coding plugin concept.... ;)

**Comment by ZedCee** [comment]
@badvision That's great to hear.  I'm going to close this ticket.  If anything else comes up be aware that win10-done-properly is one of our unsupported branches, but if you post to this issue @dktapps will see (our lead dev on that branch).  We apologize for any breakages that may occur, as that branch is still being developed.

**Comment by dktapps** [comment]
@badvision Are you able to craft with GVR on the Win10 branch?

**Comment by badvision** [comment]
@dktapps The following worked:
- In creative mode, added 64 sticks and 64 coal to my inventory
- From inventory screen, crafted 64 torches using the sticks/coal (without crafting table)
- Placed the crafted torches in a chest
- Logged out
- Logged back in
- Contents of chest were reordered, but everything I put in there was correct including the torches.

Did you need me to test more elaborate crafting using a table, etc?

**Comment by badvision** [comment]
Also, forgot to say (how clumsy of me!) thank you @dktapps for a great job on this branch so far.  I'm about to have an ecstatic daughter once we can play together again with all these mods we picked out.  The server experience is an important part of how we engage with Minecraft as we can build much more elaborate worlds using warps, etc.   Not to mention, it's fun to have a Tardis that takes you places, am i right? ;)

**Comment by dktapps** [comment]
@badvision :D yeah it's been a rough ride. Win10 and PE both are buggy asf on the network layer and there are inconsistencies which make my life hard work. But it's good to know that my changes work for GVR too.

**Comment by ZedCee** [comment]
@badvision May want to head over to #1621 and take a look-see :+1:
