### ISSUE TITLE
Bug Enchant

### ISSUE THREAD

**Issue by Bluzzi** [iTXTech/Genisys#1517]
Players can delighted their tools thanks to a mod!

Here is a link or downloading the mod: https://www.youtube.com/watch?v=xhlpatS8H_k must result in holding a tool in his hand and used under 'enchant' mod without being OP or without a right mod works!

Genisys: git-5084225
protocol version 81
PHP:
Server OS:
Version: 0.15.3

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by Bluzzi** [comment]
0 plugin :/ I do not know the PHP version and OS

**Comment by Driesboy** [comment]
os is Andriod or windows etc
and i think php is 7.0.4

**Comment by Bluzzi** [comment]
OS = Android
PHP = 7.0.4

**Comment by Bluzzi** [comment]
Players can delighted their tools thanks to a mod!

Here is a link or downloading the mod: https://www.youtube.com/watch?v=xhlpatS8H_k must result in holding a tool in his hand and used under 'enchant' mod without being OP or without a right mod works!

Genisys: git-5084225
protocol version 81
PHP: 7.0.4
Server OS: Android
Version: 0.15.3

0 plugins

**Comment by gaoyichuan** [comment]
FOLLOW OUR ISSUE TEMPLETE!
