### ISSUE TITLE
Craft on Win10

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#1518]
#### Issue description

Craft does not work on Windows 10
#### OS and versions

* Genisys: git-a8b4261 "Kyrios"
* PHP: 7
* Server OS: Ubuntu
* Game version: Win10

#### Crashdump, backtrace, memory dumps, plugins list or other files

Notice: Undefined offset: 0 in phar:///root/swtest/PocketMine-MP.phar/src/pocketmine/Player.php on line 3346

```

**Comment by Driesboy** [comment]
https://github.com/iTXTech/Genisys/issues/1337 READ THIS!!
