### ISSUE TITLE
Bug Enchant

### ISSUE THREAD

**Issue by Bluzzi** [iTXTech/Genisys#1519]
Players can delighted their tools thanks to a mod!

Here is a link or downloading the mod: https://www.youtube.com/watch?v=xhlpatS8H_k must result in holding a tool in his hand and used under 'enchant' mod without being OP or without a right mod works!

Genisys: git-5084225
protocol version 81
PHP: 7.0.4
Server OS: Android
Version: 0.15.3

0 plugins

**Comment by Driesboy** [comment]
FOLLOW THE TEMPLATE!!!!!

**Comment by gaoyichuan** [comment]
If you continue do issue spamming, you will be welcomed by a ban

**Comment by Bluzzi** [comment]
I just want to tell you an important bug !!
