### ISSUE TITLE
Sign bug (+video)

### ISSUE THREAD

**Issue by Crypthu** [iTXTech/Genisys#1521]
#### Issue description

Sign text bugg
video: https://youtu.be/Iu2ruVSvMzE
#### OS and versions

* Genisys: Genisys
* PHP: 7.0.3
* Server OS: Windows
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Without knowing your Genisys version or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate information is provided, the issue will be closed; it may be reopened if you update the ticket with the required information.

**Comment by dktapps** [comment]
I might also comment that "Sign bug" is a very generic issue title and doesn't give us any hint as to what the issue actually is.

**Comment by Crypthu** [comment]
Video....

**Comment by Crypthu** [comment]
Watching youtube video....
