### ISSUE TITLE
Sign text does not reappear when BlockBreakEvent is cancelled for a sign

### ISSUE THREAD

**Issue by Crypthu** [iTXTech/Genisys#1522]
#### Issue description
[edited by admin]
When BlockBreakEvent is cancelled for a sign (for example in a protected area) the text on the sign does not reappear when the sign respawns

VIDEO FOR ERROR: https://youtu.be/Iu2ruVSvMzE Please watch...
#### Steps to reproduce the issue
- Break a sign in a protected area.
- When the sign reappears, it will be blank.

#### OS and versions

* Genisys: run from source (image)
* PHP: 7.0.3
* Server OS: Windows
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

![screenshot_2016-07-25-12-40-42](https://cloud.githubusercontent.com/assets/20270278/17098895/184c877e-5265-11e6-8a1d-a5b963e8d0dd.png)

**Comment by Crypthu** [comment]
No close... fix ...

**Comment by dktapps** [comment]
Another issue with a very generic title. Not to mention incorrect.

**Comment by Crypthu** [comment]
Sry im no english...

**Comment by dktapps** [comment]
Reproduced. Will investigate later.

**Comment by XFuryMCPE** [comment]
Isn't this a client-side bug? If you relog the text should reappear

**Comment by Muqsit** [comment]
^ yeah.

**Comment by Crypthu** [comment]
No client bug

**Comment by Crypthu** [comment]
Thank youuu :3
