### ISSUE TITLE
synapse dont work

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#1525]
#### Issue description

synapse dont work after https://github.com/iTXTech/Genisys/commit/6e22d0dc54256844c35688ee8725df1e7ae8fe51

#### Steps to reproduce the issue

download latest genisys
download latest synapse

#### OS and versions

*Genisys:https://github.com/iTXTech/Genisys/commit/6e22d0dc54256844c35688ee8725df1e7ae8fe51
* PHP:7.0.4
* Server OS:windows
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Driesboy** [comment]
fixed chat spam

**Comment by ishitatsuyuki** [comment]
It's deprecated, thanks. You're supposed to use Nemisys.

**Comment by Driesboy** [comment]
how i can install it if i run the .jar it do nothing
