### ISSUE TITLE
Hoe bug

### ISSUE THREAD

**Issue by mixailenko5** [iTXTech/Genisys#1526]
If you break block by hoe, that hoe breaking indicator does not change

**Comment by ZedCee** [comment]
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.  
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.  
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by ZedCee** [comment]
I just saw you're an iTX member...
You should know about issue templates.
I can't tell exactly what you're describing, it is very unclear.

**Comment by dog194** [comment]
@mixailenko5  Hoe donot lost its durability while breaking block. It just lost durability while Tilling or Hitting. Genisys' durability system was re-write. And work more like WIKI(http://minecraft.gamepedia.com/Item_durability)
BTW following the template is Genisys' issue reporting rule.
So next time XD.

**Comment by dog194** [comment]
914702683093ba885ffdd2e1d076c03161d7e740

**Comment by mixailenko5** [comment]
@dog194 ok i understand
