### ISSUE TITLE
SplObject

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1527]
!Warning: SplObjectStorage::detach() expects parameter 1 to be object, null given in phar:///jar/versions/Genisys/Genisys_d1db106.phar/src/pocketmine/Player.php on line 4359

**Comment by gaoyichuan** [comment]
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.

A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.

Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
