### ISSUE TITLE
Hateful Spam

### ISSUE THREAD

**Issue by alwe2710** [iTXTech/Genisys#1530]
Becuse of that you're hated.
A better Alternative:[ClearSky](https://github.com/ClearSkyTeam/ClearSky)

**Comment by CLiu13** [comment]
Just get out. 

At least the Genisys developers are mature enough not to whine and complain about ClearSky in the README. https://github.com/ClearSkyTeam/ClearSky/commit/30a0d22521424df85a1cd5d6d4f219002433fd23

Also, I do not see how Genisys lags - I have 50+ plugins on my server running Genisys, and I don't notice any lag. But, when I switch over to ClearSky, my server begins to lag.

If you don't like Genisys, that is your opinion, and I respect that. However, there is no need to be obnoxious about it and post an issue about it.

**Comment by ZedCee** [comment]
This requires a ban @ishitatsuyuki

**Comment by Muqsit** [comment]
@CLiu13 Ayee! <3
