### ISSUE TITLE
Server ticking rate is beyond normal.

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1532]
Recently, I've been getting enormous amount of load on my server. Mind checking the Level file?
![we](https://cloud.githubusercontent.com/assets/18363310/17146927/35aeb2aa-5315-11e6-8736-76b16364d913.PNG)

**Comment by XFuryMCPE** [comment]
How long has it been online?

**Comment by GenisysFTW** [comment]
@XFuryMCPE 37 minutes, 19 plugins.

**Comment by XFuryMCPE** [comment]
You should edit this post to match the issue template or you're going to get banned/ not helped

**Comment by ishitatsuyuki** [comment]
Improperly Formatted Issue Ticket - Lacks Information
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Please also paste the URL to the timings, so we can see more details.
Sorry for the inconvenience.
