### ISSUE TITLE
How i can download a phar, i dont know how, now its from gitlab, how i can, help me pls

### ISSUE THREAD

**Issue by SoyPro** [iTXTech/Genisys#1534]
#### OS and versions

* Genisys:
* PHP: 
* Server OS: 
* Game version:

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by LewBr** [comment]
Install on Jenkins!

**Comment by Muqsit** [comment]
https://gitlab.com/itxtech/genisys/pipelines?scope=branches

**Comment by ZedCee** [comment]
@LewBr Jenkins has be discontinued and not recommended anymore.
