### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by LewBr** [iTXTech/Genisys#1535]
#### Issue description

 I want to disable the help command on my server but plug in for this doesn't works.. can you members fromantic genisys make new system to disable some commands, or just make system to change it? Sorry english im german.

Plugin that doesn't works to disable /help, /me...
NoCMDPe, HelpMessage

**Comment by Muqsit** [comment]
Nope sorry. This MUST be done via plugins. Here's some code that can help you out...

public function cmd(PlayerCommandPreprocessEvent $e){
$command = explode(" ", strtolower($e->getMessage()));
if($command[0] === "/help" or $command[0] === "/?"){
$e->setCancelled();
    }
}
