### ISSUE TITLE
How do I Give all players a item at once?

### ISSUE THREAD

**Issue by Nevgent** [iTXTech/Genisys#1536]
#### Issue description
Need help giving all players items at once using /give 

#### OS and versions

* Genisys:
* PHP:7
* Server OS:Ubuntu 
* Game version:

**Comment by Muqsit** [comment]
Note that this is not a "forum" where you can post help threads.
It's /give @a <item>
(Make sure you enabled command selector in genisys.yml).
If you try getting help from the issue section, you can get banned for going off topic. This section is dedicated to bugs, enhancements and other related stuff.
