### ISSUE TITLE
Mob AI

### ISSUE THREAD

**Issue by MCITGAMER11** [iTXTech/Genisys#1537]
Mobs dont move or dont behave normally.
Please implement MOB AI.

**Comment by gaoyichuan** [comment]
We do have MobAI, enable them in genisys.yml. Also please follow our issue template

**Comment by dog194** [comment]
And our AIs are not good enough,(So if is possiable, you can find some plugins about AI.)

**Comment by MCITGAMER11** [comment]
Could you tell me how to enable it.
I m using server.pro PE Server.
Or can you tell me a Plug-in.

**Comment by dog194** [comment]
change the option in genisys.yml
