### ISSUE TITLE
nemisys spp 6 update

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#1540]
#### Issue description

nemisys spp 6 update

#### Steps to reproduce the issue

/

#### OS and versions

* Genisys: c4b3494 
* PHP:7.0.4
* Server OS:osx
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
No plz in title or description, please make it descriptive not with those redundant words.

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
0.15.4 nemisys

https-//transfer.sh/KbQRQ/spigot.jar
