### ISSUE TITLE
How to use Synapse?

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys#1544]
#### Issue description

I do not know, use it can give me a basic manual?

#### OS and versions

* Genisys: 2.0.0
* PHP: 7
* Server OS: Windows
* Game version: 0.15.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
NOTE that we don't provide help in this section. This section is dedicated to ISSUES only.
https://github.com/iTXTech/Synapse/wiki/How-to-setup
You can get blocked from accessing this branch if you try getting help from here, next time!

**Comment by RedstoneAlmeida** [comment]
not work :/
