### ISSUE TITLE
Unlimited spawn eggs glitch

### ISSUE THREAD

**Issue by Kelton01** [iTXTech/Genisys#1546]
#### Issue description

When in survival mode you can use spawn eggs but the amount you have won't go down. For example you can have just 1 zombie egg but spawn 10 because the egg will never disappear.
#### Steps to reproduce the issue

Make sure you're in survival mode. Give yourself any type of spawn egg and use it
#### OS and versions

* Genisys: Genisys-00656ef
* PHP: 7.0.3
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Yoyu666** [comment]
this is vanina mcpe bug,because this is since 0.8.0...

**Comment by TheAppleGamer** [comment]
Most likely will be fixed in 0.16.0 because the devs said they are fixing multiplayer

**Comment by Kelton01** [comment]
Oh ok thanks
