### ISSUE TITLE
Chunks getting overwritten in Anvil worlds

### ISSUE THREAD

**Issue by xHFx** [iTXTech/Genisys#1549]
#### Issue description

https://gyazo.com/665f4293adbf05416cd46052c98dd01a

This starts to happen on Anvil maps im guessing the MCPC maps I used this happened on and it get worst and worst 
#### OS and versions

- Genisys: https://github.com/iTXTech/Genisys/commit/00656ef426d7cc274e553a958952bfc15ea72ac6
- PHP: php7
- Server OS: Ubuntu
- Game version: 
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Your build is outdated. Please update to the newest build and try to reproduce it. If you can, please update the ticket or it may be closed.

**Comment by xHFx** [comment]
I updateded it but what do you mean try to reproduce it.

**Comment by dktapps** [comment]
Does the problem still happen on the newest build? If so, update the version hash in the ticket.

**Comment by xHFx** [comment]
I dont know yet I run a factions server and its like random when it happens so time is key

**Comment by dktapps** [comment]
All right, well make sure you update the ticket if it happens again.

**Comment by rdcmcpe** [comment]
This happens to my too i have the latest version
Pc maps keep crashing

**Comment by rdcmcpe** [comment]
Can u guys fix the word crashin?

**Comment by dktapps** [comment]
@rdcmcpe that is a different issue, refer to #1206

**Comment by ZedCee** [comment]
For clarity purposes, is the crash server side or client side?  
PC Maps contain block and entity information (NBT data) that at present is not handled correctly by the client, ultimately leaving us to wait on an update.  Of course, however, with an update comes the time to correct other issues it may also cause in general.

**Comment by dktapps** [comment]
@ZedCee this isn't a crash, it's an issue with some chunks not loading.

**Comment by rdcmcpe** [comment]
Yeah my mcpe crashes

**Comment by ZedCee** [comment]
@rdcmcpe See #1206, that would definitely be the issue you are experiencing.  There are a couple posts for temporary resolutions, but they may not be exactly what you are looking/hoping for.

**Comment by xHFx** [comment]
Its world corruption not a chunck loading problem the blocks are loading into my spawn and they dnt go away how is that a chuck prob

**Comment by dktapps** [comment]
@xHFx please explain in more detail. What I see in the picture looked like a missing chunk. What's the actual problem?

**Comment by SuperDude36** [comment]
@dktapps How can I find a non-testing phar? All I can find is GitLab. It doesn't even support 0.15.4

**Comment by xHFx** [comment]
https://gyazo.com/0de5de57e960c28c6a1135afc6a42253 Happened agn this is a spawn that was made via PC Anvil format the Genisys is tryna gen land inside of it !!

**Comment by ZedCee** [comment]
@SuperDude36 This is not a forum for questions.  All the phars are located on Gitlab and 0.15.4 just came out and is not supported yet.

@dktapps Could this be populator related?

**Comment by dktapps** [comment]
@ZedCee it seems unlikely

**Comment by Muqsit** [comment]
A bit offtopic...

pocketmine\level\fomat\leveldb\LevelDB.php
Line 79

`$this->db = new \LevelDB($this->path . "/db", [`

should it be .db or /db?

**Comment by dschwartz783** [comment]
I've actually noticed some chunk corruption on a world too, but the world was an MCRegion one. I think this issue exists, but isn't directly tied to the Anvil format. The Anvil world we have has no corruption issues that I know of.

**Comment by xHFx** [comment]
My has no corruption issues either but the chucks are getting overwritten in my spawn'

**Comment by legoboy0215** [comment]
@Muqsit '/db' is right I think. In LevelDB there is a db folder.

**Comment by vcraftPE** [comment]
I have same bug and lastest genisys

**Comment by YaBoiBalAnce** [comment]
This is still happening and it becoming worse
http://i66.tinypic.com/33njfkm.jpg

**Comment by ZedCee** [comment]
This may be a stupid question:
Do any of you edit with outside software, like MCEdit?

**Comment by dschwartz783** [comment]
Can we verify if we're using Anvil worlds, or MCRegion worlds? The data files will either end in ".mcr" for MCRegion, or ".mca" for Anvil.

**Comment by xHFx** [comment]
Any fix ?

**Comment by Sandertv** [comment]
I can confirm this issue too, random chunks are getting resetted to some time ago, no way to revert it.

**Comment by JackNoordhuis** [comment]
This issue should be fixed on the [mcpe-1.0 branch](https://github.com/iTXTech/Genisys/tree/mcpe-1.0). I'm going to close this issue for now, if this problem is still occurring feel free to reopen this issue :)
