### ISSUE TITLE
[FEATURE] Entity Spawning

### ISSUE THREAD

**Issue by Muqsit** [iTXTech/Genisys#155]
Can you add the command /summon to the game....just like those PC servers have?

Usage: /summon <entity>

**Comment by happy163** [comment]
Can you give us more information about this command.

**Comment by Muqsit** [comment]
/summon Zombie
Will spawn a zombie at the position of the player.

/summon Creeper
Will spawn a creeper at the position of the player
And so on..

**Comment by gaoyichuan** [comment]
It seems not difficult. I will work around it after my exam(Jan.29), in my winter holiday.

**Comment by Muqsit** [comment]
Thanks :)

**Comment by PeratX** [comment]
Just use Entity::createEntity xD

**Comment by gaoyichuan** [comment]
@PeratX I think I will just use code from Mob Spawning Eggs. XD
