### ISSUE TITLE
At version 0.15.4 it says outdated client

### ISSUE THREAD

**Issue by Mike4l6** [iTXTech/Genisys#1552]
#### Issue description

[17:46:06] [Server thread/INFO]: Mike4l6[/173.57.199.53:1025] logged out due to Outdated server!
0.15.4 Just updated
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheAppleGamer** [comment]
Dang protocol changes :P

**Comment by TheAppleGamer** [comment]
Fixed it :)

**Comment by Mike4l6** [comment]
Thanks

**Comment by Mike4l6** [comment]
Wheres the phar?
