### ISSUE TITLE
0.15.4

### ISSUE THREAD

**Issue by WBTclancode** [iTXTech/Genisys#1556]
Issue description

It says outdated client on Mcpe

Steps to reproduce the issue
 
I don't get it

OS and versions

Genisys: latest src
PHP: 7
Server OS: Windows 8 server // 2012 R2
Game version: 0.15.4
Crashdump, backtrace, memory dumps, plugins list or other files

Na

Ps it won't work still

**Comment by dog194** [comment]
latest is not a version.
Plz write the Git SHA like 0ddc67f32520cd786c0114dd1c323347674aa3c1

**Comment by WBTclancode** [comment]
K fixed
