### ISSUE TITLE
Jenkins server unusable

### ISSUE THREAD

**Issue by Striker209** [iTXTech/Genisys#1557]
#### Issue description

The jenkins server seems to be offline/away as it gives a 404 error

#### Steps to reproduce the issue

Try to connect http://jenkins.mcper.cn/job/Genisys-master/
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Jenkins was removed weeks ago. Use GitLab. Links are in the README.
