### ISSUE TITLE
New functions for SPP

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#1558]
#### Issue description
Make genisys can connect to multiply synapse/nemisys instances(such as Spigot and BungeeCord).

#### Steps to reproduce the issue
Add this feature to genisys.

#### OS and versions

* Genisys: Current version
* PHP: 7.1
* Server OS: Windows/Linux
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Closing this in favour of #1540 with reference.
