### ISSUE TITLE
(Question) PHP7Plugins

### ISSUE THREAD

**Issue by MilkoIvanov** [iTXTech/Genisys#156]
Since Genisys is way ahead pocketmine with PHP7 some plugins are incompatible shouldn't it there be a Plugins repo or something because as far as I know the changes between PHP5 and PHP7 are not that Big, on syntax side.

**Comment by flaxues** [comment]
I was thinking it was very hard to make all the plugins work with php7 but I'm running a php7 for some hours and every plugin are working normal with some exceptions... Most of the plugins just need a small one line fix

**Comment by linuzo** [comment]
Yeah most my plugins still work..

**Comment by flaxues** [comment]
If you have any plugins that don't work with php7 say it to me :P

**Comment by PeratX** [comment]
NBT are changed into NBTTags. This is the only change for plugins

**Comment by flaxues** [comment]
@PeratX Nope Manyworlds and worldeditart are needing more fixes but I can't fix that

**Comment by gaoyichuan** [comment]
@PeratX But the plugin developers should make their plugins compatible with PHP7, not Genisys's API.

**Comment by PeratX** [comment]
@gaoyichuan Genisys API is the same as PocketMine-MP API 2.0.0

**Comment by MilkoIvanov** [comment]
Well "EssentialsPE""EssentialsTP" , "ManyWorlds", "Touchit"i think these were rhe plugins that had problems

**Comment by flaxues** [comment]
@gaoyichuan It's nog updates because Pocketmine is not official supporting php7 for now

**Comment by flaxues** [comment]
@MilkoIvanov I have fixed manyworlds and EssentialsPE to work with Genisys. You want it?

**Comment by flaxues** [comment]
@PeratX You should add a new Repository called: 'php7 compatible plugins'

**Comment by MilkoIvanov** [comment]
@flaxues Yeah thank you!

**Comment by flaxues** [comment]
Manyworlds: https://github.com/flaxues/ManyWorlds-PHP7
EssentialsPE: https://github.com/flaxues/EssentialsPE-PHP7
Killrate: https://github.com/flaxues/KillRate_v2.1.1-PHP7
Economy (not done yet): https://github.com/flaxues/EconomyS-PHP7

**Comment by MilkoIvanov** [comment]
So @PeratX are we getting the PHP7Plugins repo? Just to close this issue.

**Comment by Muqsit** [comment]
You may close this thread...
Btw flauxes...can you update WorldEditArt? :-:

**Comment by MilkoIvanov** [comment]
Well thanks guys :)
