### ISSUE TITLE
Block Placement while flying

### ISSUE THREAD

**Issue by Crypthu** [iTXTech/Genisys#1560]
#### Issue description
The problem is that if , for example crtative flying mode and put behind us a little bit of the block you can not make it and I would like if you would you do that around by.

#### Steps to reproduce the issue
1. Grab a block and fly him back and put yourself down a bit
2. the block will disappear

#### OS and versions
* Genisys: This server is running Genisys (codename "Kyrios")
* PHP: 7.0.9
* Server OS: Windows
* Game version: 0.15.4

**Comment by ZedCee** [comment]
I've noticed similar issues regarding any block placing directly where you may be flying, as well as behind you while flying.  This appears to be a long standing issue throughout the server commits.

@Crypthu Could you provide the commit number of your version and edit your template with that.  Someone will look into this, but it may take a bit to get to.

**Comment by Crypthu** [comment]
version ?

**Comment by ZedCee** [comment]
For example, e28d63b9, is the latest version number.  Displayed when you start your server.

**Comment by Crypthu** [comment]
im not download all source im only editing files

**Comment by Crypthu** [comment]
I'm not used it enough to download the entire source only for that which is fixed to edit php

**Comment by Crypthu** [comment]
Version whatever it may be , this is a mistake you can also hone

**Comment by ZedCee** [comment]
Then there's a good chance that my issue is not actually the same issue you are experiencing.  I run from src as well, but via git tools I pull a fresh copy every commit.  
There's no way to know for certain unless we can replicate the environment and server you are run.  I can only recommend that you update to the latest commit, or briefly run a phar from gitlab, to see if the same issue persists.

**Comment by ZedCee** [comment]
I will close this issue for now, but will gladly reopen it if you can recreate the issue with the latest release from the master branch without plugins.
