### ISSUE TITLE
Creative Bug..

### ISSUE THREAD

**Issue by MaryVictoria** [iTXTech/Genisys#1565]
Can't choose blocks. And also the error in console.help?attached Screenshot

**Comment by ZedCee** [comment]
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by MaryVictoria** [comment]
![Uploading Screenshot_2016-07-30-12-45-49-1.png…]()

Help this error message about the drop item
