### ISSUE TITLE
When will genisys be updated to 0.15

### ISSUE THREAD

**Issue by MinerNetworkOwner** [iTXTech/Genisys#1568]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Thank you for spamming. Next time, you will be banned.

**Comment by MinerNetworkOwner** [comment]
I mean 0.15.4

**Comment by dktapps** [comment]
Try updating and don't waste our time asking stupid questions.

**Comment by Yoyu666** [comment]
@Dktapps,he dont know~u need tell him,because the webside is dead,so he dont kbow where to update it.... so pls dont mad from him XD
