### ISSUE TITLE
Players are able to get super weapons

### ISSUE THREAD

**Issue by Kelton01** [iTXTech/Genisys#1569]
#### Issue description

Players are able to get sharpness 1000 swords and any other enchantment with a new hack tool. Is there any way to patch this?
#### Steps to reproduce the issue

Need the hack tool to reproduce
#### OS and versions

* Genisys: Genisys-6fa3bac
* PHP: 7.0.3
* Server OS:
* Game version: MCPE

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
Use plugins to patch this.
public function onDamage(EntityDamageEvent $e){
  if($e instance of EntityDamageByEntityEvent){
    $i = $e->getDamager()->getInventory()->getItemInHand();
    foreach($i->getEnchantments() as $en){
      if($en->getLevel() > 5){
        $e->getDamager()->getInventory()->removeItem($i);
      }
    }
  }
}

**Comment by dog194** [comment]
@Muqsit  Unneeded. All enchantment effects controlled by Server have MAXLEVEL limit.
Although some players have sharpness 1000 swords, the swords only work like Level 5.
Also some enchantment effects computed by client cannot be controlled by Server now.

**Comment by Kelton01** [comment]
They still 1 hit players with protection 7 armor. How do I set the limit?
