### ISSUE TITLE
Farmland

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1571]
#### Issue description

When you try to grow crops, the farmland doesn't get wet and the crops don't grow
#### Steps to reproduce the issue

Farm some land and try to grow crops
#### OS and versions

* Genisys: 1.2dev
* PHP: 7.0.3
* Server OS: LXDE
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Adam1609** [comment]
Mostly I will use Farms plugin from organization!

**Comment by dog194** [comment]
do you check your setting in Genisys.yml? and in server player can crop without water

**Comment by dog194** [comment]
also genisys version should not be 1.2dev. you should paste the git version. :)

**Comment by ishitatsuyuki** [comment]
Closing for outdated version. You configuration is probably incorrect.

**Comment by TheAppleGamer** [comment]
I always update once a day

**Comment by ishitatsuyuki** [comment]
Improperly Formatted Issue Ticket - Lacks Information
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by TheAppleGamer** [comment]
There we go, updated my ticket

**Comment by ishitatsuyuki** [comment]
And, have you enabled the options to do random ticks?
