### ISSUE TITLE
Bow cannot be shoot when jump once

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#1574]
#### Issue description

Bow cannot be shoot when jump once

#### Steps to reproduce the issue

Hold the screen to activate the bow, jump once, and the arrow won't shoot.
The same thing is not happened when not jumping.

#### OS and versions

* Genisys: 37abb4d
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Minecraft Windows 10 Edition

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Can be reproduced on the master branch.
Just jump and a primed bow is rendered useless.

#### OS and versions
* Genisys: from src: 6b404b2
* PHP: 7.0.9 (native libraries)
* Server OS: Arch
* Game version: 0.15.4 iOS

@intagaming We will look into this, it may take a bit.  Stay tuned.
