### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by majovec** [iTXTech/Genisys#1575]
Bug maps  
- 0.14.x  maps work
- 0.15.x not work maps

(annihilation maps Canyon Amazon ...... )

**Comment by gaoyichuan** [comment]
Closing for not following the template and unclear language.

**Comment by gaoyichuan** [comment]
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by ZedCee** [comment]
#1206
