### ISSUE TITLE
Effect Particles

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1577]
This has been an issue since 0.15 release.
$effect->setVisible(false);
DOES WORK but it will replace the effect's particle with a black particle.

* Genisys: 1.8.0 | #3832426
* PHP: 7.0.8
* Server OS: Ubuntu 14.04 LTS
* Game version: 0.15.1, 0.15.2, 0.15.3, 0.15.4

**Comment by Muqsit** [comment]
confirmed... ._.

**Comment by legoboy0215** [comment]
Yeah. But IDK why some times it works.

**Comment by GlitchPlayer** [comment]
Lel, I thought only template can be submitted?

**Comment by GlitchPlayer** [comment]
Lmao

**Comment by ishitatsuyuki** [comment]
@GlitchPlayer it doesn't matter if adequate information is provided. It looks better if unneeded things are trimmed down.

**Comment by Crypthu** [comment]
EssentialsPE plugin funcions ... no bug

**Comment by Muqsit** [comment]
@Crypthu That's because EssentialsPE doesn't send invisibility effect packet to the player.
---
And this seems to be a client bug.. ;-;

**Comment by robske110** [comment]
Protocol change probably

**Comment by dktapps** [comment]
This appears to be a client issue. I won't say "bug" because there aren't any circumstances that I know of that would require invisible particles in vanilla MCPE currently. Closing.

**Comment by dktapps** [comment]
This should be able to be fixed in the 0.16 update.

**Comment by Muqsit** [comment]
This still hasn't been fixed.
