### ISSUE TITLE
File too short : libz.so1

### ISSUE THREAD

**Issue by AlpBEgger** [iTXTech/Genisys#1578]
Help me please!

- Genisys 99
- PHP 7.0.6 x86 64
- Debian 8 x86 64
- PE 0.15.4

I can't start server because get this error :

root@play:~/kin# ./start.sh
./bin/php7/bin/php: error while loading shared libraries: /root/kin/bin/php7/bin/../lib/libz.so.1: file too short
root@play:~/kin#

**Comment by TDMidkwhatisxd** [comment]
i got it too!! Is corupted i guess :/ !! Even the builds from pocketmine got same error!!
I replaced libs with the ones from my old php7 as a test and worked!!!

And is from /bin/php7  not from genisys fork!!
