### ISSUE TITLE
Hunger is not working properly.

### ISSUE THREAD

**Issue by linuzo** [iTXTech/Genisys#158]
Hunger is suppose to workk like this.  

Action and Exhaustion Level Increase

    Walking and sneaking (per meter): 0.01
    Swimming (per meter): 0.015
    Breaking a block: 0.025
    Sprinting (per meter): 0.1
    Jumping: 0.2
    Jumping while sprinting: 0.8
    Attacking an enemy: 0.3
    Receiving any damage: 0.3
    Effects of food poisoning (Raw Chicken/Rotten Flesh): 0.5 per second (15.0 total)
    Effects of food poisoning (Pufferfish): 1.5 per second (22.5 total)
    Regenerating 1 health point: 3.0

Any way to implement this into the hunger system..  As it is not suppose to be dropping the same rate no matter what your doing..

**Comment by happy163** [comment]
Thank you very much. We'll improve the hunger system soon.

**Comment by markkrueg** [comment]
When standing still hunger drops very quickly. I have even set in genisys.yml:
```
 #Hunger Time-Counter, Default: 80=4sec
 hunger-timer: 900000
```
And it still drops really fast when just standing still. How can I slow down hunger?

**Comment by PeratX** [comment]
@markkrueg In fact,@happy163 is rewriting hunger system.

**Comment by linuzo** [comment]
Thanks @happy163

**Comment by isoz** [comment]
A month later no news?

**Comment by PeratX** [comment]
@isoz @happy163 is also busy with study... Almost done
