### ISSUE TITLE
Server Is Laggy

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1580]
Build:Genisys 0ddc67f     
PHP: 7.0.3
OS: Centos
Machine VDS: A root server with dedicated hard drive
Ram:16 gb
Swap: 8gb
Cpu Model:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
Stepping:              4
CPU MHz:               2094.950
BogoMIPS:              4189.90
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-3

If u need more info tell me

Steps to reproduce, run it  xd
-------------------------------------------------------
For some reason server lag , just too hardcore!! It just suddenly get 1.0 tps , then 18 , then 4, 20 , etc...
On timings say , averange 17-18 sometimes , but in fact tps is 1-8 mostly!! Is just go down too fast!!
And on top , even with 60 players , sometimes cpu ussage goes over 170% for a second!!
It can use even 300% if it will give me more TPS xd!!
![img_20160801_203009](https://cloud.githubusercontent.com/assets/18122629/17304647/e7c6482a-5826-11e6-840f-f2df32af2226.JPG)
[pocketmine.txt](https://github.com/iTXTech/Genisys/files/394499/pocketmine.txt)

http://timings.aikar.co/?url=21792014

Any advice would be great!!
:)

**Comment by robske110** [comment]
Firstly many of your plugins seem to be badly written. And also this is genisys. Sadly lag is a well known issue here, and I'm sure @dktapps is doing everything to resolve it while the others are trying to make it even more bad. You might want to try another fork.

**Comment by TDMidkwhatisxd** [comment]
Many!! Is a good answer -_- !!

**Comment by ZedCee** [comment]
Plugins very frequently cause issues because most are outdated or poorly written.

**Comment by robske110** [comment]
But he has only 5% plugin load. I'd recommend to disable AI

**Comment by dktapps** [comment]
Judging by your timings you have excess network overhead. Unsurprising considering you're hosting so many players.

**Comment by TDMidkwhatisxd** [comment]
So, there are plugins at fault? Hmm , can u tell me what plugins u think it cause lag?
Ofcourse , simpleauth wont be removed  !! I dont wanna reset server!!!!
If auth plugin is at fault!! Genisys should develop a auth plugin :)


So 80 players is out of question? Even with 60 it drop tps under 8-10 sometimes!!

**Comment by Muqsit** [comment]
Can you also tell us your net speed?

**Comment by TDMidkwhatisxd** [comment]
dmesg | grep eth0
[    4.567932] e1000 0000:00:05.0 eth0: (PCI:33MHz:32-bit) 00:1c:42:00:03:58
[    4.567948] e1000 0000:00:05.0 eth0: Intel(R) PRO/1000 Network Connection

**Comment by robske110** [comment]
it is not your plugin's fault. Please try to disable AI

**Comment by robske110** [comment]
and we need real net speed
do some sort of speed test

**Comment by TDMidkwhatisxd** [comment]
All is disambled !! I had a pet plugin , but removed , and no changes!! I will do a speed test now!!

**Comment by robske110** [comment]
AI from genisys?

**Comment by TDMidkwhatisxd** [comment]
Al from genisys is disambled

**Comment by robske110** [comment]
And i just noticed you have only 2.10GHz per core, wich isn't really enough for Genisys? Do you have the possibility to get sth like 3Ghz per core?

**Comment by TDMidkwhatisxd** [comment]
Network speed is 1gbps , but i guess it can be lower!!
I dont wanna to do speed tests, that needs me to download a program!! 
But i just downloaded a file with 32mb/sec  !! 
So 32mb/sec im 100% sure is enough!!

And cant get a 3ghz cpu :(

**Comment by robske110** [comment]
Network speed is no problem at all.
We can, sadly not really help you. The only thing that helps is getting a better Core speed.
Or you may try one of these things:
world world and world plot ticking is taking much up too. This doesn't necessarily mean it's all by entities. Disabling some random-ticking-blocks may help.
### Also, what i do not understand why non-player-entities ticking has so much impact. This may be a real issue in genisys.

**Comment by TDMidkwhatisxd** [comment]
And u can see in pocketmine.yml  I disambled chunks ticking!!

**Comment by robske110** [comment]
read my edited version please

**Comment by TDMidkwhatisxd** [comment]
I have time comander wich do /lagg clearall  every 2 minutes

**Comment by robske110** [comment]
Sadly, then i can really not help you. Genisys has some problems with non-player-entities using much resources even with AI disabled, that may get fixed in some time.

I apologise for not being able to help you with Genisys.

**Comment by TDMidkwhatisxd** [comment]
I guess i will put 65-70 slots -_-  !! Dang wen my server was not popular i could easy put 500 slots!!
Then after some weeks i saw 180 players online and limited to 150 , then 120 , 100, 80 , Now 70 :( !!

In just 7-10 more updates(i mean big updates) i will need to limit to 40-50 players!! And final 1 player (1 player was a joke) =)))!!!


And thx for help!

**Comment by robske110** [comment]
You may also try to switch to another fork. There'll be probably less features but that automatically means that you have less bugs and a bit more Performance.

**Comment by TDMidkwhatisxd** [comment]
U know , that i used C****S*y  !! But i had same problems on my 3.4ghz vps (old hoster, moved becouse was expensive) !! Im sure it may be a less laggy !!

And pocketmine-mp , is the worst!! I know is original!! But on 0.12  there was undetified offset -1 error, wen y= -1  on player login!!  They ignored it hardcore!! And fixed only wen genisys already  patched it!!
Now they wanna again for ppl to use official pocketmine, many succesfull server owners dont use it!!

Sooo.... Welll , ill do my best to find a workaround :)

**Comment by robske110** [comment]
do that 
and btw PocketMine is not a fork :P

**Comment by TDMidkwhatisxd** [comment]
Ik!!! But i guess u suggest me pocketmine too for less lag :p
