### ISSUE TITLE
Inventory/Hotbar Glitch

### ISSUE THREAD

**Issue by CLiu13** [iTXTech/Genisys#1581]
#### Issue description

Infamous hotbar glitch is back, but a bit different this time.

When the glitch occurs, I cannot place any items in my hotbar from my inventory.

#### Steps to reproduce the issue

I cannot find a definite pattern or series of steps to produce this bug. It seems to occur almost randomly.

However, there are a few "triggers" that seem to cause the glitch to occur more frequently, but each trigger listed below does NOT cause the glitch 100% of the time.

- Picking up items after a person died
- Picking up items that are spawned in the sky and drop down
- Having items being added to your inventory with addItem()

#### OS and versions

* Genisys: 6b404b2f
* PHP: 7
* Server OS: Ubuntu 14.04
* Game version: MCPE 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

Does not cause a crash, and does not cause any error messages to show up in console.

**Comment by ZedCee** [comment]
This is a longstanding issue that has plagued PM and its derivatives for a while.   
We are constantly looking for ways to fix this, making small improvements here and there.  
Our unsupported win10-done-properly branch has some fixes for those inventory/hot-bar issues, but is not yet at production standard (beta) and you should expect other problems; 
a **_use at your own risk_** option. 
 
I will leave this open for now, but there is a chance it will end up closed, as this is a well known issue.  Keep up to date and improvements will come in time.

**Comment by CLiu13** [comment]
Thanks for the info.

Although it may be a longstanding issue, it seems as if this bug is occurring more frequently and noticeably than it used to. None of my players reported this bug before, up until now - and it occurs quite regularly now, unfortunately.

Did a recent change possibly trigger this issue?

**Comment by ZedCee** [comment]
I think more likely than not the newest changes and additions to anvils and enchantments have exposed bugs existing within the base code.  
As the client updates so do many of the handling approaches as well, especially as the Windows 10 version is being rolled out.  And errors in the way the client handles things also arise and become exposed in the development on the server side of things (win10-done-properly).

**Comment by CLiu13** [comment]
W10-done-properly branch fixes this issue, will be using this branch for now (even though it is a bit unstable).

Thank you for all of your help! You may close this issue now if you want :P

**Comment by ZedCee** [comment]
@CLiu13 Im glad to see a fix is one the horizon.  

@dktapps Another success with fixes from your branch :+1:

**Comment by dktapps** [comment]
Yeyey, I knew it would. By the way @CLiu13 , if you figure out what's causing the segmentation fault, please do let me know at #1337
