### ISSUE TITLE
Keep experience 

### ISSUE THREAD

**Issue by Dannyiy** [iTXTech/Genisys#1582]
#### Issue description
When a player died,  he lost levels, although keep-experience is active. If it disconnects and reconnects, it recovers levels

#### Steps to reproduce the issue
1. Do /kill or be killed by an another player
2. After that, we lost levels

#### OS and versions

* Genisys: e28d63b
* PHP: 7.0.3
* Server OS: Hosted on my Android phone
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Can be reproduced.

Experience displays inconstantly upon death with `keep-experence: true`, although upon level up or relogin returns to normal.  Further more the first level up, after the level temporarily reverts to 0, counts toward a full level up regardless of present XP.

#### OS and versions
* Genisys: from src: 6b404b2
* PHP: 7.0.9 (native libraries)
* Server OS: Arch
* Game version: 0.15.4 iOS

@Dannyiy  We will look into this as soon as we can. 

_**For your notes:**_ Experience functions normally if `keep-experience: false`, this will prevent any cheating to gain levels that may be happening. It is also strongly advised to be using the latest commit (6b404b2) before filling out an issue ticket as stated clearly in the issue template; This expedites both the handling of issues and development.
Stay tuned.
