### ISSUE TITLE
Messages containing %0 can freeze/crash the client

### ISSUE THREAD

**Issue by Dannyiy** [iTXTech/Genisys#1583]
#### Issue description
If a player do /me %0 , it will crash all connecteds clients. Bug tested on many servers.

#### Steps to reproduce the issue
1' Do /me %0

#### OS and versions

* Genisys: 6b404b2
* PHP: 7.0.3
* Server OS: On my Android phone
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Can reproduce.  Causes a crash.  The crash only seems to be client side, you can reconnect immediately following.  However this is likely an error on what the server returns to the client.

Interestingly enough, everything appears okay on the server.  No errors or debug messages and everything keeps functioning after the fact.

#### OS and versions
* Genisys: from src: 6b404b2
* PHP: 7.0.9 (native libraries)
* Server OS: Arch
* Game version: 0.15.4 iOS

@Dannyiy We will look into this.  Stay tuned.

**Comment by robske110** [comment]
This is a funny client bug. %0 tells the client to find the translation string 0
and as i know mojang this is probably what they did:
function translateString(translationString){
 int Index = 0; 
 bool foundTranslatedString = false;
 while(!foundTranslatedString){
  Index++;
  if(translationIndex[Index] == translationString){
   foundTranslatedString = true;
  }
 }
 return translatedStringsForCurrentLanf[Index];
}

**Comment by SzczepanPolska** [comment]
[
![image](https://cloud.githubusercontent.com/assets/16169053/17417881/e984b36a-5a95-11e6-9f0e-604a08151276.png)
](url)

**Comment by dktapps** [comment]
Removed an irrelevant spam comment. @SzczepanPolska read the text in red very carefully.

**Comment by dktapps** [comment]
I've made a hack for this on the network layer that works nicely.
