### ISSUE TITLE
Phar

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#1584]
Hello guys
I can't find Genisys 0.15.3 phar file

Can anyone give me the link? 

Thanks

**Comment by DubaiGamerXD** [comment]
...

**Comment by DubaiGamerXD** [comment]
Please give me the link :(

**Comment by gaoyichuan** [comment]
READ README

**Comment by DubaiGamerXD** [comment]
Where is readme?????

**Comment by GlitchPlayer** [comment]
I can see the README in the code tab -.-

**Comment by DubaiGamerXD** [comment]
Why should I read readme I already read it -.-

**Comment by HyGlobalHD** [comment]
You Should Read Carefully 
https://gitlab.com/itxtech/genisys/pipelines?scope=branches

**Comment by DubaiGamerXD** [comment]
Does not give me the 0.15.3 phar file..

**Comment by HyGlobalHD** [comment]
It support 0.15.0 ,0.15.1 ,0.15.2 ,0.15.3 ,0.15.4

**Comment by DubaiGamerXD** [comment]
No..  People say that the server is outdated

**Comment by DubaiGamerXD** [comment]
I'm on the 0.15.0 phar file

**Comment by HyGlobalHD** [comment]
that is plugin fault.
if u install custom alert plugin disable the outdate message or smth

**Comment by DubaiGamerXD** [comment]
I don't have custom alert plugin -.-

**Comment by dktapps** [comment]
Please take this discussion somewhere else. You're spamming my notifications.
