### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by MCITGAMER11** [iTXTech/Genisys#1588]
In Server.pro it shows Genisys has vLatest
Can u plz tell me which version is it exactly.

**Comment by ZedCee** [comment]
Without ever following the issue template or using grammatically correct sentences, it is difficult to help or understand you.  
  This is also not a forum for generalized questions.
Please use gitter.im or Mattermost for that.

Lastly, a sure fire way to know you're using the "latest" version of Genisys, is to just download the master phar from Gitlab.
