### ISSUE TITLE
No drop for Minecart

### ISSUE THREAD

**Issue by Dannyiy** [iTXTech/Genisys#1589]
#### Issue description

In survival, when we break the minecart. The minecart does no appear.
#### Steps to reproduce the issue
1. Get a Minecart (by command or crafting it)
2. Then, place it and when you break the minecart, it does not appear
#### OS and versions

- Genisys: 45f2ae08
- PHP: 7.0.3
- Server OS: Android
- Game version: 0.15.4 (protocol version 82)
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
...
```

(Sorry for my bad english)

**Comment by Dannyiy** [comment]
public function getDrops(){
		return [ItemItem::get(ItemItem::MINECART, 0, 1)];
	}

does not work too... (to Entity/Minecart.php)

**Comment by dktapps** [comment]
This is a known issue. That function is not currently used. This will be corrected at a later date.

**Comment by dktapps** [comment]
Will correct this problem in the process of upgrading entity API.

**Comment by thebigsmileXD** [comment]
Still unfixed?

**Comment by dktapps** [comment]
@thebigsmileXD I've been working on Project Phoenix and also 0.16, so no.
