### ISSUE TITLE
Default Permissions need OP to work

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1590]
#### Steps to reproduce the issue

Create a command that has default: true set USING A PLUGIN, then try to run it without OP

#### OS and versions
* Genisys: https://github.com/iTXTech/Genisys/commit/45f2ae0840c270cb22c4e9af43abe550c4112593
* PHP: 7.0.2
* Server OS: Ubuntu
* Game version: 0.15.4 Win10 AND PE

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Hmm. To the best of my knowledge nothing has changed that would cause this. Are you using a permissions plugin?

**Comment by Yoyu666** [comment]
@XFuryMCPE,pls gove more info to @dktapps

**Comment by TDMidkwhatisxd** [comment]
Many changed!! The lag is becouse genisys removed checkmovement! 
I told them if there is not checkmovement , there will be lag , nut noo !!! They still removed it!!
(i tested this)

So no wonder permissions are messed up :( , they mess up the sistem!

**Comment by XFuryMCPE** [comment]
PurePerms allows me to set default permissions, but they dont work without it. I put all commands in one class then setExecutor in the main class

**Comment by XFuryMCPE** [comment]
@dktapps

**Comment by dktapps** [comment]
@XFuryMCPE you don't need to ping me, I get notified for participating. And I suggest don't use PurePerms - it's a buggy piece of **** and the author never fixes the important bugs.

**Comment by legoboy0215** [comment]
Then what do you suggest? It is quite stable for me and default: true works for me though?

**Comment by XFuryMCPE** [comment]
I mean that's why I want to remove it. But default perms don't work for me ._.

**Comment by GlitchPlayer** [comment]
Then what perm plugin we shall use??

**Comment by 64FF00** [comment]
PurePerms is just like a BS you guys just need to stop using it... I was already thinking of taking it down from GitHub

**Comment by GlitchPlayer** [comment]
BS

**Comment by dktapps** [comment]
@64FF00 use a patched version that doesn't have that stupid bug in it that I PRed for

**Comment by 64FF00** [comment]
@dktapps Nah, I'd better just give up. It's just literally piece of shit now as you said... Why did you even make a patched version if you don't recommend it... *Pffffffffff*

**Comment by 64FF00** [comment]
JK, I'm gonna merge it asap... The thing is... I have a really important 'university entrance' exam in 3 months... So yeah... PurePerms sucks... and even my life sucks... *dies*

**Comment by dktapps** [comment]
@64FF00 the only reason I said it was a piece of **** is because of that bug. Apart from that it's served me well enough. I do apologize.

**Comment by legoboy0215** [comment]
@64FF00 Don't go suicidal. Wait. You already died. And I thought this is about default perms?

**Comment by ZedCee** [comment]
Looks like this issue related to plugins has just about wrapped up.   Not halting discussion, just closing the issue.

**Comment by 64FF00** [comment]
@dktapps Lol I'm sorry dood, I'll try to merge it asap as I said

**Comment by 64FF00** [comment]
Eh really sorry for going off-topic, but may I ask how many peeps are using Genisys compared to Nukkit? Just curious about it, I already know everyone's been using Genisys instead of PM

**Comment by dktapps** [comment]
@64FF00 if anyone has statistics, I don't know about them. :D

**Comment by legoboy0215** [comment]
People still use Genisys or PM the most.

**Comment by 64FF00** [comment]
@dktapps dood may i ask why do you think these should be added 
```PHP
if(!file_exists($this->getDataFolder() . "config.yml")){
    $this->saveDefaultConfig();
}
```

**Comment by 64FF00** [comment]
@dktapps I'm sorry but may I ask why you want to add this code
```PHP 
if(!file_exists($this->getDataFolder() . "config.yml")){
    $this->saveDefaultConfig();
}
```

Well you know... the `saveDefaultConfig()` function in [PluginBase.php](https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/plugin/PluginBase.php) already checks if the config file exists or not....

**Comment by dktapps** [comment]
@64FF00 well something is broken somewhere, because until I added that my configs were getting reset every startup

**Comment by legoboy0215** [comment]
Really? Nothing was getting reset for me though

**Comment by dktapps** [comment]
@legoboy0215 Try and set `disable-op` to false and restart your server. Then open the config again and read it.

**Comment by legoboy0215** [comment]
Ok.

**Comment by 64FF00** [comment]
@dktapps @legoboy0215 Weird... I'll take a look at it very soon

**Comment by dktapps** [comment]
:+1:
