### ISSUE TITLE
MCA causes lag

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1591]
#### Issue description

Alright, I was hosting a UHC today and I forgot to convert my world to MCRegion and I thought it would be okay. I had players join and play, and instantly everyone started spamming "LAG" and I looked at the server TPS and I saw it was 86% and converted my world because I knew MCA would be laggy. As soon as I put it to MCRegion the tps was down to its normal 26% with 60 players on
#### Steps to reproduce the issue

Use a world with mca and have people join it and look at tps
Use a world with mcr and look at tps
#### OS and versions

* Genisys: 45f2ae08
* PHP: 7.0.3
* Server OS: LXDE
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Striker209** [comment]
This is really interesting, I'm gonna check that for me :o

**Comment by Striker209** [comment]
How did you converted Anvil to MCRegion ?

**Comment by ZedCee** [comment]
@TheAppleGamer I'm about to run some tests myself, but there really shouldn't be lag issues with ```anvil```, in fact it should perform a little better by theory, as it is just ```mcregion``` with some patches: http://minecraft.gamepedia.com/Anvil_file_format

@Striker209 You can use [pmimporter](https://github.com/Muirfield/pmimporter/tree/dev) to convert to mcregion.  For more of a forum for generalized questions I recommend you use gitter.im or Mattermost and join our rooms, we like to keep our issue tickets work oriented.  Apologies.

**Comment by Striker209** [comment]
I just wanted to test what @TheAppleGamer said to see if I can reproduce the issue

**Comment by Muqsit** [comment]
@TheAppleGamer What was the current TPS? (not in percentage)

**Comment by ZedCee** [comment]
@TheAppleGamer There are several improvements to `anvil` that will always outperform ```mcregion```, primarily the handling of chunks, blocks, the format data size, and packet compression.  I did however find significant lag utilizing both formats at once.

There are a few ways you can try to improve performance:  
1. Entities are a huge draw of resources, disabling them will always bring improvements to speed.
2.  Plugins are another large culprit in causing lag, particularly passive plugins that run on users automatically.
3. A few tweaks to `pocketmine.yml`, will help.
4.  Sticking with one world format

One thing to always remember, the more lag your players have (and the more players you have in general), the more your server may begin lagging.  You can never benchmark on the consistency of 60 people, 60 various connections, and an unknown number of plugins, travel paths, exploring or build exercises.

If you have the bandwidth, raising `network: batch-threshold:` will reduce the amount of compression and improve performance.  Increasing the `chunk-generation:` queues will help in exploration.  While I find also, personally, increasing the `chunk-sending: max-chunks:` sent to a player for worlds with boundaries or little map generation can improve performance, increase the users cache, and reduce chunk calls in low exploration worlds.  
These are just a couple of things aside from increasing memory, disabling query and profiling.  Come over to gitter.im or Mattermost and you can get help.  Some of this may not be the best for your setup, platform, or general connectivity, many differences can happen DE to DE.

@Muqsit This sounds an awful lot like inadequate configuration, bandwidth, or the specs to handle the players.  One thing I noticed in my testing, the more worlds open, the more formats being read, the worse performance was.  Having both `anvil` and `mcregion` open at once caused significant lag on its own.

**Comment by ZedCee** [comment]
Hopefully this helps with understanding `anvil` a bit better and what some of the issues may be used along side `mcregion`.  Using more than one map type at a time definitely slows the server down.  
Perhaps there is a way to help reduce lag with better configuration; 60 players is quite a few.

If you need help looking into your configuration, again I recommend gitter.im, Mattermost, or even our IRC option.

**Comment by mhsjlw** [comment]
Ok, also, LXDE is not a server operating system it's a desktop :stuck_out_tongue_winking_eye:
