### ISSUE TITLE
MAP Cruhes

### ISSUE THREAD

**Issue by vcraftPE** [iTXTech/Genisys#1596]
#### Issue description
i uploaded pc map to my mcpe but when i tp to The spawn X Y Z my mcpe crush i uploaded 20 map and all same . i tested this maps in 14.x and it works fine
#### Steps to reproduce the issue i asked my friend about this and he said its Genisys 15.0 BUg

-->
* Genisys:lastest
* PHP:7.03
* Server OS:VGladiators
* Game version:15.4

**Comment by ZedCee** [comment]
#1206 

Please read previous issue tickets.
It is a client issue.  Also 'latest' is not technically a version, always refer to the commit number.  For future reference. Thank you.
