### ISSUE TITLE
What happened to checkmovement

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1597]
Build:Genisys 0ddc67f

PHP: 7.0.3
OS: Centos

Long ago, on version 0.14, i reported , that if i put ceckmovement false it lags!!
Lots of tryes to fix that , and finally checkmovement just wont work!!
Why i say that?
Lets make this test!
sky spawn is made from dirt and i will start to glich trough it!
Test1 ! 0.14 version genisys
On checkmovement true:
On Version 0.14 i dig in sky spawn dirt , im not falling , im still on spawn!!!
On checkmovement false:
I fall and die !! And server lags!! 
Test2. This build!!
Nothing much to say , i fall even if checkmovement is true or false :/!!!

Checkmovement was a great for anti-noclip and server tps (if true) !!

I never asked why was removed, leet still got checkmovement, becouse they forked this build, and i will do the same!!

**Comment by ZedCee** [comment]
I'm having a great deal of difficulty comprehending what you are try to say.

Much of the information provided is difficult to make sense of.

Please use the best grammatical sentences you can or we cannot help you.

**Comment by TDMidkwhatisxd** [comment]
--_--  !!
So !! Check movement dont work!!
Leet.cc forked a older build to keep check-movement !! 
___________________
Hope you understand that! Use google translate for this reply ;)  !

So ! You dont understand english !! Please dont read english issues if you are not able to read!!

Google translate cant make a sense of words, but you can try to get a ideea!!
______________
Please dont insult me , i saw here worse english comments ! So why you are rude for?

**Comment by ishitatsuyuki** [comment]
You are just using a lot of exclamation mark to make the things confusing. By the way, ZedCee is a native speaker, you are just not saying proper English.

**Comment by TDMidkwhatisxd** [comment]
Most rude genisys dev is on!!  --__--  !! So u hide something by closing this issue!! Ppl use "your grammar is bad" , wen they wanna avoid a question!
I will try to fix it by myself.

**Comment by ishitatsuyuki** [comment]
Hey, you are as same as using an alien language that we cannot understand. Here's your problems:  
* Non descriptive title
* Unclear description
* Many unneeded symbols
* Not following the template
* Poor formatting

Anyway, answering your questions, anti-cheat is basically not supported and buggy. We're planning to get rid of it, since it cause lag and can teleport player wrongly.
