### ISSUE TITLE
setAllowFlight() issue

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1606]
#### Issue description
You can't remove fly from players if they have flight already enabled.
#### Steps to reproduce the issue
Create an area!
if($x > 10 && $x < 20 && $z > 10 && $z < 20){
  $player->setAllowFlight(true);
}else{
  $player->setAllowFlight(false);
}

So when a player is in X = 10 to 19 and Z = 10 to 19, the player can fly. But when the player goes out of this area, the player's flight will be disabled. Although it works, the issue lies in disabling flight mode.
This has been an old issue in PocketMine. It's still being carried out.

**ISSUE**: When the player's allow flight gets disabled, the player cannot fly AND cannot move on the Y axis(cannot move up or down, just can go left, right, forward and backward).

#### OS and versions

* Genisys: All versions (check issue description)
* PHP: 7.0.8
* Server OS: Ubuntu 14.04 LTS
* Game version: 0.15.4

```

**Comment by dktapps** [comment]
This is not a Genisys issue. It's because of a giant hole in the MCPE protocol. Nothing we can do about it.
