### ISSUE TITLE
Server without default level

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#1607]
#### Issue description

I'm want to create server WITHOUT default level, example, I want to create minigame server with random map selection by plugin.

#### OS and versions

* Genisys: the latest
* PHP: 7.0.4
* Server OS: Windows/Linux
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
No questions here. Read the contribution guidelines.
