### ISSUE TITLE
Create synapse servers with random description

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#1608]
#### Issue description

I'm want to create many clones of one server with anything description to share it to database and transfer players there.

#### Steps to reproduce the issue

Add custom flag for "synapse.description", "random".

#### OS and versions

* Genisys: dedb804
* PHP: 7.0.4
* Server OS: Windows/Linux
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by XFuryMCPE** [comment]
"the latest" is NOT a version name. Please provide an actual version.

**Comment by Ishannaik** [comment]
how to find the version

**Comment by ZedCee** [comment]
@Ishannaik The version is the commit version number.  The Genisys.phar is typically labelled with it after unzipping the archive.zip.

**Comment by PeratX** [comment]
No. You can write a script to edit synapse description.
