### ISSUE TITLE
 Thunderstorm on a sunny day

### ISSUE THREAD

**Issue by samalero** [iTXTech/Genisys#1610]
#### Issue description

I noticed not the first time. The weather is sunny, but the sky flashes thunderstorms.

#### Steps to reproduce the issue

Watching ...
#### OS and versions

* Genisys: dedb804
* PHP: 7.0.6
* Server OS: Debian Jessie
* Game version: MCPE 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
This is not a bug.
