### ISSUE TITLE
Give glitch

### ISSUE THREAD

**Issue by Ishannaik** [iTXTech/Genisys#1613]
when some one uses /give the player has to relog to see his item or enchant

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by Ishannaik** [comment]
Genisys: 477c6b2
PHP: 7
Server OS: Windows 7
Game version: 0.15.4.0
