### ISSUE TITLE
Give Issue

### ISSUE THREAD

**Issue by Ishannaik** [iTXTech/Genisys#1614]
Genisys: 477c6b2
PHP: 7
Server OS: Windows 8
Game version: 0.15.4.0
When i /give the player a item or /enchant it takes a while to appear or player has to relog

**Comment by dktapps** [comment]
Thank you for spamming and **failing to follow the template.** Continue to spam and you'll be banned.

**Comment by Ishannaik** [comment]
WHAT DID I DO WRONG NOW??

**Comment by dktapps** [comment]
If you bothered to a), read the contribution guidelines, b), read the warnings in the issue template, and c) read my comments, you'd not need to ask.
