### ISSUE TITLE
Player back is nothing 

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1615]
Player back is nothing Every time when you login in server with gamemode 1.
Player need set other Gamemode and set to 1.

**Comment by ibookcc** [comment]
and than set to Gamemode 1

**Comment by ibookcc** [comment]
word spelling mistake : back to pack

**Comment by Striker209** [comment]
I don't understand a word of what you're saying

**Comment by Striker209** [comment]
Also please use and read the contributing guidelines

**Comment by ZedCee** [comment]
See `gamemode=` and `force-gamemode=` in `server.properties` or `player: auto-clear-inventory: false` in `genisys.yml`.

Note that this is not a technical issue with the server. 
It is a generalized setup question/user error.  
For further support I recommend you use gitter.im, Mattermost, or IRC.

**Comment by Gianluxx** [comment]
the problem is that if you are in gm 1 and you enter in the server your "creative inventory" is empty. (gamemode=0 , force-gamemode= off , auto-clear-inventory : false )
