### ISSUE TITLE
Wtf is your jenkins hosted on?

### ISSUE THREAD

**Issue by DelxHQ** [iTXTech/Genisys#1617]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
WTF is your jenkins hosted on?! its so slow!

**Comment by ZedCee** [comment]
Thanks.

**Comment by ZedCee** [comment]
Oh by the way, plain and simple this is spam.
Redirect questions to one of the offered chat networks; gitter.im, Mattermost, and IRC.
Read the contribution guidelines and the template before filling an issue.

**Comment by gaoyichuan** [comment]
If you have any faster machine, please donate it to us. Or don't do any more spam here
