### ISSUE TITLE
updateAround not work properly

### ISSUE THREAD

**Issue by dog194** [iTXTech/Genisys#1618]
#### Issue description

updateAround not work properly

#### Steps to reproduce the issue

1. put a Jungle wood
2. put 4 cocoBean around this wood.
3. break the Jungle wood.
You will find that only one CocoBean update properly.
#### OS and versions

* Genisys: 3c07347286e7cbca1ec38a695ef903968fa83dd7
* PHP:7
* Server OS:Win10
* Game version: MCPE0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

Reference:
 - 1 #1599
 - 2 https://github.com/PocketMine/PocketMine-MP/commit/781de3efabcd526281fd1adc8ce881d408471563
 - 3 https://github.com/PocketMine/PocketMine-MP/pull/4024

**Comment by dktapps** [comment]
I've observed the same thing with torches. Put a bunch of them on a block and break the block, only one of them updates.
