### ISSUE TITLE
Version mismatch between GitLab and Jenkins

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1619]
#### Issue description
We don't have 1.2dev-whatever anymore,as we now use a rolling release. The version number was removed because it is redundant. Why do Jenkins builds have it? This just adds to confusion in issues.

Something else (admittedly slightly off-topic): why the hell does Jenkins use a Windows build environment?

http://i.imgur.com/e4BsPLu.jpg

**Comment by ZedCee** [comment]
I agree entirely with this point.  1.2dev is nothing but a misdirection and slice of confusion for the users.  Especially users unfamiliar with git.  As this is rolling release, you need a versioning system that reflects that; Git commit hashes are the easiest go to.

**Comment by PeratX** [comment]
please check again.I have changed to git hash directly.

**Comment by dktapps** [comment]
:+1:
