### ISSUE TITLE
Client crash when hit by a entity

### ISSUE THREAD

**Issue by iVertx** [iTXTech/Genisys#162]
Well, i'm tryng out this server software, but got a bug related with entities

If I spawn two non-living entities with the same id of a player, to disquise then with that entity, if one of this entities (the player) hit another one also disguisted, the client that has been atacked will crash.

Seems that the client don't know what the hell are the entity that atacked him, and crashes, because the entity isn't even a living entity, (is a falling sand for be specific).

**Comment by PeratX** [comment]
Not living entity attack crashes the client.
