### ISSUE TITLE
Can enchant items with mods

### ISSUE THREAD

**Issue by fycarman** [iTXTech/Genisys#1626]
#### Issue description
As the title say,you can enchant your items with mods (like AlphaHack).

#### Steps to reproduce the issue
Join the server with AlphaHack or other mods
Enchant an item with the mod's menu
#### OS and versions
* Genisys: 0e0db04
* PHP: 7.0.8
* Server OS: Ubuntu 14.04
* Game version: 0.15.4 alpha (protocol 82)

#### Crashdump, backtrace, memory dumps, plugins list or other files
![img_20160809_194706](https://cloud.githubusercontent.com/assets/12121120/17527411/8a874696-5e6b-11e6-8c59-c5b42538aee0.jpg)

**Comment by dktapps** [comment]
You're several days out-of-date.

**Comment by fycarman** [comment]
This happens also on the last version,i only wrote the version i have on my test server

**Comment by dktapps** [comment]
Hmm. Would you like to test a build from the Win10 branch? I fixed a huge stack of bugs like this over there.

**Comment by fycarman** [comment]
Ok,i'll test.

**Comment by fycarman** [comment]
Just tested,mod won't work on windows 10 branch. This issue can be closed as the branch will be merged (soon?). Thanks @dktapps !

**Comment by dktapps** [comment]
Yeah, checkout #1621
