### ISSUE TITLE
Fix Asynctask for Query facade

### ISSUE THREAD

**Issue by DummyU8** [iTXTech/Genisys#1627]
Is it possible to get the Asynctask fixed for a plugin called QueryFacade by Viperize?

**Comment by ishitatsuyuki** [comment]
We don't provide plugin support. CLOSED INVALID

**Comment by GlitchPlayer** [comment]
So does genisys, wont provide support for plugins... Meaning genisys wanted no plugins?? I guess soo :/

**Comment by ishitatsuyuki** [comment]
No, issue tracker is not plugin support forum.

**Comment by GlitchPlayer** [comment]
But plugins uses genisys src. Some are genisys fault, some are plugins fault

**Comment by ishitatsuyuki** [comment]
Anyway, no details are provided. If you have any question, bring it to chat.
