### ISSUE TITLE
UUID class toString method invalid changing

### ISSUE THREAD

**Issue by nyankichi820** [iTXTech/Genisys#1628]
src/pocketmine/utils/UUID.php
class is wrong implement
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/utils/UUID.php#L97

use 
```
$player->getRawUniqueId()->toString()
```
uuid changing

example
```
aa34cf5a-dec2-394a-ad2a-04b88dcf3f7e
```
to
```
aa34cf5a-dec2-394a-8d2a-04b88dcf3f7e
```
changed

**Comment by gaoyichuan** [comment]
Closing for not following the template and unclear language. Also no support request here.
