### ISSUE TITLE
Anvils that fall cause no damage

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1629]
#### Issue description

I was messing around on a private server and I dropped an anvil on my head in survival mode and nothing happened
#### Steps to reproduce the issue

Get an anvil and drop it on your head is smode
#### OS and versions

* Genisys: a6d1d50
* PHP: 7.0.3
* Server OS: LXDE
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Yes, this is not implemented yet. I'm going to be upgrading various anvil behaviours soon, including crafting. Referencing #888 (generic Anvils issue)
