### ISSUE TITLE
FloatingTextParticle is broken (again)

### ISSUE THREAD

**Issue by sero583** [iTXTech/Genisys#1634]
#### Issue description

The FloatingTextParticle won't get added.
#### Steps to reproduce the issue

Create a FloatingTexctParticle
#### OS and versions

* Genisys:  fb2d504
* PHP: 7.0.3
* Server OS: srry idk, its a root server
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
bam, didn't even need a fix~

**Comment by sero583** [comment]
@Muqsit Well at our Server, i've never touched the code from the holograms (aka FTP (!!Not File transfering Protocol!!)) and after a update it seems to get broken again.
I dont know why, does this bug lays on my MC:PE client or on Genisys, because on Nukkit it doesn't works too... :/

**Comment by Tee7even** [comment]
>on Nukkit it doesn't works too...

*"It works in Nukkit too."
That is what you wanted to say, I think. ☺

**Comment by sero583** [comment]
@Tee7even could you send me a jar where it works, i want to see if im stupid or it really doesnt work...
Please put the SRC into the zip too pls, i get headache from that...

**Comment by Pub4Game** [comment]
@sero583 

https://1278-36117051-gh.circle-artifacts.com/0//tmp/circle-artifacts.am70Xgy/nukkit-1.0-SNAPSHOT.jar

**Comment by Tee7even** [comment]
@sero583 [Click.](https://github.com/iTXTech/Genisys/files/413725/NotFileTransferProtocolTest.zip)

**Comment by Muqsit** [comment]
It does work @sero583. Chances could be the plugin you are using might not be working or was coded for an old API.
