### ISSUE TITLE
Feature request: Update to php7-leveldb!

### ISSUE THREAD

**Issue by Striker209** [iTXTech/Genisys#1636]
As I asked @reeze to update the php-leveldb package, it's now compatible with php7!

https://github.com/reeze/php-leveldb/

BIG BIG THANKS to @reeze!

I notice you about that because people that would like to run MCPE Maps directly on Genisys could thanks to this package!

EDIT: GO to the "PHP7" branch

**Comment by ishitatsuyuki** [comment]
Well, we refrain from installing non-release things. Can you ask him also to make a release to PEAR?

**Comment by Mgl64200** [comment]
It's cool, but I don't know how to Install it how do I do please ?

**Comment by Striker209** [comment]
@ishitatsuyuki I asked, but we'll have to wait some time until we get a response

**Comment by reeze** [comment]
Hi  guys,

There are some bugs need to be fixed after migrate to PHP7 before I can release it. I will release it ASAP when I have time to fix them.

**Comment by Striker209** [comment]
Thanks a lot reeze! You are bringing a lot to the MCPE Universe :D
