### ISSUE TITLE
chest don't open in creative mode 

### ISSUE THREAD

**Issue by AliMAltamimi** [iTXTech/Genisys#1637]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by dktapps** [comment]
I might also add that this is intended and can be changed in genisys.yml. Switch `limited-creative` to `false` and restart your server.

**Comment by AliMAltamimi** [comment]
why closed, i wrote everything

**Comment by ZedCee** [comment]
Thank you for updating the issue ticket.  We appreciate that.  As mentioned by @dtkapps, there is an option in genisys.yml  
This should solve your issue.  Thus the ticket will remain closed.  
For general questions regarding setup, a potential issue that you are unsure is an issue, or anything that is not the vanilla functioning of the server, we recommend you come to one of our forums: Gitter.im, Mattermost, or IRC.

**Comment by GlitchPlayer** [comment]
Such a nice descriptive issue you say?
