### ISSUE TITLE
Max Chunks Radius

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1638]
Version:Genisys c19e850 
How to reproduce: Try to set chunk radius to lower!
_____________

I have a problem ! Too many chunks spawn around players, i dont know how many , but there are ... a lot!

I put radius from genisys.yml to 2 .
I set max chunks in pocketmine.yml to 28 .

After i updated to latest , it seems that it does not have any effect anymore!
Please have a look.

(I Hope you understand what im trying to say :p )

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by TDMidkwhatisxd** [comment]
I think i sent enough info!
And how error occured:  Wen you walk , and map start loading :D  !

I ask you just to check if something is wrong! Is not a critical issue or something . I know you are bussy!

**Comment by dktapps** [comment]
Lower `max-chunks` and `spawn-threshold` in pocketmine.yml

**Comment by TDMidkwhatisxd** [comment]
Both are to 28
