### ISSUE TITLE
How to Install Genisys

### ISSUE THREAD

**Issue by Nidish** [iTXTech/Genisys#164]
Help me installing Genisys .. Running Windows 8 32 Bit.
If possible a zip file without .sh world be good .
Thanks in advance

**Comment by MilkoIvanov** [comment]
I don't see how are you going to manage a server when you don't even know how to install it. In answer just download the Genisys-master and the php7 from Genisys-PHP, extract them both, then find and install php7 from the Genisys-PHP zip file then just run the start.cmd. I think that's it :D

**Comment by Nidish** [comment]
Well i tried that

**Comment by PeratX** [comment]
@Nidish You can get all files for windows x86 here http://windows.php.net/downloads/pecl/releases/

**Comment by Nidish** [comment]
@PeratX Thanks I will wait :)

**Comment by PeratX** [comment]
@Nidish It is available now! Here https://github.com/iTXTech/PHP-Genisys/tree/master/php7/7.0.2_win32

**Comment by Nidish** [comment]
@PeratX Thanks

**Comment by Nidish** [comment]
Can this be closed ? @PeratX

**Comment by PeratX** [comment]
Yes

**Comment by wiligangster** [comment]
How To install php7 linux ?

**Comment by PocketKiller** [comment]
@wiligangster https://github.com/iTXTech/PHP-Genisys

**Comment by wiligangster** [comment]
Problem error is: Could'nt find a working PHP Binary, please use the installer ?
