### ISSUE TITLE
skeletons, creepers, sheeps, pigs dont spawn if i set mobs spawning on

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#1640]
#### Issue description

skeletons, creepers, sheeps, pigs dont spawn if i set  mobgenerate on

#### Steps to reproduce the issue

set  mobgenerate on
and play

#### OS and versions

* Genisys: #24 (jenkins)
* PHP:7.0.4
* Server OS: OS X El Capitain
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
This will be changed when Mob AI is rewritten.
