### ISSUE TITLE
Server::getLevelByName not working.

### ISSUE THREAD

**Issue by xBeastMode** [iTXTech/Genisys#1641]
The method `Server::getLevelByName()` is not working. I just realized it. When I var_dump the result, I get an empty level object.

**Comment by ishitatsuyuki** [comment]
Improperly Formatted Issue Ticket - Lacks Information
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by xBeastMode** [comment]
# Issue
The method `Server::getLevelByName()` is not working. I just realized it. When I var_dump the result, I get an empty level object. The error is when I try to loop all the level signs it says `Warning: Invalid argument supplied for foreach() in C:\Users\*****\Downloads\PocketMine-MP\plugins\HungerGames\src\hungergames\lib\mgr\SignManager.php on line 93`.

# Server info
OS: Windows 10
PHP Version: 7.0.3
Genisys: Genisys-0ddc67f "Kyrios" (API 2.0.0)

# Code
Game Level it self:
`$this->gameLevel = Loader::getInstance()->getServer()->getLevelByName($game->get("game_level"));`
`foreach($game->getSignList() as $tile){}`

![capture00](https://cloud.githubusercontent.com/assets/16060686/17651656/7eea7f70-6220-11e6-97ac-44f9dcf0de02.PNG)

**Comment by ishitatsuyuki** [comment]
There is no class named `Loader`. You haven't checked if the supplied name parameter is valid or not.

**Comment by xBeastMode** [comment]
That is because `Loader` is the main class (plugin base). The supplied name is from a config string. Even by doing it with a valid string `getLevelByName('world')`, it returns a empty level object.

**Comment by ishitatsuyuki** [comment]
Easy, your instance is just invalid.

**Comment by xBeastMode** [comment]
Nope. Even tried accessing the function via delayed task, it still points empty level object. Here is an example of how I am doing it:
```PHP
<?php
namespace hungergames\tasks;
use hungergames\Loader;
use pocketmine\scheduler\PluginTask;
class VarDumpLevel extends PluginTask{
    /** @var Loader */
    private $HGApi;
    public function __construct(Loader $main){
        parent::__construct($main);
        $this->HGApi = $main;
    }
    /**
     * @param $currentTick
     */
    public function onRun($currentTick){
       var_dump($this->HGApi->getServer()->getLevelByName("world"));
    }
}
```
output:

```
object(pocketmine\level\Level)#11794 (0) {
}
```

**Comment by ishitatsuyuki** [comment]
Please ask in chat. We don't have any issue with that.
