### ISSUE TITLE
Feature Request: Xbox function

### ISSUE THREAD

**Issue by MCPEPIG** [iTXTech/Genisys#1642]
#### Issue description

Could you please add a function for checking whether or not a player is using xbox? Look here: https://github.com/ClearSkyTeam/ClearSky/commit/b2baec8510e35009c238f4e1bf04b0cd428bfffb
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Yes, this is planned.

**Comment by TDMidkwhatisxd** [comment]
Cool ! We can make plugin to kick a player if is not using xbox!
And say bye to cheaters , and bad players :3  !

**Comment by TDMidkwhatisxd** [comment]
Enchants can be hacked! :(  just saw some players with protection 10000 enchant lol

**Comment by Muqsit** [comment]
Please stop bumping with more and more issues. Also, we do not provide any anti hacks and enchantments cannot be "hacked".

**Comment by ishitatsuyuki** [comment]
By the way, I think CS one isn't verifying the token and thus not reliable. I will implement with a verification.

**Comment by dktapps** [comment]
@Muqsit incorrect. Anti-cheat _is_ provided, but currently isn't worth the code it's written in. Items and enchantments _can_ **currently** be hacked in with apps like AlphaHack. . _My_ anti-cheat on Win10 branch, on the other hand... _that_ is powerful. My new anti-cheat there is bulletproof.

**Comment by robske110** [comment]
We are indeed not checking the key. This'll be a lot of work. And as we need to contact servers we cannot just do this onJoin. This would need an AsyncTask wich would either delay joining or kick players after they joined. I would say we just provide getXboxData() and getWebtokens() for plugins to check it themselves. But as you can see isXboxValid() also exists, and it was planned to do it over that way.

**Comment by ishitatsuyuki** [comment]
robske110: I have just done the impl of key checking. I'm still working on debug though.

**Comment by dktapps** [comment]
VOTE: Xbox Auth - on or off by default? Thumbs UP for ON, thumbs DOWN for OFF

**Comment by mhsjlw** [comment]
You need to support both.

**Comment by ishitatsuyuki** [comment]
@mhsjlw - said it's just a vote for default, and it's configurable. It's just a decision between the safety and user confusion.

**Comment by robske110** [comment]
And to why OFF by default: It was always like this. It may confuse some players and it may especially for small servers with server owners bot aware of the change be fatal, beause they'll loose players. For me there is no reason for the option to be enabled by default.

**Comment by dktapps** [comment]
@robske110 your reasoning is perfect, because it's the exact same as mine. XD

**Comment by mhsjlw** [comment]
@ishitatsuyuki, that's my vote. Support both by default. If the user wants online mode, then you can just kick players that aren't XBOX but both should be able to play by default.

**Comment by dktapps** [comment]
@mhsjlw that basically means off by default then.

**Comment by mhsjlw** [comment]
Sure. ;)
