### ISSUE TITLE
Console messages upon starting server

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1644]
#### Issue description

There are some server warnings and notices that pop up. I'm wondering if this could be related to everyone crashing upon joining also (the actual server doesn't crash, just the clients).
#### Steps to reproduce the issue

Start the server
Look through the console messages for when you first start the server
#### OS and versions

* Genisys: c19e850
* PHP: 7.0.8
* Server OS: Linux (Hosted by NetherBox)
* Game version: 15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
13.08 23:22:39 [Server] INFO Warning: Invalid argument supplied for foreach() in phar:///jar/genisys.phar/src/pocketmine/plugin/PluginDescription.php on line 116
13.08 23:22:39 [Server] Server thread/INFO Genisys is distributed under the GPL License version 3 and later
13.08 23:22:39 [Server] INFO sh: ifconfig: command not found
13.08 23:22:39 [Server] INFO sh: ifconfig: command not found
```

```
23:44:43 [Server] Server thread/INFO Plugins (36): CheckID v1.0-Alpha, RestartMe v1.2.0,
PocketGuard v2.1.1, EconomyJob v2.0.4, Broadcaster v1.16, FactionsPro v1.3.2, 
NoOpCMD_Prank v1.0.0, iProtector v3.1b, Slapper v1.2.9.5, EconomyAPI v2.0.9, MSpawns v1.5, WorldEdit+ v0.01, CapsLimit v1.1.0, 
TimerBan v2.1, SteakIt v3.0.0, WorldGM v1.1.0, 
ManyWorlds v2.1.0, ChatToolsPro v1, 1vs1 v0.0.5, CustomAlerts v1.6, BasicHUD v1.0.6, 
MoreCommands v1.1.4, BanItem v2.2, AlwaysSpawn v2.2.2, BlockSniffer v1.0.0, NetherChests v1.1.1, SimpleAuth v1.7.2, ClearLagg v1.1.0, PurePerms v1.3.7, BlockCmdPE v1.0.1, 
WordBlocker v1.0.0, SimpleAuthHelper v2.0.4, SimpleWarp v2.1.1, MyPlot v1, PureChat v1.4.0, SimplePortals v0.0.5
```

**Comment by GlitchPlayer** [comment]
Invalid argument supplied for foreach() in phar:///jar/genisys.phar/src/pocketmine/plugin/PluginDescription.php on line 116

One of your plugins has problems in descriptions.Try removing each one of them until you find the plugin

**Comment by Muqsit** [comment]
Your probably using multicraft (ifconfig error).
