### ISSUE TITLE
Spawn Egg names

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1649]
#### Issue description

All spawn eggs say "Spawn Egg" upon tapping on them in Creative mode, instead of saying which kind of egg they are (it does say the appropriate name for a split second, and then changes to Spawn Egg). 
#### Steps to reproduce the issue

Go in Creative mode
Tap a spawn egg and look at the popup. 
#### OS and versions

* Genisys: c19e850
* PHP: 7.0.8
* Server OS: Linux (Hosted by NetherBox)
* Game version: 15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
https://youtu.be/muPLRY8Ftt0
(video of bug, look at spawn egg names)
```

**Comment by dktapps** [comment]
Plugin issue or Netherbox issue. This is not reproducible. Closing.
