### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Artur0022** [iTXTech/Genisys#165]
The sign does not retain text...

**Comment by flaxues** [comment]
Try to place a block at place of a sign break the block and place the sign again.

**Comment by Artur0022** [comment]
@flaxues sign does not retain text

**Comment by MilkoIvanov** [comment]
Have this issue on both php5 and php7 repos, and I don't see what's the problem

**Comment by Artur0022** [comment]
я тоже не видел пока не вышли обновления выше 24
