### ISSUE TITLE
Feature request: ServerShutdownEvent

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1651]
Could this be added? So, for example, I could transfer all players to a backup server when the server shuts down. This could be used for many other things too, but that was just a quick example

**Comment by GlitchPlayer** [comment]
I think it would be hard. Like in kick event. Before the kick message are
sent to client. The disconnect event will be sent first before the message
are sent.

**Comment by robske110** [comment]
huh? just use PlayerKickEvent

**Comment by robske110** [comment]
And i think there is a reason why this doesn't exist. The shutdown period is one of the most unstable situations you can find PocketMine in. Segfaults everywhere.

**Comment by ishitatsuyuki** [comment]
@robske110 *Before* it shuts down is OK. However, we should discuss if this is necessary.

**Comment by robske110** [comment]
and we should not break more and more and more plugin compabilty. Plugins start to be labeled as CS or Genisys.

**Comment by dktapps** [comment]
@robske110 This won't break a thing. It's the addition of _extra_ functionality.

**Comment by xBeastMode** [comment]
Indeed. Plugins with this new event would have to be renamed for/to Genisys, since it wouldn't exist in other server software, like PocketMine-MP.

**Comment by XFuryMCPE** [comment]
This is a PocketMine FORK, features don't need to be the same. PocketMine doesn't have potions, mobs, or fishing, but those are in genisys too, right? @xBeastMode

**Comment by robske110** [comment]
That is one thing. Making plugins break on original pocketmine due to unnecessary events. This event has very less usage.

**Comment by ishitatsuyuki** [comment]
Please do it on plugin unload. Server shutdown is not reliable and thus should not be a part of API.

**Comment by dktapps** [comment]
I might also add that a cancellable ServerShutdownEvent is a very dangerous idea. You don't want cancellable shutdown in the event of a crash.

**Comment by XFuryMCPE** [comment]
I bet this would be added if I wouldve "squashed my commits" but whatever I guess. And don't plugins un load after players leave @ishitatsuyuki ?? I can't do anything with the players on shutdown if that's the case, so that's pountless. @dktapps , Cancellable could be removed easily if you would've let me know before the issue was closed. I don't understand how it's not 'reliable' either, because im currently using ServerShutdownEvent in my own build and it works perfectly fine with no problems at all.

**Comment by XFuryMCPE** [comment]
Pardon my spelling mistakes, I rushed the message.😒😒

**Comment by ishitatsuyuki** [comment]
```
			$this->getLogger()->debug("Disabling all plugins");
			$this->pluginManager->disablePlugins();
			foreach($this->players as $player){
				$player->close($player->getLeaveMessage(), $this->getProperty("settings.shutdown-message", "Server closed"));
			}
```
Okay, what were you thinking about?

**Comment by XFuryMCPE** [comment]
It was a question
