### ISSUE TITLE
win10 MC Can not create item

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1652]

**Comment by ishitatsuyuki** [comment]
Provide details - or you will be banned.

**Comment by ibookcc** [comment]
@ishitatsuyuki 
这个问题很严重，
This problem is very serious, 
win10，xbox版无法分解以及合成物品，包括在背包，以及合成台
Win10, Xbox version can not be broken down as well as synthetic items, including in the backpack, as well as the synthesis of Taiwan 
请尊重我，谢谢，我提的问题都是很严重的bug
Please respect me, thank you, I mentioned the problem is very serious bug

**Comment by ibookcc** [comment]
@ishitatsuyuki And i just want yours fix this bug.No malice.

**Comment by ishitatsuyuki** [comment]
We already have fixes in the w10 branch - I couldn't respond because you filed an issue with only a incomprehensible title.

**Comment by dog194** [comment]
@ibookcc  你在要求受到尊重的时候有没有想过，你之前开的数个issue全部被关，并且在我们提示你无论反馈啥都需要按照 issue提供的一个模板进行问题反馈前提下依旧 你行你素 的以你的习惯开issue。你都没有尊重现在既定的要求，为何还在此要求受到尊重？
Respect should be mutual, so you should update the ticket first.

Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by dktapps** [comment]
#1621 fixes this problem, awaiting review. You're welcome to try a beta build from the `w10-done-properly` branch.

**Comment by ibookcc** [comment]
@dog194 sorry i ignored it. :( please forget.
