### ISSUE TITLE
玩家移动检测的某些问题

### ISSUE THREAD

**Issue by yhzx233** [iTXTech/Genisys#1654]
在genisy.yml关闭check-movement后如果再出现穿墙等现象后的确不会pull back玩家，然而不拉回并不意味着在服务器里不会检测玩家的移动，原本应该拉回的情况关闭这个设置后玩家实际上还是卡着的
掉下虚空有些时候会被无限拉回
穿过展示框时会被拉回
旁观者模式下导致的穿墙同样不被服务器承认

**Comment by dog194** [comment]
你需要按照模板填写详细东西，不然会直接被无视。

**Comment by Striker209** [comment]
Bruh

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
