### ISSUE TITLE
饥饿度与饱食度

### ISSUE THREAD

**Issue by yhzx233** [iTXTech/Genisys#1661]
#### Issue description

服务器里玩家没有饱食度(foodSaturationLevel)，就是不会溢出。

[Google Translate] 
Server where players no satiation (foodSaturationLevel), is not overflow.

#### OS and versions

* Genisys: [5dab58](https://gitlab.com/itxtech/genisys/commit/5dab58d3939b86deb79fb5606c83ba978593ec14)
* PHP: 7
* Server OS: Centos
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Cannot understand.
