### ISSUE TITLE
Can not pass the event to plugin

### ISSUE THREAD

**Issue by FUGAMARU** [iTXTech/Genisys#1663]
#### Issue description

I use a translation site.

When PlayerChatEvent is carried out in plug in, "**[Server thread/CRITICAL]: "'Ayaka v2.0.0'に'pocketmine\event\player\PlayerChatEvent'Eventを渡すことができませんでした: Ayaka\AyakaでのClass Ayaka\Exception not found"
[17:49:04] [Server thread/CRITICAL]: ClassNotFoundException: "Class Ayaka\Exception not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144**" and an error will be displayed.
However, this error is not displayed in my PC(Windows10 Home 64bit).
When I carried out this plugin in VPS(Ubuntu 14.04 LTS 64bit), an error is displayed.
The cord of the plugin is totally same as both, too, and the commitment version of Genisys is same as, too.
So I think that plugin does not have a problem.
A developer of this plugin is me.
#### Steps to reproduce the issue

I would like the downloading of the plug in from a lower link
API Key described in plug in removed it. I'm sorry.
https://www.dropbox.com/s/envg130hsq1376f/Ayaka.zip?dl=0
#### OS and versions

* Genisys:https://github.com/iTXTech/Genisys/commit/5dab58d3939b86deb79fb5606c83ba978593ec14
* PHP:7.0.2
* Server OS:Ubuntu 14.04 LTS 64bit
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
It's just your plugin problem, contact the author or talk in chat.
**No questions.** Next time you doing this will cause in a ban.

**Comment by FUGAMARU** [comment]
Why do you think so?

**Comment by ishitatsuyuki** [comment]
https://www.google.com/search?q=php+class+exception+not+found
Shut up before I start to scold you.
