### ISSUE TITLE
Error while crafting

### ISSUE THREAD

**Issue by attichicco** [iTXTech/Genisys#1665]
Notice: Undefined offset: 0 in C:\Users\MyUser\Documents\PocketMine-MP\src\pocketmine\Player.php on line 3336

i am using genisys phar (not actually a phar but i intend all the src files) on pocketmine

everything works fine except crafting, no problem going around or breaking blocks, also when you switch to creative mode your inventory is completly cleared.

here is the server
[PocketMine-MP.zip](https://github.com/iTXTech/Genisys/files/420073/PocketMine-MP.zip)

**Comment by dktapps** [comment]
Improperly Formatted Issue Ticket

#1621 fixes this, waiting to be merged. You may use the Win10 Beta branch for the time being.
