### ISSUE TITLE
open ssl

### ISSUE THREAD

**Issue by zFellowZ** [iTXTech/Genisys#1670]
#### Issue description

How to get Open ssl? 
How
#### Steps to reproduce the issue

Download lastest one, start it and it will give u an error. It's cause of the XboxAut thing :/ 
#### OS and versions

* Genisys: Lastest
* PHP: 7
* Server OS: Ubuntu 14.04
* Game version:  lastest one

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
You don't properly write version, and don't read README. Who would like to help such a lazy bone?

**Comment by zFellowZ** [comment]
@ishitatsuyuki  This issue has already been solve (from read me).  Such a fgt you are eh?

**Comment by ZedCee** [comment]
@zFellowZ That kind of language and rudeness is not tolerable.  You will get banned if you persist.  Further more, read the contribution guidelines; issue tickets are not for general questions, always check the README first for changes, then resource the multiple chat networks we are on.
