### ISSUE TITLE
Random lightning strikes everywhere

### ISSUE THREAD

**Issue by robske110** [iTXTech/Genisys#1671]
#### Issue description

Lightning strikes occur while weather seems clear (no rain)

#### Steps to reproduce the issue
Just wait for a lightning strike to occur while no rain or whatsoever falls
Even after entering /weather clear it still occurs

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/f1b6d5c5fa6147543f94eb78a9b3d6c1a0c5af53
* PHP: 7.0.3 custom 
* Server OS: Ubuntu 16.04 (broken X)
* Game version:  0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
-/-
```

**Comment by xZeroMCPE** [comment]
Yeah, confirmed. I had a flat world. And the weather was clear and lightning would hit (strike) the ground randomly.... Even though it was clear -_-
