### ISSUE TITLE
Some bug

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1672]
1. 金合欢木树叶撸掉掉橡树树苗
2. 物品展示框放入附魔物品取出后附魔效果会丢失
3. 地狱孢子长好后只会只掉落一个
4. Window10版 MC 无法制作或者分解物品 无论是背包还是工作台都这样
5. 指令'/status' or '/gc' or ‘makeplugin’ 丢失无法使用（不知道是不是特性）

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by ibookcc** [comment]
@dktapps 
Can you just tell me, I will try to match you, rather than the simple closure of the issues.
Close but not want to know.
Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux
