### ISSUE TITLE
Some bug

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1673]
Can you just tell me, I will try to match you, rather than the simple closure of the issues.
Close but not want to know.
Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux

1. 金合欢木树叶撸掉掉橡树树苗  
??? tree drops oak sapling
2. 物品展示框放入附魔物品取出后附魔效果会丢失  
putting item in frame cause the ench to lost
3. 地狱孢子长好后只会只掉落一个  
nether wart only drops one
4. Window10版 MC 无法制作或者分解物品 无论是背包还是工作台都这样  
w10 issues. already fixed.
5. 指令'/status' or '/gc' or ‘makeplugin’ 丢失无法使用（不知道是不是特性）  
these commands missing. either removed or typo.

**Comment by dktapps** [comment]
The PR for Windows 10 Edition support has just been merged.

**Comment by Leo3418** [comment]
`/makeplugin` is a (DevTools) [https://github.com/iTXTech/Genisys-DevTools] command. Since Genisys does not integrate DevTools anymore, you have to download DevTools to use it.
To enable `/status` and `/gc`, you must edit `pocketmine.yml` like this:
```yml
#Enables /status, /gc
 commands: true
```

**Comment by ibookcc** [comment]
@Leo3418 About /status and /gc , but i enable this, and check many times.

**Comment by ibookcc** [comment]
@PeratX Thank you.

**Comment by dktapps** [comment]
The Nether Wart bug is a client rendering bug. Reference: https://bugs.mojang.com/browse/MCPE-11796
