### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1675]
#### Issue description

[21:45:23] [Server thread/CRITICAL]: Error: "Call to undefined function pocketmine\utils\openssl_random_pseudo_bytes()" (EXCEPTION) in "/src/pocketmine/utils/Utils" at line 438

#### Steps to reproduce the issue

idk

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/78f41edcb7f980bf805164df3a17e1f5993145b8
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: win10 + android

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

I have OpenSSL installed and it is not working. Idk if i did it wrong or something.. You should add an installation tutorial somewhere.

**Comment by XFuryMCPE** [comment]
Maybe this should be reverted? Because if you don't have online-mode on it is unnecessary. https://github.com/iTXTech/Genisys/commit/58a2cea3286448e1fe8f996bfde0ae9c8a8e9289

**Comment by ZedCee** [comment]
We have some resources available in our wiki and announced on our README.md
https://github.com/iTXTech/Genisys/wiki/FAQs
Have you checked these new resources yet?

**Comment by XFuryMCPE** [comment]
Whoops, I didn't know that existed. Testing that out now.

**Comment by ZedCee** [comment]
Awesome!
Still pretty new.
I'm going to close this off for now
If you find you're having the same problems, just check back in.

**Comment by XFuryMCPE** [comment]
Didn't work, :(

**Comment by gaoyichuan** [comment]
You should install openssl php extension, not openssl itself.

**Comment by XFuryMCPE** [comment]
How..?

**Comment by ishitatsuyuki** [comment]
Read docs before spamming. You know, ask these in chat.
