### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by flash586** [iTXTech/Genisys#168]
what kind of package update in linux pthreads? please specify
![screenshot_20160126-044440](https://cloud.githubusercontent.com/assets/14042336/12571213/93e76d8e-c3e7-11e5-88ac-97202f81e8b4.png)

**Comment by flash586** [comment]
Crash
![screenshot_20160126-044539](https://cloud.githubusercontent.com/assets/14042336/12571223/ab78ad8c-c3e7-11e5-9113-7e5bf138964d.png)

**Comment by flash586** [comment]
Or this bug of core?

**Comment by PeratX** [comment]
@flash586 NO!!! Please use pthreads 3.1.x!!!

**Comment by flash586** [comment]
I upgrade this package libpthread-stubs0-dev. Whether you want to?

**Comment by PeratX** [comment]
@flash586 http://pecl.php.net/package/pthreads
