### ISSUE TITLE
Internal world name does not change after renaming worlds/world folder

### ISSUE THREAD

**Issue by ZizzyZizzy** [iTXTech/Genisys#1680]
#### Issue description
If you have a world named "world2", or whatever, then stop the server, rename the worlds/world2 folder to something else, then start it back up again, plugins still see "world2" for the world name. As does server.log. 

This causes problems with plugins like EssentialsPE that save the world name in the Warps.yml and Homes.yml files. They work fine until the server is restarted, then the warps that were previously saved are "missing" because the world name in the .yml file doesn't match what Genisys thinks is the name of the world.

Google search phrase:
EssentiaslsPE warps deleted or missing after restart (not really an EssentialsPE problem.)

#### Steps to reproduce the issue
Stop the server
Delete worlds/*
Start the server
Let it generate a new world with whatever name you have configured in server.properties (we'll call it "world" for this example)
Stop the server
Rename **worlds/world** to **worlds/FactionsWorld**
Start the server
Join the server. Notice in the server.log file that it clearly says "world" instead of "FactionsWorld" when players join.
Use EssentialsPE or any other plugin that stores the world name in one of its yml files. Set a warp or a home, or a permissions per world, then restart the server.
Try to use the same feature of the same plugin (warp, home, perm per world) and notice that it no longer works. Check the .yml file and you'll see the world referred to as "world" instead of "FactionsWorld"

#### OS and versions
* Genisys: 17.08 18:58:13 [Server] Server thread/INFO Target client: Minecraft PE v0.15.4 alpha (protocol version 82)
17.08 18:58:13 [Server] Server thread/INFO API: 2.0.0 (iTX API version 1.8.0)
17.08 18:58:13 [Server] Server thread/INFO PHP version: 7.0.3
17.08 18:58:13 [Server] Server thread/INFO This server is running Genisys-unsupported-831a443 (codename "Kyrios")
* Server OS: CentOS 6.7

#### Crashdump, backtrace, memory dumps, plugins list or other files
N/A

On a side note, perhaps this is not a bug, but this is NOT the behavior of an Anvil world stored on a Minecraft PC server. You can rename a PC world to whatever you like and this does not happen.

**Comment by ImagicalGamer** [comment]
The worlds name is different than the worlds folder name, you can edit that with the "lvdat" command.

**Comment by ZizzyZizzy** [comment]
Neat! Thanks for that.

**Comment by ZedCee** [comment]
@ZizzyZizzy Has this helped resolve your issue?  The PC functions have been noted and our local PC-purist assigned.  Otherwise if you're worlds renamed we can close this issue.
