### ISSUE TITLE
Built-in spawn-protection doesn't work.

### ISSUE THREAD

**Issue by psycholyzern** [iTXTech/Genisys#1681]
#### Issue description
spawn-protection wont work. I set it to any amount and I still can destroy blocks whether Im op or not.
Relogged, restarted, used different account, reinstalled, issue still persist.

#### Steps to reproduce the issue
spawn-protection=30
Any amount still wont make it work

#### OS and versions

* Genisys: d08bff9 
* PHP: 7.0.9
* Server OS: Debian 8
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
No log produced regarding this issue.
```

**Comment by ZedCee** [comment]
Spawn protection appears to be working on my end. 
Do you happen to use any plugins?  World protection plugins may conflict.

Can anyone else recreate this?

**Comment by psycholyzern** [comment]
No plugins. As you may not know, I am new to this. These is what I did:
-I cloned the git, built php, and grabbed latest phar file. 
-Then went through wizard, server started. I logged in and I can destroy blocks around me.
- So I flew to another spot and /setworldspawn at that spot, then modified spawn-protection to other value.
- Stopped and re-run server, I still can destroy blocks around me.

I have tried as op and not as op, I can destroy blocks in both role.

**Comment by dktapps** [comment]
Cannot reproduce. Windows 10 hosted server with PHP 7.0.9 and Pocket Edition. Spawn protection works just fine for me.

**Comment by Striker209** [comment]
Some things you have to check :
- Be sure NOT TO BE an op
- Be sure that you're at the real spawn map location (otherwise use /setworldspawn as op player)
- Be sure your server.properties is not broken (delete it and restart your server)

If none of those steps worked, create a new directory, install Genisys in it and test!

**Comment by FaanMaario** [comment]
I have the same issue.

**Comment by caspervanneck** [comment]
disable toolbox for mcpe and it dont if you have op @psycholyzern

**Comment by NML32** [comment]
weird I was having that issue until I deleted my ops.txt file and let it recreate.

**Comment by NML32** [comment]
Ok, I spoke too soon ppl are able to place and break in spawn protection again.

**Comment by psycholyzern** [comment]
This issue seems to happen randomly to me when I changed spawn-protection value and restart genisys. So, right now, Im using the value that working right bow.  I guess I would be fine if I didnt change and restart genisys again.

**Comment by NML32** [comment]
Just realized that OP group in PurePerms isn't enough to build in spawn. Now you have to add OPs back to ops.txt before they can build in SP area.

**Comment by starterdragon** [comment]
Spawn protection does work on my server.

**Comment by psycholyzern** [comment]
Now I sticked to 20blocks of spawn-protection. It would be messed up if I changed and restarted genisys. This issue is solved temporarily for me, so I this issue closed until any further issue.
