### ISSUE TITLE
Entity and Block 

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1682]
液体(包含Lava和Water)是属于方块还是实体

Liquid (including Water and Lava) is a box or entity 

在放置的时候 BlockPlaceEvent 不会触发

BlockPlaceEvent will not be triggered when placed 

但是 EntitySpawnEvent 触发了但是 液体(包含Lava和Water)

But EntitySpawnEvent triggers the liquid (including Lava and Water). 

属于Block文件所以应该是方块。此处矛盾

Belongs to the Block file so it should be a box. Contradiction here

**Comment by ishitatsuyuki** [comment]
The EntitySpawnEvent is not triggered. They are not placed but created using a bucket, thus you should use another event corresponding to that.

**No questions here.** Beware a ban.

**Comment by ibookcc** [comment]
@ishitatsuyuki 谢谢,我想了很久都没搞懂,
