### ISSUE TITLE
PlayerChatEvent bug

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#1683]
#### Issue description

chat server displays a message, and then my message
It should be the other way around
https://pp.vk.me/c637927/v637927617/65eb/shs_9Lw88Cg.jpg
for example:
public function onChat(PlayerChatEvent $event){
$message = $event->getMessage();
if($message == "hi"){
$this->getServer()->broadcastMessage("hi");
}
In chat:
 hi
 MrDoni98 > hi

#### OS and versions

* Genisys: Genisys (codename "Kyrios")
* PHP: 7
* Server OS: ubuntu
* Game version: 0.15.6

**Comment by MrDoni98** [comment]
![shs_9lw88cg](https://cloud.githubusercontent.com/assets/10742315/17771839/3c0c0a58-6567-11e6-85de-c2ba6ac95057.jpg)
Blue message it's server message, next message it's my

**Comment by ishitatsuyuki** [comment]
Strange. Is it always or occasionally?

**Comment by MrDoni98** [comment]
always

**Comment by dktapps** [comment]
Player chat won't be sent until the event has been processed. So if you're sending the broadcast during the event, the broadcast will be sent first.

**Comment by MrDoni98** [comment]
what to do then?

**Comment by ishitatsuyuki** [comment]
This is the correct behavior. Closing.
