### ISSUE TITLE
PHP 7.0.9 with OpenSSL extension for Linux x64?

### ISSUE THREAD

**Issue by MrGenga** [iTXTech/Genisys#1685]
#### Issue description

I have tried to start new Genisys with old bin, it needs openssl, I tried to compile new bin with build script, starting... after loading properties I had zend_mm_heap corrupted. Any download link to precompiled binaries for Linux x64?
#### Steps to reproduce the issue

1. Compile php 7.0.9 with linux-build-install.sh
2. Try to start Genisys(after XBOX update!!!!).
#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/2ff7fac6aa6cf6ba58a0415f62314e0df85e48de
* Server OS: Ubuntu 16.04
* PHP: 7.0.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
You need to compile it yourself or use Docker. Please see the wiki for details.

**Comment by MrGenga** [comment]
@dktapps read my issue agaiin. I said, I already compiled and have zend_mm_heap corrupted!

**Comment by ishitatsuyuki** [comment]
You weren't patient enough to try some more times. It's a temporary issue caused by pthreads and can only solved by retrying.

**Comment by dktapps** [comment]
You've edited the ticket since I read it. Apologies for the misunderstanding.

**Comment by MrGenga** [comment]
@dktapps how to fix zend_mm_heap corrupted?

**Comment by ishitatsuyuki** [comment]
READ THE TEXT

**Comment by dktapps** [comment]
^ was literally just typing

**Comment by MrGenga** [comment]
@ishitatsuyuki i tryed 4 times, same issue

**Comment by ishitatsuyuki** [comment]
Try 20 times. Seriously.

**Comment by Frago9876543210** [comment]
Лол, Рауль на гитхабе :/

**Comment by NML32** [comment]
Is there any place to download php with ssl already compiled for Linux?  I'm having such a hard time with this.

**Comment by ishitatsuyuki** [comment]
@NML32 you need to use Docker, or compile it yourself. Further questions go to chat.
