### ISSUE TITLE
Genisys disconnects from Nemisys. Reason: timeout.

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#1688]
#### Issue description

I'm create nemisys proxy, 11 genisys clients(all connects to nemisys). If more than 4-6 players are in one servers, genisys disconnect with reason "timeout".

#### Steps to reproduce the issue

I'm think that this happens not always.

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/281048f34060c7b593acda3c56cfe836c32ad1b8
* Nemisys: https://github.com/iTXTech/Nemisys/commit/4fcf37ed6c05251c65c5b05aea8ba29111c24dad
* PHP: 7.0.9
* Server OS: Ubuntu Linux
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

Genisys:
```
[15:18:09] [Server thread/INFO]: _daniyr_play_[/46.235.78.101:54992] logged out due to Player has been transferred 
[15:23:01] [Server thread/INFO]: mr_king_Ytob[/46.235.78.101:30134] [ClientID: -1276569749772982458] logged in with entity id 7 at (hub_EnderCat, 8.5, 96, 8.5) 
[15:23:01] [Server thread/INFO]: _daniyr_play_[/46.235.78.101:54992] [ClientID: 5868662380824647913] logged in with entity id 8 at (hub_EnderCat, 8.5, 96, 8.5) 
[15:23:05] [Server thread/INFO]: _daniyr_play_[/46.235.78.101:54992] logged out due to timeout 
[15:23:32] [Server thread/NOTICE]: Synapse Client has disconnected due to timeout 
[15:23:32] [Server thread/INFO]: mr_king_Ytob[/46.235.78.101:30134] logged out due to Server Closed 
[15:23:32] [SynapseClient thread/NOTICE]: Trying to re-connect to Synapse Server 
[15:23:32] [SynapseClient thread/INFO]: Synapse has connected to 192.168.12.12:10305 
[15:23:33] [Server thread/INFO]: Login success to 192.168.12.12:10305 
timings paste 
[15:28:30] [Server thread/INFO]: Timings uploaded to http://paste.ubuntu.com/23067298/ 
[15:28:30] [Server thread/INFO]: You can read the results at http://timings.aikar.co/?url=23067298
```

Nemisys:
```
15:29:43 [CRITICAL] Error packet: 1B42C4BBF09F521344713BD1638F0C000000010000003F0000000200000002015C0400000000015C0400000000015C0400000000015C040000000000000001005901000000008B52386271D73CD81FB3397E847980800000000100000035000000020000000200560100000000000000320100000000000000000001005B01000000008E9CF27780D11E22DF6679444FED4649000000010000003F0000000200000002014C0100000000014C0100000000014C0100000000014C010000000000000001005001 
15:30:13 [INFO] Client 192.168.12.13:38629 has disconnected due to timeout 
15:30:13 [INFO] Pokiter[/178.92.8.117:2153] logged out due to Server Closed 
15:30:13 [INFO] FadelssHawk108[/89.151.156.199:16653] logged out due to Server Closed 
15:30:13 [INFO] Xx_CENA_xX_YT[/90.189.201.214:20000] logged out due to Server Closed 
15:30:13 [NOTICE] Client 192.168.12.13:38706 has connected successfully 
15:30:13 [NOTICE] mainServer: false 
15:30:13 [NOTICE] description: srv004 
15:30:13 [NOTICE] maxPlayers: 256 
15:30:20 [INFO] Pokiter[/178.92.8.117:2153] logged in with client id -916863997713146651 
15:30:20 [INFO] Pokiter has been transferred to 192.168.12.12:56876 
15:30:20 [INFO] Pokiter has been transferred to 192.168.12.13:38488 
```

**Comment by Guillaume351** [comment]
Same issue,  both servers are on max TPS.

**Comment by Tarik02** [comment]
@Guillaume351, do you use async tasks in your plugins?

**Comment by Guillaume351** [comment]
@Tarik02 For certain tasks, yes

**Comment by Tarik02** [comment]
@Guillaume351, how often and how many async taks do you use?

**Comment by Guillaume351** [comment]
@Tarik02 I use tasks to send mysql request, it depends, maybe 1 every 2 seconds

**Comment by Tarik02** [comment]
@Guillaume351, so, maybe this is reason. I'm will try to use other thread pool for mysql.

**Comment by Tarik02** [comment]
@Guillaume351, you can try my plugin to work with mysql in async tasks: https://github.com/GoldWill/DBManager

**Comment by Tarik02** [comment]
@Guillaume351, i'm tried to disable async queries(use queries in main thread), servers disconnects. This isn't reason...

**Comment by kuttLoggin** [comment]
U menya tochno takaya zhe problema, kak ispravit' yeyo?

**Comment by Tarik02** [comment]
@Guillaume351, i'm tried to send HeartbeartPacket one time per second(one time per five seconds default), so maybe this works.

**Comment by Guillaume351** [comment]
@Tarik02 Tell me if it works,  but spamming heartbeat is not a long time fix :/

**Comment by Tarik02** [comment]
@Guillaume351, spamming of Heartbeat don't helps...

**Comment by kabluinc** [comment]
same issue. happens too often

**Comment by Tarik02** [comment]
Solved. Optimizing of plugins helped me.

**Comment by Guillaume351** [comment]
Not sure if it's the reason for me.20 TPS, <25% load, 1Gbps network. Seems to happen randomly from a few minutes to a few hours.

**Comment by Tarik02** [comment]
@Guillaume351, i'm also. I'm tried to optimize scheduler tasks(use 1 time per 10 ticks instead of 1 time per tick).
