### ISSUE TITLE
Version 281048f crashes server

### ISSUE THREAD

**Issue by masterbuilderop** [iTXTech/Genisys#1689]
#### Server Crashes

I use MCPRO hosting to host a MCPE Pocketmine / Genisys server.I always use the latest phar from the master. If I use 281048f from master, it crashes the server immediately. *FYI* Since I am not in direct control of the server, when I want to update the phar I have to rename it to what is defined in the MCPro Pocketmine options. (Genisys_1.2dev-26_cc278a2.phar).

Server thread/CRITICAL Error: "Call to undefined function pocketmine\utils\openssl_random_pseudo_bytes()" (EXCEPTION) in "/src/pocketmine/utils/Utils" at line 438
Server thread/CRITICAL Error: "Call to a member function disablePlugins() on null" (EXCEPTION) in "/src/pocketmine/Server" at line 2465

#### Steps to reproduce the issue
Update Genisys.phar to build Genisys_281048f_2016-08-18_01-27-42
Start Server

#### OS and versions
* Genisys: 281048f
* PHP: 7.0.3
* Server OS: Linux
* Game version:  Windows 10 Edition Beta 15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Genisys Crash Dump Thu Aug 18 14:00:01 UTC 2016

Error: Call to undefined function pocketmine\utils\openssl_random_pseudo_bytes()
File: /src/pocketmine/utils/Utils
Line: 438
Type: notice

Code:
[429] 					$systemRandom = fread($fp, 64);
[430] 					fclose($fp);
[431] 				}else{
[432] 					$systemRandom = str_repeat("\x00", 64);
[433] 				}
[434] 
[435] 				$strongEntropyValues = [
[436] 					is_array($startEntropy) ? hash("sha512", $startEntropy[($rounds + $drop) % count($startEntropy)], true) : hash("sha512", $startEntropy, true), //Get a random index of the startEntropy, or just read it
[437] 					$systemRandom,
[438] 					openssl_random_pseudo_bytes(64),
[439] 					$value,
[440] 				];
[441] 				$strongEntropy = array_pop($strongEntropyValues);
[442] 				foreach($strongEntropyValues as $value){
[443] 					$strongEntropy = $strongEntropy ^ $value;
[444] 				}
[445] 				$value = "";
[446] 				//Von Neumann randomness extractor, increases entropy
[447] 				$bitcnt = 0;
[448] 				for($j = 0; $j < 64; ++$j){

Backtrace:
#0 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/root/multicraft/servers/server555270/Genisys_1.2dev-26_cc278a2.phar/, string /home/root/multicraft/servers/server555270/, string /home/root/multicraft/servers/server555270/plugins/, string unknown)
#1 (1): require_once(string phar:///home/root/multicraft/servers/server555270/Genisys_1.2dev-26_cc278a2.phar/src/pocketmine/PocketMine.php)

Genisys version: 281048f34060c7b593acda3c56cfe836c32ad1b8 [Protocol 82; API 2.0.0]
uname -a: Linux Node84.ash.mcprohosting.com 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 0 seconds
Number of loaded worlds: 0
Players online: 0/30

```

**Comment by dktapps** [comment]
Read README. (^_^)

**Comment by NML32** [comment]
I've been trying to get php compiled with ssl since yesterday. I tried using the script (now removed) and still Genisys crashes. There must be an easier way to update.

**Comment by ZedCee** [comment]
@NML32 https://github.com/iTXTech/Genisys/wiki/FAQs
XBOX set up and a link to the new build scripts can be found there.

**Comment by NML32** [comment]
I don't see any build scripts for Linux. Maybe they were removed.

**Comment by jojoe77777** [comment]
@NML32 https://github.com/iTXTech/php-build-scripts/blob/master/linux-build-install.sh
