### ISSUE TITLE
RCON crash. 

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#169]
Error: "Call to undefined method pocketmine\network\rcon\RCONInstance::kill()" (EXCEPTION) in "/src/pocketmine/network/rcon/RCON" at line 74
[20:15:50] [Server thread/EMERGENCY]: Crashed while crashing, killing process
And not save level :<

**Comment by CrayonDing** [comment]
Please use the newest version.

**Comment by xpyctum** [comment]
@CrayonDing okay. Will test.
