### ISSUE TITLE
Spawner Bug

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1695]
#### Issue description
Mobs will spawn on top of spawners, they should be spawning to the side.

#### Steps to reproduce the issue
Place a monster spawner (id 52) and put a spawn egg inside. Watch the mob of your choice spawn on top of the spawner.

#### OS and versions
PE
* Genisys: bebd304
* PHP: 7
* Server OS: Mac
* Game version:  0.15.4 and 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files
Nothin Here :)

**Comment by dktapps** [comment]
Why am I assigned to this? This has nothing to do with me.

**Comment by SuperDude36** [comment]
Idk. I just want help.

**Comment by ishitatsuyuki** [comment]
Oh wait, you mean that the spawner isn't a solid block?

**Comment by dktapps** [comment]
http://minecraft.gamepedia.com/Monster_Spawner
There's nothing in here that makes me think that this is a bug,

**Comment by ZedCee** [comment]
I constantly see mobs spawn on top personally, but thats usually when there plenty of mobs around.

 If theyre *only* spawning on top, then thats a different story.

**Comment by TDMidkwhatisxd** [comment]
Mobs spawn inside spawner , not on top lol ! 
Is annoying to see mobs inside spawner gliching around with leads =))). !
I will come with a screenshoot!

**Comment by SuperDude36** [comment]
@TDMidkwhatisxd Duhhh, I'm not talking about that, I'm talking about when they spawn...

**Comment by TDMidkwhatisxd** [comment]
i dont get that , and what is the problem if some spawn on top?

**Comment by SuperDude36** [comment]
If the spawn on top then peoples can't make IG a blaze grinders

**Comment by ishitatsuyuki** [comment]
Closing. Cannot understand what you're trying to say.

**Comment by daniktheboss** [comment]
I think what he means is like factions that spawn blazes and u make a lava trap and they die... I think lol
