### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by berkutta** [iTXTech/Genisys#1696]
Allocated 8GB of Ram in the server.properties
memory-limit=8192M

But it still crashes with the error, that it's exhausted out of 1024MB. But why 1024MB?

Genisys Crash Dump Thu Aug 18 20:18:42 UTC 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes)
File: /src/pocketmine/network/Network
Line: 216
Type: E_ERROR

Code:
[207] public function registerPacket($id, $class) {
[208] $this->packetPool[$id] = new $class;
[209] }
[210]
[211] public function getServer() {
[212] return $this->server;
[213] }
[214]
[215] public function processBatch(BatchPacket $packet, Player $p) {
[216] $str = zlib_decode($packet->payload, 1024 * 1024 * 64); //Max 64MB
[217] $len = strlen($str);
[218] $offset = 0;
[219] try {
[220] while ($offset < $len) {
[221] $pkLen = Binary::readInt(substr($str, $offset, 4));
[222] $offset += 4;
[223]
[224] $buf = substr($str, $offset, $pkLen);
[225] $offset += $pkLen;
[226]

Backtrace:
0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 272757ad70c160b6504048dc8ef9bcd19ce77057 [Protocol 82; API 2.0.0]
uname -a: Linux mc12 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 15 minutes 51 seconds
Number of loaded worlds: 7
Players online: 4/50

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
Bedwars 2.2 by Bluplayz for API(s) 1.14.0, 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
AdvancedMOTD 1.0.1 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
Friends 1 by Bluplayz for API(s) 1.14.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
RandomNick 1 by UltimateDevs for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
Stats 1.0.0 by CraftYourBukkit for API(s) 1.13.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
AMHD 1.0.0 by AppleMinerHD for API(s) 1.10.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by Muqsit** [comment]
change your main-hard-limit to 8GB too!
