### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1698]
#1: Wither Boss, I know this isn't added in normal minecraft, but you guys should add the wither, that would be awesome. 
#2: Nether Fortresses, they might be added, but I can't find any in the nether. Please add!
#3: Those dungeon things tomaso was talking about sound really cool. Or maybe you could just make a world generator.

**Comment by TheAppleGamer** [comment]
Wither could not be added to Genisys, it has to actually exist in Minecraft PE

**Comment by FaanMaario** [comment]
@TheAppleGamer I think he talks about Wither Skeletons.

**Comment by Muqsit** [comment]
Wither could also be an effect. Or any two of these mobs: Wither Boss, Wither Skeleton.

**Comment by SuperDude36** [comment]
@FaanMaario  I think he talks about Wither Bosses ;).

**Comment by SuperDude36** [comment]
@TheAppleGamer Ohhh, ok, I understand why my custom items didn't work...

**Comment by ishitatsuyuki** [comment]
Not to say, the client cannot render entities which aren't implemented.

**Comment by dktapps** [comment]
Wither Skeleton has been added on the`mobs` branch. I'm currently working on a variety of mob/entity improvements.

Wither boss will not happen. Reason: it's impossible, client doesn't support it. Wait for Mojang.

The rest of your suggestions are already on the ToDo list.
