### ISSUE TITLE
Not working   :(

### ISSUE THREAD

**Issue by Nidish** [iTXTech/Genisys#170]
It is saying-
/usr/bin/php/php.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127

**Comment by Nidish** [comment]
Fixed :)

**Comment by Guillaume351** [comment]
How ? :/

**Comment by PocketKiller** [comment]
@Guillaume351 https://github.com/iTXTech/PHP-Genisys/README.md read that.

**Comment by Jeff19** [comment]
I have the same problem as solved ??

**Comment by ishitatsuyuki** [comment]
VS2015 runtime.

**Comment by Jeff19** [comment]
Several times already and nothing changes run Bin folder and still as I do ??

**Comment by ishitatsuyuki** [comment]
@Jeff19 shut up and read my comment.

**Comment by Jeff19** [comment]
I do not understand?
VS2015 ?

**Comment by Jeff19** [comment]
@ishitatsuyuki I mean that my version is 2015 ?

**Comment by ishitatsuyuki** [comment]
Wow! I have just find a nice page on Internet! Must check!
https://www.google.co.jp/search?q=VS2015+runtime
