### ISSUE TITLE
Feature request: PlayerCraftEvent

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1706]
A PlayerCraftEvent in my opinion would be very cool, where it supplies the player attempting to craft an item, the items used to craft, and the output crafted item. For example in a plugin, you could only allow crafting torches for trusted members, etc. Or you could possibly change the output item. Please consider adding this :laughing: 

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/19c0136e81c9a74d037ad186a31cf246e8cfb238
* PHP: php7.0.9
* Server OS: Ubuntu 15.04 (Linux)
* Game version: 0.15.6-win10

**Comment by ifvictr** [comment]
@XFuryMCPE Have you checked [this](https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/event/inventory/CraftItemEvent.php) out yet? And changing output? I don't think that is possible.

**Comment by ishitatsuyuki** [comment]
You can add custom recipes. Check permissions on a recipe to achieve what you are trying to do.

**Comment by XFuryMCPE** [comment]
Whoops. Didn't check there lol

**Comment by dktapps** [comment]
I've said this before, but **get your facts straight first**.
