### ISSUE TITLE
Enhancement: For Kill message and it's type..

### ISSUE THREAD

**Issue by starterdragon** [iTXTech/Genisys#1707]
#### Issue description
Victim was slain by Killer message is kinda annoying and looks old, could I ask you to please make it configurable just like Player Join and Leave message plus the message type setting can be changed.
#### Steps to reproduce the issue
N/A

#### OS and versions

* Genisys: cc278a2 
* PHP: 7.0.0
* Server OS: windows xp
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ZedCee** [comment]
Via the api it's already configurable and can be changed with plugins.  GrabBag would be one example of one, however I'm sure there are others with less bloat.  
I would however highly recommend that you update to the latest release, https://github.com/iTXTech/Genisys/commit/e795eaab35729f59852040a0e2309650525cc5ee, which brings a large number of fixes for chests, inventories and the hotbar, adds hopper, and enables better W10 support, as well a XBOX Auth.
