### ISSUE TITLE
Network Problem when Port Forwarding under PHP7

### ISSUE THREAD

**Issue by markkrueg** [iTXTech/Genisys#171]
I've spent a number of hours troubleshooting a network problem with Genisys running under PHP7. 

Steps to reproduce:
1) Compile current PHP7 using PeratX script
2) Install current build of Genisys (currently testing #36)
3) Start Genisys and choose default settings
4) Set up Port Forwarding on your firewall to forward external port 19132 to your internal IP address port 19132 using UDP only.
5) Connect to Genisys using an iOS or Android device running MCPE 0.13.1 on your local LAN. Success!
6) Connect again from outside your LAN (the Internet) using your external IP address. Able to see server with correct name and player count. Fails with "Unable to connect to world."

I have swapped out PHP7/Genisys with a known working build of PHP5/PocketMine-MP on the same machine and step 6 then works fine. I have confirmed with two completely different firewalls on two different networks.

My only theory left is that something strange is going on with the network code in the current version of Genisys. I know as a fact that a previous version of PHP7/Genisys was working; but I am having trouble finding the exact combination.

Would someone please run the above test to confirm this issue?

Tested under 
- Ubuntu Server 14.04.3 LTS 
  - PeratX Script Compiled PHP7 and #36 fails
  - PHP5/PocketMine-MP works fine on same system
- OS X El Capitan 10.11.2
  - PeratX Script Compiled PHP7 and #36 fails
  - PHP5/PocketMine-MP works fine on same system
- Windows 10
  - I have confirmed that Windows 10 with the Genisys PHP binary and Build #36 does NOT have this problem.

My PHP7 Ubuntu build:
```
bash ./compile.sh -t linux64 -j 2 -c -f x86_64
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[opt] Set target to linux64
[opt] Set make threads to 2
[opt] Will force compile cURL
[opt] Enabling abusive optimizations...
[INFO] Compiling for Linux x86_64
[PHP] downloading 7.0.2... done!
[zlib] downloading 1.2.8... checking... compiling... installing... cleaning... done!
[mcrypt] downloading 2.5.8... checking... compiling... installing... cleaning... done!
[GMP] downloading 6.1.0... checking... compiling... installing... cleaning... done!
[mbed TLS] downloading 2.2.0... checking... compiling... installing... cleaning... done!
[cURL] downloading curl-7_46_0... checking... compiling... installing... cleaning... done!
[YAML] downloading 0.1.6... checking... compiling... installing... cleaning... done!
[libpng] downloading 1.6.20... checking... compiling... installing... cleaning... done!
[PHP pthreads] downloading 3.1.5... done!
[PHP Weakref] downloading 0.3.2... done!
[PHP YAML] downloading 2.0.0RC6... done!
[PHP] enabling optimizations... checking... compiling... installing... generating php.ini... done!
[INFO] Cleaning up... done!
[PocketMine] You should start the server now using "./start.sh."
[PocketMine] If it doesn't work, please send the "install.log" file to the Bug Tracker.
```

**Comment by Muqsit** [comment]
Confirmed. This has happened to my server too. At first, the PHP7 build worked for a whole day but then the next day, it stopped working. I then made another server on another system with the same OS (Ubuntu 14.04 LTS 64-bit) and it was working there. I tried transferring the residue files (*.yml and server.properties) to the system where the 19132 server didn't work and it still didn't work. I then stopped the server, made another folder and freshly started a new server running 19132, but still get the same unable to connect to world error.

My servers on port 3800 and 13579 (on the same system on which my server on port 19132 didn't work) are working.

**Comment by Muqsit** [comment]
For now, I'm using the php5 version for my server running on port 19132

**Comment by SalmonGER** [comment]
It's working great for me.

**Comment by markkrueg** [comment]
@SalmonGER Can you be more specific? 

What OS are you running your server on? What version of Genisys? How did you build your PHP7? How recently? 

Thanks! Just trying to track this one down; and having a known-working setup would help a great deal.

**Comment by flaxues** [comment]
I'm running Ubuntu 14.04 I compiled php7 with the compile script some days ago!

Without any problem...

**Comment by SalmonGER** [comment]
@markkrueg my server runs on a Windows 10 system with the Genisys PHP binary and Build #36 ( http://mcper.cn:8080/job/Genisys/36/ ). On Linux i had some problems but on windows it's working fine.

**Comment by markkrueg** [comment]
@SalmonGER OK, so this may be a problem only on Linux and OS X. I have not tested on Windows; but will.

@flaxues I'm wondering if the "some days ago" is the issue. The version I had running last week was also working fine. I just don't know the exact version I was running then because I have overwrote it with the newest version. Which version of Genisys are you running? And you are port forwarding port 19132 to 19132 UDP only?

**Comment by flaxues** [comment]
19132 UDP yup and i'm running build 23

**Comment by markkrueg** [comment]
@flaxues I don't see a build #23 on http://mcper.cn:8080/job/Genisys/

Do you mean #32?

**Comment by PeratX** [comment]
Port check?

**Comment by markkrueg** [comment]
I don't have enough confirmation that this is widespread problem; so closing for now until others can reproduce.

**Comment by flaxues** [comment]
I think I'm having this problem now!

**Comment by PeratX** [comment]
@flaxues Details??

**Comment by flaxues** [comment]
Well out of nowhere http://minecraftpocket-servers.com/ says my server is offline

**Comment by flaxues** [comment]
But the port is open according to some website with port checkers

**Comment by PeratX** [comment]
This website sometime cannot reaches server. Some Chinese servers cannot be reached.

**Comment by PeratX** [comment]
Can you join the server through the external network?

**Comment by flaxues** [comment]
Nope I can't join it either localhost or external

**Comment by PeratX** [comment]
And server is running properly !?

**Comment by flaxues** [comment]
I think so i'm running it as I always do but suddenly it just says it's offline 19134 works fine

**Comment by PeratX** [comment]
MCPE cannot get the status of server ?

**Comment by flaxues** [comment]
The client, server list and port checkers etc.

**Comment by PeratX** [comment]
Time out or Disconnecting from server?

**Comment by flaxues** [comment]
Client just says Unable to connect to world.

**Comment by flaxues** [comment]
But in the list of all servers on my client it's says it's online

**Comment by PeratX** [comment]
Oops...I do not know what is going on. Is your server crashes?

**Comment by flaxues** [comment]
It's not a plugin i did a clean install to check

**Comment by flaxues** [comment]
I'm getting a error at a certain interval

Warning: unpack(): Type N: not enough input, need 4, have 0 in /home/matthew/daemon/src/pocketmine/utils/Binary.php on line 330

**Comment by PeratX** [comment]
Seems something wrong with your level

**Comment by jazzwhistle** [comment]
I have that same 'unpack' error although it doesn't stop the server running, unusual lag for servers reporting 20TPS with very little CPU or memory usage, minecraftpocketservers reporting my servers offline when they are online, and players who have trouble joining... the green bar just stops during "generating world". This happens on multiple servers, and is independent of plugins or PM version.

I also have 3 servers with ports above 33333 that refuse to allow players to connect when using PHP7 and latest Genisys builds (although they start and run normally), but they work fine with PHP5. The other servers work with PHP5 or PHP7, so I'm stumped.

**Comment by flaxues** [comment]
Yup thats also a problem my TPS is 19-20 and load is 30% with 60-70 people and the lag is horrible sometimes... It's not my network tho 1Gbps Up and 1Gbps Down :P

**Comment by PeratX** [comment]
Can you upload you level?I have to reproduce the error.

**Comment by jazzwhistle** [comment]
Here's a world that gives the unpack error and is unplayable: https://drive.google.com/file/d/0ByMnFOzZgPbzMlVXUnhHSmpOWGM

Thanks
