### ISSUE TITLE
Particle command bug

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#1719]
#### Issue description
 in genisys the command /particle doesn't work, when I do /particle nameparticle ~ ~~ 1 1 1 1000 the particles doesn't generate

#### OS and versions

* Genisys: cedc4a5e
* PHP: 7.0.3
* Server OS: windows
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files
 none 
```
```

**Comment by SuperDude36** [comment]
When you typed the "~ ~~" it has to be "~ ~ !"

**Comment by SuperAlecs** [comment]
oh thanks man, sorry genisys for having disturbed!
