### ISSUE TITLE
setHotbarSlotIndex deprecated? WTH?

### ISSUE THREAD

**Issue by MrGenga** [iTXTech/Genisys#1724]
#### Issue description

I had a lot of bugs with PlayerInventory, after W10 update. I got messages like: Do not attempt to change hotbar links in plugins! You are broke a lot of plugins. Fix it please.
#### Steps to reproduce the issue

Try to add items with old methods.
#### OS and versions

* Genisys: after d08bff9d21536de630f6e33052d3f03dcc8d9558
* PHP: 7.0.2
* Server OS: Ubuntu 16.04
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///home/mb/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 102
```

**Comment by dktapps** [comment]
Deprecated means deprecated, not broken.
