### ISSUE TITLE
The PHP binary you provided don't have pthread extension

### ISSUE THREAD

**Issue by fengberd** [iTXTech/Genisys#1726]
#### Issue description

ARM PHP 7.0.9 binary don't have pthread extension.

#### Steps to reproduce the issue

Download [this binary](https://itxtech.org/download/PHP%20for%20Genisys/php_7.0.9_linux_arm.xz) then just start server.

#### OS and versions

* Genisys:Any version
* PHP:7.0.9 ARM
* Server OS:Flyme 4.2 based on Android 4.4.4
* Game version: Any version

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.
```

**Comment by GlitchPlayer** [comment]
I haven't tried on android suu....

**Comment by ishitatsuyuki** [comment]
Please download again. The CDN cache has been fixed.

**Comment by dktapps** [comment]
Works fine for me (Sony Xperia Z2 with Android 6.0.1)

**Comment by ishitatsuyuki** [comment]
@dktapps I said that it was just the CDN cache.
