### ISSUE TITLE
Tar xz archive with complied php is broken

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#1732]
Tired get Linux compiled php, but xz archive is broken. 
Link: https://itxtech.org/download/PHP%20for%20Genisys/php_7.0.9_linux_arm.xz

**Comment by ishitatsuyuki** [comment]
Your brain is broken.

**Comment by dktapps** [comment]
I think my colleague means to say that there doesn't appear to be anything wrong with that link or the downloaded file. Downloaded myself and it's fine.

**Comment by AuroRacing** [comment]
xpyctum, Lol, I thought your skill is higher...

**Comment by xpyctum** [comment]
@ishitatsuyuki You could help , and not to offend ? 
The problem is that the archive does not unpack .
Tired using tar -xJf name.xz
![img_3012](https://cloud.githubusercontent.com/assets/6584811/17837322/2a4a989e-67b9-11e6-9c66-3ca3b9396a31.PNG)
 Get error and I thought that the archive is broken

**Comment by ishitatsuyuki** [comment]
> xpyctum, Lol, I thought your skill is higher...

This is not tar file, this is pure xz file. Use xz -d, and this is only for ARM.

**Comment by xpyctum** [comment]
@ishitatsuyuki I know. It only for testing. I first meet with this format . the Internet found that it xz.

**Comment by MrDoni98** [comment]
Олежа юзай https://github.com/iTXTech/php-build-scripts ))

**Comment by ishitatsuyuki** [comment]
**No Russian here. Beware banning.**

**Comment by MrDoni98** [comment]
sorry

**Comment by MrDoni98** [comment]
but why? Chinese is written...

**Comment by ishitatsuyuki** [comment]
Chinese is understanded of many of our members, however we barely understand Russian. Basically, we make it translated so everyone can read it.

**Comment by xpyctum** [comment]
@MrDoni98 still using.

**Comment by MrDoni98** [comment]
@ishitatsuyuki  More people undestand English, and speak Russian. Ban for the fact that they explain the issue to the in his own language, not right.Native speakers would be able to better help him.

**Comment by ishitatsuyuki** [comment]
Remember that this is not you guy's entertainment chat, expressing a thing in the way everyone, especially the core developers can understand is important.

**Comment by MrDoni98** [comment]
the language barrier is the eternal problem of people :-(

**Comment by MrDoni98** [comment]
the language barrier is the eternal problem of people :-(

**Comment by xpyctum** [comment]
@ishitatsuyuki but it is better to use English , and then everyone will understand what you are driving the conversation .

**Comment by ishitatsuyuki** [comment]
This question is resolved, no more chatting.

**Comment by Muqsit** [comment]
@xpyctum 
Google is a very helpful tool in our day-to-day life.
http://askubuntu.com/questions/92328/how-do-i-uncompress-a-tarball-that-uses-xz

**Comment by ishitatsuyuki** [comment]
@Muqsit 
Reading the whole conversation is a very important thing.
This is XZ, not TAR.XZ
