### ISSUE TITLE
InventoryTransactionEvent (Problems Introduced)

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1733]
#### Issue description
These changes occurred after InventoryTransactionEvent was changed. Several plugin have stopped working. There are many more errors. The best thing would be to revert back, so that Genisys could support PocketMine plugins.

#### Steps to reproduce the issue
```
if($holder instanceof \pocketmine\tile\Chest){
					$shopChest = $holder->getBlock();
					$hasChest = true;
					$usedTransaction = $transaction;
				}
		$transactions = $event->getTransaction()->getTransactions();
		$inventories = $event->getTransaction()->getInventories();
$tileChest->getInventory()->getItem($i)->getDamage() === $usedTransaction->getTargetItem()->getDamage();				
```
Doesn't work anymore.
#### OS and versions
* Genisys: (GitLab) 640718ca
* PHP: 7.0.10
* Server OS: Ubuntu 14.04 LTS
* Game version: 

```
```

**Comment by dktapps** [comment]
API changes. Client functionality comes before plugins. Deal with it.

**Comment by tigerza117** [comment]
Pls Fix this
