### ISSUE TITLE
Charcoal + sticks = craft torch not work

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1745]
#### Issue description
Charchoal + sticks = craft torch not work

#### Steps to reproduce the issue
1. place stick, and charchoal
2. make torch
3. torch reseted, and drop stick, charcoal

#### OS and versions
Genisys: https://github.com/iTXTech/Genisys/tree/3d8f4377f30907ca8b01c2de6fcb7a7a477941c6
PHP: 7.0.10 (Genisys script)
Server OS: Ubuntu 14.04.4 LTS
Game version: 0.15.6 (Windows 10 Editions beta)

#### Crashdump, backtrace, memory dumps, plugins list or other files
none

**Comment by dktapps** [comment]
Confirmed. Seems I missed something. Will investigate.
