### ISSUE TITLE
Getting metadata of offline player

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#1746]
#### Issue description

Error when trying to get metadata of offline player

#### Steps to reproduce the issue

1. Get offline player by 'Server->getOfflinePlayer($name)'
2. Try to get metadata by 'OfflinePlayer->getMetadata("Pos")'
3. ERROR

#### OS and versions

* Genisys: 617e284
* PHP: 7.0.3
* Server OS: Linux Mint 17.3
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\metadata\PlayerMetadataStore::disambiguate() must implement interface pocketmine\metadata\Metadatable, instance of pocketmine\OfflinePlayer given, called in /home/***/Genisys/src/pocketmine/metadata/MetadataStore.php on line 71" (EXCEPTION) in "/src/pocketmine/metadata/PlayerMetadataStore" at line 28```

**Comment by dktapps** [comment]
This is not supported.

**Comment by alex2534alex** [comment]
But it's a bug, which causing an error

**Comment by dktapps** [comment]
**This is not supported.**
