### ISSUE TITLE
Crops and the bed

### ISSUE THREAD

**Issue by Efforto** [iTXTech/Genisys#175]
English: i cant get crops and i cant sleep at night when i used /time set
PS:SiteLand plugin.
中文:自从本渣新上了SiteLand买了一块地之后在上面种菜换生存依然得不到作物，如果用/time set设置为黑夜时间那么还是You can only.sleep at night

**Comment by CrayonDing** [comment]
植物生长问题，你需要在pocketmine.yml里更改设置。那个时间的问题我去看看

**Comment by CrayonDing** [comment]
另外，时间那个没问题啊。睡觉设置到14000-23000之间。

**Comment by Efforto** [comment]
wtf难道是我的问题？

**Comment by Efforto** [comment]
我再看看

**Comment by Efforto** [comment]
先关issue了
