### ISSUE TITLE
Crafting ingredients have to be put in specific squares of the grid [Win10]

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1750]
#### Issue description

Bucket crafting not work Windows 10 Edition when the ingots are placed in the bottom of the crafting grid. 
#### Steps to reproduce the issue
1. place iron ingots crafting table
2. Not seeing bucket
#### OS and versions

Genisys: https://github.com/iTXTech/Genisys/tree/3d8f4377f30907ca8b01c2de6fcb7a7a477941c6
PHP: 7.0.10 (Genisys script)
Server OS: Ubuntu 14.04.4 LTS
Game version: 0.15.6 (Windows 10 Editions beta)
#### Crashdump, backtrace, memory dumps, plugins list or other files

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/17866297/4fcbd46e-68a6-11e6-8616-a01c58a98769.PNG)

**Comment by dktapps** [comment]
You need to put the ingots in the top half of the crafting grid. This is a known issue and will be fixed in a future update.

**Comment by andris155** [comment]
Thanks.

**Comment by ImagicalGamer** [comment]
In MCPE don't you have to put it in the right slots? If it goes at the top you place it at the top?

**Comment by jojoe77777** [comment]
@ImagicalGamer Have you tried playing PE? There are no crafting slots.

**Comment by thebigsmileXD** [comment]
@jojoe77777 it does show the recipes, i think he meant that. @dktapps i may look into that. #blamethecraftingmanager

**Comment by dktapps** [comment]
I'm also investigating PocketMine-MP's JSON based crafting. Interestingly, I believe it actually might be free of this issue. Needs testing further.

**Comment by thebigsmileXD** [comment]
Its a wonder that PM uses this method of Json files.. we spoons don't have it

**Comment by dktapps** [comment]
Fixed in https://github.com/iTXTech/Genisys/commit/3d6d5f8324e2f451a4ee83b6375adf7415153ce2
