### ISSUE TITLE
Huge load

### ISSUE THREAD

**Issue by AuroRacing** [iTXTech/Genisys#1755]
* Genisys: 0.15.4 
* PHP: 7
* Server OS: Debian 8
* Game version: 0.15.4

8 core 13 GB RAM, online 90+. But why load 100% TPS 1. Plugins, not a lot... Here's the timings https://timings.aikar.co/?url=23081324 

Help me.

**Comment by dktapps** [comment]
Simply put: way too many players. Can you post your pocketmine.yml please?

**Comment by Muqsit** [comment]
Um an I the only one wondering why the RAM is such a unique  number. 13 of all numbers... It should be a multiple of 2 excluding 14 right?

You have too many tiles close to your spawn. Do /status and find out how many tiles are loaded. For you, the normal amount must be 8k

**Comment by AuroRacing** [comment]
# Main configuration file for PocketMine-MP
# These settings are the ones that cannot be included in server.properties
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading.

settings:
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "rus"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 #When server shut down, the players will get kicked and this is what will show on there screen.
 shutdown-message: "PECTAPT CEPBEPA"
 #Allow listing plugins via Query
 query-plugins: false
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: true
 #Enable plugin and core profiling by default
 enable-profiling: false
 #Will only add results when tick measurement is below or equal to given value (default 20)
 profile-report-trigger: 20
 #Number of AsyncTask workers.
 #Used for plugin asynchronous tasks, world generation, compression and web communication.
 #Set this approximately to your number of cores.
 #If set to auto, it'll try to detect the number of cores (or use 2)
 async-workers: auto

memory:
 #Global soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 global-limit: 0

 #Main thread soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 main-limit: 0

 #Main thread hard memory limit in megabytes. Set to 0 to disable
 #This will stop the server when the limit is surpassed
 main-hard-limit: 3048

 #Period in ticks to check memory (default 1 second)
 check-rate: 20

 #Continue firing low-memory-triggers and event while on low memory
 continuous-trigger: true

 #Only if memory.continuous-trigger is enabled. Specifies the rate in memory.check-rate steps (default 30 seconds)
 continuous-trigger-rate: 30

 garbage-collection:
  #Period in ticks to fire the garbage collector manually (default 30 minutes), set to 0 to disable
  #This only affect the main thread. Other threads should fire their own collections
  period: 120

  #Fire asynchronous tasks to collect garbage from workers
  collect-async-worker: true

  #Trigger on low memory
  low-memory-trigger: true

 max-chunks:
  #Limit of chunks to load per player, overrides chunk-sending.max-chunks
  trigger-limit: 4

  #Do chunk garbage collection on trigger
  trigger-chunk-collect: true

  #Trigger on low memory
  low-memory-trigger: true

 world-caches:
  disable-chunk-cache: true
  low-memory-trigger: true


network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable.
 batch-threshold: 256
 #Compression level used when sending batched packets. Higher = Uses More CPU, Less = More Bandwidth Usage
 compression-level: 2
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: true
 #Experimental, only for Windows. Tries to use UPnP to automatically port forward
 upnp-forwarding: false

debug:
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables /status, /gc
 commands: true

level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #If true, converts from a format that is not the default to the default format on load
 #NOTE: This is currently not implemented
 convert-format: false
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: false
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: false

chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 1
 #Amount of chunks sent around each player
 max-chunks: 4
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 4
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 0
 #Radius of chunks around a player to tick
 tick-radius: 0
 light-updates: false
 clear-tick-list: true

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 2
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 2

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15

auto-report:
 #Send crash reports for processing
 enabled: false
 send-code: false
 send-settings: false
 send-phpinfo: false
 host: crash.pocketmine.net

anonymous-statistics:
 #Sends anonymous statistics for data aggregation, plugin usage tracking
 enabled: false
 host: stats.pocketmine.net

auto-updater:
 enabled: false
 on-update:
  warn-console: false
  warn-ops: false
 #Can be development, beta or stable.
 preferred-channel: beta
 #If using a development version, it will suggest changing the channel
 suggest-channels: false
 host: www.pocketmine.net

aliases:

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

**Comment by AuroRacing** [comment]
@Muqsit 13GB RAM because we bought so much... Here is the screen /status
![zlrudawqh54](https://cloud.githubusercontent.com/assets/20933452/17892686/3f101c8e-694b-11e6-9c12-0eba66277b80.jpg)

**Comment by dktapps** [comment]
3048MB ! == 13GB
Maybe try increasing your async-workers (change from auto to 8)

**Comment by TheAppleGamer** [comment]
This may help, try converting the world to mcr

**Comment by ZedCee** [comment]
@TheAppleGamer Please don't spam.  His configuration is already set to `mcregion`. Thus would be `mcr`.  `Anvil` is nearly the same as `mcregion`, but by design, built to run faster. That's `mca`.

See my comments on #1591 regarding `anvil` benefits over `mcregion`, and various things that can lag a server besides the map format.

**Comment by TheAppleGamer** [comment]
@ZedCee I can almost guarantee that the map format causes lag

**Comment by ZedCee** [comment]
@TheAppleGamer Before posting comments, read everything prior!
  The `pocketmine.yml`very clearly states `mcregion`.  

There is no such thing as an almost guarantee, either you can or you can't.  Your past issues would not have been closed otherwise.  (You couldn't provide, and we could not produce, enough evidence to the fact).  Please cease generalized commenting and arguing in other users issue tickets or you will end up banned.  Use our chats if you wish to discuss map formats.  
Issue tickets are not a public forum of discussion, they are here to solve provable problems.

---

@AuroRacing I apologize for any confusion this may have caused.
Did the suggestion provided by @dktapps, increasing the `main-hard-limit: ` and changing to`async-workers: 8` in your `pocketmine.yml`, help you with your load?

**Comment by SleepSpace9** [comment]
Just seen - the period for **garbage-collection** is set VERY low:
```period: 120```

By default it's 36000 ticks!
