### ISSUE TITLE
Not work again Hopper

### ISSUE THREAD

**Issue by Crypthu** [iTXTech/Genisys#1757]
#### Issue description
No work again Hopper

#### Steps to reproduce the issue
 1 Click creative mode Hopper item
2 . Place Hopper ( no work)

#### OS and versions
* Genisys: 0.15.4
* PHP: 7.0.10 (Genisys source)
* Server OS: Windows 7 Ultimate
* Game version:  0.15.6 ( Android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
The description is very vague. I have no hopper issues on any platform. Please however be aware that any hoppers placed prior to the hopper update will not work.

**Comment by Crypthu** [comment]
The hopper called item does not work since the update again

**Comment by Crypthu** [comment]
Sry XD nothing problem
