### ISSUE TITLE
About the Effect bottles

### ISSUE THREAD

**Issue by Efforto** [iTXTech/Genisys#176]
→_→Translate urself,i dont want to translate to English.......
qwq，隐身，虚弱药水等部分药水显示6分钟其实是8分钟，plz fix~
还有。。。→_→如果在创造模式吃掉药水瓶没有效果qwq
如果用喷溅药水给自己效果的话，或者吃药水，能不能设置成重新计时呐:P就是说你吃掉药水之后剩了1分钟你再吃一个药水是否可以回到原来的时间qwq

**Comment by flaxues** [comment]
Just dropped in a translator:

qwq, stealth, and some other weak syrup syrup is actually displayed 6 minutes 8 minutes, plz fix ~
and also. . . →→ If you eat the vial in the creation mode has no effect qwq
If splash potion to their effects, or if medication water, can be set to re-clocked na: P That you eat syrup left after 1 minute if you eat a potion can return to the original time qwq

**Comment by CrayonDing** [comment]
上面是机翻？
