### ISSUE TITLE
FloatingTextParticle is not despawned from the player when changing worlds

### ISSUE THREAD

**Issue by fuyutsuki** [iTXTech/Genisys#1764]
#### Issue description
Server::getLevelByName not working.

#### Steps to reproduce the issue
Specify the world in the following plug-ins displaying the particle, but particles are displayed in all a Level.

#### OS and versions

* Genisys: [master branch latest](https://github.com/iTXTech/Genisys/commit/9f1ee84fe36d16742a650fd001ba09091763a2c6)
* PHP: 7.0.3
* Server OS: win10 64bit
* Game version:  0.15.6 PE/win10

#### Crashdump, backtrace, memory dumps, plugins list or other files
 [ManyWorld v2.1.0] (https://github.com/Muirfield/ManyWorlds)
plugin [text.zip](https://github.com/iTXTech/Genisys/files/433872/text.zip)
```php
public function onJoin(PlayerJoinEvent $event){
		$player = $event->getPlayer();

		$this->getServer()->loadLevel("world");
		$level1 = Server::getInstance()->getLevelByName("world");
		$pos = new Vector3("128", "5", "128");
		$particle = new FloatingTextParticle($pos, "test1", "test1");
		$level1->addParticle($particle, [$player]);

		$this->getServer()->loadLevel("test");
		$level2 = Server::getInstance()->getLevelByName("test");
		$pos = new Vector3("130", "5", "130");
		$particle = new FloatingTextParticle($pos, "test2", "test2");
		$level2->addParticle($particle, [$player]);
	}
```
**Level in world**
![img_2305](https://cloud.githubusercontent.com/assets/16377174/17915876/228829be-69e9-11e6-937f-d635037d4fe5.PNG)

**Level in test**
![img_2306](https://cloud.githubusercontent.com/assets/16377174/17915883/2ea684a2-69e9-11e6-9260-e027c1453130.PNG)

**Comment by diamond-gold** [comment]
Floating text particle is basically a add entity packet, so any player that receives that packet will see the particle
If you do not want the player to see the other text particle, don't send to player if player is not in that level

**Comment by fuyutsuki** [comment]
@diamond-gold Well, do you think this code is how to fix it if you work well?

**Comment by SleepSpace9** [comment]
Possibly this is a client bug, because I saw this behaviour with FloatingText Particles even on different Servers which are connected through Nemisys. Very strange...

And the problem seems to exist for a long time:
https://github.com/Muirfield/pocketmine-plugins/issues/20

**Comment by dktapps** [comment]
This isn't a client bug. It's due to the hacky nature of FloatingTextParticle and the way multiworld is handled.

**Comment by diamond-gold** [comment]
@fuyutsuki  you can fix this by doing
public function onEnable(){
$this->level1Par = new FloatingTextParticle(new Vector3("128", "5", "128"), "test1", "test1");
$this->level2Par = new FloatingTextParticle(new Vector3("130", "5", "130"), "test2", "test2");
}
public function onLevelChange(EntityLevelChangeEvent $event){
        $player = $event->getEntity();
        if($player instanceof Player){
        if(($level = $player->level->getName()) === "world"){
        $level1Par->setInvisible(false);
        $level->addParticle($level1Par, [$player]);
$level2Par->setInvisible(true);
        $level->addParticle($level2Par, [$player]);
}elseif($level === "test"){
        $level1Par->setInvisible(true);
        $level->addParticle($level1Par, [$player]);
$level2Par->setInvisible(false);
        $level->addParticle($level2Par, [$player]);
}
}
    }

**Comment by fuyutsuki** [comment]
@diamond-gold Oh, ok thanks!

**Comment by PeratX** [comment]
Make FloatingTextParticle an entity is better
