### ISSUE TITLE
Hiding particles when using /effect doesn't work

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1765]
#### Issue description

When attempting to hide particles when using the effect command (ex: /effect ABAxStorm invisibility 99 99 true), the particles are still displayed to all clients. 
#### Steps to reproduce the issue

Perform the command /effect player invisibility 999 999 true
Notice that the particles are still visible
#### OS and versions

* Genisys: e795eaa (unable to update Genisys myself, but this issue has been present for a long time)
* PHP: 7.0.8
* Server OS: Linux (Hosted by NetherBox)
* Game version: 15.6 Android

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by ABAxStorm** [comment]
My apologies for opening a issue already reported, will not happen again.

**Comment by ZedCee** [comment]
#1577
