### ISSUE TITLE
Random client crash, and rejoin instant client crash

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1767]
#### Issue description
Random client crash, and rejoin instant client crash

#### Steps to reproduce the issue
1. Use /warp, or /p h world sometimes not loading world (transparent).
2. Crash client
3. Rejoin load world, and crash client

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/3d8f4377f30907ca8b01c2de6fcb7a7a477941c6
* PHP: 7.0.10 (Genisys script)
* Server OS: Ubuntu 14.04.4 LTS
* Game version:  0.15.6 (Android, Windows 10 Edition Beta)

#### Crashdump, backtrace, memory dumps, plugins list or other files

https://www.youtube.com/watch?v=C3rrJtMwzAo
`MesterBoy17 lost connection: timeout`
![screenshot_20160824-131433](https://cloud.githubusercontent.com/assets/8324198/17928811/ed14238c-69fc-11e6-8f29-24bea83a357d.png)
![screenshot_20160824-131419](https://cloud.githubusercontent.com/assets/8324198/17928812/ed16ea4a-69fc-11e6-9b89-36c135244024.png)
![screenshot_20160824-131408](https://cloud.githubusercontent.com/assets/8324198/17928813/ed19e470-69fc-11e6-84c9-ab262a0cd2a4.png)
![14115013_1284578758242408_6545167070618481611_o](https://cloud.githubusercontent.com/assets/8324198/17928478/1ea30834-69fb-11e6-8456-faf68b7139be.jpg)
![13698124_1284578721575745_4335841813024429922_o 1](https://cloud.githubusercontent.com/assets/8324198/17928479/1ea6b8a8-69fb-11e6-956f-0ad66a740a02.jpg)

**Comment by dktapps** [comment]
See #1206?

**Comment by ZedCee** [comment]
For the issue mentioned by @dktapps,  you can quickly prime a /tp command on the server to pull a player out, keeping your view distance at the lowest possible with 'genisys.yml`:
```
player: 
  ...
  chunk-radius: 1
```
This is a client issue.  You can delete the erroneous chunks, or cross your fingers (like I am) for a fix to come in 0.16.0(Hopefully) and stash your maps away until then.  (You can also use [MCEdit](https://github.com/Khroki/MCEdit-Unified) or [PMImporter](https://github.com/Muirfield/pmimporter) to try to remove erroneous blocks).

**Comment by dktapps** [comment]
#blamemojang

**Comment by ABAxStorm** [comment]
A simple solution, actually, is to use BlockLauncher. BlockLauncher actually shows the unsupported blocks as update blocks, allowing you to easily remove them.
