### ISSUE TITLE
Hoppers Dupe Bug

### ISSUE THREAD

**Issue by Prisane** [iTXTech/Genisys#1768]
#### Issue description
When item transfer to the hopper, item is replicates.

#### Steps to reproduce the issue
Watch the video that I took. You will understand the problem.

https://www.youtube.com/watch?v=ocC2sZXFOZ0

#### OS and versions
* Genisys: https://github.com/iTXTech/Genisys/tree/731f8b30546947f86dd6d19b2e259a135bd9ed0e
* PHP: 7.0.3
* Server OS: Lunix
* Game version: Pocket Edition and Windows 10 Edition Beta

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Will investigate.

**Comment by Prisane** [comment]
Thank you, I hope you can solve quickly. This bug is very important to hopper

**Comment by Prisane** [comment]
#2052
