### ISSUE TITLE
"Loading *.yml" debug logs always appear even if debug.level <= 1

### ISSUE THREAD

**Issue by Leo3418** [iTXTech/Genisys#1769]
#### Issue description
Even if `debug.level` in `pocketmine.yml` is set to value <= 1, "Loading pocketmine.yml" and "Loading genisys.yml" still appear as debug info.
I believe this issue is related to commit fb2d504346cb7cc494c61289dc851c5fad296d77, because [those prompts appear] (https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/Server.php#L1822) before [Genisys determines the debug level] (https://github.com/iTXTech/Genisys/blob/fb2d504346cb7cc494c61289dc851c5fad296d77/src/pocketmine/Server.php#L1953), so even if they are debug logs, they still appear.
This is not a serious issue, but still worth noting.

#### Steps to reproduce the issue
Simply start Genisys.

#### OS and versions
* Genisys: 79d7093d2c5ad643a8402fae34f80d7e0600d941 (this issue should affect all versions after fb2d504346cb7cc494c61289dc851c5fad296d77)
* PHP: 7.0.9
* Server OS: Windows 10 1607
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files
![start](https://cloud.githubusercontent.com/assets/14175175/17931339/98409106-6a3d-11e6-8c87-3cb111763dff.PNG)

**Comment by dktapps** [comment]
That's my bad. I forgot that the configs don't get loaded until _after_ those prompts are shown :laughing:

**Comment by ZedCee** [comment]
Exactly what I was gonna say :+1:
