### ISSUE TITLE
Jenkins down?

### ISSUE THREAD

**Issue by Nidish** [iTXTech/Genisys#177]
jenkins is down and is not english also. where is the new jenkins link?

**Comment by CrayonDing** [comment]
Sorry.We are transfering our jenkins server to a better computer room to improve the speed.

**Comment by flaxues** [comment]
And storage?

**Comment by CrayonDing** [comment]
yes.

**Comment by Nidish** [comment]
So where is the new link?

**Comment by PeratX** [comment]
@Nidish No new link...We are also waiting for the express...

**Comment by Nidish** [comment]
@PeratX ok I'll also wait

**Comment by Nidish** [comment]
Can you upload latest .phar to userscloud or something? 
I have #36 will upload for others if you want

**Comment by SalmonGER** [comment]
@Nidish Just make a .phar with DevTools. I always make my own .phar.

**Comment by Nidish** [comment]
DevTools ? Link..

**Comment by SalmonGER** [comment]
https://forums.pocketmine.net/plugins/devtools.515/

Load the server with the src folder and type the command /makeserver
When DevTools finished the .phar will  be in /plugins/DevTools

**Comment by Nidish** [comment]
@SalmonGER  Thanks

**Comment by Nidish** [comment]
SRC server to paste where?

**Comment by SalmonGER** [comment]
@Nidish In the server folder where you also put your PocketMine-MP.phar in.

**Comment by CrayonDing** [comment]
I upload the newest version Genisys.phar to my cloud disk
https://drive.google.com/file/d/0B47xKpOkRL7JaU9ZNE9CRDVXTTA/view?usp=sharing

**Comment by GalvinGao** [comment]
@CrayonDing Saving it as China Webdisk...

**Comment by CrayonDing** [comment]
@GalvinGao Here is Github.You know.

**Comment by GalvinGao** [comment]
Saved.

**Comment by GalvinGao** [comment]
README.md rewrites. @CrayonDing

**Comment by Nidish** [comment]
Thanks guys
