### ISSUE TITLE
Paintings despawn

### ISSUE THREAD

**Issue by Gianluxx** [iTXTech/Genisys#1771]
* Genisys: Latest (of 23/8/2016)
* PHP: 7
* Server OS: ubuntu
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files
``` No one
```

Paintings despawn on my server. Idk how and why. Thanks.

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the F\[ine|\*\*\*\*\*\*\] FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
