### ISSUE TITLE
Player position stops updating after colliding in Spectator mode

### ISSUE THREAD

**Issue by udwarf** [iTXTech/Genisys#1772]
#### Issue description
When the player in the spectator mode and he goes through a block, the corresponding coordinate stops updating

#### Steps to reproduce the issue
I was using a simple plugin that handles PlayerMoveEvent and writes players position: $player->getPosition() all the time

1) switching to spectator mode: /gamemode 3
2) stand under any solid blocks (not nesessary right above the head)
3) start to move up

after colliding with the block  Y-coordinate stops updating!

The same situation when spectator collides with a block by X or Z coordinates

This behaviour could be eliminated by disablind calculateXOffset/calculateYOffset/calculateZOffset calls from Entity->move() function, but, i guess, its not the best way

#### OS and versions

* Genisys: Kyrios
* PHP: PHP 7.0.3
* Server OS: windows
* Game version: 0.15.2, 0.15.6

**Comment by dktapps** [comment]
This is intended I believe. It's what allows spectator to actually function. Spectator is really not much more than a collection of dirty hacks.
