### ISSUE TITLE
Not work wet farmland (Farmland + water)

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1773]
#### Issue description

Not work wet farmland (Farmland + water)

#### Steps to reproduce the issue

1. Use hoe, create farmland.
2. Place water

#### OS and versions
* Genisys: https://github.com/iTXTech/Genisys/tree/3d8f4377f30907ca8b01c2de6fcb7a7a477941c6
* PHP: 7.0.10 (Genisys script)
* Server OS: Ubuntu 14.04.4 LTS
* Game version: 0.15.6 (Windows 10 edition beta)

#### Crashdump, backtrace, memory dumps, plugins list or other files

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/17951599/a0b7024a-6a63-11e6-8c6b-510914198407.PNG)

**Comment by ishitatsuyuki** [comment]
Ambiguous description. Closing.
