### ISSUE TITLE
disconnectionScreen.notAuthenticated=Xbox login required translate not work

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1774]
#### Issue description

disconnectionScreen.notAuthenticated=Xbox login required translate not work

#### Steps to reproduce the issue

I changed Xbox login required text, and not see changed text.

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/3d8f4377f30907ca8b01c2de6fcb7a7a477941c6
* PHP: 7.0.10 (Genisys script)
* Server OS: Ubuntu 14.04.4 LTS
* Game version: 0.15.6 (Android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

![screenshot_20160825-021640](https://cloud.githubusercontent.com/assets/8324198/17952366/0af0343c-6a6a-11e6-8a0d-d400d03a2b31.png)

**Comment by ishitatsuyuki** [comment]
Since it's a client side translation.
