### ISSUE TITLE
[HELP NEEDED] CRASHES

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1775]
Crashes happen!!!!! KiK me at SuperDudeMCPE . Idk how to fix do anything about it... Plz reply!!!!!

**Comment by Leo3418** [comment]
Nobody can help you without detailed description or crash dumps.

**Comment by ishitatsuyuki** [comment]
Shut up!!!!! Idk what you really want to do... Let me give you a ban!!!!!
