### ISSUE TITLE
No sound when placing blocks

### ISSUE THREAD

**Issue by overmase** [iTXTech/Genisys#1777]
#### Issue description

When a player has placed a block, sound does not sound
#### Steps to reproduce the issue

1:  join in the world
2: Place the block

#### OS and versions

# Invalid version

* Genisys: latest source
* PHP: 7.0.2
* Server OS:Ubuntu 14.04.4 LTS
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Error did not go out
```

**Comment by dktapps** [comment]
Known issue, I'm currently looking into fixing it.

**Comment by dktapps** [comment]
Fixed in https://github.com/iTXTech/Genisys/commit/1dacf3560594e22d2d981b5a5742258e5c2c7fa0 but forgot to reference this issue. Closing.
