### ISSUE TITLE
PlayerDropItemEvent bug

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#1778]
event/player/PlayerDropItemEvent
when setCancelled(true)
drop entity not spawn is Ok.
but player package can't get this Drops back.

**Comment by ibookcc** [comment]
ITX version is #79 in Jen-build.

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the F\[ine|\*\*\*\*\*\*\] FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by dktapps** [comment]
Will you finally learn?
