### ISSUE TITLE
Inventory transaction additions

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1779]
Hello, this is just a humble request. Ever since InventoryTransactionEvent had a change, there have been many things I had to change, some of which, don't exist.
```
	public function onChestUse(InventoryTransactionEvent $event){
        $transactions = $event->getTransaction()->getTransactions();
        $inventories = $event->getTransaction()->getInventories();
```
...doesn't work anymore. I request someone to please add support for this.
**P.S:** _The changes to InventoryTransactionEvent have indeed made the game feel somewhat smoother, good job with that._
Peace. :+1:

**Comment by Muqsit** [comment]
```$transactions``` should be working, not sure about ```$inventories```.

**Comment by GenisysFTW** [comment]
yeah that's what I need

**Comment by dktapps** [comment]
API changes. But since you asked so nicely, I'll try and see what I can do.

Incidentally, you can simulate this by getting the inventory per-transaction component.
```
$inventories = [];
foreach($transaction->getTransactions() as $t){
    $inventories[] = $t->getInventory();
}
```

**Comment by GenisysFTW** [comment]
@dktapps Thank you soo much. You are a true legend. :D

**Comment by GenisysFTW** [comment]
faster than sanic.
