### ISSUE TITLE
不能用红石吗？

### ISSUE THREAD

**Issue by studentstudy11** [iTXTech/Genisys#178]
正在使用#34版，but 红石不能使用。已修改genisys.yaml。
or修改错了，应该修改哪里呢？

**Comment by CrayonDing** [comment]
请带Genisys.yml截图

**Comment by studentstudy11** [comment]
![1](https://cloud.githubusercontent.com/assets/8223268/12611763/6282d45c-c529-11e5-9d46-c634cef8dd33.PNG)
This

**Comment by CrayonDing** [comment]
关服之后再修改试试
