### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#1781]
#### Issue description

The first bug is the textformat reset don't reset in the second line

The second bug is when player consume more than 2 item in 1 slotbar such mushroom soup and potions, it consume all ,not consume 1
i have a clip to confirm it
http://sendvid.com/ncqzxcie

#### OS and versions

* Genisys:  a968deb5
* PHP: 7.0.8
* Server OS: Windows 10
* Game version:  Win10 Beta 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
First: https://github.com/iTXTech/Genisys/issues/1285
Second: invalid, you can't stack those regardless, following vanilla behaviour,  therefore that is not supported.
