### ISSUE TITLE
Memory leak [New Genisys Version]

### ISSUE THREAD

**Issue by lsw46** [iTXTech/Genisys#1783]
The server is open with no response, any command can not be used, the memory continues to increase

* Genisys: Newest
* PHP: 7.0.10
* Server OS: Windows Server 2008 R2
* Game version: 0.15.6

Without any crushdump and error

**Comment by ishitatsuyuki** [comment]
Follow the guidelines.

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
