### ISSUE TITLE
Second line of chat changes to bold characters

### ISSUE THREAD

**Issue by ABAxStorm** [iTXTech/Genisys#1784]
#### Issue description

The second line of chat always changes to bold text, without any way of changing it. This issue has been present for a long time throughout the Genisys versions. This is NOT related to any plugins. 
#### Steps to reproduce the issue

Type in chat enough to where there's at least two lines
Notice the bold text
#### OS and versions

* Genisys: e795eaa
* PHP: 7.0.8
* Server OS: Linux (Hosted by NetherBox) 
* Game version: 15.6 (Android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

![Image of Bug](http://i.imgur.com/vtQz2Oz.jpg)

**Comment by ABAxStorm** [comment]
Could #1285 be related to this? It didn't seem like it so I opened this.

**Comment by jojoe77777** [comment]
Double check your chat plugins; I have noticed that when I use §l, it only shows on the second/third/etc line

**Comment by ABAxStorm** [comment]
I use PureChat, but I only use it for the rank part.

**Comment by XFuryMCPE** [comment]
https://gyazo.com/c9e61bf8bc8833b546f2e6c62e635e4c
