### ISSUE TITLE
CRITICAL

### ISSUE THREAD

**Issue by iPeedroPvP** [iTXTech/Genisys#1787]
• Genisys 1.2dev-46_e795eaa (codename "Kyros")
• API: 2.0.0 (iTX API version 1.9.0)
Target client: Minecraft PE 0.15.4 alpha (protocol version 82)

" TOOLBOX IS BAD HACK!!!

The Hack Toolbox now has a new function to duplicate items ! I have a server that use the sofware of you Factions , as are more than 100 players all day always has a hack doubling your items to +99 , porfavor try to correct this serious mistake 'll be grateful ... or talk me a plugin blocks it!

**Comment by dktapps** [comment]
Stop issue spamming.
