### ISSUE TITLE
Error: "Call to a member function getHolder() on null" 

### ISSUE THREAD

**Issue by tigerza117** [iTXTech/Genisys#1789]
#### Issue description
Error: "Call to a member function getHolder() on null" 
code  function error https://github.com/Bluplayz/BedwarsPE/blob/master/src/Bluplayz/Bedwars.php#L857

#### OS and versions

* Genisys: master 8/26/2016
* PHP: 7.0.9
* Server OS: win server 2008
* Game version:  0.15

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
My bad. Dropping items is now also processed as a transaction, but without an inventory.

**Comment by tigerza117** [comment]
https://youtu.be/5HGPkyVYZ9E
