### ISSUE TITLE
Hackers use toolbox creative mode and place camera, and kill my world unknown block error... -.-

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1791]

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the F\[ine|\*\*\*\*\*\*\] FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
