### ISSUE TITLE
Use toolbox app place camera creative mode -> Dead my world and crash clients

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1792]
#### Issue description
Use toolbox app place camera in creative -> Dead my world and crash clients

#### Steps to reproduce the issue
1. Use Toolbox mod
2. Place camera creative
3. Crash client, and world chunk dead (load world -> client crash)

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/b4773fc89c65848d082321743a75c863154b6256
* PHP: 7.0.10 (Genisys script)
* Server OS: 14.04.4 LTS
* Game version: 0.15.6 (Windows 10 Editions beta, Android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

https://www.youtube.com/watch?v=oKU1VB3TroY&feature=youtu.be

Please help fix my world. :'(

**Comment by MichaelM04** [comment]
I can confirm this is a issue (happened to me once), but I'm not sure if they can fix this, the client is crashing, perhaps banning the id from being placed? But surely make backups of all your worlds.

**Comment by Yoyu666** [comment]
hope genisys add auto kick mcpe-modder(third-app) person,only original mcpe(real) can join only :+1: 
#allow modder app
 set : false

**Comment by legoboy0215** [comment]
It is not that easy to detect mods.

**Comment by Yoyu666** [comment]
@legoboy0215  i know,it is a great features :+1: 
btw long time no see u :P

**Comment by ZedCee** [comment]
The camera is actually a client related bug.  Unfortunately there's no way to really prevent placement.  You can however fix your map using [MCEdit](https://github.com/Khroki/MCEdit-Unified) and remove the entity manually.  
This is a peculiar client issue, but it shouldn't be able to save the entity, so we are looking into it.  Don't hold your breath, we'll see what we can do.

**Comment by dktapps** [comment]
This is related to #1206.  You may find a solution there, or check the FAQs in the wiki.

**Comment by dktapps** [comment]
I've fixed the issue causing crashes, but you'll still need to remove the unknown blocks from your world to get them working again. Refer to #1206 or the FAQs.
