### ISSUE TITLE
All stone stairs variants flammable

### ISSUE THREAD

**Issue by ZedCee** [iTXTech/Genisys#1796]
#### Issue description
All stone stair variants are flammable.
Place any stairs and set alight.
Stone, brick, netherrack, quartz, etc.

#### OS and versions
* Genisys: https://github.com/iTXTech/Genisys/commit/0054e25d3dd86f4bb8d5b8418e1db0bae2cdd9d7
* PHP: 7.0.9 (Arch)
* Server OS: Arch Linux
* Game version: 0.15.6 (iOS)

![image](https://cloud.githubusercontent.com/assets/20411465/18028443/781060ca-6c4d-11e6-9691-55798ebc39dc.png)
![image](https://cloud.githubusercontent.com/assets/20411465/18028444/78293942-6c4d-11e6-9a6c-092a37edd136.png)

**Comment by dktapps** [comment]
Well, fail hard. Will investigate.
