### ISSUE TITLE
no animals & no monsters 

### ISSUE THREAD

**Issue by AliMAltamimi** [iTXTech/Genisys#1797]
#### OS and versions

* Genisys:a9ee546
* PHP:php_7.0.10_x86
* Server OS:windows
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Very generic issue, lacks information. Please, elaborate.

**Comment by BobbyTowers** [comment]
You need to turn on the Mob spawning in the genisys.yml

**Comment by daniktheboss** [comment]
Are mobs still laggy tho?

**Comment by AliMAltamimi** [comment]
genisys.yml
        mobgenerate: true
server.properties
        spawn-animals=on
        spawn-mobs=on

still not work.

**Comment by LtanHonor** [comment]
Do not forget to check that your difficulty is *not* 0.  I had the same issue until I changed that to at least a 1.

**Comment by samalero** [comment]
and AI switch must set true
