### ISSUE TITLE
Debian x64 PHP binaries with XBOX auth needed

### ISSUE THREAD

**Issue by Bluscream** [iTXTech/Genisys#1798]
I need some compiled php binaries for debian x64 and ubuntu x86 thanks :)

**Comment by ABAxStorm** [comment]
You can ask questions on the chat, not here.

**Comment by ishitatsuyuki** [comment]
Read the rules. you will be banned next time.

**Comment by Bluscream** [comment]
I cant get banned lol

**Comment by Bluscream** [comment]
From github

**Comment by iPocket** [comment]
@dktapps

**Comment by daniktheboss** [comment]
He probably got banned XD

**Comment by Bluscream** [comment]
lul

**Comment by dktapps** [comment]
Hmm, seems I missed something
