### ISSUE TITLE
Item Frames Duplicate Items.

### ISSUE THREAD

**Issue by DylanAlexandre** [iTXTech/Genisys#1799]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DylanAlexandre** [comment]
The item fames once broken, tend to duplicate the objects inside them.

**Comment by ishitatsuyuki** [comment]
Improperly Formatted Issue Ticket - Lacks Information
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
