### ISSUE TITLE
Item Frame Duplication Bug

### ISSUE THREAD

**Issue by DylanAlexandre** [iTXTech/Genisys#1800]
The item frames seem to love duplicating whatever items go in it, when players break it the item stays in the frame but pops out to them and they can do this numerous of times.

Issue:
Item Fram duplication bug
1. Place item in frame
2. Take item out, item comes out and stays in frame but pops out of frame giving item
3. Free item to player.

Genisys: Most recent on Jenkins
Os: Ubuntu16.0
Php: 7
Game Version: 0.15.6

**Comment by ishitatsuyuki** [comment]
Latest is invalid. Don't spam issues.

**Comment by DylanAlexandre** [comment]
Fixed it myself since yall need so much info and are so strict about "templates" smh.
