### ISSUE TITLE
为什么一直提示：系统检测到你用了小号

### ISSUE THREAD

**Issue by lsw46** [iTXTech/Genisys#1804]
#### Issue description

一直提示：系统检测到你用了小号，进不去服务器
#### OS and versions

* Genisys:Genisys_Kyrios_a5fc45e
* PHP:PHP7.0.2
* Server OS:Windows 2008
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```木有报错...总是提示系统检测到你用了小号，换别的ID又可以了
```

**Comment by Yoyu666** [comment]
update u php
