### ISSUE TITLE
kick ban don't work

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1806]
on my server when kick a player is not kicking is still in server !?

**Comment by ZedCee** [comment]
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.  
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.  
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
