### ISSUE TITLE
Usage message for /cave is not displayed correctly

### ISSUE THREAD

**Issue by maxicusj** [iTXTech/Genisys#1808]
When issuing the /cave command a cave is not genrated and the following is displayed on the device screen: Usage: ommand.cave.usage

Steps to reproduce the issue

Type /cave in game

OS and versions

Genisys: a5fc45e
PHP: 7
OS: Raspbian

**Comment by ABAxStorm** [comment]
You probably didn't enter the args.

**Comment by maxicusj** [comment]
Ok, i see in code it expects 8 params. Help needs to be then updated. As well as the usage message.

Roman

**Comment by Dannyiy** [comment]
Try enabling force-language in pocketmine.yml, for me, it's work with that ;)
