### ISSUE TITLE
how to install Genisys in CentOS 7 with 19132

### ISSUE THREAD

**Issue by VCraftMCPE** [iTXTech/Genisys#1810]
Hello. i bought A VPS linux with CentOS 7 Operating System and i dont have any idea how to install Genisys in it with 19132 port please help

**Comment by daniktheboss** [comment]
Close issue, this is issues not help!

**Comment by daniktheboss** [comment]
Read issue template!

**Comment by Leo3418** [comment]
These questions belong to Gitter chat and IRC rather than issue tracker.
