### ISSUE TITLE
Level crash

### ISSUE THREAD

**Issue by marker98** [iTXTech/Genisys#1813]
My build battle server get crash with this dump. I dnt know what too do

Error: Call to a member function getName() on null
File: /src/pocketmine/level/Level
Line: 3021
Type: notice

Code:
[3012] 		return (int) $this->time;
[3013] 	}
[3014] 
[3015] 	/**
[3016] 	 * Returns the Level name
[3017] 	 *
[3018] 	 * @return string
[3019] 	 */
[3020] 	public function getName() : string{
[3021] 		return $this->provider->getName();
[3022] 	}
[3023] 
[3024] 	/**
[3025] 	 * Returns the Level folder name
[3026] 	 *
[3027] 	 * @return string
[3028] 	 */
[3029] 	public function getFolderName(){
[3030] 		return $this->folderName;
[3031] 	}

Backtrace:
#0 /src/pocketmine/Server(2981): pocketmine\Server->checkTickUpdates(integer 8068, double 1472539794.1465)
#1 /src/pocketmine/Server(2676): pocketmine\Server->tick(boolean)
#2 /src/pocketmine/Server(2554): pocketmine\Server->tickProcessor(boolean)
#3 /src/pocketmine/Server(2119): pocketmine\Server->start(boolean)
#4 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/bb1/, string /home/bb1/, string /home/bb1/plugins/, string unknown)

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
