### ISSUE TITLE
LoginPacket Issue

### ISSUE THREAD

**Issue by marker98** [iTXTech/Genisys#1815]
Sometimes i just got it.

Warning: zlib_decode(): data error in /home/2/src/pocketmine/network/protocol/LoginPacket.php on line 46

Warning: unpack(): Type V: not enough input, need 4, have 0 in /home/2/src/pocketmine/utils/Binary.php on line 343

Notice: Trying to get property of non-object in /home/2/src/pocketmine/network/protocol/LoginPacket.php on line 51

Warning: unpack(): Type V: not enough input, need 4, have 0 in /home/2/src/pocketmine/utils/Binary.php on line 343

Notice: Undefined offset: 1 in /home/2/src/pocketmine/network/protocol/LoginPacket.php on line 107

Notice: Undefined offset: 2 in /home/2/src/pocketmine/network/protocol/LoginPacket.php on line 107

**Comment by dktapps** [comment]
A 0.16 player attempted to join your server.
