### ISSUE TITLE
Feature request: Allow connection to multiple Synapse Servers

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1816]
Officially allowing connection to multiple Synapse Clients (2-3) would really help with lag issues, if I (Or another Nemisys user) were to host a big server network with only 1 Nemisys server, chances are it wouldn't go well, due to one proxy not being sufficient enough to handle all the players incoming. Though if we could connect to MULTIPLE servers, we could easily loadbalance the main IP address to cycle through the servers, thus allowing us to efficiently host a well balanced network without worrying about the proxy(s) being unable to hold the amount of traffic incoming. 

Please take this into consideration :D it would really help big server owners

**Comment by XFuryMCPE** [comment]
P.S. I tried sounding as professional as possible, adding as many details as possible so this wouldn't get closed for not having enough details.

**Comment by ishitatsuyuki** [comment]
I thought Nemisys should act as entry point and loadbalancing doesn't make sense... What's your opinion?

**Comment by minecrafter** [comment]
It looks like @XFuryMCPE wants to run multiple Synapse clients (Nemisys servers).

There are valid use cases for this, namely high-availability and scalability. However, for the last one, profiling and fixing scalability issues would be a much better use of time than implementing multi-client support.

**Comment by XFuryMCPE** [comment]
So what you're saying is, rather than allowing Synapse Clients to connect to more than one server, we should instead optimize Nemisys to hold more players? @minecrafter

**Comment by jojoe77777** [comment]
@minecrafter > would be a much better use of time than implementing multi-client support.

https://github.com/iTXTech/Genisys/pull/1754

**Comment by JUSTaMod** [comment]
this may be a bit off topic.... but how would one set up a Nemisys server on windows?

**Comment by ABAxStorm** [comment]
@JUSTaMod

https://mattermost.itxtech.org/itxtechnologies/channels/genisys
https://gitter.im/iTXTech/Genisys?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Or #genisys at freenode for questions

**Comment by PeratX** [comment]
The performance of php does not allow this. SynapseAPI has supported multi-server, use Nukkit + SynapseAPI + Nemisys instead.

**Comment by XFuryMCPE** [comment]
Reopen this issue. I was talking about Nemisys the whole damn time ... Update Nemisys and SynapseAPI at the same time

**Comment by XFuryMCPE** [comment]
They are called Synapse clients, so I'm going to call them that NOT because I'm using Synapse.

**Comment by Tarik02** [comment]
@PeratX, how about that i can't use nukkit? I'm want to use genisys, nukkit is not good for me.
