### ISSUE TITLE
I have no idea what this is but, its destroying my server

### ISSUE THREAD

**Issue by BudderSticks** [iTXTech/Genisys#1817]
My server cannot startup... Can not even restart. I found this error on console:

30.08 22:20:34 [Server] Server thread/CRITICAL pocketmine\utils\ServerException: "This build is not intended for production use. You may set 'settings.enable-testing: true' under pocketmine.yml to allow use of non-production builds. Do so at your own risk and ONLY if you know what you are doing." (EXCEPTION) in "/src/pocketmine/Server" at line 1831
30.08 22:20:34 [Server] INFO Warning: yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 36, column 1), context while scanning a simple key (line 34, column 1) in phar:///jar/genisys.phar/src/pocketmine/utils/Config.php on line 143

**Comment by XFuryMCPE** [comment]
Lol. You have syntax errors in your pocketmine.yml I'm assuming.

**Comment by BudderSticks** [comment]
@XFuryMCPE First, it is not funn, and second, how do I fix it?

**Comment by XFuryMCPE** [comment]
On line 36 of your Pocketmine.yml, there is a yaml parsing error. Go there and you'll most likely spot the mistake.

**Comment by dktapps** [comment]
Nice job reading the error.

**Comment by BudderSticks** [comment]
@XFuryMCPE Thank you, I will check it out.

**Comment by BudderSticks** [comment]
That is my line 36. How is that a error? Do you want me to change it to a dofferent number?

![image](https://cloud.githubusercontent.com/assets/20302875/18117457/c4fe1c34-6f03-11e6-9427-ccc9205c08a2.png)

**Comment by BudderSticks** [comment]
And no change, I disabled the continuous trigger rate off, I will also try to change the number...

**Comment by BudderSticks** [comment]
Nothing changed

**Comment by BudderSticks** [comment]
Maybe wrong line?

**Comment by SleepSpace9** [comment]
Let us see your whole file contents?

**Comment by BudderSticks** [comment]
Okay, do you want me to copy n paste? Or send a link. I will send a link...

**Comment by SleepSpace9** [comment]
do a copy&paste and use styling with ```

**Comment by BudderSticks** [comment]
Okay

**Comment by BudderSticks** [comment]
'# Main configuration file for PocketMine-MP
# These settings are the ones that cannot be included in server.properties
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading.

settings:
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 #When server shut down, the players will get kicked and this is what will show on there screen.
 shutdown-message: "Server closed"
 #Allow listing plugins via Query
 query-plugins: true
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: true
 #Enable plugin and core profiling by default
 enable-profiling: false
 #Will only add results when tick measurement is below or equal to given value (default 20)
 profile-report-trigger: 20
 #Number of AsyncTask workers.
 #Used for plugin asynchronous tasks, world generation, compression and web communication.
 #Set this approximately to your number of cores.
 #If set to auto, it'll try to detect the number of cores (or use 2)
 async-workers: 4

#Global soft memory limit in megabytes. Set to 0 to disable
#This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
global-limit: 2048

#Main thread soft memory limit in megabytes. Set to 0 to disable
#This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
main-limit:4000

#Period in ticks to check memory (default 1 second)
check-rate: 20

#Continue firing low-memory-triggers and event while on low memory
continuous-trigger: true

#Only if memory.continuous-trigger is enabled. Specifies the rate in memory.check-rate steps (default 30 seconds)
continuous-trigger-rate: 60

garbage-collection:
#Period in ticks to fire the garbage collector manually (default 30 minutes), set to 0 to disable
#This only affect the main thread. Other threads should fire their own collections
period: 36000

#Fire asynchronous tasks to collect garbage from workers
collect-async-worker: true

#Trigger on low memory
low-memory-trigger: false

max-chunks:
#Limit of chunks to load per player, overrides chunk-sending.max-chunks
trigger-limit: 96

#Do chunk garbage collection on trigger
trigger-chunk-collect: true

#Trigger on low memory
low-memory-trigger: false

world-caches:
disable-chunk-cache: false
low-memory-trigger: false

network:
#Threshold for batching packets, in bytes. Only these packets will be compressed
#Set to 0 to compress everything, -1 to disable.
batch-threshold: -1
#Compression level used when sending batched packets. Higher = more CPU, less bandwidth usage
compression-level: 16
#Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
async-compression: true
#Experimental, only for Windows. Tries to use UPnP to automatically port forward
upnp-forwarding: false

debug:
#If > 1, it will show debug messages in the console
level: 1
#Enables /status, /gc
commands: true

level-settings:
#The default format that levels will use when created
default-format: mcregion
#If true, converts from a format that is not the default to the default format on load
#NOTE: This is currently not implemented
convert-format: false
#Automatically change levels tick rate to maintain 20 ticks per second
auto-tick-rate: true
auto-tick-rate-limit: 5
#Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
base-tick-rate: 1
#Tick all players each tick even when other settings disallow this.
always-tick-players: false

chunk-sending:
#Amount of chunks sent to players per tick
per-tick: 2
#Amount of chunks sent around each player
max-chunks: 192
#Amount of chunks that need to be sent before spawning the player
spawn-threshold: 56
#Save a serialized copy of the chunk in memory for faster sending
#Useful in mostly-static worlds where lots of players join at the same time
cache-chunks: true

chunk-ticking:
#Max amount of chunks processed each tick
per-tick: 0
#Radius of chunks around a player to tick
tick-radius: 3
light-updates: true
clear-tick-list: true

chunk-generation:
#Max. amount of chunks in the waiting queue to be generated
queue-size: 8
#Max. amount of chunks in the waiting queue to be populated
population-queue-size: 8

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15

auto-report:
 #Send crash reports for processing
 enabled: false
 send-code: true
 send-settings: true
 send-phpinfo: false
 host: crash.pocketmine.net

anonymous-statistics:
 #Sends anonymous statistics for data aggregation, plugin usage tracking
 enabled: true
 host: stats.pocketmine.net

auto-updater:
 enabled: false
 on-update:
  warn-console: false
  warn-ops: false
 #Can be development, beta or stable.
 preferred-channel: beta
 #If using a development version, it will suggest changing the channel
 suggest-channels: false
 host: www.pocketmine.net

aliases:
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)'

**Comment by SleepSpace9** [comment]
#Main thread soft memory limit in megabytes. Set to 0 to disable
#This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
**main-limit:4000**

**Comment by BudderSticks** [comment]
Okay, you want me to change that number?

**Comment by SleepSpace9** [comment]
no, only insert a blank like this:
```main-limit: 4000```

**Comment by BudderSticks** [comment]
Nvm, I think I have founs bug

**Comment by BudderSticks** [comment]
Okay

**Comment by BudderSticks** [comment]
No change -_-

**Comment by SleepSpace9** [comment]
The error message says the same line number?

**Comment by BudderSticks** [comment]
Yes, line 36 and column 1

**Comment by BudderSticks** [comment]
This is really starting to irritate me XD

**Comment by SleepSpace9** [comment]
How about renaming your original pocketmine.yml and recreate a new one by starting the server?
After this you can edit the lines you need to change (carefully :wink:).

**Comment by BudderSticks** [comment]
But, will tjese reset my data?

**Comment by BudderSticks** [comment]
This*

**Comment by BudderSticks** [comment]
And sorry for bugging you, I am very new to servers

**Comment by SleepSpace9** [comment]
Yes, reset to default values and hopefully correct in yaml syntax.
Btw your pasted file contents doesn't have a leading space at any line. I don't know whether it's from pasting here or from your file. Maybe you can also upload a copy of the original file.

**Comment by BudderSticks** [comment]
Hmm, I am talking about my server data like plugins, and worlds... I do not think it will reset correct? Because those files are seperate. (I just wanna make sure)

**Comment by BudderSticks** [comment]
I deleted poketmine.yml and no change at all

**Comment by SleepSpace9** [comment]
So I would suggest you to download a new phar from GitLab CI or Jenkins and pay attension to use a build from the **master** branch.

**Comment by BudderSticks** [comment]
Umm, I dont think I can do that. I use a host called netherbox and I dont think I can upload a new pocketmine.yml

**Comment by BudderSticks** [comment]
Heres the funny thing, when I switch my sevrer jar over to pocketmine php7 0.150, server can turn online... I think this is probably probablem eith genisys

**Comment by SleepSpace9** [comment]
Oh, I wanted you to download a new copy of the Genisys build (e.g. https://gitlab.com/itxtech/genisys/builds/3562654/artifacts/download). But if you can't even upload a pocketmine.yml you have to ask your netherbox service desk.

**Comment by BudderSticks** [comment]
I think i can upload one but, is the thing i just downloaded from ur link a pocketmine.yml or a new genisys?

**Comment by dktapps** [comment]
Please take this discussion somewhere else and stop spamming others' (and my) notifications.
