### ISSUE TITLE
Mob issues

### ISSUE THREAD

**Issue by SuperDudeMCPE** [iTXTech/Genisys#1821]
#### Issue description
When you spawn a mob, not only you can not hurt it, but leads are connected to the mob.

#### Steps to reproduce the issue
Place down a spawn egg. Try to hit the mob. And now look at the leads connecting.

* Genisys: d181790
* PHP: 7
* Server OS: Mac
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Ban evasion. Closing.
