### ISSUE TITLE
PhP 7.10

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1822]
how I do update php to 7.10 on multicraft ?

**Comment by Muqsit** [comment]
**Please** use the gitter chat (read the description) for such questions. Note that this section is dedicated to ISSUES and ISSUES only.

**Comment by MCPEPluginer16** [comment]
I dont play Minecraft for 40 days I lost the all idea of servers !

**Comment by Muqsit** [comment]
Sorry, you can only blame yourself for that.
