### ISSUE TITLE
kick ban error

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1827]
Warning: unpack(): Type V: not enough input, need 4, have 0 in phar:///jar/versions/Genisys/Genisys_752282b.phar/src/pocketmine/utils/Binary.php on line 343
01.09 22:55:26 [Server] INFO Notice: Undefined offset: 1 in phar:///jar/versions/Genisys/Genisys_752282b.phar/src/pocketmine/network/protocol/LoginPacket.php on line 107
01.09 22:55:26 [Server] INFO Notice: Undefined offset: 2 in phar:///jar/versions/Genisys/Genisys_752282b.phar/src/pocketmine/network/protocol/LoginPacket.php on line 107

when I kicked a player is spam this on consel

**Comment by XFuryMCPE** [comment]
**Improperly Formatted Issue Ticket - Lacks Information**

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by XFuryMCPE** [comment]
++ Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by XFuryMCPE** [comment]
# Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by XFuryMCPE** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by ABAxStorm** [comment]
You already posted an issue on this.

**Comment by dktapps** [comment]
A 0.16 player attempted to join your server.  Also, @XFuryMCPE got the issue template thing, thanks. Aaaaan that issue was fixed a couple of days ago. So you're out of date. (^_^)

(When will people learn.)
