### ISSUE TITLE
"Fake" player count

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#1828]
#### Issue description

I always get the players bug whenever i leave my server up for 1 day or more. It says server is full although its only 30/70 people, the player list is full of offline players.

#### Steps to reproduce the issue

Don't actually know. Just leave your server for some days. (I don't think this is a nice reproduce way lol)

#### OS and versions

* Genisys: 1.2dev-24_c19e850
* PHP: 7.3 (?)
* Server OS: CentOS 7
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by GlitchPlayer** [comment]
Players who leave the server still stays on the player list.

**Comment by dktapps** [comment]
That version is well outdated. Please update and try and reproduce with an up-to-date version.

**Comment by TDMidkwhatisxd** [comment]
I got same bug , but only wen i used a plugin to kick players on join without cancel events!
So check your plugins!

**Comment by XFuryMCPE** [comment]
Yeah, if you kick a player on join or prelogin etc without cancelling the event, the player still connects to the server, while the actual client isn't connected.

**Comment by GenisysFTW** [comment]
This happened to me in a 4 day ago build but was fixed later the same day.

**Comment by intagaming** [comment]
Hnmm i think that's my plugin problem though (?) Will check later!
