### ISSUE TITLE
Respawn Grass not works?

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#183]
![image](https://cloud.githubusercontent.com/assets/6584811/12639803/376f953a-c5c8-11e5-9ffd-de63bbd1dca3.png)

**Comment by PeratX** [comment]
Not implemented..

**Comment by thebigsmileXD** [comment]
Actually........ coded it ages ago. I made a PR to PocketMine once. Grass will spread and die like in PC version
But its a bit slow. Maybe do a copy of the code in ClearSky?

**Comment by thebigsmileXD** [comment]
https://github.com/PocketMine/PocketMine-MP/pull/3724

**Comment by PeratX** [comment]
Changed chunk.per-tick: and chunk.radius to a non-zero number
