### ISSUE TITLE
I find a bug ，the players can get many item by cheat。我希望你能快点修复，这段英文写得好辛苦。

### ISSUE THREAD

**Issue by WaiMen** [iTXTech/Genisys#1831]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by dog194** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
/你需要填写你用的核心版本号(最新不是不被接受的)，PHP版本，游戏客户端类型版本(MCPE 0.xx.xx/ WIN10PE 0.xx.xx)。以及插件列表(如果需要)。跟问题是如何发生的，重现该问题的步骤如何。
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
/一个编写好的模板已经提供在issue编辑框。如实填写已方便我们对问题进行查找测试及最终解决。
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
/总之，没有具体信息的issue往往会被直接关闭。同时反复开启issue的用户将会被丢出去。

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

PS 你就说发现一个bug，其他什么都没有，你当劳模是神么。直接透过现象看本质？

**Comment by gaoyichuan** [comment]
如果你不会英语，用中文比你写一段糊里糊涂的英文要好得多

**Comment by ExerciseBook** [comment]
是不是有人会帮忙翻译。。。【貌似开发组也有中国人吧

**Comment by gaoyichuan** [comment]
我们基本都是中国人

2016年9月3日 20:43，"Eric_Lian" <notifications@github.com>写道：

**Comment by ishitatsuyuki** [comment]
实验证明你不会更新

**Comment by PeratX** [comment]
刷一下存在感
