### ISSUE TITLE
Player easy to get all item by cheat

### ISSUE THREAD

**Issue by WaiMen** [iTXTech/Genisys#1832]
#### Issue description

The bug is some player can get a lot of item by cheat,I find one of the player and talk ,he say he can easy to get all of the item.Then I change to clearsky.phar.Then he tell me he can't get all of the item.
I think ITX have bug,It can't anticheat,so please hurry to fix this.
#### OS and versions

* Genisys:  1.2dev-24_c19e850
* PHP: 7
* Server OS: 6.4
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
Server OS again??

**Comment by Leo3418** [comment]
If your player is using Toolbox, using Xbox Live authentication can block Toolbox.

**Comment by WaiMen** [comment]
But many player are using xbox ,if use the xbox live authentication，the server will have no people.can you fix this bug(like the clearsky and 官方核心）

**Comment by dktapps** [comment]
This is nonsense. Our anti-cheat is the strongest there is (after the Win10 Update). Also, you're waaaaaaay out of date.
