### ISSUE TITLE
FEATURE REQUEST: Upon level change, send loading world screen

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1834]
I have been experimenting for awhile, and so far, the best way to do this without the player glitching out:

`//First sending
$dimension0 = new ChangeDimensionPacket();
$dimension0->dimension = 0;
$p->dataPacket($dimension0);

$status1 = new PlayStatusPacket();
$status1->status = 3;
$p->dataPacket($status1);

$dimension1 = new ChangeDimensionPacket();
$dimension1->dimension = 1;
$p->dataPacket($dimension1);

$status2 = new PlayStatusPacket();
$status2->status = 3;
$p->dataPacket($status2);

//Send player to level

//Second sending
$dimension3 = new ChangeDimensionPacket();
$dimension3->dimension = 1;
$p->dataPacket($dimension3);

$status3 = new PlayStatusPacket();
$status3->status = 3;
$p->dataPacket($status3);

$dimension4 = new ChangeDimensionPacket();
$dimension4->dimension = 0;
$p->dataPacket($dimension4);

$status4 = new PlayStatusPacket();
$status4->status = 3;
$p->dataPacket($status4);`

This will send the generating terrain screen, but I have encountered that when doing this, sometimes it sends the opposite colored sky of what the previous world had, but I'm pretty sure you guys can fix this. I ported this code from MiNET's spawn level function (https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Player.cs#L634)

**Comment by dktapps** [comment]
This was previously attempted and was shelved due to many issues.

**Comment by XFuryMCPE** [comment]
fastest close yet xd
