### ISSUE TITLE
Feature Request: New function in PlayerItemHeldEvent.

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1835]
Hi there,
This is a small feature request. It's okay if it isn't possible, but anyways...
In EntityArmorChangeEvent, there's a nice little ```getOldItem()``` function that I really like. I was just thinking if you can implement this into PlayerItemHeldEvent, it would be really amazing and perhaps, would save me out on scheduling repetitive tasks.

Peace. :+1:

**Comment by ishitatsuyuki** [comment]
I believe that the event is called before the player data change with the new data in the event object. Please consider if that match your requirement.

**Comment by dktapps** [comment]
@ishitatsuyuki is right. This is redundant, because you can get the previously selected slot number by using `getHeldItemIndex()` and `getItemInHand()` to get the item. Changes are only made once all plugins have finished handling the event.
