### ISSUE TITLE
Genisys wont work?

### ISSUE THREAD

**Issue by VCraftMCPE** [iTXTech/Genisys#1840]
#### Issue description

bin\php\php.exe: Exit 127C:/Users/VCraft/Downloads/Genisys/Genisys-master/Genisys-master/bin/php/php.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
#### OS and versions

* Genisys:e67d863
* PHP:7.0.10
* Server OS:Windows 10
* Game version: 15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Your brain don't work. Read guidelines.

**Comment by VCraftMCPE** [comment]
->- yours

**Comment by ishitatsuyuki** [comment]
Wow! A great site! google.com

**Comment by dktapps** [comment]
[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by PeratX** [comment]
Please install VC++ 2015 RP before
