### ISSUE TITLE
addEffect() issue.

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1841]
#### Issue description
Well, addEffect() doesn't go smooth with EntityArmorChangeEvent when the player joins the server.

#### Steps to reproduce the issue
P.S: Sorry for the cancerous code formatting. I formatted it on GitHub via my phone.
```
	public function whileArmoured(EntityArmorChangeEvent $e){
		$i = $e->getNewItem();
		$o = $e->getOldItem();
		$p = $e->getEntity();
	        if($i->getId() == 310){//If player has equipped a diamond helmet.
		  $p->addEffect(Effect::getEffect(1)->setDuration(999999999)->setVisible(false)->setAmplifier(1));
	         }
	    }
```
Now, equip a diamond helmet. It will give you speed. Okay. Cool. Smooth.
But now, quit the server, and join back. It will show an error in the console.

#### OS and versions
* Genisys: e67d863
* PHP: 7.0.10
* Server OS: Ubuntu 14.04 LTS (64-bit)
* Game version: 0.15.6 and 0.15.7

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Call to undefined function getValue() on null in pocketmine/entity/Effect.php at line 310
```

**Comment by GenisysFTW** [comment]
Does the "This doesn't happen on CS" fix work? :3

**Comment by thebigsmileXD** [comment]
@GenisysFTW what

**Comment by GenisysFTW** [comment]
This bug is cannot be reproduced anymore. Closing..
