### ISSUE TITLE
[VOTE] MyOwnWorld based AI removal

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1842]
This is a poll for the future of the MyOwnWorld based AI currently in Genisys. I want to remove the current AI.

### Reasons:
- because it's a disgusting, buggy mess, not worthy to be included in our server software
- it's some of the worst code I've ever had the misfortune to work with
- it's not GPL licensed and therefore should not be included in a GPL-licensed software
- if you want MOW AI, you can use MOW itself (https://github.com/zzm317/MyOwnWorld).

### Wait, the AI will be removed?
The current horrible AI will be replaced at a later date by a more advanced, much cleaner and nicer AI. I have plans to write new AI in the future.

### How do I vote?
Simply add a reaction to this issue.
- :+1: : Remove the AI
- :-1: : keep it

**Comment by ZedCee** [comment]
:+1:

**Comment by ABAxStorm** [comment]
How long would it take for the new AI when you start writing it?

**Comment by dktapps** [comment]
@abaxstorm Intelligent people don't ask for ETAs :P

**Comment by ABAxStorm** [comment]
@dktapps I just meant how long it takes generally to write an AI :p

**Comment by dktapps** [comment]
@abaxstorm I don't "generally" write AI.

**Comment by ABAxStorm** [comment]
Ok whatever nevermind

**Comment by xHFx** [comment]
Damn @dktapps being an ass much

**Comment by dktapps** [comment]
¯\_(ツ)_/¯ Ask dumb questions and you'll get dumb answers.

**Comment by ABAxStorm** [comment]
@dktapps It wasn't dumb, you guys are just dicks. Screw Genisys.

**Comment by thebigsmileXD** [comment]
Seems like the decision won't be hard.

**Comment by dktapps** [comment]
@thebigsmileXD lmao, so it seems 😂

**Comment by JUSTaMod** [comment]
aye. enhancement is a proper label. the 36 up-votes and the one laugh emoji (not sure what that's doing there) pretty much confirms it.

**Comment by xHFx** [comment]
So no mob ai at all

**Comment by dterweij** [comment]
Leave it until there is a new AI system.
By removing it stops me for using newer Genisys builds. My kids love them and we use it with killrate stats so we see how many mobs we have killed :P

**Comment by thebigsmileXD** [comment]
Quote:
if you want MOW AI, you can use MOW itself (https://github.com/zzm317/MyOwnWorld).

**Comment by dterweij** [comment]
NOW does not work!!!!

```
[22:54:23] [Server thread/INFO]: Loading source plugin MyOwnWorld v1.0.0
PHP Fatal error:  Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in /home/danny/minecraft-pe/plugins/MyOwnWorld/src/MyOwnWorld/MyOwnWorld.php on line 28

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in /home/danny/minecraft-pe/plugins/MyOwnWorld/src/MyOwnWorld/MyOwnWorld.php on line 28
[22:54:23] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[22:54:23] [Server thread/EMERGENCY]: Please upload the "/home/danny/minecraft-pe/crashdumps/CrashDump_Thu_Sep_8-22.54.23-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

```

**Comment by dterweij** [comment]
Note:
Use the fork: https://github.com/kniffo80/MyOwnWorld  it states PHP7 ready and a lot changes.

**Comment by dterweij** [comment]
Okay that fork is not working. Server starts, plugin is loaded bu client can not join the server. No debug output on console. So MOW original and the fork are not working.

You should have test that before announcing to use MOW :)

**Comment by psycholyzern** [comment]
@dterweij I dont know php much, this is my working forked MOW - https://github.com/psycholyzern/MyOwnWorld/

Skeleton wont shoot from far, creeper wont explode, too many mobs/animals spawned (maybe?).
Well, atleast they will spawn 😅😅

Idk how to fix those problems because I code using my phone. Opening files with long code would lag my browser, so I cant do make some reference. This is my limit, hope it will help some people until Genisys team implement a new AI.

**Comment by dterweij** [comment]
Thanx @psycholyzern I go try it now.
