### ISSUE TITLE
Spectator mode

### ISSUE THREAD

**Issue by GlitchPlayer** [iTXTech/Genisys#1843]
#### Issue description

When you change into spectator mode, your GUI won't disappear.
#### Steps to reproduce the issue

Go to /gamemode 3
Notice it
#### OS and versions

* Genisys: ce14320
* PHP: 7.0.9
* Server OS: Windows 10
* Game version: 0.15.7 (Win10), 0.15.6 (Android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ABAxStorm** [comment]
Go into Settings to turn off your GUI.

**Comment by GlitchPlayer** [comment]
I know, but it hides some popups

**Comment by dktapps** [comment]
This cannot be done since it isn't supported by the client.
