### ISSUE TITLE
Leggins don't return true on isLeggings()

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#1851]

**Comment by dktapps** [comment]
Any specific type of leggings? I can't find any issue.

**Comment by dktapps** [comment]
Those methods may be removed anyway. They're kind of stupid to be honest.

**Comment by thebigsmileXD** [comment]
@dktapps kind of nice to have them, faster code for equipping mobs/players because you don't have to check every single piece of armor.

**Comment by dktapps** [comment]
Fair enough
