### ISSUE TITLE
Players set you on fire when they are burning

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#1854]
Thats totally not a vanilla thing, only mobs burning in sunlight (or simply burning) cause the player which they attack to burn.

**Comment by JUSTaMod** [comment]
you know... it does make sense for other players to set you on fire.  goddammit Microsoft.

**Comment by thebigsmileXD** [comment]
Its not vanilla so remove. If you wan't it, code it in a plugin.

**Comment by diamond-gold** [comment]
Its already like that since pocketmine lol

**Comment by thebigsmileXD** [comment]
nope

**Comment by IrishUHC** [comment]
this is actually a feature in vanilla, please reassess your statement.

**Comment by GlitchPlayer** [comment]
@IrishUHC No, it isn't it. Try doing it on single player

**Comment by ishitatsuyuki** [comment]
It only applies to zombie, IIRC.

**Comment by IrishUHC** [comment]
I was sure it applied to players, I knew it works for zombies, skeletons, etc. hm guess I'm wrong.

**Comment by thebigsmileXD** [comment]
Players dont burn something else.
