### ISSUE TITLE
The default nether world in genisys.yml generates using the normal generator

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#1855]
when generating the default nether world, you get a red sky, but its green everywhere. Can't handle all this salad..
What i did: genisys.yml->nether->"nether"
joined the server
buildt a portal
stopped the server and removed the world
started and joined the nether world
genisys knows its the nether sky but uses the survival normal generator with grass etc.

**Comment by dktapps** [comment]
That's a very peculiar bug, haven't been able to reproduce it. Will investigate.

**Comment by thebigsmileXD** [comment]
Tried to reproduce, for some reason i now spawn in the main level if nether is missing. Will investigate.

**Comment by PeratX** [comment]
Cannot be reproduced. If you have defined the generator in other plugins or in pocketmine.yml, it will overwrite the default settings.

**Comment by PeratX** [comment]
Remove the world, including the level.dat.

**Comment by thebigsmileXD** [comment]
I tested something. when there is nether: [] in default-levels in pocketmine.yml it will generate as normal world. Maybe it should override it to nether generator by default if its called "nether"?

**Comment by dktapps** [comment]
Well, that would explain the issue. I'm going to upgrade the world link-up format soon anyway, will also be able to resolve this.

**Comment by dktapps** [comment]
TODO: Merge configs and get rid of the ugly mess that is genisys.yml

**Comment by ZedCee** [comment]
Can't seem to reproduce this.  Albeit, I have plenty of salad in my nether on purpose.

 _**@dktapps I can't agree more that some consolidation needs to be done**_
