### ISSUE TITLE
3 layers mossy cobblestone in taiga

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#1856]
Mossy cobblestone is found in pieces, not under 2 layers of podzol. The second layer in the taiga also should be dirt, not podzol.

**Comment by GenisysFTW** [comment]
Wrong. It can even be stone or stone variants (granite, andesite or diorite).

**Comment by thebigsmileXD** [comment]
@GenisysFTW i meant those: https://fbcdn-sphotos-f-a.akamaihd.net/hphotos-ak-prn2/1412569_688779761140444_1525652280_o.jpg are correct.
(only generate like this though: 
![image](https://cloud.githubusercontent.com/assets/8733998/18242466/bd5d606e-7356-11e6-86c2-12e543b6fbbf.png))

This instead is 100% wrong: 
![image](https://cloud.githubusercontent.com/assets/8733998/18242489/d8ec22b6-7356-11e6-9071-cec921d67f11.png)
