### ISSUE TITLE
[REQUEST] Update Genisys/Nemisys to More Stability

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys#1858]
#### Issue description

Fix Error, please, my network is crashed :(

#### Steps to reproduce the issue

![image](https://cloud.githubusercontent.com/assets/15146680/18234511/a25338a2-72de-11e6-96f7-84c9e000ca5a.png)

#### OS and versions

* Genisys: Nemisys.jar(last version)
* PHP: Java 8
* Server OS: 0.15.6/9
* Game version: 0.15.7/9
* Host Ram: 4gb, 6 cores

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
No detail provided. This is considered as spam.

**Comment by RedstoneAlmeida** [comment]
não é spam filho da puta

**Comment by RedstoneAlmeida** [comment]
lixo
