### ISSUE TITLE
New code name for incoming 0.16 version of Genisys

### ISSUE THREAD

**Issue by PeratX** [iTXTech/Genisys#1868]
## Why post this "issue"
As we all know, 0.16 is on its way. So Genisys is going to have an update like 0.14 to 0.15.
## How to post your opinion
(Your code name): Reason
## How to vote
Just use :+1:  or :-1: on your name of choice.

**Comment by PeratX** [comment]
Asteria: Hope of light

**Comment by daniktheboss** [comment]
Moonlight: sound cool I guess... and

**Comment by XFuryMCPE** [comment]
Harambe: He needs recognition and should be the new codename

**Comment by dktapps** [comment]
You're voting for your own names? Pfft. That's just cheating.

**Comment by XFuryMCPE** [comment]
lmao

**Comment by PeratX** [comment]
gg

**Comment by dktapps** [comment]
¯\_(ツ)_/¯

**Comment by dondre** [comment]
Flatiron: District in the 16th block of Manhattan

**Comment by JUSTaMod** [comment]
right now the original post has the most up-votes.... does the whole paragraph become the codename if it wins? that would be interesting.

:0

**Comment by dktapps** [comment]
Katharos

Greek for "clean". With reference to the fact I'm giving the core the nuclear treatment, stripping the s\*\*\* out of it and returning it to a clean code base. Result: a lighter, faster, cleaner server core.

**Comment by daniktheboss** [comment]
👍 to dkapps

**Comment by dschwartz783** [comment]
Genisys SP1
Sorry... I channeled my inner Microsoft there for a moment.

Hexigen: Version 16, and base 16 is hexadecimal, + gen from genisys. Seems to make sense. :D

**Comment by legoboy0215** [comment]
isithuthukisi: Enhancement in Zulu and looks like @ishitatsuyuki

**Comment by dktapps** [comment]
...

**Comment by legoboy0215** [comment]
MPGA: Make PocketMine great again! 

FirstGenBoss? First of the Boss Updates, and with Gen for genisys.

No, those were obviously jokes, but why not consider them?

**Comment by dktapps** [comment]
@legoboy0215 This is Genisys, not PocketMine. Genisys is way too messy to do that, and plus it's a spoon, not a fork. However, I have plans to change that.

**Comment by legoboy0215** [comment]
Actually, to me it is a knife, not yet a fork but not a spoon ;)

**Comment by dktapps** [comment]
That's somewhat disturbing. I refer to it as a spoon, because that's what the PocketMine team calls us.

**Comment by legoboy0215** [comment]
Agreed. GitHub should add a Spoon button. Back to the topic, I kinda have a question for everyone. Who named it Genisys? What was the reasoning behind it?

**Comment by dktapps** [comment]
@PeratX did. Why, I have no idea. I might also observe that it's also the name of an operating system developed by Cyberdyne in Terminator. :P

**Comment by psycholyzern** [comment]
I really like "Katharos". Just because greek always suitable to name any awesome things😊
Plus, it sounds right with previous codename which is Kyrios is Im not mistaken?

**Comment by dktapps** [comment]
@psycholyzern we do seem to have a Greek trend. Ikaros, Kyrios, Katharos, Aegis (Nemisys current codename)

(P.S. Kyrios was my idea too :D)

**Comment by JackboyPlay** [comment]
Zystelix

**Comment by TheProest35YT** [comment]
Mystical . Maybe

**Comment by Muqsit** [comment]
Mystic is way too overused and common.
(OffTopic: Can anyone find out what sound packet 1060 is? It sounds like a human being tortured).

**Comment by dktapps** [comment]
@Muqsit that's LevelEvent, not sound. And afaik 1060 doesn't have a sound? What data value did you send?

**Comment by TheProest35YT** [comment]
Intactical maybe ?

**Comment by TheProest35YT** [comment]
Or Karachi

**Comment by Muqsit** [comment]
```php
const EVENT_SOUND_COOL = 1060;
```
That's what I used and it sounds really strange.

**Comment by dktapps** [comment]
@Muqsit I wrote a plugin for this a while ago. I pushed source to GitHub today (you reminded me :P). Here: https://github.com/dktapps/leveleventfinder

**Comment by Muqsit** [comment]
@dktapps omg xD...you know what...I'll just make a simple sound discoverer.

**Comment by Muqsit** [comment]
@dktapps https://github.com/Muqsit/SoundDiscovery
/sound.
Looks like a pig sound but it's a little more exaggerated.

**Comment by dktapps** [comment]
yeah, I though that @Muqsit , but it's too protracted. Lol

**Comment by XFuryMCPE** [comment]
that sound is creepy o_o

**Comment by dondre** [comment]
PMS.16 - Pocket Mine Spoon 16

**Comment by mhsjlw** [comment]
Irrlicht, from google:

> Irrlicht, the German name for will-o'-the-wisp, the ghostly light sometimes seen at night over bogs and swamps.

**Comment by dschwartz783** [comment]
@dondre Are you sure that's what PMS means...? :o

**Comment by Infernus101** [comment]
Fukkit: Fork of Nukkit

**Comment by GlitchPlayer** [comment]
@Infernus101 xD

**Comment by dktapps** [comment]
Removed an inappropriate stupid comment. That comment didn't make any sense at all.

**Comment by thebigsmileXD** [comment]
Call it Banana. #BananasForHarambe.
> @dktapps : Greek for "clean".

:D i understand that joke.

**Comment by KairusDarkSeeker** [comment]
Namsuke: #HarmbeIsBae

**Comment by Muqsit** [comment]
Okay, can we all stop the Harambe thing? You all tried acting cool! GG.

**Comment by Muqsit** [comment]
How about...Universal Remote.
:3

**Comment by AryToNeX** [comment]
Light of Zeus
Again

**Comment by KairusDarkSeeker** [comment]
Hydrophathic: Zeus
👍

**Comment by thebigsmileXD** [comment]
This vote now should be closed and the result chosen.

**Comment by TheClimbing** [comment]
CyberNet? Anyone? Terminator?

**Comment by KairusDarkSeeker** [comment]
Delta, Alpha

**Comment by dktapps** [comment]
@thebigsmileXD 0.16 is not released yet. And Genisys is not ready for 0.16 either.

**Comment by dktapps** [comment]
Seems that right now it's a tie between Katharos and the contents of @PeratX 's initial post. This is going to be fun :laughing:

**Comment by Thunder33345** [comment]
If i am begin honest we should have a thread for strictly voting and another for discussion it makes it hard for others who just want to vote hard to vote

**Comment by thebigsmileXD** [comment]
@dktapps well, except when you don't count "vote your own post"

**Comment by dktapps** [comment]
@thebigsmileXD heh. Well, the tie has been broken.

**Comment by IrishUHC** [comment]
Exelixi: Greek word for evolution, as Genisys is evolving and getting better.

**Comment by MajorPlayz** [comment]
I think that dekaxi as it is a spin off of the greek word for 16 (0.16) but also Genisys is a _sort of_ a spin off of PocketMine-MP _(Genisys is **better** than a spin off XD)_

**Comment by KairusDarkSeeker** [comment]
How about Hyroku? Taken from Tokyo Ghoul

**Comment by qyd0801** [comment]
Denisys 不要问我为什么，我不爱听

**Comment by KairusDarkSeeker** [comment]
Myrium?

**Comment by KairusDarkSeeker** [comment]
Xyrium, Xenon

**Comment by thebigsmileXD** [comment]
Genischiss

**Comment by KairusDarkSeeker** [comment]
Fuckenis

**Comment by dktapps** [comment]
I'm actually going to withdraw my suggestion of Katharos, since it's just far too much of a lie. I'm instead going to suggest

*Thanatos*

to honour the death of PocketMine.

**Comment by KairusDarkSeeker** [comment]
Canopus

**Comment by mhsjlw** [comment]
@dktapps, in which case my suggestion is quite fitting... :smile:

**Comment by DubaiGamerXD** [comment]
GeniSixteen:Genisys 0.16

**Comment by daniktheboss** [comment]
Minecraft server software

**Comment by Aericio** [comment]
Any release date for Genisys 0.16.0?

**Comment by KairusDarkSeeker** [comment]
@Aericio please don't spam when they'll release support for 0.16.0

**Comment by dktapps** [comment]
Smart people don't ask for ETAs.

**Comment by xinghao2003** [comment]
Secret : I love it 😏

**Comment by IISweePII** [comment]
Eclipse: As the new 0.16 mcpe version comes out to all devices, it shines brightly as a new chance for contributors to see how to work out new ways of code, and make minecraft pe work a lot better with it

**Comment by KairusDarkSeeker** [comment]
@IISweePII I think Syndrome is better

**Comment by thebigsmileXD** [comment]
So it will be called: POS? Piece of

**Comment by KairusDarkSeeker** [comment]
Neumann
