### ISSUE TITLE
0.14.0?

### ISSUE THREAD

**Issue by LogicSGPro** [iTXTech/Genisys#1873]
My server Is in version 0.14.0 I need help. How do I fix it

**Comment by XFuryMCPE** [comment]
Update to the latest Genisys version.

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
