### ISSUE TITLE
Redstone and other items broken

### ISSUE THREAD

**Issue by Froz3n907** [iTXTech/Genisys#1875]
#### Issue description

Redstone items/pressure plates, iron doors, and pistons either do not place or do not function. 

Minecarts constantly bounce up and down on the tracks. 

#### Steps to reproduce the issue

Login to server running Genisys 0.15.7 and placeabove mentioned blocks into your world. 

Items do not behave correctly.

#### OS and versions

* Genisys: 0.15.7
* PHP:
* Server OS: unknown (MCProHosting)
* Game version: 0.16.0 (iOS), windows 10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Redstone must be enabled in genisys.yml, and the minecarts issue was fixed some weeks ago. Please ensure you are up to date.
