### ISSUE TITLE
EntityDeathEvent

### ISSUE THREAD

**Issue by laurobeleche** [iTXTech/Genisys#1879]
- Genisys: 4b7394c
- PHP: 7
- Server OS: win 10
- Game version: 0.15.7

---

I have been experiencing this problem in various versions of Genisys in EntityDeathEvent event, we have the function

public function setDrops ($array drops ) {
$this-> = $ drops drops ;
}

But when I'm developing plugins and call the function as follows:

$event- > setDrops ([] ) ;

Does not work , continues dropping the items , you must do something different or is a problem in Genisys programming ?

**Comment by dktapps** [comment]
This relates to #1589

**Comment by dktapps** [comment]
Closing in favour of #1589 , it's the same bug causing both issues.
