### ISSUE TITLE
Use BatchPacket often

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#1881]
#### Issue description

Can you add ability(optional) to save packets and send many packets in one BatchPacket(this can help with packet ordering). This used in MiNET server software, so packets received correctly ordered.

#### Steps to reproduce the issue

Try to send many messages in plugin:
```
$player->sendMessage(implode(PHP_EOL, [
'Hello',
'Dear',
'User'
]));
```
Messages can be bad ordered: 'Dear', 'Hello', 'User'...

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/0deaf92b54256fa1d9e7d0bd47e96486845b46b0
* PHP: 7.0.9
* Server OS: Ubuntu Linux
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
This is already implemented.
