### ISSUE TITLE
Buggy InventoryTransactionEvent

### ISSUE THREAD

**Issue by diamond-gold** [iTXTech/Genisys#1885]
#### Steps to reproduce the issue
Make a plugin that has the following
public function InventoryTransactionEvent(InventoryTransactionEvent $event){
		var_dump(time());
		foreach($event->getTransaction()->getInventories() as $inv){
			var_dump(get_class($inv));
			if($inv->getHolder() instanceof Player) $player = $inv->getHolder();
			if($inv->getHolder() instanceof Chest) $chest = $inv->getHolder();
		}
		if(!isset($player)){
			var_dump("player not found");
			return;
		}elseif(!isset($chest)){
			var_dump("chest not found");
			return;
		}
		var_dump("ok");
}

and transfer items from chest to player, you will see that sometimes it will var_dump "ok", other times it will var_dump "player/chest not found"

#### OS and versions

* Genisys:Latest commit 3fdac8a
* PHP: 7 without OpenSSL
* Server OS: win 8
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

int(1473222261)
string(35) "pocketmine\inventory\ChestInventory"
string(16) "player not found"
int(1473222261)
string(36) "pocketmine\inventory\PlayerInventory"
string(15) "chest not found"

int(1473222302)
string(35) "pocketmine\inventory\ChestInventory"
string(36) "pocketmine\inventory\PlayerInventory"
string(2) "ok"
int(1473222305)
string(35) "pocketmine\inventory\ChestInventory"
string(36) "pocketmine\inventory\PlayerInventory"
string(2) "ok"
int(1473222307)
string(35) "pocketmine\inventory\ChestInventory"
string(16) "player not found"
int(1473222307)
string(36) "pocketmine\inventory\PlayerInventory"
string(15) "chest not found"
int(1473222345)
string(35) "pocketmine\inventory\ChestInventory"
string(16) "player not found"
int(1473222345)
string(36) "pocketmine\inventory\PlayerInventory"
string(15) "chest not found"

**Comment by dktapps** [comment]
That's just the way it is, I'm afraid. Win10 update changed the way transactions are processed, and it's impossible to pair them now.

**Comment by diamond-gold** [comment]
So currently there is no stable way to know where the items went or came from?

**Comment by dktapps** [comment]
Nope. All you can do is try and track it yourself. So items out -> items in is 2 separate transactions usually. So you'll have to track items coming/going.

**Comment by diamond-gold** [comment]
omg thats bad :(

**Comment by dktapps** [comment]
¯\\\_(ツ)_/¯ Client functionality comes before plugins. I apologize for the issues this has caused.

**Comment by diamond-gold** [comment]
But why is it that sometimes it works and sometimes not?

**Comment by dktapps** [comment]
Because transactions are processed on the spot, instead of waiting to see if they have a destination. Because in Win10 you can make inventory changes without them having a destination.
