### ISSUE TITLE
Arrow direction bug

### ISSUE THREAD

**Issue by SuperAdam47** [iTXTech/Genisys#1888]
![screenshot_2016-09-07-16-06-28](https://cloud.githubusercontent.com/assets/16169771/18316618/054969e4-7524-11e6-965b-4ad722976c10.png)

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
