### ISSUE TITLE
I cant pack to phar genisys

### ISSUE THREAD

**Issue by darkspive** [iTXTech/Genisys#189]
Jenkins does not works
Compile.sh does not works
By pocketmine devtools also does not works

**Comment by xpyctum** [comment]
Jenkins has travelling.

**Comment by nikita2000nikita** [comment]
How long?

**Comment by ChiefArtz** [comment]
ye?

**Comment by PeratX** [comment]
use /ms to make Phar Archive

**Comment by CrayonDing** [comment]
I upload the newest version Genisys.phar to my cloud disk
https://drive.google.com/file/d/0B47xKpOkRL7JaU9ZNE9CRDVXTTA/view?usp=sharing
