### ISSUE TITLE
ToolBox

### ISSUE THREAD

**Issue by MCPEPluginer16** [iTXTech/Genisys#1893]
Hi, I Developed 3 Plugins Kick Fly and Speed Hack and Game mode Hack But Dont work and I installed AntiCheat But Dont work Players Hacking Servers Using ToolBoX How I do Stop This I will Report ToolBox App ..

**Comment by XFuryMCPE** [comment]
In the issue template, it specifies that modded clients are not supported, but it seems that you haven't followed that anyways. Next time you open an issue, please follow the issue template.

**Comment by Leo3418** [comment]
Use Xbox Live authentication. I've tested logging in Xbox Live in Toolbox, even if you successfully logged in, the game still said Xbox authentication required.
