### ISSUE TITLE
Plugin no longer works 

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#1894]
#### Issue description

On the newest Genisys my plugin no longer works. I can get it to work on old Genisys versions. I'm also sorry if this counts as spam, I am just confused on why it no longer works properly
#### Steps to reproduce the issue

Check my code lol
#### OS and versions

* Genisys: Plugin only works in ce143206
* PHP: 7.0.3
* Server OS: Linux
* Game version: 0.15.7

#### Crashdump, backtrace, memory dumps, plugins list or other files

<?php

namespace Core;

use pocketmine\Player;
use pocketmine\Server;

use pocketmine\event\player\PlayerDeathEvent;
use pocketmine\event\entity\EntityRegainHealthEvent;

use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase implements Listener{

   public function onEnable(){
     $this->getServer()->getPluginManager()->registerEvents($this,$this);
    }

   public function onDeath(PlayerDeathEvent $death){
      $player = $death->getEntity();
          $player->setGamemode(3);
       }
  
   public function onEntityRegainHealth(EntityRegainHealthEvent $event){
        if($event->getRegainReason() === EntityRegainHealthEvent::CAUSE_REGEN){
                $event->setCancelled(true);
 	}
        if($event->getRegainReason() === EntityRegainHealthEvent::CAUSE_EATING){
                $event->setCancelled(true);
	}
   }
}

**Comment by GlitchPlayer** [comment]
Post this on chat. What was the error?
without any error, you can't unsure what is the problem

**Comment by TheAppleGamer** [comment]
There wasn't an error, it just didn't activate

**Comment by ZedCee** [comment]
I agree that your issue is rather unclear and would be better suited in the chat.

Perhaps this may answer your question.
aec7a3ed85a04f30b9d72b70142777864949ca9e

**Comment by Muqsit** [comment]
Maybe the plugin is in the folder and you aren't using a Folder-Plugin-Loader?

**Comment by dktapps** [comment]
Please review the contribution guidelines and read the FAQs before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by TheAppleGamer** [comment]
@ZedCee Didn't even notice that happened lol thanks I got it working now
