### ISSUE TITLE
FolderPluginLoader not working

### ISSUE THREAD

**Issue by KairusDarkSeeker** [iTXTech/Genisys#1897]
#### Issue description
It seems that FolderPluginLoader isn't working with openssl in FENGberd's PocketServer app.

#### OS and versions

* Genisys: 32c29dc
* PHP: 7.0.3
* Server OS:
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Please review the contribution guidelines and the FAQs before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
