### ISSUE TITLE
Important issue everyone read NOW asian porn

### ISSUE THREAD

**Issue by TheDiamondYT1** [iTXTech/Genisys#1900]
Now i got your attention,
@dktapps made a new twitter https://twitter.com/dktapps

**Comment by TheDiamondYT1** [comment]
*Waits for ban*

**Comment by TheDiamondYT1** [comment]
Lock the issue so ppl dont start asking where the porn is

**Comment by TheDiamondYT1** [comment]
Liek me

**Comment by dktapps** [comment]
You're tremendously immature. Go and get a life.
