### ISSUE TITLE
Enchantments are "hackable"

### ISSUE THREAD

**Issue by KillerXtream** [iTXTech/Genisys#1904]
#### Issue description

Hey there.
I currently have a problem with Genisys. some people using a "famous" hack called AlphaHack can hack enchantments in some X way.

#### Steps to reproduce the issue

Using AlphaHack 

#### OS and versions

* Genisys: Last commit of today
* PHP: 7
* Server OS: RHEL7
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Write your git commit hash. Read what the template states.

**Comment by dktapps** [comment]
Please note that we do not provide any support for third-party mods and do not endorse the use of them on servers.
You can also enforce XBL auth to stop hackers joining your server.
