### ISSUE TITLE
Add Placeable pistons 

### ISSUE THREAD

**Issue by SuperAdam47** [iTXTech/Genisys#1907]
#### Issue description

Not placeable And improve redstone system
#### OS and versions

* Genisys: a day ago
* PHP: 7.0.9
* Server OS:android
* Game version: 15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Try checking open issues before spamming.

**Comment by SuperAdam47** [comment]
No spam ,add
