### ISSUE TITLE
Incorrect server time

### ISSUE THREAD

**Issue by Pub4Game** [iTXTech/Genisys#191]
![image](https://cloud.githubusercontent.com/assets/11244874/12684264/0762edd0-c6cf-11e5-9b81-d90397835d6a.png)

It is 100% the problem a Genisys as Nukkit displays the correct time

**Comment by seetch** [comment]
mmm.. 24serv ^-^

**Comment by Pub4Game** [comment]
?

**Comment by seetch** [comment]
i love hosting 24serv.pro :3 i'm learn russian

**Comment by Pub4Game** [comment]
Nice man :3 :+1:

**Comment by seetch** [comment]
and MCPEhost.ru is stupid hosting!

**Comment by Pub4Game** [comment]
:smile:  666

**Comment by seetch** [comment]
oh yeah, I'm **dangerous**

**Comment by Pub4Game** [comment]
vk page?)

**Comment by seetch** [comment]
Yes, vk.com/seetch  :3

**Comment by PocketKiller** [comment]
Please be on-topic @Pub4Game & @seetch

**Comment by Pub4Game** [comment]
@PocketKiller sorry, you can fix it problem?

**Comment by PocketKiller** [comment]
look at you php.ini

**Comment by Pub4Game** [comment]
@PocketKiller in my php.ini "date.timezone=MSK" and minuts do not depend on time zone

**Comment by markkrueg** [comment]
I also have this issue. My php.ini specifies the correct time zone. However the console time seems to be always UTC (not my time zone).

**Comment by PeratX** [comment]
OK,I will fix it.

**Comment by PeratX** [comment]
I think something wrong in PocketMine.php

**Comment by Pub4Game** [comment]
Wow, @PeratX  Thank you very much!
