### ISSUE TITLE
Mob issues

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1911]
#### Issue description
Mobs have leads connecting them and when they die they don't drop anything

#### Steps to reproduce the issue
do "/summon 43 ~ ~ ~" and kill it, you will see that there is a lead. You can also use spawn eggs.

* Genisys: 82f9e7f
* PHP: 7
* Server OS: Mac
* Game version: 0.15.4/6

**Comment by XShockinFireX** [comment]
The old, unstable mob ai has been removed, the devs are going to work on a cleaner version in the future.

**Comment by TheAppleGamer** [comment]
Please close, this is invalid. Mob AI was removed until there is a newer more efficient one

**Comment by dktapps** [comment]
This issue is not relevant to AI.
