### ISSUE TITLE
NBT.php on line 486

### ISSUE THREAD

**Issue by misha1** [iTXTech/Genisys#1914]
Warning: zlib_decode(): data error in D:\mineserver\src\pocketmine\nbt\NBT.php on line 486
[09:50:21] [Server thread/INFO]: NASTYAKOT_YT[/46.146.40.55:6214] logged out due to client disconnect

help , what i can do fix?

**Comment by PeratX** [comment]
Delete that user's profile, it is broken. (maybe by sudden shutdown)

**Comment by misha1** [comment]
thank
