### ISSUE TITLE
Items keep falling out of chests

### ISSUE THREAD

**Issue by GoldenSteel** [iTXTech/Genisys#1921]
Hi there is a bug on Cosmic PE. When we are putting items in chests they randomly fall out and then disapear. Also once the chest is full the items randomly disapear and we have to break the chests in order to get the items back. Please please please fix this in time. Alot of people are raging about them loosing their god sets and swords. Thankyou

**Comment by GlitchPlayer** [comment]
Report this to @Muqsit since he works on CosmicPE not on genisys

**Comment by GoldenSteel** [comment]
I did. But he said to tell you guys. This bug is annoying af....

**Comment by GlitchPlayer** [comment]
Then use the Genisys issue template. This is considered as spam

**Comment by GoldenSteel** [comment]
Ok sorry. I dont know how to do that coz this is my first time using github
😶

**Comment by dktapps** [comment]
From the issue template:
><!--- READ THE FOLLOWING CAREFULLY BEFORE OPENING THIS TICKET.
> - Issues not following this template will also be closed as spam. If you do not supply the information we ask for then your issue cannot be resolved.

¯\\\_(ツ)_/¯

**Comment by GlitchPlayer** [comment]
#1898

**Comment by GoldenSteel** [comment]
So what do I do?

**Comment by ishitatsuyuki** [comment]
Follow the rules. Edit if you want this reopened. Do not try to open a new one.
