### ISSUE TITLE
DropItemEvent not working

### ISSUE THREAD

**Issue by lengoctantoan** [iTXTech/Genisys#1924]
Hi,
DropItemEvent not working, see code :
`public function onPlayerDropItem(PlayerDropItemEvent $event){
		if(!$this->plugin->isPlayerAuthenticated($event->getPlayer())){
			$event->setCancelled(true);
		}
	}
`
 
When drop, player will lose the item, please fix

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by lengoctantoan** [comment]
https://youtu.be/RhHb93dPuvA
Pls watch video, item will be lose when i cancalled PlayerDropItemEvent


`public function noDrop(PlayerDropItemEvent $event)
    {
          $event->setCancelled();
    }
'
Sorry my bad english
