### ISSUE TITLE
Inventory (addItem, clearInv) bugs

### ISSUE THREAD

**Issue by Misteboss** [iTXTech/Genisys#1925]
I have a bug when I 
-> addItem ($player->getInventory()->addItem
-> clearInv ($player->getInventory()->clearAll()
And there is no error in the consol :/
Can you fix it ?

**Comment by Muqsit** [comment]
What are you trying to do?

**Comment by Misteboss** [comment]
When I give an item it doesn't work :(
Can we dm in twitter @Misteboss_mcpe
I will explain you

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
