### ISSUE TITLE
PlayerJoinEvent, Player::setAllowFlight

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#1926]
#### Issue description

I'm tried to call Player::setAllowFlight(true) in PlayerJoinEvent, and it's not works.

#### Steps to reproduce the issue

1. Create event `PlayerJoinEvent` in plugin.
2. In this event, call `$event->getPlayer()->setAllowFlight(true);`.
3. Try to fly.

You can see problem here `Player.php:1008`:
```
		$this->server->getPluginManager()->callEvent($ev = new PlayerJoinEvent($this, new TranslationContainer(TextFormat::YELLOW . "%multiplayer.player.joined", [
			$this->getDisplayName()
		])));

		if(strlen(trim($msg = $ev->getJoinMessage())) > 0){
			if($this->server->playerMsgType === Server:: PLAYER_MSG_TYPE_MESSAGE) $this->server->broadcastMessage($msg);
			elseif($this->server->playerMsgType === Server::PLAYER_MSG_TYPE_TIP) $this->server->broadcastTip(str_replace("@player", $this->getName(), $this->server->playerLoginMsg));
			elseif($this->server->playerMsgType === Server::PLAYER_MSG_TYPE_POPUP) $this->server->broadcastPopup(str_replace("@player", $this->getName(), $this->server->playerLoginMsg));
		}

		$this->setAllowFlight($this->gamemode == 3 || $this->gamemode == 1);
```

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/eb168db2e3a32097ba3d654bbcafc3e7d113efa8
* PHP: 7.0.1
* Server OS: Windows 10, Ubuntu Linux
* Game version: 0.15.6

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Ragnok123** [comment]
У меня тоже такая проблема. Наверное баг ядра

**Comment by undrfined** [comment]
Just allow fly after 1 tick

**Comment by Tarik02** [comment]
@undrfined, this is not good way.

**Comment by thebigsmileXD** [comment]
@undrfined is right.
