### ISSUE TITLE
Next step?

### ISSUE THREAD

**Issue by MarMallowz** [iTXTech/Genisys#1928]
After Port Forwarding my server, what should I do next on starting up the server?
Im new here sorry

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
