### ISSUE TITLE
FolderPlugin is not load

### ISSUE THREAD

**Issue by ParkChanSol** [iTXTech/Genisys#1929]
#### Issue description

I make Plugin, then I put my plugin into Plugin Folder, but Genisys doesn't sense
I try PHAR, then plugin is working and Genisys can sense
#### OS and versions

* Genisys:Pocketmine-MP API 2.0.0(iTX-Tech API 1.9.1)
* PHP:7.0.9(by iTX-Tech Offical Site)
* Server OS:Windows 7 Utimate K(x64,64bit)
* Game version: d720b7df2c4986cca3d32e009fe7f834dbe6104d

#### Crashdump, backtrace, memory dumps, plugins list or other files
Genisys-DevTools
```
```

**Comment by Ragnok123** [comment]
If you will use genisys devtools, its ok. If you havent got genisys devtools, it doesnt work.

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by GlitchPlayer** [comment]
No, I tried to load a Plugin in folder too. I have installed Devtools. But it seems doesn't detect it. Well, probably. I should report this on issue tracker on Devtools repo

**Comment by dktapps** [comment]
@GlitchPlayer DevTools itself cannot be loaded as a folder. You can get a phar from the releases page at the DevTools repo.

**Comment by GlitchPlayer** [comment]
No, I was meaning a plugin not devtools. For example, I want "TellRaw by Joejoe7777" to be loaded. I do not see any messages like "Loading TellRaw" in purple.

**Comment by GlitchPlayer** [comment]
I had to use a old version of genisys with devtools built in.
