### ISSUE TITLE
About EconomySell 

### ISSUE THREAD

**Issue by zzz1999** [iTXTech/Genisys#193]
Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name in phar:///root/PocketMine-MP/plugins/EconomySell_v2.0.4.phar/src/onebone/economysell/EconomySell.php on line 19

in EconomySell 's 19 line 
use pocketmine\nbt\tag\Int;

**Comment by PeratX** [comment]
Use EconomyS provided by onebone on github. It supported php7

**Comment by zzz1999** [comment]
thanks!
