### ISSUE TITLE
Memory leak with excessively high levels of exp causes server crash in seconds

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1930]
#### Issue description
I can crash a Genisys server within seconds with an excessively high level of EXP.

#### Steps to reproduce the issue
- Use /xp to set your exp to an extremely high level of exp, for example /xp 2147483647L @p 
- Quit the server
- Rejoin the server. You'll hang at the "Locating server" terrain. Meanwhile, your server maxes out at 100% CPU and the memory usage spirals upwards at an astonishing rate.
- Look in your terminal.

### The issue here is the exp cache. The exp cache is for a start pointless over-engineering and a terrible premature optimization case. You're caching the calculated exp to reach a certain level, for 2.1 billion levels:
- 1 integer is 32 bits or 4 bytes
- 2.1 billion cached ints = 8.6x10^9 bytes = 8 GIGABYTES of cached integers.

#### Possible solutions
- Remove the exp cache. It's completely pointless, just a waste of memory by holding onto a potentially extremely large quantity of numbers. The processing time it saves is so close to zero it is non-existent. As @SOF3 would say, premature optimization is the root of all evil. In this case, the optimization is over-engineered and has caused major issues. This is the worst case of over-engineered optimization I have seen in a long time.
- Change the calculation and saving of exp so that such calculation is not necessary.
- ~~If the exp cache is to be kept, make it an SplFixedArray of size 32767 to stop it growing to such an astonishing size in this kind of situation.~~ Exp cache is completely pointless.

## I will implement a solution myself. **I open this issue as a warning to whoever did this and hope they learn a lesson.**

I might also point out that this is the second exp-related memory leak I have discovered. Let the person who wrote the exp system hang their head in shame.

#### OS and versions

* Genisys: eb168db
* PHP: 7.0.9 x86
* Server OS: Windows 10 Pro x86
* Game version: Pocket Edition 0.15.7

#### Crashdump, backtrace, memory dumps, plugins list or other files

- xdebug backtrace
```
Fatal error: Out of memory (allocated 136314880) (tried to allocate 234881024 bytes) in C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php on line 1572

Call Stack:
    0.0025     349072   1. {main}() C:\Users\Admin\Downloads\Genisys\src\pocketmine\PocketMine.php:0
    0.1756     454432   2. pocketmine\Server->__construct() C:\Users\Admin\Downloads\Genisys\src\pocketmine\PocketMine.php:467
    2.6756   17142936   3. pocketmine\Server->start() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2035
    2.7451   17244624   4. pocketmine\Server->tickProcessor() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2449
   19.1456   17256920   5. pocketmine\Server->tick() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2571
   19.1456   17256920   6. pocketmine\network\Network->processInterfaces() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Server.php:2861
   19.1456   17256920   7. pocketmine\network\RakLibInterface->process() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\Network.php:145
   19.1456   17256920   8. raklib\server\ServerHandler->handlePacket() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\RakLibInterface.php:76
   19.1463   17282848   9. pocketmine\network\RakLibInterface->handleEncapsulated() C:\Users\Admin\Downloads\Genisys\src\raklib\server\ServerHandler.php:99
   19.1463   17291136  10. pocketmine\Player->handleDataPacket() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\RakLibInterface.php:140
   19.1463   17291136  11. pocketmine\network\Network->processBatch() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2289
   19.1472   17365248  12. pocketmine\Player->handleDataPacket() C:\Users\Admin\Downloads\Genisys\src\pocketmine\network\Network.php:239
   19.1503   17437528  13. pocketmine\Player->onPlayerPreLogin() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2419
   19.1504   17437920  14. pocketmine\Player->processLogin() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2057
   19.1678   17501720  15. pocketmine\Player->calcExpLevel() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:2141
   37.9537  133365288  16. pocketmine\Server->getExpectedExperience() C:\Users\Admin\Downloads\Genisys\src\pocketmine\Player.php:395

[14:54:48] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[14:54:48] [Server thread/EMERGENCY]: Please upload the "C:\Users\Admin\Downloads\Genisys\crashdumps/CrashDump_Sun_Sep_11-14.54.48-AZOST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```

- Crashdump
```
Genisys Crash Dump Sun Sep 11 14:51:45 AZOST 2016

Error: Out of memory (allocated 278921216) (tried to allocate 469762048 bytes)
File: /src/pocketmine/Server
Line: 1572
Type: E_ERROR

Code:
[1563] 			Server::$sleeper->wait($ms);
[1564] 		}, $microseconds);
[1565] 	}
[1566] 
[1567] 	public function getExpectedExperience($level){
[1568] 		if(isset($this->expCache[$level])) return $this->expCache[$level];
[1569] 		$levelSquared = $level ** 2;
[1570] 		if($level < 16) $this->expCache[$level] = $levelSquared + 6 * $level;
[1571] 		elseif($level < 31) $this->expCache[$level] = 2.5 * $levelSquared - 40.5 * $level + 360;
[1572] 		else $this->expCache[$level] = 4.5 * $levelSquared - 162.5 * $level + 2220;
[1573] 		return $this->expCache[$level];
[1574] 	}
[1575] 
[1576] 	public function about(){
[1577] 		$string = '
[1578] 
[1579] 	§3Genisys§f is a fork of §bPocketMine-MP§f, made by §5iTX Technologies LLC§f
[1580] 	Version: §6' . $this->getPocketMineVersion() . '§f
[1581] 	Target client version: §b' . \pocketmine\MINECRAFT_VERSION . '§f
[1582] 	Source code: §dhttps://github.com/iTXTech/Genisys§f

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
uname -a: Windows NT DESKTOP-4CUH8HC 10.0 build 10586 (Windows 10) i586
PHP version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 4 minutes 4 seconds
Number of loaded worlds: 2
Players online: 0/20

Loaded plugins:
```

**Comment by XFuryMCPE** [comment]
Very good find. I noticed this awhile ago, but never knew how to fix it

**Comment by SOF3** [comment]
I didn't say that :confused: 

https://en.wikiquote.org/wiki/Donald_Knuth#Computer_Programming_as_an_Art_.281974.29

> The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; **premature optimization is the root of all evil (or at least most of it) in programming**.

**Comment by xxFlare** [comment]
@dktapps Later on, any plans to rewrite this code? It is sort of a mess.
