### ISSUE TITLE
Provide some high level documentation

### ISSUE THREAD

**Issue by mpfeifer** [iTXTech/Genisys#1934]
Do provide some high level documentation including information about the genisys software architecture/code organization, common workflows and general information for new developers (how to get started).

For example i consider my usecase not to uncommon. I have played mcpe for a while and now want to move my worlds to a server: What are the different level "formats" in src/pocketmine/level/format and how can levels be converted between the different formats.

I guess there might be more common situations that can be documented.

**Comment by ishitatsuyuki** [comment]
Too abstract. Closing.

**Comment by ishitatsuyuki** [comment]
You should get help in the chat service.

**Comment by mpfeifer** [comment]
I find Genisys lacks some good documentation for developers who want to get involved in Genisys development. How would you formulate the issue? What is abstract about:

"provide some high level documentation including information about the genisys software architecture/code organization, common workflows and general information for new developers"

**Comment by ishitatsuyuki** [comment]
We don't like to force any codestyles, or make noob code similar junks. PocketMine itself has been sucking enough on design, how the user code is up to the user.

**Comment by dktapps** [comment]
[Doxygen-generated API documentation](https://storage.googleapis.com/itx-technologies-141911.appspot.com/docs/genisys/index.html)
