### ISSUE TITLE
Feature: Spawn radius

### ISSUE THREAD

**Issue by DaMatrix** [iTXTech/Genisys#1936]
#### Issue description

Vanilla servers have a spawn radius, where if you die and don't have a bed you are teleported to a random location in a set radius of spawn.  This would be a good feature to implement for survival (especially Anarchy servers)

#### OS and versions

* Genisys: all
* PHP: all
* Server OS: all
* Game version: all

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by PeratX** [comment]
Use plugin.
