### ISSUE TITLE
setCustomName () does not seem to work.

### ISSUE THREAD

**Issue by Sandertv** [iTXTech/Genisys#1937]
#### Issue description

setCustomName () is not working in a plugin
#### Steps to reproduce the issue

  public function onHeld (PlayerJoinEvent $event) {
    $item = Item::get (175, 0, 1);
    $item->setCustomName(TF::YELLOW . "Coin");
}
Executing this code does not do anything at all, I have tried using this on several events but just nothing happens. (I've tried this in lots of ways and I'm quite sure this should work like this)
#### OS and versions

* Genisys: 1.9.1
* PHP: 7.0.3
* Server OS: Sorry I do not know what this is...
* Game version: Minecraft PE 0.15.4 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
This is a known issue with the colours. If you remove the colour it works fine.

**Comment by Sandertv** [comment]
Oh thanks! Is there any way to work around this or not that you know of?

**Comment by Skull3x** [comment]
Maybe..

if($item->getCustomName() == "Coin"){
$item->setName(TF::YELLOW . "Coin");

I don't know, just a preference.

**Comment by dktapps** [comment]
@Skull3x that's backwards. @sandertv not that we know about unfortunately. It will be investigated.

**Comment by Sandertv** [comment]
Okey thanks, I'll stick with no colours for now :)

**Comment by jojoe77777** [comment]
Well, that code doesn't do anything with the item...

**Comment by Muqsit** [comment]
You cannot change the name of the item that the player has in their inventory. You will need to remove the item, set its custom name, then add it back to the player's inventory.

**Comment by Sandertv** [comment]
Yeah I know, it's not my full code, I just didn't feel like posting the whole code.

**Comment by Sandertv** [comment]
Nevermind this all, I find a way which does work. @dktapps colours in setCustomName () do work.
