### ISSUE TITLE
Deprecated: This method is deprecated, do not use it (EXP update issue)

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1939]
#### Issue description

Deprecated: This method is deprecated, do not use it in phar:///home/Network2/PvP/KitPvP/1/Genisys.phar/src/pocketmine/Player.php on line 384
everytime a player joins

#### Steps to reproduce the issue

join the server and it happens

#### OS and versions

* Genisys: 971b506
* PHP: 7.0.9
* Server OS: ubuntu
* Game version: 0.15

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
confirmed... @dktapps :3

**Comment by dktapps** [comment]
Synapse issue. I don't test with Synapse.

**Comment by dktapps** [comment]
(I did explicitly state in that pull request that I didn't test with Synapse... :P)
