### ISSUE TITLE
PC Worlds on Client Crash!

### ISSUE THREAD

**Issue by bulutsun** [iTXTech/Genisys#1945]
Hi, I bought the map periodically causing the client to crash. You have uninstalled all unknown blocks and villages, but this problem continues. There is a solution to this? What is causing this?

**Comment by ImagicalGamer** [comment]
Most likely there is unsupported blocks and/or entities in the world. When a chunk is sent to a player with an unsupported block/entity it crashes the player. I believe PMImporter removes PC blocks/entitys?

**Comment by dktapps** [comment]
Please review the contribution guidelines and read the FAQs before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by bulutsun** [comment]
Though he continues to remove everything that is not compatible. This problem will be resolved in version 0.16?

**Comment by bulutsun** [comment]
ImagicalGamer How Can I use the plugin pmimporter?
