### ISSUE TITLE
enchant, animals, monsters and eggs

### ISSUE THREAD

**Issue by AliMAltamimi** [iTXTech/Genisys#1947]
#### Issue description

* enchant command works just to make weapon shinning, it adds no effects or powers to weapon/tools.
 example:
    /enchant  player  enchantment ID  [level]  
      /enchant aalmp888 diamondsword 70

* animals and monsters are not spwanning 

* eggs:
 when use command to give an egg it gives the egg, but the egg not spwanning anything.
  /give  player  item[:damage]  [amount] [tags...]
   /give aalmp888 383:54 1
      to give one zombie egg, it says 
#### OS and versions

* Genisys: Genisys_unsupported-7ef1056_2016-09-16_01-47-10
* PHP: php_windows_7.0.11_x86
* Server OS: windows 10
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Shadow166050** [comment]
They removed mobs, please add them back!

**Comment by AliMAltamimi** [comment]
really? what about enchantment
