### ISSUE TITLE
Unset array in the config.

### ISSUE THREAD

**Issue by FerroDump** [iTXTech/Genisys#1948]
#### Issue description
It is impossible to remove in the config.yml array

my config in this format
``homes:
  name:
    x: 134
    "y": 66
    z: 161``

help plz

#### Steps to reproduce the issue
$config->remove("homes.name");
$config->save(); $config->reload();
don't work

only
$config->remove("homes");
$config->save(); $config->reload();

#### OS and versions

* Genisys: Kyrios
* PHP: 7
* Server OS: linux
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
```

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by FerroDump** [comment]
fix please

**Comment by dktapps** [comment]
You're doing it wrong. That will not work for removing a value, as it checks only for that literal array key being set.
