### ISSUE TITLE
Mob Removed

### ISSUE THREAD

**Issue by Shadow166050** [iTXTech/Genisys#1949]
#### Issue description
Mobs Where Removed From Genisys And No Longer Work

#### Steps to reproduce the issue
Spawn Eggs / Spawners

#### OS and versions
* Genisys: 5e4bfc0
* PHP:7.0.7
* Server OS: 2.0.0
* Game version: 15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files
I'm Just looking for an answer to when they will be added back

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
