### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Jelly9912** [iTXTech/Genisys#195]
Hi, can someone give me .phar file with newest version of genisys? I know how to compile it into .phar with /makeserver but for this i need upload all the files on my ftp, and here is the problem. I can upload only one file and genisys have so many files :V 
It would take a long time :/

**Comment by GalvinGao** [comment]
Please go to [here](mcper.cn:8080) to get the last version of Genisys.

Simply throw it in.

**Comment by CrayonDing** [comment]
I upload the newest version Genisys.phar to my cloud disk
https://drive.google.com/file/d/0B47xKpOkRL7JaU9ZNE9CRDVXTTA/view?usp=sharing

**Comment by Jelly9912** [comment]
@CrayonDing sorry for problems but i'm using php5 :/

**Comment by CrayonDing** [comment]
OK.I will make a php5.phar in this evening.

**Comment by Jelly9912** [comment]
Thanks :) oh and one more thing, for 0.14?

**Comment by CrayonDing** [comment]
yes

**Comment by Jelly9912** [comment]
Ok :)

**Comment by Jelly9912** [comment]
@CrayonDing Done?

**Comment by CrayonDing** [comment]
OK.https://drive.google.com/file/d/0B47xKpOkRL7JMjRVclhUN01wS00/view?usp=sharing

**Comment by SalmonGER** [comment]
@CrayonDing Did you update the protocol version for Build 3?

**Comment by CrayonDing** [comment]
I downloaded the zip just now,and make a .phar

**Comment by SalmonGER** [comment]
@CrayonDing Well, the php5 branch still uses protocol version 41 and not 42. So it's not compatible with build 3. You just need to change **const CURRENT_PROTOCOL = 41;** in **src/pocketmine/network/protocol/Info.php to const** to **CURRENT_PROTOCOL = 42;**

**Comment by CrayonDing** [comment]
Thx.Done.

**Comment by Jelly9912** [comment]
So this is for build 3? 
https://drive.google.com/file/d/0B47xKpOkRL7JMjRVclhUN01wS00/view

**Comment by CrayonDing** [comment]
No.

**Comment by SalmonGER** [comment]
@Jelly9912  No

**Comment by Jelly9912** [comment]
Ok, so i'll run my server on build 1 xD
thanks anyway ;)

**Comment by SalmonGER** [comment]
@Jelly9912 I could make you a build 3 .phar

**Comment by SalmonGER** [comment]
@Jelly9912 Here https://drive.google.com/open?id=0B28Bu_R-nk06aERYRW5KVHE1dGM

**Comment by Jelly9912** [comment]
Thank you! :smiley:

**Comment by Jelly9912** [comment]
Oh, i can't download it. I don't have permission :V i'm not owner of this file :V

**Comment by SalmonGER** [comment]
@Jelly9912 Sry. xD Try this link: https://drive.google.com/file/d/0B28Bu_R-nk06aERYRW5KVHE1dGM/view?usp=sharing

**Comment by Jelly9912** [comment]
Ok, works now. Thanks!

**Comment by DesPlaysMC** [comment]
hey ppl, i need some help here. when i use the 0.14 phar, the console keeps showing this and refuses to start:
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/4n0nym0u$/Documents/GRRR PLZ WORK GENISYS/PocketMine-MP.phar/src/pocketmine/Server.php on line 68
wat does this mean? is there a solution for this?
