### ISSUE TITLE
PlayerJoinEvent not just players

### ISSUE THREAD

**Issue by Sandertv** [iTXTech/Genisys#1950]
Hey!
When making and using a plugin I made, I found out that PlayerJoinEvent is more like EntityJoinEvent. I made it so it creates a file with the player's name when joining, but it turned out every entity got 'getNamed ()' and made a file for. $player instanceof Player does work, but I don't think PlayerJoinEvent is supposed to trigger for entities too...
![screenshot_2016-09-17-08-23-08](https://cloud.githubusercontent.com/assets/16114089/18606372/90a8d308-7cae-11e6-8117-59dc7cd36415.png)

**Comment by jojoe77777** [comment]
Show the code?

**Comment by Sandertv** [comment]
Whoops sorry, sure.
`  public function onJoin (PlayerJoinEvent $event) {
    $p = $event->getPlayer ();
    @mkdir($this->getDataFolder () . "plugins/PocketRPG/party/");
    @file_put_contents ($this->getDataFolder () . "plugins/PocketRPG/party/" . $p->getName () . ".yml", yaml_emit([
    "Pending" => array (),
    "Allies" => array ()
    ]));
  }`

**Comment by Sandertv** [comment]
Only adding $p instanceof Player will make it so the code won't get executed when then event does.

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
