### ISSUE TITLE
Map item not working 😭

### ISSUE THREAD

**Issue by EmreTr1** [iTXTech/Genisys#1951]
Can you add?

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by PeratX** [comment]
This will be added after redstone re-implementation
