### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by AndreySK4** [iTXTech/Genisys#1952]
Please add /updateserver command

OS: -
Version: -
MCPE: -

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
