### ISSUE TITLE
Give items doesn't work (just the first of the series is given)

### ISSUE THREAD

**Issue by Misteboss** [iTXTech/Genisys#1955]
#### Issue description

When i try to give an item it doesn't work, i try with lot of difference things but doesn't work :/ (addItem, setItem)
I try without setCustomName too and doesn't work
#### OS and versions

* Genisys: Genisys-9c13370
* PHP: 7.0.10
* Server OS: Unknown (HostMyServer)
* Game version: 0.15.6 and 0.15.8

#### Crashdump, backtrace, memory dumps, plugins list or other files

The code is used for give the items
```
$player->getInventory()->setItem(8, Item::get(Item::BED,0,1)->setCustomName("1"));
$player->getInventory()->setItem(4, Item::get(Item::ENCHANTED_BOOK,0,1)->setCustomName("a"));
$player->getInventory()->setItem(0, Item::get(Item::FILLED_MAP,0,1)->setCustomName("a"));
```
Just the first item is given

**Comment by dktapps** [comment]
"Last version" is not a valid version. Did you not read the warnings in the issue template?

**Comment by iPocket** [comment]
Provide a valid OS...

**Comment by Misteboss** [comment]
I'm talking about the Last Build, i download the version 20 minutes ago..

**Comment by Misteboss** [comment]
And i don't know the OS my host is HostMyserver

**Comment by dktapps** [comment]
> Valid version must contain build number or git hash, "latest" is invalid. Use the 'version' command in Genisys.

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by Misteboss** [comment]
Genisys-9c13370

**Comment by Misteboss** [comment]
I try to fix it since one week and doesn't arrive 👎

**Comment by dktapps** [comment]
Open-source, unpaid developers do not work according to a schedule. If you're unhappy with our development speed, I'd like to remind you of that. Nobody pays us to do this; we develop for free. So you can shut up complaining.

**Comment by Misteboss** [comment]
I was not talking about your speed of work but just about me ^^

**Comment by Misteboss** [comment]
I fix it you can closed the issue, but i will open an other because i have an other problem
