### ISSUE TITLE
Cant spawn blocks in my server

### ISSUE THREAD

**Issue by karanpatel567** [iTXTech/Genisys#1956]
Im using the latest genisys phar php7 and its working good but when i go in my server and selectany block and place it it shows another type of block and when i spawn another type of block it doesnt even work thx for your your hard work!

**Comment by flaxues** [comment]
Nobody is going to help you without all of the information... You need to follow the issue template.

The rules and basics of making a issue:
READ THE FOLLOWING CAREFULLY BEFORE OPENING THIS TICKET.
- Any issues regarding outdated Genisys versions will be CLOSED. Make sure you can reproduce the issue on the latest build before submitting an issue.
- Make sure you are using a build from the MASTER branch. Issues relating to non-production builds will be closed.
- Any issues requesting updates to new versions of MCPE will be treated as spam. We do not need spamming with issues to know that there is a new version available.
- SEARCH EXISTING ISSUES before you open a new one. This INCLUDES searching OUR issue tracker AND Mojang's issue tracker at https://bugs.mojang.com/browse/MCPE. Duplicate issues will be treated as spam and dealt with accordingly.
- Issues not following this template will also be closed as spam. If you do not supply the information we ask for then your issue cannot be resolved.
- We DO NOT provide support for issues relating to 3rd-party mods or modded clients in any way, shape or form. Genisys is designed for vanilla MCPE/Win10 ONLY. Issues submitted relating to modded clients will be treated as spam and dealt with accordingly.
- Repeated spamming will result in a ban. You have been warned!

**Comment by dktapps** [comment]
@flaxues :D (Ctrl+C -> Ctrl+V)

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
