### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by misha1** [iTXTech/Genisys#1957]
Fatal error: Out of memory (allocated 547356672) (tried to allocate 86016 bytes) in D:\mineserver\src\pocketmine\Player.php on line 4423
[20:26:09] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

VirtualAlloc() failed: [0x00000008] ▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒.

VirtualFree() failed: [0x000001e7] ▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒.

VirtualAlloc() failed: [0x00000008] ▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒.

VirtualFree() failed: [0x000001e7] ▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒.

VirtualAlloc() failed: [0x00000008] ▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒.

VirtualFree() failed: [0x000001e7] ▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒.

zend_mm_heap corrupted

**Comment by flaxues** [comment]
Nobody is going to help you without all of the information... You need to follow the issue template.

The rules and basics of making a issue:

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
