### ISSUE TITLE
trapdoors can't be placed without a supporting block

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1958]
#### Issue description

An update was done that allows trapdoors to be placed anywhere without a supporting block

#### Steps to reproduce the issue

try placing a trapdoor on the ground, it disappears

#### OS and versions

* Genisys: any
* PHP: any
* Server OS: ubuntu
* Game version: 0.15

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheAppleGamer** [comment]
I'll look into it, save the Genisys team some time.

**Comment by dktapps** [comment]
Unable to reproduce in any manner. Check your plugins.

(I did however discover a very strange client bug with red sandstone slabs while investigating this...)

**Comment by XFuryMCPE** [comment]
Crap, meant trapdoors 😅 on my phone rn cant change names

**Comment by dktapps** [comment]
Hint: Bottom right, hit the Desktop Version button. :P

**Comment by XFuryMCPE** [comment]
thanks, what bug with red sandstone

**Comment by dktapps** [comment]
[Off-topic] Place a red sandstone bottom slab, then place a stone one on top. It's a vanilla bug
