### ISSUE TITLE
Items with different metas stack over eachother

### ISSUE THREAD

**Issue by PragaKart67z** [iTXTech/Genisys#1959]
#### Issue description

When identical items with different metas are in any inventory, they stack over eachother. When placed into a chest, they glitch into eachother and are thrown out of the inventory when you exit the chest.
#### Steps to reproduce the issue

Ex: Give yourself id 52:1 and 52:2, place them, mine them with silktouch, then they will stack. Items with different metas aren't supposed to stack! Please fix!
#### OS and versions

- Genisys: Kyrios
- PHP: 7.0.9
- Server OS: Debian 8.5 x64 
- Game version: 0.15.x
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[02:47:34] [Server thread/INFO]: Plugins (24): ManyWorlds v2.0.3, FactionsPro v1.8.0, BetterGenerators v0.8.1, PrivateVault v1.0.0, EP-Bounties v1.0.0, SimpleNoSpam v0.1, WorldEdit v1, Withdraw v1.0, EP-AntiSpam v0.1, HeadHunter v1.0.0, CustomEnchants v1.0.1, ServerAuth v2.13, Genisys-DevTools v1, Quest v1.0_Beta, WorldConverter v1.0.0, ExplosiveEnvoys v1.0, MysteryCrate v0.0.5, AdvancedSpawners v0.0.4, SkyBlock v1.5, EconomyAPI v2.0.9, CENamer v0.1, EnchantShop v1.0-dev#9, EssentialsPE v1.1.4.EP, EconomyShop v2.0.7
```

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by PeratX** [comment]
May related to deepEquals in transcation.

**Comment by legoboy0215** [comment]
That is why /give diamond armors don't work well...

**Comment by dktapps** [comment]
confirmed

**Comment by dktapps** [comment]
Monster Spawners do not retain the damage value when placed or broken, this is expected behaviour. Not reproducible with normal items. Closing.
