### ISSUE TITLE
Unable to Craft win10

### ISSUE THREAD

**Issue by NiceleyDone** [iTXTech/Genisys#1960]
#### Issue description
Unable to Craft in Windows 10 Edition using classic/manual crafting system. Items reset to original state after craft attempt. Loading the same player data in MCPE, player is able to craft in MCPE. able to do everything else besides craft.

#### Steps to reproduce the issue.
Gather crafting materials in Windows 10edition
Attempt to craft anything. (Sticks, planks, torches, tools, armor, etc.)

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by NiceleyDone** [comment]
Genisys : 0.15.4 API 2.0.0 PHP 7.0.3
Php: 7.0.3
Server os: Pocketmine
Player game version: windows 10e beta 0.15.8

**Comment by iPocket** [comment]
Provide a valid Genisys version.
on console:
/version
and a valid OS.

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by dktapps** [comment]
This issue was resolved months ago.
