### ISSUE TITLE
PlayerDropItemEvent not working

### ISSUE THREAD

**Issue by ghost** [iTXTech/Genisys#1961]
**Issue description**
https://youtu.be/RhHb93dPuvA
Pls watch video, item will be lose when i cancalled PlayerDropItemEvent
`public function noDrop(PlayerDropItemEvent $event) { $event->setCancelled(); } `

**OS and versions**

Genisys: 5e4bfc0
PHP Version: 7.0.3
OS : Linux, linux
Game Verison: 0.15.x

Sorry my bad english

**Comment by lengoctantoan** [comment]
#1924

**Comment by dktapps** [comment]
Actually, it's not. It's stuck in what is known as your FloatingInventory. If you open and close your inventory, it will drop the missing items.

**Comment by lengoctantoan** [comment]
i open and close my inventory, but items aren't appear .how when drop , items aren't missing.

**Comment by XFuryMCPE** [comment]
Just give them the item after the event is called as a workaround until it's fixed

**Comment by legoboy0215** [comment]
I can confirm this too.

**Comment by TDMidkwhatisxd** [comment]
Why is still not fixed? :|

**Comment by dktapps** [comment]
> Open-source, unpaid developers do not work according to a schedule. If you're unhappy with our development speed, I'd like to remind you of that. Nobody pays us to do this; we develop for free. So you can shut up complaining.

I ought to make that a saved reply.

**Comment by TDMidkwhatisxd** [comment]
At least dont make updates that break things 0-0 !

And ok! I understand that you code only for fun , but i could not help it! :D. 
And good luck !

**Comment by xxFlare** [comment]
@TDMidkwhatisxd Yes, @dktapps breaks things on purpose when he makes updates.

If your so concerned, why not make your own fork and code the fix yourself?

**Comment by TDMidkwhatisxd** [comment]
Nice ideea !

**Comment by dktapps** [comment]
@xxFlare that's uncalled for.

**Comment by dktapps** [comment]
@TDMidkwhatisxd you think you could do it better? By all means, continue to be self-centered and ungrateful. I put my hard time and effort into Genisys so people like you can use it, and what I get in return is spam and idiotic comments like that. This is a bug that resulted from the new transaction system I put in place for Windows 10 Edition.

**Comment by ZedCee** [comment]
@xxFlare That's unnecessary and untrue.  As with any development, stagnant code eventually causes problems and needs to be changed.  If said code is not changed, more features cannot be fixed or added without repercussions.  In fixing bugs, more may arise or be discovered.  Stop instigating with ignorrance.

@TDMidkwhatisxd Seriously, please take a second and think.  You spam constantly about us not coming to fix your plugin related issues or discovered bugs, but never think about what else we may have going on in our lives.  We are busy people and this is just a hobby, you're lucky to get anything at all.  For example, I, myself, am a full time student.  Genisys is not our (fulltime) day job.

**Comment by xxFlare** [comment]
@ZedCee I was saying that sarcastically. 😛

**Comment by TDMidkwhatisxd** [comment]
I think i could do it ! No better! Im just lazy!
I have some base in php , in past i did several projects on my local server !
(Chat, Mmorpg, Css maker , Chat maker etc... :p )

So dont think im a kid + Genisys staff are really mean!  They even call ppl idiots  without reason!
Got mad becouse i act like i could do it? Well , if i read the entire PocketMine code , i could do a stable fork for myself! But like you , i run pocketmine like a hobby and i dont ask for donations , even if i run my server for almost 2 years! So why to make such effort?

You say "we are working for free ;-; ". !!! I cant belive that ppl didnt donate to genisys! So if someone donate u get 0$?  If so is unfair!

This bug is critical for players who use /login ! I really dont care so much , i can wait even 1 year to be fixed! So stop with drama!

Im gratefull to you ! I know you are talented! If you wanna $ for your work, get hired by someone !

**Comment by legoboy0215** [comment]
That is the point. They want to help, not the money. But they always have the choice of not continuing Genisys. And @TDMidkwhatisxd, _"i could do a stable fork for myself"_ is some funny BS right there.

**Comment by TDMidkwhatisxd** [comment]
I plan to give up Genisys soon , and make my fork! So why i care?
Is just that im searching for a real job (i had a surgery and 1 year and half i could not leave home, so i quit my last job) , im really bussy , but i will make some time for it, and i wont make it open source!
So devs can close this project if all they do is playing around and leave holes for cheating! So , i dont care!

**Comment by AliMAltamimi** [comment]
hi can anyone tell me how to enable animals spawn 
there was an option, but now i can't find it

**Comment by dktapps** [comment]
@AliMAltamimi Unrelated topic. Stop spamming

**Comment by ScandiePlay** [comment]
Have you implemented Listener and registered the events? You can simple forget about it, as I did yesterday (I thought, why didn't my plugin work?...)
