### ISSUE TITLE
EntityDamageByEntityEvent isn`t work.

### ISSUE THREAD

**Issue by fuyutsuki** [iTXTech/Genisys#1963]
#### Issue description
EntityDamageByEntityEvent isn`t work.

#### Steps to reproduce the issue
- Write ```use pocketmine\event\entity\EntityDamageByEntityEvent;```
- public function onEntTap(EntityDamageByEntityEvent $e){  
echo "onEntityDamageByEntityEvent";  
}  

but not worked.

#### OS and versions

* Genisys: [latest master branch](9c13370ec33dad0e4f096447dbc5fd597f06d75a)
* PHP: iTXTech`s 7.1.10
* Server OS: Win10
* Game version: 0.15.8

#### Crashdump, backtrace, memory dumps, plugins list or other files

[Server thread/CRITICAL]: pocketmine\utils\PluginException:  "pocketmine\event\entity\EntityDamageByEntityEvent does not have a handler list" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 787

**Comment by Blubberboy333** [comment]
You don't use EntityDamageEvent as its own function. You would do something like this:

public function onEntityDamageEvent(EntityDamageEvent $event){
    if($event instanceof EntityDamageByEntityEvent){
        //This works
    }
}

**Comment by fuyutsuki** [comment]
Oh, Sorry I'm lack of study.
