### ISSUE TITLE
AnimatePacket not showing to players?

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#1965]
#### Issue description

I tried sending the animatepacket to everyone, making it set to a certain entity, but it didn't work, am I doing this wrong?
#### Steps to reproduce the issue

check code below

#### OS and versions

* Genisys: Any..?
* PHP: any
* Server OS: ubuntu linux
* Game version: 0.15

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
code:
				$pk2 = new AnimatePacket();
				$pk2->action = 1;
				$pk2->eid = $hit->getId();
				foreach($this->plugin->getServer()->getOnlinePlayers() as $pl){
					$pl->dataPacket($pk2);
                                }
```

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Do you know how to learn?** Elementary school seems suitable.

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
