### ISSUE TITLE
"[ERROR] Couldn't find a valid installation of Genisys"

### ISSUE THREAD

**Issue by JustJacko** [iTXTech/Genisys#1967]
-->
* Genisys: 0.16
* PHP: 7
* Server OS: Not sure
* Game version: Doesn't Matter 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```None Error is in the title
```

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
