### ISSUE TITLE
Mob branch - Notice: Undefined variable: p - Creeper.php

### ISSUE THREAD

**Issue by alicheek** [iTXTech/Genisys#1971]
Error:

Notice: Undefined variable: p in /home/minecraft/mcpe/src/pocketmine/entity/Creeper.php on line 123

[Server thread/CRITICAL]: Could not tick level "world": Call to a member function getGamemode() on unknown

Its not crashing the server at all but this is getting spammed in the logs.

**Comment by caspervanneck** [comment]
-_-

**Comment by dktapps** [comment]
Topic branch is stale and not intended for production use.

**Comment by dktapps** [comment]
> - Make sure you are using a build from the MASTER branch. Issues relating to non-production builds will be closed.

Nice job reading that...

**Comment by alicheek** [comment]
sorry just thought i would post it and try and help out since ai is something which is sought after in mcpe servers.

Any updates to what is happening with that, before when it was in i have to say it was working quite well.
