### ISSUE TITLE
0.15.9

### ISSUE THREAD

**Issue by Pogogo007** [iTXTech/Genisys#1973]
0.15.9 is out with some more stupid protocol changes!
Note* this is only to let you know if you didnt you may close this whenever you see it

**Comment by dktapps** [comment]
Thanks for spamming and not reading the issue template.

**Comment by dktapps** [comment]
> - Any issues requesting updates to new versions of MCPE will be treated as spam. We do not need spamming with issues to know that there is a new version available.
