### ISSUE TITLE
0.15.90 clients unable to connect to 0.15.9 Genisys server

### ISSUE THREAD

**Issue by ZizzyZizzy** [iTXTech/Genisys#1977]
#### Issue description
Windows 10 MCPE 0.15.9 clients are able to connect to the latest build without issues. However, mobile clients that have updated to 0.15.90 cannot. "Outdated Server" is the message received.

#### Steps to reproduce the issue
Update mobile device client MCPE to 0.15.90. (Shows 0.15.9 in the Play store.)
Attempt to connect to Genisys-c1ea9cc (codename "Kyrios")

#### OS and versions
* Genisys: Genisys-c1ea9cc 0.15.9
* PHP:  7.0.10
* Server OS: CentOS 6.7
* Game version: MCPE 0.15.90

#### Crashdump, backtrace, memory dumps, plugins list or other files
N/A

**Comment by TheAppleGamer** [comment]
0.15.9 and 0.15.90 are two different MCPE versions!

**Comment by ZizzyZizzy** [comment]
If 0.15.9 was intended to be 0.15.09, it would have been written as so, no?

Also, the mobile client may show 0.15.90 while in-game, but in the play store it IS listed as 0.15.9. Someone is being pedantic, I'm just not sure who.

**Comment by dktapps** [comment]
0.15.9 != 0.15.90. Also, we provide no official support for betas. General rule of thumb: If your issue involves a beta, don't bother submitting one.

**Comment by ZizzyZizzy** [comment]
Thanks. The devices I used were not supposed to be using BETA. I have two Google accounts on the devices, and Play store was apparently launched using the one with the BETA channel enabled.
Of course now the non-beta version won't launch without crashing on either the tablet or the phone...*sigh* Freaking Mojang developers.

**Comment by dktapps** [comment]
\#blamemojang is also a good rule of thumb ;)
