### ISSUE TITLE
XP is lost when player dies even if keep-experience:true

### ISSUE THREAD

**Issue by markkrueg** [iTXTech/Genisys#1978]
#### Issue description
XP is lost when player dies when genisys.yml =
```
#Choose if keep experience when a player died
 keep-experience: true
```

#### Steps to reproduce the issue
1) set in genisys.yml
keep-experience: true
2)  Join server. In console do "xp 3l PlayerName"
3) Die (drown is fine)
4) Note that all XP is lost.

#### OS and versions
* Genisys: c1ea9cc
* PHP: 7.0.3
* Server OS: Ubuntu server 16.04
* Game version: 0.15.9 iOS 10.0.2

**Comment by daniktheboss** [comment]
Hmm can't reproduce

**Comment by markkrueg** [comment]
Are you on Android or Windows? It's easy to reproduce on iOS. I'm wondering if it's specific to iOS.

**Comment by dktapps** [comment]
Levels are not equivalent to EXP. Only your raw exp is dropped, i.e. exp acquired from legitimate sources.

**Comment by markkrueg** [comment]
So if I am level 6, and I die, I show level 0. However, if I disconnect from the server and re-connect, I am back to level 6.

This seems confusing for the player.

**Comment by dktapps** [comment]
Your level is not directly tied to your exp. Otherwise your overall gamerscore would go down when you used an anvil for example, which isn't supposed to happen.
