### ISSUE TITLE
Version 0.15.9 Needs to be on servers (S

### ISSUE THREAD

**Issue by PiggyPigGaming** [iTXTech/Genisys#1980]
The servers are currently in 0.15.8 and a new MCPE/Win10 update came out "0.15.9" the server haven't been updated it to the latest version.
```

**Comment by TheAppleGamer** [comment]
It's been updated for a while, Lord knows where you've been!

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
