### ISSUE TITLE
Can't Join

### ISSUE THREAD

**Issue by LewBr** [iTXTech/Genisys#1981]
#### Issue description
Can't join to my local server!

#### Steps to reproduce the issue
I have all conected, my ip port address, firewall active but i cant join to my local server!
#### OS and versions

* Genisys: Least Update 147 phar
* PHP: 7.0
* Server OS: x64
* Game version: 0.15.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

``` 
http://prntscr.com/clq0vl
http://prntscr.com/clq116
```

**Comment by ParkChanSol** [comment]
If click your server list, what happened?

**Comment by iPocket** [comment]
Provide a valid OS, valid Genisys version, and try to disable firewall.

**Comment by LewBr** [comment]
How can i see my OS version and Genisys? my firewall is disabled now, and doesn't works.
(Srry english)

**Comment by LewBr** [comment]
Genisys config version 21.

**Comment by LewBr** [comment]
It works now, thanks!
