### ISSUE TITLE
Arrow not shooting if sneaking during loading

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Genisys#1983]
#### Issue description

When I load bow then sneak, the arrow does not come out.

#### Steps to reproduce the issue

Load bow, sneak, release.

#### OS and versions

* Genisys: Downloaded 24/09/2016 from main branch
* PHP:7
* Server OS:CentOS 7
* Game version: 0.15.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by iPocket** [comment]
For the genisys version, which commit?

**Comment by iPocket** [comment]
/version

On 24 September 2016 at 14:23, PocketKiller - Google <tahasalah585@gmail.com

**Comment by Guillaume351** [comment]
Downloaded just after this commit https://github.com/iTXTech/Genisys/commit/c1ea9cca6e87eaa45d288a5b8f2e9e16dabd15eb
