### ISSUE TITLE
No Gear Durability

### ISSUE THREAD

**Issue by SuperDude36** [iTXTech/Genisys#1985]
#### Issue description
Amor doesn't have durability

#### Steps to reproduce the issue
Get into a PvP fight with diamond gear (or any gear)
#### OS and versions

* Genisys: c1ea9cc
* PHP: 7.0.3
* Server OS: Mac
* Game version: 0.15.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
This issue has already been reported.
