### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MajorPlayz** [iTXTech/Genisys#1987]
Needing help with something I am trying to perfom. I wondered if it was possible to run muiltiple phars at the same time on the same server for like a compatibility server which works on many versions of MCPE as some of my players are on outdated clients.

Sorry if this isn't the right place to post. XP
Thanks,
Major

**Comment by TheAppleGamer** [comment]
Genisys removed all support except for 0.15.9 in their master build. They only did that, so capes will model correctly!

**Comment by MajorPlayz** [comment]
Yes I know but is there a way of doing this anyway?

**Comment by TheAppleGamer** [comment]
If you want messed up cape models, just edit the info.php under network and add the numbers 81, and 82 to the accepted protocols to allow all 0.15 players.

**Comment by MajorPlayz** [comment]
I dont have acess to the php files :/

Or i might...
Are they accesible on android?
Also thanks for the numbers will certainlty use those features _if_ i can acess the php files :D

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by MajorPlayz** [comment]
Sorry @dktapps :D
