### ISSUE TITLE
No Animals or creepers on latest version (Genisys_c1ea9cc_2016-09-23_09-02-19)

### ISSUE THREAD

**Issue by cyberjudge** [iTXTech/Genisys#1988]
#### Issue description
I've been playing around trying different things. I noticed a comment saying to add mobgenerate: true in the genisys.yml file which I have done and restarted the server but the existing world still is not showing animals or creeps. I do have spawn-animals=on and spawn-mobs=on in server.properties. In my server's genisys.yml there was no option already for spawn-animals so I had to add. Any suggestions how to get animals and creepers? I'm not using any mods.

#### OS and versions
Genisys: Genisys-c1ea9cc (codename "Kyrios")
PHP: 7.0.11
Server OS: Windows 10
Game version: 0.15.9 (Both on android and Windows)

This may just be an issue due to my lack of knowledge of setting up a minecraft server (this is my first attempt at setting up a minecraft server, though I do run other servers). Any help would be appreciated. Thanks.

**Comment by dktapps** [comment]
Your configs are outdated. The mob AI was removed due to licencing issues and various other things.

**Comment by cyberjudge** [comment]
So from this am I right to assume we can't have animals or creeper spawns?

**Comment by dktapps** [comment]
yes.
