### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by MajorPlayz** [iTXTech/Genisys#1992]
#### Issue description
Water does not replace when blocks are broken around it

#### Steps to reproduce the issue
Put blocks into a lake
Broke the blocks
The water did not replace where the blocks were

#### OS and versions

* Genisys: 149
* PHP: 7.0.3 (Not sure entirely)
* Server OS: Android
* Game version: 0.15.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

![screenshot_20160928-143655](https://cloud.githubusercontent.com/assets/19922783/18915606/7d3f7ed2-8589-11e6-9c90-55016b9c0fbf.png)

**Comment by MajorPlayz** [comment]
No sorry genisys #147 not #149 :D

**Comment by Muqsit** [comment]
Is chunk ticking > 0 in your pocketmine.yml?

**Comment by MajorPlayz** [comment]
Nopity nope nope

**Comment by Wizardon777** [comment]
solved it in my world by changing 
`chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 16`

to

`chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 1`

in pocketmine.yml

**Comment by MajorPlayz** [comment]
Ok thanks

**Comment by Muqsit** [comment]
So it's solved!?

**Comment by MajorPlayz** [comment]
Sorta, It works in the fact that the water does replace but sometimes it doesn't. Will personally look into this.

Also, @Muqsit do you have Gitter? I wondered if we could make a plugin together :D as your code looks smart! Sorry a little off topic xD

**Comment by Muqsit** [comment]
I don't use gitter often. But i'd like to get updates about this issue, since I cannot produce it by myself.

**Comment by MajorPlayz** [comment]
Ok haha! Do you want to make a plugin with me? @Muqsit
