### ISSUE TITLE
World issues.

### ISSUE THREAD

**Issue by BegForMercyMCPE** [iTXTech/Genisys#1994]
#### Issue description
The map was generated as flat on the first build of 0.15.9 in android app called Pocket Server. I usually use this kind of trick to build maps offline and never had any errors when transfered the world folder to main server that runs Linux OS. And now, I made world transfered to main server and the build doesn't seems to appear in main server and the console starts to spamming errors. The errors will be shown on the last line.
#### Steps to reproduce the issue
The world being generated on first 0.15.9 build as flat on android app called Pocket Server. Made transfer to another server that run by Linux and the world seems to be empty when server started yet it start to spamming errors.

#### OS and versions

* Genisys: latest build of 0.15.9
* PHP: 7.0.3
* Server OS: Linux Ubuntu 64 bit
* Game version: 0.15.9

#### Crashdump, backtrace, memory dumps, plugins list or other files
Notice: Undefined offset: 1015 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2039 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1016 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2040 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1017 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2039 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1016 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2040 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1017 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2041 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1016 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2040 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1017 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2041 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1018 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2040 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1017 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2041 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1018 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2042 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1017 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2041 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1018 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2042 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1019 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2041 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1018 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2042 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1019 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2043 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1018 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2042 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1019 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2043 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1020 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2042 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1019 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2043 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1020 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2044 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1019 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2043 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1020 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2044 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1021 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2043 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1020 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2044 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1021 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2045 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1020 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2044 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1021 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2045 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1022 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2044 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1021 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2045 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266

Notice: Undefined offset: 1022 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 265

Notice: Undefined offset: 2046 in phar:///home/beg/PocketMine-MP.phar/src/pocket
mine/level/format/mcregion/RegionLoader.php on line 266
mine/level/format/mcregion/RegionLoader.php on line 265                         |
                                                                                |
Notice: Undefined offset: 2045 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 266                         |
                                                                                |
Notice: Undefined offset: 1022 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 265                         |
                                                                                |
Notice: Undefined offset: 2046 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 266                         |
                                                                                |
Notice: Undefined offset: 1023 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 265                         |
                                                                                |
Notice: Undefined offset: 2047 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
Notice: Undefined offset: 2047 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 266                         |
                                                                                |
Notice: Undefined offset: 1024 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 265                         |
                                                                                |
Notice: Undefined offset: 2048 in phar:///home/beg/PocketMine-MP.phar/src/pocket|
mine/level/format/mcregion/RegionLoader.php on line 266                         |

**Comment by BegForMercyMCPE** [comment]
Sorry, I forgot the build number of first 0.15.9 build, do you have any idea whats the problem?

**Comment by Muqsit** [comment]
Use anvil.

**Comment by BegForMercyMCPE** [comment]
Why anvil? The map is mcregion format. 
There's another missing errors.
Warning: fwrite() expects parameter 1 to be resource, boolean given in phar:///h
ome/beg/PocketMine-MP.phar/src/pocketmine/level/format/mcregion/RegionLoader.php
Warning: fseek() expects parameter 1 to be resource, boolean given in phar:///ho
me/beg/PocketMine-MP.phar/src/pocketmine/level/format/mcregion/RegionLoader.php
on line 287

Warning: fwrite() expects parameter 1 to be resource, boolean given in phar:///h
ome/beg/PocketMine-MP.phar/src/pocketmine/level/format/mcregion/RegionLoader.php
 on line 288

Warning: fseek() expects parameter 1 to be resource, boolean given in phar:///ho
me/beg/PocketMine-MP.phar/src/pocketmine/level/format/mcregion/RegionLoader.php
on line 289

Warning: fwrite() expects parameter 1 to be resource, boolean given in phar:///h
ome/beg/PocketMine-MP.phar/src/pocketmine/level/format/mcregion/RegionLoader.php
 on line 290

**Comment by BegForMercyMCPE** [comment]
Did tried changing the mcregion to anvil in pocketmine.yml, it doesn't seems to do anything, just same errors.

**Comment by Muqsit** [comment]
Seems like a permission error. You might not be having ful authority on PocketMine-MP.phar

**Comment by ZedCee** [comment]
Nailed it @muskit, I knew those errors looked familiar. I frequently see this in my edits, as on a Linux platform MCEdit ends up needing to be run as root if you install it.  

@BegForMercyMCPE, you may have to get out the good old `chgrp` and `chown`.
Let us know how that works for you.
