### ISSUE TITLE
Rcon

### ISSUE THREAD

**Issue by devin5411** [iTXTech/Genisys#1995]
How do I setup rcon?

**Comment by gaoyichuan** [comment]
See server.properties

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
