### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by RandomAltThingy** [iTXTech/Genisys#200]
1. Get rid of those weird round lakes that are in PocketMine, or make them less common.
2. Add more grass to plains biomes.
3. Maybe add village generation too?
4. Last, but not least, stop ripping off a plugin and actually edit the code of it. You can see it's been directly taken from the plugin and you haven't even removed the japenese (?) comments from it. **other than that great work!**

**Comment by Efforto** [comment]
more grass and village generation is not come true in Nukkit , so Genisys will not.
我只想问你是傻逼吗（DO NOT TRANSLATE IT.）

**Comment by gaoyichuan** [comment]
you haven't even removed the japenese (?) comments from it. They are **Chinese**

**Comment by jasonczc** [comment]
@Efforto  别骂人,国人脸被你丢尽了...
@RandomAltThingy Sorry about @Efforto 's words.
We changed a lot....Genisys is made for Chinese at first.So we deleted other languages.
And I am so sorry that we are powerless about Japanese.
If you want,you can help us to finish multi language work.

**Comment by RandomAltThingy** [comment]
OK, I will help

**Comment by RandomAltThingy** [comment]
Alright, can I remove some of the random Chinese messages in the AI classes  ? And those debug logger messages that are **commented** and have no use.

**Comment by Efforto** [comment]
nope:)Translate it

**Comment by Efforto** [comment]
if i can, i'll.translate it.(maybe 12 hours later,i stay up whole night...)

**Comment by Efforto** [comment]
these messages sometimes useful for developers

**Comment by RandomAltThingy** [comment]
Well I will remove the completely useless ones and keep most I will add it to the language files.

**Comment by gaoyichuan** [comment]
@jasonczc I removed the line from the comment. 维护国人的脸面吧。。

**Comment by jasonczc** [comment]
@RandomAltThingy ZombieAI in Genisys is developed by Chinese first so during development we use Chinese to debug and we've already note(I am not sure the English of"注释") it.If you want to understand the resource ,you can use Google Translate.I think translate the note in the resource is insignificance because when it is working,it won't send ANY message to player or debug sth in the console.

**Comment by jasonczc** [comment]
I'll translate those note into English soon.

**Comment by jasonczc** [comment]
The algorithm of the generator is difficult xD.It won't finish in a short time.But when we have chance we'll try to develop it.Now biomes is OK.U can change the color of grass and water.
Most of developers in Genisys are in high school or middle school so the algorithm may be a big challenge for us.
If you want to get rid of the strange terrain,why not try to use McEdit to create a big map on PC.It has complete village generation and plain biomes.
P.S.My Chinglish is good xD.

**Comment by gaoyichuan** [comment]
You can also have a try on Minecraft Land Generator, it's a handy tool to use
