### ISSUE TITLE
Master Plugins

### ISSUE THREAD

**Issue by Nickleog** [iTXTech/Genisys#2002]
#### Issue description
When will the master plugin update for 0.15.9 come? Because when i start the server only the .phar plugins loads

#### OS and versions

* Genisys: 5fc2854
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Minecraft PE v0.15.9 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Nickleog** [comment]
what? why?

**Comment by Nickleog** [comment]
Need an answer

**Comment by dktapps** [comment]
Please review the contribution guidelines and FAQs efore opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by Nickleog** [comment]
oh ok 👍
