### ISSUE TITLE
World Problem

### ISSUE THREAD

**Issue by Nickleog** [iTXTech/Genisys#2007]
#### Issue description

I use Anti-Fly on my server, whenever a player is detected flying and kicked, console gives me this error [Server thread/CRITICAL]:  "Could not tick level "world": Call to a member function getAttribute() on null"
#### Steps to reproduce the issue

Use Anti-Fly and get detected
#### OS and versions

* Genisys: abad89e
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Minecraft PE v0.15.9 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files

```None
```

**Comment by dktapps** [comment]
Invalid, Genisys doesn't kick flying players. Check your plugins.

**Comment by Nickleog** [comment]
i know, i used anti fly by Lambo but what about the error?

**Comment by Nickleog** [comment]
???

**Comment by Nickleog** [comment]
Does this silence mean you dont't know and you just like to close an issue?

**Comment by dktapps** [comment]
This is a plugin issue. Contact the developer instead of spamming,
