### ISSUE TITLE
DKT KILL URSELF

### ISSUE THREAD

**Issue by Nickleog** [iTXTech/Genisys#2008]
#### Issue description

DKTAPPS BEING AN ASS
#### Steps to reproduce the issue

POST AN ISSUE
WAIT 2 SECS
DKTAPPS CLOSES IT OR REPLIES SOMETHING BITCHY
#### OS and versions

* Genisys: DKTASS
* PHP: 7.0.DKTASS
* Server OS: ASS
* Game version: 0.15.DKTASS

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
DKT CRASHASS
```

**Comment by dktapps** [comment]
Wow, how amazingly immature. Congratulations, you just got yourself a ban.

**Comment by caspervanneck** [comment]
thats wy i dont post issue (tink about it houw shult genisys by with spam [dat is not good])

**Comment by caspervanneck** [comment]
sorry for bad eng
