### ISSUE TITLE
flower pot bug

### ISSUE THREAD

**Issue by smyb** [iTXTech/Genisys#201]
When i pick up a flower pot , a stack of the item that i'm holding is dropped , i also made a video so you can test it on your own [video](https://youtu.be/l9YcNbz48-8)

**Comment by PocketKiller** [comment]
LOL

**Comment by GalvinGao** [comment]
sure that has this problem. saving in china webdisk.

**Comment by svilex** [comment]
?

**Comment by Efforto** [comment]
Ah , youtube is blocked
and a bug is that, you put on a flower on it,and it is redflower(other flower is too)

**Comment by PainTR** [comment]
Lol youtube is blocked in china

**Comment by svilex** [comment]
use vpn. @Efforto this is a different bug

**Comment by gaoyichuan** [comment]
I think it's a possible bug, but I can't reproduce it using the method in the video. My version is the newest github pull.
