### ISSUE TITLE
Unable to spawn MOBS

### ISSUE THREAD

**Issue by Wizardon777** [iTXTech/Genisys#2010]
#### Issue description
No animals or monsters are spawning on my server (wizardon.zapto.org:19132).
your help will be appreciated!

#### Steps to reproduce the issue
pocketmine.yml:
`ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15`

server.properties
`spawn-animals=on
spawn-mobs=on
difficulty=1
`
genisys.yml
`ai:
 #AI switch
 enable: true
 #Zombie'AI，0=disabled，1=AI 1.0ver，2=new AI(Faultiness)
 zombie: 1
 #PigZombie's AI
 pigzombie: true
 #the AI of cow and mushroom cow
 cow: true
 #Chicken's AI
 chicken: true
 #Sheep's AI
 sheep: true
 #Pigs' AI
 pig: true
 #Skeleton's AI
 skeleton: true
 #Creeper's AI
 creeper: true
 #Iron golem's AI
 iron-golem: true
 #Snow golem's AI
 snow-golem: true
 #Destory blocks if creeper exploded
 creeper-explode-destroy-block: false
 #Choose if allow mob auto generate
 mobgenerate: true 
`
#### OS and versions
* Genisys: 1a4abbc
* PHP: 7.0.11.0
* Server OS: Windows 10 Pro
* Game version: 0.15.9

#### Plugins list
essentialsTP v1.0.9
LiveXYZ v0.5.0-alpha
SimpleAuth v1.7.2
SimpleAuthHelper v2.0.4

**Comment by dktapps** [comment]
Mob spawning is not currently implemented. It was removed along with the nasty AI due to licensing issues.

**Comment by Wizardon777** [comment]
ahh... ok, thank you!
will it be back soon?

**Comment by dktapps** [comment]
Not likely.

**Comment by Wizardon777** [comment]
oh... too bad...
Thanks anyway...

**Comment by TristonStuart** [comment]
Is there a plugin that can do this?

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before spamming.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
