### ISSUE TITLE
Blocks not updating on $chunk->setBlock()

### ISSUE THREAD

**Issue by jjplaying** [iTXTech/Genisys#2011]
#### Issue description

When updating a block of a chunk with $chunk->setBlock(), it's sometimes not sent to the client. When you rejoin, the blocks are there. $level->setBlock() is working without fine, but I can't use it async.

#### Steps to reproduce the issue

See the plugin code down.

#### OS and versions

* Genisys: 6ccefaeea951cbde62ac6ef174f15b006376df15
* PHP: 7.0.11
* Server OS: Debian 8 x64
* Game version: 0.15.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

Plugin code:

```
public function onRun() {
        $chunkClass = $this->getChunkClass();
        $chunks = unserialize($this->getChunks());

        foreach($chunks as $hash => $binary) {
            $chunks[$hash] = $chunkClass::fromBinary($binary);
        }

        $x = $this->getX();
        $y = $this->getY();
        $z = $this->getZ();

        $tox = $x + 20;
        $toz = $z + 20;
        $toy = $y + 20;

        for($cx = $x; $cx <= $tox; $cx++) {
            for($cy = $y; $cy <= $toy; $cy++) {
                for($cz = $z; $cz <= $toz; $cz++) {
                    $hash = Level::chunkHash($cx >> 4, $cz >> 4);

                    if(isset($chunks[$hash])) {
                        $chunks[$hash]->setBlock($cx & 0x0f, $cy & 0x7f, $cz & 0x0f, Block::AIR & 0xff);
                    }
                }
            }
        }

        $this->setResult($chunks);
    }

    public function onCompletion(Server $server) {
        $chunks = $this->getResult();
        $levelId = $this->getLevelId();

        $dangerousValley = $server->getPluginManager()->getPlugin("DangerousValley");

        if($dangerousValley instanceof DangerousValley) {
            $level = $server->getLevel($levelId);

            if($level instanceof Level) {
                foreach($chunks as $hash => $chunk) {
                    Level::getXZ($hash, $x, $z);

                    $level->setChunk($x, $z, $chunk);
                }
            }
        }
    }
```

**Comment by dktapps** [comment]
Wow... I don't think that's actually intended for use in plugins. Are you writing a structure generator or something?

**Comment by jjplaying** [comment]
I'm writing a minigame where the arena is generated randomly for each game and inspired at the async code of https://github.com/Falkirks/MineReset.

**Comment by dktapps** [comment]
I think that function is only really intended for internal use. You'd have to schedule block update sending manually.

**Comment by jjplaying** [comment]
Okay, I'll do that. But I think this function worked in PocketMine because otherwise, Falkirks wouldn't have published his plugin to the plugin page.

**Comment by dktapps** [comment]
Did you copy the code to the letter? or modify it? I don't think updates would be sent unless you either sent them manually or resent the modified chunks.

**Comment by jjplaying** [comment]
I modified it, but there's only one function $level->setChunk(); in MineReset, nothing else which could update blocks. I'll send the updated chunks to every player.

**Comment by jjplaying** [comment]
I fixed it with sending the chunks again to the client, so this issue can be closed. Nevertheless, I'm thinking it worked in PocketMine, because MineReset also worked in PocketMine-times.
