### ISSUE TITLE
error spamming the console constantly 

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#2012]
#### OS and versions
* Genisys: c1ea9cca
* PHP: PHP version: 7.0.2
* Zend version: 3.0.0
* OS : Linux, linux
* Game version: android ( 0.15.9 )

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

i know this is maybe not for official use ( or whatever u call it ) . and im not complaining about  it im just letting u know this issue . 

if u have a fix for it let me know . if not just close this issue and please try to fix it . thanks

**Comment by mote166** [comment]
sorry idk what happend here are the errors  ->

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///jar/versions/Genisys/Genisys_c1ea9cca.phar/src/pocketmine/inventory/PlayerInventory.php on line 103 

and this 

Deprecated: This method is deprecated, do not use it in phar:///jar/versions/Genisys/Genisys_c1ea9cca.phar/src/pocketmine/Player.php on line 361

**Comment by dktapps** [comment]
Plugin issues.

**Comment by mote166** [comment]
how ? i didn't add any plugin. im using the same plugins from 0.14.0 and it didn't  spam me with these errors

**Comment by IrishUHC** [comment]
Let me explain, some methods from PocketMine circa 0.14 have since deprecated via 0.15. So your plugins have deprecated methods now.

**Comment by dktapps** [comment]
@IrishUHC actually they were deprecated by me in the Windows 10 Beta support update. Apart from that well explained. :P

**Comment by IrishUHC** [comment]
@dktapps Explains the PlayerInventory getting spammed instead of others. Since inventory was revamped since then, correct?
