### ISSUE TITLE
error import map

### ISSUE THREAD

**Issue by AliMAltamimi** [iTXTech/Genisys#2013]
#### Issue description

can't import pc map to genisys 
#### Steps to reproduce the issue

using pmimporter 
im file path    for example: im F:\Myworlds\world4 world4
#### OS and versions

* Genisys: 498379b
* PHP: 7.0.11 x86
* Server OS: windows 
* Game version: 0.15.9
[import map error.txt](https://github.com/iTXTech/Genisys/files/506212/import.map.error.txt)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Plugin issue. Use a newer version of pmimporter.

**Comment by AliMAltamimi** [comment]
i am using latest version 1.5upd2
