### ISSUE TITLE
Anti-Cheat is bugging

### ISSUE THREAD

**Issue by jjplaying** [iTXTech/Genisys#2016]
#### Issue description

The anti-cheat is bugging you down heavily sometimes, when you are jumping between blocks in the void. See the screenshot below to see what type of world I mean.
#### Steps to reproduce the issue

Just take a void world, build some blocks with a bigger distance, and jump over them.
#### OS and versions

- Genisys: 498379bfc4903533ea99d275a6daecba1088ed0b
- PHP: 7.0.11
- Server OS: Debian 8 x64
- Game version: 0.15.9
#### Crashdump, backtrace, memory dumps, plugins list or other files

![img_0431](https://cloud.githubusercontent.com/assets/15860314/19048685/aec01828-89a7-11e6-9413-70617991607d.PNG)

**Comment by JackNoordhuis** [comment]
Closing this issue here as relevant issues are open over at the PMMP repo. https://github.com/pmmp/PocketMine-MP/issues/169
