### ISSUE TITLE
PlayerKickEvent::setQuitMessage() does not work

### ISSUE THREAD

**Issue by MyNameIsTriXz** [iTXTech/Genisys#2017]
I experience it since 13.0, this function does not work, it still says the default one instead of the modified.

**Comment by LazzKiller** [comment]
No have setQuitMessage for this event, i think, just for event PlayerQuitEvent.

**Comment by IrishUHC** [comment]
I'll make a PR to fix this.

**Comment by JackNoordhuis** [comment]
This is a client/internet speed related issue. Sometimes the client disconnects before the packet containing the kick message is received.

**Comment by IrishUHC** [comment]
Smart cookie ^.

**Comment by dktapps** [comment]
Are you trying to modify the "xxx left the game" message or the "Kicked by admin" message?

**Comment by dktapps** [comment]
This has been closed due to lack of response. If the issue still occurs please comment and update the ticket and it will be reopened.
