### ISSUE TITLE
Compile.sh 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#2020]
trying to set up a new server but cant find the Compile.sh file. any advice?

**Comment by IrishUHC** [comment]
So you are on Linux? What distribution? I'm guessing Ubuntu, but I could be mistaken. Also make sure to follow the issue template or they'll close it instantly.

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by Tolo0** [comment]
its not really a issue.  thats why i didn't use the template.  sorry dktapps.
i just need the compile.sh to create a server. i ust to use.

wget https://github.com/iTXTech/php-build-scripts/archive/master.zip; unzip master.zip; rm -rf master.zip; cd php-build-scripts; chmod +x *.sh; screen -s x ./compile.sh

but now i get error 404 from the compile.sh part.

Linux  Centos 6.7

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by iPocket** [comment]
@dktapps You're acting like a bot :D

**Comment by gaoyichuan** [comment]
You know that's not a issue, so
