### ISSUE TITLE
15.10 not same protocol?

### ISSUE THREAD

**Issue by AomSkr** [iTXTech/Genisys#2023]
#### Issue description

 15.10
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheAppleGamer** [comment]
Check my PR

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
