### ISSUE TITLE
Hopper duplication bug

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#2029]
#### Issue description

Hoppers can duplicate items

#### Steps to reproduce the issue

Place 2 hoppers next to each other side by side and a double chest in front of them

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/498379bfc4903533ea99d275a6daecba1088ed0b
* PHP: 7.0.9
* Server OS: Ubuntu 14.06
* Game version: 0.15.X

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Skull3x** [comment]
Yes, I also experienced a similar issue.

If you drop a stack of an item it will double, for me that only happens if the item before lands on to the middle of the 2 hoppers.

**Comment by dktapps** [comment]
You also have a duplication bug... #1768

**Comment by XFuryMCPE** [comment]
This should be a main bug to be fixed, because it defeats the purpose of survival when everyone is duplicating everything.
