### ISSUE TITLE
sometimes naive!!!

### ISSUE THREAD

**Issue by 13358172372** [iTXTech/Genisys#2032]
who can fuck me????

**Comment by 13358172372** [comment]
i am dalao

**Comment by CreeperGo** [comment]
excuse me?
大佬您的整合包后门很厉害啊

**Comment by ExerciseBook** [comment]
没搞懂发生了什么。。。

**Comment by CreeperGo** [comment]
@ExerciseBook @13358172372 大佬发布带后门的东西声称可以远程删除文件，然后被对大佬反感人士盗号

**Comment by PeratX** [comment]
@13358172372 You have been banned.
