### ISSUE TITLE
Option to disable player.dat

### ISSUE THREAD

**Issue by AndreyNazarchuk** [iTXTech/Genisys#2035]
Can you guys provide an option to disable the saving of player.dat files?

In production servers they are a nuisance because the plugins query a database for any information that has to stay after the player leaves.

Thank you!

**Comment by daniktheboss** [comment]
Did you think before asking?

**Comment by inferboy** [comment]
Hahahahahahah

**Comment by daniktheboss** [comment]
Plugins don't save any data. They use the player.dat file! Plugins are lines of code that perform the action you tell it to!

**Comment by Aericio** [comment]
Please...
Disabling player.dat files = disabling saving player data (such as inventory, gamemode, etc)
If it really did cause lag from "plugins querying" them, then it would've been loooooong gone or used a different method.

**Comment by Tarik02** [comment]
+1. This very useful for mini-games. Player always starts from zero or items given from plugin. Saving of player's data is not used.

**Comment by Aericio** [comment]
A plugin could do all of that... Tell it to clear the players inventory, reset their scores, etc.

**Comment by vvzar** [comment]
> Tell it to clear the players inventory, reset their scores, etc.

When you have ton of players and around million registrations - issue is in files player.dat themselves. As a result, after those thousands players connect to the server for the first time, my players folder fills with many useless files <nick>.dat and I have to use crutches to handle this (remove them regularly, or move players folder at some ramdisk...)
Is this possible to have ability to disable function of auto create inventory files by server. It could be just an option in genisys.yml. Thank you.

**Comment by dktapps** [comment]
This would be very easy to implement.

**Comment by MattWAnderson** [comment]
Hmm +1.. we have done this for years on some of our servers with various methods of removing write perms to players to now just having it coded to be deleted on certain events such as leave.

**Comment by dktapps** [comment]
It's added, have fun.

To use the feature, add:
```
player:
 save-player-data: false
```

to your pocketmine.yml and reboot the server.
