### ISSUE TITLE
Item setCustomName() bug!

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#2038]
#### Issue description

When setting an item's name via setCustomName($string), the custom name isn't shown **until the player relogins.**
#### Steps to reproduce the issue

On PlayerInteractEvent by any $event->getItem(), do this:

``` php
$item = $event->getItem();
$item2 = Item::get($item->getId(), $item->getDamage(), $item->getCount());
$item2->setCustomName("Used item\n"."By ".$event->getPlayer()->getName());
$event->getPlayer()->getInventory()->setItem($event->getPlayer()->getInventory()->getHeldItemSlot(), $item2);
$event->getPlayer()->getInventory()->remove($item);
```
#### OS and versions

- Genisys: (Pulled from Jenkins) 80faae0
- PHP: 7.0.10
- Server OS: Ubuntu 14.04 LTS (64-bit)
- Game version: 0.15.10
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
No traces, sadly.
```

**Comment by intagaming** [comment]
This was my problem exactly.
I was working with setNamedTag(), this way works flawlessly. I had tried drop the item on the ground with minimum pickup delay and it works too.

**Comment by ImagicalGamer** [comment]
Try using ```php $player->getInventory()->sendContents($player); ```

**Comment by intagaming** [comment]
It won't work. The "name" field in CompoundTag needs to be updated with the custom name in order to be shown to the player. sendContents() sends the items, not change them.

**Comment by ImagicalGamer** [comment]
@intagaming I had the same issue and I resent the inventory's contents to the player and I can now use Item::setCustomName(); like normal.

**Comment by intagaming** [comment]
@ImagicalGamer I don't remember so well, in conclusion this has no mean and need a fix.

**Comment by Shadow166050** [comment]
I have his same issue, and $player->getInventory()->sendContents($player); won't work :/

**Comment by erkam2002** [comment]
public function onInteract(PlayerInteractEvent $event){
$player = $event->getPlayer();
$item = $event->getItem()->getId();
$itemdmg = $event->getItem()->getDamage();
$itemcount = $event->getItem()->getCount();
$item1 = Item::get($item, $itemdmg, $itemcount);
$name = $player->getName();
$item->setCustomName("Used item\n"."By ".$name);

**Comment by dktapps** [comment]
Bug since the Win10 inventory update.

**Comment by GenisysFTW** [comment]
@dktapps Probably.
I've found a way to reproduce it (P.S. You may close it).

If you...
$item->addEnchantment(...);
$item->setCustomName(...);
You can reproduce this bug. But if you...
$item->setCustomName(...);
$item->addEnchantment(...);
It works fine.
