### ISSUE TITLE
add option to disable Xbox login

### ISSUE THREAD

**Issue by mote166** [iTXTech/Genisys#2039]
#### Issue description

add an option to disable the xbox login 
#### OS and versions

* Genisys: c1ea9cca
* PHP: 7.0.11
* Server OS: linux
* Game version: android

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by mote166** [comment]
k thx
