### ISSUE TITLE
[ANNOUNCEMENT] Fixes for RakLib DoS vulnerabilities

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#2040]
**It is strongly recommended that all users update to the latest build as soon as possible**. This patches several DoS vulnerabilities found in RakLib causing unresponsive servers.

Further details can be found on the original PR at https://github.com/pmmp/RakLib/pull/1

**Comment by KairusDarkSeeker** [comment]
😱

**Comment by dterweij** [comment]
Looks like that something is broken. Serverlist is acting weird. 

[img]http://prntscr.com/csflbz[/img]
