### ISSUE TITLE
Corrupt chunk detection / fix

### ISSUE THREAD

**Issue by beetree** [iTXTech/Genisys#2042]
#### Issue description
I have fairly frequent corrupts of chunks. It's at a level where it's causing significant problems.

#### Steps to reproduce the issue
1. Set up a fresh clone of Genisys
2. Drop in this map: leet.cc/corrupt_world.tgz
3. Start the server
4. Read the sign in-game and follow the directions to find the corrupt chunk
Please note: If you can't see the sign in-game, delete the players/ folder so that you spawn on the default of the map.

#### OS and versions
Ubuntu 16.04, custom built php7, Fresh clone from Genisys github ~10 minutes ago

#### Crashdump, backtrace, memory dumps, plugins list or other files
No plugins, fresh install

I'm not looking for manual fix of this chunk (obviously). I think the fix for issues like this should be to detect it inside Genisys and regenerate the chunk.

Thanks a ton for the help!

/beetree

**Comment by dktapps** [comment]
Automatic regeneration is a bad idea, because any corrupted data will be lost altogether, beyond recovery. It's preferable to regenerate these manually instead.

**Comment by AlphaMusty** [comment]
Hi

**Comment by eDroidPlayzYT** [comment]
Why can't chunks generate like on PC?
