### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#2043]
#### Issue description
Server keeps crashing due to out of memeory. all memory limits including soft, hard memory limits are set to 0 but it still crashes. allocated memory for the server is 2GB but the server only uses about 200 MB at the time of crash

#### Steps to reproduce the issue
Happens randomly

#### OS and versions

* Genisys: Genisys Build 168 2f820fe
* PHP: 7.0.10
* Server OS: Windows 10
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files
Genisys Crash Dump Sat Oct 8 18:20:22 BST 2016

Error: Out of memory (allocated 557842432) (tried to allocate 65536 bytes)
File: /src/pocketmine/nbt/NBT
Line: 512
Type: E_ERROR

Code:
[503] }
[504] return $this->buffer;
[505] }
[506] 
[507] return false;
[508] }
[509] 
[510] public function writeCompressed($compression = ZLIB_ENCODING_GZIP, $level = 7){
[511] if(($write = $this->write()) !== false){
[512] return zlib_encode($write, $compression, $level);
[513] }
[514] 
[515] return false;
[516] }
[517] 
[518] public function readTag(){
[519] switch($this->getByte()){
[520] case NBT::TAG_Byte:
[521] $tag = new ByteTag($this->getString());
[522] $tag->read($this);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 84; API 2.0.0]
uname -a: Windows NT NS306121 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
PHP version: 7.0.10
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 1 hours 20 minutes 12 seconds
Number of loaded worlds: 9
Players online: 14/20

Loaded plugins:
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
BlockCmdPE 1.0.1 by Vaivez66 for API(s) 1.12.0, 2.0.0
BlockSniffer 1.0.0 by DRedDogPE for API(s) 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
DevBAN 1 by Ragnok123 for API(s) 1.13.1
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
Economy2 1.1.1 by ProjectInfinity for API(s) 2.0.0
Economy2Shop 1.0.0 by ProjectInfinity for API(s) 2.0.0
EconomyAPI 0.1.0 by ProjectInfinity for API(s) 1.12.0
Functions 1.0 by Ad5001 for API(s) 1.14.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
Oplist 1.0.2 by for API(s) 2.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
LeetTP 1.0.0 by ProjectInfinity for API(s) 2.0.0
Afk 0.3 by hoyinm14mc for API(s) 1.12.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
PurePerms 1.3.6 by 64FF00 for API(s) 1.13.0, 2.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
Rotater 1.1.0 by for API(s) 1.11.0
seat 2.1.0 by MineRourii for API(s) 1.0.0
ServerBackup 1.0.0 by for API(s) 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0, 2.0.0
1vs1 0.0.5 by for API(s) 1.0.0, 1.1.0, 2.0.0
Nick 1.0.1 by AryToNeX for API(s) 1.12.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0, 2.0.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
VIP1b 2.0.0 by for API(s) 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
WarnPlayer 1.0.0 by applqpak for API(s) 1.0.0
WorldEdit 2.1.0 TRANSLATE BY ZIKEN by ikenusi / ByZikenPE, hmy2001(Plug- source reference) for API(s) 1.13.0
WorldGM 1.1.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
xyz 1.0.1 by unerds for API(s) 1.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0, 2.0.0
WarpSigns 0.0.1 by Falkirks for API(s) 1.12.0, 2.0.0
BBDoDo NetherBox by KaitoDoDo for API(s) 1.0.0, 2.0.0
AdvancedKits 5.0b1 by luca28pet for API(s) 2.0.0
BanItem 2.1 by LDX for API(s) 1.0.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0, 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomyLand 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EmotionsPE 1 by paetti for API(s) 1.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0, 2.0.0
GameStats 1.0.0 by ace, wolfdale for API(s) 1.2.0
GameTime 1 by FaigerSYS for API(s) 1.13.0, 2.0.0
HungerGames build#06 by xbeastmode for API(s) 2.0.0
iProtector 3.1a by LDX for API(s) 2.0.0
Jail Alpha0.1.1 by hoyinm14mc for API(s) 2.0.0
MysU&GlxPet_v1.0 1.0.1 by Adam1609&Justin for API(s) 2.0.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
PureChat 1.3.3 by 64FF00 for API(s) 2.0.0
ServerChannels 1.2 by EvolSoft for API(s) 1.11.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0, 2.0.0
Slapper 1.2.9.6 by jojoe77777 for API(s) 2.0.0
StatsPE 2.4.6 by SalmonDE, Aericio, robske_110, XenialDan for API(s) 2.0.0
SW_svile 0.6dev by svile for API(s) 2.0.0
SynapseTransfer 1.0.0 by iTX Technologies for API(s) 2.0.0
TurfWars 1.0.0 by MyNameIsTriXz for API(s) 2.0.0
WildTP 0.0.1 by Taki21 for API(s) 1.14.0, 2.0.0
KillRate 2.1.1b by aliuly for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 2.0.0
RankUp 0.3.1 by Falkirks for API(s) 1.4.0

**Comment by Muqsit** [comment]
1h, 9 worlds, soon many plugins...this is expected.

**Comment by dktapps** [comment]
To help us resolve this, you can create a memory dump when your server is at high usage and upload it and send a link.

How to create a memory dump:
1. Open your `pocketmine.yml` and set `debug.commands` to `true`
2. Run your server. You can use `/status` to see how much memory your server is using.
3. When the memory usage is near the limit, run `/dumpmemory`. This will create a memory dump in your server folder under `/memory_dumps`.
4. Compress the memory dump and upload it to a file host and post a link so that our developers can examine it.

Thanks for your cooperation.

**Comment by dktapps** [comment]
Linking this to #1788 so I can clear up the issue tracker some. Please feel free to comment here.
