### ISSUE TITLE
Enchantment Table / Anvil | BUG

### ISSUE THREAD

**Issue by ItzRadius** [iTXTech/Genisys#2044]
#### Issue description

Their's a bug when the player uses the enchantment table the item that they enchant disappears or the item fly's out of the enchantment table and the player cannot pick it up and get the item back. Also this does the same thing to the Anvil as well.

#### OS and versions

* Genisys: Genisys-c6ef55e (codename "Kyrios")
* PHP: 7.0.8
* Server OS: Linux
* Game version: 0.15.10

```
```

**Comment by Gianluxx** [comment]
On my server works. The item pops out if you close the inventory of the ench_table/anvil with the item still inside but i can pick it up. Try enable on genisys.yml the use anvil and use enchtable.

**Comment by dktapps** [comment]
Set inventory.allow-cheats to true. This is a well-known issue with Win10 Edition. Also, anvils are not fully implemented yet.
