### ISSUE TITLE
0.16 (Must Read)

### ISSUE THREAD

**Issue by karanpatel567** [iTXTech/Genisys#2047]
Genisys whats the point making 0.16 beta phar's when they don't even work not to be rude but they do not work and they wasting your time and also your issue tickets. I am currently downloading all your 0.16 latest phar they don'twork because when i try to join my server it crashes so whats the poinnt your just wasting your time.

**Comment by TheGamersHD** [comment]
Hes right

**Comment by TheGamersHD** [comment]
Its not working genisys just makes it for no reason

**Comment by TheGamersHD** [comment]
whats the point

**Comment by iTzAnTiFTW** [comment]
It is made for test purposes. Not every build is gonna work.

**Comment by MrPowerGamerBR** [comment]
*facepalm*

@iTzAnTiFTW is right, they make it to prepare to 0.16.0, if they don't do tests before 0.16.0 releases, they won't be able to update Genisys to 0.16.0 soon when 0.16.0 drops.

Also, @karanpatel567 and @TheGamersHD why complain about creating broken builds? Are you paying to use Genisys? Are you helping Genisys in any way or form? No? Then shut up.

**Comment by fycarman** [comment]
Actually,in 0.16 many things changed,devs have to do a massive update to the protocols. If you don't know how much work there's behind an update,please don't ask. Also,the 0.16 branch is not usable yet. Just for testing purpose.

**Comment by dktapps** [comment]
I'll tell you what YOU should read: THIS. https://github.com/iTXTech/Genisys/issues/1807

Especially the bit that says: 
# DISCLAIMER: THE 0.16 BRANCH IS NOT INTENDED FOR PUBLIC USE. Issues submitted relating to 0.16 will be treated as spam.

**Comment by dktapps** [comment]
Why don't you USE your brain (if you have one) before making stupid noise like this.

(@dktapps goes into RAGE mode)
