### ISSUE TITLE
0.15.10

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#2048]
Where can I find the 0.15.10 GENISYS phar file? I cant find it anywhere

Anyways
Thanks!

**Comment by iTzAnTiFTW** [comment]
Latest Genisys Jenkins Build: https://ci.itxtech.org/job/Genisys/lastSuccessfulBuild/

**Comment by DubaiGamerXD** [comment]
Thanks so much! Requesting lock.

**Comment by kabluinc** [comment]
@DubaiGamerXD do you have a server? I think I know you from somehwre
