### ISSUE TITLE
Cant portforward

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#2050]
Ive tried everything i can do ut on mcpe servers (were u get to register servers) it says its offline can anyone help?

**Comment by kabluinc** [comment]
Have you opened ports in your routers settings?

**Comment by DubaiGamerXD** [comment]
What does that supposed to mea

**Comment by DubaiGamerXD** [comment]
Mean

**Comment by kabluinc** [comment]
To port forward and enable people outside your network to join your server, you must have the relevant ports (e.g. 19132) open in your router. That can normally be accessed from your routers setting page. searching up port forwarding (include your router model) . 

Whats your server ip?

**Comment by DubaiGamerXD** [comment]
94.59.128.140

**Comment by DubaiGamerXD** [comment]
Thats my ip

**Comment by kabluinc** [comment]
Hmm server looks offline for me. I would suggest opening a post at pocketmine forums https://forums.pocketmine.net/  and someone should be able to help you there, as this place isn't really for questions.

Ps. I'm gamer if you still remember me xD

**Comment by dktapps** [comment]
If you continue to abuse our issue tracker you will be banned.

Review the FAQ and contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
