### ISSUE TITLE
Mobs not spawning in world. MobAI not working?

### ISSUE THREAD

**Issue by MetabolicCloth** [iTXTech/Genisys#2056]
#### Issue description
Hey, been running a MCPE Genisys server for over a month now and have been unable to get mobs to spawn/summon. When manually entered with an egg they don't move or attack, burn, or anything Mobs should be doing. 

#### Steps to reproduce the issue

Not sure if isolated issue. i just followed install instructions.

#### OS and versions

* Genisys: b6535f9
* PHP: 7.0.11
* Server OS: Win7
* Game version: v0.15.10 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files
I've included relevant configuration files.
[serverFiles.zip](https://github.com/iTXTech/Genisys/files/520657/serverFiles.zip)

**Comment by ABAxStorm** [comment]
It was removed and is going to be rewritten entirely.

**Comment by MetabolicCloth** [comment]
Thanks for the quick response, just to be clear mobs don't move, or spawn at this time?

**Comment by ABAxStorm** [comment]
@MetabolicCloth Correct.

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/wiki/FAQs
