### ISSUE TITLE
Server randomly getting killed

### ISSUE THREAD

**Issue by RandomAltThingy** [iTXTech/Genisys#206]
I have an SMP server where players are not always online (its private), after a while from disconnecting from ssh then connecting again the server will say "Killed.". I use TMUX (On Linux) so it keeps it running when I'm not connected. I can try it with screen if that would fix it.

**Comment by PeratX** [comment]
use screen?

**Comment by RandomAltThingy** [comment]
Someone said it could be put of ram

**Comment by gaoyichuan** [comment]
@PeratX He means GNU Screen

**Comment by GalvinGao** [comment]
GNU screen will not working. Sometime it will says 'Segmentation Fault'.

**Comment by gaoyichuan** [comment]
Actually, I just use nohup and control the server via RCON..

**Comment by astersx** [comment]
i use screen!!

**Comment by PEMapModder** [comment]
Most likely out of RAM. Check your processes with the `top` or `ps aux` commands.
