### ISSUE TITLE
Bad plugin load order

### ISSUE THREAD

**Issue by Tarik02** [iTXTech/Genisys#2060]
#### Issue description

Plugin load order(in `plugin.yml`):
```
load: POSTWORLD
```
or
```
load: STARTUP
```
is just plugin enable order. I'm want to use classes from plugin named `A` in plugin that named `B`. This is works. But try to use classes from plugin named `B` in plugin that named `A`, this will not work. "Plugin load order" don't changes anything.
So plugin load order is just plugin enable order.
Also, this is feature request, ability to type in `plugin.yml`, after what plugin to load this plugin.

#### Steps to reproduce the issue

Up.

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/b816e46335cf145b8eca9c1a24b18ee10e80cae3
* PHP: 7.0.9
* Server OS: Ubuntu
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by SOF3** [comment]
`load` is not a plugin load order or plugin enable _order_. It is the plugin load _stage_. It is only guaranteed that plugins of `STARTUP` will be loaded before default levels are loaded, and `POSTWORLD` after that. It should not be used to determine the order of plugin loading.

If one plugin depends on another plugin, use the `depend` attribute, or `softdepend` if not strictly dependent.

**Comment by Tarik02** [comment]
@SOF3, thanks.

**Comment by Tarik02** [comment]
`loadbefore` here is solution.
