### ISSUE TITLE
Armor not taking damage.

### ISSUE THREAD

**Issue by LordJoshie** [iTXTech/Genisys#2063]
#### Issue description

Armor Does Not Take Damage. :/ 
#### Steps to reproduce the issue

Load up & duel, check armor.
#### OS and versions

* Genisys:  b816e46
* PHP: 7.0.6
* Server OS: Ubuntu 15.10 Server
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by FaigerSYS** [comment]
Related to #1962 . Close this issue
