### ISSUE TITLE
Slapper and Plugins downloaded as folders are not working...

### ISSUE THREAD

**Issue by LargeArt7338551** [iTXTech/Genisys#2064]
I really want slapper... So if you can help me with this that would be great.

**Comment by LargeArt7338551** [comment]
My folder is originally pocketmine mp, but I downloaded the genisys 0.15.4 Phar and It runs just fine.

**Comment by LargeArt7338551** [comment]
But when I try to download A plugin that is In a folder, it does not work... Could anyone help me?

**Comment by iTzAnTiFTW** [comment]
Please do not comment this here! This is for Genisys issues, not plugins issues. If your having issues installing it please use the pocketmine fourms or something else.

**Comment by kabluinc** [comment]
loading plugins in folder format was removed from Genisys. Use devtools

**Comment by dktapps** [comment]
Read the FAQs in the wiki before opening an issue.
