### ISSUE TITLE
Server crashes always!!

### ISSUE THREAD

**Issue by poustmal** [iTXTech/Genisys#2065]
Hello.I have a server,but it always crashes every 2-6 hours.I don't understand the reason.First crash is from ZMusicBox plugin:Genisys Crash Dump Wed Oct 12 00:48:18 EEST 2016

Error: yaml_parse(): parsing error encountered during parsing: did not find expected key (line 4, column 15), context while parsing a block mapping (line 4, column 4)
File: /src/pocketmine/utils/Config
Line: 142
Type: E_WARNING

Code:
[133] 					case Config::PROPERTIES:
[134] 					case Config::CNF:
[135] 						$this->parseProperties($content);
[136] 						break;
[137] 					case Config::JSON:
[138] 						$this->config = json_decode($content, true);
[139] 						break;
[140] 					case Config::YAML:
[141] 						$content = self::fixYAMLIndexes($content);
[142] 						$this->config = yaml_parse($content);
[143] 						break;
[144] 					case Config::SERIALIZED:
[145] 						$this->config = unserialize($content);
[146] 						break;
[147] 					case Config::ENUM:
[148] 						$this->parseList($content);
[149] 						break;
[150] 					default:
[151] 						$this->correct = false;
[152] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 84; API 2.0.0]
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Tue Dec 3 15:37:57 CST 2013 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 22 minutes 23 seconds
Number of loaded worlds: 5
Players online: 2/25

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FChestReset 1.0.0(English) by FENGberd for API(s) 1.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.0.0, 2.0.0
WorldGM 1.0.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
PmChair 1.1 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SW_svile 0.6dev by svile for API(s) 1.13.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 2.0.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
xyz 1.0.1 by unerds for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
SpawnWithItems 2.1 by LDX for API(s) 1.1.0, 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
PurePerms 1.3.7-patch1 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
ZMusicBox 2.5.0 by Zzm for API(s) 1.0.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SkyBlock 1.5.6 by  for API(s) 1.12.0
ChatBot 1.0.0 by applqpak for API(s) 1.0.0, 2.0.0

**Comment by poustmal** [comment]
The second crash is:Genisys Crash Dump Tue Oct 11 23:35:45 EEST 2016

Error: mkdir(): File exists
File: /plugin-866.phar/src/ServerKits/Main
Line: 71
Type: E_WARNING

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : ServerKits v1.3

Code:
[62] 		$message = str_replace($symbol."m", TextFormat::STRIKETHROUGH, $message);
[63] 		$message = str_replace($symbol."n", TextFormat::UNDERLINE, $message);
[64] 		$message = str_replace($symbol."o", TextFormat::ITALIC, $message);
[65] 		$message = str_replace($symbol."r", TextFormat::RESET, $message);
[66] 	
[67] 		return $message;
[68] 	}
[69] 	
[70] 	public function registerFirstJoin(Player $player){
[71] 		@mkdir($this->getDataFolder() . "data/");
[72] 		$tmp = new Config($this->getDataFolder() . "data/" . strtolower($player->getName() . ".dat"));
[73] 		$tmp->save();
[74] 	}
[75] 	
[76] 	public function hasJoinedFirstTime(Player $player){
[77] 		if(file_exists($this->getDataFolder() . "data/" . strtolower($player->getName() . ".dat"))){
[78] 			return false;
[79] 		}else{
[80] 			return true;
[81] 		}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 84; API 2.0.0]
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Tue Dec 3 15:37:57 CST 2013 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 4 hours 24 minutes 24 seconds
Number of loaded worlds: 5
Players online: 0/25

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FChestReset 1.0.0(English) by FENGberd for API(s) 1.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.0.0, 2.0.0
WorldGM 1.0.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
PmChair 1.1 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SW_svile 0.6dev by svile for API(s) 1.13.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 2.0.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
xyz 1.0.1 by unerds for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
SpawnWithItems 2.1 by LDX for API(s) 1.1.0, 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
PurePerms 1.3.7-patch1 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
ZMusicBox 2.5.0 by Zzm for API(s) 1.0.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SkyBlock 1.5.6 by  for API(s) 1.12.0
ChatBot 1.0.0 by applqpak for API(s) 1.0.0, 2.0.0

**Comment by dktapps** [comment]
Your config format is invalid.

**Comment by poustmal** [comment]
And the third crash that I have usually is:Genisys Crash Dump Tue Oct 11 14:24:46 EEST 2016

Error: time_sleep_until(): Sleep until to time is less than current time
File: /src/pocketmine/Server
Line: 2547
Type: E_WARNING

Code:
[2538] 		return [];
[2539] 	}
[2540] 
[2541] 	private function tickProcessor(){
[2542] 		$this->nextTick = microtime(true);
[2543] 		while($this->isRunning){
[2544] 			$this->tick();
[2545] 			$next = $this->nextTick - 0.0001;
[2546] 			if($next > microtime(true)){
[2547] 				@time_sleep_until($next);
[2548] 			}
[2549] 		}
[2550] 	}
[2551] 
[2552] 	public function onPlayerLogin(Player $player){
[2553] 		if($this->sendUsageTicker > 0){
[2554] 			$this->uniquePlayers[$player->getRawUniqueId()] = $player->getRawUniqueId();
[2555] 		}
[2556] 
[2557] 		$this->sendFullPlayerListData($player);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 84; API 2.0.0]
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Tue Dec 3 15:37:57 CST 2013 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 40 minutes 19 seconds
Number of loaded worlds: 6
Players online: 1/25

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FChestReset 1.0.0(English) by FENGberd for API(s) 1.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.0.0, 2.0.0
WorldGM 1.0.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
PmChair 1.1 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SW_svile 0.6dev by svile for API(s) 1.13.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 2.0.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
xyz 1.0.1 by unerds for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
SpawnWithItems 2.1 by LDX for API(s) 1.1.0, 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
PurePerms 1.3.7-patch1 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
ZMusicBox 2.5.0 by Zzm for API(s) 1.0.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SkyBlock 1.5.6 by  for API(s) 1.12.0
ChatBot 1.0.0 by applqpak for API(s) 1.0.0, 2.0.0
