### ISSUE TITLE
Bug of the map PC to PE

### ISSUE THREAD

**Issue by LewBr** [iTXTech/Genisys#2066]
#### Issue description
Join to the PC World

#### Steps to reproduce the issue
Fix this problem whit the no compatible blocks in McPE, changing the ID's!!

#### OS and versions
* Genisys: This server is running Genisys (codename "Kyrios")
* PHP: PHP version: 7.0.11
* Server OS: API: 2.0.0 (iTX API version 1.9.3)
* Game version: Target client: Minecraft PE v0.15.10 alpha (protocol version 84)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
When i try to join at my server whit the map of PC then crashes my client, its possible to fix this?
```

**Comment by RocoWayne** [comment]
im having the same problems in some maps, but i remove all the no compatible blocks and still crashes :/

**Comment by dktapps** [comment]
It's unrealistic and would potentially have a large performance impact. This is a client bug, it's up to Mojang to fix it.

**Comment by dktapps** [comment]
Update on that: this bug has been fixed in the 0.16.0 beta, please wait for release.

**Comment by MrPowerGamerBR** [comment]
@dktapps so Mojang made that unknown blocks doesn't crash the client in 0.16.0?

**Comment by JUSTaMod** [comment]
Or did they make the unknown blocks known? hrmmmm. What a conundrum.

**Comment by dktapps** [comment]
@JUSTaMod no, I tested it myself. They now show as update! blocks as they did before the 0.16 update. Try blockID 210 for example.
