### ISSUE TITLE
Armor not damaging

### ISSUE THREAD

**Issue by Gianluxx** [iTXTech/Genisys#2067]
#### Issue description
When i do PvP my armor doesn't take damage. Always full repaired.

#### Steps to reproduce the issue
 Go in pvp and take damage

#### OS and versions

* Genisys: b816e463
* PHP: 7.0.10
* Server OS: linux server 16.4
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
#1962
