### ISSUE TITLE
Player doesn't drop items on death

### ISSUE THREAD

**Issue by poustmal** [iTXTech/Genisys#2068]
When a player dies,he/she doesn't drop the items that was having.On mcpe real map(not server),when a player dies,always drops items.

**Comment by poustmal** [comment]
Please fix this problem,players can't play a normal survival in my server.

**Comment by Gianluxx** [comment]
Check if keep-inventory in genisys.yml is false

**Comment by poustmal** [comment]
Ok.I will try this.

**Comment by poustmal** [comment]
It didn't work.

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by poustmal** [comment]
Genisys version: 6cb5529 [Protocol 84; API 2.0.0]
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Tue Dec 3 15:37:57 CST 2013 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android
