### ISSUE TITLE
request / question: colored signs

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Genisys#207]
Sorry, I know you have enough work with other more important things.
But maybe you can solve my problem - it wasn't possible for me to create signs with colored / formated text as a non-OP. I also didn't find a permission for that or any hint in the pocketmine source. When only OPs can create signs with colored text I have to give helping people (Builder) OP permission?
It would be nice if I could use a PurePerms permission to control this. Any idea:question:

**Comment by PeratX** [comment]
in 0.14?

**Comment by xpyctum** [comment]
and in 0.13

**Comment by PeratX** [comment]
got it. It is Player::setRemoveFormat(false)

**Comment by SleepSpace9** [comment]
Wow - found and fixed so quickly! Thank you so much, my son is happy about it! :thumbsup:
