### ISSUE TITLE
Server bug, server full

### ISSUE THREAD

**Issue by LittleLai5** [iTXTech/Genisys#2071]
#### Issue description
<When the server start. I try to joining. But it always said Server full. I promise there's no people and the slot is 1000.

#### OS Version
-->
Genisys: 498379b
PHP: 7.3
Server OS: Android
Game version: MCPE 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Your version is outdated. This will be closed until you ensure it is reproducible on the current version.
