### ISSUE TITLE
Hunger system and mobs setup

### ISSUE THREAD

**Issue by rivermigue** [iTXTech/Genisys#2072]
#### Issue description
It seems that the hunger system works only when you take damage to increase health, however when you have lost one bar in the hunger hud and your helth is low none of them are recovering or decreasing, is this sopose to be like this? Also mobs are not spawning even tho the settings within pocketmine.yml has enabled it, are mobs still not supported?

#### Steps to reproduce the issue
Try to take damage on survival mode

#### OS and versions

* Genisys: #4587807  master  064965e7
* PHP: 7
* Server OS: CentOS 6.5
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files
No crash dumps, just in-game issues.

**Comment by TheAppleGamer** [comment]
The hunger thing is just legit vanilla, and they removed AI
