### ISSUE TITLE
New Here.  Redstone and redstone powered items question.

### ISSUE THREAD

**Issue by KalonaHone** [iTXTech/Genisys#2077]
okay well i just joined github and posted in the wrong section i appologize please dont ban.

im usings win 7, 

im curious as to know why i cannt use redstone or redstone powered items?  i can place redstone but when i connect it to pressure plates or switches etc no power happens, like the circuit doesnt quite work.    

are redstone and redstone powered items not implementaed yet?

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by KalonaHone** [comment]
okay cool thank you..

**Comment by KalonaHone** [comment]
Well I turned it from false to true. But Redstone's still don't seem to work. Switches don't power. And I can use sticky pistons. They still dissapear

**Comment by ishitatsuyuki** [comment]
No questions here. Did you wanted a ban instead?

**Comment by dktapps** [comment]
Please review the FAQs and contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
