### ISSUE TITLE
Config::setDefaults() error

### ISSUE THREAD

**Issue by KairusDarkSeeker** [iTXTech/Genisys#2079]
#### Issue description
I was recently testing a plugin when suddenly this error appeared, I have no idea why.

#### OS and versions

* Genisys: 064965e
* PHP: 7.0.3
* Server OS: Android
* Game version: 0.15.10 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files

![img_20161014_211216_036](https://cloud.githubusercontent.com/assets/13493402/19388773/df36dfbe-9253-11e6-96f9-62922460207e.JPG)

**Comment by ImagicalGamer** [comment]
It says that you were passing a boolean, setDefaults requires an array.

**Comment by KairusDarkSeeker** [comment]
@ImagicalGamer are you dumb? The contents on my config are arrays

**Comment by KairusDarkSeeker** [comment]
@ImagicalGamer I already know that the contents of the config must be an instance of Array
