### ISSUE TITLE
What is going wrong ?

### ISSUE THREAD

**Issue by jerryzooyoyo** [iTXTech/Genisys#208]
[Asynchronous Worker #2 thread/CRITICAL]: Error: "Class name must be a valid object or a string" (EXCEPTION) in "/src/pocketmine/level/generator/GeneratorRegisterTask" at line 54

Notice: Undefined index: generation.level.generator in C:\PocketMine-MP\src\pocketmine\scheduler\AsyncTask.php on line 129

As you saw, the world generation DOES have a little bug.

**Comment by flaxues** [comment]
This may be cause by a plugin...

**Comment by Efforto** [comment]
i think this may caused by a plugin, not the WorldGeneratior

**Comment by flaxues** [comment]
Jerry could you post you're plugins here?

**Comment by jerryzooyoyo** [comment]
AlwaysSpawn v2.2.2, 
BetterGenerators v0.8.1, 
BlockEffects v1.0.5, 
BouncyBlocks v1.1, 
DontTapTheWhiteTile v0.1.2, 
EconomyAPI v2.0.9, 
EconomySell v2.0.7, 
EconomyShop v2.0.7, 
Marriage v2.0.0, 
PocketVIP v1.1.1, 
xRulesx v1.0.0, 
ABMiniGame v1.0.1, 
AntiSpammer v1.1, 
AshMan v1.0.1, 
BanCommands v1.0.0, 
Broadcaster v1.16, 
ChatCheck v1.0.0, 
CustomAlerts v1.6, 
DelayDetection v2.0.1, 
DelNull v1.0.1, 
EconomyJob v2.0.4, 
EconomyTax v2.0.3, 
EntityManager v3.0 Beta, 
essentialsTP v1.1.0, 
FNPC v1.1.5, 
GeoIP v1.0.0, 
Ginvitation v2.3.3, 
Grade v1.0.4, 
Holiday v1.1, 
InstantRespawn v0.3.1, 
ItemCasePE v1.0.8, 
KillMarker_Jaciel v0.1-Alpha, 
KSpleef v1.3.0, 
KTNTRun v1.3.0, 
MagicTelePortal v1.3.2, 
ManyWorlds v2.0.3, 
NoAdvertisingPE v1.0.0, 
oplist v0.0.1, 
Protection v1.8.0, 
RestartMe v1.3.0, 
Rjoinmoney v2.0.0, 
ServerMail v0.0.2, 
SignStatus v3.0.0, 
TAGBlock v0.8-Alpha, 
TapToDo v2.2.1, 
TicTacToe v1.0.0, 
TimerBan v2.1, 
UnCrafting v1.1.3, 
WorldProtect v2.2.0, 
ZKit v1.0.0, 
MyPlot v1

That's all plugins I use.

**Comment by PocketKiller** [comment]
BetterGenerators.

**Comment by jerryzooyoyo** [comment]
Got it. I will try.

**Comment by jerryzooyoyo** [comment]
Thanks a lot. It have been fixed. The issue can be closed.
