### ISSUE TITLE
Servers having vulnerability on Toolbox for Minecraft: PE

### ISSUE THREAD

**Issue by KairusDarkSeeker** [iTXTech/Genisys#2083]
#### Issue description
A hacker just recently reported to me that they're able to get unlimited items from toolbox on my server @EvolvedNetwork.

#### Steps to reproduce the issue
Just use Toolbox for Minecraft: PE and hack items on a server that's using Genisys.However, I'm not pretty sure if this works on "every" servers that is using Genisys.

#### OS and versions

* Genisys: 064965e
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: 0.15.10 alpha

#### Crashdump, backtrace, memory dumps, plugins list or other files

![img_20161015_202759](https://cloud.githubusercontent.com/assets/13493402/19410205/80379164-9318-11e6-9f9b-baec9cb36779.png)

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by KairusDarkSeeker** [comment]
There

**Comment by jjplaying** [comment]
It's just one of those hacker issues. Hacking items has always been not possible, because the server checks it. Maybe you should check if you gave somebody OP, and he gave another one OP, or you have a buggy plugin or a gamemode change from creative to survival without cleaning the inventory, whatever. You should try it on a fresh Genisys install without any plugins. And as I can see, the screenshots are just showing an inventory. It can simply be on another server.

**Comment by ABAxStorm** [comment]
Go in your genisys.yml, and find this & set it to false. Here's an example:

`inventory:
 #Set this to true if you have problems with anvils. Will process inventory transactions in a vanilla fashion with no anti-cheats or verification.

allow-cheats: false
`

**Comment by KairusDarkSeeker** [comment]
mk

**Comment by isoz** [comment]
It's set to false by default and they still are able to get it, its been like this for a while.
