### ISSUE TITLE
Server crashing (invalid human skin)

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#2084]
So when I put my server online..
When a player joins the server crashes heres the report

Genisys Crash Dump Fri Oct 14 11:47:03 UTC 2016

Error: Human must have a valid skin set
File: /src/pocketmine/entity/Human
Line: 642
Type: notice

Code:
[633] 		$this->namedtag->foodSaturationLevel = new FloatTag("foodSaturationLevel", $this->getSaturation());
[634] 		$this->namedtag->foodTickTimer = new IntTag("foodTickTimer", $this->foodTickTimer);
[635] 	}
[636] 
[637] 	public function spawnTo(Player $player){
[638] 		if($player !== $this and !isset($this->hasSpawned[$player->getLoaderId()])){
[639] 			$this->hasSpawned[$player->getLoaderId()] = $player;
[640] 
[641] 			if(strlen($this->skin) < 64 * 32 * 4){
[642] 				throw new \InvalidStateException((new \ReflectionClass($this))->getShortName() . " must have a valid skin set");
[643] 			}
[644] 
[645] 			if(!($this instanceof Player)){
[646] 				$this->server->updatePlayerListData($this->getUniqueId(), $this->getId(), $this->getName(), $this->skinId, $this->skin, [$player]);
[647] 			}
[648] 
[649] 			$pk = new AddPlayerPacket();
[650] 			$pk->uuid = $this->getUniqueId();
[651] 			$pk->username = $this->getName();
[652] 			$pk->eid = $this->getId();

Backtrace:
#0 /src/pocketmine/level/Level(2614): pocketmine\Player->sendChunk(integer 6, integer 0, pocketmine\network\protocol\BatchPacket object)
#1 /src/pocketmine/level/Level(2657): pocketmine\level\Level->sendChunkFromCache(integer 6, integer 0)
#2 /src/pocketmine/level/format/anvil/ChunkRequestTask(87): pocketmine\level\Level->chunkRequestCallback(integer 6, integer 0, string ........Y.............................................................................................................................................................................................................................................................................99.99............9.9..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................I................................................................................I.............................................................................................................................................................II..............II...............................................................................................I..............................................................................................................................................I...................................................................................................................................................................................................................................................8...........................................................................................................................................................................................................II..............II..................8..............8...............................................................................................................................................................................................................................................88..............8...............................................................................................................................................................................................................................................8................................................................................................I..............................................I...............II................................................................................................................................................................................................................................................................................................................I...............I...............II..........................................................................................................................................................................................................................I...I...........I...I...............II..........................................................................................................................................................................................................................I...............I...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................I...............................................................................................................................................................................................................................................II..............II..............................................................................................................................................................................................II...............I...............................I..............................................................................................................................................................................................................................II..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by DubaiGamerXD** [comment]
Problem fixed. Some guy had an invalid skin

**Comment by DubaiGamerXD** [comment]
Ok this is again happenig to players!,
I seriously need help!

**Comment by iTzAnTiFTW** [comment]
What Genisys Version Is It?

**Comment by DubaiGamerXD** [comment]
3ca6654

**Comment by jjplaying** [comment]
Client details like MCPE version would be helpful.

**Comment by DubaiGamerXD** [comment]
What do you mean?

**Comment by DubaiGamerXD** [comment]
Oh its on 0.15.10

**Comment by jjplaying** [comment]
The version of MCPE.

**Comment by jjplaying** [comment]
Sounds strange to me, and I can't reproduce it. I think this doesn't happens with a normal MCPE client. Maybe someone is intentionally crashing your server or it's related to a Slapper-like plugin. Does it also happens on a clean Genisys instance without plugins?

**Comment by DubaiGamerXD** [comment]
Uhm this is more information its like the player's name...
When that player changes the name it works bur it EFFECTS on other players.

**Comment by DubaiGamerXD** [comment]
So this issue needs maybe an Investigation. Its unknown and like.. idk

**Comment by iTzAnTiFTW** [comment]
Are people joining on earlier clients, like 0.15.9?

**Comment by MCPEGamerJPatGitHub** [comment]
Use SkinTools

**Comment by DubaiGamerXD** [comment]
Ok I will use skintools can anyone give me a link
