### ISSUE TITLE
Invisible block make some lags / LevelChange too 

### ISSUE THREAD

**Issue by Misteboss** [iTXTech/Genisys#2089]
#### Issue description

When a player change of level there is lag (freeze) and when the  invisible block (95) is at proximity of a player it creates some lags too.
Do you know how can i resolve the problem (maybe i can load chunk before TP)
#### OS and versions
OS and versions

Genisys: 064965e
PHP: 7.0.3
Server OS: Ubuntu
Game version: 0.15.10 alpha

**Comment by dktapps** [comment]
Duplicate of #1889
