### ISSUE TITLE
Couldn't open Genisys on Windows.

### ISSUE THREAD

**Issue by jerryzooyoyo** [iTXTech/Genisys#209]
_Failed to fork child process: Resource temporarily unavailable.
DLL rebasing may be required. See 'rebaseall --help'._

Well, before I wrote this issue, the server was just FINE.
But after I use the command " /stop " in-game, and restart it again, my server is just showing this.
I tried to reset my server ( delete all my server folders and data, download it in the PocketMine-MP's official downloading link, and copy Genisys into the folder.).
No plugin, no players, no map.
I couldn't open PM, even the setup messages are not showing.( just can't open )
But the mintty.exe is running, showing this message.
Could you help me? Or should I do something else?

**Comment by PeratX** [comment]
Simple to solve.Just follow my steps. This is a bug of PHP.
1.stop ALL PHP process in your computer.
2.Delete temp file generated by PHP. Usually in C:/Users/Username/AppData/Local/Temp
3.Restart your program

**Comment by jerryzooyoyo** [comment]
Thanks a lot, it WORKS !!!!!!!!!
