### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#2090]
Server crashes after the invalid human skin problem i downloaded skin tools now sgain

Genisys Crash Dump Sun Oct 16 16:38:36 UTC 2016

Error: Human must have a valid skin set
File: /src/pocketmine/entity/Human
Line: 642
Type: notice

Code:
[633] 		$this->namedtag->foodSaturationLevel = new FloatTag("foodSaturationLevel", $this->getSaturation());
[634] 		$this->namedtag->foodTickTimer = new IntTag("foodTickTimer", $this->foodTickTimer);
[635] 	}
[636] 
[637] 	public function spawnTo(Player $player){
[638] 		if($player !== $this and !isset($this->hasSpawned[$player->getLoaderId()])){
[639] 			$this->hasSpawned[$player->getLoaderId()] = $player;
[640] 
[641] 			if(strlen($this->skin) < 64 * 32 * 4){
[642] 				throw new \InvalidStateException((new \ReflectionClass($this))->getShortName() . " must have a valid skin set");
[643] 			}
[644] 
[645] 			if(!($this instanceof Player)){
[646] 				$this->server->updatePlayerListData($this->getUniqueId(), $this->getId(), $this->getName(), $this->skinId, $this->skin, [$player]);
[647] 			}
[648] 
[649] 			$pk = new AddPlayerPacket();
[650] 			$pk->uuid = $this->getUniqueId();
[651] 			$pk->username = $this->getName();
[652] 			$pk->eid = $this->getId();

Backtrace:
#0 /src/pocketmine/level/format/generic/BaseFullChunk(149): pocketmine\entity\Entity->spawnToAll(boolean)
#1 /src/pocketmine/level/Level(2789): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#2 /src/pocketmine/level/Level(696): pocketmine\level\Level->loadChunk(integer 6, integer 0)
#3 /src/pocketmine/Player(923): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(10), integer 6, integer 0, boolean 1)
#4 /src/pocketmine/Player(1961): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2852): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2544): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2422): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(2012): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/, string unknown)
#10 (1): require_once(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 84; API 2.0.0]
uname -a: Linux localhost 3.10.49-7686342 #1 SMP PREEMPT Wed Apr 6 17:20:26 KST 2016 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 7 minutes 4 seconds
Number of loaded worlds: 2
Players online: 2/25

Loaded plugins:
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
DropParty 1.0.3 by HotshotHD for API(s) 1.12.0, 1.13.0
GodMode 2.4 by LDX for API(s) 1.0.0, 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
MassiveEconomy 1.0 R3 by EvolSoft for API(s) 1.9.0
MassiveEconomyExample 1 by EvolSoft for API(s) 1.4.0
iManager 1.1.0 by Gamecrafter for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
Afk 0.3 by hoyinm14mc for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
KillHeart 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
JoinCommands 1.4.1 by PixelGuy75 for API(s) 1.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
Nick 1.0.1 by AryToNeX for API(s) 1.12.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
ReasonWL 2 by CreeperFace for API(s) 1.12.0
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
SkinTools 1.1.0 by Gamecrafter for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0

**Comment by DubaiGamerXD** [comment]
What should I do?, any suggestions?

**Comment by kabluinc** [comment]
Could it be because of the skintools plugin you have installed? Try starting the server without it and see if it still crashes

**Comment by DubaiGamerXD** [comment]
Uhm, ok

**Comment by DubaiGamerXD** [comment]
I downaloded it DIRECTLY from the pocketmine app

**Comment by dktapps** [comment]
You have an invalid human entity in your world. You will need to remove it.

**Comment by DubaiGamerXD** [comment]
How will I remove it?

**Comment by dktapps** [comment]
MCEdit ought to do the job.

**Comment by DubaiGamerXD** [comment]
Uhm, is it a plugin?

**Comment by dktapps** [comment]
https://github.com/Khroki/MCEdit-Unified

**Comment by DubaiGamerXD** [comment]
Tysm!

**Comment by DubaiGamerXD** [comment]
Its a bug? So never will be fixed?

**Comment by DubaiGamerXD** [comment]
The server is again crashing :(

**Comment by dktapps** [comment]
Fixed in https://github.com/iTXTech/Genisys/commit/6cb55298a3f2cb635af38315636936d34e612539
