### ISSUE TITLE
Genisys - CMD Crashes

### ISSUE THREAD

**Issue by SirGamer** [iTXTech/Genisys#2091]
The Genisys Server CMD prompt closes on load.
I am new here, I need help. Also, I cannot use the automatic installer, it says "NOT FOUND" when installing or something like that.

**Comment by TheAppleGamer** [comment]
Do you have the bin folder?

**Comment by XShockinFireX** [comment]
Please follow the issue template.

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

Being newbie is not a reason to spam, and you will be banned next time you annoy us.

**Comment by SirGamer** [comment]
Shut up, you annoy me. 👍

**Comment by ishitatsuyuki** [comment]
Okay, say that again, now you are banned.
