### ISSUE TITLE
Items not appearing in inventory

### ISSUE THREAD

**Issue by BudderSticks** [iTXTech/Genisys#2092]
I have found a glitch in my Genisys server. When you do /give, or get a kit or whenever items are supposed to appear in your inventory they don't. The only way they appear is when you tap the ground with a open slot where the item is supposed to be. Items also drop when you die.

I know there has already been a issue on this but I have read through it and it did not help me at all.

Thank you!

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
