### ISSUE TITLE
Server crashing #AGAIN

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#2097]
Genisys Crash Dump Tue Oct 18 11:54:25 UTC 2016

Error: Human must have a valid skin set
File: /src/pocketmine/entity/Human
Line: 643
Type: notice

Code:
[634] 		$this->namedtag->foodTickTimer = new IntTag("foodTickTimer", $this->foodTickTimer);
[635] 	}
[636] 
[637] 	public function spawnTo(Player $player){
[638] 		if($player !== $this and !isset($this->hasSpawned[$player->getLoaderId()])){
[639] 			$this->hasSpawned[$player->getLoaderId()] = $player;
[640] 
[641] 			if(strlen($this->skin) < 64 * 32 * 4){
[642] 				$this->close();
[643] 				throw new \InvalidStateException((new \ReflectionClass($this))->getShortName() . " must have a valid skin set");
[644] 			}
[645] 
[646] 			if(!($this instanceof Player)){
[647] 				$this->server->updatePlayerListData($this->getUniqueId(), $this->getId(), $this->getName(), $this->skinId, $this->skin, [$player]);
[648] 			}
[649] 
[650] 			$pk = new AddPlayerPacket();
[651] 			$pk->uuid = $this->getUniqueId();
[652] 			$pk->username = $this->getName();
[653] 			$pk->eid = $this->getId();

Backtrace:
#0 /src/pocketmine/level/format/generic/BaseFullChunk(149): pocketmine\entity\Entity->spawnToAll(boolean)
#1 /src/pocketmine/level/Level(2789): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#2 /src/pocketmine/level/Level(696): pocketmine\level\Level->loadChunk(integer 6, integer 0)
#3 /src/pocketmine/Player(923): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(4), integer 6, integer 0, boolean 1)
#4 /src/pocketmine/Player(1961): pocketmine\Player->sendNextChunk(boolean)
#5 /src/pocketmine/Server(2852): pocketmine\Player->checkNetwork(boolean)
#6 /src/pocketmine/Server(2544): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2422): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(2012): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/, string unknown)
#10 (1): require_once(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 84; API 2.0.0]
uname -a: Linux localhost 3.10.49-7686342 #1 SMP PREEMPT Wed Apr 6 17:20:26 KST 2016 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 2 minutes 11 seconds
Number of loaded worlds: 2
Players online: 3/10

Loaded plugins:
iManager 1.1.0 by Gamecrafter for API(s) 1.10.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
MassiveEconomy 1.0 R3 by EvolSoft for API(s) 1.9.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
Afk 0.3 by hoyinm14mc for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
MassiveEconomyExample 1 by EvolSoft for API(s) 1.4.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
WarpSigns 0.0.1 by Falkirks for API(s) 1.12.0

**Comment by dktapps** [comment]
Update your server.

**Comment by DubaiGamerXD** [comment]
The latest build dosent work i really need help.
