### ISSUE TITLE
authentication failed (auth empty response)

### ISSUE THREAD

**Issue by MarceloJr21** [iTXTech/Genisys#2098]
Genisys Crash Dump Mon Oct 17 18:00:12 EDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 86016 bytes)
File: /src/pocketmine/utils/BinaryStream
Line: 64
Type: E_ERROR

Code:
[55] 			$this->offset = strlen($this->buffer) - 1;
[56] 			return "";
[57] 		}elseif($len === true){
[58] 			return substr($this->buffer, $this->offset);
[59] 		}
[60] 		return $len === 1 ? $this->buffer{$this->offset++} : substr($this->buffer, ($this->offset += $len) - $len, $len);
[61] 	}
[62] 
[63] 	public function put($str){
[64] 		$this->buffer .= $str;
[65] 	}
[66] 
[67] 	public function getLong(){
[68] 		return Binary::readLong($this->get(8));
[69] 	}
[70] 
[71] 	public function putLong($v){
[72] 		$this->buffer .= Binary::writeLong($v);
[73] 	}
[74] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

**Comment by dktapps** [comment]
Not enough information. Please provide details.

**Comment by MarceloJr21** [comment]
It only appears that as an error I can not move on the panel as soon appears this error if I try to move "authentication failed (auth empty response)"

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by MarceloJr21** [comment]
Genisys Crash Dump Mon Oct 17 18:00:12 EDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 86016 bytes)
File: /src/pocketmine/utils/BinaryStream
Line: 64
Type: E_ERROR

Code:
[55] 			$this->offset = strlen($this->buffer) - 1;
[56] 			return "";
[57] 		}elseif($len === true){
[58] 			return substr($this->buffer, $this->offset);
[59] 		}
[60] 		return $len === 1 ? $this->buffer{$this->offset++} : substr($this->buffer, ($this->offset += $len) - $len, $len);
[61] 	}
[62] 
[63] 	public function put($str){
[64] 		$this->buffer .= $str;
[65] 	}
[66] 
[67] 	public function getLong(){
[68] 		return Binary::readLong($this->get(8));
[69] 	}
[70] 
[71] 	public function putLong($v){
[72] 		$this->buffer .= Binary::writeLong($v);
[73] 	}
[74] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: b816e46335cf145b8eca9c1a24b18ee10e80cae3 [Protocol 84; API 2.0.0]
uname -a: Linux s6.craftandohosting.net 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP version: 7.0.10
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 4 hours 14 minutes 4 seconds
Number of loaded worlds: 3
Players online: 77/10

Loaded plugins:
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
MSpawns 1.5 by EvolSoft for API(s) 1.11.0, 2.0.0
OreInstantDrop 1.0 alpha by Polina_White for API(s) 1.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
itemID_DoDo 1.1.0 by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
ObsidianBreaker 1 by  for API(s) 1.13.1, 2.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
Staff 2.0.2 by LazzKiller Modificado por Megaplay adr for API(s) 2.0.0, 1.13.0, 1.12.0
DropParty 1.0.3 by HotshotHD for API(s) 1.12.0, 1.13.0
UnlimitedSlots 1.0.0 by Gumbrat-And-TheDeibo for API(s) 1.14.0
Rank 1 by iPeedro for API(s) 2.0.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
aTopPlayers 1 by AlexBrin for API(s) 2.0.0
ParticlesPlus 0.0.2 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
SAutoMine Alpha_0.1 by Sergey_Dertan for API(s) 1.8.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
VIPSlots 0.0.3 by iJoshuaHD for API(s) 1.8.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
EnderPearls 1.0.0 by XFuryMCPE for API(s) 1.12.0, 2.0.0
punir 1.0 by LazzKiller for API(s) 2.0.0, 1.13.0, 1.12.0
FactionsPro 1.4 by Tethered_ for API(s) 1.12.0, 2.0.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
SClearLagg Beta_0.2 by Sergey_Dertan for API(s) 1.8.0
Sparklers 0.1-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
Nicknames 1.0.0 by Kairus Dark Seeker for API(s) 1.13.0, 2.0.0
Anti-Xray 0.8 by DanielYTK for API(s) 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
DropMobSpawner 1.0 by ScandiePla for API(s) 1.12.0
WorldEdit+ 0.01 by  for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
Jail Pre-alpha0.4 by hoyinm14mc for API(s) 2.0.0
CommandBlocker 1.5.5 by Thunder33345 for API(s) 2.0.0
WarFly 1.0 by TheoBR™ for API(s) 1.0.0
KillChat 1.0.2.MOD by Array for API(s) 1.9.0, 2.0.0
BasicHUD 1.0.6 by aliuly for API(s) 2.0.0
GlobalBan 1.4 by LazzKiller for API(s) 2.0.0
AdvancedKits 5.0b1 by luca28pet for API(s) 2.0.0
aFloatingText 1.2 by AlexBrin for API(s) 1.10.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
AntiCheat 1.3.1 by DarkWav (Darku) for API(s) 2.0.0, 1.14.0, 1.13.2
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
Denuncia 1.0 by LazzKiller for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0, 1.13.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0

**Comment by MarceloJr21** [comment]
That's enough? Will you be able to solve?

**Comment by ishitatsuyuki** [comment]
Your memory limit is insufficient.
