### ISSUE TITLE
Question: can i use it (genisys) on android?

### ISSUE THREAD

**Issue by MasterWolf** [iTXTech/Genisys#210]

**Comment by PocketKiller** [comment]
How to : 
- download the .zip
- install DevTools by PocketMine Team
- unzip the zip
- restart your PocketMine server
- drag the unzipped .zip at /plugins/DevTools
- go to the console and type /makeserver then wait
- copy the .phar on /plugins/DevTools/PocketMine-dev.phar
- paste it on the main server folder
- delete PocketMine-MP.phar
- rename PocketMine-dev.phar to PocketMine-MP.phar
- kill (not restart) your server
- start the server.

**Comment by PeratX** [comment]
No need to use DevTools.
Just Download Zip->Unpack->Start server->Enter /ms command and wait

**Comment by MasterWolf** [comment]
Oh, thanks! But i dont understand why i must kill server! Will it delete all my server settings and data?

**Comment by PocketKiller** [comment]
no, just forcly stops it, because if you stop it normally it will give you many errors.

**Comment by MasterWolf** [comment]
Ooooh! Thanks, i was very scared... Now im normal! I just heard that ImagicalMine will not developing for android anymore and i think that i will use genisys from now. Is it true that php 7 is incomplatible with android?
