### ISSUE TITLE
Server gets stuck after "Server was stopped"

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#2100]
#### Issue description

Server often gets stuck for a few seconds after the message display "Server was stopped". It's really annoying, I need to constantly press CTRL+Z

#### Steps to reproduce the issue

Just stop the server
#### OS and versions

* Genisys: ce1fd04
* PHP: 7.0.6
* Server OS: Linux Mint 17.3 x64
* Game version: 0.15.10

**Comment by ishitatsuyuki** [comment]
A few seconds? At most it could hang for <1 sec.

**Comment by alex2534alex** [comment]
Nope. I have to wait an average of 5-10 seconds. I think it's because of
ServerKiller

19 окт. 2016 г. 10:39 пользователь "Tatsuyuki Ishi" <
notifications@github.com> написал:

**Comment by DaMatrix** [comment]
only happens for me on some computers, not on others. it can hang for up to a minute on my pi, debug doesn't show anything.

**Comment by Leo3418** [comment]
I've seen this, espeially when the server occupied lots of memory before stopped. Is the system releasing memory?

**Comment by Muqsit** [comment]
Type Ctrl + C in the console when it happens.

**Comment by alex2534alex** [comment]
Muqsit , I wrote about this above, and it does not fix the bug

**Comment by Muqsit** [comment]
Update PHP to 7.0.12 and try?

**Comment by alex2534alex** [comment]
@Muqsit , I can't because of [this issue](https://github.com/iTXTech/php-build-scripts/issues/23)

**Comment by ishitatsuyuki** [comment]
Your link is even not an issue.

**Comment by Leo3418** [comment]
Is this a valid reason for closing this issue?

**Comment by ishitatsuyuki** [comment]
Cannot reproduce, no details. Enough.
