### ISSUE TITLE
Is this my problem or portforward?

### ISSUE THREAD

**Issue by DubaiGamerXD** [iTXTech/Genisys#2103]
Everything seems fine.. the server is on BUT when i go to mcpe its not on my remote world (I removed all of my servers) but still..and in server hosting website it dosent work, Little help?

**Comment by iPocket** [comment]
Do not use the issue tracker as a help forum.

**Comment by DaMatrix** [comment]
"server hosting website" srsly?

**Comment by dktapps** [comment]
If you continue to misuse our issue tracker, you will he banned. I've just about had enough of you.
