### ISSUE TITLE
Lag when Open and closing an inventory in MCWin10 

### ISSUE THREAD

**Issue by Mike4l6** [iTXTech/Genisys#2104]
#### Issue description

I will have to wait for a couple of seconds if I'm in my server in MCWin10 if I open and close my inventory tons of times. :/
#### Steps to reproduce the issue

Open/Close Inventory several times

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: WINDOWS 10 EDITION 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheAppleGamer** [comment]
You failed to provide the Server OS, PHP, Genisys version, so it will be closed

**Comment by Mike4l6** [comment]
ok let me put that in a sec
