### ISSUE TITLE
Items do not appear in inventory (Updated)

### ISSUE THREAD

**Issue by BudderSticks** [iTXTech/Genisys#2105]
Recently on my Genisys 0.15.10 MCPE server I have relized a glitch. I am not to sure what caused this problem but I will give as much information as possible. First, the problem is when you do /give player apple 1 the item will not appear in your inventory. When you die the item will appear. Sometimes the glitch doesnt happen and the items do appear. But if you are giving yourself for example two stacks of cobblestone, only one will appear. (Note: that is when the glitch sorta doesnt appear to be there but still laggy)

Items seem not to appear whenever items are supposed to instantly appear in inventory.

I have looked at all issue tickets on this and tried everything. I am currently using a host for my Genisys server so I contacted the support there too but they said come here.

Here is my list of plugins. (I have tried to re install the majority of them but none of that worked)

-BuildUHCJericMD
-EasyMessages
-Functions
-Genisys
-HereAuth
-MyPlot
-PureChat
-PurePerms
-SW_svile
-SkyBlock
-SwaggyMOTD
-TNTRun
-WorldEdit
-WorldGM
-essentialsTP
-iProtector

I currently do nor know what caused this malfunction. If you could help me out that would be great. If you need any more information I would be glad to send it.

BudderSticks

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by BudderSticks** [comment]
I belive I am running client, and I sent a list of my plgins in the first message I sent. If I knew what caused the glitch I would havefixed it by now.

**Comment by BudderSticks** [comment]
I sent the plugins with the main messages I sent. Plus I am running PHP

**Comment by iPocket** [comment]
@BudderSticks You've deleted the template, that's the reason.
