### ISSUE TITLE
Player setAllowFlight bug

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#2108]
#### Issue description

In a plugin when player is flying and setAllowFlight(false) the player do not fall it stay on the air and it can't fly/jump sorry for my english#### Steps to reproduce the issue

#### OS and versions

* Genisys:  c4632558
* PHP: 7
* Server OS: ubuntu
* Game version: 0.15.10

**Comment by dktapps** [comment]
This is a client issue. It has been fixed in the 0.16 beta.

**Comment by SuperAlecs** [comment]
Thanks for information!
