### ISSUE TITLE
Door Animation not Showing

### ISSUE THREAD

**Issue by iTzAnTiFTW** [iTXTech/Genisys#2112]
#### Issue description
When Opening//Closing a door, you do not recieve a animation. This occurs when you open doors with a item as well with no items.

#### Steps to reproduce the issue
 Opening/Closing a door using Genisys causes no hand motion when opening/closing including when holding a item.

 OS and versions
* Genisys: c463255
* PHP: 7.0.2
* Server OS: iOS iPhone 6
* Game version: 0.15.10 - Pocket Edition

**Comment by dktapps** [comment]
Client bug.
