### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by JustMaks19** [iTXTech/Genisys#2119]
Pls, add `public function getInteface(){ return $this->interface; }` in Player.php

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
