### ISSUE TITLE
0.16.0 Genisys is Closed?

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys#2121]
#### Issue description

Genisys is Death in 0.16.0? or 0.16.0 is extremaly bug?

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Thank you for spamming. Maybe you could read the README.

**Comment by RedstoneAlmeida** [comment]
Please, read again my question
