### ISSUE TITLE
Genisys Crash (Chunk)

### ISSUE THREAD

**Issue by Misteboss** [iTXTech/Genisys#2124]
#### Issue description

Sometimes my server crash, you can see the error below but i don't know why exactly 
#### OS and versions

* Genisys: ce1fd048
* PHP: 7.0.2
* Server OS: Debian 8
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```"Call to a member function getChunk() on null" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2767[m
```

**Comment by dktapps** [comment]
Related to #1908
