### ISSUE TITLE
[README] 0.16 update status

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#2126]
This issue is here for the purposes of people not spamming me or anyone else any further about the 0.16 update.

Yes, I'm now primarily working on PocketMine-MP. However, this does NOT mean that I'm abandoning Genisys, as I'm fully aware that Genisys is still for the time being more feature-complete than PocketMine is.

The 0.16 update is currently not yet stable and still in the testing phase. It wil be released into the Genisys repository when it is stable.

Thank you for your patience. Remember, I am one human being, and this is not my full-time job.

References: #1807

**Comment by DubaiGamerXD** [comment]
Read and Understood!

**Comment by willotheblessed** [comment]
Thank you. Will the update be available first on PocketMine-MP or here?

**Comment by SalmonGER** [comment]
@willotheblessed It already is for PocketMine. No support though, since it isn't merged into master yet.

**Comment by FienixEC** [comment]
sorry to bother, can u provide a link to Pocketmines 16.0 version phar? i tried looking and updated to the latest on MP jenkins and it still says Server Outdated, thank you!

**Comment by ishitatsuyuki** [comment]
@FienicEC this is not a support forum. Ask your question on our or their chat service or you will get banned.

**Comment by CaptainDuck** [comment]
Is there a 0.16.0 Genisys test Phar yet? :3

**Comment by ishitatsuyuki** [comment]
@CaptainDuck asking means that you're not capable to use beta software, shut up.

**Comment by ParkChanSol** [comment]
@dktapps @ishitatsuyuki Plz lock message

**Comment by ParkChanSol** [comment]
Plz Lock Message

**Comment by ishitatsuyuki** [comment]
@ParkChanSol shut up, it's none of your business.

**Comment by ParkChanSol** [comment]
@ishitatsuyuki 
Ok. Ok. I'll shut up.
You'd batter respect others
