### ISSUE TITLE
The Rail issue

### ISSUE THREAD

**Issue by Muqsit** [iTXTech/Genisys#213]
![screenshot_2016-02-01-20-05-41](https://cloud.githubusercontent.com/assets/15074389/12724487/454e905c-c91f-11e5-8b15-d353b3f1e592.png)
The image..

**Comment by PocketKiller** [comment]
my fault, I'll check it out.

**Comment by SleepSpace9** [comment]
now one more error with getDrops():

Fatal error: Declaration of pocketmine\block\Rail::getDrops(pocketmine\item\Item $item) must be compatible with pocketmine\block\Block::getDrops(pocketmine\item\Item $item): array in /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/block/Rail.php on line 0
