### ISSUE TITLE
RakLib failed.

### ISSUE THREAD

**Issue by jerryzooyoyo** [iTXTech/Genisys#2132]
#### Steps to reproduce the issue

Well, I just updated to 0.16.0.5 (API 2.0.1), with empty plugin folder, empty player folder.
#### OS and versions

* Genisys:[`c25d07608295ea1e25687514c9a433d7c7fe6669`](https://github.com/iTXTech/Genisys/tree/c25d07608295ea1e25687514c9a433d7c7fe6669)
* PHP: `7.0.11`
* Server OS: `Windows Server 2012 R2 Datacenter`
* Game version: `0.16.0.5`

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: assert(): Still 5089 bytes unread! failed in C:\PocketMine-MP\src\pocketmine\network\RakLibInterface.php on line 140
```

**Comment by Muqsit** [comment]
The 0.16 branch is still in testing. You can write the issue in the PR conversation instead.
