### ISSUE TITLE
Bug genisys DATA_SHOW_NAMETAG

### ISSUE THREAD

**Issue by Andrew1481432** [iTXTech/Genisys#2135]
Error console pocketmine/event/player/PlayerPreLoginEvent Undefined class constant DATA_SHOW_NAMETAG

**Comment by kabluinc** [comment]
Some data flags were changed and some removed due to 0.16 changes so plugins that use metadata need updating.

**Comment by Muqsit** [comment]
![sx](https://cloud.githubusercontent.com/assets/15074389/19907253/0660919a-a08f-11e6-9cb4-4f0380200f95.PNG)
