### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by MasterWolf** [iTXTech/Genisys#214]
When i installed genisys, server dont want to start. It just says "You need to use PHP 7". How to install PHP 7?

**Comment by markkrueg** [comment]
@MasterWolf It depends on your OS. Are you on Linux, OS X, or Windows?

**Comment by PocketKiller** [comment]
he is Android.

**Comment by MilkoIvanov** [comment]
No im on Linux

**Comment by gaoyichuan** [comment]
on Android? ...

**Comment by MasterWolf** [comment]
Yes i am on android and i havent got any windows/linux device at the moment. And i think if there is on solution, you can create branch "PHP 5 0.14.0" if its not very hard for you. A lot of my friends have servers on android. And i think that android is not bad, its very good OS to run servers. My server is 7 months running on my android without any problems. But now... I dont know what to do... So what is solution? Maybe create branch or there is a way to install PHP 7 on android?

**Comment by MasterWolf** [comment]
Plz help

**Comment by Efforto** [comment]
Android......
that's crazy, PHP7 on Android!?
try terminal ,

**Comment by MasterWolf** [comment]
Where can i get php5 for 0.14.0?

**Comment by MasterWolf** [comment]
Can you give me a link for 0.14.0 php5 ?

**Comment by MasterWolf** [comment]
Now i will wait for genisys-android prject :D

**Comment by djpiper28** [comment]
You could use the app "Server for PHP" which is on PHP7 and install pthread.so to the app data on rom (needs root). I tried to edit PocketMine-MP for android by inserting a PHP7 file but it replaced it.

**Comment by ishitatsuyuki** [comment]
Do not bump old issue.
