### ISSUE TITLE
binary issue

### ISSUE THREAD

**Issue by inferboy** [iTXTech/Genisys#2140]
#### Issue description

Warning: unpack(): Type N: not enough input, need 4, have 0 in PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 335
#### Steps to reproduce the issue

when player joins
#### OS and versions

* Genisys: Genisys-7896cbd
* PHP: 7.0.3
* Server OS: Debian 8
* Game version:   Minecraft PE v0.16.0.5 alpha (protocol version 91)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by dktapps** [comment]
Are you using Synapse?

**Comment by inferboy** [comment]
no
