### ISSUE TITLE
Server vanilla commands broken

### ISSUE THREAD

**Issue by Sandertv** [iTXTech/Genisys#2141]
#### Issue description

When installing the 0.16 version of Genisys the server commands seem to be broken. Commands such as /stop, /plugins and /version do not work, but give the unknown command error.
#### Steps to reproduce the issue

1. Install the latest 0.16 version of Genisys
2. Go into the game (or console) and try to execute the command /stop
#### OS and versions

* Genisys: 7896cbd0621fd6acc26cc7101c6921303d7e25f4
* PHP: 7
* Server OS: Linux
* Game version: PE

**Comment by dktapps** [comment]
That error has nothing to do with commands, that's a plugin issue.

**Comment by Sandertv** [comment]
I'm not sure if that error was from the commands, sorry. There is no error when executing the server commands, just unknown.

**Comment by inferboy** [comment]
my players are saying /spawn and some commands don't work, they get the message "cheats aren't enabled". what's that about?

**Comment by Sandertv** [comment]
The commands are in fact able to be used through console, just not in the game, I found out.

**Comment by dktapps** [comment]
This is only happening on iOS I bet too, right?

**Comment by inferboy** [comment]
i dont know

**Comment by flaxues** [comment]
@dktapps Occuring on W10 too. /version doesn't work but /help does... And I have no plugins interfering /version or /help

**Comment by flaxues** [comment]
Hmm Now W10 commands are working normally again??

**Comment by Sandertv** [comment]
This is happening on Android versions of MCPE as well.

**Comment by Sandertv** [comment]
What's weird too, is that commands can be executed through players via a command in console. Say I use this command from Slapper:
/rca Sandertv stop
The command DOES do what it's supposed to, while it doesn't when using the command directly in game.

**Comment by Muqsit** [comment]
I surveyed my server's players' and they've that
`./<command>` works but `/<command>` doesn't (iOS)

The permission bug (if you are using a permission-based plugin) is due to $player->sendCommandData() not being executed on player join.

**Comment by flaxues** [comment]
@Muqsit ./<command> is a hack from @dktapps

**Comment by isoz** [comment]
From what I see in my server sometimes they work, sometimes they dont, relogging helps.

**Comment by flaxues** [comment]
@isoz Can confirm that relogging helps

**Comment by Callum9966** [comment]
This is what I think is the reason, commands that are on single player work like /help, /gamemode, etc... but commands just for servers like /plugins, /version don't work because 0.16.0 now has commands as well, which means server commands and single player commands are interfering with each other, I believe servers now use ./plugins or .plugins

**Comment by TheAppleGamer** [comment]
I have a fix for it, it is modifying the fast hack and no one has had to do ./ anymore
