### ISSUE TITLE
Error crash 

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#2142]
@dktapps 0.16.0 ....

I'm using PR " Remove synapse" and plugin for support synapse ( for use for 0.16.0 ) and if i'm enter on server ( Windows 10 Edition ) get crash.

If i'm enter with Pocket Edition is all ok. But if i'm put : " / " for login ,client get crash.

You can fix,please?

**Comment by inferboy** [comment]
issue template not followed. Closing issue

**Comment by dktapps** [comment]
Didn't I ban you once already?
