### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#2143]
#### Steps to reproduce the issue

I'm using PR " Remove synapse" and plugin for support synapse ( for use for 0.16.0 ) and if i'm enter on server ( Windows 10 Edition ) get crash.
**YES ISN'T MASTER ,BUT ISN'T CHANGES **
If i'm enter with Pocket Edition is all ok. But if i'm put : " / " for login ,client get crash.

You can fix,please?

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/f7104d6a509a4d50eaeb88eec01d80cd888b9515
* PHP: 7.0.9
* Server OS: Linux , Ubuntuu 16.04.1 LTS 64bit
* Game version: 0.16.0 on android and 0.16.1 on Windows 10

#### Crashdump, backtrace, memory dumps, plugins list or other files

``` non
```

**Comment by dktapps** [comment]
Branch not intended for production use, this is in a PULL REQUEST for a reason. Stop spamming and read the issue template.

**Comment by NycuRO** [comment]
@dktapps And master have this issue -_-
