### ISSUE TITLE
Item errors

### ISSUE THREAD

**Issue by AppleDevelops** [iTXTech/Genisys#2149]
#### Issue description

Item::parseCompoundTag() must be in instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\nbt\tag\EndTag
#### Steps to reproduce the issue

I just did /kill
#### OS and versions

* Genisys: f7104d6a
* PHP: 7.0.3
* Server OS: LXDE (Ubuntu)
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by JackNoordhuis** [comment]
We need more information and possibly a backtrace to find the cause of this issue.

**Comment by JackNoordhuis** [comment]
No response. Closing until more info is given.
