### ISSUE TITLE
Can't find .phar

### ISSUE THREAD

**Issue by Doge987** [iTXTech/Genisys#2155]
I can't seem to find the .phar file for Genisys. Yesterday it was in readme.md. Where has it gone?

**Comment by adamiss5138** [comment]
Simply download source code in .zip file and use DevTools plugin to create .phar

**Comment by Ragnok123** [comment]
Download then on GitLab artifacts

**Comment by Ragnok123** [comment]
@adamiss5138, jestli nevíš jak to udělat, tak nedělej

**Comment by adamiss5138** [comment]
@Ragnok123 Dá sa to spraviť viacerými spôsobmi. Tak sa tu nevyťahuj

**Comment by Ragnok123** [comment]
@adamiss5138, jen ne extrahováním zipu v devtools. Jako jde to devtools, ale jen na vds/vps. Nejčastější způsob je PHPStorm, nebo android appka PHAR.

**Comment by adamiss5138** [comment]
@Ragnok123 Máš pravdu, každý má iný spôsob.

**Comment by Ragnok123** [comment]
@adamiss5138, jinak jsem vevěděl, že i slováci jsou vývojaři)0))

**Comment by eddir** [comment]
@Ragnok123, what is the link for last successful build in phar?

**Comment by adamiss5138** [comment]
@eddir 
Latest successful build
https://gitlab.com/itxtech/genisys/builds/5897224/artifacts/download

**Comment by Doge987** [comment]
Does the last successful build there contain the phar for 0.16.1?
