### ISSUE TITLE
Unable to enchant items on MCW10E

### ISSUE THREAD

**Issue by Wizardon777** [iTXTech/Genisys#2156]
#### Issue description
Unable to enchant items on MCW10E

#### Steps to reproduce the issue
1. place item + 3 lapis in enchant table
2. pick the 3rd enchantment
3. take item into inventory
4. watch it drops from inventory
5. pick it up and get an un-enchanted item + 3 lapis

#### OS and versions

* Genisys: f7104d6
* PHP: 7.0.11
* Server OS: Windows 10 x64
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files
Plugins:
essentialsTP v1.0.9, CommandSigns v2, CrateKeys v1.0.5, DevTools v1.10.0, EconomyAPI v2.0.9, EconomySell v2.0.7, EconomyShop v2.0.7, LiveXYZ v0.5.0-alpha, ManyWorlds v2.1.0, NetherChests v1.1.1, PurePerms v1.3.7, SignPortal v1.1.2, SimpleAuth v1.7.2, SimpleMessages v1.2, VoteReward v3.0.2, WorldProtect v2.2.0, SimpleAuthHelper v2.0.4

**Comment by dktapps** [comment]
Client bug. You'll need to set `allow-cheats` to `true` in genisys.yml

**Comment by Wizardon777** [comment]
just to clarify, what would happen if I'll set `allow-cheats` to `true`?

**Comment by dktapps** [comment]
It disables cheats. There are bugs in the Win10 Edition that cause problems with anti-cheat.
