### ISSUE TITLE
Synapse Error

### ISSUE THREAD

**Issue by JackboyPlay** [iTXTech/Genisys#2157]
#### Issue description
 If I want to connect to my Nemisys server with my Genisys server it says "Client IP has disconnected due to Incompatible SPP version! Require SPP version: 7
"

#### Steps to reproduce the issue
 Let the Genisys server connect to the Nemisys server

#### OS and versions

* Genisys: latest
* PHP: php-7 
* Server OS: Windows [Nemisys] Linux [Genisys]
* Game version: 0.16.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Check closed issues before opening a new one.
