### ISSUE TITLE
Player cannot use command on 0.16

### ISSUE THREAD

**Issue by TanToan99** [iTXTech/Genisys#2159]
When i write /help, server show list of command, but when i write command. It show "Unknown command. Try /help for a list of commands"

* Genisys: 2e13c6d
* PHP: 7.0.2
* Server OS: Linux
* Game version: 0.16.0.5

#### Crashdump, backtrace, memory dumps
: Plugins (41): FCAKit v1.0, NoSpam v0.1, WorldProtect v2.2.0dev1, Napthe v1.0.0 beta 1, TimeCommander v2, TapToDo v2.2, AlwaysSpawn v2.2.2, ManyWorlds v2.0.3, Fly v0.0.1, FCARules v2.0.0, PurePerms v1.3.7, VoteReward v3.0.2, Functions v1.0, FolderPluginLoader v1.0.0, iProtector v3.1a, KillMoneyFix v1, TimeCapsule v1.1.1, ChairPE v1.0.1, Broadcaster v1.16, ChatLimit v1.0.0, ClearLagg v1.1.0, SignPortal v1.1.2, AdvancedKits v5.0b1, DevTools v1.1-iTX, WorldEdit v1.0.2, EconomyAPI v2.0.9, MSpawns v1.5, FCA_VIP v1.0.0 beta 1, NameCorrector v1.0.0#build010, CustomAlerts v1.6, FlyOff v1, PrizeWin v1.0.6, SimpleAuth v1.8.1, SimpleAuthHelper v2.0.4, EconomyShop v2.0.7, EconomySell v2.0.7, PureChat v1.3.3, GrabBag v2.5.0, SimpleWarp v2.0.3, Plots v1, WarpSigns v0.0.1
![screenshot_20161106-120001](https://cloud.githubusercontent.com/assets/23021197/20035518/1a5b305e-a41a-11e6-9002-7175adc8b7e6.png)
![screenshot_20161106-115947](https://cloud.githubusercontent.com/assets/23021197/20035519/208067e2-a41a-11e6-847b-fc37e842b0ff.png)

**Comment by ishitatsuyuki** [comment]
#2141
