### ISSUE TITLE
Server not joinable.

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#2161]
#### Issue description
After the Synapse downgrade update, the server is un joinable by everyone.

#### Steps to reproduce the issue
Join the server using build 9f0acbc45750f498ba4e83760a1539675cf9a6c7

#### OS and versions

* Genisys: 9f0acbc
* PHP: 7.0.12
* Server OS: Ubuntu 14.04 64-bit LTS
* Game version: 0.16.0 & 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
No crashdumps.
```

**Comment by Tarik02** [comment]
https://github.com/iTXTech/Genisys/pull/2162
