### ISSUE TITLE
Enchanting is not working at all

### ISSUE THREAD

**Issue by mihnea91** [iTXTech/Genisys#2165]
Enchanting is not working. If you try to enchant an item (for example a sword) , after you apply the enchant as long as the item is in the enchanting table inventory it shows you that the sword is enchanted but when you try  to drag that sword into your inventory it disapear and after that it is dropped without any enchant. The enchants works only if you put on true cheating mode in genysis.yml

* Genisys: Genisys_017fa6f_2016-11-06_12-57-03
* PHP: 7.0.3
* Server OS: ubuntu 14.04 x64 lts
* Game version: 0.16.0.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Infernus102** [comment]
Enchanting is not yet supported for 0.16.0 Genisys, try /enchant

**Comment by Muqsit** [comment]
You need to enable `allow-cheats` in `genisys.yml` for it to function.
Enabling `allow-cheats` may introduce duplication glitches.

**Comment by dktapps** [comment]
Also, some breaking changes were made to enchanting in 0.16 which we haven't yet worked out.

**Comment by LordJoshie** [comment]
thanks Muqsit <-- stupid name keeps auto correcting to Kuwait .... 

also, leave the issue open until it's fixed u fuck boy
