### ISSUE TITLE
Outdate client

### ISSUE THREAD

**Issue by TanToan99** [iTXTech/Genisys#2174]
Issue description

When i join server with version 0.15.10, Server send message "login timeout" . It doesn't send message "outdate client". 

OS and versions

Genisys: 9f0acbc
PHP: 7.0.2
Server OS: Linux
Game version when join: 0.15.10
Crashdump, backtrace, memory dumps, plugins list or other files

No crashdumps.

**Comment by dktapps** [comment]
This is because of a batch decoding issue because of Mojang's stupidity in 0.15. The same thing will occur with two vanilla clients.
