### ISSUE TITLE
the Cancelable events is not working in version 0.16

### ISSUE THREAD

**Issue by laurobeleche** [iTXTech/Genisys#2175]
* Genisys: 01480a3
* PHP: 7.0.4
* Server OS: windows 10
* Game version: 0.16.1

**Comment by iPocket** [comment]
Please review the FAQs and contribution guidelines before opening an issue.

Read the FAQs
Contribution guidelines

**Comment by iPocket** [comment]
Provide us more information?

**Comment by laurobeleche** [comment]
I believe that the event is not being handled in the proper way, but still need to gather more information, I did the update today from my server and I'm finding these and other problems.

**Comment by iPocket** [comment]
#2176
