### ISSUE TITLE
Canceling certain events no longer work

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#2176]
#### Issue description

After 0.16 many events like EntityRegenEvent, not sure what else can be cancelled and doesn't work,  cannot be cancelled. It doesn't show anything in the console but it doesn't work
#### Steps to reproduce the issue

Cancel the event using a plugin it doesn't work.
#### OS and versions

* Genisys: e42c372
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by EpicSteve33** [comment]
I have no issues with block break or place

**Comment by erkam2002** [comment]
It works was me

**Comment by Infernus102** [comment]
DataPacketReceive Event doesn't work for me anymore for Itemframe ...

**Comment by iPocket** [comment]
Any list for events that aren't cancellable?

**Comment by Infernus102** [comment]
DataPacketReceive Event

**Comment by TheAppleGamer** [comment]
EntityRegainHealthEvent

**Comment by TheAppleGamer** [comment]
Found the issue
