### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#2177]
#### Issue description

While in combat with a sword it appears to have the start of 1.9 criticals but it shouldn't be occuring
#### Steps to reproduce the issue

Combat with using a sword
#### OS and versions

* Genisys: e42c372
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Sandertv** [comment]
I can confirm this, random critical particles occuring after combat

**Comment by IISweePII** [comment]
Hmm, does it occur when you hit anywhere on the character? Criticals do happen sometimes, but only by chance

**Comment by Sandertv** [comment]
It happens actually when you don't get hit anymore. After being damaged you keep getting random critical particles around you... Nevermind I think I just found out what the problem is while typing this!!

**Comment by Sandertv** [comment]
I think because of particle ID changes, the particles that happen when you get the particles on the ground when jumping on it, have the wrong ID and show critical particles. (I think this is the problem)

**Comment by TheAppleGamer** [comment]
UPDATE: Its a bug with health regen, use a plugin that shows a health popup and you will notice that it actually takes longer than it appears on screen.
