### ISSUE TITLE
Client Crash while Spawning Statues

### ISSUE THREAD

**Issue by FunnyBuddys** [iTXTech/Genisys#2179]
#### Issue description

Client Crash while Spawning Statues

#### Steps to reproduce the issue

Download plugin like Slapper and Spawn an statue

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/017fa6fe80b8a75117bed2eed81a3927b78c6905
* PHP: 7.0.6
* Server OS: Linux
* Game version: 0.16.0.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Plugin issue.
