### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by MilkoIvanov** [iTXTech/Genisys#218]
I was wondering if a /feed command is possible

**Comment by gaoyichuan** [comment]
What's the command for?

**Comment by MilkoIvanov** [comment]
Well to feed you or other player

**Comment by gaoyichuan** [comment]
@MilkoIvanov Feed? I haven't heard of the command yet.

**Comment by flaxues** [comment]
It's a command what is in the official Essentials so not a vanilla command :)

**Comment by Efforto** [comment]
it's a useless command i think , and i'd like to say , can u guys NOT OPEN ISSUE TO TELL SOME USELESS THING ON GITHUB?

**Comment by MilkoIvanov** [comment]
@Efforto Ok if you think its useless.closing
