### ISSUE TITLE
ExplodePacket doesn't work

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#2181]
#### Issue description

ExplodePacket doesn't work, following by the code in Lighting.php

#### Steps to reproduce the issue

```
$pk = new ExplodePacket();
		$pk->x = $this->x;
		$pk->y = $this->y;
		$pk->z = $this->z;
		$pk->radius = 10;
		$pk->records = [];
		$player->dataPacket($pk);
```
Just run this code anywhere, in command for instance.

#### OS and versions

* Genisys: 017fa6f
* PHP: 7.1.0
* Server OS: Windows 10
* Game version: Windows 10 Edition

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
well, obviously, since you've given it no records... it's not supposed to blow things up, only make the sound and particles.

**Comment by intagaming** [comment]
No sound and particle too!
