### ISSUE TITLE
Worlds crash now

### ISSUE THREAD

**Issue by poustmal** [iTXTech/Genisys#2182]
Genisys version: 017fa6f
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android
Game version:0.16.0.5

Now,when I join in my worlds,all crash often and when I spawn a slapper also,I can't join,it crashes and with slappers.

Steps to stop this crash:
I think that slappers plugin is unsupported for 0.16. and maybe I should create again level.dat to fix world crash?

**Comment by starterdragon** [comment]
false, On my server, I have a slapper.. U maybe using an outdated version of slapper..

**Comment by jojoe77777** [comment]
"Plugin fault" - You're using an outdated version of Slapper, as @starterdragon said.

**Comment by poustmal** [comment]
starterdragon send me the slappers plugin pls if you can

**Comment by Muqsit** [comment]
This is not a world crash. This might be something to do with how LoginPacket is handled. If it would be world crash, it would've occurred when you were being transferred from one world to another.

**Comment by dktapps** [comment]
@Muqsit he's using an outdated version of Slapper, it's bad metadata causing crashes.
