### ISSUE TITLE
enchanting table bug

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#2184]
#### Issue description

When you enchant a item the item will enchant but after enchant the items will drop out and doesn't enchant
#### Steps to reproduce the issue

enchant a item with gamemode survivaL
#### OS and versions

* Genisys: 017fa6fe
* PHP: 7.0.6
* Server OS: UBUNTU
* Game version:  0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Duplicate of #2099

**Comment by SuperAlecs** [comment]
nope, this is not the same, this is enchanting table bug not enchants

**Comment by Muqsit** [comment]
https://github.com/iTXTech/Genisys/issues/2165
