### ISSUE TITLE
View range is very small

### ISSUE THREAD

**Issue by dsyer** [iTXTech/Genisys#2186]
When playing in a world that is hosted locally on the client, or on a Realm hosted by Mojang, the horizon is quite far away, and there is no "edge" to the rendered terrain (it just fades out). Using Genisys I see a distinct edge, and it's very close, so I can't see stuff that I could have seen in a local world.

#### OS and versions
* Genisys: 017fa6f, v0.16.0.5 alpha
* PHP: php:7-zts (docker image)
* Server OS: Linux
* Game version: 0.16.0

**Comment by kabluinc** [comment]
The render distance/chunk loading values can be changed in the pocketmine.yml. by default its set to low

**Comment by dsyer** [comment]
OK, thanks. I already tries tweaking these values:  `memory.max-chunks.trigger-limit`, `chunk-sending.max-chunks`, `chunk-ticking.per-tick` and `chunk-ticking.tick-radius`. Either I haven't found a combination that works or I'm looking in the wrong place. Can you be more specific?

**Comment by KingDman** [comment]
I cant install it I install genisys but not php

**Comment by starterdragon** [comment]
Try this settings:
chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 16
 #Amount of chunks sent around each player
 max-chunks: 128
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 5
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 64
 #Radius of chunks around a player to tick
 tick-radius: 16
 light-updates: false
 clear-tick-list: true

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 8
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 8

**Comment by dsyer** [comment]
Thanks for the suggestion. I'm still seeing edges, so until I actually navigate into an area it won't render. Anything else I can try? Which of these settings actually controls that?

**Comment by dsyer** [comment]
Update. This is working much better now with the above and this:

```
chunk-sending:
per-tick: 16
max-chunks: 4096

chunk-ticking:
per-tick: 64
tick-radius: 32
```

Maybe something for the docs?

**Comment by KairusDarkSeeker** [comment]
Please close this issue, its already solved.

**Comment by dsyer** [comment]
Actually, I don't think this issue is closed. For a start, there were no changes I could see to and code or documentation. Also, I don't think the problem is actually solved. This is an update: i still have issues of "edges" showing up in the game. If I fly into them I get completely lost and have to quit and start playing again, or sometimes restart the server, to get back to solid ground. Surely this is a bug? Also, on some devices I cannot start the game at all, and the genisys console just reports a timeout. This only happens when I bump the config file as above.

**Comment by dktapps** [comment]
Sending 4096 chunks I'm not surprised you're timing out. 192 should be more than sufficient. The problem with invisible chunks is a client issue. There have been large chunk format changes in 0.17 that may resolve this issue however.

**Comment by dsyer** [comment]
I guess that underlines my point that there is some missing documentation? I don't believe your assertion about client issues though (since I can use a non-genisys world and it works much smoother).
