### ISSUE TITLE
Crashing Client while teleport to other world.

### ISSUE THREAD

**Issue by EnderKenjii** [iTXTech/Genisys#2187]
#### Issue description
Crash client while teleport to other world, the world was working well on 0.15.10. I heard from someone is nbt related problem.

Notice: The world is ported from pc. I'm sure its Genisys problem, it works well on Nukkit.

#### Steps to reproduce the issue
1. Use MultiWorld "/mw tp world2"
2. Crashed client.

#### OS and versions

* Genisys: 83a4dd9
* PHP: 7.0.3
* Server OS: Multicraft
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

-

**Comment by dktapps** [comment]
Closing for ban evasion.
