### ISSUE TITLE
0.16 items

### ISSUE THREAD

**Issue by poustmal** [iTXTech/Genisys#2188]
Genisys version: 017fa6f
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android
Game version:0.16.0.5

Can you add some items from 0.16.0?Prismarine blocks,sea lanterns and beacons if they're possible?If beacons are difficult to add them,at least try to add the other items pls.

**Comment by ishitatsuyuki** [comment]
wontfix
