### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by laurobeleche** [iTXTech/Genisys#2189]
* Genisys: 01480a3
* PHP: 7.0.4
* Server OS: Windows 10
* Game version: 16.1

Warning: assert(): Still 13 bytes unread in pocketmine\network\protocol\SpawnExperienceOrbPacket failed in C:\xampp2\htdocs\brasilcraft-pa\Genisys16\src\pocketmine\network\Network.php on line 253

This message has been printed several times on the console.

**Comment by dktapps** [comment]
You should not have assertions enabled in a production environment. In your php.ini:

`zend.assertions=-1`

That message is a **debug alert** to tell you that the server received an unexpected packet from the client.
