### ISSUE TITLE
$player->sendTip()

### ISSUE THREAD

**Issue by laurobeleche** [iTXTech/Genisys#2191]
* Genisys: 01480a3
* PHP: 7.0.4
* Server OS: windows 10
* Game version: 0.16.1

I have encountered problems using the $ player-> send tip ().
Messages have a daley of up to 1 minute even sending them every second or every 20 ticks.

To reproduce, just create a plugin using a 20-tick repeatTask using $player->sendTip( "message")

**Comment by dktapps** [comment]
Tips changed in 0.16, they are now very stuttery if you spam them. Blame Mojang.
