### ISSUE TITLE
Potion damage in Creative

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#2193]
#### Issue description

When using a harming potion you can kill players in creative
#### Steps to reproduce the issue

Get a harming potion and a player
Make sure the player is in gmc
hit then with harming
#### OS and versions

* Genisys: 379a533
* PHP: 7.0.12
* Server OS: Windows 10
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by samalero** [comment]
reproduced

**Comment by iPocket** [comment]
Let me check it out...
