### ISSUE TITLE
Review command execution

### ISSUE THREAD

**Issue by laurobeleche** [iTXTech/Genisys#2194]
* Genisys: 01480a3
* PHP: 7.0.4
* Server OS: windows 10
* Game version: 0.16.1

When we begin typing a command, a list is displayed, a list of the commands on the server, if the command you are tending to execute is not in this list, the PlayerCommandPreprocessEvent event is not even called, and you already receive an error message saying that Command does not exist, however, if you run the command as follows ./ starting with ".", It calls the PlayerCommandPreprocessEvent event normally and everything follows its natural cycle. I believe that this functionality, added in the recent MCPE update, is requesting the CommandMap server from the server and comparing it with the player's permissions inside the server, which eventually conflicts with some permissions plugins that give privileges without granting OP. I can not tell if this is a bug, but it sure is something that needs to be reviewed.

Tests were performed at a clean Genisys facility.
![screenshot_2016-11-10-10-20-19](https://cloud.githubusercontent.com/assets/14208219/20176570/8d56ac10-a72f-11e6-82da-3641ecce3e39.png)

**Comment by dktapps** [comment]
Invalid/outdated version. Closing.

**Comment by laurobeleche** [comment]
Sorry for my failure, I also ran the test without using phar, using the github source code directly, I put the src folder in the Genisys root, and the same error occurs, it does not show any version at the top of the console.
![console](https://cloud.githubusercontent.com/assets/14208219/20177174/8b69d6a4-a732-11e6-8383-2e595aaba159.png)

**Comment by flaxues** [comment]
use /version to see the version you are running
