### ISSUE TITLE
Enchanting Tables Don't Enchant.

### ISSUE THREAD

**Issue by LordJoshie** [iTXTech/Genisys#2198]
#### Issue description

Put items in e-table, select what you want, it gets plopped out with no enchant....
#### Steps to reproduce the issue

Try it yourself....
#### OS and versions

* Genisys:  21d5f86
* PHP: 7.0.6
* Server OS: Ubuntu 15.10 Server
* Game version: 0.15.10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
Oh my GOD. PLEASE go through the closed issues.

**Comment by LordJoshie** [comment]
why the he is it closed if its not fixed ??

**Comment by iPocket** [comment]
Because it's a **duplicate**, and it's WIP

**Comment by dktapps** [comment]
Again? Fine, let me find my ban hammer.

**Comment by TheAppleGamer** [comment]
@LordJoshie I've had no issues with enchants
