### ISSUE TITLE
cant pick up NBT items

### ISSUE THREAD

**Issue by AvivShopen** [iTXTech/Genisys#2199]
#### Issue description
When you make items with nbt tags you cant pick them up unless youre in gamemode creative

#### Steps to reproduce the issue
make a item with alot of nbt tags and try to pick it up, then in gamemode creative

#### OS and versions
* Genisys: a7d766e
* PHP: 7.0.2
* Server OS: Windows 8
* Game version:  0.16.0.5

#### Crashdump, backtrace, memory dumps, plugins list or other files
nothing, just not able to pick up items

**Comment by TheAppleGamer** [comment]
Enable cheats

**Comment by iPocket** [comment]
^
