### ISSUE TITLE
Items do not drop when mining some ores!

### ISSUE THREAD

**Issue by austina1212** [iTXTech/Genisys#2201]
#### Issue description
When mining ores (diamonds, iron, coal, redstone, gold, etc) it does not drop the item!

#### Steps to reproduce the issue
Place a ore of each type stated above and go to survival mode, then try to mine them!

#### OS and versions

Genisys: 379a533
PHP: 7.0.12
Server OS: Windows 10
Game version: 0.16.1 Windows 10

**Comment by TheAppleGamer** [comment]
Enable cheats and try again also check your plugins

**Comment by austina1212** [comment]
Just started working out of no where ;-;

**Comment by austina1212** [comment]
Where do I find cheats?

**Comment by TheAppleGamer** [comment]
genisys.yml

**Comment by KingDman** [comment]
Hey Austin Can I Be Co On our Server IP:

**Comment by samalero** [comment]
check all your plugins, rather PlayerInteractEvent.

**Comment by iPocket** [comment]
@austina1212 lol, you know me, nice to see you filling the template correctly :)
Can we see your plugin list?
