### ISSUE TITLE
Console Warnings

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#2208]
#### Issue description

Find Warnings in a console.

#### Steps to reproduce the issue

I don't know.

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/6e91f614bff5c5aa556262c8384adb0ff07541c0
* PHP: 7.0.12 x64 Genisys script
* Server OS: Ubuntu 14.04.5 LTS
* Game version: 0.16.1/0.16.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
11.11 22:58:31 [Server] Server thread/INFO [Prémium]SKHigazi: ?
11.11 22:58:33 [Server] INFO Warning: zlib_decode(): data error in phar:///Genisys_.phar/src/pocketmine/network/Network.php on line 234
11.11 22:58:35 [Server] Server thread/INFO [Prémium]SKHigazi: ejjdeee xd
11.11 22:58:40 [Server] INFO Warning: zlib_decode(): data error in phar:///Genisys_.phar/src/pocketmine/network/Network.php on line 234
```

**Comment by ishitatsuyuki** [comment]
Malicious packet, they are not critical.
