### ISSUE TITLE
things are not selected

### ISSUE THREAD

**Issue by vzlomka76** [iTXTech/Genisys#2209]
When the plug-in start dropping things, they are not selected, but when a player throws a thing - it is selected. At the core of [Elywing](https://github.com/H4PM/Elywing) this bug is not observed

[zip_DropParty_v1.0.3_1JgHZWUwUhOEZHZ.zip](https://github.com/iTXTech/Genisys/files/587310/zip_DropParty_v1.0.3_1JgHZWUwUhOEZHZ.zip)

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
