### ISSUE TITLE
Command list

### ISSUE THREAD

**Issue by Harviy** [iTXTech/Genisys#2210]
#### Issue description

Hi,
I want to remove the typing the command list "/". Is this possible ?
https://s17.postimg.org/r7xufoq3z/cats.jpg

#### OS and versions

* Genisys: v0.16.0.5 alpha
* PHP: php7
* Server OS: windows
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
No.
