### ISSUE TITLE
ExplodePacket couldn't send to client

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#2211]
#### Issue description

ExplodePacket couldn't send to client (at least Windows 10 Edition). The TNT is a good example.

#### Steps to reproduce the issue

1. Blow up a TNT
2. Just watch. No effects, no sounds, just hurt, push back and block updates.

#### OS and versions

* Genisys: 55ae11e
* PHP: 7.1.0
* Server OS: Windows 10
* Game version: Windows 10 Edition

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
No error.
```

**Comment by dktapps** [comment]
This is a metadata issue, it will be fixed.
