### ISSUE TITLE
getHealth() get random value sometimes

### ISSUE THREAD

**Issue by KennFatt** [iTXTech/Genisys#2212]
#### Issue description
i try to getHealth() on EntityDamageEvent **and** _instanceof_ EntityDamageByEntityEvent.

first, i hit the entity using diamond sword, and the result from getHealth() is still 20.
then i try again to hit with same weapon, and getHealth() still 20. (it should be 6 cause entity has 3 heart)
and then its normal when i test with hand (getHealth() - 1)

so im not sure about that, then i try again with another weapon ( iron axe ), and same buggy at first time to second time testing

this is some result :
20 === victim health (heart > 10)
15 === victim health (heart < 10)
11 === victim health (i forgot about entity heart when this result)
5 === victim health (heart near 2.5 or above)

i already tested it for 3-4 times.

#### OS and versions

* Genisys: #2205 
* PHP: 7.0.x
* Server OS: Ubuntu 16.10 64-bit
* Game version: 0.16.0.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by KennFatt** [comment]
and i try it again with diamond sword.

i add new function to make sure.

1st times test. Entity/Player heart = 6.5, getHealth() = 20;
20 = victim health
8 getDamage
8 getOriginalDamage
1 getRateDamage

2nd test is same like 1st times, i start when player heart is full.

then i try 3rd test, Entity heart = 8 to 4, getHealth() = 20 to 16.
16 = victim health
8 getDamage
8 getOriginalDamage
1 getRateDamage

4th times, Entity heart = 4 to 0 (died), getHealth() = 16 to 8.
8 = victim health
8 getDamage
8 getOriginalDamage
1 getRateDamage

**Comment by KairusDarkSeeker** [comment]
I don't understand what you're trying to say.

**Comment by TheAppleGamer** [comment]
I'm pretty sure the issue has been opened but with less details lol https://github.com/iTXTech/Genisys/issues/2177

**Comment by KennFatt** [comment]
@KairusDarkSeeker its hard to be explained, the point is getHealth() is buggy. @TheAppleGamer maybe yes

**Comment by JackNoordhuis** [comment]
An entities health isn't actually updated until all event handlers have been called. If you want the updated health value from a damage event you'll have to subtract the event damage from the entities health.

This is not a forum to help you with using the API incorrectly. Unless you can provide some proof that this bug exists this issue will remain closed.
