### ISSUE TITLE
XboxLive bug

### ISSUE THREAD

**Issue by GamakCZ** [iTXTech/Genisys#2213]
#### Issue description

not write in chat

#### Steps to reproduce the issue

Connection to the server

![minecraft_ windows 10 edition beta 13 11 2016 19_10_04](https://cloud.githubusercontent.com/assets/17053298/20247752/f6101046-a9d4-11e6-9b90-56301985d848.png)

#### OS and versions

* Genisys: Genisys-55ae11e Kyrios
* PHP: 7.0.2
* Server OS: linux
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
-
```

**Comment by minecrafter** [comment]
Not an issue with Genisys.
