### ISSUE TITLE
[0.16] Flying and Walking speeds like a turtle

### ISSUE THREAD

**Issue by dterweij** [iTXTech/Genisys#2215]
#### Issue description
When walking or flying you suddenly are walking or flying at the speed of a turtle. Makes it non play able.

#### Steps to reproduce the issue
Fly or Walk after joining the server.

#### OS and versions

* Genisys:  http://jenkins.terweij.nl/job/Genisys/310/
* PHP: 7.0.13 (REMI)
* Server OS: CentOS 6 / 64bit
* Game version: 0.16.1.0 (windows and android client)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by judithdrive** [comment]
The plug-in MyOwnWorld will cause this whenever the player is near a mob. If you are using MOW, try disabling it to see if it is the cause. I don't think you need to remove residual mobs to test, because I think it's a problem in the AI, but I could be wrong. Unfortunately, I don't know of any solution if this is in fact the problem.

**Comment by dktapps** [comment]
That's not a supported build. Please use a phar provided by our CI. No support will be provided for third party builders.

**Comment by dterweij** [comment]
@dktapps it is a supported build. Just my own jenkins thats builds it localy because the provided phars are not always downloadable (lags, offline, not always reachable etc etc). So thats why i build localy. Github is faster to get the code and build  the phar here, then getting your phar at the other side of the world :)

**Comment by dterweij** [comment]
MOW was the problem.

**Comment by dktapps** [comment]
Please read my comment again. We don't know what optimizations or modifications a third-party builder may be performing, therefore we won't provide support for them. The mess that results from inlining on the PocketMine _official_ Jenkins is bad enough.
