### ISSUE TITLE
0.16.1

### ISSUE THREAD

**Issue by orangetictac** [iTXTech/Genisys#2216]
Hello, everybody where i can download Genisys 0.16.1, help me please

**Comment by iPocket** [comment]
Please review the FAQs and contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
