### ISSUE TITLE
EntityArmorChangeEvent called in a wrong event.

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#2218]
#### Issue description

I've just found out that EntityArmorChangeEvent is being called during EntityDamageByBlockEvent which is kinda bad for people who want to get "Entity - while - changing - armor -> 's entity"

#### Steps to reproduce the issue

Try EntityArmorChangeEvent and see how its being called when the player is hit by cactus.

#### OS and versions

* Genisys: 55ae11e5acf93b753129343a3888cd4cf007da05
* PHP: 7.0.13
* Server OS: Ubuntu 14.04 64-bit (LTS)
* Game version: 0.16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Console is clean.
```

**Comment by laurobeleche** [comment]
I want to reproduce the bug, but I did not understand how you did it.

**Comment by GenisysFTW** [comment]
Hey @laurobeleche
Thanks for fixing this annoying issue =D
I should've been more descriptive lol..
