### ISSUE TITLE
EnchantingTable and Anvil can't use in Survival mode

### ISSUE THREAD

**Issue by DKQoo2** [iTXTech/Genisys#2219]
Issue description

EnchantingTable and Anvil can't use in Survival mode.

Steps to reproduce the issue

Just changing to Survival mode, and try to use EnchantingTable and Anvil :D

OS and versions

Genisys: 55ae11e
PHP: 7.0.9
Server OS: Ubuntu 16.04 64-bit (LTS)
Game version: 0.16.1

**Comment by dktapps** [comment]
Check existing issues before opening a new one.

**Comment by DKQoo2** [comment]
I see
