### ISSUE TITLE
Hopper duplication 

### ISSUE THREAD

**Issue by TacosYum** [iTXTech/Genisys#2222]
When throwing items in a hopper 2by2 or 4by4 it duplicates It into each of the hoppers I tried banning them but they still have it placed around the world and it's a survival world so I can't  replace the world.

**Comment by isoz** [comment]
I thought this was fixed like 2 months ago?

**Comment by TacosYum** [comment]
Nope still works on My server

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
