### ISSUE TITLE
Help, how to change the size of the entity of player and mobs?

### ISSUE THREAD

**Issue by MrAlecsesDev** [iTXTech/Genisys#2223]
Gооd Mоrning!
Help, how to change the size of the entity of player and mobs?
Help me , please.

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by DeroxDEVElOPER** [comment]
But what we must use fоr help questions ?

**Comment by Muqsit** [comment]
@DeroxDEVElOPER
https://github.com/iTXTech/Genisys#discussion
