### ISSUE TITLE
How to change the size of the entity or players and mobs?

### ISSUE THREAD

**Issue by DeroxDEVElOPER** [iTXTech/Genisys#2224]
#### Issue description
Im want to change size of entity. I have changed public variables ($height, $size, $eyeSize and $length), but size hasnt been changed. Please, answer me and say, what i do incorrect.
P.S I speak English and Russian
#### Steps to reproduce the issue
-

#### OS and versions

* Genisys: Custom API 2.0
* PHP: 7
* Server OS: Debian
* Game version: 0.16.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DeroxDEVElOPER** [comment]
?????

**Comment by Muqsit** [comment]
Do not use the issue tracker for help questions. Please read the guidelines.
