### ISSUE TITLE
Nether issue (minor)

### ISSUE THREAD

**Issue by TacosYum** [iTXTech/Genisys#2225]
Issue:
The nether portal teleports you to the nether spawn I was hoping for it to spawn you 8x your coordinates just like on pc for survival purposes. Also if you walk far out in the nether and make a portal it does not make a new portal in the over world and what it does is it teleports you to spawn.

Steps to reproduce:
Walk into a nether portal and check coordinates

* Genisys: 55ae11e
* PHP: 7.0.13
* Server OS: Ubuntu 4.04 64-bit
* Game version: 0.16.2

Crashdump, backtrace, memory dumps, plugins list 

Console is new / empty using Genisys only.

**Comment by dktapps** [comment]
The nether implementation is a heap of crap, and Genisys is being phased out, so this will not be fixed. Thank you for reporting this anyway.
