### ISSUE TITLE
FloatingTextParticle bug

### ISSUE THREAD

**Issue by SergeyIvanov14** [iTXTech/Genisys#2230]
Hello, I have a bug with FloatingTextParticle.

When I create first text he appaer when I create second text first text disappear, what is problem? I use many versions of Genisys but don't work:( and I use many codes to create a text but bug not disappear.

          public function onText(PlayerInteractEvent $e){
            $p = $e->getPlayer();
              if($e->getItem()->getId() == 264){
                $this->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(128, 5 + 2, 128), "", "text"), [$e->getPlayer()]);
                $this->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(128, 5 + 1.75, 128), "", "text2"), [$e->getPlayer()]);
                $this->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(128, 5 + 1.50, 128), "", "text3"), [$e->getPlayer()]);
                      }
          }

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**Comment by SergeyIvanov14** [comment]
Here is video with bug.
[mobizen_20161120_180910.mp4.zip](https://github.com/iTXTech/Genisys/files/604906/mobizen_20161120_180910.mp4.zip)

**Comment by SergeyIvanov14** [comment]
His bun is only in 0.16
