### ISSUE TITLE
hungry not correct work

### ISSUE THREAD

**Issue by Andrew1481432** [iTXTech/Genisys#2233]
Hunger stopped working in version 0.16.0

**Comment by dktapps** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by TacosYum** [comment]
Just used this on 4a61667 and hunger is not working
