### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by VCraftMCPE** [iTXTech/Genisys#2234]
#### Issue description
commands auth bypass ./

#### Steps to reproduce the issue
add an auth plugin then join and do ./op and u will have access to it

#### OS and versions
* Genisys: f7104d6
* PHP:7
* Server OS:Window server
* Game version: 16.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by laurobeleche** [comment]
If you use a plugin to restrict the permissions of the players, this problem will not occur, but soon a solution to this problem will be given.

**Comment by Infernus102** [comment]
doesn't work @laurobeleche

**Comment by Infernus102** [comment]
Use PlayerCommandPreprocess Event

**Comment by Infernus102** [comment]
This code works! YESSS!!

**Comment by dktapps** [comment]
https://github.com/iTXTech/Genisys/commit/9548ebb4cc362affd876a6fea7ed2e6a3bc2ab7d
