### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by IrishPacks** [iTXTech/Genisys#2235]
#### Issue description
Here is the simplest way to put it. When cancelling health events, it works server side but the player is still receiving SetHealthPackets(I'm assuming),  because they show the correct health via plugins that get health, but on their screens they continue to regenerate.

[EDIT] I was informed it wasn't SetHealthPacket, but could it be UpdateAttributesPacket?

#### Steps to reproduce the issue

Cancel EntityRegainHealthEvent and use a way to see your server side health. You'll notice that they aren't the same.

#### OS and versions

* Genisys: 478c3d4
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheAppleGamer** [comment]
It's a weird thing with the health, but the health doesn't actually regen, it's just displayed like that to the client, but use a hud with health displayed in it and it shows your actual health

**Comment by JackNoordhuis** [comment]
Going to close this issue here to keep the issue tracker clear as this issue has been opened over at [PMMP/#23](https://github.com/pmmp/PocketMine-MP/issues/23). Please continue any discussion over there.
