### ISSUE TITLE
pthreads extension

### ISSUE THREAD

**Issue by TristonStuart** [iTXTech/Genisys#2240]
#### Issue description
Hello, when I run  '$ ./start.sh/' I get The following error:

php is /usr/local/opt/php70/bin/php
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage. 

#### Steps to reproduce the issue
This is how I installed and ran this : 
1.) Went to https://github.com/iTXTech/Genisys and downloaded the master branch as a .zip
2.) Extracted the file to a folder called 'MC PE Server'
3.) Opened terminal and typed 'cd (The location of the folder here)'
4.) Then typed './start.sh'

And now I get this error.

#### OS and versions

* Genisys: 11/26/16 Masterbranch Download
* PHP: 7
* Server OS: Mac osx
* Game version: 0.16.2

### Note :
If there is a better way to install Genisys for mac please tell me!

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by TristonStuart** [comment]
And i dont see how this should be closed, could have just said : 'Dont download the main thing download the .phar and rename it to PocketMine-MP.phar then put it into the pocketmine folder.'
