### ISSUE TITLE
Server's MOTD is not shown in MC: PE (0.16)

### ISSUE THREAD

**Issue by SuperPuperSteve** [iTXTech/Genisys#2241]
#### Issue description

Server's MOTD is not shown in client.
#### Steps to reproduce the issue

1. Start your server
2. Add your server to client's server list
3. Wait a while. You won't see MOTD
#### OS and versions

* Genisys: 82ef5d6
* PHP: 7.0.6
* Server OS: Ubuntu 14.04.5 LTS
* Game version: Minecraft PE v0.16.0.5 alpha (protocol version 91)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
it's impossible
```

**Comment by File14** [comment]
This is not fixable, it's the client side. Ask Mojang :)

**Comment by ishitatsuyuki** [comment]
#blamemojang
