### ISSUE TITLE
Synapse: mcpe crash

### ISSUE THREAD

**Issue by TheBluePinguin1** [iTXTech/Genisys#2247]
#### Issue description

Hello,

if you join with a client the minecraft from that client will crash

#### Steps to reproduce the issue

use nemisys on windows 
idk if it works with other server softwares

#### OS and versions

* Genisys: 2939405
* PHP:7.0.12
* Server OS: Windows Vista
* Game version: Minecraft PE v0.16.2 on Ipad Air 2
* Nemisys: c0000f8 (latest)
* SynapsePM: 1.0.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
no crash dump
```

**Comment by dktapps** [comment]
Open an issue on SynapsePM repo.

**Comment by TheBluePinguin1** [comment]
ok im sorry
