### ISSUE TITLE
Server sometimes crashes

### ISSUE THREAD

**Issue by Akuroma** [iTXTech/Genisys#2248]
#### Issue description
Apparently there issues with brewingstands, droppers, hoppers, etc... . Sometimes the server crashes. Maybe it can't handle the unloading of chunks. As you can see in the crashdump below, the item which causes the issue is the brewing stand. The same issue is happening with droppers, hoppers and so on.
Hope you can fix this.

#### OS and versions

* Genisys: Genisys-efdea79 (Codename "Kyrios")
* PHP: 2.1.0 (iTX API Version 1.9.3)
* Server OS: Linux, linux
* Game version: 0.16.1 (latest version + Windows 10) 

#### Crashdump, backtrace, memory dumps, plugins list or other files

Genisys Crash Dump Wed Nov 30 16:35:09 CET 2016

Error: Call to undefined method pocketmine\nbt\NBT::putItemHelper()
File: /src/pocketmine/tile/BrewingStand
Line: 168
Type: notice

Code:
[159] 	 *
[160] 	 * @param int  $index
[161] 	 * @param Item $item
[162] 	 *
[163] 	 * @return bool
[164] 	 */
[165] 	public function setItem($index, Item $item){
[166] 		$i = $this->getSlotIndex($index);
[167] 
[168] 		$d = NBT::putItemHelper($item, $index);
[169] 
[170] 		if($item->getId() === Item::AIR or $item->getCount() <= 0){
[171] 			if($i >= 0){
[172] 				unset($this->namedtag->Items[$i]);
[173] 			}
[174] 		}elseif($i < 0){
[175] 			for($i = 0; $i <= $this->getSize(); ++$i){
[176] 				if(!isset($this->namedtag->Items[$i])){
[177] 					break;
[178] 				}

Backtrace:
#0 /src/pocketmine/level/format/mcregion/Chunk(401): pocketmine\tile\BrewingStand->saveNBT(boolean)
#1 /src/pocketmine/level/format/mcregion/RegionLoader(168): pocketmine\level\format\mcregion\Chunk->toBinary(boolean)
#2 /src/pocketmine/level/format/mcregion/McRegion(240): pocketmine\level\format\mcregion\RegionLoader->writeChunk(pocketmine\level\format\mcregion\Chunk object)
#3 /src/pocketmine/level/Level(1113): pocketmine\level\format\mcregion\McRegion->saveChunk(integer -1, integer 27)
#4 /src/pocketmine/level/Level(1101): pocketmine\level\Level->saveChunks(boolean)
#5 /src/pocketmine/Server(2618): pocketmine\level\Level->save(boolean )
#6 /src/pocketmine/Server(2793): pocketmine\Server->doAutoSave(boolean)
#7 /src/pocketmine/Server(2466): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2344): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1934): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/genisys.phar/, string /home/minecraft/multicraft/servers/server1102/, string /home/minecraft/multicraft/servers/server1102/plugins/, string unknown)
#11 (1): require_once(string phar:///home/minecraft/multicraft/jar/genisys.phar/src/pocketmine/PocketMine.php)

Genisys version: efdea79a29cdcdbd40a3ff92db3763686b07addf [Protocol 91; API 2.1.0]
uname -a: Linux mc5.hk-hosting.de 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 15 Minuten 4 Sekunden
Number of loaded worlds: 19
Players online: 2/50

Loaded plugins:
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
Friends 1 by Bluplayz for API(s) 1.14.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
BadWordBlocker 1.0.0 by SURVA.ml Dev Team for API(s) 1.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
MicroBattles 2.3.0 by KaitoDoDo+LittleBigMC for API(s) 1.0.0, 2.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
BlockSniffer 1.0.0 by DRedDogPE for API(s) 1.12.0
JoinMessage 0.3 by  for API(s) 1.13.0, 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
iManager 1.1.0 by Gamecrafter for API(s) 1.10.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldGM 1.0.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
JoinQuit 1 by Akuroma for API(s) 2.0.0
TNTRun 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
Pets 1.0.0 by Driesboy, BalAnce, LifeBoat Stolen Core for API(s) 1.12.0
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
GlobalBan 1.0 by LazzKiller for API(s) 2.0.0, 1.13.0, 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
MagicCore 1.0.0 by Aku for API(s) 2.0.0
BanSystem 1.0.2.1 by xXSuperFrostyXx, randy128gamer, Aku for API(s) 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0
superBAR 1.6.1 by FaigerSYS for API(s) 2.0.0
RankPoints 1.4 by JD for API(s) 2.0.0
EconomyLand 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
TheDropper 1.0.0 by  for API(s) 1.1.0
Worlds 1.0.3 by jjplaying for API(s) 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
HotBlock 1.0.0 by jjmc for API(s) 1.0.0
Report 1.0.1 by Bluplayz for API(s) 1.14.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
WorldEdit+ 0.01 by える for API(s) 2.0.0
EconomyProperty 2.0.6 by onebone for API(s) 2.0.0
SimpleWarp 2.1.1 by Falkirks for API(s) 1.12.0, 2.0.0
SimplePortals 0.0.5 by Falkirks for API(s) 1.10.0, 2.0.0Genisys Crash Dump Wed Nov 30 16:35:09 CET 2016

Error: Call to undefined method pocketmine\nbt\NBT::putItemHelper()
File: /src/pocketmine/tile/BrewingStand
Line: 168
Type: notice

Code:
[159] 	 *
[160] 	 * @param int  $index
[161] 	 * @param Item $item
[162] 	 *
[163] 	 * @return bool
[164] 	 */
[165] 	public function setItem($index, Item $item){
[166] 		$i = $this->getSlotIndex($index);
[167] 
[168] 		$d = NBT::putItemHelper($item, $index);
[169] 
[170] 		if($item->getId() === Item::AIR or $item->getCount() <= 0){
[171] 			if($i >= 0){
[172] 				unset($this->namedtag->Items[$i]);
[173] 			}
[174] 		}elseif($i < 0){
[175] 			for($i = 0; $i <= $this->getSize(); ++$i){
[176] 				if(!isset($this->namedtag->Items[$i])){
[177] 					break;
[178] 				}

Backtrace:
#0 /src/pocketmine/level/format/mcregion/Chunk(401): pocketmine\tile\BrewingStand->saveNBT(boolean)
#1 /src/pocketmine/level/format/mcregion/RegionLoader(168): pocketmine\level\format\mcregion\Chunk->toBinary(boolean)
#2 /src/pocketmine/level/format/mcregion/McRegion(240): pocketmine\level\format\mcregion\RegionLoader->writeChunk(pocketmine\level\format\mcregion\Chunk object)
#3 /src/pocketmine/level/Level(1113): pocketmine\level\format\mcregion\McRegion->saveChunk(integer -1, integer 27)
#4 /src/pocketmine/level/Level(1101): pocketmine\level\Level->saveChunks(boolean)
#5 /src/pocketmine/Server(2618): pocketmine\level\Level->save(boolean )
#6 /src/pocketmine/Server(2793): pocketmine\Server->doAutoSave(boolean)
#7 /src/pocketmine/Server(2466): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2344): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1934): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/genisys.phar/, string /home/minecraft/multicraft/servers/server1102/, string /home/minecraft/multicraft/servers/server1102/plugins/, string unknown)
#11 (1): require_once(string phar:///home/minecraft/multicraft/jar/genisys.phar/src/pocketmine/PocketMine.php)

Genisys version: efdea79a29cdcdbd40a3ff92db3763686b07addf [Protocol 91; API 2.1.0]
uname -a: Linux mc5.hk-hosting.de 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 15 Minuten 4 Sekunden
Number of loaded worlds: 19
Players online: 2/50

Loaded plugins:
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
Friends 1 by Bluplayz for API(s) 1.14.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
BadWordBlocker 1.0.0 by SURVA.ml Dev Team for API(s) 1.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
MicroBattles 2.3.0 by KaitoDoDo+LittleBigMC for API(s) 1.0.0, 2.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
BlockSniffer 1.0.0 by DRedDogPE for API(s) 1.12.0
JoinMessage 0.3 by  for API(s) 1.13.0, 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
iManager 1.1.0 by Gamecrafter for API(s) 1.10.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldGM 1.0.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
JoinQuit 1 by Akuroma for API(s) 2.0.0
TNTRun 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
Pets 1.0.0 by Driesboy, BalAnce, LifeBoat Stolen Core for API(s) 1.12.0
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
GlobalBan 1.0 by LazzKiller for API(s) 2.0.0, 1.13.0, 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
MagicCore 1.0.0 by Aku for API(s) 2.0.0
BanSystem 1.0.2.1 by xXSuperFrostyXx, randy128gamer, Aku for API(s) 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0
superBAR 1.6.1 by FaigerSYS for API(s) 2.0.0
RankPoints 1.4 by JD for API(s) 2.0.0
EconomyLand 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
TheDropper 1.0.0 by  for API(s) 1.1.0
Worlds 1.0.3 by jjplaying for API(s) 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
HotBlock 1.0.0 by jjmc for API(s) 1.0.0
Report 1.0.1 by Bluplayz for API(s) 1.14.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
WorldEdit+ 0.01 by える for API(s) 2.0.0
EconomyProperty 2.0.6 by onebone for API(s) 2.0.0
SimpleWarp 2.1.1 by Falkirks for API(s) 1.12.0, 2.0.0
SimplePortals 0.0.5 by Falkirks for API(s) 1.10.0, 2.0.0

**Comment by dktapps** [comment]
Outdated version.

**Comment by Akuroma** [comment]
I'm hosting my server with HK-Hosting (hk-hosting.de). If this would help you. I can't just change the server jar. Please could you contact the team of HK-HOSTING and send them the bewest Genisys-Version?

**Comment by dktapps** [comment]
This is your problem, contact them yourself.

**Comment by Akuroma** [comment]
I already did and they said that I should contact you.
