### ISSUE TITLE
Enchantment Tables/Anvils don't work Plz fix

### ISSUE THREAD

**Issue by DoctorClarke** [iTXTech/Genisys#2249]
**Issue description**
So basically, whenever i try to enchant something in the enchantment table, the item that is being enchanted glitches out and doesn't enchant. Secondly I cannot repair or rename things on anvils as the items glitch out of the anvil as well. 
**OS and versions**

Genisys:  c8645899
PHP: 7.0.3
Server OS: Windows 10, Pocket Edition
Game version: 0.16.2

**Comment by Muqsit** [comment]
See open issues

**Comment by dktapps** [comment]
And don't say "plz fix", it's very irritating.
