### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by CubeFromSpace** [iTXTech/Genisys#2250]
#### Issue description

There are a lot of missing ID values in the code, both for current and upcoming versions.
#### Steps to reproduce the issue

Look at the code.
#### OS and versions

* Genisys: latest dev build possible
* PHP: 7
* Server OS: latest
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
