### ISSUE TITLE
Why are not the Synapse settings in the genisys.yml?

### ISSUE THREAD

**Issue by Henning-Klatt** [iTXTech/Genisys#2251]
I miss the following settings in the genisys.yml:

`synapse:
 enabled: true
 server-ip: 127.0.0.1
 server-port: 10305
 is-main-server: true
 server-password: password
 description: "1"
 disable-rak: false`

Is there a reason why they are missing?

**Comment by erkam2002** [comment]
Lexodexo XD benutz das : -> https://github.com/iTXTech/SynapsePM 
Es wurde von Genisys entfernt aber man kann es per plugin usen
