### ISSUE TITLE
Snow Bug

### ISSUE THREAD

**Issue by BeynerGames127** [iTXTech/Genisys#2255]
When snow falls and you remove it and then when you restart the server reappears on the whole map
:( 

Genisys:  a9f5b8fe
PHP: 7
Server OS: Windows
Game version: v0.16.0 alpha

**Comment by BeynerGames127** [comment]
Also In Old Versions

**Comment by kabluinc** [comment]
Go to one corner of the affected map and do /biome pos1 then go to opposite corner and do /biome pos 2 then do /biome set 1. /save-all, restart your server. Problem solved

**Comment by poustmal** [comment]
You can rejoin to your server and will see the snow.For me that works.

**Comment by poustmal** [comment]
you will see,I wrote it wrong

**Comment by BeynerGames127** [comment]
And Why I Cant Get The Snow Balls? xD
By Destroying Snow With Shovel
Its That A Bug Too?? xD

**Comment by dktapps** [comment]
This is a client issue.
