### ISSUE TITLE
Cannot open chests

### ISSUE THREAD

**Issue by trekinsanity** [iTXTech/Genisys#2256]
#### Issue description
Can't open chests in survival. The only people that can are opped (in survival or creative).

#### Steps to reproduce the issue
Click on a chest - it does nothing (in survival).

#### OS and versions

* Genisys: Kyrios
* PHP: 7.0.3
* Server OS: Mac OS 10.11.6
* Game version: PE 0.16.05 alpha (protocol version 91)

#### Crashdump, backtrace, memory dumps, plugins list or other files
No plugins.

I did try to set limited-creative from true to false but no change.

**Comment by kabluinc** [comment]
Probably those chests are in the spawn protection radius or the areas protected by some plugin? Chests work fine for us

**Comment by trekinsanity** [comment]
You are correct. Thank you so much!
