### ISSUE TITLE
How can i make snow weather in my server? (QUESTION)

### ISSUE THREAD

**Issue by Rectex** [iTXTech/Genisys#2257]
#### Issue description

How i can make snow in my server? :P

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by JackNoordhuis** [comment]
This is not a forum for you to ask questions on. Please use the issues section for issues only.

**Comment by poustmal** [comment]
Tap /biome pos1 to set the first position,then /biome pos2 for second position and /biome set 1 for snow.After you do this,rejoin your world,tap /weather rain and snow!
