### ISSUE TITLE
When I shifted to other world players, the players going back in that jerky move that point where I was standing. At that point the player must wait about 15 seconds is not jerky and lag phenomenon. Please explain to me and the fix on.

### ISSUE THREAD

**Issue by vuahackervn** [iTXTech/Genisys#2259]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Aericio** [comment]
Did you forget what "title" means and mistake it for "description"?
