### ISSUE TITLE
When the memory exceeds 1GB, it shows overload

### ISSUE THREAD

**Issue by silence8620** [iTXTech/Genisys#226]
When the server RAM more than 1GB, it shows ：can't keep up! is the server overloaded? 
the server machine configuration is very high, how to let him do not need to restart ?

**Comment by silence8620** [comment]
中文：
当服务器运行内存超过1GB左右时，服务器会显示Warning：Can't keep up！Is the server overloded？
机器的配置比较高，8GB的RAM，16核内存。
如何让他一直保持运行而不需要重启服务器？5人进入游戏时，基本1个小时就超载了。

**Comment by PocketKiller** [comment]
not sure of this.

**Comment by silence8620** [comment]
@PocketKiller 没有什么好的解决方法吗？只能定时重启？

**Comment by silence8620** [comment]
基本超过986MB时，就会显示超载，而5人登录时基本不到1个小时就超过1G了

**Comment by PocketKiller** [comment]
I don't understand Chinese, so I dropped it on a translator ;)
Memory Leak

**Comment by silence8620** [comment]
i'm sorry,i means，The ram on the server after more than 986MB-RAM will show overload warning, how to let the server running better, that is to say, can put my ram full use, make the Server can run to 8GB of RAM, after that, I needn't  each hour to restart the server, the server machine configuration has very high up.

**Comment by silence8620** [comment]
My server host memory has 8GB, but Pocketmine can only use 1G then it will overload

**Comment by silence8620** [comment]
@PocketKiller Do you have a good solution？thank you！

**Comment by PocketKiller** [comment]
I've got no solution, I think this is a Memory Leak.

**Comment by silence8620** [comment]
@PocketKiller Is every Pocketmine server this way? But memory is not run out！

**Comment by silence8620** [comment]
When he shows the overloaded , the host has 6GB memory is not used.

**Comment by PocketKiller** [comment]
I'll try to make my test server reach 1G, I'll see

**Comment by silence8620** [comment]
@PocketKiller thank you very much，please。

**Comment by silence8620** [comment]
You said there may be a server software configuration problem？ that is, my server does not have the corresponding procedures to reduce the memory? Your server running for a long time, the memory will not be very high？

**Comment by gaoyichuan** [comment]
@silence8620 I haven't got my server's memory to run over 1GB, with a uptime of over 24h. Maybe you can try a plugin such as Automatic Server Restarter to restart your server in a given time period.

**Comment by gaoyichuan** [comment]
Oh, I got the overload message, I will take out more experiments

**Comment by PeratX** [comment]
@silence8620 Try the latest version. Probably fixed Memory Leak

**Comment by GalvinGao** [comment]
Yeah and try to edit line 31, 35, 39 at pocketmine.yml

**Comment by gaoyichuan** [comment]
@PeratX I'm using the latest version, but it didn't fix the memory.

**Comment by silence8620** [comment]
@gaoyichuan That plugin in my server can not run, because once executed, it will show exit bin/php 255

**Comment by silence8620** [comment]
@PocketKiller I tried to install the 64 bit version, but using both Genisys and ImagicalMine is a function error.And then quit.
It shows：
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in phar://E:/Pocketmine-MP.phar/src/spl/ThreadedFactory.php on line 52
bin\php\php.exe: Exit 255

**Comment by silence8620** [comment]
@gaoyichuan Can you give me your server to try it？ only need the main program, thank you. 943954552@qq.com

**Comment by gaoyichuan** [comment]
@silence8620 Just clone the project repo and run the start.sh

**Comment by silence8620** [comment]
@gaoyichuan my server running in  Windows ,not Linux

**Comment by CrayonDing** [comment]
@silence8620 Why don't you try Linux.Maybe it will fix this problem

**Comment by Efforto** [comment]
nononono
试试新版Genisys也许可以，但是最好检查一下插件23333

**Comment by Efforto** [comment]
pocketmine.yml修改一下2333

**Comment by jasonczc** [comment]
1.check一下pocketmine.yml以及配置文件中的内存设置.线程数/chunksend/etc.请自行更改.
2.矿车/生物AI等实体会占用大量资源,没有必要关掉即可.
3.Genisys的Overload提示是根据tps来计算的,RAM占用与LOAD/TPS/OverLoad提示没有任何关系
4.PHP能有效利用的核心数很少,你的机器所谓的"配置高"只是核数多,单核性能目测很差,也就是说,假设你用x5565/16h的U,开服效果也许不如四核E5/E7,所以切勿把对于PHP的性能与CPU核心数混为一谈.
5.尝试精简插件.自行进行优化.
最后:如果你用的面板,趁早换吧.

**Comment by silence8620** [comment]
@jasonczc pocketmine.yml里面只有max-chunk设置。请问大神如何修改？
AI现在都还不能动呢……矿车也会出bug，都没有开启。
我用的就是传统的start.cmd开服，不是面板服。

**Comment by silence8620** [comment]
试试新的设置，我找到了，谢谢

**Comment by GalvinGao** [comment]
Issue solved by **user**. Closing issue.

**Comment by Bidou0418** [comment]
What was the solution?
I have the same problem
