### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by ParkChanSol** [iTXTech/Genisys#2260]
#### Issue description

Namespace declaration statement
#### Steps to reproduce the issue

I excute my plugin. and, stop server because plugin.
but, I can't solve this error.
#### OS and versions

* Genisys: a9f5b8f
* PHP: 7.0.11
* Server OS:Windows 7 Ultimate Edition Service Pack 1
* Game version: 0.16.0.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
[CrashDump_Thu_Dec_8-21.38.25-AWST_2016.txt](https://github.com/iTXTech/Genisys/files/639540/CrashDump_Thu_Dec_8-21.38.25-AWST_2016.txt)

**Comment by dktapps** [comment]
This is not a support forum.
