### ISSUE TITLE
BrewingStand error?

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#2264]
#### Issue description

PLace brewingstand error
#### Steps to reproduce the issue

Place brewingstand wait stop server and see error
#### OS and versions

* Genisys: newest
* PHP: 7.0.13
* Server OS: Debian 8 Linux
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\nbt\NBT::putItemHelper()" (EXCEPTION) in "/src/pocketmine/tile/BrewingStand" at line 168
[Server thread/EMERGENCY]: Crashed while crashing, killing process
```

**Comment by dktapps** [comment]
"Newest" is not a valid version. And this isn't newest, this bug was fixed days ago. Thanks for wasting our time.
