### ISSUE TITLE
Out of memory exception during teleportations. 

### ISSUE THREAD

**Issue by willotheblessed** [iTXTech/Genisys#2266]
#### Issue description
Getting errors reported for out of memory while teleporting player around map (using algorithm). It is a relatively small map. Here are my teleport locations:

  xPos: 67.949562
  yPos: 66.413264
  zPos: 39.785423
---------------
  xPos: 32.704216
  yPos: 76.163257
  zPos: 3.900910
---------------
  xPos: 86.962662
  yPos: 78.000000
  zPos: -52.299995
-----------------
  xPos: 52.604340
  yPos: 75.871600
  zPos: 54.472023
-----------------
  xPos: 78.045006
  yPos: 76.288272
  zPos: -35.730122
------------------
  xPos: 64.778595
  yPos: 114.119334
  zPos: -48.826584

Any given location can have memory issues. This was not an issue in past versions, but as of early November, and in current builds, it remains an issue.

#### Steps to reproduce the issue
Teleporting player around a small map using an algorithm which teleports every 5-10 seconds.

#### OS and versions
"Kyrios"
PHP version: 7.0.11
API: 2.1.0 (iTX API version 1.9.3)
Target client: Minecraft PE v0.16.0.5 alpha (protocol version 91)
Server OS: Windows
Game Version: 0.16.2, Windows 10 Edition

#### Crashdump, backtrace, memory dumps, plugins list or other files
Fatal error: Out of memory (allocated 10485760) (tried to allocate 65536 bytes) in \\src\pocketmine\network\CompressBatchedTask.php on line 43
[12:40:15] [Server thread/CRITICAL]: Could not execute asynchronous task CompressBatchedTask: Task crashed

**Comment by dktapps** [comment]
Do you have serialized chunk caching enabled?

**Comment by PragaKart67z** [comment]
I have the same exact issue. Whenever I tp to a chunk that is unloaded I crash. I am using the same OS and Versions

**Comment by willotheblessed** [comment]
Turning off serialized chunk caching seems to alleviate the issue.

**Comment by dktapps** [comment]
I believe b9e93d696cbf3e37339cd67bc1c46404ce47e2c3 should have fixed this issue, if the issue still occurs after updating please open a new issue.
