### ISSUE TITLE
Enchantment table does not work

### ISSUE THREAD

**Issue by TacosYum** [iTXTech/Genisys#2267]
#### Issue description
 Enchantment table spits stuff out and does not enchant when you try to enchant

#### Steps to reproduce the issue
Try enchanting

#### OS and versions

* Genisys: 6938a48
* PHP: php7
* Server OS: Ubuntu 14
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files
 Its clean  
```
```

**Comment by Muqsit** [comment]
PLEASE read the closed issues. Like seriously! There are more than 10 closed issues addressing the same issue.
