### ISSUE TITLE
Player Experience Functions

### ISSUE THREAD

**Issue by Infernus102** [iTXTech/Genisys#2268]
#### Issue description
Experience functions like getTotalXp(), addXp(), setTotalXp() etc. not working properly....

#### Steps to reproduce the issue
Send negative value in addXp()

#### OS and versions

* Genisys:  55ae11e 
* PHP: 7.0.10
* Server OS: Ubuntu
* Game version: Minecraft PE v0.16.0.5 alpha (protocol version 91)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
No Crashdump
```

**Comment by JackNoordhuis** [comment]
Why are you passing a negative value to Human::addXp() in the first place? Human::takeXp() should work just fine in this situation.

**Comment by Infernus102** [comment]
getTotalXp() doesn't work either.

**Comment by Muqsit** [comment]
Negative value for addXp() is working for me. And so is getTotalXp(), setTotalXp() etc.
Try with  ```php ($player instanceof Human)```

**Comment by Infernus102** [comment]
Muqsit aren't you using Elywing?

**Comment by Muqsit** [comment]
Genisys.
