### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by poustmal** [iTXTech/Genisys#2271]
Genisys Crash Dump Fri Dec 16 13:29:57 EET 2016

Error: assert(): Still 3031 bytes unread! failed
File: /src/pocketmine/network/RakLibInterface
Line: 140
Type: E_WARNING

Code:
[131] 	}
[132] 
[133] 	public function handleEncapsulated($identifier, EncapsulatedPacket $packet, $flags){
[134] 		if(isset($this->players[$identifier])){
[135] 			try{
[136] 				if($packet->buffer !== ""){
[137] 					$pk = $this->getPacket($packet->buffer);
[138] 					if($pk !== null){
[139] 						$pk->decode();
[140] 						assert($pk->feof(), "Still " . strlen(substr($pk->buffer, $pk->offset)) . " bytes unread!");
[141] 						$this->players[$identifier]->handleDataPacket($pk);
[142] 					}
[143] 				}
[144] 			}catch(\Throwable $e){
[145] 				$logger = $this->server->getLogger();
[146] 				if(\pocketmine\DEBUG > 1 and isset($pk)){
[147] 					$logger->debug("Exception in packet " . get_class($pk) . " 0x" . bin2hex($packet->buffer));
[148] 				}
[149] 				$logger->logException($e);
[150] 			}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: a9f5b8fe556eb9bf80d48ff7f2b45e446a960518 [Protocol 91; API 2.1.0]
uname -a: Linux localhost 3.4.5 #1 SMP PREEMPT Tue Dec 3 15:37:57 CST 2013 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 5 hours 20 minutes 13 seconds
Number of loaded worlds: 11
Players online: 0/10

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
DevTools 1.1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FChestReset 1.0.0(English) by FENGberd for API(s) 1.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
WorldGM 1.0.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SW_svile 0.6dev by svile for API(s) 1.13.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 2.0.0
FolderPluginLoader 1.1.0 by  for API(s) 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
xyz 1.0.1 by unerds for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
SpawnWithItems 2.1 by LDX for API(s) 1.1.0, 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0
PurePerms 1.3.7-patch1 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
Slapper 1.3.1 by jojoe77777 for API(s) 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
MagicWE 0.2.7 by thebigsmileXD for API(s) 1.13.0, 2.0.0
SkyBlock 1.5.6 by  for API(s) 1.12.0

**Comment by poustmal** [comment]
What does this mean?

**Comment by dktapps** [comment]
Disable assertions on a production server. That's a **debug** assertion failure due to an outdated client attempting to join the server.

In your php.ini, set `zend.assertions` to -1.
