### ISSUE TITLE
Could not tick level 'world'!

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#2272]
#### Issue description
Console spam issue. Happens randomly when spawning mobs.

#### Steps to reproduce the issue
[Unknown, as of now.]

#### OS and versions

* Genisys: 5afd2c1
* PHP: 7.0.14
* Server OS: Ubuntu 14.04 LTS (64-bit)
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Could not tick level "world": Call to a member function spawnToAll() on null.
```

**Comment by JackNoordhuis** [comment]
Could you please set the debug level to 2 in pocketmine.yml and post the backtrace here? It'd also be helpful if you could provide some way to replicate the issue, if we don't know anything about the problem we can't find find the cause and therefore can't fix it.

**Comment by dktapps** [comment]
Closing due to lack of response.
