### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by LewBr** [iTXTech/Genisys#2274]
#### Issue description
Undefined Offset

#### Steps to reproduce the issue
When i try to make a PlayerCommandPreProcessEvent, its all Ok its works... but on my Painel i have the a little error, and i dont want this spam message on my Server!

#### OS and versions

* Genisys: 2.1.0 (iTX API version 1.9.3)
* PHP: 7.0.8
* Server OS: Linux
* Game version: 0.16.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
error: 16.12 12:53:11 [Server] INFO Notice: Uninitialized string offset: 0 in /plugins/PG-Core-P/src/pg/main.php on line 609

Code Line:  if ($command{0} == '/') {
Sorry English
```

**Comment by dktapps** [comment]
This is not a support forum.

**Comment by LewBr** [comment]
wtf.. but help me.. lol

**Comment by dktapps** [comment]
# This is not a support forum.

did you read?
