### ISSUE TITLE
for() can not use

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#2275]
插件中执行for语句的时候程序会跳过这段并且有时候会导致服务器无响应
我改用while循环就ok

Use for() in plugin can not succeed. Some time happen to stop answer. And no err report.
when i use while() anything is turn back.

Genisys version: 6938a483f0aa61263dc20139cc5e17fa9c3813c0 [Protocol 91; API 2.1.0]
uname -a: Linux izydapw1hh4929z 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

**Comment by CrayonDing** [comment]
检查代码和服务器配置
