### ISSUE TITLE
Starting multiple servers causes issue

### ISSUE THREAD

**Issue by remotevase** [iTXTech/Genisys#2277]
#### Issue description

When I start 4 servers at one on the machine, I get an error. Yes, they are on different ports. I am trying to set up synapse (Speaking of which, someone please look at @Itxtech/synapse#26)
Note: Some 2 of the 4 servers start, the other 2 get the error message below. It goes 
server 1: Success
Server 2: fail
server 3: success
server 4: fail

The only way that I have found to fix this issue is to replace the bin folder every time. Sorry!
#### OS and versions

* Genisys: 
``` batch
[19:43:59] [Server thread/INFO]: -----Server information-----
[19:43:59] [Server thread/INFO]: This server is running Genisys (codename "Kyrios")
[19:43:59] [Server thread/INFO]: PHP version: 7.0.2
[19:43:59] [Server thread/INFO]: API: 2.1.0 (iTX API version 1.9.3)
[19:43:59] [Server thread/INFO]: Target client: Minecraft PE v0.16.0.5 alpha (protocol version 91)
```
* Server OS: Running on windows 7 with 2 cores, 16 gb ram, 4x500 max IOPS, 20gb ssd, running on MEGA (mega.co.nz)
* Game version: Not Revelant to the issue

#### Crashdump, backtrace, memory dumps, plugins list or other files

``` batch
Sat Dec 17 19:47:11 2016 (3608): Fatal Error Base address marks unusable memory region
bin\php\php.exe: Exit 127
```

**Comment by intagaming** [comment]
Have you try turning off opcache.enable_cli in php.ini?

**Comment by remotevase** [comment]
Going to try that... Thanks...

**Comment by remotevase** [comment]
THANKS SO MUCH!
