### ISSUE TITLE
Issue on Sign

### ISSUE THREAD

**Issue by FunnyBuddys** [iTXTech/Genisys#2278]
#### Issue description

Signs are buggy and with game plugins caused laggs and will become invisible

#### Steps to reproduce the issue

Make a sign with a plugin who changing if clicking on it

#### OS and versions

* Genisys:
* PHP: 7
* Server OS: Debian 7
* Game version: 0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by FunnyBuddys** [comment]
Thanks for (no) help!

**Comment by dktapps** [comment]
This is not a support forum, we aren't here to help you with **your** plugin issues.
