### ISSUE TITLE
zlib decode error

### ISSUE THREAD

**Issue by Infernus102** [iTXTech/Genisys#2280]
#### Issue description

This error showed up in console from nowhere
"Warning: zlib_decode(): data error in genisys/0.16/Genisys.0.16.0.phar/src/pocketmine/network/Network.php on line 234"
#### Steps to reproduce the issue

Unknown
#### OS and versions

* Genisys: 55ae11e
* PHP: 7.0.10
* Server OS: Ubuntu
* Game version: Minecraft PE v0.16.0.5 alpha (protocol version 91)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by dktapps** [comment]
Outdated version. 

This usually occurs when a 0.15 client attempted to join and the error-detection failed. This can't be fixed due to Mojang stupidity in 0.15 with batching loginpackets.
