### ISSUE TITLE
Genisys pocketmine 1.0

### ISSUE THREAD

**Issue by poustmal** [iTXTech/Genisys#2283]
Mojang released 1.0,genisys will be ready to update soon?

**Comment by poustmal** [comment]
Here's the changelog

**Comment by Muqsit** [comment]
Uh. You need not tell us that, we are already aware of it.

**Comment by poustmal** [comment]
Ok

**Comment by dktapps** [comment]
@Muqsit You're nicer than I am, I usually just give a ban because they didn't read the issue template... ¯\_(ツ)_/¯

**Comment by poustmal** [comment]
I don't want a ban,but I want to be sure if 1.0 will be problematic,because I have already crashes in my server.

**Comment by FunnyBuddys** [comment]
@poustmal You can wait 1-2 Weeks for 1.0 Support from Genisys :). Lots of people want to update 1.0 but its isn't easy and yes...

**Comment by bluefurrymonster** [comment]
@FunnyBuddys, @Muqsit  and all contributors, I just want to thank you all for this wonderful product that my kids are enjoying with. I risk being ban but my kids want to say a BIG THANK YOU!

**Comment by Muqsit** [comment]
@bluefurrymonster 
Thank @dktapps. Without him, this project would be dead 2 months ago.

**Comment by bluefurrymonster** [comment]
@dktapps Thank you! You made a difference in at least 3 children's lives!

**Comment by poustmal** [comment]
If you just change the protocol to 100,it will not be ok for 1.0 update?
