### ISSUE TITLE
1.0 Support Please

### ISSUE THREAD

**Issue by SinlesFlyer376** [iTXTech/Genisys#2284]
Please add support for 1.0 pocket edition

**Comment by JackNoordhuis** [comment]
Spam.

**Comment by SinlesFlyer376** [comment]
Spam? I said 6 words two numbers and a period...

**Comment by SinlesFlyer376** [comment]
Spam is if I did the same word over and over, And I never stop

**Comment by gaoyichuan** [comment]
Banned, look the contribution guideline
