### ISSUE TITLE
Can You Update to mcpe 1.0?

### ISSUE THREAD

**Issue by LordTheFeak** [iTXTech/Genisys#2285]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by FunnyBuddys** [comment]
Bump to 1.0.0 on PocketMine.php and Info.php

**Comment by ishitatsuyuki** [comment]
Can you shut up?

**Comment by dktapps** [comment]
Wow, so much spam!
