### ISSUE TITLE
0.13.2 is out for iOS

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#229]
0.13.2 is out for ios is it already out for android if so could you might edit the thingy thats says that the server is 0.13.1?

**Comment by PocketKiller** [comment]
0.13.2 is bugged when you open the game it crashes.

**Comment by thebigsmileXD** [comment]
@PocketKiller no crashes so far xD

**Comment by Driesboy** [comment]
dont work update protocol

**Comment by Driesboy** [comment]
new skins i think thats the problem

**Comment by Driesboy** [comment]
0.13.2 changelog iOS

journey to the west skins
various bugs fixed

**Comment by thebigsmileXD** [comment]
@Driesboy xD yeaa.. pretty short. http://minecraftpocketedition.wikia.com/wiki/Update_0.13.2

**Comment by Driesboy** [comment]
haha info from App Store

**Comment by PocketKiller** [comment]
can I have the protocol number? I'll commit it.

**Comment by Driesboy** [comment]
39

**Comment by AppleMinerHD** [comment]
Is a Update out for MCPE 0.13.2 ?

**Comment by Driesboy** [comment]
yes

**Comment by AppleMinerHD** [comment]
And a Genisys Update to?

**Comment by Driesboy** [comment]
yes

**Comment by AppleMinerHD** [comment]
Where is this ?

**Comment by Driesboy** [comment]
i have create a pr

**Comment by AppleMinerHD** [comment]
Okay is it on this Site?

**Comment by AppleMinerHD** [comment]
I'm sorry for my english! Cause i'm German...

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
https://github.com/iTXTech/Genisys/pull/231

**Comment by AppleMinerHD** [comment]
Thanks Mate!

**Comment by AppleMinerHD** [comment]
Can you send a Downloadlink for this Folder my Hoster don't understand how to do this..

**Comment by AppleMinerHD** [comment]
O its on sorry

**Comment by AppleMinerHD** [comment]
Can anybody tell me where i can download the .phar or how to Change the masteer in .phar pleas?

**Comment by PeratX** [comment]
@AppleMinerHD Please check README.md to get download links. Or just start server and type /ms to make phar archive
