### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by khaled098** [iTXTech/Genisys#2295]
#### OS and versions

* Genisys:0.2.5
* PHP:7.0.3
* Server OS:Android
* Game version:0.16.2 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by erkam2002** [comment]
...............................

**Comment by khaled098** [comment]
Please Guys Tell Me what i need to Do.

**Comment by erkam2002** [comment]
Where is your Crash log?

**Comment by khaled098** [comment]
Opps

**Comment by khaled098** [comment]
I mean the app Is Crashing So I can't Get The Log

**Comment by Smasher535** [comment]
What "app"?

**Comment by erkam2002** [comment]
The is old dont use it use another app

**Comment by Muqsit** [comment]
If I could ban you, I would.

**Comment by dktapps** [comment]
The ban hammer has struck
