### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by khaled098** [iTXTech/Genisys#2296]
#### OS and versions

* Genisys: 0.2.5
* PHP: 7.0.3
* Server OS: Android
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
PLEASE fill the issue form.

**Comment by erkam2002** [comment]
xD

**Comment by erkam2002** [comment]
Angry @Muqsit  -.-
