### ISSUE TITLE
I can't pvp other players :/

### ISSUE THREAD

**Issue by DWWf** [iTXTech/Genisys#23]
I doesn't let me pvp other people :/ just mobs and its hard to completely kill them

**Comment by PeratX** [comment]
If it caused no damage,try ti turn off Hunger System.

**Comment by DWWf** [comment]
How?

**Comment by MCPEPIG** [comment]
genisys.yml

**Comment by DWWf** [comment]
Tried it but still doesn't work.

**Comment by astersx** [comment]
not genisys fault is a plugin u own!!!  Turn pvp on,  and a guess unuse ifriend+pureperms?

**Comment by DWWf** [comment]
only pure perms

**Comment by CrayonDing** [comment]
maybe some plugins cause this problem
