### ISSUE TITLE
Deu.ini

### ISSUE THREAD

**Issue by MorpheusTP** [iTXTech/Genisys#2301]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
May I update the deu.ini?
It looks really like google-translator it is a really bad german.

**Comment by SleepSpace9** [comment]
Google Translate was definitely not used and there were more than one german reviewer before it was added to Genisys. Please give an example what you mean!

**Comment by MorpheusTP** [comment]
Hmm I meant its bad formated.

**Comment by MorpheusTP** [comment]
Ich meine es fehlt oft eine Anrede wie zB. Du. Es klingt öfters unprofessionell deswegen.
Ihr könnt es natürlich gerne so lassen, es ist nur als Verbesserungsvorschlag gemeint.

**Comment by SleepSpace9** [comment]
_in german:_
Einige der Meldungen wurden auch aus dem originalen Repository (https://github.com/PocketMine/PocketMine-Language/blob/master/deu.ini) übernommen. Dabei scheinen auch ein paar Rechtschreibfehler mitgekommen zu sein. Sicher sind einige Übersetzungen nicht optimal, häufig zeigt sich das dann aber erst, wenn die Meldung mal wirklich im Spiel auftaucht und auch der Zusammenhang klar ist.
Ich würde sagen, erstell doch einfach mal einen PR mit deinen Vorschlägen und @robske110 kann dann sicher auch nochmal mit drüber schauen.

_in (bad) english:_
Some of the messages were copied from the original repository (https://github.com/PocketMine/PocketMine-Language/blob/master/deu.ini). It seems that some misspelling has also found its way into this repository. Certainly some translations are not optimal, but often this becomes not apparent until you are in-game and the context is clear.
I would say create a PR with your proposed corrections and then @robske110 can also have a look at it.

**Comment by Aericio** [comment]
@SalmonGER :D

**Comment by robske110** [comment]
this project is dead anyways

**Comment by FunnyBuddys** [comment]
It's not Bad German!

**Comment by JackNoordhuis** [comment]
If there's an issue with any of the languages feel free to open a pull request. The issue tracker is meant for code-related issues, the translations aren't critical and can be discussed without clogging up the issue tracker.
