### ISSUE TITLE
MCPE 1.0 – Update

### ISSUE THREAD

**Issue by JackNoordhuis** [iTXTech/Genisys#2308]
#### What's taking so long?
MCPE 1.0 has been out for a while now and Genisys hasn't received any attention yet, this has been a result of most contributors being either inactive or deciding it's time to let Genisys die off. There were mixed opinions about this decision, some people weren't happy and others didn't seem to mind at all.

#### So what's going to happen now?
You may have noticed a lot of stuff going on over in the [mcpe-1.0 branch](https://github.com/iTXTech/Genisys/tree/mcpe-1.0) over the past few days, this because I have decided to take on the tedious task of updating Genisys myself. A large majority of the changes so far have been cherry-picked (the glorified copy-paste of the git world) over from [PMMP](https://github.com/pmmp/PocketMine-MP/tree/mcpe-1.0). I would personally like to thank @dktapps and the rest of the PMMP team/collaborators for allowing us to do this.

#### The future of Genisys
Whilst Genisys seems to have hardly survived another MCPE update, the future does not look so promising. Most of the 1.0 changes have been copied over from PMMP, with their team planning a complete rewrite to improve the software we will no longer be able to copy over any changes directly. This will mean that whoever decides to take on the task of updating Genisys will need to reverse engineer the MCPE protocol and implement it into Genisys themselves. This is a very long and frustrating task that will most likely not be worth doing, if the PMMP rewrite goes as planned then Genisys will become obsolete.

__With all that said, I do plan on improving the Genisys codebase and implementing as many of the new MCPE features as possible. Genisys is not a stale project yet and has a (short?) future ahead of it and we can only hope for the best.__

## Planned Changes for PMMP
- [ ] __Code Clean Up –__ More consistency and cleaner, more descriptive documentation.
- [ ] __PHP 7 Updates –__ Update the core to use the new PHP 7 features (small scraps have been popping up for a while now).
- [ ] __Network Updates –__ Updating the server-side handling of data packets to use individual handlers.
- [ ] __New Command API –__ Update the server-side command implementation to make full use of the new client commands.
- [ ] __Block/Item API Clean Up  –__ Clean up the block/item API for plugin developers (and possibly addons).
- [ ] __Entity Clean Up –__ Better server-side entity implementation for plugin developers (and possibly addons).

While this is a very exciting prospect for us all, anything is subject to change at any time. Also remember that us developers have lives too, most of us are students and this is not our full-time job so please refrain from asking for ETAs.

**Comment by VoliPlays** [comment]
Pro:) anyway genisys team will update to 1.0.0 probably never:)

**Comment by Muqsit** [comment]
Since the mcpe-1.0 pmmp branch, I've ported each and every commit to Genisys privately and have been using it for production. 
With the permission of @dktapps, I can upload it here.

**Comment by dktapps** [comment]
I would prefer that we keep a clean consistent commit history so that things can be reverted as necessary. GIT exists for a reason.

(Not like the tremendous mess @thebigsmileXD made of the commit history of a certain spoon, I might add...)

**Comment by Muqsit** [comment]
Entities need some cleaning. Zombie.php and more still have redundant AI code left. I could've helped if it wasn't for school...

**Comment by Muqsit** [comment]
mcpe-1.0 branch no longer exists.
