### ISSUE TITLE
Genisys 1.0.0 potion error

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#2310]
#### Issue description

Potion error

#### Steps to reproduce the issue

Drink potions

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/b7b15d2b9adbff6b2b835d8c353115f063352bed
* PHP: 7.0.14
* Server OS: Ubuntu 16
* Game version:  1.0.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
12.01 16:06:47 [Server] INFO Deprecated: Non-static method pocketmine\Server::broadcastPacket() should not be called statically in phar:///Genisys_.phar/src/pocketmine/item/Potion.php on line 176
```

**Comment by dktapps** [comment]
lol
