### ISSUE TITLE
XBox Login

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#2313]
#### Issue description
On clean install whenever i try to join my server when I have logged into my XBox Live account its says that im nor logged in

#### OS and versions

* Genisys:  Genisys-871fd77 (codename "Kyrios")
* PHP: 7.0.14
* Server OS: Win7
* Game version: 0.16.5

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by BobbyTowers** [comment]
Having the same problem.

**Comment by TheClimbing** [comment]
I think it's because of a recent XBox Live update

**Comment by dktapps** [comment]
I cannot reproduce this. Xbox auth is working perfectly for me.

**Comment by TheClimbing** [comment]
Hey so first i enabled debug and when I tried to login with xbox the server againt kicked me saying I'm not logged in.And the debug message is `[17:16:47] [Server thread/DEBUG]: Attempted to drop a null crafting inventory
`  That's on clean install noone has ever joined

**Comment by TheClimbing** [comment]
Issue self-answered somehow.
