### ISSUE TITLE
Hopper !!

### ISSUE THREAD

**Issue by thientuu2911** [iTXTech/Genisys#2314]
#### Issue description
Hopper error spamming on console!

* Genisys: https://github.com/iTXTech/Genisys/tree/e10b5bed2194cb15362974b620a7cf5f8719f76d
* PHP: 7.0.13
* Server OS: Window Server 2008 64bit
* Game version: MCPE 1.0.0

#### Crashdump, backtrace, memory dumps, plugins list or other files
Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$TransferCooldown in phar://C:/Users/Administrator/Desktop/Server/Genisys.phar/src/pocketmine/tile/Hopper.php on line 81
[04:43:38] [Server thread/CRITICAL]: Could not tick level "Survival": Call to a member function getValue() on null

```
```

**Comment by JackNoordhuis** [comment]
Git left out the changes a I made during testing due to switching between the command line and GUI (I'm already aware of this issue). I'll push the fix sometime soon if no body else decides to fix it.
