### ISSUE TITLE
Mcr map can not be used at 1.0. and there is no valid map format conversion tool

### ISSUE THREAD

**Issue by lowingly** [iTXTech/Genisys#2315]
Mcr map can not be used at 1.0
Whenever I enter mcr map, the service will close.

Warning: Creating default object from empty value in phar://C:/Users/COCOD/Desktop/1.0/G                                                                                                                                   enisys_.phar/src/pocketmine/tile/Furnace.php on line 48
[14:26:18] [Server thread/CRITICAL]: Error: "Call to a member function setItem() on null                                                                                                                                   " (EXCEPTION) in "/src/pocketmine/tile/Furnace" at line 53

These mcr maps are valid maps that I can use at Genisys 0.15.x.
I tried the map format conversion tool (mcr->mca) but it does not work (there are too many errors in the conversion process). 
Is there any other solution? Or will you try to let 1.0 to support mcr maps in the future？

Windows
Version:
Target client version: v1.0.0.2 alpha
PHP7

**Comment by JackNoordhuis** [comment]
This issue is inavlid, you haven't used the template and you're using an outadated dev build. MCRegion is *depreciated* due to the format not supporting 256 high worlds.
