### ISSUE TITLE
Cannot start 1.0.0

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#2316]
#### Issue description

Crash on startup look at crashdumps
#### Steps to reproduce the issue

Start server
#### OS and versions

* Genisys: 1.0.0 branch
* PHP: 7.0.14
* Server OS: Debian 8
* Game version: 1.0.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: require_once(/home/unifrees/main/src/spl/ClassLoader.php): failed to open stream: No such file or directory in /home/unifrees/main/src/pocketmine/PocketMine.php on line 107
```

**Comment by ishitatsuyuki** [comment]
Well, one thing I noticed that you always open pointless issues and close it.

**Comment by Aericio** [comment]
Gets him easy contributions, duh.

**Comment by erkam2002** [comment]
I have forgot that the 1.0.0 branch spl and raklip not has

**Comment by erkam2002** [comment]
i have copied it from Master branch

**Comment by dktapps** [comment]
:facepalm: did you ever hear of git?

**Comment by erkam2002** [comment]
Yes :)

**Comment by dktapps** [comment]
then use it. "copied from master branch" 🤦‍♂️

**Comment by MichaelKunze** [comment]
You want to use:
`git submodule init`
`git submodule update`
