### ISSUE TITLE
mcp-1.0.0 branch does not build at gitlab-ci

### ISSUE THREAD

**Issue by MichaelKunze** [iTXTech/Genisys#2317]
#### Issue description
mcp-1.0.0 branch does not build at gitlab-ci because of missing unzip

#### Steps to reproduce the issue
With commit 6f7391bfe2483ab5588891e84946354ce597faf5 a step to unzip the DevTools was introduced. Unfortunatly unzip seems to be missing from the machine or the path. Hard to say without ssh into the box. I like to help, but without knowing whats there, impossible to fix.

#### OS and versions
* Genisys: cd027717dfcd639d2aa4378c78a49149f6217208
* PHP: 7.0.14
* Server OS: unknown
* Game version: irrelevant

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
$ ./tests/ci.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8713    0  8713    0     0  90675      0 --:--:-- --:--:-- --:--:-- 91715
./tests/ci.sh: line 4: unzip: command not found
mv: cannot stat 'archive/*.phar': No such file or directory
Running lint...
Lint done successfully.
```

**Comment by ishitatsuyuki** [comment]
None of your business.
