### ISSUE TITLE
Genisys DevTools

### ISSUE THREAD

**Issue by Pav155** [iTXTech/Genisys#2318]
Where can I download DevTools for latest version of Genisys? The link in README is not valid and I have not got DevTools on new API. Thx.

**Comment by dktapps** [comment]
Did you not learn from these? https://github.com/iTXTech/Genisys/issues?q=is%3Aissue+author%3APav155+is%3Aclosed

**Comment by lakwsh** [comment]
I can't found the Genisys-Devtools in https://github.com/iTXTech/DevTools
