### ISSUE TITLE
Shutdown error

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#2322]
#### Issue description

Genisys 1.0.0 server stop error

#### Steps to reproduce the issue

Stop server

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/b45dc8fb06584cc7970318eaee20b6f510c94799
* PHP: 7.0.14
* Server OS: Ubuntu 16.04.1
* Game version: Android

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
2017-01-20 [16:04:47] [Server thread/INFO]: Unloading level "end"
2017-01-20 [16:04:47] [Server thread/INFO]: Unloading level "spawn"
2017-01-20 [16:04:47] [Server thread/INFO]: Unloading level "skypvp2"
2017-01-20 [16:04:47] [Server thread/INFO]: Unloading level "spawnworld"
2017-01-20 [16:04:47] [Server thread/ERROR]: Error while unloading a chunk: Call to a member function getServer() on null
2017-01-20 [16:04:47] [Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 1810
2017-01-20 [16:04:47] [Server thread/INFO]: Unloading level "szabad2"
2017-01-20 [16:04:47] [Server thread/INFO]: Unloading level "telkek"
2017-01-20 [16:04:48] [Server thread/INFO]: Unloading level "nether"
2017-01-20 [16:04:48] [Server thread/INFO]: Stopping other threads
```

**Comment by dktapps** [comment]
seems a lot of things leak on shutdown... first double-chests, now this. Please enable debug in your pocketmine.yml and try to reproduce.

**Comment by kaitododoyt** [comment]
Same Error confirmed

**Comment by dktapps** [comment]
@kaitododoyt Please see my comment and post any relevant debug output when reproduced.

**Comment by kaitododoyt** [comment]
Only This, before of stop server(Sorry, i dont know spoiler code)

20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level
20.01 20:21:22 [Server] Server thread/DEBUG Position was holding a reference to an unloaded Level

CrashDump:

Error: Call to a member function getServer() on null
File: /src/pocketmine/entity/Entity
Line: 1810
Type: notice

Code:

Backtrace:
#0 /src/pocketmine/level/format/io/region/Anvil(1970): pocketmine\entity\Entity->__destruct(boolean)
#1 /src/pocketmine/level/format/io/region/RegionLoader(116): pocketmine\level\format\io\region\Anvil->nbtDeserialize(string x..._k.P..._lf..o..7....SP.0X7.2......DQ.......o....w^..d9.%.J.rj....$.4ONKKF..'...(x.L{..|..I......a...{.8......I....N.$8V3....7...`~...W.........8...j...T.Ozr..N.k/.#;.....g............qxvuVwwxOz/...^..................@C..z?8J.h.{jw.+.3?.E.M_...0..n.N?......Y.....}+..l...E......r.=..(z..h..Z..O>...oW~W..4::]......8...~....b...........@{......=.Z..O>...O~......@..th......`.....X.. ...O>..[.O{......;..........A`....?6..1.o.......V...=H>...U...?@..-....:A>..o.q.Y..m....@.........&....~.zDk.bB........Iu.....o.._[.f..m........^....p.h`.U...F..=h..P.K.....EZn..........h...n......j......R[n.#......../X.v)
#2 /src/pocketmine/level/format/io/region/McRegion(341): pocketmine\level\format\io\region\RegionLoader->readChunk(integer 19, integer 20)
#3 /src/pocketmine/level/format/io/region/McRegion(290): pocketmine\level\format\io\region\McRegion->loadChunk(integer -13, integer 52, boolean 1)
#4 /src/pocketmine/level/Level(2711): pocketmine\level\format\io\region\McRegion->getChunk(integer -13, integer 52, boolean 1)
#5 /src/pocketmine/level/Level(684): pocketmine\level\Level->loadChunk(integer -13, integer 52)
#6 /src/pocketmine/Player(955): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(745), integer -13, integer 52, boolean 1)
#7 /src/pocketmine/Player(1960): pocketmine\Player->sendNextChunk(boolean)
#8 /src/pocketmine/Server(2698): pocketmine\Player->checkNetwork(boolean)
#9 /src/pocketmine/Server(2390): pocketmine\Server->tick(boolean)
#10 /src/pocketmine/Server(2268): pocketmine\Server->tickProcessor(boolean)
#11 /src/pocketmine/Server(1872): pocketmine\Server->start(boolean)
#12 /src/pocketmine/PocketMine(486): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server1124/custom-phar.phar/, string /home/minecraft/multicraft/servers/server1124/, string /home/minecraft/multicraft/servers/server1124/plugins/, string unknown)
#13 (1): require_once(string phar:///home/minecraft/multicraft/servers/server1124/custom-phar.phar/src/pocketmine/PocketMine.php)

**Comment by dktapps** [comment]
It's ``` around code blocks FYI. and... wtf???

**Comment by dktapps** [comment]
omfg... PeratX 🤦‍♂️

**Comment by TheClimbing** [comment]
@dktapps  Now that crashed my server...Here is the CrashDump

[CrashDump_Thu_Feb_9-20.42.46-GMT_2017.txt](https://github.com/iTXTech/Genisys/files/765092/CrashDump_Thu_Feb_9-20.42.46-GMT_2017.txt)

**Comment by dktapps** [comment]
I know what's causing it, I just can't be bothered fixing it.
