### ISSUE TITLE
Canceling drop event Duplicate items

### ISSUE THREAD

**Issue by orlando092** [iTXTech/Genisys#2325]
#### Issue description

If you cancel drop event the item that you are trying to drop will be duplicated

#### Steps to reproduce the issue

Cancel drop Item event 

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/6d716e09ef9b8bc0fdbfbb733192c2918995ca66
* PHP: 7.0
* Server OS: windows 10
* Game version: Android, mcpe 1.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
Probably something with the floating inventory. I can't get this glitch to happen but try clearing the floating inventory after the event gets cancelled.
