### ISSUE TITLE
Inventory Transaction

### ISSUE THREAD

**Issue by RompeCraneos** [iTXTech/Genisys#2327]
#### Issue description
Im making Chest Shop plugin,  in Transaction i cancelled it when player dont have amount of diamonds(Diamonds are money), but in plugin test item is given to my inventory anyway. 
Im new making plugins, if you know a plugin to guide me I will be grateful, thanks

#### Steps to reproduce the issue
modify InventoryTransactionEvent

#### OS and versions
* Genisys: Genisys (codename "Enopoio")
* PHP: PHP version: 7.0.14
* Server OS: windows 8
* Game version: Minecraft PE 1.0.0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
```

**Comment by Muqsit** [comment]
You have to modify the target item too 

/** @var Transaction $transaction */
$transaction->setTargetItem(Item::get(0));

Please read the source code.
