### ISSUE TITLE
Tnt issue

### ISSUE THREAD

**Issue by JunkDaCoder** [iTXTech/Genisys#2329]
#### Issue description

Tnt doesnt explode
#### Steps to reproduce the issue

Place tnt and ignite it
#### OS and versions

* Genisys:
* PHP:7
* Server OS:Ubuntu
* Game version: 1.0.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[23:31:40] [Server thread/CRITICAL]: Could not tick level "Mansion": Undefined class constant 'DATA_FUSE_LENGTH'
```

**Comment by JackNoordhuis** [comment]
Please provide what version you are using. We cannot help you without knowing what version this is occurring on.

**Comment by JunkDaCoder** [comment]
@JackNoordhuis on startup all it says is version: nothing else. I put for Version: on the issue as 1.0.0 branch

**Comment by JackNoordhuis** [comment]
@JunkDaCoder That is still invalid. Please provide a git commit hash, look at other open issues if you need an example.

**Comment by JunkDaCoder** [comment]
I fixed it, was just missing something in the primedtnt.php
