### ISSUE TITLE
Check movement

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#2330]
#### Issue description

Cant disable check movement
#### Steps to reproduce the issue

GO over stairs or run over slabs and etc.
#### OS and versions

* Genisys: 1.0.0 Branch
* PHP: 7.0.14
* Server OS: Debian 8
* Game version: 1.0.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dktapps** [comment]
Already known, this was removed to aid sync between PocketMine-MP and Genisys. See pmmp/PocketMine-MP#287.
