### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by VoliPlays** [iTXTech/Genisys#2331]
#### Issue description

When I go in the portal don't happen anything.P.s I have nether activated in genisys.yml!
#### Steps to reproduce the issue

1.Activate nether in genisys.yml
2.Make a portal and go in.
#### OS and versions
* Genisys:latest
* PHP:7.0.3
* Server OS:Ubuntu 14.04
* Game version: 1.0.16

**Comment by JackNoordhuis** [comment]
The portal works fine for me. Your issue is invalid, 'latest' is not a valid version. Please provide a git hash.

**Comment by Superman987** [comment]
Same problem, I get the error "World nether not found". I am using Genisys:1ed05b7.
