### ISSUE TITLE
Query stop working at 41+ players on.

### ISSUE THREAD

**Issue by iagomcs** [iTXTech/Genisys#2335]
#### Issue description
Everytime server hit 41+ players QUERY stop working. Works fine with 40 players, hit 41+ query stop.

#### Steps to reproduce the issue
Just get a server with 40 players on and check https://mcapi.ca/query/SERVERIP/mcpe query works fine.
Now get a server with 41 players on and check mcapi again, query stop working.

#### OS and versions
* Genisys: all version
* PHP:7.0.15
* Server OS: CentOS 7
* Game version: all version

**Comment by JackNoordhuis** [comment]
Works fine for me. This is probably in issue with either your plugins or the API.
