### ISSUE TITLE
allow all api

### ISSUE THREAD

**Issue by qyd0801** [iTXTech/Genisys#2338]
allow old api（1.0，2.0）
Version: unsupported-de9576c

**Comment by dktapps** [comment]
Maybe we should just remove the API version altogether... only slightly dumber idea. :man_facepalming:

**Comment by dterweij** [comment]
Whats the differences between all the API's ?  I dont see anywhere a list of changes...

**Comment by SuperDude36** [comment]
Yeah lets just screw API, no point :P
