### ISSUE TITLE
InventoryTransactionEvent not work

### ISSUE THREAD

**Issue by Enes5519** [iTXTech/Genisys#2339]
Video: https://youtu.be/vixEgqPZ1fY

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
