### ISSUE TITLE
Dont work!!!

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#234]
i put php 7 in bin,  download start.sh from master,  and phar from google drive.
It spam my ssh with php7 no permision -.-'.  And then auto dellete it after i force exit........

**Comment by astersx** [comment]
Oh ya,  i modify do loop to yes in start.sh,  but i dont thinknis my fault

**Comment by xpyctum** [comment]
It it your problem, not Genisys

**Comment by astersx** [comment]
./bin/php7/bin/php permisson denied 
wtf is my problem?

**Comment by Efforto** [comment]
YES!CHANGE THE PERMISSION TO 0777

**Comment by astersx** [comment]
Php7 didnt dellete,  it was after i chmod it,  maybe was this problem,  then it removed my acces becouse of chmod and didnt show php7 anymore,  now i reverted it to normal!!!!!!!
So how infix permision problem? Php5 didnt have this problem

**Comment by astersx** [comment]
chmod +0777

**Comment by astersx** [comment]
Ok i will try

**Comment by astersx** [comment]
Dont Work

**Comment by astersx** [comment]
![screenshot_2016-02-05-10-31-08](https://cloud.githubusercontent.com/assets/13157548/12841256/289e3a94-cbf3-11e5-8639-ba20e8c1e076.png)

I did chmod 0777  ./bin     and same

**Comment by xpyctum** [comment]
chmod 777 ./start.sh -_-

**Comment by Efforto** [comment]
= =so try WinSTP on computer

**Comment by astersx** [comment]
or i need to specify path? no directory......  hmmm

**Comment by Efforto** [comment]
chmod 0777 bin

**Comment by Efforto** [comment]
change all the permission of ur server

**Comment by Efforto** [comment]
then it could run

**Comment by astersx** [comment]
chmod work well,  becouse i did a chmod mistake on bin,  wen i paniked (spam permision denied)
now chmod is back to normal,  and i dont think is directory permision at fault

**Comment by astersx** [comment]
I run php5 without problems,  why i need change server perms?

**Comment by Efforto** [comment]
AAAHHHH just try = =

**Comment by Efforto** [comment]
try baidu.com or google.com (Fxxxxxxxxxxk just try!!!!!!)

**Comment by astersx** [comment]
I wont change my vps perms and ruin it -.-'

**Comment by Efforto** [comment]
ruin? you only change your server's(NOT VPS) permission, linux need permission to do things.............

**Comment by astersx** [comment]
=))  im so confused =))...............

**Comment by Efforto** [comment]
......

**Comment by astersx** [comment]
chmod 777  ./ ?

**Comment by astersx** [comment]
You wanna me chmod all server files?

**Comment by Efforto** [comment]
no....chmod 777 /bin

**Comment by astersx** [comment]
done,  and no changes,  same error

**Comment by xpyctum** [comment]
chmod -R 755 bin

**Comment by Efforto** [comment]
did you change some of the files for php7?

**Comment by astersx** [comment]
Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by astersx** [comment]
i did chmod 777. /bin/php7/bin/php and worked,  but this error show

**Comment by Efforto** [comment]
err....try some cilent on computer such as WinSCP to change the permission

**Comment by astersx** [comment]
Chmod work after i did that action,  i needed to specify file no directory,  thx,  but now this error show


Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

**Comment by astersx** [comment]
Server start and run without problems

**Comment by astersx** [comment]
One problem!!!!  0.13.2...  it say on master that is done,  buuuut :(,  it show 0.13.1,  i use version from google drive

**Comment by astersx** [comment]
Maybe is outdated,  i will run master from source , thx so much for help :)

**Comment by MasterWolf** [comment]
@astersx wait are you using android?

**Comment by zzz1999** [comment]
Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory

I hava same problem。。。How to solve?

**Comment by gaoyichuan** [comment]
@zzz1999 Install the opcache..

**Comment by zzz1999** [comment]
@gaoyichuan I don't know how to install opcache..

**Comment by astersx** [comment]
Opcache will improve the game?

**Comment by astersx** [comment]
And php7 genisys,  killed plugins artificial inteligence by onebone and manyworlds :(!!!!
Anyway it works fine,  but on serverauth give some notice errors!!!!!!!
