### ISSUE TITLE
Breath underwater

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#2343]
#### Issue description

Breath underwater is decreasing way too fast
#### Steps to reproduce the issue

Just go underwater
#### OS and versions

* Genisys:Genisys-1ed05b7
* PHP:7.0.14
* Server OS:Win7
* Game version: 1.0.0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by dschwartz783** [comment]
lol
