### ISSUE TITLE
 allow-movement-cheats makes server freeze

### ISSUE THREAD

**Issue by DKQoo2** [iTXTech/Genisys#2346]
Just set   allow-movement-cheats: true
and try to teleport

**Comment by JackNoordhuis** [comment]
Without knowing your Genisys version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
