### ISSUE TITLE
Make Invinsible Bedrock Placeable

### ISSUE THREAD

**Issue by Qimie** [iTXTech/Genisys#2348]
Hey,can you make  Invinsible Bedrock can be on place on each other? Like barrier block.

* Genisys: Latest-> Just Test It.
* PHP: Latest-> Just Test It.
* Server OS: Genisys App On My Tablet-> It Don't Care.
* Game version: Latest-> Just Test It.

**Comment by iTzAndrew33212** [comment]
This would be really helpful tho .. You can download world protect and use world barrier

**Comment by Qimie** [comment]
I just figure the block just now. Just Do /give {name} 95 {amount}

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
