### ISSUE TITLE
Not issue, but what version supports 1.0.2?

### ISSUE THREAD

**Issue by neoneosa** [iTXTech/Genisys#2349]
This isnt an issue, but what branch should i use for MCPE 1.0.2?

**Comment by ishitatsuyuki** [comment]
# Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by neoneosa** [comment]
I asked on Telegram and the FAQ doesnt answer my question
