### ISSUE TITLE
SetBlock Issue

### ISSUE THREAD

**Issue by RompeCraneos** [iTXTech/Genisys#2351]
#### Issue description
->setBlock() on more of 200 blocks distance causes world corruption
![sin titulo](https://cloud.githubusercontent.com/assets/25283322/22669446/520f37b2-eca3-11e6-8e6f-49636b1fe140.jpg)

#### Steps to reproduce the issue
setBlock long distance of player

#### OS and versions
* Genisys: 
* PHP: 7
* Server OS: Windows 8
* Game version: 1.0.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment]
Please provide the Genisys version as setBlock() is working fine, at least for me.
Are you running the latest version of Genisys?
