### ISSUE TITLE
No Blocks 

### ISSUE THREAD

**Issue by Christian665** [iTXTech/Genisys#2352]
In the shadow holes of a mountain, no blocks are displayed. You have to put a torch that the blocks appear?...

In cave is light. If you stand longer in it it becomes slowly darker !?

There is no lava to be found .

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
