### ISSUE TITLE
Question About Porting

### ISSUE THREAD

**Issue by CaptainRalph** [iTXTech/Genisys#2356]
I would like to ask about porting a mcpe server. 1st; How much it will consume on the internet. Will it consume very big, or it will not consume

**Comment by CaptainRalph** [comment]
And also, when I do /banlist shows the permission of the command and also for the other commands. Thank you

**Comment by JackNoordhuis** [comment]
This is an issue tracker, not a Q&A or forum. Please consider reading the readme to find the appropriate place to ask questions.
