### ISSUE TITLE
Classic mode crafting

### ISSUE THREAD

**Issue by Assblocker** [iTXTech/Genisys#2358]
#### Issue description

Can't craft while in classic mode on mcpe v1.0.3
#### Steps to reproduce the issue

Try to craft in classic mode
#### OS and versions

* Genisys: 0ce7918
* PHP: 7.0.14
* Server OS: Linux Ubuntu
* Game version: MCPE v1.0.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
None
```

**Comment by Muqsit** [comment]
I have just tested this and Classic GUI crafting works perfectly on both: Win10 and PE.
