### ISSUE TITLE
PHP Runtime

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#2359]
#### Issue description

Please someone add this cause I'm sick of `"Base address marks unusable memory region"`
So please add this to the php ini `opcache.mmap_base = 0x20000000`

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by TheClimbing** [comment]
Well okay

**Comment by dktapps** [comment]
wrong repository.

**Comment by TheClimbing** [comment]
I'm dumb af, sry...
