### ISSUE TITLE
Why have Emerald on it ?

### ISSUE THREAD

**Issue by xinghao2003** [iTXTech/Genisys#2361]
#### Issue description
![screenshot_2017-02-16-23-00-17-733](https://cloud.githubusercontent.com/assets/20557459/23026358/fb4eb758-f49b-11e6-9bf4-dc8a6cb5f11d.png)

#### Steps to reproduce the issue
1. Place a Item Frame
2. Place any item into the Frame
3. Break the Item Frame (Because some problem cannot take out the item from the frame directly)

#### OS and versions
* Genisys: 0ce7918
* PHP: 7.0.8
* Server OS: Windows 10
* Game version:  Pocket Edition 1.0.4 beta

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Nothing
```

**Comment by xinghao2003** [comment]
I am not sure will this happen in 1.0.3 , but hope you can test it , thanks

**Comment by dktapps** [comment]
1.0.4 is not supported, it is a beta.

**Comment by xinghao2003** [comment]
._.

**Comment by xinghao2003** [comment]
maybe i will test it on 1.0.3 later

**Comment by xinghao2003** [comment]
okay , it just happen in 1.0.4 beta ._.
