### ISSUE TITLE
Xbox Live Auth

### ISSUE THREAD

**Issue by lolmanz0** [iTXTech/Genisys#2367]
Can you tell me how to have enabled Xbox Live authentication and normal mode too? I have enabled online-mode but I want to join a server without Xbox Live account too. Is it possible like on MinePlex etc.?

* Genisys: 15a7982
* PHP: 7.0.6
* Server OS: Windows
* Game version: 1.0..3

**Comment by Muqsit** [comment]
Modify ‘online-mode‘ in server.properties.

**Comment by lolmanz0** [comment]
How? I can modify it only on or off, am I right?
