### ISSUE TITLE
Can not use the boat

### ISSUE THREAD

**Issue by 2300206764** [iTXTech/Genisys#2368]
when i use the boat ,it can show but when i click it the boat is to be a rider.It means that the boat is on my head and my body is sink in the water.

**Comment by ishitatsuyuki** [comment]
## Improperly Formatted Issue Ticket - Lacks Information

Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.
