### ISSUE TITLE
Can not use boat

### ISSUE THREAD

**Issue by 2300206764** [iTXTech/Genisys#2369]
#### Issue description
when i use the boat ,it can show but when i click it the boat is to be a rider.It means that the boat is on my head and my body is sink in the water.

#### Steps to reproduce the issue
 - use boat item and click to the water
 - click the boat

#### OS and versions
* Genisys:1.0.3.0
* PHP:7.0
* Server OS:Windows
* Game version: 1.0.3.0

#### Crashdump, backtrace, memory dumps, plugins list or other files
without error.
```
```

**Comment by Muqsit** [comment]
Boats aren't fully implemented. Mob AI and Boats are scheduled to be implemented on a later date.
