### ISSUE TITLE
It's Magic!

### ISSUE THREAD

**Issue by noremac09** [iTXTech/Genisys#2371]
Hello! There is such a thing: VDS broke dpkg, fixed it, then when installing programs gave Warnings, reset all the programs that appear in dpkg-l using the command: apt-get install --reinstall *the program name", VDS is the web server. So.. People can't get on the server. In the console are error Segmentation error, mm_heap_corrupted. And players can't to join to the server, they must open website that is on apache2, surf it, and again try to come in. What I can try to do?

OC: Debian 7
The PHP Version on web server, apache2: 7.0.15
PHP on Genisys Version: 7.0.15
I tried to re-compile PHP Binaries.

I apologize for the grammatical errors, I from Russia.

* Genisys: Lastest
* PHP: 7.0.15
* Server OS: Debian 7
* Game version: 1.0.3

**Comment by Muqsit** [comment]
More of a server based issue. Contact your host about problems with your system's network.
I recommend you reinstall your OS.
