### ISSUE TITLE
Box can't open chunk!!

### ISSUE THREAD

**Issue by w2333333** [iTXTech/Genisys#2372]
Box can't open
* Genisys:Genisys_2d56cbd
* PHP:7
* Server OS: windows
* Game version: 1.03
After I upload a plugin with box, it start crash down 
Server thread/CRITICAL]: TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in phar://plugins/PVE_Pro_v1.6.0.phar/src/PVEPro/Main.php on line 1271" 

```
```

**Comment by Muqsit** [comment]
https://github.com/iTXTech/Genisys/commit/3c1ea71247169837adcdda9895fe7f46cbbcf563
