### ISSUE TITLE
Lag [Please read]

### ISSUE THREAD

**Issue by LEETMasterCode** [iTXTech/Genisys#2374]
The issue : 

1- When you put items in the item frame it counts it as if it was something like an entity [prediction] (surely not tho as than it would be cleared if you had ClearLagg plugin) and makes the area with the item frames laggy. Tho it takes more than 20-30 itemframe to makes it laggy. Still it really bad when your making a Shop in your server.

2- It seems every 1-5 seconds the player is teleport to themselves or something or a lag spike happens every 1-5 seconds, I am guessing when ever it does that, it checks if the player is connected. But that's an issue when PvPing.

How to solve this issue -

1- Look into Itemframe's code.

2- The bug is most likly located It player.php (or whatever it's called haven't checked)

Thanks for reading.

**Comment by ishitatsuyuki** [comment]
Please review the contribution guidelines before opening an issue.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)

**Comment by LEETMasterCode** [comment]
So are you saying make two issue topics?

**Comment by ishitatsuyuki** [comment]
Without knowing what your Version, OS, PHP, Client, or plugins and how the issue occurred, the issue cannot begin to be solved.
A friendly pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template is provided, the issue will be closed; you are fully welcome to update the issue ticket with the adequate information and we will gladly reopen the issue.
Sorry for the inconvenience.

**This is not a support forum. Consult one of the chat or forums provided in README.**

**Comment by LEETMasterCode** [comment]
Updated... Anymore info?

**Comment by ishitatsuyuki** [comment]
Without knowing what your **Version**, OS, PHP, Client, or **plugins** and how the issue occurred, the issue cannot begin to be solved.
**A friendly pre-formatted template** is provided that shows the required information to begin to find, test and solve an issue.

**Comment by LEETMasterCode** [comment]
Sorry, Version of what? and taking about plugins (it's says or)

**Comment by ishitatsuyuki** [comment]
Lag means your server doesn't have enough machine power to handle it. There's no support beyond this, since Genisys is no longer in mainline development.

Looking at the code doesn't solve it - this is how it works, and it's working as intended.

**Consult a chat to get some comments on your problem.**
