### ISSUE TITLE
Plugin APIS are all "broken"/incompatible

### ISSUE THREAD

**Issue by ChickenTheDuck** [iTXTech/Genisys#2376]
#### Issue description

All Plugin APIS are Broken/Incompatible
Must be because of Genisys because with Elywing it works
#### OS and versions

* Genisys: I really didn't understand how to find it but it's the latest (non failed) hope this helps
* PHP: 7.0
* Server OS: Genisys
* Game version: 1.0.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by ishitatsuyuki** [comment]
Your brain is all "broken" because Elywing plugins are not Genisys plugins.
