### ISSUE TITLE
$this->getServer()->getDefaultLevel not working!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by EpicArtz08999** [iTXTech/Genisys#2380]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Ragnok123** [comment]
Facepalm

Code in studio...

**Comment by yungtechboy1** [comment]
#close-this-issue
Bra take the time to fill the template out

**Comment by HAN-105** [comment]
Nice issue anyway

**Comment by Muqsit** [comment]
Please provide us with your PHP version, Genisys version and server OS and any more information that could be used to assist you.

**Comment by ishitatsuyuki** [comment]
wow, such a noisy title
