### ISSUE TITLE
Ids for different type of spawners is missing.

### ISSUE THREAD

**Issue by LEETMasterCode** [iTXTech/Genisys#2382]
Id for different type of spawners such as Zombie spawner is missing. Or it could be that /give <player> monsterspawner:<second ID> doesn't work on spawners.

Please try to Fisk this issue.

**Comment by Muqsit** [comment]
The is no such thing as a "Zombie Monster Spawner" physical item. That just doesn't exist in MCPE.

**Comment by LEETMasterCode** [comment]
Ok, so when you place a spawners and you use a zombie egg to make it into a zombie spawner... 

I am saying is that that zombie spawner needs to have its own ID...

**Comment by Muqsit** [comment]
That's a tile and they don't exist in item forms.

**Comment by Muqsit** [comment]
Here's list of items currently available in MCPE, along with their ids: https://hydra-media.cursecdn.com/minecraft.gamepedia.com/c/c6/DataValuesPE.png?version=aeaec2dd309456bb5414a618f36f3089
