### ISSUE TITLE
Sounds are DIASPPEAR!!!!!

### ISSUE THREAD

**Issue by DKQoo2** [iTXTech/Genisys#2384]
#### Issue description
many sounds are disappear

#### Steps to reproduce the issue
put things, destory things or doing anything can make sounds

#### OS and versions
* Genisys: #6931292
* PHP: 7.0.9
* Server OS: Linux 16.04
* Game version: v1.0.4 PE

**Comment by dktapps** [comment]
Known issue since 0.16, 1.0.4 just compounded the issue with resource pack changes.

**Comment by kaitododoyt** [comment]
How to solve it?

**Comment by ExaSonit** [comment]
Try to restart minecraft or server

**Comment by DKQoo2** [comment]
@ExaSonit I try before it didn't change anything

**Comment by ExaSonit** [comment]
I am not developer...
