### ISSUE TITLE
No Nether ? 

### ISSUE THREAD

**Issue by LordJoshie** [iTXTech/Genisys#2391]
I've been away from Genisys for a while because Tesseract came around and was quicker for updates.. 

Coming back to test out Genisys, and notice some weird things... 

Including the nether?

**Comment by dktapps** [comment]
The way the Nether is loaded has been altered, it is now only loaded ondemand. Previously it was wasting lots of CPU time with level ticks when nobody was in it.

**Comment by LordJoshie** [comment]
so then how do you generate/load the Nether?

**Comment by dktapps** [comment]
It should be loaded/generated automatically when you use a Nether portal.

**Comment by LordJoshie** [comment]
which cannot be lit.... lol

**Comment by ishitatsuyuki** [comment]
Please ask your question in one of the [chat](https://github.com/iTXTech/Genisys#discussion) instead. Thanks.
