### ISSUE TITLE
I cannot connect to servers hosted on the same computer with Windows 10 Edition Beta. How can I fix this?i have tried both methods on the FAQ but they don't work powershell wont run the script and options dont work at all i have been trying to fix this for weeks so please help me ffs

### ISSUE THREAD

**Issue by AmrSlayer** [iTXTech/Genisys#2393]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Aericio** [comment]
please learn that the title is a small description of whats wrong, such as "Can't connect via localhost" or whatever. also that title up there should be in "Issue description". supplying us with server information helps also. also if you require assistance, you should communicate with us via mattermost, frenode, gitter, telegram, or the forums. so then they wont keep closing the issue and you can get help.
