### ISSUE TITLE
Regardiennn

### ISSUE THREAD

**Issue by ICrashHD** [iTXTech/Genisys#2396]
Привет, мне было интересно, сможете ли вы обновить genisys? Его устаревшее .... пожалуйста ..... НЕ СДАВАЙТЕСЬ ПРИЧИНА УР ИСПЫТАНИЙ КАЖДЫЙ !!!! СЛУШАЙТЕСЬ мне, потому что мне нужно знать, что мне нужно, чтобы она жила, пожалуйста, сделайте это живым ..... Я люблю программное обеспечение всего сервера, не двигайтесь в PocketMine, слушайте меня, потому что все, что вы собираетесь делать, Вопрос: (вы всегда к этому ко всем вопросам люди на разных языках сообщение! Your're расистские!Привет, мне было интересно, сможете ли вы обновить genisys? Его устаревшее .... пожалуйста ..... НЕ СДАВАЙТЕСЬ ПРИЧИНА УР ИСПЫТАНИЙ КАЖДЫЙ !!!! СЛУШАЙТЕСЬ мне, потому что мне нужно знать, что мне нужно, чтобы она жила, пожалуйста, сделайте это живым ..... Я люблю программное обеспечение всего сервера, не двигайтесь в PocketMine, слушайте меня, потому что все, что вы собираетесь делать, Потому что я нуждаюсь в этом, и ты знаешь, что причина его лучших когда-либо !! борьба?? Да это rirgh ?? Listne к мне o wcause u знайте я намереваюсь !! Вам нужно istenПотому что я нуждаюсь в этом, и ты знаешь, что причина его лучших когда-либо !! борьба?? Да это rirgh ?? Listne к мне o wcause u знайте я намереваюсь !! Вам нужно istenВопрос: (вы всегда к этому ко всем вопросам люди на разных языках сообщение! Your're расистские!
Потому что я нуждаюсь в этом, и ты знаешь, что причина его лучших когда-либо !! борьба?? Да это rirgh ?? Listne к мне o wcause u знайте я намереваюсь !! Вам нужно isten

ДАВАЙТЕСЬ ПРИЧ  👍

**Comment by Muqsit** [comment]
Sorry but we aren't international.

**Comment by xZeroMCPE** [comment]
Damn.... That seems supremacist.

**Comment by dktapps** [comment]
So we should listen to you while you tell us to do things? No thanks. This project is dead. Get over it.
