### ISSUE TITLE
0.13.2 php5 ?

### ISSUE THREAD

**Issue by AppleMinerHD** [iTXTech/Genisys#241]
How can i Change  the php7 to php5 cause my Server Needs php5. And i dont find a Genisys_1.0dev.phar for the Version 0.13.2 in php5

**Comment by gaoyichuan** [comment]
There is no phar for other branches.. You can checkout the php5 branch and run directly from source.

**Comment by AppleMinerHD** [comment]
But is the php5 branch for 0.13,2?

**Comment by gaoyichuan** [comment]
@AppleMinerHD Oh, sorry I forgot it.. It's for 0.14.0

**Comment by flaxues** [comment]
There is no php5 version for 0.13.2 anymore

**Comment by Driesboy** [comment]
Ok i go fix 0.13.2 for genisys

**Comment by CrayonDing** [comment]
Try the newest version.
