### ISSUE TITLE
certain nbt tags causing server crash because of unsupported plugins

### ISSUE THREAD

**Issue by DesPlaysMC** [iTXTech/Genisys#243]
example:
-------------------------------------------------------------------------------------------------------------------------------
Genisys Crash Dump Sat Feb 6 14:37:01 AWST 2016

Error: Cannot use pocketmine\nbt\tag\Int as Int because 'Int' is a special class name
File: /plugins/SignShop_v2.0.0build3.phar/src/SignShop/Manager/SignManager
Line: 23
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起
BAD PLUGIN : SignShop v2.0.0build3

Code:
[14]  * @link http://forums.pocketmine.net/plugins/signshop.668/
[15]  * @description Buy and Sell the items using Signs with virtual-money.
[16]  * @version 1.1.2
[17]  * @api 1.11.0
[18]  */
[19] namespace SignShop\Manager;
[20] 
[21] use SignShop\SignShop;
[22] use pocketmine\Server;
[23] use pocketmine\nbt\tag\Int;
[24] use pocketmine\nbt\tag\String;
[25] use pocketmine\level\Level;
[26] use pocketmine\level\Position;
[27] use pocketmine\item\Item;
[28] use pocketmine\block\Block;
[29] use pocketmine\tile\Sign;
[30] use pocketmine\tile\Tile;
[31] use pocketmine\nbt\tag\Compound;
[32] use pocketmine\utils\TextFormat;
[33] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #0 [Protocol 43; API 2.0.0]
uname -a: Windows NT DESKTOP-QQLDUQJ 10.0 build 10586 (Windows 10) i586
PHP version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
加载的插件:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
AntiLagg 1 by Mrswa9 for API(s) 1.13.0
BanItem 2.1 by LDX for API(s) 1.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
CustomChat 5.0.0 by Array for API(s) 1.7.1
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FloatingTexter 1.0 by Heromine/Jon for API(s) 1.12.0
GrabBag 2.4.1 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
InventoryClear 1.3 by CrazedMiner for API(s) 1.11.0
iProtector 3.1a by LDX for API(s) 1.9.0
KillChat 1.0.2 by Array for API(s) 1.9.0
LightningOnDeath 1 by MichaelM04 for API(s) 1.13.0
MassiveEconomy 1.0 R3 by EvolSoft for API(s) 1.9.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
OreBroadcast 0.0.1 by Falkirks for API(s) 1.9.0
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
PlanB 1.2.0 by Gamecrafter for API(s) 1.10.0
PocketDockConsole 0.0.14 by humerusj for API(s) 1.0.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
PopupDisplayer 2.0.1 by Heromine, Flavius12 for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 1.12.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SubnetBan 1.0.0 by  for API(s) 1.0.0
SurvivalFly 1.0.9 by Mentha Haplocalyx Alcatraz_Du for API(s) 1.9.0
TAGBlock 0.3-Alpha by hm for API(s) 1.4.1
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TierLoot 1.0.0 by XFuryMCPE for API(s) 1.12.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
WalkingParticles 2.2.3 by CyberCube-HK Team & hoyinm14mc for API(s) 1.13.0, 2.0.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0
WarpSigns 0.0.1 by Falkirks for API(s) 1.12.0

another example:
-------------------------------------------------------------------------------------------------------------------------------
Genisys Crash Dump Sat Feb 6 14:34:20 AWST 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: /plugins/TNT_v1.2.4.phar/src/Tnt/Tnt
Line: 15
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[6] use pocketmine\utils\Random;
[7] 
[8] use pocketmine\entity\Entity;
[9] 
[10] use pocketmine\level\sound\AnvilUseSound;
[11] 
[12] use pocketmine\nbt\tag\Compound;
[13] use pocketmine\nbt\tag\Enum;
[14] use pocketmine\nbt\tag\Double;
[15] use pocketmine\nbt\tag\Float;
[16] use pocketmine\nbt\tag\Byte;
[17] 
[18] use pocketmine\plugin\PluginBase;
[19] 
[20] use pocketmine\event\entity\ExplosionPrimeEvent;
[21] use pocketmine\event\Listener;
[22] use pocketmine\event\server\DataPacketReceiveEvent;
[23] use pocketmine\event\block\BlockPlaceEvent;
[24] 
[25] use pocketmine\network\protocol\UseItemPacket;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #0 [Protocol 43; API 2.0.0]
uname -a: Windows NT DESKTOP-QQLDUQJ 10.0 build 10586 (Windows 10) i586
PHP version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
加载的插件:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
AntiLagg 1 by Mrswa9 for API(s) 1.13.0
BanItem 2.1 by LDX for API(s) 1.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
CustomChat 5.0.0 by Array for API(s) 1.7.1
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FloatingTexter 1.0 by Heromine/Jon for API(s) 1.12.0
GrabBag 2.4.1 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
InventoryClear 1.3 by CrazedMiner for API(s) 1.11.0
iProtector 3.1a by LDX for API(s) 1.9.0
KillChat 1.0.2 by Array for API(s) 1.9.0
LightningOnDeath 1 by MichaelM04 for API(s) 1.13.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
MassiveEconomy 1.0 R3 by EvolSoft for API(s) 1.9.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
OreBroadcast 0.0.1 by Falkirks for API(s) 1.9.0
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
PlanB 1.2.0 by Gamecrafter for API(s) 1.10.0
PocketDockConsole 0.0.14 by humerusj for API(s) 1.0.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
PopupDisplayer 2.0.1 by Heromine, Flavius12 for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 1.12.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SubnetBan 1.0.0 by  for API(s) 1.0.0
SurvivalFly 1.0.9 by Mentha Haplocalyx Alcatraz_Du for API(s) 1.9.0
TAGBlock 0.3-Alpha by hm for API(s) 1.4.1
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TierLoot 1.0.0 by XFuryMCPE for API(s) 1.12.0

any solutions for this? there are some plugins i cant live without that are causing the crashes

**Comment by Muqsit** [comment]
Since PHP7, there has been a small change in the pocketmine/nbt/tag/*

Before (PHP5)...
use pocketmine\nbt\tag\Compound;
use pocketmine\nbt\tag\Enum;
use pocketmine\nbt\tag\Double;
use pocketmine\nbt\tag\Float;
use pocketmine\nbt\tag\Byte;
and so on...

Now (PHP7)...
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\nbt\tag\EnumTag;
use pocketmine\nbt\tag\DoubleTag;
use pocketmine\nbt\tag\FloatTag;
use pocketmine\nbt\tag\ByteTag;
and so on...

**Comment by Muqsit** [comment]
The error
`Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name`
can be fixed by modifying the plugin and changing

`use pocketmine\nbt\tag\Float`
to
`use pocketmine\nbt\tag\FloatTag`

**Comment by PocketKiller** [comment]
what do you expect? tell the author to update

**Comment by flaxues** [comment]
https://github.com/flaxues/SignShop

Try this one :)

**Comment by DesPlaysMC** [comment]
mk now i get it. thanks all

**Comment by DesPlaysMC** [comment]
but muqsit if i edit the tag files name like "FloatTag" into "Float", will it affect the server? i got too may plugins to fix @_@

**Comment by PeratX** [comment]
You plugins are not designed under PM API 2.0.0
