### ISSUE TITLE
Monster Spawner

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#244]
Monster spawner summon mobs? Becouse i think it dont work

**Comment by gaoyichuan** [comment]
They actually work. If you think they don't, please submit a way to reproduce the issue.

**Comment by astersx** [comment]
Mobs dont spawn on spawner,  or what is spawner supposed to do?

**Comment by gaoyichuan** [comment]
@astersx The spawners do work in my server. I think you should check your configures carefully, maybe you are in Peaceful Mode.
