### ISSUE TITLE
Inventory Reset

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#246]
Players keep losing stuff and all players complain!!!!
It happened after i update to php7 😢!!
I activated,  redstone,hunger, mobs,  and mobs generator,,,
Is one of these function at fault? Oh ya and weather too!!

**Comment by astersx** [comment]
It happen to me too :0

**Comment by astersx** [comment]
Ohhh! Really? It happen to me too,  but now i relogin 3 times to get stuff back.... But not many are lucky and they lose stuff!!!!!!  In php5 i didnt have this problem,  this is why i was so happy about genisys but..... 😓

**Comment by gaoyichuan** [comment]
I haven't got all the issues you have report, if you have, give some pictures or a way to reproduce the issue. OR YOU JUST STOP SPAMMING HERE, IN THE ISSUE TRACKER!

**Comment by astersx** [comment]
![screenshot_2016-02-07-12-38-12](https://cloud.githubusercontent.com/assets/13157548/12871880/069d0362-cd97-11e5-8011-da94563659e7.png)

Belive me , i dont wanna waste my time in confusing genisys team, i use this core on my servers becouse it seems the most stable build!!! I had a plugin keepinventory and genesis keepinventory(built in ) was off!!!  
Now i removed keepinventory plugin and i turn on genesis keepinventory!!!

Hope this was the problem 😄!!!

I really Hope genisis will always stay active 😍

**Comment by astersx** [comment]
I rebooted PC,   and some players inventory erased...  
How is that posible?

**Comment by RandomAltThingy** [comment]
Probably didn't save

**Comment by astersx** [comment]
save-all   save inventory too?

**Comment by RandomAltThingy** [comment]
I think so. Check the code if you're not sure.

**Comment by astersx** [comment]
Just experienced again,  i use a no Oped player to ocasionaly play on my server.  Server did not restart, so is not "save" fault!! My inventory was empty,  i log off then log in again all items back!!  Yay.
The problem is,  players dont know that they need to relogin and they get new items from chests and if they relogin inventory reset is permanent! I will make a video if i experience again!! This time i forgot.
