### ISSUE TITLE
TnT

### ISSUE THREAD

**Issue by MilkoIvanov** [iTXTech/Genisys#247]
The TnT is not exploding if there is another TnT in its radius.

**Comment by gaoyichuan** [comment]
Tested on my server, the TNT explodes when there are five TNTs around it. Which version are you using?

**Comment by MilkoIvanov** [comment]
Well I'm wirh the last version

**Comment by gaoyichuan** [comment]
Have some more try.. I can't reproduce the issue so I can't make the fix..

**Comment by MilkoIvanov** [comment]
Could it be from the binary files?

**Comment by gaoyichuan** [comment]
I don't think so.

**Comment by MilkoIvanov** [comment]
Well thanks I'll try to reinstall the server
