### ISSUE TITLE
PlayerJoin

### ISSUE THREAD

**Issue by MilkoIvanov** [iTXTech/Genisys#248]
From a few days the players on my server told that when they try to connect their client crashes but if thry change their names to something else they are able to connect. It happend to me too and i had ti delete the Player.dat to be able to connect but its pretty annoying as its deleting your inventory. Any help? I don't know how you can reproduce it because ita random

**Comment by astersx** [comment]
Ya,  there are some player who are able to use a item that crash the client. I exploded myself (in console),  to be able playing,  becouse i keep crashing!!!!!  And that item was destroyed and i got freed!!!!

**Comment by MilkoIvanov** [comment]
Amm that's not the problem. The problem is that some players are unable to join the server because of their names. If they try to connect their client just crash. And I have to delete the player.dat file but that's not a solve because they loose all inventory.

**Comment by PeratX** [comment]
They used some unsupported items or the chunk has some unsupported blocks

**Comment by gaoyichuan** [comment]
@MilkoIvanov Maybe there names contain some invaild syntaxes. If you could give me some of their names, I can try to reproduce it.

**Comment by PeratX** [comment]
Please give us their player.dat

**Comment by MilkoIvanov** [comment]
Ok one of the names is Protonim_BGR and here is his dat
[protonim_bgr.zip](https://github.com/iTXTech/Genisys/files/121624/protonim_bgr.zip)
Changed the .dat to .zip because i can't upload it in .dat format
