### ISSUE TITLE
[Question] Can u add loadbalancing proxy system based on changing of sockets? 

### ISSUE THREAD

**Issue by darkspive** [iTXTech/Genisys#249]
Sry it is not issue.I know it. I have server with 150 players and i need loadbalancing. Your genisys cant keep up my players. I cant setup roundrobin bind dns. It is very hard.
Can u create new branch with proxy system?

**Comment by darkspive** [comment]
U can close my issue. But i can help u...

**Comment by PeratX** [comment]
load balancing...

**Comment by PeratX** [comment]
Can you upload your timings file?

**Comment by gaoyichuan** [comment]
Do you need to sync the data between the servers?

**Comment by flaxues** [comment]
PeratX what he means is he wants you to make a proxy system so he can make multiple servers and clients can connect to them just like the transfer packet thingy that is removed.

**Comment by jasonczc** [comment]
I just wrote a plugin that can sync inventory and some lv/money/vip/etc. data between servers by MySQL.
But how to do with temporal data has not been decided= =..
I want to use Redis to solve these problem.
Now I think maybe using sockets is also OK .

**Comment by PeratX** [comment]
Very difficult...

**Comment by jasonczc** [comment]
@PeratX 不行我吹boi吹不下去了= =

**Comment by jasonczc** [comment]
If U run your servers in ONE server.You can link the data folder by system.That's a very simple method.

**Comment by darkspive** [comment]
I wanna create it in github.com/undrfined/Hydround

**Comment by darkspive** [comment]
Create loadbalancing system

**Comment by jasonczc** [comment]
The idea is great,but that's not our work.
So it's not an issue.
I closed it.
