### ISSUE TITLE
add php5 0.14.0 branch

### ISSUE THREAD

**Issue by SuperAdam47** [iTXTech/Genisys#254]

**Comment by MasterWolf** [comment]
yes plz. it will be cool :)

**Comment by gaoyichuan** [comment]
The php5 branch is already for 0.14

**Comment by MasterWolf** [comment]
@gaoyichuan but how to download it as phar file?

**Comment by RandomAltThingy** [comment]
@MasterWolf It may be compiled from Travis but if not and you have Linux do these commands:
```bash
sudo apt-get install git

git clone https://github.com/itxtech/Genisys

cd Genisys

git checkout origin/php5

mkdir plugins
```

You will need the **"bin"** folder that you got from the PocketMine setup wizard on https://PocketMine.net.

In the plugins folder you created, add the plugin called "DevTools". (The one by The PocketMine Team not Shoghicp, Shogi's one is outdated). Plugin can be found on PM forums. 

After that, start the server with <code>./start.sh</code>, set it up then type in console
```bash
makeserver Genisys
```
Then the phar will be in plugins/PocketMine-iTX

**Comment by MasterWolf** [comment]
@RandomAltThingy i havent linux. But im interested how to download from travis.ci?
