### ISSUE TITLE
Async Crash

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#263]
Crash:

Genisys Crash Dump Wed Feb 10 21:52:26 GMT 2016

Error: pthreads detected an attempt to connect to an object which has already been destroyed
File: /src/pocketmine/scheduler/AsyncTask
Line: 85
Type: notice

Code:
[76] 
[77] 	public function isCrashed(){
[78] 		return $this->crashed;
[79] 	}
[80] 
[81] 	/**
[82] 	 * @return mixed
[83] 	 */
[84] 	public function getResult(){
[85] 		return $this->serialized ? unserialize($this->result) : $this->result;
[86] 	}
[87] 
[88] 	public function cancelRun(){
[89] 		$this->cancelRun = true;
[90] 	}
[91] 
[92] 	public function hasCancelledRun(){
[93] 		return $this->cancelRun === true;
[94] 	}
[95] 

Backtrace:
#0 /LiveSigns-Master/src/aliuly/livesigns/FetchTask(80): pocketmine\scheduler\AsyncTask->getResult(boolean)
#1 /src/pocketmine/scheduler/AsyncPool(149): aliuly\livesigns\FetchTask->onCompletion(pocketmine\Server object)
#2 /src/pocketmine/scheduler/ServerScheduler(268): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#3 /src/pocketmine/Server(2885): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 15)
#4 /src/pocketmine/Server(2581): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2459): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(1990): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\Gebruiker\Desktop\Genisys\Genisys-master\PocketMine-MP.phar/, string C:\Users\Gebruiker\Desktop\Genisys\Genisys-master\, string C:\Users\Gebruiker\Desktop\Genisys\Genisys-master\plugins\)
#8 (1): require_once(string phar://C:/Users/Gebruiker/Desktop/Genisys/Genisys-master/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.0dev #0 [Protocol 39; API 2.0.0]
uname -a: Windows NT MATTHEW 10.0 build 10586 (Windows 10) AMD64
PHP version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
加载的插件:
EnderChest 1 by Matthww for API(s) 2.0.0
LiveSigns 1.2.1 by aliuly for API(s) 2.0.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0

**Comment by SleepSpace9** [comment]
This is caused by the LiveSigns plugin, so the author of the plugin has to solve it. The issue has been reported, but no response... :worried:: https://github.com/Muirfield/pocketmine-plugins/issues/48

**Comment by dog194** [comment]
Maybe you should ask the author to solve this problem.
