### ISSUE TITLE
WoodenButton

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#264]
![image](https://cloud.githubusercontent.com/assets/6584811/12970085/d4b609e4-d0ab-11e5-8134-521ce2b1a4cc.jpeg)

**Comment by CrayonDing** [comment]
When player touch it?

**Comment by xpyctum** [comment]
@CrayonDing I don't know. I see it today when trying to reload server.

**Comment by CrayonDing** [comment]
I maybe fixed it.
