### ISSUE TITLE
Genisys 0.13.x or 0.13.1 ?

### ISSUE THREAD

**Issue by NguyenQuangLap** [iTXTech/Genisys#270]
May I 0.13 x or is 0.13.1. phar is not, I don't see any of the phar 0.13.1 or 0.13.

**Comment by NguyenQuangLap** [comment]
@PeratX  ? -_-

**Comment by Muqsit** [comment]
You can download the zip file and then unzip it and use src

**Comment by Muqsit** [comment]
Use the command 'unzip master.zip' if you're on Linux.

To compile it you can download DevTools plugin and run Command 'makeserver' on console.

**Comment by PocketKiller** [comment]
@Muqsit's easy way :)
