### ISSUE TITLE
No border

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#273]
If I tp to far it's really buggy liek if there are 2-4 in each other and my screen is shaking...

To reproduce:

TP really far for example '/tp 103434 80 -428346

Video: https://youtu.be/wlB0vftSePE

**Comment by RandomAltThingy** [comment]
You TPed too far... This is only Pocket edition. I take away the number on the end maybe that might work.

**Comment by flaxues** [comment]
Yeah thats the problem in Pocketmine you had some kind of a border where the world just doesn't work and you couldn't move if you tped to far

**Comment by PocketKiller** [comment]
wait for the world to load, it'll load.

**Comment by flaxues** [comment]
No thats not the problem the problem is that the border is removed!

**Comment by PocketKiller** [comment]
I can't see the video, its private, make it unlisted not private.

**Comment by flaxues** [comment]
done

**Comment by PocketKiller** [comment]
that is also on Pocketmine.

**Comment by RandomAltThingy** [comment]
I have no idea what he means by border. If he means when the world stops generating proper (like far lands) then that's about 2million blocks away in PE.

**Comment by RandomAltThingy** [comment]
In PocketMine its 1million or something just don't tp more  than a million out.

**Comment by PEMapModder** [comment]
Are you referring to farlands? This is related to an OpenGL issue, which is system-dependent, where floating point precision numbers become not precise at high ranges.

**Comment by PocketKiller** [comment]
when you move while far, you don't move, until some time passes then you will be moving like the time you where moving.

**Comment by PeratX** [comment]
Too big !
