### ISSUE TITLE
Crash -_-

### ISSUE THREAD

**Issue by Marttinek** [iTXTech/Genisys#275]
http://pastebin.com/raw/2FvAJP5E

**Comment by CrayonDing** [comment]
you need to change your allow memory size.

**Comment by Marttinek** [comment]
256M, 512M, 1024M, 2048M, -1, 19999M = crash...

**Comment by Efforto** [comment]
Full memory.Try to update Genisys to new version or check maps and plugins in your server.
Maybe you can change some settings in pocketmine.yml.

**Comment by PeratX** [comment]
Already have one same issue
