### ISSUE TITLE
getSeed crash

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#277]
Genisys Crash Dump Sat Feb 13 08:19:09 GMT 2016

Error: Return value of pocketmine\level\Level::getSeed() must be of the type integer, string returned
File: /src/pocketmine/level/Level
Line: 2943
Type: notice

Code:
[2934] 		$this->sendTime();
[2935] 	}
[2936] 
[2937] 	/**
[2938] 	 * Gets the level seed
[2939] 	 *
[2940] 	 * @return int
[2941] 	 */
[2942] 	public function getSeed() : int{
[2943] 		return $this->provider->getSeed();
[2944] 	}
[2945] 
[2946] 	/**
[2947] 	 * Sets the seed for the level
[2948] 	 *
[2949] 	 * @param int $seed
[2950] 	 */
[2951] 	public function setSeed($seed){
[2952] 		$this->provider->setSeed($seed);
[2953] 	}

Backtrace:
#0 /src/pocketmine/Server(1192): pocketmine\level\Level->initLevel(boolean)
#1 /src/pocketmine/Server(1945): pocketmine\Server->loadLevel(string Lobby)
#2 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Driesc\Desktop\PhP-7 server\Lobby V3\, string C:\Users\Driesc\Desktop\PhP-7 server\Lobby V3\, string C:\Users\Driesc\Desktop\PhP-7 server\Lobby V3\plugins\)

Genisys version: 1.0dev #0 [Protocol 38; API 2.0.0]
uname -a: Windows NT DRIESC-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
PHP version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
加载的插件:
1vs1 0.0.6 by  for API(s) 1.0.0, 1.1.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
AfkKick 1 by XxDXM_hippiexX for API(s) 1.11.0, 1.13.0
BetaTester 0.14.0 alpha build 4 by PeratX for API(s) 1.13.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ChatLogin 1.4 by EvolSoft for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ColorMatch 1.1.1 by CreeperFace for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
FactionsPro 1.5b3 by Tethered_ for API(s) 1.12.0
GoogleAnalytics 1.0.0 by  for API(s) 1.0.0
HealthTag 1 by EnderKenji for API(s) 1.3.1
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
LIAB 1.0.0 by aliuly for API(s) 1.10.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
PurePerms 1.3.0-BETA-1 by 64FF00 for API(s) 1.13.0
RestartMe 1.1.0 by Gamecrafter for API(s) 1.10.0
RocketPads 1.0.0 by Gamecrafter for API(s) 1.12.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
Slapper 1.2.9.3_PHP7 by jojoe77777 for API(s) 1.12.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.4-INDEV by 64FF00 for API(s) 1.11.0
KillRate 2.1.1 by aliuly for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by Driesboy** [comment]
and work on php5

**Comment by Driesboy** [comment]
i think taga its the problem

**Comment by Driesboy** [comment]
and yes newest version

**Comment by PEMapModder** [comment]
@64FF00 :grin:

**Comment by Driesboy** [comment]
help me plz

**Comment by Driesboy** [comment]
Why

**Comment by Driesboy** [comment]
and only on windows not on apple or linux

**Comment by Driesboy** [comment]
and if you dont set it as default

**Comment by Driesboy** [comment]
if you not set it to default the level load and work

**Comment by Driesboy** [comment]
reopen
