### ISSUE TITLE
Slapper

### ISSUE THREAD

**Issue by FIRERO** [iTXTech/Genisys#278]
Plugin Slapper doesn't work on this core :/ Not on php 5 and not on php 7 It's very bad

**Comment by Driesboy** [comment]
use the newest version

**Comment by FIRERO** [comment]
And what about plugin TagBlock? It doesn't work too!

**Comment by Efforto** [comment]
Hey!Why don't try FNPC?It's powerful

**Comment by FIRERO** [comment]
Where may I download FNPC?

**Comment by Efforto** [comment]
ooops,FNPC is in Chinese,not English:(
But you can download in this link:https://coding.net/u/FENGberd/p/FNPC
And this is the donate link:https://pl.zxda.net/plugins/11.html
:P

**Comment by Efforto** [comment]
ooops,FNPC is in Chinese,not English:(
But you can download in this link:https://coding.net/u/FENGberd/p/FNPC
And this is the donate link:https://pl.zxda.net/plugins/11.html
:P

**Comment by Efforto** [comment]
@fengberd (#Huaji)

**Comment by FIRERO** [comment]
Thanks a lot! Can you give me something like a plug Tag Block

**Comment by Efforto** [comment]
i dont.know what's TapBlock's features:/

**Comment by FIRERO** [comment]
TagBlock* https://forums.pocketmine.net/plugins/tagblock.1064/

**Comment by Driesboy** [comment]
livesign php7
