### ISSUE TITLE
0.13.2 and 0.14 together as Lifeboat or BrokenLens

### ISSUE THREAD

**Issue by darkspive** [iTXTech/Genisys#281]
Can u update your branch of php7-0.14? I wanna that will be works 0.14 & 0.13.2  versions together
Sorry for my english...

**Comment by PeratX** [comment]
@darkspive Check here https://github.com/PeratX/BetaTester

**Comment by flaxues** [comment]
But Perat lifeboat supports 0.13 and 0.14 on the same port!

**Comment by PocketKiller** [comment]
we do not want that - I'll cause problems.

**Comment by PEMapModder** [comment]
What problems

**Comment by PeratX** [comment]
@PEMapModder how!

**Comment by PEMapModder** [comment]
?

**Comment by flaxues** [comment]
They don't know how...

**Comment by PEMapModder** [comment]
If you know how to let them join, what is so hard about letting multiple join?
