### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#284]
If you press the bone (or other subject - I did not check ) on the TRAPPED_CHEST crashes minecraft.

**Comment by astersx** [comment]
Reboot your phone!!

**Comment by PocketKiller** [comment]
@astersx that's an invalid solution.

**Comment by astersx** [comment]
This is what i did,  from experience!!  I crashed x10 times with a bow in hand or if i try to sellect a block!!!
Until i reboot tablet,  (quand core,  1gb ram)
