### ISSUE TITLE
Chunks in 0.14

### ISSUE THREAD

**Issue by darkspive** [iTXTech/Genisys#286]
Very very luggy chunks in 0.14.....
When i install 0.13 chunks works good

**Comment by PocketKiller** [comment]
MCPE Bug.

**Comment by darkspive** [comment]
Developer of pocketmine++ said me that it is problem of protocol

**Comment by PocketKiller** [comment]
@mixailenko5 ?

**Comment by darkspive** [comment]
Yeah

**Comment by darkspive** [comment]
Please! Please! FIX IT!!!!!
I cant install MiNet on linux.
![screenshot_2016-02-14-22-02-42](https://cloud.githubusercontent.com/assets/14966273/13035022/e8036556-d366-11e5-93a1-2ec31545cba8.png)

**Comment by darkspive** [comment]
It is so so annoyed!

**Comment by PocketKiller** [comment]
oh thanks for the pic - I thought it was that batchPacket.
also what is MiNET doing here -_-

**Comment by darkspive** [comment]
Minet works without any laggs and support 1000 players
Pm 100-150 player max. And laggs...

**Comment by PEMapModder** [comment]
Then don't use any Minecraft server software written in PHP.

**Comment by darkspive** [comment]
And MiNet deleted support of linux

**Comment by darkspive** [comment]
(0(((((

**Comment by PEMapModder** [comment]
MiNET didn't delete support for Linux, I believe?

**Comment by darkspive** [comment]
Genisys is best right now.... :(0(((( i havent windows os....

**Comment by darkspive** [comment]
It is currently

**Comment by PocketKiller** [comment]
would you please mind mixing all that in one comment?

**Comment by darkspive** [comment]
I did not understand the question. I do not know much English

**Comment by Driesboy** [comment]
Set all info in 1 comment

**Comment by darkspive** [comment]
Ok

**Comment by darkspive** [comment]
Damn.... Its is hars

**Comment by PEMapModder** [comment]
First of all, anything written in PHP will never be good at doing CPU-intensive operations like games. And this is the case for Minecraft servers.

**Comment by darkspive** [comment]
I want to at least working chunks....

**Comment by darkspive** [comment]
When  will be fix it?

**Comment by PeratX** [comment]
@darkspive Change your batch-threshold bigger then 256 in pocketmine.yml (bug of 0.14.0)

**Comment by darkspive** [comment]
It is not fixed
![screenshot_2016-02-15-19-31-29](https://cloud.githubusercontent.com/assets/14966273/13051380/c7b51e2a-d41a-11e5-8ac8-f568a073deca.png)
![screenshot_2016-02-15-19-29-28](https://cloud.githubusercontent.com/assets/14966273/13051384/ce1c5792-d41a-11e5-8015-a164138f5225.png)
![screenshot_2016-02-15-19-29-09](https://cloud.githubusercontent.com/assets/14966273/13051388/d509a4c4-d41a-11e5-84e1-a1af8d64bb42.png)
