### ISSUE TITLE
Advanced Kits Bug

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#287]
So I have Advanced Kits problem and I have some kits that have potions in them but for some reasons when I drink the potion it doesn't work

**Comment by Driesboy** [comment]
i think its a give potion bug and not advanced kits fault

**Comment by Driesboy** [comment]
advanced kits work good for me

**Comment by TheGalaxyLord** [comment]
I am using 0.13 PHP7 maybe ur using another version

**Comment by Driesboy** [comment]
no

**Comment by PocketKiller** [comment]
@TheGalaxyLord unsure

**Comment by flaxues** [comment]
Did you tryed to drop the potions and pick them up again?

**Comment by Driesboy** [comment]
haha i had this problem with im and food

**Comment by TheGalaxyLord** [comment]
Yep and I still can't drink the potions

**Comment by Muqsit** [comment]
It's not a problem with AdvancedKits/Genisys. If you use iProtector, you must enable touch flag for the region...I had this problem too :#
