### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#293]
Fatal error: Out of memory (allocated 788529152) (tried to allocate 86016 bytes) in C:\Users\Driesc\Desktop\Lobby V4\src\pocketmine\Player.php on line 4363

**Comment by Efforto** [comment]
Try to check ur plugins and maps.Or change your memory setting.

**Comment by Driesboy** [comment]
already done

**Comment by Efforto** [comment]
You can change ur pocketmine.yml to try:)

**Comment by Driesboy** [comment]
delete and all but i have this

**Comment by Efforto** [comment]
My server has memory leak too, and i give it 3072MB(I have a Linux Server):))

**Comment by Efforto** [comment]
so change the memory setting to 2048MB or larger...

**Comment by Driesboy** [comment]
but its after 20 hours

**Comment by Driesboy** [comment]
not direct memory goes up

**Comment by Efforto** [comment]
....Well...i have no idea:( , do you use PC for ur server?

**Comment by Driesboy** [comment]
yes but 8gb ram

**Comment by Driesboy** [comment]
i think its not the problem it have work with php5 perfect

**Comment by Efforto** [comment]
:) i have to do my homework...@CrayonDing
See ya~

**Comment by Driesboy** [comment]
ok

**Comment by Muqsit** [comment]
It also depends on your uptime. Restart your server every 1-2 hours!

**Comment by Driesboy** [comment]
yes but the memory leak is a problem
in php5 my server restarted every 24 hours

**Comment by PeratX** [comment]
@Driesboy Yes. pthreads. We will try

**Comment by Driesboy** [comment]
https://github.com/ImagicalMine/ImagicalMine/commit/9f2cba642e0942e7f1d5799f8bfdb131fd2939d5

**Comment by jasonczc** [comment]
You can check pocketmine.yml to turn down the number of threads.
That will not solve the bug,but can relief it.

**Comment by NML32** [comment]
I'm having the same issue where the memory keeps increases until the server finally crashes. I have two servers running one a flat plots server (no memory issues) the other a basic survival server that has the memory issue. I've done a lot of testing by removing plugins, disable Redstone, disable mob spawning, etc and nothing seemed to help. the last think I did was change the world to Flat and no more memory issues. When the world is set to Default the memory issues seem to come back.

**Comment by jasonczc** [comment]
@NML32  How many player online?

**Comment by NML32** [comment]
During my test I think the most at one time was 10 users.

**Comment by NML32** [comment]
Any thoughts or updates on this issue?  For me it only happens on Default worlds. The memory keeps climbing and GC doesn't free any memory and even when everyone leaves the server memory isn't freed up.

**Comment by PeratX** [comment]
We don't have a server to test... Please wait for some days...

**Comment by Driesboy** [comment]
Its only on genisys

**Comment by xpyctum** [comment]
@PeratX Okay, waiting c:

**Comment by Driesboy** [comment]
fixed
