### ISSUE TITLE
Genisys在php7下的性能表现如何？多人卡不卡？

### ISSUE THREAD

**Issue by zxl777** [iTXTech/Genisys#294]
很关心Genisys的表现，和其他Pocketmine非官方优化版本相比，有没有速度优势？

**Comment by CrayonDing** [comment]
首先php7较php5本身效率就有部分提升。另外，Genisys在0.11.0时代（PHP5）曾创下过1核1g阿里云主机进入70人流畅运行的记录。不过介于本身语言的问题，想到单端承载1000人不大可能。
