### ISSUE TITLE
Can you add this to wiki

### ISSUE THREAD

**Issue by RandomAltThingy** [iTXTech/Genisys#295]
This is an example of only allowing plugin to be loaded by Genisys, as some functions won't exist in normal PM and using this could mean that normal PocketMine plugins can have exclusive Genisys features.

https://gist.github.com/RandomAltThingy/dc23b76a0f656a93dc28

It's just a snippet, but if should work.

**Comment by CrayonDing** [comment]
Thx.

**Comment by RandomAltThingy** [comment]
And instead of code tags use
\```php
(Then paste the code)

\```
(At the end of the code)
So if will be one code block
