### ISSUE TITLE
刚刚测试了Readme下的服务器地址，一个也登录不了。

### ISSUE THREAD

**Issue by zxl777** [iTXTech/Genisys#297]
刚刚测试了Readme下的服务器地址，一个也登录不了。

Young Dream
地址: mcper.cn
端口: 19132

Young Dream - Survival
地址: mcper.cn
端口: 12345

Young Dream - Happy Town
地址: mcper.cn
端口: 666

Sai Gao Server
地址: sgmcpe.com
端口: 100

That the sky
地址: g.mcpe.cc
端口: 2333

Test Server
地址: mcper.cn
端口: 233

Zhy WAC Survival Server
地址: umcpe.com
端口: 888

**Comment by Efforto** [comment]
然后呢？登陆不了就来开issue占位置么？
Zhy的和赛高都可以用
不懂你们这些大神

**Comment by Efforto** [comment]
He's saying that No servers could be connected in Readme.ini
= =

**Comment by gaoyichuan** [comment]
mcper的机器不是炸了么

**Comment by CrayonDing** [comment]
不不不，就是炸了
