### ISSUE TITLE
http://mcper.cn/Genisys-Docs 不能访问

### ISSUE THREAD

**Issue by zxl777** [iTXTech/Genisys#298]
http://mcper.cn/Genisys-Docs 不能访问，请检查web服务是不是挂了。

**Comment by dog194** [comment]
是的，mcper暂时无法使用，Jenkins 可以用 两个用的不同服务器
Yes, the server "mcper.cn" is down temporary. but Jenkins is still work. because they use different server.

**Comment by zxl777** [comment]
我主要是要想找安装帮助，如果和pocketmine一样，就没问题了。

**Comment by dog194** [comment]
基本一样，你可以先尝试
