### ISSUE TITLE
0.14.0 alpha build 7 还不能登录，报告“服务器版本过旧”

### ISSUE THREAD

**Issue by zxl777** [iTXTech/Genisys#299]
建议象0.13.x 那样，自动兼容所有小版本。

**Comment by gaoyichuan** [comment]
build7都出来了？我们不知道。。

**Comment by dog194** [comment]
你可以在你的服务器自己修改版本号使其支持b7进服。怎么修改可以到php7-0.14分支 commit中查找
You can change some file in your server to make it support build7. Or make a pull request.
