### ISSUE TITLE
Errors during installation Genisys on Ubuntu with php7

### ISSUE THREAD

**Issue by gacus007** [iTXTech/Genisys#301]
Hi
I cant find tutorial how install Genisys on linux ,I 've got some errors during exe command : bash start.sh -r:
Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
13:58:32 [CRITICAL] Unable to find the Weakref extension.
13:58:32 [CRITICAL] Please use the installer provided on the homepage, or recompile PHP again.

I 've got Linux Ubuntu 15.10 x64

**Comment by gaoyichuan** [comment]
Genisys doesn't need Weakref support now. I think you may be using a older version

**Comment by gacus007** [comment]
@gaoyichuan thx ,how compile lastest version of Genisys?

**Comment by markkrueg** [comment]
@gacus007 To install lastest version of PHP7:

Do the following from whatever directory you wish to run Genisys from.
1) Download latest compile script
```
wget https://raw.githubusercontent.com/iTXTech/php-build-scripts/master/compile.sh
```
2) Compile PHP7 and support binaries
```
bash compile.sh -t linux64 -j 2 -c -f x86_64
```
You may run into errors during compile; and it will tell you what is missing. For example: If bison is missing, then do this:
```
apt-get install bison
```
Then repeat step 2 until it completes without error. Once you have your bin directory with PHP7 in it, you are ready to install Genisys.
3) Download current Genisys (confirm link to current Genisys by looking at http://jenkins.mcper.cn/job/Genisys-master/ ) and rename so it can be started.
```
wget http://jenkins.mcper.cn/job/Genisys-master/17/artifact/artifact/Genisys-master_Jenkins_%2317.phar
```
```
mv Genisys* PocketMine-MP.phar
```
4) Download current start script and start Genisys
```
wget http://raw.githubusercontent.com/iTXTech/Genisys/master/start.sh
```
```
bash ./start.sh
```
5) Follow the instructions to choose your language and Genisys will start. Note that it often segfaults. Just run it again using:
```
bash ./start.sh
```
You may have to do this 5 or 6 times before it stays running.

**Comment by PeratX** [comment]
Thx @markkrueg

**Comment by gaoyichuan** [comment]
Thanks a lot @markkrueg
