### ISSUE TITLE
RCON

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#302]
rcon not work :(
I'm online donations through Rcon, after the upgrade stopped working

**Comment by Efforto** [comment]
RCON not working?:)Well,we don't always use RCON in China...But you can try to change the files in the kernel...

**Comment by markkrueg** [comment]
I have tested RCON on current build from source in Master running PHP7. It works.

I am currently using port 19135. I have not tested on port 19132.

**Comment by PeratX** [comment]
@MrDoni98 Check GeniRCON Client
