### ISSUE TITLE
How create phar from repository?

### ISSUE THREAD

**Issue by gacus007** [iTXTech/Genisys#304]
How create phar from https://github.com/iTXTech/Genisys/tree/php7-0.14 
?I must have basic engine from pocketmine.net and then compile via dev tools ???

**Comment by PocketKiller** [comment]
use Jenkins provided on the README.

**Comment by gacus007** [comment]
Lastest build dont support 0.14 ... mcpe

**Comment by dog194** [comment]
look at the php7 branch

**Comment by gaoyichuan** [comment]
@gacus007 Look at the Genisys-php7-0.14 in jenkins
