### ISSUE TITLE
Bow

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#306]
Hi! Sometimes,  bows make players crash!!!  Well if is many players with bow,  at some time (" If someone see a player shooting the arrow,  he crash,  ofcourse the player who shoot crash too,  but this affect all players").  My kits server will be ruined if bows not fixed T.T
P.S. I crashed too!!! And maybe the problem may be the arrow,  i dont know :D,

**Comment by PocketKiller** [comment]
the arrow, when someone picks an arrow, all players that have that chunk loaded crashes.

**Comment by PocketKiller** [comment]
the arrow, when someone picks an arrow, all players that have that chunk loaded crashes.

**Comment by PocketKiller** [comment]
the arrow, when someone picks an arrow, all players that have that chunk loaded crashes.

**Comment by PocketKiller** [comment]
the arrow, when someone picks an arrow, all players that have that chunk loaded crashes.

**Comment by PocketKiller** [comment]
...

**Comment by xpyctum** [comment]
@PocketKiller okay. Can be this fixed?

**Comment by PeratX** [comment]
Can be fixed. Maybe tomorrow. Today I am very BUSY

**Comment by astersx** [comment]
Yay 😍

**Comment by PeratX** [comment]
Fixed.
