### ISSUE TITLE
PHP7 Linux 32Bit

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#308]
Is there a 32 bit of the PHP7 binaries i can download? When i try to run start.sh it says it cant find a working PHP binary. Thanks

**Comment by PEMapModder** [comment]
https://github.com/iTXTech/php-build-scripts/blob/master/compile.sh

**Comment by PeratX** [comment]
wget http://raw.githubusercontent.com/iTXTech/php-build-scripts/master/compile.sh
chmod 777 compile.sh
./compile.sh
Just wait.

**Comment by Skyladd** [comment]
Thank you very much. ImagicalMine people wouldnt help /.\

**Comment by PocketKiller** [comment]
@Skyladd we do help... use forums

**Comment by AndreyNazarchuk** [comment]
@PeratX Link no longer works

**Comment by ishitatsuyuki** [comment]
@AndreyNazarchuk Read the README, and ask questions on chat.

Please review the contribution guidelines before commenting.

[Read the FAQs](https://github.com/iTXTech/Genisys/wiki/FAQs)
[Contribution guidelines](https://github.com/iTXTech/Genisys/blob/master/CONTRIBUTING.md)
