### ISSUE TITLE
0.14 To-Do

### ISSUE THREAD

**Issue by Muqsit** [iTXTech/Genisys#311]
1. Add Witches AI
2. Add Cauldrons
3. Redstone enhancements (double trapped chests, comparators, repeaters, hoppers)
4. Slime Blocks
5. Items (Maps, Witch Spawn Egg)

**Comment by PocketKiller** [comment]
Cauldrons are too hard..becauseit can mix dyes..

**Comment by Muqsit** [comment]
True

**Comment by Skyladd** [comment]
Why not just take the code from ImagicalMine? They have the chests and everything working for creative and redstone seems to be alright there.

**Comment by jasonczc** [comment]
@Skyladd
 So that they can laugh at us and deny the work of us.xD

**Comment by Muqsit** [comment]
ImagicalMine is way too laggy. I prefer genisys and only genisys!

**Comment by flaxues** [comment]
I agree Genisys is so much faster!

**Comment by jasonczc** [comment]
Thank for supporting us!xD

**Comment by meetloaf13** [comment]
@jasonczc No shame! =]  T. S. Eliot once said that “good writers borrow, great writers steal.”

Just give credit ;)

I really wish we could just create a master dev team.  Just came here after trying ClearSky & Bukkit, working Nether and the like, most impressive

**Comment by Tee7even** [comment]
>Add Witches AI
Add Cauldrons
Redstone enhancements (double trapped chests, comparators, repeaters, hoppers)
Slime Blocks
Items (Maps, Witch Spawn Egg)

_0.14 To-Do_ should actually be "fix all the bugs" :P

**Comment by jasonczc** [comment]
@meetloaf13
Most of Chinese developer are student.The schoolwork is so heavy.(For example,I only sleep 4-5hours in school days)So this year we could have less time to develop.
We welcome EVERYONE to join the development.

**Comment by meetloaf13** [comment]
@jasonczc I wish I could DEV, never been much of a code-head.  I'm an accountant in the middle of tax season though, putting in 80 hrs/wk so I know how the no-sleep things goes =]

You guys are great, love the product that you've put out. 

I was simply saying how awesome it would be if we had one master-product instead of dev teams competing...but now that I've been figuring out how the commits work on git and see some of the bread crumbs it looks like a lot of the work actually is shared.

**Comment by jasonczc** [comment]
I understand what you said xD.

**Comment by Muqsit** [comment]
I'm only good (more like 'Okay') at generation...I'm coding Mesa and Flower biomes right now. If they work, ill publish it!

**Comment by PeratX** [comment]
@Muqsit How about join @iTXTech?

**Comment by gaoyichuan** [comment]
@Muqsit It doesn't matter what thing you are good at, since myself is only good at commands. :) Just work on what you are good at is good enough
