### ISSUE TITLE
what is mean？how di deal with it?

### ISSUE THREAD

**Issue by potato520hjj** [iTXTech/Genisys#316]
ReflectionException: "Class pocketmine\event\player\PlayerJionEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 732

**Comment by flaxues** [comment]
Class pocketmine\event\player\PlayerJionEvent does not exist

The class doesn't exist you can try to change it to:

pocketmine\event\player\PlayerJoinEvent

**Comment by PocketKiller** [comment]
Plugin Fault.

**Comment by flaxues** [comment]
yeah a typo in the use
