### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by orangetictac** [iTXTech/Genisys#318]
Hello all! How i can download core from Travis CI?

**Comment by Skyladd** [comment]
0.14.0 ---> http://jenkins.mcper.cn/job/Genisys-php7-0.14/
Master---> http://jenkins.mcper.cn/job/Genisys-master/
I don't know how to download things from travis either.

**Comment by PocketKiller** [comment]
Travis is not like Jenkins.. it is that tick on pull requests
