### ISSUE TITLE
Upgrade to official 0.14.0 build?

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#322]
The official 0.14.0 is out now and was wondering if the server version could be changed thanks :D

**Comment by astersx** [comment]
it already changed to 0.14.0

**Comment by Skyladd** [comment]
Yeah but its the beta still. No official 0.14 people can join

**Comment by CLiu13** [comment]
I am having this issue too.

**Comment by PeratX** [comment]
But I can use win10 beta 0.14.0 to join!

**Comment by EnderKenji** [comment]
Jerkins has no update. Or tell us where can download the latest build?

**Comment by astersx** [comment]
Wtf,  i have official 0.14.0,  and can join,  dont make it hard for devs.

**Comment by Skyladd** [comment]
@astersx but does it have 0.14 items.?

**Comment by astersx** [comment]
Yes,  just some,  but gliched!!!  Genesis have no-lag core,  and is very stable,  and u can equip heads :+1:

**Comment by Skyladd** [comment]
Master doesnt work with PHP7 the issue still stands! official 0.14 cant join the 0.14 php7 !!

**Comment by CLiu13** [comment]
When I join my server using a fresh installation of Genisys PHP5 branch, the console says that I joined, but on my tablet, it just stays on Locating Server screen. Hopefully this will help you resolve the bug.

**Comment by CLiu13** [comment]
My issue is resolved, PHP5 branch works perfect with 0.14.0.
