### ISSUE TITLE
Nether Portal

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#324]
Nether portal works fine but one isnt created when you travel to the nether, so youre basically stuck there until you type /spawn or die

**Comment by PeratX** [comment]
Yes... I don't know how to write generator

**Comment by gaoyichuan** [comment]
That is a unimplemented feature.. Maybe we will work around it in the future

**Comment by Muqsit** [comment]
Noo! Listen!
If you have made a structure in the Nether, and you have protected it, and someone randomly makes a nether portal in the overworld. What if the nether portal generates on the protected structure in the Nether? It might mess up the structure!
