### ISSUE TITLE
Crash minecraft

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#326]
US:
Hangs minecraft when you use some symbols . The same happens when Broadcast message with symbols , then you just do not go to the server and minecraft freezes . This is NOT a problem with my device . It emerged after the transition of your kernel 0.14

RU:
Зависает майнкрафт когда ты используешь некоторые символы. Такое же происходит когда в броадкасте сообщение с символами, то ты просто не заходишь на сервер и майнкрафт зависает. Это проблема НЕ С МОИМ УСТРОЙСТВОМ. Это появилось после перехода вашего ядра на 0.14

**Comment by xpyctum** [comment]
Так это игра виновата, не?

**Comment by PocketKiller** [comment]
MCPE Issue, on iOS, symbols crash MCPE.

**Comment by MasterWolf** [comment]
проблема майнкрафта 100%

**Comment by PocketKiller** [comment]
EN?

**Comment by MasterWolf** [comment]
Its MCPE issue 100%
