### ISSUE TITLE
Please add a head

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#327]
Head that has already been added, but I would like to see Metadata for rotating the head.

**Comment by matthew4444** [comment]
Tou mean mob heads?

**Comment by Varfalomey** [comment]
yes

**Comment by Skyladd** [comment]
Heads can be placed in all directions. Not sure what youre talking about

**Comment by Muqsit** [comment]
^

**Comment by PeratX** [comment]
Mob head can be placed with different directions. Close
