### ISSUE TITLE
Warning: yaml_parse(): scanning error encountered during parsing: found character that cannot start any token (line 10, column 4), context while scanning for the next token (line 10, column 4) in C:\Users\Yeruchum\Desktop\Genisys-php5 19134 Creative server\src\pocketmine\utils\Config.php on line 143

### ISSUE THREAD

**Issue by Lucario2** [iTXTech/Genisys#328]
Warning: yaml_parse(): scanning error encountered during parsing: found character that cannot start any token (line 10, column 4), context while scanning for the next token (line 10, column 4) in C:\Users\Yeruchum\Desktop\Genisys-php5 19134 Creative server\src\pocketmine\utils\Config.php on line 143

**Comment by xpyctum** [comment]
Plugin issue.

**Comment by TheDiamondYT1** [comment]
@xpyctum When plugins cause yaml_parse() errors it mentions the name of the class... This says it happened in Genisys.

**Comment by jasonczc** [comment]
Plugin issue.If you edit your config of plugins is a wrong way,it will not work correctly.
Try to delete config of some plugins.
