### ISSUE TITLE
Jenkins not auto Compiling?

### ISSUE THREAD

**Issue by Nidish** [iTXTech/Genisys#329]
Where do i download the latest .phar file from ? please help me out guys .
Also How to download from Travis-CI

**Comment by Nidish** [comment]
Can Anyone Help me?

**Comment by PocketKiller** [comment]
@PeratX compile it.
@Nidish Travis CI is not like Jenkins, it's used to build/test pull request and commits, where you see the 'x' or the tick on pull requests, 'x' means build failed, the tick means build success, which you can run the server after merging the pull request.

**Comment by Nidish** [comment]
how do i get a compiled version now?

**Comment by Nidish** [comment]
@PocketKiller

**Comment by gaoyichuan** [comment]
I had add the automatic building in jenkins. Get the phar from jenkins.mcper.cn
