### ISSUE TITLE
Notice: Undefined index: api

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#330]
Notice: Undefined index: api in /home/matthew/daemon/src/pocketmine/plugin/PluginDescription.php on line 67

plugin.yml:
```
name: GoldenApple
main: GoldenApple\Main
version: 1.0
author: Matthww
api: [1.12.0]
```

**Comment by Skyladd** [comment]
This is a plugin issue. Either the plugin doesnt support PHP7 or the plugin has bugs. Contact the plugin author for issues.

**Comment by PocketKiller** [comment]
@Skyladd he made this plugin, not plugin issue because there is 'api' already, nothing with PHP7.

**Comment by PeratX** [comment]
Checked there is nothing wrong with PluginDescription
