### ISSUE TITLE
Redstone Block--No Power---Still

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#334]
I checked and redstone is enabled in the genisys.yml file i have pulsing enabled as well. This issue affects redstone lamps, they dont take power from anything but buttons, levers and pressure plates that are directly by them

**Comment by PeratX** [comment]
Can you upload a screenshot?

**Comment by Skyladd** [comment]
I cant because my tablet sucks but i can still confirm tat redstone blocks dont produce power

**Comment by PeratX** [comment]
No details. Close
