### ISSUE TITLE
Server time differs from system time

### ISSUE THREAD

**Issue by Garem** [iTXTech/Genisys#338]
Hi,

There are a few hours difference between the printout of the server and system time in my raspberry pi 2. 
I am not sure if this is related to the ARM PHP:
https://github.com/iTXTech/PHP-Genisys/issues/6

**Comment by SleepSpace9** [comment]
you have to set your timezone in **php.ini** (pocketmine/bin/php7/bin/php.ini)
````
date.timezone=...
```

**Comment by MilkoIvanov** [comment]
What is the format I mean what you have tobwrite after er the "="
