### ISSUE TITLE
WeakrefCrash

### ISSUE THREAD

**Issue by MilkoIvanov** [iTXTech/Genisys#339]
Tried to compile the latest updates into the Genisys.phar with /ms but after I've used the compiled version and run it without genisys.yml it crash the whole server.Anf the error is 'unable to find the weakreaf extension. Please uwe the installer provided on the home paga, ir recompile PHP again.'

**Comment by PeratX** [comment]
OK,we will remove WeakRef dependency.

**Comment by PeratX** [comment]
Checked. master branch does not require Weakref .
