### ISSUE TITLE
Item Frame bug

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#347]
![screenshot_2016-02-20-18-41-49](https://cloud.githubusercontent.com/assets/15629214/13196183/450c9c96-d802-11e5-8ca3-f99479a9f492.jpg)
:+1:

**Comment by PeratX** [comment]
How to reproduce it

**Comment by EnderKenji** [comment]
Wht do u mean reproduce?

**Comment by gaoyichuan** [comment]
@EnderKenji Reproduce the issue shown in the issue. If we can't reproduce it we can't fix it.

**Comment by EnderKenji** [comment]
Its happened when I place any blocks. 

Place ItemFrame > Place a block > become wht u saw up there

**Comment by gaoyichuan** [comment]
Well I can't even place a block in the frame.. :(

**Comment by Muqsit** [comment]
That isn't a "bug". That was meant to happen. I will tell you why!

In 0.14, you can access your survival inventory. When you hold a block form the creative inventory, you automatically get 64 of the blocks in your survival inventory.

Also reproduced if you hold 2+ amount of any block in your hand and tap the ItemFrame.(doesn't happen with *ITEMS* tho, just blocks - weird).

For now, you can switch to survival and /give your self ONE block!
If you tap ItemFrames with one block in your hand, that won't happen! If you tap ItemFrames with 2 or more amount of a block, that thing happens! But overall, ItemFrames are really stable!! :+1:
