### ISSUE TITLE
Genysis.yml 

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#349]
Hi! If i put check movement false,  server loads become so high, that it cant function well anymore!!
See my screenshoot!!
![screenshot_2016-02-20-14-43-13](https://cloud.githubusercontent.com/assets/13157548/13196744/f9449b3c-d7df-11e5-9004-640c4ce426b4.png)

**Comment by astersx** [comment]
Now i put again true,  and wait to see if loads are so high!!!

**Comment by astersx** [comment]
Not fixed!!!!!!!

**Comment by astersx** [comment]
It always freeze wen i put check movement false,  😔

**Comment by Efforto** [comment]
...Go and find PeratX or CrayonDing

**Comment by Efforto** [comment]
= =So sleepy.....
