### ISSUE TITLE
Enchanting?

### ISSUE THREAD

**Issue by yungtechboy1** [iTXTech/Genisys#35]
Any ideal when it'll be ready?

**Comment by astersx** [comment]
Is already loool -.-'

**Comment by PeratX** [comment]
We dont know the protocol...

**Comment by astersx** [comment]
Oh so enchanting is not? There are already xp,  so i tought is enchanting too

**Comment by yungtechboy1** [comment]
Ok, Ill Try and do some tests to find it XD

**Comment by thebigsmileXD** [comment]
https://forums.pocketmine.net/threads/log-packages-on-certain-action.14379/#post-141614

**Comment by Muqsit** [comment]
Nukkit has fully working enchantment table...but its written in java :3

**Comment by PeratX** [comment]
@Muqsit We have translated in php7-0.14 branch, but it does not work
