### ISSUE TITLE
Fishingrod

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#351]
If I spam the fishingrod my minecraft crashes

**Comment by PeratX** [comment]
Try to restart your MCPE and your phone. Fishing Rod is fine here.

**Comment by haniokasai** [comment]
realy?
my server was crashed by fishing rod.

**Comment by flaxues** [comment]
What error?

**Comment by haniokasai** [comment]
016-02-19 [07:12:58] [Server thread/CRITICAL]: TypeError: "Argument 3 passed to pocketmine\entity\FishingHook::__construct() must be an instance of pocketmine\Player, none given, called in /ramdisk/wall2/src/pocketmine/entity/Entity.php on line 445" (EXCEPTION) in "/src/pocketmine/entity/FishingHook" at line 43
2016-02-19 [07:12:58] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2016-02-19 [07:12:58] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2016-02-19 [15:38:17] [Server thread/INFO]:

**Comment by haniokasai** [comment]
maybe,in map,fishingrods are left.

**Comment by flaxues** [comment]
Do you have the latest version?

**Comment by haniokasai** [comment]
about 8 hours ago build.

**Comment by flaxues** [comment]
try the latest one on jenkins

**Comment by haniokasai** [comment]
ok,ill check it...
