### ISSUE TITLE
Can't open brewing stand or anvil

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#353]
If i want to open it it closes really fast!

**Comment by gaoyichuan** [comment]
They are not implemented yet.

**Comment by flaxues** [comment]
Brewing stand were implemented!

**Comment by gaoyichuan** [comment]
Have you enabled it in genisys.yml?

**Comment by flaxues** [comment]
yes I have and I can't place them either

**Comment by erkam2002** [comment]
I cant open anvil enchantment_table and brewingstand and i have enabled

**Comment by MilkoIvanov** [comment]
Same here

**Comment by PeratX** [comment]
Yes. 0.14.0 has changed chunk format(seems nbt). We are trying

**Comment by PeratX** [comment]
Just wait. I and MagicDroidX is working on it now!

**Comment by PeratX** [comment]
Fixed
