### ISSUE TITLE
Crash o.0

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#356]
Genisys Crash Dump Sat Feb 20 03:16:28 EST 2016

Error: Argument 1 passed to pocketmine\item\Item::__construct() must be of the type integer, string given, called in phar:///home/minecraft/multicraft/servers/server12/ImagicalMine-PHP7-0.14-b293.phar/src/pocketmine/item/Item.php on line 1169
File: /src/pocketmine/item/Item
Line: 1207
Type: notice

Code:
[1198] 				}
[1199] 			}else{
[1200] 				$item = self::get($b[0] & 0xFFFF, $meta);
[1201] 			}
[1202] 
[1203] 			return $item;
[1204] 		}
[1205] 	}
[1206] 
[1207] 	public function __construct(int $id, $meta = 0, int $count = 1, string $name = "Unknown"){
[1208] 		$this->id = $id & 0xffff;
[1209] 		$this->meta = $meta !== null ? $meta & 0xffff : null;
[1210] 		$this->count = $count;
[1211] 		$this->name = $name;
[1212] 		if(!isset($this->block) and $this->id <= 0xff and isset(Block::$list[$this->id])){
[1213] 			$this->block = Block::get($this->id, $this->meta);
[1214] 			$this->name = $this->block->getName();
[1215] 		}
[1216] 	}
[1217] 

Backtrace:
#0 /src/pocketmine/nbt/NBT(111): pocketmine\item\Item::get(string minecraft:sapling, integer 1, integer 1)
#1 /src/pocketmine/entity/Item(77): pocketmine\nbt\NBT::getItemHelper(pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:sapling.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:1.})
#2 /src/pocketmine/entity/Entity(283): pocketmine\entity\Item->initEntity(boolean)
#3 /src/pocketmine/entity/Entity(445): pocketmine\entity\Entity->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:0.00017849426271445.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:-0.0001459847403953.}.pocketmine\nbt\tag\LongTag:-6421386763107517706.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\FloatTag:177.0128326416.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:sapling.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:1.}.pocketmine\nbt\tag\LongTag:-3645599089946048564.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:1377.0780748486.pocketmine\nbt\tag\DoubleTag:42.pocketmine\nbt\tag\DoubleTag:368.2759331758.}.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\StringTag:Item.pocketmine\nbt\tag\ShortTag:36.})
#4 /src/pocketmine/level/format/generic/BaseFullChunk(148): pocketmine\entity\Entity::createEntity(string Item, pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:0.00017849426271445.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:-0.0001459847403953.}.pocketmine\nbt\tag\LongTag:-6421386763107517706.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\FloatTag:177.0128326416.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:sapling.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:1.}.pocketmine\nbt\tag\LongTag:-3645599089946048564.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:1377.0780748486.pocketmine\nbt\tag\DoubleTag:42.pocketmine\nbt\tag\DoubleTag:368.2759331758.}.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\StringTag:Item.pocketmine\nbt\tag\ShortTag:36.})
#5 /src/pocketmine/level/Level(2692): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#6 /src/pocketmine/level/Level(660): pocketmine\level\Level->loadChunk(integer 16, integer 16)
#7 /src/pocketmine/Player(853): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(1), integer 86, integer 23, boolean 1)
#8 /src/pocketmine/Player(2061): pocketmine\Player->sendNextChunk(boolean)
#9 /src/pocketmine/Server(2918): pocketmine\Player->checkNetwork(boolean)
#10 /src/pocketmine/Server(2608): pocketmine\Server->tick(boolean)
#11 /src/pocketmine/Server(2486): pocketmine\Server->tickProcessor(boolean)
#12 /src/pocketmine/Server(2019): pocketmine\Server->start(boolean)
#13 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server12/ImagicalMine-PHP7-0.14-b293.phar/, string /home/minecraft/multicraft/servers/server12/, string /home/minecraft/multicraft/servers/server12/plugins/)
#14 (1): require_once(string phar:///home/minecraft/multicraft/servers/server12/ImagicalMine-PHP7-0.14-b293.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux unassigned.psychz.net 4.3.3-1.el6.elrepo.x86_64 #1 SMP Tue Dec 15 13:13:15 EST 2015 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0

**Comment by gaoyichuan** [comment]
Which version are you using?

**Comment by EnderKenji** [comment]
Latest from jenkins

**Comment by gaoyichuan** [comment]
@EnderKenji Don't use that version(a possible bug is inside it). Use build #19, I tested it

**Comment by EnderKenji** [comment]
But when u guys will fix this?

**Comment by gaoyichuan** [comment]
I don't know... since I have no time these days..

**Comment by gaoyichuan** [comment]
But what's that???
```
ImagicalMine-PHP7-0.14-b293.phar
```

**Comment by PocketKiller** [comment]
Hmm... Where did this get called?

**Comment by gaoyichuan** [comment]
/src/pocketmine/nbt/NBT(111):

**Comment by PocketKiller** [comment]
How can you reproduce this?

**Comment by PeratX** [comment]
Fixed

**Comment by PeratX** [comment]
Seems using a PC map.
