### ISSUE TITLE
error

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#357]
Server thread/CRITICAL ReflectionException: "Class CyberTech\BlockBreakEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 728

**Comment by gaoyichuan** [comment]
That's a plugin issue, submit it to the plugin's repo, not this one

**Comment by erkam2002** [comment]
i havent a plugin with the name cybertech
