### ISSUE TITLE
Items Glich

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#361]
Hi! It seems,  wen server have low tps,  items tend to glich and dissapear!! I logged in ,  i walk and i was pulled back,  at that moment all items gone!!! 

i got items back with relogin,  but many players complain that items gliches!

i have keepinventory on!!!

**Comment by Muqsit** [comment]
Weird, happens on my server too!

**Comment by flaxues** [comment]
Having this to even without lag!

**Comment by TheDiamondYT1** [comment]
#BlameShoghicp

**Comment by astersx** [comment]
So there is no way to fix? T.T

**Comment by Muqsit** [comment]
Technically, everything is possible. There probably is a fix for this. I don't think this happens in the official PocketMine-MP but who uses it lol.
Btw, I'm gonna make a slimeblock pr :)

**Comment by gaoyichuan** [comment]
I haven't run into such a situation. Please submit a detailed list of the Plugins you are using and the version of Genisys you are using

**Comment by Muqsit** [comment]
I think it were the plugins. I never knew the API was bumped to 2.0.0 so I changed all my plugins' api version

**Comment by astersx** [comment]
Hi,  i had the problems with my survival,  and factions server!!!
Factions dont use many plugins! 
Netherchests, Alias, ServerAuth, AdminFun,Block Effects, Chat defender, Economy Api,  Economy Land,
I protector, Lighting on dead, Pureperms,  purechat, RestartMe, SimpleHome, TapToDo, TimeComander, World Protect, Magic teleportal,  Mspawns.

**Comment by Muqsit** [comment]
Do any of the plugins show errors in console?
