### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#362]
Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\nbt\NBT::putItemHelper() must be an instance of pocketmine\item\Item, null given, called in phar:///home/Desktop/Server/PocketMine-iTX.phar/src/pocketmine/entity/Item.php on line 165" (EXCEPTION) in "/src/pocketmine/nbt/NBT" at line 83

**Comment by gaoyichuan** [comment]
PocketMine-iTX.phar
Are you using such an old version?
