### ISSUE TITLE
Feature request: add an option to disable throwing potions

### ISSUE THREAD

**Issue by tankisu01** [iTXTech/Genisys#367]
Title says all.

Needed especially for php5 :(

**Comment by Skyladd** [comment]
Honestly bud, i think there has to be a line drawn in the sand, as technology advances people should upgrade. If your server cant handle potions id recommend getting a new host/server. If they were to take all feature requests like yours into consideration eventually everything would be toggle-able. I recommend getting WorldProtect plugin and banning the potion item

**Comment by MasterWolf** [comment]
@Skyladd wait i have BanItem ( or ItemBan xD I forgot ) plugin on my server and i cant ban bucket of lava... Why?? Or maybe i entered incorrect id?

**Comment by TheKillerTacos** [comment]
Maybe incorrect ID,
