### ISSUE TITLE
Some bugs? 

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#368]
# **1, The stairs'  shadow?**
![screenshot_2016-02-21-19-07-40](https://cloud.githubusercontent.com/assets/15629214/13202245/a6b88e88-d8ce-11e5-8edc-1657510669b1.jpg)
I broke and replace it again, but still.

# **2, Chunk loading? **
![screenshot_2016-02-21-17-12-44](https://cloud.githubusercontent.com/assets/15629214/13202255/1685be48-d8cf-11e5-87fe-232f56b3bf74.jpg)
The chunk loding its lagg and slow. Its not the same as before... is this bug or?

# **3, Break block particles**
When u break block, the particles will appear after 1 sec when u broke a block, please fix.

**Comment by xpyctum** [comment]
1. MCPE issue?
3. MCPE issue?

**Comment by PeratX** [comment]
only second maybe Genisys problem.

**Comment by PeratX** [comment]
Checked,second issue is MCPE's issue. When you to high, it will auto disappear.

**Comment by xpyctum** [comment]
@PeratX fix third issue :C

**Comment by smyb** [comment]
2nd is mcpe issue

**Comment by darkspive** [comment]
Please FIX CHUNKS!!!
IT IS SO! SO! ANNOYED!!!
![screenshot_2016-02-15-22-47-50](https://cloud.githubusercontent.com/assets/14966273/13203042/3222e360-d8cf-11e5-8626-5ff7ef120822.png)

**Comment by darkspive** [comment]
![screenshot_2016-02-15-19-29-28](https://cloud.githubusercontent.com/assets/14966273/13203049/6614db9c-d8cf-11e5-839d-755bb8ca70fb.png

**Comment by smyb** [comment]
@darkspive isn't a genisys bug-issue

**Comment by darkspive** [comment]
![screenshot_2016-02-15-19-29-28](https://cloud.githubusercontent.com/assets/14966273/13203054/7eba1f90-d8cf-11e5-9f8b-915c1cbd426c.png)

**Comment by darkspive** [comment]
It is genisys becouse coordinates of y = 15

**Comment by darkspive** [comment]
Any coordinates chunks is not load

**Comment by darkspive** [comment]
It is on all russian servers.... 0.14
Please fix it!

**Comment by xpyctum** [comment]
@darkspive
Write it in one message. Not flooding. 
Try use another map. It's not Genisys issue.

**Comment by BlackShadow1** [comment]
@smyb it is. In Yuriko it doesn't happen.

**Comment by darkspive** [comment]
![screenshot_2016-02-21-19-22-38](https://cloud.githubusercontent.com/assets/14966273/13203087/88d7d70a-d8d0-11e5-9276-929e4ff6504e.png)



It is genisys generation

**Comment by darkspive** [comment]
They recognized the mistake and you do not.
![screenshot_2016-02-21-19-26-42](https://cloud.githubusercontent.com/assets/14966273/13203122/3cf63358-d8d1-11e5-90f5-d35a683c0b8a.png)

**Comment by EnderKenji** [comment]
BrokenLens have no this chunks issue. I think its not MCPE's prob.

**Comment by EnderKenji** [comment]
The 3rd issue is not MCPE's issue. I tested on single player.

**Comment by gaoyichuan** [comment]
@darkspive Don't mention IM here, or you may fall into a annoying situation. DON'T ask why.

**Comment by gaoyichuan** [comment]
I think chunks bug maybe about your network brand since this thing heavily depends on the brand..

**Comment by PeratX** [comment]
MCPE does not add Particle any more. We must add DestroyBlockParticle to Client. So will have delay

**Comment by PeratX** [comment]
First is MCPE issue. Second is fixed. Third is related to bandwidth. close
