### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#370]
With the new compile.sh my server freezes!

**Comment by gaoyichuan** [comment]
Compling do need a lot system resources... So that's not an issue

**Comment by flaxues** [comment]
No thats not what I mean what I mean is when I have the server started after like 2-3 mins it just freezes...

**Comment by gaoyichuan** [comment]
That's nothing to do with the compile.sh.. Compiled php binary is the same as the one you downloaded from somewhere else.. Since they are just compiled by other people

**Comment by flaxues** [comment]
I have the same problem as #376
