### ISSUE TITLE
Mobs are hit when right-clicked (long tap)

### ISSUE THREAD

**Issue by Tee7even** [iTXTech/Genisys#374]
Right click and left click are different, you know?

**Comment by PeratX** [comment]
Can be hurt in single play too.

**Comment by Tee7even** [comment]
Um, clearly NOT.
![image](https://cloud.githubusercontent.com/assets/6763610/13214261/a672b0e8-d95f-11e5-8cf2-3a17b42ce2f2.png)

**Comment by PeratX** [comment]
Win10 0.14.0 can!

**Comment by Tee7even** [comment]
Did you check it?

**Comment by PocketKiller** [comment]
I can from 0.10.0 to 0.14.0.

**Comment by Tee7even** [comment]
Are you two joking? ._. It was **NEVER** possible to hurt mobs by right-clicking (or long-tapping) them in minecraft, both in PC version and PE. And isn't possible now. Both in MCPE and MCW10E.
Maybe you don't understand what I'm talking about? THIS is right-click:
![image](https://cloud.githubusercontent.com/assets/6763610/13221537/01cc3e46-d98d-11e5-9f9d-45f2767de489.png)
Long-tap is when you tap the screen for long time.

**Comment by PocketKiller** [comment]
Yes, I tapped the screen long time.

**Comment by Tee7even** [comment]
Sorry, WTF? You now trying to challenge a pretty obvious thing for anyone who ever played Minecraft! As I said earlier:
>It was **NEVER** possible to hurt mobs by right-clicking (or long-tapping) them in minecraft, both in PC version and PE. And isn't possible now. Both in MCPE and MCW10E.

_Please Understand:_ it always was like this. Right-clicking (long-tapping on entities in PE) is for **USING** items (on entities in particular), it was **NEVER** used for attacking! Proofs anywhere, for example, Minecraft Wiki: http://minecraft.gamepedia.com/Controls
I don't know why it's different for you. Either it's some kind of client bug or you just didn't even bother to really check it.

**Comment by PocketKiller** [comment]
I am TOO blind.

**Comment by thebigsmileXD** [comment]
@PeratX Totally incorrect xD

https://github.com/PocketMine/PocketMine-MP/commit/7ba7eaf303fbd69ffaf9cd473098c13a3978e769

https://github.com/ClearSkyTeam/ClearSky/commit/d2601db5aab68d100e4c6f33babf792279ac33a0#diff-e7946cb9b02a4dba1a3d5e627e31b2ccR2571

And in CS the actions are fixed. (except that useOn always returns false->right click always cancelled on mobs)

**Comment by PeratX** [comment]
Fixed
