### ISSUE TITLE
Need fix this :D

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#375]
Fatal error: Uncaught Error: Call to a member function getChunk() on null in /root/root/src/pocketmine/level/Level.php:2665

**Comment by PeratX** [comment]
More details, only this cannot prove error. It seems something wrong with your map

**Comment by astersx** [comment]
It was on server startup this warning,  so is not genisys?

**Comment by PeratX** [comment]
Not Genisys's problem. Close
