### ISSUE TITLE
checkmovement: false

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#376]
If you put checkmovement:false      server freeze!!!
You need to have 30 players on server!!!!

**Comment by flaxues** [comment]
Omg if thats the reason imma be so mad at myself :/

**Comment by astersx** [comment]
Why?

**Comment by flaxues** [comment]
Because I have spend over more then 7 hours trying things recompiling new server etc. and it's just this single thingy

**Comment by astersx** [comment]
=)))))

**Comment by astersx** [comment]
Not fiiiiixed :(

**Comment by astersx** [comment]
Fk this
