### ISSUE TITLE
Php 7 binary 

### ISSUE THREAD

**Issue by GrimDevs** [iTXTech/Genisys#377]
![image](https://cloud.githubusercontent.com/assets/16393634/13205917/57f5dbe4-d8eb-11e5-873b-295c8577e26f.png)
Do I need this one p,z tell me I am on win 7 OK Tell me the thing for php to get to work on me server

Link for 64 http://windows.php.net/downloads/qa/php-7.0.4RC1-Win32-VC14-x64.zip
Line for 86 http://windows.php.net/downloads/qa/php-7.0.4RC1-Win32-VC14-x86.zip

**Comment by Muqsit** [comment]
https://github.com/iTXTech/PHP-Genisys

**Comment by gaoyichuan** [comment]
Please the php binarys provided by ourselves in iTXTech/PHP-Genisys or you will run into lacking of dependcy libraries.
