### ISSUE TITLE
CraftBukkit commands

### ISSUE THREAD

**Issue by Muqsit** [iTXTech/Genisys#382]
Clear:
Usage: /clear [user] [item] [data] [maxCount] [dataTag]
Clears a players inventory.

Setidletimeout:
Usage: /setidletimeout <Minutes until kick>
Set the servers idle timeout.

(Command Selectors)
@a - Target all players
@e - Target all entities
@p - Target nearest player
@r - Target a random player

**Comment by erkam2002** [comment]
Is not go

**Comment by gaoyichuan** [comment]
Command selectors are hard to do.. Clear command is possible

**Comment by flaxues** [comment]
Would love to see Command Selectors!

**Comment by Muqsit** [comment]
Command selectors are hard but @aliuly made a plugin called GrabBag and it has working command selectors. I use it on my server too!

**Comment by gaoyichuan** [comment]
@PeratX See this.

**Comment by flaxues** [comment]
@Muqsit I don't want to use such a big plugin for a small thing :P

**Comment by Muqsit** [comment]
@flauxes yeah it's so huge

**Comment by rj0495** [comment]
I have working Command Selectors. I'll commit them later.
