### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#386]
I have maked /summon Human and now crash always my mcpe help pls!

**Comment by PocketKiller** [comment]
because we should add the info for the Human, like skin and...

**Comment by erkam2002** [comment]
I cant join my server :'(

**Comment by erkam2002** [comment]
How can i fix that?

**Comment by PocketKiller** [comment]
delete the world entities by anything.

**Comment by gaoyichuan** [comment]
Shall I disable summon for human?

**Comment by PocketKiller** [comment]
Yes.

**Comment by erkam2002** [comment]
How now?
