### ISSUE TITLE
ceckmovement problem

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#388]
Still not fixed :(,  again freeze on 50 players!!!
![screenshot_2016-02-22-18-51-26](https://cloud.githubusercontent.com/assets/13157548/13225249/aed469c2-d994-11e5-872c-a07539697767.png)
It need 5 minutes to take a command!!!

**Comment by flaxues** [comment]
yours is reacting mine doesn't anything it just waits for me to sigkill it :(

**Comment by astersx** [comment]
It reacted after 20 minutes,  dont know!!  I just wake up and run command,  after some time it appeared,  stop didnt work i killed session!!!

**Comment by astersx** [comment]
Just put checkmovement: true

**Comment by gaoyichuan** [comment]
Have a update. The checkmovement issue was fixed yesterday

**Comment by astersx** [comment]
I really dont think it was fixed,  but just test checkmovement:false    with 50+ players online.
If i test again all my players will leave!!!

**Comment by PeratX** [comment]
Same as another issue. Close
