### ISSUE TITLE
Please look at this!

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#397]
Genisys Crash Dump Mon Feb 22 16:00:06 MST 2016

Error: Argument 1 passed to pocketmine\item\Item::__construct() must be of the type integer, string given, called in phar:///home/user/Desktop/Server/PocketMine-iTX.phar/src/pocketmine/item/Item.php on line 1171
File: /src/pocketmine/item/Item
Line: 1209
Type: notice

Code:
[1200] 				}
[1201] 			}else{
[1202] 				$item = self::get($b[0] & 0xFFFF, $meta);
[1203] 			}
[1204] 
[1205] 			return $item;
[1206] 		}
[1207] 	}
[1208] 
[1209] 	public function __construct(int $id, $meta = 0, int $count = 1, string $name = "Unknown"){
[1210] 		$this->id = $id & 0xffff;
[1211] 		$this->meta = $meta !== null ? $meta & 0xffff : null;
[1212] 		$this->count = $count;
[1213] 		$this->name = $name;
[1214] 		if(!isset($this->block) and $this->id <= 0xff and isset(Block::$list[$this->id])){
[1215] 			$this->block = Block::get($this->id, $this->meta);
[1216] 			$this->name = $this->block->getName();
[1217] 		}
[1218] 	}
[1219] 

Backtrace:
#0 /src/pocketmine/nbt/NBT(111): pocketmine\item\Item::get(string minecraft:rail, integer 0, integer 3)
#1 /src/pocketmine/entity/Item(77): pocketmine\nbt\NBT::getItemHelper(pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:rail.pocketmine\nbt\tag\ByteTag:3.pocketmine\nbt\tag\ShortTag:0.})
#2 /src/pocketmine/entity/Entity(283): pocketmine\entity\Item->initEntity(boolean)
#3 /src/pocketmine/entity/Entity(445): pocketmine\entity\Entity->__construct(pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\LongTag:-6002842692348843593.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\FloatTag:205.02008056641.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:rail.pocketmine\nbt\tag\ByteTag:3.pocketmine\nbt\tag\ShortTag:0.}.pocketmine\nbt\tag\LongTag:-8340055636963409293.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:609.875.pocketmine\nbt\tag\DoubleTag:21.pocketmine\nbt\tag\DoubleTag:1063.75.}.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\StringTag:Item.pocketmine\nbt\tag\ShortTag:163.})
#4 /src/pocketmine/level/format/generic/BaseFullChunk(148): pocketmine\entity\Entity::createEntity(string Item, pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\LongTag:-6002842692348843593.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\FloatTag:205.02008056641.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:rail.pocketmine\nbt\tag\ByteTag:3.pocketmine\nbt\tag\ShortTag:0.}.pocketmine\nbt\tag\LongTag:-8340055636963409293.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:609.875.pocketmine\nbt\tag\DoubleTag:21.pocketmine\nbt\tag\DoubleTag:1063.75.}.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\StringTag:Item.pocketmine\nbt\tag\ShortTag:163.})
#5 /src/pocketmine/level/Level(2691): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#6 /src/pocketmine/level/Level(660): pocketmine\level\Level->loadChunk(integer 38, integer 66)
#7 /src/pocketmine/Player(854): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(4382), integer 38, integer 66, boolean 1)
#8 /src/pocketmine/Player(2061): pocketmine\Player->sendNextChunk(boolean)
#9 /src/pocketmine/Server(2918): pocketmine\Player->checkNetwork(boolean)
#10 /src/pocketmine/Server(2608): pocketmine\Server->tick(boolean)
#11 /src/pocketmine/Server(2486): pocketmine\Server->tickProcessor(boolean)
#12 /src/pocketmine/Server(2019): pocketmine\Server->start(boolean)
#13 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/user/Desktop/Server/PocketMine-iTX.phar/, string /home/user/Desktop/Server/, string /home/user/Desktop/Server/plugins/)
#14 (1): require_once(string phar:///home/user/Desktop/Server/PocketMine-iTX.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux krismar-B633 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:30:01 UTC 2014 i686
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
PurePerms 1.3.1 by 64FF00 for API(s) 1.13.0, 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
BlockSniffer 1.0.0 by DRedDogPE for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.13.0, 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by gaoyichuan** [comment]
The same with #356
