### ISSUE TITLE
Why This error?

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#401]
Warning: include(phar:///root/root/PocketMine-MP.phar/src/pocketmine/level/generator/GeneratorUnregisterTask.php): failed to open stream: phar error: internal corruption of phar "/root/root/PocketMine-MP.phar" (actual filesize mismatch on file "src/pocketmine/level/generator/GeneratorUnregisterTask.php") in phar:///root/root/PocketMine-MP.phar/src/spl/BaseClassLoader.php on line 128

Warning: include(): Failed opening 'phar:///root/root/PocketMine-MP.phar/src/pocketmine/level/generator/GeneratorUnregisterTask.php' for inclusion (include_path='.:') in phar:///root/root/PocketMine-MP.phar/src/spl/BaseClassLoader.php on line 128

Warning: include(phar:///root/root/PocketMine-MP.phar/src/spl/ClassNotFoundException.php): failed to open stream: phar error: internal corruption of phar "/root/root/PocketMine-MP.phar" (actual filesize mismatch on file "src/spl/ClassNotFoundException.php") in phar:///root/root/PocketMine-MP.phar/src/spl/BaseClassLoader.php on line 128

Warning: include(): Failed opening 'phar:///root/root/PocketMine-MP.phar/src/spl/ClassNotFoundException.php' for inclusion (include_path='.:') in phar:///root/root/PocketMine-MP.phar/src/spl/BaseClassLoader.php on line 128
[01:39:06] [Server thread/CRITICAL]: Error: "Class 'ClassNotFoundException' not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 131
[01:39:06] [Server thread/EMERGENCY]: Crashed while crashing, killing process
./root/start.sh: line 75: 19310 Killed                  "$PHP_BINARY" "$POCKETMINE_FILE" $@
Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
[01:39:06] [Server thread/INFO]:

It did after i /stop server!!!

**Comment by astersx** [comment]
[php-error.txt](https://github.com/iTXTech/Genisys/files/142092/php-error.txt)

Again a error!!!!  after /stop

**Comment by gaoyichuan** [comment]
I think the phar you downloaded is broken. Re-download it.

**Comment by PeratX** [comment]
Broken Phar. Redownload it.
