### ISSUE TITLE
 zlib_decode(): data error 

### ISSUE THREAD

**Issue by gacus007** [iTXTech/Genisys#402]
Hi I 've got error during player joining:

Warning: zlib_decode(): data error in /home/mc/src/pocketmine/nbt/NBT.php on line 473
[12:13:11] [RakLibServer thread/NOTICE]: Blocked 83.30.176.50 for 5 seconds

**Comment by PeratX** [comment]
Player data is broken. Delete it. Not a server issue.

**Comment by gacus007** [comment]
thx
