### ISSUE TITLE
Arrow Crash--ImagicalMine fixed

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#406]
There seems to be an arrow crash going on on my server

https://github.com/ImagicalMine/ImagicalMine/commit/4485d5773fcf776bba5753d71c5f9787a7aaccae

ImagicalMine Has it fixed

**Comment by PocketKiller** [comment]
and Fixed also here.

**Comment by PocketKiller** [comment]
can you reproduce this?

**Comment by Skyladd** [comment]
I can my buddy has a bunch of arrows in his inventory and would crash the server when he joins. i deleted his player data and now its fine
