### ISSUE TITLE
question

### ISSUE THREAD

**Issue by seetch** [iTXTech/Genisys#407]
How can I create a repository for you with an installer for Linux and similar OC?

**Comment by PocketKiller** [comment]
How? you should know how if you want to make for us...

**Comment by seetch** [comment]
Not exactly written question, I want to do for you.

**Comment by PocketKiller** [comment]
Ok, create a repo on your profile and I'll test on Windows 8.

**Comment by seetch** [comment]
https://github.com/seetch/Genisys-Install/tree/master
