### ISSUE TITLE
Dead event

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#409]
Hi! Players on dead wont teleport in spawn if they leave the game and rejoin!!!
For example in a faction server invaders leave server after dead and join again,  they are teleported on victim base not on spawn!!!
Is there a way to fix this?

**Comment by jasonczc** [comment]
You can write a plugin...When player die,to tp spawn...

**Comment by thebigsmileXD** [comment]
@astersx AlwaysSpawn
