### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#412]
Notice: Undefined variable: thos in /home/egor/RPG/src/pocketmine/Player.php on line 3194

Notice: Trying to get property of non-object in /home/egor/RPG/src/pocketmine/Player.php on line 3194

**Comment by PeratX** [comment]
There is nothing with line 3194. $thos does not exist

**Comment by flaxues** [comment]
I already fixed that use the latest build before reporting!
