### ISSUE TITLE
"bin\php\php.exe: Exit 127" on startup

### ISSUE THREAD

**Issue by meetloaf13** [iTXTech/Genisys#413]
No error log, just says "bin\php\php.exe: Exit 127"

All I did was place updated phar in the directory

**Comment by PeratX** [comment]
Seems something wrong with your php runtime

**Comment by NML32** [comment]
Sometimes it takes me several tries before the server starts.

**Comment by meetloaf13** [comment]
Very good, I updated to the latest Win x64 php, it did take a couple restarts.  Thanks to both of you.

**Comment by meetloaf13** [comment]
I continue to have the issue.  It was not specific to build #55.  I have tried updating my PHP files several times, redownloading and the like.

I start my server, and the console hangs for a second or two at the line "Preparing level 'nether'" and then I get the "bin\php\php.exe: Exit 127" error.

I have ZERO plugins, this has been recreated on almost every build since 55, and the only way I have found to get around this is to do what NML32 suggested, simply restarting the server several times.  That is a manageable solution...but only if I'm actively managing this server, which is not very often.

Thanks for your help.

**Comment by PeratX** [comment]
Try to delete your maps(backup first)

**Comment by meetloaf13** [comment]
I suppose I could delete the nether map.  No one has really messed with it yet.

**Comment by meetloaf13** [comment]
Alright, just deleted the nether world and let the server recreate.  Error seems to be gone for now.  I'll let you know if the problem crops up again.  

Thanks!

**Comment by meetloaf13** [comment]
No better, still happening.  Corruption in my main level, or perhaps in the nether world?  How would I remedy this, if this is in fact what is causing this.  (I don';t think it's the main level, as it loads, and the server moves on to loading the nether world.

**Comment by meetloaf13** [comment]
Nope, deleted Nether, disabled it in the genisys.yml, still happening.

**Comment by PeratX** [comment]
I have no idea. Can you trace your code?

**Comment by meetloaf13** [comment]
I don't really have much experience coding or debugging, a little VBA.  But I can if you show me how =]

**Comment by meetloaf13** [comment]
What can I do to get a debug or do some discovery on this?  It's not reliably reproduceable.  Sometimes server starts, sometimes not.  Win 10 x64 PHP7.

**Comment by meetloaf13** [comment]
In case anyone is interested, I have created this  AutoRestart script in AHK.  It doesn't fix the problem, but it will automatically restart the server if the error pops up.
`#SingleInstance, force
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
 
GoTo, MainLoop
Error := "Exit 127"
 
 
MainLoop:
loop {
	Error := "Exit 127"
	WinClose, ahk_class mintty
	Run C:\MCPE\genisys\Start.cmd
	Sleep 2500
 
	WinActivate, ahk_class mintty
	WinWaitActive, ahk_class mintty, , 5
	Sleep 1000
	MouseClick, Right, 281, 213
	Send, {Down 2}
	Send, {Enter}
	Sleep 2500
	MouseClick, Right, 281, 213
	Send, {Down 4}
	Send, {Enter}
	ClipWait
	;MsgBox, %Error%
	;MsgBox, %clipboard%
	IfInString, clipboard, %Error%
	{
    GoTo, MainLoop
	}
	else
	WinMinimize, ahk_class mintty
 
    ;sleep 1750000
    Sleep 5350000
 
	WinActivate, ahk_class mintty
	WinWaitActive, ahk_class mintty, , 5
 
	Send, say This server will implode in 4 minutes and maybe restart{enter}
	sleep 60000
	Send, say This server will melt your face in 3 minutes {enter}
	sleep 60000
	Send, say I hope you kissed your momma this morning...2 minutes {enter}
	sleep 60000
	Send, say you might as well jump off the world...1 minute {enter}
	sleep 50000
	Send, say Hasta La Vista BABY! {enter}
	sleep 10000
	Send, Stop {enter}
	sleep 60000
	WinClose, ahk_class mintty
	}`

**Comment by PeratX** [comment]
Try to delete temp files
