### ISSUE TITLE
Cannot use pocketmine\nbt\tag\Float as Float

### ISSUE THREAD

**Issue by Garem** [iTXTech/Genisys#414]
I get the following error after updating .phar file 

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/pi/Schreibtisch/Genisys-master/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by PeratX** [comment]
Download the latest phar from official jenkins
