### ISSUE TITLE
worlds

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#415]
Hi! pocketmine.yml dont load all my worlds!!  What is format u use for adding multiple worlds in pocketmine.yml? Maybe i mystake something! I did:
world:name
world:name1
etc....

And new worlds make mcpe a little laggy,  maybe becouse of many stuff it spawn? i mean flowers,  dead bushes,  etc..

**Comment by PeratX** [comment]
Please upload your pocketmine.yml

**Comment by astersx** [comment]
[pocketmine.txt](https://github.com/iTXTech/Genisys/files/145629/pocketmine.txt)

**Comment by astersx** [comment]
Tested again,  and all players are forced to spawn, in lobby map after server restart!!
worlds dont auto load,  im happy that Magic Teleportal , force the world to load  wen someone use it.

**Comment by gaoyichuan** [comment]
Your plugin hasn't automatically load the worlds properly. I use ManyWorlds-PHP7 and it works without bugs.

**Comment by gaoyichuan** [comment]
And you have missed Tabs in your pocketmine.yml. Add two space before each 'worls:xxx' will solve the problem. YML files are sensitive in syntax

**Comment by astersx** [comment]
ok thx :)

**Comment by astersx** [comment]
[pocketmine.txt](https://github.com/iTXTech/Genisys/files/147074/pocketmine.txt)
what i did wrong now? Dont work!! 1 space should be enough!!

**Comment by astersx** [comment]
I did and the same,  
"2 spaces" world: name

"2 spaces" world: name2

Only 3 maps are loading :(

**Comment by astersx** [comment]
The way i put was wrong!! Why nobody warned me? is not about spaces,  =D
