### ISSUE TITLE
Invisible signs & chest.

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#420]
When i create sign, then its normal. But after server restart, it became invisible.... same as chest.
![screenshot_2016-02-25-21-44-08](https://cloud.githubusercontent.com/assets/15629214/13322491/9ae32ed0-dc0f-11e5-919f-045d49c669a4.jpg)

And when i sell something using EconomySell plugin , its said sold and the items in inventory still there, but when i tap on the item, its disappear. This should be a glitch...

**Comment by PocketKiller** [comment]
second is EconomySell problem

**Comment by EnderKenji** [comment]
The invisible problem? Its happened even is not Sell / Buy sign.. (normal)

**Comment by flaxues** [comment]
The inventory is not updating properly

**Comment by Muqsit** [comment]
I KNOW THE SIGN AND CHESTS BECOMING INVISIBLE PROBLEM!
....happens to ItemFrames too...they go invis too!

If I create a mine using the MineReset plugin by @Falkirks and I do /mine reset <name>, (and if the mine is in a chunk where there are chests and signs and itemframes) the chests, signs and itemframes go invisible!

**Comment by PeratX** [comment]
Chunk is broken.

**Comment by EnderKenji** [comment]
Thts MineReset Problem, maybe. Not sure.

**Comment by EnderKenji** [comment]
Reopen if u think its Genisys's Problem.
