### ISSUE TITLE
Builds jenkins #50+

### ISSUE THREAD

**Issue by isoz** [iTXTech/Genisys#422]
* Server gets stuck on "server is stopping" after issuing the stop command.

* Some players get stuck on "Building terrain" and eventually timeout.

* Breaking blocks feels odd, the block disappears instantly but the animation comes a few mili secs later giving the feeling that theres lag.

* Performance decreased massively, I can feel rubberbanding and lagging back with less than 50 players (not at all times) and before 0.14 we could easily have 120 players with minimal lag.

With jenkins build #49 players dont time out and server doesnt get stuck.

**Comment by flaxues** [comment]
Having the same issue!

**Comment by MilkoIvanov** [comment]
Same here!

**Comment by PeratX** [comment]
@isoz Can you upload your timings info? /timings on /timings paste

**Comment by isoz** [comment]
I can do it later today at peak times, but do you want the timings just to see if there is a plugin creating issues? because if that's the case you can rest assured that theres no plugin creating problems.

**Comment by PeratX** [comment]
No not plugins. Just timings of core.

**Comment by isoz** [comment]
Here it is 
http://timings.aikar.co/?url=15207362

**Comment by PeratX** [comment]
Fixed
