### ISSUE TITLE
Php5

### ISSUE THREAD

**Issue by Frago9876543210** [iTXTech/Genisys#423]
Php5 will no longer produce ?

**Comment by astersx** [comment]
php7 is really unstable,  pulls back,  memory leak...  But is just the most stable server,  i dont know other good forks.
I was on a server who use genesis php5,  modifyed to work on 0.14.0.
He have 100+ players online and i dont get pulled back!!

**Comment by PeratX** [comment]
@astersx Can you upload your timings info of your php7 server? We are trying hard to fix it!

**Comment by MasterWolf** [comment]
Oh... I really hate PHP 7

**Comment by astersx** [comment]
@PeratX  Hi! I already sent u timings wen i report checkmovement!! Mostly saving map,  players network,  make lag!! Anyway wen i have 50+ players i will check timings!!

**Comment by Syntaxious** [comment]
To be honest, I think Genysis should have a branch of PHP 5, PHP 7 is indeed unstable and requires plugins to be patched for PHP 7.

If possible, create a PHP 5 branch for those who want It.

**Comment by MilkoIvanov** [comment]
It's not that hard to change the 'Tag', anyway the 0.14.0 update for PHP7 made it unstable

**Comment by Syntaxious** [comment]
Oops, didn't see that. But they should continue updating for PHP 5 as well.

**Comment by MasterWolf** [comment]
@Syntaxious yes but here is not link on jenlibs for php5

**Comment by MilkoIvanov** [comment]
@MasterWolf You can use the /ms command.Just paste the'src' of genisys to your main directory and you are done

**Comment by MasterWolf** [comment]
@MilkoIvanov ерфтлі

**Comment by MasterWolf** [comment]
@MilkoIvanov thanks
