### ISSUE TITLE
Client crashing

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#426]
I'm getting reports from some of my players that they crash in game. 
So far I don't see any pattern or reason. It's a client crash so nothing in the logs. I tried to delete their profile but that didn't help. 

Report from a user:
NML,
Every time I join any of your servers I tend to crash. I know that some people are experiencing the same thing, but I just wanted you to know that this has been happening for awhile. If you are able to may you please tell me why it's happening and when the crashing will start to end. Sorry if it seems like I'm asking for too much. Thank You
-Sunset0318(Sun)

**Comment by astersx** [comment]
This was happening to me too,  i just took player coordinates and blow up that area , all done =))

**Comment by PeratX** [comment]
If some un-supported blocks in that chunk, client will crash

**Comment by astersx** [comment]
Yep!!  But i still dont know what chunks are unsuported!!

**Comment by NML32** [comment]
The client crashing seems random. It's not happening to everyone.

**Comment by jasonczc** [comment]
1,Use blocklauncher to solve the problem.
2, http://www.mcbbs.net/thread-341836-1-1.html Use this plugin to clear un-supported block.(nees Google Translate)
