### ISSUE TITLE
Many,many bugs...

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#436]
From the 50+ builds I got so many bugs...First all spawn eggs,all potions,item frame,buckets dissappeared from the creative bar .The iron door cannot be opened or closed.The creative bar is being blank on player join.And yeah there is aloooot of lagg.Some help here are the timings http://paste.ubuntu.com/15205283/ and the others http://timings.aikar.co/?url=15205283 even with 9 players there is lagg.Before build 50+ and 0.14.0 at all the server could keep 60-70 players almost without any lagg.

**Comment by astersx** [comment]
limited creative and world save cause lag :p! ! The main problem is that pulls back,  even with 20 tps i get pulled back,  ofcourse with 50+ players!!!

**Comment by gaoyichuan** [comment]
Why dom't you use the older builds?

**Comment by astersx** [comment]
is there php5 0.14.0?

**Comment by astersx** [comment]
http://timings.aikar.co/?url=15208225

**Comment by astersx** [comment]
Most lag is from pocketmine

**Comment by PeratX** [comment]
@TheClimbing I see your TPS and load is normal. Is it just pull back?

**Comment by Muqsit** [comment]
There's no lag. Join my server -> rumbencraft.zapto.org:13579

**Comment by Muqsit** [comment]
Send your pocketmine.yml and server.properties file

**Comment by gaoyichuan** [comment]
@astersx php5 support is abandoned by us. We will only push changes to the php7 branches

**Comment by erkam2002** [comment]
Muqsit iam MCPE_Expert are you RumbrnSitkin?

**Comment by TheClimbing** [comment]
@PeratX  It's not just the pull back. Half of the items are gone from the creative bar also players are complaining, about lagg. I've thought its my fault but even after  modifying my pocketmine.yml.Tbere is lagg which is for like 5 seconds and I don't know what's the problem. Do you want to upload my pocketmine.yml?

**Comment by TheClimbing** [comment]
Oh yeah I don't have rail,powerd rails..etc.Someone?

**Comment by TheClimbing** [comment]
Am I the only one who don't have item from the creative inventory?
