### ISSUE TITLE
ItemFrame crash: __clone method called on non-object

### ISSUE THREAD

**Issue by ZizzyZizzy** [iTXTech/Genisys#437]
Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]

http://pastebin.com/UNWQuKKd

Relevant bits:

Error: __clone method called on non-object
File: /src/pocketmine/tile/ItemFrame
Line: 83
Type: notice

...

#0 /src/pocketmine/tile/Spawnable(67): pocketmine\tile\Spawnable->spawnTo(pocketmine\Player Player(6))
#1 /src/pocketmine/tile/Spawnable(57): pocketmine\tile\Spawnable->spawnToAll(boolean)
#2 /src/pocketmine/tile/ItemFrame(34): pocketmine\tile\Spawnable->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\Str
ingTag:ItemFrame.pocketmine\nbt\tag\IntTag:198.pocketmine\nbt\tag\IntTag:30.pocketmine\nbt\tag\IntTag:49.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\FloatTag:1.})

**Comment by NML32** [comment]
My server is crashing non-stop with this error.

**Comment by PeratX** [comment]
Maybe fixed

**Comment by NML32** [comment]
It's fixed on my server.
