### ISSUE TITLE
error php7

### ISSUE THREAD

**Issue by Frago9876543210** [iTXTech/Genisys#439]
Help me please. Error on start:

root@frago:/home/t# ./st*
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.15' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/t/bin/php7/bin/../lib/libz.so.1)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/t/bin/php7/bin/../lib/libyaml-0.so.2)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.15' not found (required by /home/t/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/t/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/t/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/t/bin/php7/bin/../lib/libcurl.so.4)
root@frago:/home/t#

**Comment by astersx** [comment]
php files missing? try download again php7 and upload on your server!!

**Comment by Frago9876543210** [comment]
@astersx I put the file.zip with bin and unzip file

**Comment by gaoyichuan** [comment]
Update your system to CentOS 7.x to use the precompiled php binary. Or use our start.sh to complie a binary for your own
