### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DWWf** [iTXTech/Genisys#44]
![lol](https://cloud.githubusercontent.com/assets/15623918/12072769/87d26cd2-b0bf-11e5-9d3f-567f15a87010.PNG)

So this happens when (only) i join um it hasn't happened before so i'm confused... is this a problem with genisys?

**Comment by MCPEPIG** [comment]
That's caused by VPNGuard

**Comment by DWWf** [comment]
Yeah i just fond that out XD you can close this now
