### ISSUE TITLE
pulls back

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#442]
Checkmovement is broken!!
If is on it pulls back like crazy,  for example,  you get pulled back x to y,  but u got pulled back too fast then u get pulled back from y to x,  and then u get stuck betwen x and y.  I lol so much on that thing =)).
* Why didnt u put checkmovement false?

-It makes tps 3 with 10 minutes uptime!!

* We fixed this!!

-well you didnt!!

This is the conversation i dont wanna to have,  the problem is still not solved!!!

**Comment by astersx** [comment]
In fact my game dont really lag,  tps are normal,  game start lags after 1 hour.
But with more than 40 players,  pulls back become crazy sometimes!!!

**Comment by PeratX** [comment]
You mean TPS and load is right but with pull back (check-movement: false)?

**Comment by astersx** [comment]
checkmovement:true    = pulls back

**Comment by astersx** [comment]
checkmovement:true. = lots of loadings and tps only 3 and and after some minutes tps 0

**Comment by astersx** [comment]
I dont know why,  maybe becouse worlds,  player movement,  inventory tap and any action is,  by my guess,  saved in real time?

**Comment by PeratX** [comment]
checkmovement: true just pull back and no lag?

**Comment by astersx** [comment]
Yes!! Well i restart server every hour!!  But checkmovement:false create lag!!!
So,  ceckmovement:true is working with almost 18 tps for 1 hour with 6 maps and 50+ players.
Checkmovement:false = no pulls back and make server freeze!!!

Yep @Peratx

**Comment by PeratX** [comment]
@astersx Even the latest commit?

**Comment by astersx** [comment]
i didnt try,  im now trying to install a cpanel for web hosting :D
