### ISSUE TITLE
Strange, 

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#443]
![screenshot_2016-02-27-00-08-37](https://cloud.githubusercontent.com/assets/13157548/13366752/0459eefe-dce6-11e5-9219-cb19b8fd4ddc.png)
Hi! game glich wen i look at this house,  maybe too many cobblestone walls crashes the game?
My game glich and GUI dissapear,  and cant see any entity if i look at this house made of cobblestone wall!!!

**Comment by CrayonDing** [comment]
I also set a lot of cobblestone walls,but no strange thing happened.If you open Hide GUI?

**Comment by gaoyichuan** [comment]
I don't think cobblestone walls would be any different blocks. Maybe it's because there are too many blocks in this chunk?

**Comment by astersx** [comment]
I tnt that house and i screen no more screen glich.
Btw in 0.13 that house crashed my client!!

**Comment by flaxues** [comment]
TNT fixes everything :P
