### ISSUE TITLE
W10 edition bugs

### ISSUE THREAD

**Issue by potato520hjj** [iTXTech/Genisys#444]
- [ ] 不知道为何使用win10版的，进入服务器后无法合成东西（合成后，等一下会立刻变回原材料，就好像卡了一下，但实际上好几个服务器都是如此） 
Unable to craft in W10 Edition. 

- [x] 同样也是win10的，进入服务器后按**E**可以打开背包，但是再次按**E**合上背包后，会导致手中的物品抛出去，类似与**Q**键的功能。但这是不期望的功能。 
Player throw things when use "E" to close the Inventory. This behavior is unexpected.

- [ ] Items are not dropped. When you try to drop an item dragging it from inventory window, it just disappears.

- [ ] In creative, items cannot be put into the hotbar unless the player is holding the chosen hotbar slot.

**Comment by potato520hjj** [comment]
抱歉本人的英语水平有限，有哪位大神可以解答，或者将本文翻译成英文！非常感谢！

**Comment by flaxues** [comment]
English?

**Comment by gaoyichuan** [comment]
没有win10的机器，无法测试。。@PeratX 有空看下

**Comment by Efforto** [comment]
= =我来试试
1.I cant use CraftTable on Windows10 Edition.When I crafting something it will be turn to the normal materials.
2.The same problem on Win10 is "E" could open the backpack ,but if you close the pack with "E" , the item in hand will be throwing away.=_=It same as the "Q" , but this is a bad feature.
= =无机翻，纯属瞎翻，别笑我，我只是打酱油的

**Comment by flaxues** [comment]
@PeratX Already fixed this or am I wrong?

**Comment by potato520hjj** [comment]
怎么办？如果一直这样的话，win10的可是要废了！不知道是不是核心的问题，还是客户端的毛病？

**Comment by PeratX** [comment]
@potato520hjj 试试dump一下包 和手机版不一样（手头没win10

**Comment by gaoyichuan** [comment]
团队都没人用win10？ 【摊手】

**Comment by CrayonDing** [comment]
xbox日常连不上。我本来想测试的

**Comment by dog194** [comment]
@PeratX  Zhy有(恩 不是我说的)话说你是没入还是没WIn10系统

**Comment by CrayonDing** [comment]
@dog194 我有他就有哟。他应该是没电脑……我记得他电脑升级win10了

**Comment by dog194** [comment]
@CrayonDing  我有Win10PE 可以登服务器 0.0 然而 我并不会抓

**Comment by yhzx233** [comment]
@PeratX 可以用启动器开启win10gui

**Comment by Muqsit** [comment]
Here you can clearly see that Win10 Edition is in beta: https://www.microsoft.com/en-us/store/apps/minecraft-windows-10-edition-beta/9nblggh2jhxj


This happens in ImagicalMine and in the official builds too!

**Comment by Tee7even** [comment]
>Here you can clearly see that Win10 Edition is in beta: https://www.microsoft.com/en-us/store/apps/minecraft-windows-10-edition-beta/9nblggh2jhxj
This happens in ImagicalMine and in the official builds too!

So? Is prefix "Beta" or that "ImagicalMine has it" a reason to say it's a client bug?

**Comment by Muqsit** [comment]
Hmm interesting.

**Comment by ducdude** [comment]
Had my W10 beta running windowed so I could monitor the server in another. No hit to system load but the server was reporting this every time I'd try to craft. Had the same issue in pocketmine so I guess it's carryover.

`Notice: Undefined offset: 0 in phar://C:/Minecraft/Genisys/Genisys.phar/src/pocketmine/Player.php on line 3376
[22:00:36] [RakLibServer thread/NOTICE]: Blocked 10.0.1.18 for 5 seconds`

I get those same two lines every time.

**Comment by hmy2001** [comment]
I think that fixed #699

**Comment by ducdude** [comment]
Same error after the update but now complaining about line 3410. Also strange, one block of wood picked up a total of 430 times. Filled 6 slots of the hot bar to 64 and one to 46. After dropping it cleared hot bar but if you open the inventory it shows them as still in the hot bar.

**Comment by 2300206764** [comment]
这个问题我说了好久了，不知道什么时候好

**Comment by thebigsmileXD** [comment]
omg look @ https://github.com/PocketMine/PocketMine-MP/issues/4079

**Comment by PeratX** [comment]
So how to fix.

**Comment by thebigsmileXD** [comment]
I tried something, atleast i get no more errors. But blame PM API.

**Comment by StainedPupil** [comment]
On Gear VR the same issue is there but refers to a different line : 
Notice: Undefined offset: 0 in phar://C:/Users/Citrix/Desktop/PocketMine/PocketMine-MP.phar/src/pocketmine/Player.php on line 3502

**Comment by StainedPupil** [comment]
If that can help, there are 4 .patch files for Windows 10 issues (inventory and crafting) here : 
https://gist.github.com/extremeheat/f1e9e0b8ca884727e6a3abfc7bfdc5a3

I'm quite new to GitHub and the whole thing so I don't quite know how to apply it to my files.

**Comment by intagaming** [comment]
Im claim that this is fixed in 0.14.2 and Genisys #374.

**Comment by Muqsit** [comment]
#997

**Comment by Muqsit** [comment]
#1025

**Comment by MineCorps** [comment]
Mojang forums claim its a MCPE issue.
All of the Gitlab things I've seen state that its a MCW10E Client issue.

I've tried Imagicalmine, Genisys, and Pocketmine.

Problem!

Single player?
Game works flawlessly.

Join a server?
Lose everything.
Lose villagers.
Lose crafting.
Lose creatures.
Lose inventory management (throw items on the ground when closing inventory.)

This is not a client issue. This is a client interface issue with your server software.

:/

**Comment by ishitatsuyuki** [comment]
@MineCorps who said it's a client issue? Stop posting offensive comments.

**Comment by MineCorps** [comment]
@ishitatsuyuki may people have said "its a client problem" and "Windows 10... [alluded]" and "Windows 10 MC is very buggy!"

Seriously though---why is this inventory tossing still an issue?

**Comment by dktapps** [comment]
Nobody else @iTXTech/developers have Win10 edition? I'll tackle these bugs then. I have Win10 edition on my laptop and a lot of time to spare.

**Comment by MineCorps** [comment]
@dktapps  oh my god---this is why? everybody is on an ipad or something? >.<

Speaking for a frustrated group of people, and an even more frustrated group of 7-11 year olds, thank you for taking the torch on this.

minecraft {a[t]] leuthcorps Dott com  if you need anything. I have a local test server that I'll get re-powered and up to speed to help you test (if I can get it to 0.15.0)

**Comment by dktapps** [comment]
@MineCorps Most devs favour Linux over Windows. And thanks, help testing will be appreciated.

**Comment by SirOptic** [comment]
I have windows 10 and I am willing to help with windows 10 mc testings.Its trur my inventory is always buggy.Especially when crafting and enchanting.

**Comment by dktapps** [comment]
@rcsupermanjob These aren't client bugs, this is a problem with the server misunderstanding the client.

**Comment by dktapps** [comment]
Okay guys, would you like to try this [development build](https://gitlab.com/itxtech/genisys/builds/2056703/artifacts/download)?

**Comment by SirOptic** [comment]
Doing it now.

**Comment by SirOptic** [comment]
Theres 3 phars which one is it

**Comment by ducdude** [comment]
@SirOptic I only see one dev build phar file. Have you tested it? I need to
swap drives in my Deb box to the one with Genisys, but I'll try to test it
too.

**Comment by ducdude** [comment]
Thinking out loud here so to speak, but off the top of my head it seems
that the error it's throwing when I try to craft from W10 is an exception
in Player_64.php on line 2300 something. Clear as mud, and I'll post the
exact details when I get back on my W10 machine. I decompiled the current
passing build phar as of a couple of days ago so I could pull up that php
file in notepad++. What just struck me a moment ago... those particular
lines are something regarding shapeless and shaped recipes or something to
that effect. Since PE on a tablet will show you what you can craft with
your given inventory, and W10 is more MC vanilla like in it's crafting
environment, could it be that PE is telling the server that this block of
wood is now planks whereas the W10 version is saying hey, make this block
of wood into planks for me? Who (server or client) actually handles the
crafting transaction in each version?

**Comment by ducdude** [comment]
@Dylan K. Taylor

Dude..... Whatever you did friggin works! Not perfect but a HUGE step in
the right direction. Two wood blocks somehow ended up giving me 12 planks.
No errors though. It put one wood back into inventory, but again no errors.
I was able to craft a crafting table but it wouldn't show up in my hotbar.
In inventory view it was there but not when I closed out. Until I flipped
my Yoga 3 into tablet mode. I was able to place the crafting table from the
hotbar and craft my remaining planks into sticks. I picked my crafting
table back up and it reappeared in my hot bar. There was a superfluous
crafting table block on the ground that I never could collect but ended up
going away on its own. The crafting table was in my hotbar when I switched
back from tablet mode. Placed it, picked it up and it went mia again.
Showed in inventory as being in my hotbar but not in game play. Thats my
recollection anyway. I was so happy that it sorta worked that I joyquit to
post my findings. Attached a screen shot just cause.

**Comment by dktapps** [comment]
@ducdude Yeah the hotbar is an issue across all platforms, it's just more noticeable on Win10. And consider yourself lucky I didn't give you the previous build instead, because that one would kick you for all kinds of stupid reasons xD

**Comment by MineCorps** [comment]
I'm arriving a bit late to the party apparently---is the "an' I threw it on the grounnnn" issue resolved?

**Comment by dktapps** [comment]
@MineCorps crafting works, dropping items works. Hotbar doesn't work properly, but that's a common problem across all platforms. Fixes haven't been committed to master because of some other resulting bugs.

**Comment by dktapps** [comment]
If you want to try out the `windows-10-beta` branch, feel free.

**Comment by dktapps** [comment]
Refer to #1337 to track progress. I'm going to close this one in favour of that one.

**Comment by dktapps** [comment]
Would everyone like to head over to #1621 and tell me how awesome I am? :P
