### ISSUE TITLE
 Protection

### ISSUE THREAD

**Issue by FIRERO** [iTXTech/Genisys#448]
I have a problem with protection. Players cannt break the blocks in unprotected area but OPs can! I use two protected plugins: RegionGuard and iProtector There is only one world in my server.

**Comment by jasonczc** [comment]
It's the problem of your plugins.

**Comment by FIRERO** [comment]
I was in a hosting of mcpe servers and there was no problems. And now I on a vds server and now this is problem

**Comment by PeratX** [comment]
Turn off spawn-protection
