### ISSUE TITLE
Add AutoSpawnMobEvent

### ISSUE THREAD

**Issue by BobbyTowers** [iTXTech/Genisys#449]
I run a multi-world server and would like to see if you could add a option in the Genisys.yml to choose which worlds you would like them to spawn in.

**Comment by astersx** [comment]
Wen i post that my comment was closed,  "we would never add that'
unfair 😓

**Comment by gaoyichuan** [comment]
@astersx We will only add the thing we think is useful

**Comment by astersx** [comment]
My post was similar to this.. why my closed and this post no?...  😠
