### ISSUE TITLE
RaklibInterface

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#452]
Today I got this error 
 [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to a member function dropItem() on null
And it was right after blocking an ip address for 5 mins

**Comment by flaxues** [comment]
Same problem!

```
[12:18:19] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to a member function dropItem() on null
```

**Comment by flaxues** [comment]
@PeratX

**Comment by PeratX** [comment]
More details please.(backtrace

**Comment by flaxues** [comment]
There is nothing just a error and I don't know when or how it happens...

**Comment by TheClimbing** [comment]
It just happens after like 5 mins.Guess I'll have to try to reproduce it myself

**Comment by BlackShadow1** [comment]
How to reproduce?

**Comment by TheClimbing** [comment]
Well with the latest build from jenkins. There isn't any specific way to reproduce it. It just happens

**Comment by flaxues** [comment]
And?

**Comment by TheClimbing** [comment]
Well its working for me. I've maked a pr but PocketKiller says it isn't an actual fix

**Comment by flaxues** [comment]
If you don't use ports higher than ≥32768

Change it to: 
```
$port = $this->getShort();
```
Instead of:
```
$port = $this->getShort(false);
```

**Comment by TheClimbing** [comment]
I've fixed it with $port = $this->getShort(true);
But that's not official so I'm not closing this issue

**Comment by flaxues** [comment]
I just reverted it to normal because I only use 19132
