### ISSUE TITLE
Genisys 生成的地图，是不是没有岩浆？

### ISSUE THREAD

**Issue by zxl777** [iTXTech/Genisys#454]
Genisys 生成的地图，是不是没有岩浆？

**Comment by dog194** [comment]
地狱有，主世界没有，如有需要请自行去寻找看看有没有相关插件可以实现。

**Comment by zxl777** [comment]
这个应该是bug吧？ 至少是还可以完善一下，没有岩浆，也就没办法到地狱的地图。

**Comment by dog194** [comment]
1地图生成器全部需要开发者自己编写，且这是一个艰巨的工作。2.地狱的地狱门只会生成一个，并不是一一对应的，地狱门的生成也是靠op权限玩家。3.开发者大多是学生，开学阶段开发时间有限，现阶段也是优先修复bug.

**Comment by zxl777** [comment]
好的，已经用创造模式建了地狱门。
