### ISSUE TITLE
/give issue with potions and golden apples

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#457]
When I do /give {name} 373:{Potion_ID} And drink the potion, it doesn't give me the potion effect and same thing for golden apples when I give myself a golden apple it doesn't give me the effects

**Comment by Driesboy** [comment]
drop potion and pickup

**Comment by TheGalaxyLord** [comment]
Well I am sure that all the players won't drop the potions and pick it up again for it to work

**Comment by Driesboy** [comment]
ok haha

**Comment by PeratX** [comment]
Will fix.
