### ISSUE TITLE
Colored Text Disappearing on Signs

### ISSUE THREAD

**Issue by CLiu13** [iTXTech/Genisys#459]
When I write colored text on signs, they disappear after I finish typing the sign. This does not happen with regular, uncolored text.

**Comment by flaxues** [comment]
Plugins?

**Comment by CLiu13** [comment]
None. Clean, vanilla server.

**Comment by flaxues** [comment]
Hmm I'm having this issue too!

**Comment by CLiu13** [comment]
What is the current status for this bug? Unconfirmed, fixing, etc. @PeratX

**Comment by PeratX** [comment]
Friday will have time

**Comment by PeratX** [comment]
This does not happen to me. (survival creative op notop)

**Comment by Muqsit** [comment]
Does not happen to me either! Maybe your server is lagging. Send TPS and load.

**Comment by CLiu13** [comment]
I have thoroughly tested this, and it still occurs. TPS average: 18.27 (over a 1 hour period) and load is between 30%-50%. 

Perhaps this could be a possible fix? 

https://github.com/ClearSkyTeam/ClearSky/commit/bdd8a3e97630a7717c5f6b03f4259d6ef0217f9c
https://github.com/ClearSkyTeam/ClearSky/commit/8e4cfcd9787c36f6c60b9b890bd6f3c753673e14

**Comment by PeratX** [comment]
No help

**Comment by Muqsit** [comment]
This is happening to me now! On plain Genisys server. I'll try ClearSky's fix

**Comment by Muqsit** [comment]
This is happening to me now! On plain Genisys server. I'll try ClearSky's fix

**Comment by PeratX** [comment]
Check setRemoveFormat

**Comment by Muqsit** [comment]
alright
