### ISSUE TITLE
Join and Leave Message Pop-Up Time  Length

### ISSUE THREAD

**Issue by BobbyTowers** [iTXTech/Genisys#462]
I love the option on the join and leave message to use a pop-up but can you make the pop-up last a little longer so my players have a few seconds to see the players name?

**Comment by flaxues** [comment]
Make a option in the genisys.yml for the duration of the pop up/tip!

**Comment by PocketKiller** [comment]
that's MCPE... when we send the popup/tip we only send one packet...
