### ISSUE TITLE
Installer for you!

### ISSUE THREAD

**Issue by seetch** [iTXTech/Genisys#465]
I create installer Genisys for your! https://github.com/seetch/Genisys-Install

**Comment by Driesboy** [comment]
nice

**Comment by Driesboy** [comment]
can you make it for windows

**Comment by TheKillerTacos** [comment]
There is already one for Windows, at README.md

**Comment by keithkfng** [comment]
You idiot. It's not created by you. It's created by ImagicalMine developers. It clearly says it has a license and you don't even bother to read it. https://github.com/ImagicalMine/php-build-scripts/blob/master/LICENSE
What does it say? IT CLEARLY SAYS NO COPYING.

**Comment by MasterWolf** [comment]
@seetch COPYRIGHT!!! How you can?!

**Comment by seetch** [comment]
@keithkfng and @MasterWolf it code full my! i'm not copy~

**Comment by keithkfng** [comment]
Wow. I remember writing the "(32-bit system)" lines myself while I was mucking around with my Ubuntu server. Stop lying.

**Comment by MasterWolf** [comment]
: /
