### ISSUE TITLE
Enchantment bug ( VERRY BUGGY ) 

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#466]
tab enchant and not open,help pls

**Comment by Driesboy** [comment]
enchantment is not working

**Comment by TheKillerTacos** [comment]
Enchanting table doesnt works as far as i know. but using /enchant

**Comment by NycuRO** [comment]
Why not fix?

**Comment by TheKillerTacos** [comment]
It isnt easy, but maybe? idk,

**Comment by flaxues** [comment]
Enchanting tables does work it is just really buggy players can enchant pickaxes with efficiency but no fortune...

**Comment by TheKillerTacos** [comment]
oh, i thought it wasnt but i think it doesnt do a Really good random enchants (the ones available for the specs,)

**Comment by flaxues** [comment]
I can get efficiency V ! But if there is text with fortune and you want to enchant you just lose the item :/

**Comment by TheKillerTacos** [comment]
Maybe the enchant Fortune isnt done yet, so thats the hard stuff...

**Comment by PeratX** [comment]
Enchanting table now works! genisys.yml allow-anvilandenchanttable
