### ISSUE TITLE
Ore Block bug. not dropping ore when broken.

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#467]
When breaking the "ore blocks" they don't drop the item. Only iron and gold ore work.

**Comment by Driesboy** [comment]
do you use pickaxe 4 or more

**Comment by Tolo0** [comment]
I tried diamond and iron pickaxe. Nothing drop.

**Comment by Driesboy** [comment]
ok

**Comment by Tolo0** [comment]
Is this bug fixes?

**Comment by PeratX** [comment]
fixed

**Comment by Tolo0** [comment]
Thank you 😊
