### ISSUE TITLE
PLEASE READ...Dont just close it...

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#468]
TypeError: "Argument 1 passed to pocketmine\nbt\NBT::putItemHelper() must be an instance of pocketmine\item\Item, null given, called in phar:///home/user/Desktop/Server/PocketMine-iTX.phar/src/pocketmine/entity/Item.php on line 165" (EXCEPTION) in "/src/pocketmine/nbt/NBT" at line 83

**Comment by Driesboy** [comment]
same

**Comment by DavidJBrockway** [comment]
ik

**Comment by gaoyichuan** [comment]
This is fixed, try out the latest build in jenkins.
