### ISSUE TITLE
Win10 console issue can't enter commands

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#473]
On my two windows 10 PM servers after a while I can't enter console commands. My Linux server seems fine.

**Comment by flaxues** [comment]
Do you have this on more servers if so reinstall you're mc!

**Comment by NML32** [comment]
I'm not able to enter commands in the PM server console. PM is running on Windows.

**Comment by gaoyichuan** [comment]
Windows is buggy.. If you can, don't use it

**Comment by Muqsit** [comment]
Windows 10 Edition is in beta!

**Comment by NML32** [comment]
I'm not talking about Windows 10 MCPE

**Comment by Muqsit** [comment]
Oh sorry. Does the console freeze?

**Comment by NML32** [comment]
No, just stops responding to commands.

**Comment by NML32** [comment]
Still testing but as of Build 154 commands seem to be working in console.

**Comment by ishitatsuyuki** [comment]
If you confirmed that issue is resolved, please close it. Also, you are recommended to write the git hash (7 digits hex) instead of build number.
