### ISSUE TITLE
Please fix this bug :3

### ISSUE THREAD

**Issue by Muqsit** [iTXTech/Genisys#474]
Players on my server reported a bug where when a player dies, they don't drop items. Keepinventory is off in genisys.yml

I'd also like to know whether only I am the one having this bug.

**Comment by tankisu01** [comment]
List of plugins, please

**Comment by MasterWolf** [comment]
@Muqsit check if you dont have plugins like InvSave

**Comment by Muqsit** [comment]
@tankisu01 Here!

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux rumbencraft 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
åŠ è½½çš„æ’ä»¶:
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
RBCLogger 1.2.0 by RumBenCraft for API(s) 1.12.0
FactionsPro 1.4.1 by Muqsit for API(s) 1.12.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
OPME 1.0 by Anonymous for API(s) 1.0.0
iProtector 3.1a by LDX for API(s) 1.9.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
EconomyShop 2.0.3 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
LuckyBlock 2.0.0 by xionbig for API(s) 1.12.0
RumBenHelper 1 by Muqsit for API(s) 1.13.1
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
PmChair 1.2 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
RumBenCraftCMDSelector 1 by Muqsit for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
EconomySell 2.0.5 by onebone for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0

@MasterWolf Checked, I don't think I have any plugins that have anything to do with inventories :/

**Comment by tankisu01** [comment]
@Muqsit what does OPME do?

**Comment by Muqsit** [comment]
@tankisu01  /opme will kick a player and tell them to not ask for OP.

**Comment by Muqsit** [comment]
Really sorry but it was all because of ClearLagg and...me! I had set it so as the server will clear entities every 0.5 minutes. So sorry...setting this to 5 minutes made everything go back to normal.
