### ISSUE TITLE
Request: Could the Build/Version be displayed

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#475]
In other flavors of PM you can see the Build or version in the title bar and when you do /version. In Genisys you only see Genisys 1.1-#0 on the title and no build info when you do status.

**Comment by PeratX** [comment]
will fix

**Comment by gaoyichuan** [comment]
@PeratX It needs modification in the build script?

**Comment by PeratX** [comment]
@gaoyichuan Yes. I will tell you in QQ
