### ISSUE TITLE
critical effect bug

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#478]
The extra heart effect gives u more and more hearts when u relog. Permanently.
![dda95039-12d0-400e-b134-435d2b76ec27](https://cloud.githubusercontent.com/assets/13458191/13467837/eab58192-e097-11e5-93a5-53833eefe1ef.jpg)

**Comment by TheClimbing** [comment]
Mikasaa <3

**Comment by flaxues** [comment]
I'm having the same issues!

**Comment by Tolo0** [comment]
Yea this bug is realy annoying. I player told me he counted 160 hearts then lost count 😅. Iv had to leave Genisys and use a different build. I hope they fix it soon.

**Comment by PeratX** [comment]
Effect ID please

**Comment by Tolo0** [comment]
ID 21

**Comment by Tolo0** [comment]
Really happy you fixed this. I can go back to genisys build now 😊
