### ISSUE TITLE
Opwning inventories

### ISSUE THREAD

**Issue by Creeperface01** [iTXTech/Genisys#479]
Brewing and enchant inventory doesn't work it just show another inventory for few miliseconds

**Comment by Muqsit** [comment]
They do...at least for me. Are you using the latest build??

**Comment by Creeperface01** [comment]
Ok i try it again :)

**Comment by PeratX** [comment]
genisys.yml allow-anvilandenchant !

**Comment by Muqsit** [comment]
^
Fully working but sometimes items disappear.
