### ISSUE TITLE
php7 ?

### ISSUE THREAD

**Issue by AndreTheGamer** [iTXTech/Genisys#481]
Hi' i've tried downloading PHP7 From G repo. But no luck when using ./start.sh

I get the following error 

``  /home/test/bin/php7/bin/php: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
``

Running CentOS

can you help?

**Comment by Muqsit** [comment]
`apt-get install make autoconf automake libtool m4 wget  gzip bzip2 bison g++`

**Comment by AndreTheGamer** [comment]
@Muqsit  Command isn't found. And also i'm running CentOS

**Comment by Muqsit** [comment]
@AndreTheGamer Oh, then it's
`yum install make autoconf automake libtool m4 wget gzip bzip2 bison g++`

**Comment by PeratX** [comment]
wget https://raw.githubusercontent.com/iTXTech/php-build-scripts/master/compile.sh
chmod 777 compile.sh
./compile.sh

**Comment by AndreTheGamer** [comment]
@Muqsit  I've tried that -_-

**Comment by AndreTheGamer** [comment]
@PeratX  Says i need g++    -_-

**Comment by PeratX** [comment]
yum install make autoconf automake libtool m4 wget gzip bzip2 bison g++

**Comment by XiangZhao969** [comment]
[game@static ~]$ ./start.sh
php is /usr/bin/php
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.

-----------------------------

Help me please, i'd already used the compile.sh

**Comment by XiangZhao969** [comment]
And this
---------------
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/php7/bin/php)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/game/bin/php7/bin/../lib/libz.so.1)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/game/bin/php7/bin/../lib/libyaml-0.so.2)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/game/bin/php7/bin/../lib/libpng16.so.16)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/game/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/game/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/game/bin/php7/bin/../lib/libcurl.so.4)
./bin/php7/bin/php: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/game/bin/php7/bin/../lib/libcurl.so.4)

**Comment by AndreTheGamer** [comment]
Ya... I have no idea how to fix that issue

**Comment by XiangZhao969** [comment]
@AndreTheGamer Just delete /bin in your server folder and run compile.sh again, it works!

**Comment by AndreTheGamer** [comment]
@XiangZhao969  I did that and still recieing same erors
