### ISSUE TITLE
mcpe closing as soon as joining server

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#484]
I very recently installed genesis pocketmine on my windows computer but very often, there is a problem where no one can enter the server. as soon as you enter the server and it completes building terrain, minecraft closes and this happens for everyone. there are no error messages in the console. I have tried running pocketmine genisys with no plugins but this still happens randomly.

please help

**Comment by PeratX** [comment]
Broken chunk with unsupported Blocks

**Comment by kabluinc** [comment]
How to fix this problem?
