### ISSUE TITLE
Teleport Glitch

### ISSUE THREAD

**Issue by jazzwhistle** [iTXTech/Genisys#489]
Hi, I've noticed the following official commit is missing from the Genisys Player.php

https://github.com/PocketMine/PocketMine-MP/commit/0723112207c28a4e792a0e0e51fbc839391b473b

Was this removed recently, and could this be the cause of the current tp glitch?
Thanks

**Comment by PeratX** [comment]
NO. This has removed in official repo.

**Comment by jazzwhistle** [comment]
Indeed... Unfortunately it's a problem that's hard to reproduce
consistently but affects all pocketmine builds
