### ISSUE TITLE
Redstone Glich

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#49]
If i put redstone down,  break,  go in another map,  and then come back home,  redstone reapear!!!
So players get unlimited redstone!!!

**Comment by PeratX** [comment]
What do you mean...I just cannot understand.

**Comment by astersx** [comment]
Ok,  lets say,  you put on dirt redstone ok? The just go far away,  example on another world ok? Now go back on dirt ok? Redstone Still on dirt (redstne reapeared),  redstone spawned again....
Hope u understand

**Comment by astersx** [comment]
Anyway,  if u break redstone,  you get the redstone drops,  but it spawn again !!!

**Comment by PeratX** [comment]
Sorry , I did not catch that issue.

**Comment by dog194** [comment]
@astersx  .Well, i just have a test (used the latest version from github). i put down 4 redstone on two dirt(called dirtA and dirtB) and two grass block(called grassA and grassB). Next i leave the server and login again. Ensure redstone exist. Then i break the redstone on dirtA and grassA and get two redstone back to my bag. After this i move to another map and have a little break. Then come back. But nothing happen. I break the redstone on dirtB and GrassB. Move to another map and have a rest. Then come back. nothing happen too..

**Comment by dog194** [comment]
So, does this happen everytime? Or just when put on some special kinds of block? Or just happen under the special conditions?

**Comment by astersx** [comment]
i put many redstone down,  i break them all,  teleport in anothe map,  teleport back,  redstone is back,  and i can break again :(.
 
Anyway forgot to tell,  i have redstone turned off :p

**Comment by astersx** [comment]
confirmed,  to have this glich need redstone false!!!  I put it true now no glich,  but redstone works, so i banned with world protect to make sure players wont use redstone to make lag on server!!

**Comment by PeratX** [comment]
We will check this issue . Thx a lot :)

**Comment by PeratX** [comment]
Please check it @astersx

**Comment by astersx** [comment]
I cant now,  i got many players on server and i cant stop server,  i will test it wen is time to restart server!!! Hope is fixed :)
