### ISSUE TITLE
how to fix client crashing

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#491]
Hi, every now and then some player's minecraft crashes and it continues to crash every time they join. I have tried always spawn plugin but still occurs HOW TO FIX?

Thanks

**Comment by NML32** [comment]
It's happening on all my servers that are running Genisys.

**Comment by CLiu13** [comment]
I am having this issue too. When I try to join my server, I always crash on my first attempt to join. Then, on my second attempt to join, I sucessfuly log in and am able to play for about 10 minutes until I crash again.

**Comment by Muqsit** [comment]
Probably due to overloading. Does your server lag at random intervals?

**Comment by CLiu13** [comment]
No, it does not at all.

**Comment by kabluinc** [comment]
All other versions of pocket mine including the original work flawlessly but with genisys I'm getting these client crashes... How to fix?

**Comment by PeratX** [comment]
Nope....

**Comment by ishitatsuyuki** [comment]
You can try to get a logcat.

**Comment by kabluinc** [comment]
Been using clearsky pocket mine for almost 2 days and have not had a single client crash. Happened almost every time with genisys. No errors are displayed and no crash reports are generated when the clients crashed. Must be an issue with the genisys.phar itself.

**Comment by NguyenQuangLap** [comment]
.

**Comment by kabluinc** [comment]
As you can see from the link below https://github.com/ImagicalMine/ImagicalMine/issues/231336
imagical mine too had this client crashing after joining problem and it was the phar that needed to be updated to fix this issue.

**Comment by antoinorxd** [comment]
The project Genisys is abandoned, you need to move on PMMP the new "Genisys" 
There is the link : https://pmmp.io/
