### ISSUE TITLE
getItemInHand() on null

### ISSUE THREAD

**Issue by tankisu01** [iTXTech/Genisys#492]
Genisys Crash Dump Wed Mar 2 20:37:13 MSK 2016

Error: Call to a member function getItemInHand() on null
File: /src/pocketmine/entity/Human
Line: 237
Type: notice

Code:
[228] 			$pk->eid = $this->getId();
[229] 			$pk->x = $this->x;
[230] 			$pk->y = $this->y;
[231] 			$pk->z = $this->z;
[232] 			$pk->speedX = $this->motionX;
[233] 			$pk->speedY = $this->motionY;
[234] 			$pk->speedZ = $this->motionZ;
[235] 			$pk->yaw = $this->yaw;
[236] 			$pk->pitch = $this->pitch;
[237] 			$pk->item = $this->getInventory()->getItemInHand();
[238] 			$pk->metadata = $this->dataProperties;
[239] 			$player->dataPacket($pk);
[240] 
[241] 			$this->sendLinkedData();
[242] 
[243] 			$this->inventory->sendArmorContents($player);
[244] 
[245] 			if(!($this instanceof Player)){
[246] 				$this->server->removePlayerListData($this->getUniqueId(), [$player]);
[247] 			}

Backtrace:
#0 /src/pocketmine/Player(927): pocketmine\Player->spawnTo(pocketmine\Player Player(8453))
#1 /src/pocketmine/Player(885): pocketmine\Player->doFirstSpawn(boolean)
#2 /src/pocketmine/Player(2078): pocketmine\Player->sendNextChunk(boolean)
#3 /src/pocketmine/Server(2928): pocketmine\Player->checkNetwork(boolean)
#4 /src/pocketmine/Server(2618): pocketmine\Server->tick(boolean)
#5 /src/pocketmine/Server(2496): pocketmine\Server->tickProcessor(boolean)
#6 /src/pocketmine/Server(2029): pocketmine\Server->start(boolean)
#7 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft-pe/server/, string /home/minecraft-pe/server/, string /home/minecraft-pe/server/plugins/)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux ns350827.ip-37-187-174.eu 2.6.32-openvz-amd64 #1 SMP Thu Mar 6 16:34:46 MSK 2014 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
Rainbow 1 by WorldCraftTeam for API(s) 1.12.0
ChatScribe 1.2.0 by aliuly for API(s) 1.10.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
BanClient 1.1 by luca28pet for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
NoServer 1 by WorldCraftTeam for API(s) 1.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
Fly 1 by WorldCraftTeam for API(s) 1.12.0
GMCMD 2 by MamayAdesu for API(s) 1.12.0
BouncyBlocks 1.1 by Darunia18 for API(s) 1.9.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
CL 1 by WorldCraftTeam for API(s) 1.8.0
RegionGuard 1 by WorldCraftTeam for API(s) 1.6.0
SaveInv 0.0.1 by Pub4Game for API(s) 1.12.0
essentialsTP 2 by  for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
GrabBag 2.3.0 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0

**Comment by Varfalomey** [comment]
its no core problem

**Comment by PeratX** [comment]
This is not related to Genisys
