### ISSUE TITLE
FloatingTextParticle black title

### ISSUE THREAD

**Issue by darkspive** [iTXTech/Genisys#494]
Can u remove black title argument. It is not very well....
![screenshot_2016-03-04-19-47-50](https://cloud.githubusercontent.com/assets/14966273/13530297/88751068-e242-11e5-86b3-258289c25169.png)
![screenshot_2016-03-04-19-43-56](https://cloud.githubusercontent.com/assets/14966273/13530300/8e77d7fc-e242-11e5-9652-ca8c8685d2d6.png)

**Comment by darkspive** [comment]
Also \n works bad
![screenshot_2016-03-04-20-18-22](https://cloud.githubusercontent.com/assets/14966273/13531127/afcfe03a-e246-11e5-9192-ca58118dcd70.png)

**Comment by Varfalomey** [comment]
restart your phone, its no core problem

**Comment by PeratX** [comment]
Please look at FloatingTextParticle.php and I will rewrite this to an entity
