### ISSUE TITLE
slow world load

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#495]
imagicalmine worlds load faster than genisys worlds

**Comment by darkspive** [comment]
+++ but... Genisys have an potions and redstone

**Comment by darkspive** [comment]
Please fix chunk radius

**Comment by Driesboy** [comment]
im have potions and redstone

**Comment by gaoyichuan** [comment]
@PeratX has been working on this for a long time..

**Comment by Muqsit** [comment]
Uh? I have no problem with chunks on my server. But I will try using ImagicalMine's generators with Genisys :3

**Comment by fycarman** [comment]
I have no problem with chunks loading on my server,it is faster than ever (php7)

**Comment by Driesboy** [comment]
no not on myplot

**Comment by PeratX** [comment]
Actually chunk load is related to I/O and bandwidth. Genisys have more populators written by @Muqsit (Thanks)

**Comment by Muqsit** [comment]
:o I feel special now!

**Comment by Muqsit** [comment]
But @PeratX 
I tried using ImagicalMine's level folder with Genisys but use genisys's generators and looks like it worked. The chunks were loading faster but I kept getting TAG_LIST not defined error. If I figure out what causes chunks to load faster, i'll make a pull request!

**Comment by Driesboy** [comment]
haha

**Comment by Driesboy** [comment]
i have say it

**Comment by Muqsit** [comment]
But there's not a lot of difference to be honest. Also, try the official PocketMine build...the chunks load like as if it's written in C++!

**Comment by PeratX** [comment]
Should be more populators

**Comment by PeratX** [comment]
I mean: if chunk has been generated, there is no difference. but if this chunk hasn't been generated, it will take some time

**Comment by PeratX** [comment]
@Muqsit please check https://github.com/iTXTech to join iTXTech

**Comment by AndreTheGamer** [comment]
@fycarman  -_- I tried installing php7 on CentOS but i'm getting a issue about glic or something... How did you install php7??

**Comment by fycarman** [comment]
@AndreTheGamer I'm using these binaries: https://github.com/iTXTech/PHP-Genisys/blob/master/php_7.0.2_linux_x64(GLIBC%202.16).tar.xz and i'm running Centos 7 64bit.

**Comment by Dergercol** [comment]
Slow++++++++++

**Comment by PeratX** [comment]
Turn off chunk-async-request in genisys.ynl
