### ISSUE TITLE
please add

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#496]
please add ThreadedFactory.php

**Comment by Driesboy** [comment]
haha https://github.com/bigbrotherteam/BigBrother-0.14.0

**Comment by PeratX** [comment]
Removed in official repo too

**Comment by Driesboy** [comment]
yes but we need it for bibrother

**Comment by Varfalomey** [comment]
yeah :(

**Comment by XShockinFireX** [comment]
Yeah plz add it :(

**Comment by erkam2002** [comment]
Yeah pls

**Comment by ishitatsuyuki** [comment]
Please contact the author to use an alternative approach.
