### ISSUE TITLE
Player can cheat with mods

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#50]
Player can cheat with mods (give item)

**Comment by PeratX** [comment]
Please give me more details.

**Comment by MineBuilderFR** [comment]
When the player is in spectator mode, and uses a mods (BlockLaucher) to give objects / items, items do appear in its inventory, whereas with PocketMine objects / Item not appear :/

**Comment by PeratX** [comment]
But the items does not exists in the server . So they cannot use them?

**Comment by MineBuilderFR** [comment]
Player can use them :/ It can lauch Potion , drop Item etc..

**Comment by PeratX** [comment]
Try the latest version.

**Comment by MineBuilderFR** [comment]
Ok Thanks :)

**Comment by PeratX** [comment]
Did it work?

**Comment by MineBuilderFR** [comment]
I think it works :)
