### ISSUE TITLE
Can't set block 

### ISSUE THREAD

**Issue by Fer0c** [iTXTech/Genisys#500]
at first I can set and break block in creative,
but sometimes can't block and set .

**Comment by PeratX** [comment]
details

**Comment by Driesboy** [comment]
world protect or spawn protect

**Comment by Fer0c** [comment]
Sorry . @Driesboy That's right.

**Comment by Fer0c** [comment]
But break block effect response slow. This issue dont rerate.

**Comment by Driesboy** [comment]
ok
