### ISSUE TITLE
Crash =_=

### ISSUE THREAD

**Issue by AkeKy** [iTXTech/Genisys#501]
Genisys Crash Dump Sat Mar 5 15:15:38 ICT 2016

Error: pthreads detected an attempt to connect to an object which has already been destroyed
File: /src/pocketmine/scheduler/AsyncTask
Line: 85
Type: notice

Code:
[76] 
[77] 	public function isCrashed(){
[78] 		return $this->crashed;
[79] 	}
[80] 
[81] 	/**
[82] 	 * @return mixed
[83] 	 */
[84] 	public function getResult(){
[85] 		return $this->serialized ? unserialize($this->result) : $this->result;
[86] 	}
[87] 
[88] 	public function cancelRun(){
[89] 		$this->cancelRun = true;
[90] 	}
[91] 
[92] 	public function hasCancelledRun(){
[93] 		return $this->cancelRun === true;
[94] 	}
[95] 

Backtrace:
#0 /src/pocketmine/scheduler/AsyncPool(151): pocketmine\scheduler\DServerTask->onCompletion(pocketmine\Server object)
#1 /src/pocketmine/scheduler/ServerScheduler(268): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#2 /src/pocketmine/Server(2922): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 26)
#3 /src/pocketmine/Server(2618): pocketmine\Server->tick(boolean)
#4 /src/pocketmine/Server(2496): pocketmine\Server->tickProcessor(boolean)
#5 /src/pocketmine/Server(2029): pocketmine\Server->start(boolean)
#6 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/lobby/, string /home/lobby/, string /home/lobby/plugins/)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux ake 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:

**Comment by AkeKy** [comment]
I enable dserver in genisys.yml

**Comment by Driesboy** [comment]
do not enable.

**Comment by Driesboy** [comment]
its the same for me

**Comment by flaxues** [comment]
This has to do with pthreads

https://github.com/krakjoe/pthreads/issues/511

**Comment by flaxues** [comment]
Mentioned by PEMapModder here:
http://forums.pocketmine.net/threads/asynctask-issue-on-php-7.15625/
