### ISSUE TITLE
How about the official forum?

### ISSUE THREAD

**Issue by seetch** [iTXTech/Genisys#502]
I think many people will support this, I can do this.

**Comment by Muqsit** [comment]
So can I but not with perfection :3
forums.rumbencraft.me
Only looks good on PC ._.

**Comment by seetch** [comment]
@Muqsit, I can also, rupocketmine.net, for russian!

**Comment by gaoyichuan** [comment]
No, thanks. We already have gitter and github, no need for another platform.

**Comment by PeratX** [comment]
@gaoyichuan Actually, I am building a forum (forums.mcper.cn)

**Comment by seetch** [comment]
@PeratX we hope and believe!

**Comment by Muqsit** [comment]
Nice!!
