### ISSUE TITLE
Server crashing no crash log just "Killed" message in the console

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#504]
### Issue description
The server has been crashing with no crash logs only "Killed" in the console window.

### Steps to reproduce the issue
Let the server run all day.

### OS and versions

* Genisys:Current build #104
* PHP: 7.02
* OS: Linux 64 bit

### Crashdump, backtrace or other files
No crash dump.

**Comment by SuperAlecs** [comment]
Probably is a plugin problem, if you have WorldEditArt delete it.

**Comment by PeratX** [comment]
Sorry. Killed is related to kill, killall or plugin issues. Only Segfault is related to core.
