### ISSUE TITLE
Break block issue

### ISSUE THREAD

**Issue by Fer0c** [iTXTech/Genisys#505]
If I broke block. after a short interval It was vaild break block effect!
It is not useful.please bug fix.

**Comment by ishitatsuyuki** [comment]
Please use clear English to describe the problem.

**Comment by Fer0c** [comment]
I can't use clear English .sorry:(

**Comment by gaoyichuan** [comment]
Then use Chinese, we can't understand your English

**Comment by Fer0c** [comment]
Im Japanese. Icant understand 
This issue close.
Someone will maybe claim the issue

**Comment by ishitatsuyuki** [comment]
@Fer0c : Then use Japanese. I can understand.

**Comment by Fer0c** [comment]
クリエイティブ時にブロックを破壊すると少し遅れてパーティクルが発動します。
サバイバルでも同様に少し遅れます。

**Comment by ishitatsuyuki** [comment]
どのようなパーティクルですか？ブロック破壊ではパーティクルはないはずですが...

**Comment by Fer0c** [comment]
DestroyBlockParticleです。サーバー側の処理が遅いとそのぶんパーティクル表示まで時間かかるので、仕方ないのかもしれませんが・・・。

**Comment by ishitatsuyuki** [comment]
サーバー側の性能不足だと思われます。
不適切な点は見つかりませんでした。

**Comment by jasonczc** [comment]
@ishitatsuyuki So you've learned THREE kinds of languages?Amazing!

**Comment by Fer0c** [comment]
closeされた後ですがやはり私だけのサーバーの問題ではないようです。
他のサーバーでもバグが確認されています。
