### ISSUE TITLE
How to import world?

### ISSUE THREAD

**Issue by MasterWolf** [iTXTech/Genisys#507]
I was using ClearSky before. And now im using Genisys but i dont know how to import my world to Genisys! How to import world?

**Comment by Creeperface01** [comment]
copy world folder to worlds folder

**Comment by MasterWolf** [comment]
@Creeperface01 i did this but when i joined, i saw clean world without buildings.

**Comment by MasterWolf** [comment]
What can i do?

**Comment by Driesboy** [comment]
What is your world format

**Comment by MasterWolf** [comment]
@Driesboy  mcregion

**Comment by tankisu01** [comment]
@MasterWolf what's name of world's folder?

**Comment by MasterWolf** [comment]
@tankisu01 "World"

**Comment by tankisu01** [comment]
@MasterWolf make sure that world's folder name is the same as in server.properties

**Comment by MasterWolf** [comment]
@tankisu01 it is...

**Comment by tankisu01** [comment]
@MasterWolf i don't know what's the problem, i've changed from clearsky php5 to genisys php5 to genisys php7 and everything was fine
