### ISSUE TITLE
Inplement mobs from...

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#508]
Pls implement mobs ai from PureEntitys is stable  https://github.com/milk0417/PureEntities

**Comment by Muqsit** [comment]
I made an issue about that very earlier too. They have amazing AI but....kinda laggy.

Try spawning 20 mobs and the server overloads!

**Comment by erkam2002** [comment]
No with plugin not i have used it and i havent laggs

**Comment by Muqsit** [comment]
:o I haven't tried this plugin in a while. I'll try it then!

**Comment by gaoyichuan** [comment]
Our AI is implemented from MOW.

**Comment by PeratX** [comment]
We will REWRITE MobAIs. Not copy

**Comment by erkam2002** [comment]
Ok :)
