### ISSUE TITLE
stop freezes

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#511]
.![image](https://cloud.githubusercontent.com/assets/6584811/13553966/b5c55ce6-e3bc-11e5-9f57-06ef3543006b.png)
It may reproduce by use /stop or by plugin issue (forceStop)

P.S Freeze is very very long ;c

**Comment by gaoyichuan** [comment]
We already know the issue

**Comment by xpyctum** [comment]
@gaoyichuan This needs to be fixed as soon as possible

**Comment by astersx** [comment]
I have no problems with that for now,  it happen wen the server lag a lot,  and i mean a lot,  i had 80 players,  and server freeze at 2-3 seconds,  and restartme plugin count slowed a lot,  i needed to restart server manualy, i dont use latest :p

**Comment by Muqsit** [comment]
This is a PHP7 issue. PHP7 cannot handle too many players at once unlike C++ or Java servers (such as PC servers that are capable of handling more than 250 players in one server).

**Comment by xpyctum** [comment]
@Muqsit And what i need do to fix this issue? Nothing?
