### ISSUE TITLE
Drop

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#516]
If players have full inventory and take drops it drop other items! please fix it

**Comment by fycarman** [comment]
I can confirm this issue. How to reproduce: fill your inventory,then take 1 or more items from the ground,it will drop items in your inventory and pick up items on ground

**Comment by ishitatsuyuki** [comment]
Could not reproduce. Are you running master?

**Comment by astersx** [comment]
It happen to me too :)

**Comment by ishitatsuyuki** [comment]
Cannot confirm. Please provide the git hash.

**Comment by MineBuilderFR** [comment]
I confirm This issue and i have This bug

**Comment by ishitatsuyuki** [comment]
Closing for insufficient information.
