### ISSUE TITLE
Just question :D

### ISSUE THREAD

**Issue by diygun** [iTXTech/Genisys#520]
Hello
I m french and I Love Genisys because it's very fast and have a lot advantage
Thank You very much for make this !
but
I Have a question
How to convert this zip (or extracted file) to .phar file ?
♢♢♢♢♢♢♢♢♢♢♢♢♢♢♢♢
Thank you for Genisys

**Comment by diygun** [comment]
I close issue like that you was not bother: D

**Comment by dog194** [comment]
use "/ms" or use Jenkins http://jenkins.mcper.cn/job/Genisys-master/
