### ISSUE TITLE
Question. Because of no answer on gitter

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#522]
Well noone answered me if its possible soo. Is it possible to make a generate command where it will generate the map for certain amount of time.Because if you have a big open-world server and 70 players are going everywhere the server starts lagging because its generating the map.

**Comment by Muqsit** [comment]
Let me ask you a question...how much RAM does your system on which you host your server have?

**Comment by TheClimbing** [comment]
16GB

**Comment by Muqsit** [comment]
Edit your pocketmine.yml

` world-caches:
  disable-chunk-cache: false`

`chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 3
 #Amount of chunks sent around each player
 max-chunks: 22
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 1
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true`
