### ISSUE TITLE
Invisible chest

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#523]
Some players report me invisible chests long ago,  i was at theyr base and saw invisible chests too!!
They store stuff in chests and after a while it go invisible and all stuff from chests gone.
I didnt had this problem for long time.

I dont use latest,  i dont know what build i use,  but i have slime blocks,  so i dont think chests updaTed after slimeblock support!!

I will try to make a video on yt and post the link here!!

**Comment by Muqsit** [comment]
Do you use MineReset or a plugin that modifies the terrain?

**Comment by astersx** [comment]
No!!!!!! !!

**Comment by CLiu13** [comment]
I am having this problem too.

**Comment by Tee7even** [comment]
Are chests spawned by plugins? This may be caused by setting a chest block without a tile.

**Comment by CLiu13** [comment]
No, they are not. This particularly happens with double chests...

**Comment by markkrueg** [comment]
If it is helpful; I have seen this issue as far back as the PocketMine-MP build I was running when MCPE 0.11.x was current. So I do not believe this is a Genisys specific bug. It seems to happen to a player's chests in one particular place, and nowhere else. I believe it is some form of world corruption.

It would be extremely useful if there was a way to repair a corrupt piece of a world. Maybe a command that would allow an op to "rebuild" the chunk the op was standing on; and the server would then clear that chunk and rebuild it "fresh" (clearing all player modifications). I suggest /chunkrebuild

If that is possible; I can think of a few future enhancements to that command as well :-)

**Comment by Muqsit** [comment]
I fixed this by deleting MineReset. The chunk where the mines were, were the only chunks that used to get affected. :/

**Comment by CLiu13** [comment]
I don't have MineReset. This seems to happen only with double chests...
