### ISSUE TITLE
MultiCraft errro

### ISSUE THREAD

**Issue by DavidJBrockway** [iTXTech/Genisys#525]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

07.03 13:39:15 [Multicraft] Loaded config for "Genisys Not working"
07.03 13:39:28 [Server] INFO Warning: require_once(phar://\jar\genisys.0.14.0\PocketMine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "C:/Bitnami/multicraft-2.0.1-0/apps/multicraft/jar/genisys.0.14.0/PocketMine-MP.phar" file "src/pocketmine/PocketMine.php" in \jar\genisys.0.14.0\PocketMine-MP.phar on line 1
07.03 13:39:28 [Server] INFO Fatal error: require_once(): Failed opening required 'phar://\jar\genisys.0.14.0\PocketMine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.;.\ext') in \jar\genisys.0.14.0\PocketMine-MP.phar on line 1

### OS and versions

* Genisys: #119
* PHP:7.0.2
* OS: Windoes Server 2012 r2

### Crashdump, backtrace or other files

* ...

**Comment by gaoyichuan** [comment]
This is related to your server files, not Genisys itself. Try redownload the phar file
