### ISSUE TITLE
Crafting...

### ISSUE THREAD

**Issue by ScandiePlay** [iTXTech/Genisys#527]
I'm using Genisys build #119 with PHP 7. Using Linux Debian (I'm on Russian hosting mcpehost.ru).

I have an issue with crafting. To craft a diamond sword or shovel, I need only a diamond. Only diamond, without even a stick. Such a bug I have with different items. Really weird...
![screenshot_2016-03-07-22-24-39](https://cloud.githubusercontent.com/assets/17462298/13582379/b3fd0b36-e4b4-11e5-882b-ab3efd1b5696.png)

**Comment by orangetictac** [comment]
Do you have problems with memory leak?

**Comment by ScandiePlay** [comment]
No, I haven't. Everything is OK with memory.

**Comment by orangetictac** [comment]
Ты русский? :D

**Comment by ScandiePlay** [comment]
Если быть точнее, я - украинец =D

**Comment by orangetictac** [comment]
Я тоже, ты чтобы утечки избежать в pocketmine.yml настроил ОЗУ?

**Comment by ScandiePlay** [comment]
Выставлял.

![screenshot_2016-03-07-23-26-20](https://cloud.githubusercontent.com/assets/17462298/13583833/2e57557e-e4bc-11e5-9963-1dc505f4ad48.png)

**Comment by ScandiePlay** [comment]
Я написал статистику (плагин ScoreBoardStats; это как Scoreboard на ПК), вписал туда показывание значения TPS. Нагрузка на TPS не превышает 1.5%, когда один игрок. Карта не перегружена, стоят TimeCommander + ClearLagg, в TimeCommander поставил выполнение команд /lagg clearall и /gc на раз в минуту, так что, всё чистится, утечек нету, и не было.

**Comment by orangetictac** [comment]
А у меня в pocketmine.yml был global limit=0 и тупо сервер крашился из-за утечки

**Comment by ScandiePlay** [comment]
У меня раньше стояло тоже ноль, но из-за хорошей сборки, которая состоит из 22 плагинов (5 из них - моего авторства, с оптимизированным кодом), ничего не крашилось никогда. Я поставил значения памяти так, на всякий случай, и выставил в соответствии с выдаваемыми хостингом ресурсами.

**Comment by orangetictac** [comment]
У меня дедик за 3к, после перехода на пхп7 крашило

**Comment by orangetictac** [comment]
Душевно поболтали)

**Comment by ScandiePlay** [comment]
Я не покупал ни VDS, ни дедик; на хосте MCPEhost есть тариф Unlimit: безлимитные слоты (до 10 000), 3 ГБ оперативки, 6 ГБ SSD-квоты, и канал >500 MB / сек с Anti-DDoS - за 650 рублей (≈250 грн) / месяц.

**Comment by orangetictac** [comment]
У меня дедик на 8 ГБ ОЗУ, Intel Xeon 2,4 ГГц, 500 ГБ HDD, 30 Tb траффик, канал 2 х 1000Mbit, 4 ядра, 8 потоков

**Comment by orangetictac** [comment]
И да, только что проверил у себя на сервере крафт, у меня все отлично работает

**Comment by gaoyichuan** [comment]
@markkrueg Come here to check it please.

**Comment by ScandiePlay** [comment]
Sorry, I have turned reading recipes from json on. Now I turned it off, and craft works perfectly.

**Comment by xpyctum** [comment]
But it's a bug from reading json crafts.

**Comment by Tee7even** [comment]
>But it's a bug from reading json crafts.

Are there any json crafts defined by default?
