### ISSUE TITLE
Win 10 players cant craft items and unknown error?--Maybe related

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#529]
### Issue description

Write a short description about the issue
#Notice: Undefined offset: 0 in phar:///home/user/Desktop/Server/PocketMine-iTX.phar/src/pocketmine/Player.php on line 3332

### Steps to reproduce the issue

1. ...Windows 10 Cant craft items
2. ...Second one, i dont know what the error is

### OS and versions

* Genisys: Newest...
* PHP: 7
* OS: Linux

### Crashdump, backtrace or other files

* ...Notice: Undefined offset: 0 in phar:///home/user/Desktop/Server/PocketMine-iTX.phar/src/pocketmine/Player.php on line 3332

**Comment by gaoyichuan** [comment]
Upload your Backtrace or Crashdump please.

**Comment by Skyladd** [comment]
There is no crashdump and ive never heard of a backtrace. The error came from a player that said he couldnt craft in Windows 10 edition

**Comment by gaoyichuan** [comment]
Enable the debug mode please

**Comment by Skyladd** [comment]
I'd have to do it when he joins, which isnt at the time I'm awake because he lives on the other side of the  world, and the memory leek causes a HUGE server log due to server crashes. I'd give more info if i could, but all i can say is that Windows 10 players cant craft on my server and it gives that error when they try i guess.
