### ISSUE TITLE
/extractphar command don't work

### ISSUE THREAD

**Issue by vellrya** [iTXTech/Genisys#53]
Or i am stupid) How to use it?

**Comment by dog194** [comment]
This command is case-sensitive. So ensure you type the right word. And just input the phar's name no include the versions. eg: EconomyLand 2.0.9 plz input "/extractphar EconomyLand".

**Comment by PeratX** [comment]
@vellrya eg. /extractphar C:/EconomyAPI_v2.0.4.phar

**Comment by dog194** [comment]
@PeratX 我好像直接想成 /extractplugin 了。。囧. oh. The usage i said is for "/extractplugin". I am sorry for that.

**Comment by PeratX** [comment]
Ah... /extractplugin command is available too...

**Comment by vellrya** [comment]
I want extract another server core. Can I do it?

**Comment by jasonczc** [comment]
@vellrya unphar.com
