### ISSUE TITLE
Problem Drop Item 

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#531]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. --
2. ---

### OS and versions

* Genisys:
* PHP: 7 
* OS:

### Crashdump, backtrace or other files

When player [1] kills another player [2] and the inventory of the player [1] is complete, and the player [2] has the stuff, the player's [1] inventory begins to drop many for the inventory of player [2] can recover

**Comment by Muqsit** [comment]
:o Also reproduced when a player is wearing diamond armor and has X blocks/items in their inventory!

**Comment by fycarman** [comment]
I can confirm this issue

**Comment by PeratX** [comment]
How to reproduce?

**Comment by MineBuilderFR** [comment]
put plenty of ground item , then fill your inventory item , and try to recovered items

**Comment by PeratX** [comment]
sorry, What do you mean by 'recover'?

**Comment by MineBuilderFR** [comment]
" Try to return the items to the ground "

**Comment by MineBuilderFR** [comment]
Wholesale : Put plenty of items on the ground, fill your item inventory , and try to take the items you drop to the ground

**Comment by PeratX** [comment]
Thanks. Will try
