### ISSUE TITLE
Enchantment bug. Items is not enchanted

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#532]
### Issue description

Write a short description about the issue
Enchantment not enchant items
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Genisys: 1.1dev
* PHP: 7
* OS:

### Crashdump, backtrace or other files
I put Fishing Rod in enchantment and not show enchant. I put pickaxe and other items and e.g. 
Pickaxe show/give axe enchantment.
Fishing rod not show enchantments
And others... Sorry for my english,i'm romanian :+1:

**Comment by PeratX** [comment]
OK. Will check

**Comment by PeratX** [comment]
Checked. Not supported yet.
