### ISSUE TITLE
Sign interact 

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#54]
when I interact with a sign, I have to click a long time instead of touching :/

**Comment by jasonczc** [comment]
Check your plugins.

**Comment by EpicSteve33** [comment]
its not a plugins fault I have the same problem I used Imagimine Before Genisys after switching i have the problem

**Comment by PeratX** [comment]
@EpicSteve33 In adventure or spector mode?

**Comment by EpicSteve33** [comment]
in adventure mode

**Comment by PeratX** [comment]
@EpicSteve33 Try the latest build

**Comment by EpicSteve33** [comment]
it spams console

**Comment by PeratX** [comment]
Fixed.
