### ISSUE TITLE
Copy-paste

### ISSUE THREAD

**Issue by MrGenga** [iTXTech/Genisys#55]
Someone parts of code copy-pasted from my project https://github.com/PocketMinePlusPlus/PocketMinePlusPlus
And: I put into it StrangePacket to control with it my new future php-based proxy-server. But why you add it to Genisys?
Implementation of AI for mobs is very similar to mine. 
How can you explain this?

**Comment by PeratX** [comment]
I HAVE NOT KNOWN PM++ BEFORE YOU COPY MY FURNACE

**Comment by zzm317** [comment]
@MrGenga ==Please tell me why your AI is almost same to mine?

**Comment by zzm317** [comment]
@MrGenga The AI of Genisys is a copy of MyOwnWorld and @PeratX has already told me that.
