### ISSUE TITLE
Setup shell script to utf-8

### ISSUE THREAD

**Issue by Dergercol** [iTXTech/Genisys#573]
Please, can u fix it? Russian, Korean langs does not works
![screenshot_2016-03-08-21-55-16](https://cloud.githubusercontent.com/assets/17719426/13608966/c9c2cf36-e578-11e5-88d6-63c20818a0a4.png)

**Comment by seetch** [comment]
+

**Comment by PeratX** [comment]
i think your lang is missing

**Comment by gaoyichuan** [comment]
That's due to your teminal settings, not the shell script or Genisys. Since Chinese works well, other languages won't have any difficulty. Search on Google for 'linux terminal charset'
