### ISSUE TITLE
Does not works onEnable() and onLoad()

### ISSUE THREAD

**Issue by Dergercol** [iTXTech/Genisys#575]
### Issue description

Write a short description about the issue

Does not works onEnable() and onLoad()

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Genisys:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ... Does not exists

**Comment by Dergercol** [comment]
Does not works messages to console

**Comment by Dergercol** [comment]
Any messages

**Comment by PeratX** [comment]
Error in plugin.yml

**Comment by Dergercol** [comment]
It is not error in plugin yml!!!!!!
