### ISSUE TITLE
Genisys Bugs

### ISSUE THREAD

**Issue by MrSwa9** [iTXTech/Genisys#576]
### OS and versions

* Genisys: 112
* PHP:7.0
* OS: Linux

### Crashdump, backtrace or other files
- Bigorn doesnt work
- Sometimes items go back to chest when you get them off the chest.
- Some Enchantment dont do what they say : Fortune, Fire protect(maybe more).
- Can't enchant bow properly.
- Maybe put the vanilla craftings in Genisys because the one Genisys has are too easy to Craft (too easy literally).

**Comment by Muqsit** [comment]
Use crafting inventory of .json (check genisys.yml)

**Comment by Tee7even** [comment]
Is it really hard to write with a template?

**Comment by Dergercol** [comment]
Small chunk radius....
