### ISSUE TITLE
Cant join server

### ISSUE THREAD

**Issue by Fer0c** [iTXTech/Genisys#578]
サーバーを起動しプレイヤーがサーバーに入ろうとするとすぐエラーが出てサーバーが落ちてしまいます。
Genisys Crash Dump Thu Mar 10 17:00:38 JST 2016

Error: Call to a member function getPluginManager() on null
File: /src/pocketmine/entity/Entity
Line: 1571
Type: notice

Code:
[1562] 
[1563] 	public function despawnFromAll(){
[1564] 		foreach($this->hasSpawned as $player){
[1565] 			$this->despawnFrom($player);
[1566] 		}
[1567] 	}
[1568] 
[1569] 	public function close(){
[1570] 		if(!$this->closed){
[1571] 			$this->server->getPluginManager()->callEvent(new EntityDespawnEvent($this));
[1572] 			$this->closed = true;
[1573] 			$this->despawnFromAll();
[1574] 			if($this->linkedType != 0){
[1575] 				$this->linkedEntity->setLinked(0, $this);
[1576] 			}
[1577] 			if($this->chunk !== null){
[1578] 				$this->chunk->removeEntity($this);
[1579] 			}
[1580] 			if($this->level !== null){
[1581] 				$this->level->removeEntity($this);

Backtrace:
#0 /src/pocketmine/entity/FishingHook(45): pocketmine\entity\FishingHook->close(boolean)
#1 /src/pocketmine/entity/Entity(445): pocketmine\entity\FishingHook->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:139.33985191858.pocketmine\nbt\tag\DoubleTag:5.pocketmine\nbt\tag\DoubleTag:155.15789566047.}.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\FloatTag:163.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\StringTag:FishingHook.pocketmine\nbt\tag\ShortTag:12.})
#2 /src/pocketmine/level/format/generic/BaseFullChunk(148): pocketmine\entity\Entity::createEntity(string FishingHook, pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:139.33985191858.pocketmine\nbt\tag\DoubleTag:5.pocketmine\nbt\tag\DoubleTag:155.15789566047.}.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\EnumTag:pocketmine\nbt\tag\EnumTag{.pocketmine\nbt\tag\FloatTag:163.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\StringTag:FishingHook.pocketmine\nbt\tag\ShortTag:12.})
#3 /src/pocketmine/level/Level(2721): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#4 /src/pocketmine/level/Level(673): pocketmine\level\Level->loadChunk(integer 8, integer 9)
#5 /src/pocketmine/Player(858): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(1), integer 8, integer 9, boolean 1)
#6 /src/pocketmine/Player(2090): pocketmine\Player->sendNextChunk(boolean)
#7 /src/pocketmine/Server(2934): pocketmine\Player->checkNetwork(boolean)
#8 /src/pocketmine/Server(2624): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2502): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(2035): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/fer0c/TEST/, string /home/fer0c/TEST/, string /home/fer0c/TEST/plugins/)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux vultr.guest 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64
PHP version: 7.0.4
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:

**Comment by Driesboy** [comment]
do you spawn entities

**Comment by Fer0c** [comment]
Nothing maybe
