### ISSUE TITLE
Cant Join Server

### ISSUE THREAD

**Issue by XShockinFireX** [iTXTech/Genisys#579]
Ever since iv'e upgraded to Genisys PHP-7, im not able to join my server locally.

**Comment by Driesboy** [comment]
rename to localserver

**Comment by XShockinFireX** [comment]
rename what?

**Comment by XShockinFireX** [comment]
apparently no one else can join either =/

**Comment by PeratX** [comment]
Check your fire wall

**Comment by XShockinFireX** [comment]
It has nothing to do with my firewall this recently happened when i upgraded to php 7 I can still connect to my old server

**Comment by flaxues** [comment]
Having this sometimes too... It blocks most traffic and sometime you see some players getting a "Login timeout"

**Comment by gaoyichuan** [comment]
Maybe it's because of memory

**Comment by flaxues** [comment]
Nope not a memory problem it's out of the sudden because I can't really reproduce it... restarting the whole server doesn't work. Diffrent port works

**Comment by XShockinFireX** [comment]
I'll try different ports.

**Comment by flaxues** [comment]
Using a diffrent port works...

**Comment by XShockinFireX** [comment]
Using a different port still doesn't work =/
