### ISSUE TITLE
minecarts lol

### ISSUE THREAD

**Issue by EpicSteve33** [iTXTech/Genisys#58]
minecarts dont stay on the track it kinda is like a car pretty buggy but I still love the work that you put into this Its better then any version of pm that ive used

**Comment by CrayonDing** [comment]
We will solve it in the near future

**Comment by EpicSteve33** [comment]
ok just wanted to let u know that it was a thing

**Comment by PeratX** [comment]
@EpicSteve33 It is todo list and we will work on it later
