### ISSUE TITLE
How to disable mob spawn in some worlds

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#580]
Hello. I want to create a lots of worlds: 1-Survival, 2-For_Buildings. In 1 world mob-spawn is enabled, but in 2 - it must be disabled. So, how can I do this? Can u add to config this function? (To enable mob-spawn for different worlds)

**Comment by ishitatsuyuki** [comment]
Just place torches :P

**Comment by alex2534alex** [comment]
...

**Comment by PeratX** [comment]
Write a plugin and register listen to EntityGenerateEvent. if $event->getEntity()->getLevel()->getFolderName() == World Name $event->setCancelled()
