### ISSUE TITLE
The bug that the crops do not mature into

### ISSUE THREAD

**Issue by FUGAMARU** [iTXTech/Genisys#583]
### Issue description

The bug that the crops do not mature into
https://youtu.be/dNj1SJ8Tlag

I am a Japanese, translation may not be accurate.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Genisys:1.1dev
* PHP:PHP7
* OS:Ubuntu 14.04.4 LTS 64bit Desktop

### Crashdump, backtrace or other files

* ...

**Comment by markkrueg** [comment]
For those who cannot watch the youtube video. It shows wheat seeds being planted. It then goes on for 15 minutes, and the wheat seeds do not grow at all.

This may also be a problem with saplings? Can anyone confirm?

I can go through and test all plant types if that would help the developers.

**Comment by FUGAMARU** [comment]
The saplings does not grow up, too

**Comment by FUGAMARU** [comment]
Not only I but also other people say that the crops do not grow up

**Comment by gaoyichuan** [comment]
Check your genisys.yml for the ticks

**Comment by PeratX** [comment]
Check chunk-ticking

**Comment by FUGAMARU** [comment]
There is no item called "chunk-ticking" in genisys.yml

Download link of genisys.yml using with my server↓
https://app.box.com/s/bse6576xvl17e1b08fs0mdhyck5ro8mp

**Comment by markkrueg** [comment]
I believe PeratX is referring to pocketmine.yml:
```
chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 20
 #Radius of chunks around a player to tick
 tick-radius: 2
```
If those two are set to default of 0 then crops do not grow at all. However, even with the settings above; I believe saplings are not growing. I should test wheat as you did.

**Comment by FUGAMARU** [comment]
This problem was settled on the coattails of you. Thank you for your cooperation. I really appreciate it.
