### ISSUE TITLE
Enhancement: /chunkrebuild command

### ISSUE THREAD

**Issue by markkrueg** [iTXTech/Genisys#584]
It would be extremely useful if there was a way to reset a possibly corrupt piece of a world. Or it could be used to just reset an area that you want "cleaned up".

I suggest /chunkrebuild

This would allow an op to "reset" the chunk the op was standing on; and the server would then delete that chunk and generate it "fresh" (clearing all player modifications). 

It would also be great if an op could just view the file name of the chunk the op is standing on. 

I suggest /chunkinfo

Would list the file name of the chunk the op is standing on. This could be enhanced to provide more information on the chunk in the future.

Thanks for considering it!

**Comment by Driesboy** [comment]
like /lagg clear

**Comment by gaoyichuan** [comment]
+1 for this one.

**Comment by Tee7even** [comment]
This should be implemented as a plugin, not a basic server functionality.

**Comment by markkrueg** [comment]
@Tee7even I disagree. Since the server generates chunks; it is useful to have the ability to replace chunks built into the server. Genisys has already implemented world modification commands into the server; and it is useful.

**Comment by gaoyichuan** [comment]
/fill and /setblock were implemented just because there are them in the original MC.
