### ISSUE TITLE
Death issues

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#586]
When players dies I get stuck at where I died and it does't even show the death screen that says Respawn or Main Menu... and I can't move of course

**Comment by Muqsit** [comment]
Plugins?

**Comment by TheGalaxyLord** [comment]
I downloaded an older version of Genisys and that didn't happen so its definitely Genisys problem not a plugin

**Comment by ishitatsuyuki** [comment]
No. This could caused by any tricky coded plugin. Remove all plugin and try again.

**Comment by ishitatsuyuki** [comment]
Seems aa1af8e is the issue

**Comment by gaoyichuan** [comment]
Maybe aa1af8e made some plugins to cause the issue, since there is api change
