### ISSUE TITLE
MY "INCREASE SERVER PERFORMANCE IDEA"

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#589]
I have an idea!
How to increase the performance of the server.

If TPS sags for example up to 16, then the kernel puts the burden on the players' phones -> TPS is increased to 20 -> server is running stable.

But the need for greater speed of the Internet.

And add to genisys.yml stringstring
#Server performance increaser, using players devises to increase server performance.
#Switch to true, if you want to turn on this function.
Performance-increaser=false

==================================

Is it possible to do such a thing?

**Comment by ishitatsuyuki** [comment]
No. You really trust a player's computation?

Let me make a hack client and crash your server immediately.

**Comment by Tee7even** [comment]
Is it possible?

**Comment by ishitatsuyuki** [comment]
NO. No Minecraft client has this implementation. This is never seen in any game.

**Comment by Shamil0402** [comment]
I am using the Google translate.

**Comment by ishitatsuyuki** [comment]
So what? I have said that it's impossible. If you continue to spam I will lock this issue.
