### ISSUE TITLE
Error: Object of class pocketmine\item

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#591]
Running Build #132

Notice: Object of class pocketmine\item\Diamond could not be converted to int in phar://C:/Users/Mark/Desktop/PocketMine-PHP7/PocketMine-MP.phar/src/pocketmine/item/Item.php on line 1224

Notice: Object of class pocketmine\item\IronIngot could not be converted to int in phar://C:/Users/Mark/Desktop/PocketMine-PHP7/PocketMine-MP.phar/src/pocketmine/item/Item.php on line 1224

Notice: Object of class pocketmine\item\Steak could not be converted to int in phar://C:/Users/Mark/Desktop/PocketMine-PHP7/PocketMine-MP.phar/src/pocketmine/item/Item.php on line 1224

**Comment by gaoyichuan** [comment]
Can you upload a backtrace?

**Comment by PocketKiller** [comment]
we should have used Diamond::getId()
