### ISSUE TITLE
Too laggy,see my timings

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#593]
Hi! My server have 7 worlds,  and after 20-30 minutes server tps is just too low about 5.
My kvm vps have 4gb ram, 4cpu, SSD .  Becouse of SSD the lag does not feel at all in game,  just the Worlds loads very hard,  but break/movement are normal,  thanks to high I/O support.

My worlds have about 0.3 - 3ms    in status,  so i dont think is the problem.

I have 85 max players online , and in console i get sometimes illegal offset 0 in player.php, if u wanna more about this,  next time i will copy/paste...
My timings:  http://timings.aikar.co/?url=15366920

If is not genisys fault , pls any advice :+1:  !!!

**Comment by Muqsit** [comment]
This used to happen to me too because I used to schedule the command 'gc' through TimeCommander. Hope you're not executing 'gc' command every X minutes. I'd advise you to stop using it if you are doing so!

**Comment by PeratX** [comment]
How many entities do you have!

**Comment by astersx** [comment]
I do,  and enityes are the blocks dropped @PeratX . I will try,  and i can use /lagg clear via time commander?

**Comment by astersx** [comment]
Timimcommander executed /gc,  every 30 minutes,  is bad?

**Comment by astersx** [comment]
I just stopped,  still the same,  nothing changed!!!

**Comment by Muqsit** [comment]
On my server I run

clearlagg killmobs
And
lagg clear

...commands every 5 minutes! And I've removed the gc command from the config. And my server runs smooth with MOBS, Redstone and weather enabled!

**Comment by astersx** [comment]
You have 120+ players online? Fixed lag a little after i disambled chunk ticking!!  And i put more slots,  now i need to do something to fix the lag a little,  if server freeze im doomed!!

**Comment by astersx** [comment]
Depends on how many players are online,  with 30-50 players i have no lag :3

**Comment by astersx** [comment]
I found the problem,  restart me stop count,  so server will keep runing for hours,  until it freeze!! 😥

**Comment by Muqsit** [comment]
:o 
I have only 25 (or less plugins) on every server. So that's why...minimal lag! Use async tasks (not from genisys.yml, from pocketmine.yml) for better performance!

**Comment by astersx** [comment]
Genisys,  pocketmine.yml   have it enambled!! So i already use!!

**Comment by astersx** [comment]
My guess is that!!  Becouse i run 7 worlds + nether,  server lags with many players online!!!

**Comment by Muqsit** [comment]
Yeah, blame php for that! :P
 PHP can't handle many players too, you can get upto 120-170 players on a server after which it starts lagging.

**Comment by astersx** [comment]
I cant even get 80 on =)),  i put limit at 65. No other option!!

**Comment by XxDXM-hippiexX** [comment]
Might i ask what that is you use to see the timings? and is that only for mcpc? @astersx

**Comment by astersx** [comment]
? timings on in console,  wait,  then do timing paste  , after this will be show in console a link,  go there and see timings!!

**Comment by PeratX** [comment]
So ?
