### ISSUE TITLE
Dispenser tool is axe. Many of your tools are incorrect

### ISSUE THREAD

**Issue by thebigsmileXD** [iTXTech/Genisys#599]
Title

**Comment by ishitatsuyuki** [comment]
What are you saying? Use correct English and give more details.

**Comment by thebigsmileXD** [comment]
Then learn english.

**Comment by thebigsmileXD** [comment]
Many of your "new" classes (Dispenser, hopper etc) are copies of Chest.
So the getTool === Tool:Axe blaaaaa

**Comment by PeratX** [comment]
@thebigsmileXD Would you like to join us and help us. I am really busy these days.

**Comment by thebigsmileXD** [comment]
No. Because we know what happened in the history. Also i already rejected your invittation once.

**Comment by PeratX** [comment]
But you still care our project, right? History is not important, the future is. Why not help us and make Genisys better? Also it can help develop ClearSky

**Comment by Muqsit** [comment]
Fixed. :3

**Comment by ishitatsuyuki** [comment]
@Muqsit Side note: you can close the issue from pull request by properly writing commit message
