### ISSUE TITLE
Jenkins not loading

### ISSUE THREAD

**Issue by DWWf** [iTXTech/Genisys#6]
I tried to go on mcper Jenkins but it won't load! Is there another way to get the .phar?

**Comment by PeratX** [comment]
Please try again.

**Comment by DWWf** [comment]
It worked this time, thank you. Looking forward to using this :)

**Comment by darkspive** [comment]
Does not works

**Comment by CrayonDing** [comment]
Jenkins Server is transfering.please wait.sorry

**Comment by Wolfurama** [comment]
How much time this take?
