### ISSUE TITLE
Informal Forum

### ISSUE THREAD

**Issue by seetch** [iTXTech/Genisys#601]
Hello, I have created an unofficial forum of Genisys, where you can ask questions and stuff.

mctopus.ru

**Comment by gaoyichuan** [comment]
We will build one on our own. And we don't have time to check all unformal ones. So don't bother yourself

**Comment by seetch** [comment]
togda sosite xiu dayni!

**Comment by seetch** [comment]
vashe yandro lagaet kak gavno

**Comment by seetch** [comment]
imagicalmine foreva syki

**Comment by MasterWolf** [comment]
@seetch ти дебил.

**Comment by MasterWolf** [comment]
@PEMapModder @PeratX @PocketKiller @gaoyichuan You should ban @seetch !!! He said very bad words about us. (Very very bad. In russian language.) Ban him.

**Comment by MasterWolf** [comment]
@seetch ти еще пожалеешь что так сказал... И если что то ти себе так сказал.

**Comment by Tee7even** [comment]
Ой лол xD

**Comment by MasterWolf** [comment]
ахах. дизлайкаем его!

**Comment by PEMapModder** [comment]
Why mention me...

**Comment by seetch** [comment]
ahahahah, oh lol. you boom boom russian suck?

**Comment by PEMapModder** [comment]
This issue seems entirely irrelevant.
