### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#602]
Server Freeze at 40 minutes of running, sratus show 0.93 tps!!!!!! And if i stop server it freeze!!! 
![screenshot_2016-03-13-18-20-31](https://cloud.githubusercontent.com/assets/13157548/13729859/b5915d8e-e947-11e5-9f2f-b582b350e1e5.png)

**Comment by MrDoni98** [comment]
+++

**Comment by astersx** [comment]
I put restart me at 40 minutes ;)  !!
