### ISSUE TITLE
LevelDB Support?

### ISSUE THREAD

**Issue by XFuryMCPE** [iTXTech/Genisys#604]
Hey, my lobby was built in single player, so it's on LevelDB, could you add the support of LevelDB back?

**Comment by Skyladd** [comment]
I would say it's best to build your worlds in PC edition but not all the blocks transfer properly such as top slabs and fence, more stuff too. Not sure if it's possible but id look for a PE to PC world converter or PE to Anvil

**Comment by PeratX** [comment]
We do not suggest you use ldb worlds because it is not efficient on PocketMine. Use MCRegion instead.
If you really want to use ldb worlds, you can compile leveldb extension for php by yourself.
