### ISSUE TITLE
Anti-cheat 

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#606]
Genisys,  should add a simple anti-cheat. Just tested some hacks.  For example speed hack,  lags server,  and disturb other players + is hard to see cheater name at that crazy speed!!

You should add something that detect crazy speed and kick!!

**Comment by ishitatsuyuki** [comment]
And your server laggggggg!
Remember anti cheat is an expensive operation. It can also cause normal players rejected wrongly.

**Comment by astersx** [comment]
Just calculate speed.  And only kick if is too great!!

**Comment by flaxues** [comment]
Instant break is possible to block right?

**Comment by astersx** [comment]
I saw that too on my sv,  someone break stone using a stick,  i was like wtf!!!

**Comment by Muqsit** [comment]
But...no Minecraft server softwares come with such options...or do they?

**Comment by jasonczc** [comment]
It's laggy.Won't add.
