### ISSUE TITLE
Enhancement: option for broadcast when players change their gamemode

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Genisys#607]
It would be nice to get an option in genisys.yml to disable broadcast when players change their gamemode, because you can't disable it by plugin (if this information is right -> https://forums.pocketmine.net/threads/hide-gamemode-switch-message.13584/) and it spams the chat window.
Maybe you can implement it too.

**Comment by PeratX** [comment]
You can listen to PlayerTextPreSendEvent

**Comment by SleepSpace9** [comment]
This should work with "**/defaultgamemode**" command, because **sendmessage()**
 is used, but the common "**/gamemode**" or "**/gm**" uses **Command::broadcastCommandMessage**. Maybe this is also cancellable?

**Comment by SleepSpace9** [comment]
Sorry, my fault - **broadcastCommandMessage** also uses **sendMessage()**.  :smile:

Thanks for your tip! I'll try to add this to CustomAlerts-Plugin.
