### ISSUE TITLE
vps help

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#609]
hi I'm trying to use genisys on my vps CentOS 6 server. but having problems. would some one mind telling me how I can set it up?  iv put the build and the start.sh on then tried to start the server but I keep getting a error. I think it's to do with the bin. 
error. couldn't find a working PHP binary.

**Comment by Muqsit** [comment]
First install unzip package with
`yum install unzip`

Then install these packages with
`yum install make autoconf automake libtool m4 wget gzip bzip2 bison g++`


Then type this command...
`wget https://github.com/iTXTech/php-build-scripts/archive/master.zip; unzip master.zip; rm -rf master.zip; cd php-build-scripts; chmod +x *.sh; screen -s x ./compile.sh`

**Comment by Muqsit** [comment]
After 15 minutes, you will find a bin folder in the php-build-scripts folder. Copy it to the folder containing your start.sh file.

**Comment by Tolo0** [comment]
I'm stuck on this bit. what is mode? 
![screenshot_2016-03-14-20-05-39](https://cloud.githubusercontent.com/assets/13458191/13758227/4199967e-ea20-11e5-839e-448f8423d391.png)

**Comment by Tolo0** [comment]
![screenshot_2016-03-14-20-12-09](https://cloud.githubusercontent.com/assets/13458191/13758380/167161a6-ea21-11e5-800d-cb88596ba531.png)

**Comment by Tolo0** [comment]
how I get g++ ?

**Comment by Tolo0** [comment]
it's ok I found it lol "yum install gcc-c++"

**Comment by Muqsit** [comment]
Do
yum update
If no packages were found

**Comment by Tolo0** [comment]
got a new problem 
![screenshot_2016-03-14-20-39-38](https://cloud.githubusercontent.com/assets/13458191/13759183/fa067336-ea24-11e5-87e4-c2d2c8564de5.png)

**Comment by BlackShadow1** [comment]
> chmod +x *.sh
Do you see?

**Comment by Tolo0** [comment]
it worked 😊.  thanks alot guys. appreciate it.

**Comment by gaoyichuan** [comment]
@Muqsit Would you like to write a wiki page with the steps? That would be helpful for greenhands.

**Comment by ishitatsuyuki** [comment]
@gaoyichuan You may consider Docker. It's currently used for CI and is easy to setup.

**Comment by Muqsit** [comment]
@gaoyichuan sure!

**Comment by ishitatsuyuki** [comment]
@muqsit do you know docker? I think docker is easier to install and manage

**Comment by Muqsit** [comment]
@ishitatsuyuki no im new to this :/
