### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by Adam1609** [iTXTech/Genisys#610]
Anyway I could make a pull request about language, Genisys is missing a lot @@

**Comment by ishitatsuyuki** [comment]
Why you can't make a PR?

**Comment by Adam1609** [comment]
I think that if I translate it, it maybe touch Genisys's code, so i must ask about this

**Comment by PeratX** [comment]
Check src/pocketmine/lang/locale/eng.ini

**Comment by gaoyichuan** [comment]
Just make the PR. :) Be brave about the changes
