### ISSUE TITLE
Improve bow and add new features

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#611]
In pocketmine bow is not equal in Minecraft PE can improve it?
And in ClearSky have witch and cauldron , can add this in genisys?
Thanks!

**Comment by jasonczc** [comment]
How do you think about it?
@PeratX

**Comment by PeratX** [comment]
No time..

**Comment by Skyladd** [comment]
No time? But theres time to add a cave generator command lol..

**Comment by PeratX** [comment]
@Skyladd Not me. It is written by boybook

**Comment by PeratX** [comment]
We have Brewing Stand long time ago.
