### ISSUE TITLE
setCancelled() on EntityGenerateEvent doesn't work

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#614]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* Genisys: 148
* PHP: 7
* OS: windows 10

### Crashdump, backtrace or other files

* ...

Not really a issue..besides i get cows in my lobby XD and i cant cancel the entityspawnevent /: could you add a config option to set witch worlds to allow mobs to spawn in? like..

genisys.yml

#Choose if allow mob auto generate
 mobgenerate: true
#Choose witch worlds to spawn mobs in (false for all)
 mobspawnworlds:
    - wildworld
    - anotherworld
    - thatotherworld

**Comment by PeratX** [comment]
It should be EntityGenerateEvent

**Comment by XxDXM-hippiexX** [comment]
AHH thank you C:

**Comment by XxDXM-hippiexX** [comment]
setCancelled on entitygenerate doesn't  work..

**Comment by PeratX** [comment]
Paste your code here

**Comment by XxDXM-hippiexX** [comment]
public function mobSpawn(EntityGenerateEvent $ev)
    {
        $level = $ev->getEntity()->getPosition()->level->getName();
        if(!in_array($level, $this->getConfig()->get('Mob-Worlds')))
        {
            $ev->setCancelled(true);
        }
    }

i used var_dumps for debuging..var_dumped $level inside of the if statement and it stilled spawned the mob in the wrong world..

**Comment by PeratX** [comment]
Try getFolderName

**Comment by PeratX** [comment]
Confirmed. Will fix

**Comment by alex2534alex** [comment]
@PeratX , do, u willn'd add that? ((
"#Choose witch worlds to spawn mobs in (false for all)
mobspawnworlds:
- wildworld
- anotherworld
- thatotherworld"

**Comment by ishitatsuyuki** [comment]
Speak human language.

**Comment by alex2534alex** [comment]
I can' good speak English —-—
I mean "This means you do not add that feature?"
