### ISSUE TITLE
Hangs on restart

### ISSUE THREAD

**Issue by flaxues** [iTXTech/Genisys#616]
#### Issue description

When I use /stop the server just stays on "Server has stopped"

#### Steps to reproduce the issue

Stop the server with /stop

#### OS and versions

* Genisys: Latest version available on github.com
* PHP: 7
* OS: Ubuntu 15.04

#### Crashdump, backtrace or other files

```
There is no crashdump
```

**Comment by gaoyichuan** [comment]
A known issue

**Comment by flaxues** [comment]
I just upgraded from a older genisys because of some problems with raklib they should be fixed now but now I have this issue which is really annoying and is going to drasticly drop my uptime

**Comment by flaxues** [comment]
In other words you won't fix this.

**Comment by flaxues** [comment]
This is occuring since commit https://github.com/iTXTech/Genisys/commit/02af2a5bac70ff5ee29147a2284f379ef115895b

**Comment by PeratX** [comment]
@flaxues Did it fixed?

**Comment by flaxues** [comment]
I will try it in about 1-2 hours when I'm home

**Comment by FUGAMARU** [comment]
I suddenly rude.
But in my server it has a "DO_LOOP" of "start.sh" to "yes", the server does not start automatically.
Do you have a relationship This is a bug that has been reported here?

**Comment by FUGAMARU** [comment]
By the way, the server by pressing the Enter key in a state where the server does not start automatically will start to react to it.

**Comment by flaxues** [comment]
Yup same problem

**Comment by FUGAMARU** [comment]
I see

**Comment by gaoyichuan** [comment]
That's not fixed, confirmed

**Comment by PeratX** [comment]
Same as another issue.  Close
