### ISSUE TITLE
Flood, or... 

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#619]
Hi! It seems my server is attacked by some kind of flood!!
My server Kits,  used 3gb ram,  with 2-3 ppl online and it freeze it never did it before, then yesterday my  survival server was lagging again with 3tps with only 75 players online.  My server dont lag with just 75 players,  so i guess it is some kind of attack!! 

All week my server was runing with 75 players online and it never lagged and one day it lag like hell!!
It is not resources problem, it does not use all!!

4 cpu cores,  4 gb ram,  ssd.

So im sure this is an attack,  to cause genisys freeze. 

Can you check if is raklib problem?  Or just some buggy items available to craft?

**Comment by ishitatsuyuki** [comment]
Closing for insufficient information.

**Comment by flaxues** [comment]
Could you run a timings?

/timings on

and after some time do:

/timings paste and give us the link :)

**Comment by astersx** [comment]
I did,  there was something about network tick..  etc...  .  Wen i get this problem i report!!
What is strange,  ks that the in game you dont lag,   It take long time to connect,  but after that you are not lagging so much!!    Just worlds load...  etc.. is slower, and plugins that use count wont work!!
For example restartme and timeCommander wont work,  all fault lies in network!!


this is why i think is some kind of attack caused vulnerability in genisys!! But i may be wrong!!

**Comment by astersx** [comment]
I dont have timings adress anymore,  so wen i get the problem again,  i will post there timings

**Comment by astersx** [comment]
timings.aikar.co/?url=15408278

Its not so bad.....  But in other timings network was red and the numbers was crazy!!

**Comment by astersx** [comment]
Hi!! I wanna say something! HDD and SSD .
HDD : 
You get pulled back wen many players are online,  terrain glich trigger,  and other things save harder,  so u get pulled back with many players online,  but TPS remain at 18-19   with 100 players online!! Other things are fine

SSD:
You get no pulls back,  no terrain gliches , all are saving super fast!!
With many players, after 30 minutes tps 5-8  , entering in game takes a lot if time,  but only teleporting lags,  and plugins countdowns stop!!


So with SSD , performance is very low!!!  But less gliches!!

**Comment by flaxues** [comment]
I'm running HillCraft on a HDD since I'm not seeing a difference and HDD servers are cheaper

**Comment by flaxues** [comment]
And you're survival games plugin takes a lot of resources with updating signs...

**Comment by astersx** [comment]
I had the problems before i  installed sg games lol!!

**Comment by astersx** [comment]
Maybe mining,  breaking blocks , cause lots of loads -.-'. If 100 players start break blocks,  or mine...  it will cause high loads... my guess!!

**Comment by flaxues** [comment]
I'm just saying that it can cause some lagg

**Comment by Muqsit** [comment]
I run RumBenCraft on an HDD too and it doesn't lag either!
