### ISSUE TITLE
spawn 

### ISSUE THREAD

**Issue by MrSwa9** [iTXTech/Genisys#62]
hi
players spawn in another place and i can´t change this
thanks

**Comment by dog194** [comment]
try to use /setworldspawn

**Comment by MrSwa9** [comment]
i try but no work :(

**Comment by dog194** [comment]
is another place or another level(world)?

**Comment by MrSwa9** [comment]
another place ?

**Comment by dog194** [comment]
if you wanna players spawn in the level you want. Plz change level-name in server.properties.
If you wanna players spawn in the place you want. Plz try "/setworldspawn" and "/spawnpoint".

**Comment by MrSwa9** [comment]
thanks 
this pocketmine is prepared for how many players at most ?

**Comment by dog194** [comment]
oh. I don know. XD

**Comment by MrSwa9** [comment]
]0;Genisys 1.0-#0 | Online 101/100 | Memory 191.48/144.5/368.59/604.88 MB @ 16 threads | U 2793.5 D 350.15 kB/s | TPS 8.63 | Load 98.67%

is good ?

**Comment by dog194** [comment]
TPS 8.63. en....... No good i think. U can login your server and have a test by yourself. BTW you can use "/status"

**Comment by MrSwa9** [comment]
the first day i use Genisys #104 and my server have 180 players with 19.84 tps but know i reduce the limit for 100 and have 8.63 idk whats happend :(

**Comment by MrSwa9** [comment]
what is the best system for servers ?

**Comment by BlackShadow1** [comment]
I think Yuriko-MP from ItaDevs4PM

**Comment by MrSwa9** [comment]
how i do download the Yuriko-MP ?

**Comment by Jelly9912** [comment]
What is Yuriko-MP?

**Comment by MrSwa9** [comment]
is a software type PocketMine-MP

**Comment by PeratX** [comment]
Well,try to disable some features because they can cause your TPS low(especially AIs).

**Comment by BlackShadow1** [comment]
Go in this page and click download ZIP. https://github.com/ItalianDevs4PM/Yuriko-MP?files=1 
After that, you can extract the file. Double click on Yuriko-MP-master, cut src file, drop it into a file with a PHP binary(bin/PHP.exe and estension) and you can use Yuriko-MP, if you want to make it in a phar, download DevTools and write in the console "makeserver src", Yuriko-MP doesn't have a makeplugin or extractplugin like Genisys, but is also very very fast. @PeratX, Genisys is the better for now, i think you can make it much better :)

**Comment by PeratX** [comment]
Got ut : )

**Comment by fycarman** [comment]
Hi,I'm an admin of Yuriko-MP project. Actually it isn't as faster as this project,since it's a new project. Anyway, @PeratX you're doint a very nice work! Have a nice day ~

**Comment by PeratX** [comment]
@fycarman You are doing a nice work too !  : )
