### ISSUE TITLE
EnchantmentTable Issue

### ISSUE THREAD

**Issue by MudEGG** [iTXTech/Genisys#620]
#### Issue description
My players caused this while using EnchantmentTable.

* Genisys:157
* PHP:7
* OS:ubuntu

Warning: Invalid argument supplied for foreach() in phar:///***/PocketMine-MP.phar/src/pocketmine/item/enchantment/EnchantmentLevelTable.php on line 240

**Comment by ishitatsuyuki** [comment]
Couldn't reproduce. Try running via Docker to avoid environment issues.

**Comment by PeratX** [comment]
This was fixed
