### ISSUE TITLE
"Server has stopped" and can't go on automatically

### ISSUE THREAD

**Issue by MudEGG** [iTXTech/Genisys#622]
#### Issue description
Every time the server restarts,I can see it shows "Server has stopped"and not go on.
(I have enabled the Do_Loop="yes" in start.sh)

And I have tested the versions around #140,the same server,same bin,same launch file,
It can restart(Do_loop works),,But not in #157 or #162(I think the after version may have the same problem)

#### Steps to reproduce the issue
Just the server stop..

#### OS and versions
* Genisys:#157?150?162?or after?(#157 and #162 tested,not work)
* PHP:7
* OS:ubuntu 14.04 64

**Comment by flaxues** [comment]
https://github.com/iTXTech/Genisys/commit/3bcdb2a31c450512a2284af9b6918b5b82b5fc44

I'm having this error since this commit

**Comment by markkrueg** [comment]
Isn't this the same as issue #616 ?

**Comment by PeratX** [comment]
I think it is normal stop because of without segfault.
I will try to kill process.
