### ISSUE TITLE
Level buggy and chunks

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#623]
#### Issue description

Write a short description about the issue

#### Steps to reproduce the issue

Enter server and get problem

#### OS and versions

* Genisys: Latest version
* PHP: 7
* OS: Linux 14.04 LTS 64bit

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
I have one problem with my server.
I'm enter on my server and chunk's not loaded,i'm spawned in void. Pls fix this..

**Comment by NycuRO** [comment]
Sorry for incorrect issue... Problem it's : I'm go on my server and chunk's not loaded or i'm spawned in void. I have world .mca , not .mcr

**Comment by NycuRO** [comment]
Image it's buggy,not show server terrain and chunks.

**Comment by ishitatsuyuki** [comment]
Anvil is not supported.

**Comment by NycuRO** [comment]
Map chunk not loaded and with .mcr

**Comment by NycuRO** [comment]
My chunks not loaded,but other load. 1/2 players have problem,not all
