### ISSUE TITLE
Chunks/level have bug. *.mcr

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#624]
#### Issue description

I'm enter in my server and chunks not loaded or i'm spawned in void or idk..watch photo.
Map is .mca ,but i'm tested and .mcr and not work.
Problem not have all my players,have 15 players of 50 or higher. 
And i have problem. With (nukkit and imagicalmine)*function,but with genisys not work. ( sorry for promote other...) 

#### OS and versions

* Genisys: latest version 1.1dev
* PHP: 7
* OS: Ubuntuu Linux 14.04 LTS 64bit

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by PeratX** [comment]
Try another map. Maybe bandwidth, maybe spawn-threashold...

**Comment by NycuRO** [comment]
Can you give me one pocketmine.yml very optimizated for best play? :)

**Comment by PeratX** [comment]
spawn-threashold: 56

**Comment by NycuRO** [comment]
Thanks
