### ISSUE TITLE
Day and night cycle

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#625]
#### Issue description
Basically sometimes it just keeps switching between day and night in like 10-30 seconds 
#### OS and versions

* Genisys: 1.1dev-2b1dba3
* PHP: 7
* OS: W10

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by PeratX** [comment]
confimed this issue does not happen without plugins
