### ISSUE TITLE
Android PHP7 Genisys ,generation map it's broken

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#627]
#### Issue description

I have one Allview V1 Viper S and my Genisys Android generate map broken and buggy. Trees are generated in line to 7-8 blocks away and the generated random linux . Genisys Populators not work on Android , please fix this.

#### OS and versions

* Genisys: latest version 1.1dev
* PHP: 7
* OS: Android

**Comment by gaoyichuan** [comment]
Can you upload a screenshot or something?

**Comment by PeratX** [comment]
I am sorry. Our main work is not on Android. We do not recommend you to run Genisys on Android.

**Comment by NycuRO** [comment]
And why you create Genisys for Android? :-1:
