### ISSUE TITLE
Server bug restarting and show error in console.

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#630]
![screenshot_2016-03-19-15-22-40](https://cloud.githubusercontent.com/assets/13573011/13898797/98d4555e-ede6-11e5-841b-78f474d7d887.png)
#### Issue description

I stopped server and show error in console. And server not restarting . 

#### OS and versions

* Genisys: latest version 1.1dev
* PHP: 7
* OS: Linux , Ubuntuu 14.04 LTS 64bit

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by ishitatsuyuki** [comment]
You are not running latest.

**Comment by NycuRO** [comment]
Ah,sorry. New version..
