### ISSUE TITLE
Php start server bug. Files not found

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#631]
#### Issue description

I started server,server is starter,but one files not found.

#### OS and versions

* Genisys: YES,LATEST VERSION!
* PHP: 7
* OS: Linux , Ubuntuu 14.04 LTS 64bit
![screenshot_2016-03-19-15-42-09](https://cloud.githubusercontent.com/assets/13573011/13898911/6094494e-ede9-11e5-9ec7-8b255e8f85d7.png)

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by ishitatsuyuki** [comment]
Outdated version.

**Comment by ishitatsuyuki** [comment]
You will get git hash on latest version
