### ISSUE TITLE
Bug level/chunks ! 

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#632]
#### Issue description

I'm spawned in void or chunks not load !
SPAWN STRONGHOLD - 56 ! NOT WORK
LEVEL MAP : .MCR
Watch photo.
![screenshot_2016-03-19-15-45-55](https://cloud.githubusercontent.com/assets/13573011/13898929/0697e364-edea-11e5-9745-0453bebc72b2.png)

Not all have problem! 15 players of 50 have problem.
Ip : nycuro.ddns.net
Port 19132. Go and watch. *Not all have problem,but i have problem*
Not work with delete players file and change world.
Probably because level have php5 code. Watch all files.
Example : @parram Compoud ,not CompundTag *

#### OS and versions

* Genisys: LATEST VERSION,YES
* PHP: 7
* OS: Linux Ubuntuu 14.04 LTS 64bit , AMD 3.2Ghz and 2GB RAM

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by ishitatsuyuki** [comment]
OUTDATED VERSION, YES

**Comment by ishitatsuyuki** [comment]
Consider using Docker for environment, grab latest phar from Jenkins or GitLab CI

**Comment by ishitatsuyuki** [comment]
Attach logs. Spamming useless issues will result in a ban from this project.

**Comment by NycuRO** [comment]
It's latest,not outdated !

**Comment by PeratX** [comment]
@NycuRO Just stand and wait. Maybe your chunk have too many blocks and you phone need some to load. If I access a server with a lot of blocks in one chunk, I will stay in void for 3 seconds and then all good.

**Comment by NycuRO** [comment]
PeratX , i stay 5minutes and not work!
And is not hosted from phone ,it's one Linux Ubuntuu 14.04 LTS with 64bit. 2gb ram and amd radeon 3.2Ghz ;

**Comment by NycuRO** [comment]
And i found and other server with problem :
mcpe.mcx-portal.com 19132 and my server : nycuro.ddns.net 19132. Go and watch problem. :(

**Comment by eddir** [comment]
Yes, it is actually problem. I have this situation in my server.

**Comment by gaoyichuan** [comment]
If you get 15/150 players having the problem, I think it's of high possibility that it's because of your server's bandwidth.

**Comment by ishitatsuyuki** [comment]
REPEATING,WRITE YOUR EXACT VERSION

**Comment by NycuRO** [comment]
Latest fucker! :-1:

**Comment by zch12138** [comment]
May be it's the prison plugins problem.Some time if you die on prison this will happen.Try to delete this plugins and delede your player data.My server haven't meet this problem anymore when i delete that plugins.
