### ISSUE TITLE
Weather problems

### ISSUE THREAD

**Issue by vardoOTORI** [iTXTech/Genisys#637]
#### Issue description

When I replaced the plug-in, also occur, such as when you restart.
weather of genisys.yml is "false" Yet to rain and snow, lightning fall.

#### Steps to reproduce the issue

・Entry after restart.
・After the restart after introducing plug-ins.

#### OS and versions

* Genisys: latest
* PHP: php7
* OS:

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by vardoOTORI** [comment]
English sorry a miscellaneous.
And did what English is not good.

**Comment by Driesboy** [comment]
Same problem
