### ISSUE TITLE
No Drops

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#643]
just a quick question, how can I make it so players don't drop items when they die but they can't keep it.

**Comment by flaxues** [comment]
You can use the event: PlayerDropItemEvent

**Comment by flaxues** [comment]
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/event/player/PlayerDropItemEvent.php

**Comment by TheGalaxyLord** [comment]
Ya but how do I do it

**Comment by flaxues** [comment]
Try this 

https://github.com/flaxues/NoDrop

**Comment by flaxues** [comment]
@TheGalaxyLord

**Comment by TheGalaxyLord** [comment]
Thnx

**Comment by MasterWolf** [comment]
:)
