### ISSUE TITLE
Function addWindow() is crashed

### ISSUE THREAD

**Issue by rusinc** [iTXTech/Genisys#645]
#### Issue description

 When i used PM++ for PHP5 this function opened chest very good and without bugs and lags. but now, in Genisys, it dont work! I can't open chest, when between me and chest more, than 3 blocks, and can't put items in it. please fix it.

#### Steps to reproduce the issue

Use "Player class"->addWindow("Chest class"->getInventory());

#### OS and versions

* Genisys: 177
* PHP: 7
* OS: Android

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by PeratX** [comment]
Client changed in 0.14.0

**Comment by rusinc** [comment]
How to use it now?
