### ISSUE TITLE
Add Repeater

### ISSUE THREAD

**Issue by WOWR** [iTXTech/Genisys#646]
Cannons in Genisys are not efficient. For example when I make a sand cannon the sand doesn't fall into the TNT or doesn't shoot out afterwards. So please make regular cannons work and hybrid cannons work. Could you also put repeaters and comparators out because I'm in huge need it for it.
I also want redstone ascpets to work on the server like redstone clocks.

**Comment by Adam1609** [comment]
just because there are no redstone repeater?

**Comment by gaoyichuan** [comment]
That's some kind of PC feature..

**Comment by PeratX** [comment]
Repeater. Will be online in July after my senior high school entrance exam
