### ISSUE TITLE
Floating in the sky on death

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#647]
#### Issue description
When a player dies on any world other than the default one or the lobby they glitch in the sky and cant move.

#### OS and versions

* Genisys:
* PHP: 7
* OS: W10

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by Muqsit** [comment]
...until they relog. Yes, this happens in the official PM build too. But there should be a fix for this!

**Comment by TheGalaxyLord** [comment]
hmm... how?

**Comment by PeratX** [comment]
If I wait seconds it will be alright

**Comment by MasterWolf** [comment]
@PeratX you right

**Comment by TheGalaxyLord** [comment]
If I wait seconds it will just keep me stuck in mid air lol
