### ISSUE TITLE
Wtf?

### ISSUE THREAD

**Issue by FIRERO** [iTXTech/Genisys#649]
Genisys Crash Dump Mon Mar 21 05:11:55 CDT 2016

Error: Event is not Cancellable
File: /src/pocketmine/event/Event
Line: 56
Type: notice

Code:
[47] 	}
[48] 
[49] 	/**
[50] 	 * @return bool
[51] 	 *
[52] 	 * @throws \BadMethodCallException
[53] 	 */
[54] 	public function isCancelled(){
[55] 		if(!($this instanceof Cancellable)){
[56] 			throw new \BadMethodCallException("Event is not Cancellable");
[57] 		}
[58] 
[59] 		/** @var Event $this */
[60] 		return $this->isCancelled === true;
[61] 	}
[62] 
[63] 	/**
[64] 	 * @param bool $value
[65] 	 *
[66] 	 * @return bool

Backtrace:
#0 /src/pocketmine/entity/Creeper(35): pocketmine\entity\Creeper->setPowered(boolean )
#1 /src/pocketmine/entity/Entity(288): pocketmine\entity\Creeper->initEntity(boolean)
#2 /src/pocketmine/entity/Entity(454): pocketmine\entity\Entity->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:64.5.pocketmine\nbt\tag\DoubleTag:73.pocketmine\nbt\tag\DoubleTag:148.5.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\FloatTag:316.40603637695.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:20.pocketmine\nbt\tag\StringTag:Creeper.})
#3 /src/pocketmine/level/format/generic/BaseFullChunk(148): pocketmine\entity\Entity::createEntity(string Creeper, pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:64.5.pocketmine\nbt\tag\DoubleTag:73.pocketmine\nbt\tag\DoubleTag:148.5.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:0.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\FloatTag:316.40603637695.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:20.pocketmine\nbt\tag\StringTag:Creeper.})
#4 /src/pocketmine/level/Level(2745): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#5 /src/pocketmine/level/Level(687): pocketmine\level\Level->loadChunk(integer 4, integer 9)
#6 /src/pocketmine/Player(891): pocketmine\level\Level->registerChunkLoader(pocketmine\Player Player(247), integer 4, integer 9, boolean 1)
#7 /src/pocketmine/Player(2137): pocketmine\Player->sendNextChunk(boolean)
#8 /src/pocketmine/Server(2937): pocketmine\Player->checkNetwork(boolean)
#9 /src/pocketmine/Server(2627): pocketmine\Server->tick(boolean)
#10 /src/pocketmine/Server(2505): pocketmine\Server->tickProcessor(boolean)
#11 /src/pocketmine/Server(2038): pocketmine\Server->start(boolean)
#12 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /root/gfc_full/, string /root/gfc_full/, string /root/gfc_full/plugins/, string eng)

Genisys version: 1.1dev #0 [Protocol 45; API 2.0.0]
uname -a: Linux gfc-pe.ru 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
BanItem 2.1 by LDX for API(s) 1.0.0
StaffChat 0.1 by PEMapModder for API(s) 1.0.0
MoreCommands 1.0.2 by  for API(s) 1.4.0, 1.6.0, 1.7.0, 1.9.0, 1.10.0
GameForGuard _privat_by-VoBIs by VoBIs for API(s) 1.6.0
MineReset 2.1 by Falk for API(s) 1.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PurePerms 1.3.0-INDEV by 64FF00 for API(s) 1.12.0
PopupDisplayer 2.0.1 by Heromine, Flavius12 /*пепеводил GreeN */ for API(s) 1.12.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
FoodEffect 1.0.0 by MUedsa for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
ZipPluginLoader 1.1.0 by aliuly for API(s) 1.10.0
AntiTower 1 by xpyctum for API(s) 1.0.0
Broadcaster 1.15 by EvolSoft for API(s) 1.11.0
DamageIndicator 1 by CreeperFace for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
Fly 0.0.1 by Pub4Game for API(s) 1.12.0
Donate 1.0.0 by VoBIs for API(s) 1.8.0
BanClient 1.1 by luca28pet for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#045 by PEMapModder for API(s) 1.0.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
RulesRu 1.0.0 by xFlare for API(s) 1.8.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
Whois 2.0.3 by hoyinm & CyberCube-hk Team for API(s) 1.10.0
BouncyBlocks 1 by Darunia18 for API(s) 1.9.0
SWorldEditor Beta_1.5 by Sergey_Dertan for API(s) 1.8.0
TAGBlock 0.7-Alpha by ifteam for API(s) 1.13.0, 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
NoSteve 1 by CrystalRu for API(s) 1.12.0
Anti_Piar 1.2.3 by X3 for API(s) 1.0.0
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
Cost 1.0.0 by VoBIs for API(s) 1.8.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
MyPopupStatus 1.1_ALPHA by ScandiePlay for API(s) 1.12.0
GameForAntiSpam 1.1.1 by VoBIs for API(s) 1.6.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
ServerAuth 2.10 by EvolSoft for API(s) 1.11.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
PureChat 1.3.1 by 64FF00 for API(s) 1.11.0

**Comment by ishitatsuyuki** [comment]
Your server is outdated. Thanks for spamming. Goodbye!
