### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by shanwer** [iTXTech/Genisys#65]
①红石火把不能被另外一个红石火把熄灭
②拉杆不能对它附着的方块进行强充能
③矿车不能在铁轨上，它看起来更像是车，但有时坐在上面会很奇怪的抽搐
④农田方块不能被浸湿
⑤附魔台？( •̀∀•́ )
⑥钓鱼的问题
⑦就是指令附魔也没有作用
↓建议↓
1.汉化pocketmine.yml
2.地图生成器让它变得更好
【感谢每一位开发者的辛勤奉献】

**Comment by GalvinGao** [comment]
我把 README.md 汉化了个遍，加了个pull。在学校没法上qq，有事在115 echo留言吧，screen是talk

**Comment by GalvinGao** [comment]
红石在**todo**里
附魔台也在**todo**里
钓鱼也是
矿车也是……

你看**README.md**了吗。。。

**Comment by diamond-gold** [comment]
指令附魔需要退出再进才会生效, 是bug?

**Comment by astersx** [comment]
What crash?
