### ISSUE TITLE
fishing rod

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#650]
Can't catch fish with the fishing rod.

**Comment by Driesboy** [comment]
To-Do List

Improve Potions
Improve Redstone
Improve Anvil
Fishing
New AI for all creatures
LevelDB support for Windows

**Comment by Tolo0** [comment]
anvil works fine for me lol.

**Comment by PeratX** [comment]
Fishing rod is not completed

**Comment by Tolo0** [comment]
I know ClearSky have working fishing rod. Maybe you could ask them for the code.
