### ISSUE TITLE
Map failure

### ISSUE THREAD

**Issue by ScandiePlay** [iTXTech/Genisys#651]
I bought a VDS , and copied all the data from an old server to a new one. Now I have an issue with a map. Map was beautiful, but it's broken now because of this failure (look the screenshots), and because of another one (screenshots).

* Genisys: last from Jenkins
* PHP: 7.0
* OS: Ubuntu 14.04
![screenshot_2016-03-22-00-28-36](https://cloud.githubusercontent.com/assets/17462298/13936367/dd29dfa4-efc5-11e5-9d68-02050ef95aa7.png)
![screenshot_2016-03-22-00-28-47](https://cloud.githubusercontent.com/assets/17462298/13936370/e5cd5d16-efc5-11e5-86b2-f9965a32a93d.png)
![screenshot_2016-03-22-00-36-02](https://cloud.githubusercontent.com/assets/17462298/13936406/31913358-efc6-11e5-9d2e-e9bcd35fab02.png)
![screenshot_2016-03-22-00-36-07](https://cloud.githubusercontent.com/assets/17462298/13936409/370b435a-efc6-11e5-888a-024ff6cbe19e.png)

**Comment by ScandiePlay** [comment]
I'm using a Russian hosting playvds.com . I'm sure that it's not their fault.

**Comment by PeratX** [comment]
I think your map is broken.

**Comment by MasterWolf** [comment]
@ScandiePlay делай бекап карти.

**Comment by ScandiePlay** [comment]
@PeratX , it worked on my prev. server, I have only copied it to another one.

**Comment by MasterWolf** [comment]
@ScandiePlay map importing is broken in genisys. see it https://github.com/iTXTech/Genisys/issues/507

**Comment by ScandiePlay** [comment]
@MasterWolf , really NICE. Gave away money for a beautiful spawn (it was built specially for me). Thanks, @PeratX, thanks , Genisys developers!

**Comment by MasterWolf** [comment]
@ScandiePlay Oh.. My spawn was built specially for me too. And when i told the builder about problem he built me spawn like my old but better! Just want to withdraw one thing: Everything what is broken is going better. Your phone is broken - buy a new one better, you destroyed your model plane - make new better... So dont be sad - **you always can better** :D
I hope you understand me!
