### ISSUE TITLE
$event->setCancelled(true) It doesn't work

### ISSUE THREAD

**Issue by Yupai** [iTXTech/Genisys#652]
#### Issue description

I use this $event->setCancelled(true); 
But It doesn't cancel the event. This is my code:

This is my code:
```
public function onPlayerKick(PlayerKickEvent $event) {
    if($event->getReason() === "disconnectionScreen.serverFull"){
        $event->setCancelled(true);
    }
}
```

#### OS and versions

* Genisys: 1.1 (Minecraft PE 0.14.0)
* PHP: PHP7
* OS: Linux

**Comment by ishitatsuyuki** [comment]
Hey idiot. There is no event for rejecting connection.

**Comment by Yupai** [comment]
Sorry, I did not Know That Genisys doesn't have event for rejecting connection. Not to insult me.

**Comment by ishitatsuyuki** [comment]
At least it's not "kick" if server rejects the client.

**Comment by Yupai** [comment]
Can you help me?
I want to join to my Server when it is full, but I can't. How can I do it? With a permission.
if the player haven't permission to join to full server, the player is sent off (Kick). I don't know how do it.

**Comment by ishitatsuyuki** [comment]
The limit is hard limit. You can only control from the server console.

**Comment by Yupai** [comment]
OK thanks. Sorry for the inconvenience.
