### ISSUE TITLE
Item drop bug

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#657]
#### Issue description

Item drop bug..items gone
#### Steps to reproduce the issue

go to gm s with nothing in your inventory ( just for testing sake ) /give yourself a few stacks of any block or 2 or more tools ( more than 1 slot with same item ) throw one of the items on the ground then pick it up. You will only have the item you picked up in your inventory all the rest of the same item are gone.
#### OS and versions

* Genisys: 184
* PHP: 7
* OS: windows 10

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by astersx** [comment]
Confirmed LoL!!!!!
Wtf,  genisys is broken? -_-  
It really need to fix , this and my issue!!  
Well this issue is critical lol!!

**Comment by PeratX** [comment]
sendContents Error
