### ISSUE TITLE
Armor Equip

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#661]
#### Issue description
When armor is auto equipped on a player sometimes it doesn't show up  until they wear another piece of armor on it

#### Steps to reproduce the issue
For example, I have a kit plugin and when a players gets the kit, the armor doesn't show

#### OS and versions
* Genisys: 1.1dev-185
* PHP: 7
* OS: W10

#### Crashdump, backtrace or other files

```
Replace this placeholder with your crashdump...
```

**Comment by PeratX** [comment]
$player->getInventory()->sendArmorContents()

**Comment by TheGalaxyLord** [comment]
Ehh... where do I put that?
