### ISSUE TITLE
slapper does not work anymore

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#662]
#### Issue description

/slapper spawn Human hello

#### OS and versions

* Genisys: 1.1dev-185
* PHP: 7.01
* OS: Windows vista

#### Crashdump, backtrace or other files

```
an unknown error occurred while attempting  to perform this command
```

**Comment by ishitatsuyuki** [comment]
Your version is INVALID. Please append build no. or git hash.
Also please describe what command you executed.

**Comment by Driesboy** [comment]
fixed

**Comment by Muqsit** [comment]
IP: play.rumbencraft.me
PORT: 19132
Check it out!

**Comment by Muqsit** [comment]
https://github.com/PMPlugins/Slapper/tree/php7

**Comment by Driesboy** [comment]
i use it

**Comment by Driesboy** [comment]
dont work i run already 1 month genisys
and i have now this problem

**Comment by Driesboy** [comment]
fixed
