### ISSUE TITLE
Importing the map

### ISSUE THREAD

**Issue by ScandiePlay** [iTXTech/Genisys#663]
Just want to say that import of maps works perfectly, the problem was with permissions of the files. You should change the permissions of the folder with your map's files (including "level.dat" and all ".mcr"-files) to 0777. Change their permissions, and the map will work perfectly =D

**Comment by ScandiePlay** [comment]
I changed the permissions, now my map imported successfully =B

**Comment by gaoyichuan** [comment]
No need for 777, just chown them

**Comment by MasterWolf** [comment]
@ScandiePlay ok thx you helped me :)
