### ISSUE TITLE
Feature: Feed animals

### ISSUE THREAD

**Issue by jigamiller** [iTXTech/Genisys#665]
Genisys is great! To be fair I don't know if this should be in the core or in a plugin. I have tried using PureEntities plugin (which works for more active animals see: https://github.com/milk0417/PureEntities). My kids love the creative mode but one of their favorite parts is feeding the animals so I can't get them to use the server until I find someway to get this to work.

#### Issue description
Unable to "Feed" animals

#### Steps to reproduce the issue
Spawn a pig
Select a carrot and get next to the pig until "Feed" button shows
Click "Feed"

In normal game - hearts show up when you feed them.

#### OS and versions

* Genisys:
[14:05:44] [Server thread/INFO]: This server is running Genisys 1.1dev-188 「Ikaros」 implementing API version 2.0.0 for Minecraft: PE v0.14.0 alpha (protocol version 45)
* PHP: 7.0.2
* OS: Windows Server 2012 R2

**Comment by gaoyichuan** [comment]
Since we don't know how to show the hearts.. I will have a try today evening

**Comment by NycuRO** [comment]
PeratX,need help?

**Comment by PeratX** [comment]
Yes...

**Comment by PeratX** [comment]
This is related to MobAI Imporvedment. We will write it when we are writing new MobAI system.
