### ISSUE TITLE
Skin problem.

### ISSUE THREAD

**Issue by vardoOTORI** [iTXTech/Genisys#667]
#### Issue description

Player skin of people who were from the original to when the world participated resulting in assimilation .

#### Steps to reproduce the issue

1. participation later in the state there are players .
2. people of skin that has been entered is suffer with human skin that had from before .

(exception)
Heal When you load a level.

#### OS and versions

* Genisys: latest
* PHP: php7
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by gaoyichuan** [comment]
Could use more clearly English or other language? I can't quite understand you..

**Comment by MasterWolf** [comment]
ahahahaha

**Comment by SzczepanPolska** [comment]
POLAND :)
