### ISSUE TITLE
Cancel mob spawn but it kills them?..

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#669]
#### Issue description

cancelling entitygenerateevent seems to kill the entity..
#### Steps to reproduce the issue

run this code in a 1 world server and dont allow mobs to spawn there..in that world the remains of cows will be found ( exp and steak ) randomly lying around. 

 public function mobSpawn(EntityGenerateEvent $ev)
    {
        $level = $ev->getEntity()->getPosition()->level->getName();
        if($level !== 'insertworldname')
        {
            $ev->setCancelled(true);
        }
    }

#### OS and versions

* Genisys: 188
* PHP: 7
* OS: windows

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Pull requests are welcome.

**Comment by XxDXM-hippiexX** [comment]
I dont know where that event is called..so i cant really try to fix it i have looked

**Comment by PeratX** [comment]
Check NEW GeniAPI v1.7.2
