### ISSUE TITLE
item: eggs 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#670]
I'm using the latest genisys build and I just noticed that you can't get eggs. iv tried /item egg and it shows you getting the item but it doesn't get added to your inventory. easter is coming. I need eggs 😣

**Comment by Tee7even** [comment]
It's not about items, but rather about #371

**Comment by Tolo0** [comment]
yea ur right.  I did /give egg and I got eggs and the eggs from doing /item

**Comment by Tolo0** [comment]
closing
