### ISSUE TITLE
random client disconnect 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#675]
--> latest version 

issue --> players just randomly disconnect  for no reason. you could be just walking then disconnect. you could be typing then disconnect.

**Comment by PeratX** [comment]
Your network is not stable.

**Comment by Tolo0** [comment]
what do you mean by my network?  how can I fix this

**Comment by ishitatsuyuki** [comment]
Nothing more to describe. You're also not following the template.
