### ISSUE TITLE
Can't throw Snowballs!

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#678]
#### OS and versions

* Genisys: 196
* PHP: 7.0.3
* OS: Linux

#### Crashdump, backtrace or other files
No crash dump or error
Paste here
```

**Comment by ishitatsuyuki** [comment]
Cannot reproduce.

**Comment by erkam2002** [comment]
?

**Comment by ishitatsuyuki** [comment]
Possibly caused by plugin. You must provide informations about reproducibility.
