### ISSUE TITLE
PureChat

### ISSUE THREAD

**Issue by DWWf** [iTXTech/Genisys#68]
I put PureChat on the plugins folder but after I restarted the server the plugin wasn't added, it only happens with pure perms all the other plugins work fine.

**Comment by PocketKiller** [comment]
is it .phar?

**Comment by DWWf** [comment]
Yes

**Comment by PeratX** [comment]
Check the dependency

**Comment by PocketKiller** [comment]
show console

**Comment by DWWf** [comment]
Still not working :/

**Comment by GalvinGao** [comment]
Please show the _**CONSOLE OUTPUT**_ so we can see what's going on. @DWWf

**Comment by DWWf** [comment]
Nothing is going on though lol when I put the .phar it doesn't load up aka the configs folder doesn't show up neither does the plugin appears on /pl this happens with all the pure plugins, haven't experienced this with any other oh and also can you add support for slappers, it seems like mobs from creative inventory appear to be slappers :P I mean when i spawn one it says "entity #" on name tag and I didn't even make a slapper xD anyways I hope you understood all i've written because its pretty confusing xD

**Comment by DWWf** [comment]
and slappers crash the server after I make one using /slapper spawn NO I am not using an old version

**Comment by DWWf** [comment]
you guys don't give a fuck right -_-

**Comment by GalvinGao** [comment]
.

**Comment by DWWf** [comment]
?

**Comment by DWWf** [comment]
![capture](https://cloud.githubusercontent.com/assets/15623918/12539052/e05b5a58-c2b7-11e5-8882-362b8cfd1f78.PNG)
is this what you wanted?

**Comment by PeratX** [comment]
Well I think you should report this to the author of PureChat.

**Comment by DWWf** [comment]
I did, he said I shouldn't use genisys :P its not really his fault though you guys need to add support or something idk what you guys did.

**Comment by Pub4Game** [comment]
install PurePerms + PureChat, lol

**Comment by PocketKiller** [comment]
get PurePerms first.

**Comment by PocketKiller** [comment]
as @Pub4Game said

**Comment by DWWf** [comment]
I did ._.

**Comment by Pub4Game** [comment]
I have everything working

**Comment by SalmonGER** [comment]
Same here. Everything is working great.
