### ISSUE TITLE
Redstone Block No Power

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#681]
#### Issue description

Redstone Block doesn't output power even with Redstone enabled
#### OS and versions

* Genisys: Newest
* PHP:7
* OS:Windows/Linux

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Skyladd** [comment]
![screenshot_2016-03-25-11-35-07](https://cloud.githubusercontent.com/assets/16869214/14049945/1119fc3a-f27e-11e5-9116-2ace0e9b722b.png)

**Comment by PeratX** [comment]
Redstone Block hasn't written yet.

**Comment by Driesboy** [comment]
Can you not set redstone block===activited redstone torch

**Comment by ishitatsuyuki** [comment]
We don't need advices from beginners. Can't you shut up?

**Comment by PeratX** [comment]
Fixed.
