### ISSUE TITLE
Pls add addwindow method

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#683]

**Comment by ishitatsuyuki** [comment]
Provide a reason, at least description.

**Comment by erkam2002** [comment]
I have a BedWars plugin and it gives a error undifined method but on php5 work it on php7 not addwindow method is not added : Error: "Call to undifined method BedWars\BedWars::addwindow()" (EXCEPTION) in "BedWares\......................

**Comment by ishitatsuyuki** [comment]
Please request the author to update the plugin.

**Comment by erkam2002** [comment]
Not from plugin is from server

**Comment by ishitatsuyuki** [comment]
Provide full backtrace.

**Comment by gaoyichuan** [comment]
That's a call to the method of the plugin...
BedWars\BedWars::addwindow()

**Comment by erkam2002** [comment]
How can i fix it pls say it

**Comment by gaoyichuan** [comment]
Contact with the plugin's developer. That's none of our business
