### ISSUE TITLE
Add Sugar Cane in World Populator

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#684]
#### OS and versions

* Genisys:
* PHP: 7
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Hmm... PR is welcone.

**Comment by MineBuilderFR** [comment]
(PR = PLS?) X') 

Sorry : Please you can add Sugar Cane  :) ^^ (if PR = Please)

**Comment by ishitatsuyuki** [comment]
PR stands for pull request. Google for details.

**Comment by Muqsit** [comment]
Easy! I can do it!

**Comment by Muqsit** [comment]
So far, so good!
![12419329_1254419574586271_6768002035525571529_o](https://cloud.githubusercontent.com/assets/15074389/14061944/2953011c-f39f-11e5-9ed2-011df7fadee7.jpg)

**Comment by BlackShadow1** [comment]
That's amazing!

**Comment by erkam2002** [comment]
:D

**Comment by gaoyichuan** [comment]
Why so high?

**Comment by Muqsit** [comment]
It glitched lol and I don't think I can make it perfectly...as you can see, the sugarcane sometimes spawns when there's no water a block near!

**Comment by BlackShadow1** [comment]
Just check when the sugarcanes can stay 
` private function canSugarCaneStay($x, $y, $z)
	{
             $b = $this->level->getBlockIdAt($x, $y, $z);
		return ($b === Block::GRASS or $b === Block::SAND and $this->level->getBlockIdAt($x -1, $y, $z) or $this->level->getBlockIdAt($x, $y, $z -1) === Block::STILL_WATER)
	}
`
or similar, and for the highest just set the base amount in the biomes that can spawn sugarcane (needs to use the sugar cane classes)
`
    $sugarcane = new SugarCane();
    $sugarcane->setBaseAmount(2);
`
like in the Sandy Biomes class. I think this code work

**Comment by PeratX** [comment]
@Muqsit Push it to a new branch and we can work together

**Comment by Muqsit** [comment]
Ok @Perat :)
