### ISSUE TITLE
Title objects disappear

### ISSUE THREAD

**Issue by eddir** [iTXTech/Genisys#686]
#### Issue description

Sometimes disappearin chests and sign (title objects) in the server. Thit is a old bug and I dont known what was causes this.

![alt text](http://185.97.253.184/github/scr_1.png "Screenshot 1")
![alt text](http://185.97.253.184/github/scr_2.jpg "Screenshot 2")

#### Steps to reproduce the issue

I change sign or chest and after a time they vanish, but I can break the block, can not see and interact (method $level->getBlock returned 0).

#### OS and versions

* Genisys: 1.1dev 198 build
* PHP: 7
* OS: CentOS 7

#### Crashdump, backtrace or other files
```
Not found
```

**Comment by PeratX** [comment]
Caused by some plugins!
