### ISSUE TITLE
Cauldron Glitch

### ISSUE THREAD

**Issue by Jojo2289** [iTXTech/Genisys#689]
* Genisys: Jenkins Build #201
* PHP: 7
* OS: Windows/Linux

I'm here to report a problem with the new cauldrons on public servers. When you place one water in a cauldron it is floating above it. Then when you dye it the water rises higher. If you tap enough, it goes to the bottom of the cauldron. 

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by MasterWolf** [comment]
@Jojo2289 did you know that tou cant desccribe genisys version with word NEWEST? You must write build number.

**Comment by Jojo2289** [comment]
@MasterWolf Sorry about that I'm new to this.

**Comment by gaoyichuan** [comment]
confiemed it
