### ISSUE TITLE
PlayerMoveEvent::setTo() fails

### ISSUE THREAD

**Issue by AryToNeX** [iTXTech/Genisys#691]
#### Issue description
PlayerMoveEvent::setTo() fails. Tested in a survival games server.

#### Steps to reproduce the issue
1. Make a plugin with setTo() function in PlayerMoveEvent
2. Join the Genisys server
3. You can still move

#### OS and versions

* Genisys: 1.1dev-53fbe6c
* PHP: 7.0.3
* OS: CentOS 7 64bit

#### Crashdump, backtrace or other files
Nothing

**Comment by PeratX** [comment]
Paste code here. And I checked code is not wrong.

**Comment by PeratX** [comment]
Sorry. No details
