### ISSUE TITLE
Please Add Support from Enchantment please :(

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys#692]

**Comment by erkam2002** [comment]
Is already added use newest version

**Comment by RedstoneAlmeida** [comment]
in php5? not added EnchantingTable and Enchants works :(

**Comment by erkam2002** [comment]
PHP7

**Comment by gaoyichuan** [comment]
Check your genisys.yml for configures about enchantment

**Comment by Muqsit** [comment]
You mean you wanna use the enchantment table or are you talking about some enchants that are still not working?

**Comment by CLiu13** [comment]
I believe he means that some enchants don't work. E.x. fire aspect.

**Comment by PeratX** [comment]
Same as #698. Close
