### ISSUE TITLE
Chunk radius

### ISSUE THREAD

**Issue by Dergercol** [iTXTech/Genisys#694]
#### Issue description

Genisys I updated to the latest version.
Very small chunk radius !!!.
Pocketmine - 30
Nukkit - 100
Minet - 130
Please correct it! This is a very very ugly !!
I made your instructions and genisys.yml pocketmine.yml
Nothing works!!!
#### Steps to reproduce the issue

Fix chunkradius packet

#### OS and versions

* Genisys: latest
* PHP:php 7.* (forgot)
* OS:debian

#### Crashdump, backtrace or other files
```
![screenshot_2016-03-28-18-01-07](https://cloud.githubusercontent.com/assets/17719426/14078417/1a08930e-f50f-11e5-83e9-1afff3abf2dc.png)

Paste here
```

**Comment by ishitatsuyuki** [comment]
Version invalid. Check your network.

**Comment by Dergercol** [comment]
I think this is a major problem in genisys. Everything else - is nonsense

**Comment by ishitatsuyuki** [comment]
I think the biggest problem is a noob reporting issue - you even can't run /version?
