### ISSUE TITLE
Add all biomes pls :( and more tree in world ( populator 10 in all biomes )

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#695]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
Please tell us which biome is missing.

**Comment by NycuRO** [comment]
I show you all biomes list?

**Comment by NycuRO** [comment]
public static Biome[] Biomes =
		{
			new Biome {Id = 0, Name = "Ocean", Temperature = 0.5f, Downfall = 0.5f}, // default values of temp and rain
			new Biome {Id = 1, Name = "Plains", Temperature = 0.8f, Downfall = 0.4f},
			new Biome {Id = 2, Name = "Desert", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 3, Name = "Extreme Hills", Temperature = 0.2f, Downfall = 0.3f},
			new Biome {Id = 4, Name = "Forest", Temperature = 0.7f, Downfall = 0.8f},
			new Biome {Id = 5, Name = "Taiga", Temperature = 0.05f, Downfall = 0.8f},
			new Biome {Id = 6, Name = "Swampland", Temperature = 0.8f, Downfall = 0.9f},
			new Biome {Id = 7, Name = "River", Temperature = 0.5f, Downfall = 0.5f}, // default values of temp and rain
			new Biome {Id = 8, Name = "Nether", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 9, Name = "End", Temperature = 0.5f, Downfall = 0.5f}, // default values of temp and rain
			new Biome {Id = 10, Name = "Frozen Ocean", Temperature = 0.0f, Downfall = 0.5f},
			new Biome {Id = 11, Name = "Frozen River", Temperature = 0.0f, Downfall = 0.5f},
			new Biome {Id = 12, Name = "Ice Plains", Temperature = 0.0f, Downfall = 0.5f},
			new Biome {Id = 13, Name = "Ice Mountains", Temperature = 0.0f, Downfall = 0.5f},
			new Biome {Id = 14, Name = "Mushroom Island", Temperature = 0.9f, Downfall = 1.0f},
			new Biome {Id = 15, Name = "Mushroom Island Shore", Temperature = 0.9f, Downfall = 1.0f},
			new Biome {Id = 16, Name = "Beach", Temperature = 0.8f, Downfall = 0.4f},
			new Biome {Id = 17, Name = "Desert Hills", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 18, Name = "Forest Hills", Temperature = 0.7f, Downfall = 0.8f},
			new Biome {Id = 19, Name = "Taiga Hills", Temperature = 0.2f, Downfall = 0.7f},
			new Biome {Id = 20, Name = "Extreme Hills Edge", Temperature = 0.2f, Downfall = 0.3f},
			new Biome {Id = 21, Name = "Jungle", Temperature = 1.2f, Downfall = 0.9f},
			new Biome {Id = 22, Name = "Jungle Hills", Temperature = 1.2f, Downfall = 0.9f},
			new Biome {Id = 23, Name = "Jungle Edge", Temperature = 0.95f, Downfall = 0.8f},
			new Biome {Id = 24, Name = "Deep Ocean", Temperature = 0.5f, Downfall = 0.5f},
			new Biome {Id = 25, Name = "Stone Beach", Temperature = 0.2f, Downfall = 0.3f},
			new Biome {Id = 26, Name = "Cold Beach", Temperature = 0.05f, Downfall = 0.3f},
			new Biome {Id = 27, Name = "Birch Forest", Temperature = 0.6f, Downfall = 0.6f},
			new Biome {Id = 28, Name = "Birch Forest Hills", Temperature = 0.6f, Downfall = 0.6f},
			new Biome {Id = 29, Name = "Roofed Forest", Temperature = 0.7f, Downfall = 0.8f},
			new Biome {Id = 30, Name = "Cold Taiga", Temperature = -0.5f, Downfall = 0.4f},
			new Biome {Id = 31, Name = "Cold Taiga Hills", Temperature = -0.5f, Downfall = 0.4f},
			new Biome {Id = 32, Name = "Mega Taiga", Temperature = 0.3f, Downfall = 0.8f},
			new Biome {Id = 33, Name = "Mega Taiga Hills", Temperature = 0.3f, Downfall = 0.8f},
			new Biome {Id = 34, Name = "Extreme Hills+", Temperature = 0.2f, Downfall = 0.3f},
			new Biome {Id = 35, Name = "Savanna", Temperature = 1.2f, Downfall = 0.0f},
			new Biome {Id = 36, Name = "Savanna Plateau", Temperature = 1.0f, Downfall = 0.0f},
			new Biome {Id = 37, Name = "Mesa", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 38, Name = "Mesa Plateau F", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 39, Name = "Mesa Plateau", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 127, Name = "The Void", Temperature = 0.8f, Downfall = 0.4f},
			new Biome {Id = 128, Name = "Unknown Biome", Temperature = 0.8f, Downfall = 0.4f},
			new Biome {Id = 129, Name = "Sunflower Plains", Temperature = 0.8f, Downfall = 0.4f},
			new Biome {Id = 130, Name = "Desert M", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 131, Name = "Extreme Hills M", Temperature = 0.2f, Downfall = 0.3f},
			new Biome {Id = 132, Name = "Flower Forest", Temperature = 0.7f, Downfall = 0.8f},
			new Biome {Id = 133, Name = "Taiga M", Temperature = 0.05f, Downfall = 0.8f},
			new Biome {Id = 134, Name = "Swampland M", Temperature = 0.8f, Downfall = 0.9f},
			new Biome {Id = 140, Name = "Ice Plains Spikes", Temperature = 0.0f, Downfall = 0.5f},
			new Biome {Id = 149, Name = "Jungle M", Temperature = 1.2f, Downfall = 0.9f},
			new Biome {Id = 150, Name = "Unknown Biome", Temperature = 0.8f, Downfall = 0.4f},
			new Biome {Id = 151, Name = "JungleEdge M", Temperature = 0.95f, Downfall = 0.8f},
			new Biome {Id = 155, Name = "Birch Forest M", Temperature = 0.6f, Downfall = 0.6f},
			new Biome {Id = 156, Name = "Birch Forest Hills M", Temperature = 0.6f, Downfall = 0.6f},
			new Biome {Id = 157, Name = "Roofed Forest M", Temperature = 0.7f, Downfall = 0.8f},
			new Biome {Id = 158, Name = "Cold Taiga M", Temperature = -0.5f, Downfall = 0.4f},
			new Biome {Id = 160, Name = "Mega Spruce Taiga", Temperature = 0.25f, Downfall = 0.8f}, // special exception, temperature not 0.3
			new Biome {Id = 161, Name = "Mega Spruce Taiga Hills", Temperature = 0.3f, Downfall = 0.8f},
			new Biome {Id = 162, Name = "Extreme Hills+ M", Temperature = 0.2f, Downfall = 0.3f},
			new Biome {Id = 163, Name = "Savanna M", Temperature = 1.2f, Downfall = 0.0f},
			new Biome {Id = 164, Name = "Savanna Plateau M", Temperature = 1.0f, Downfall = 0.0f},
			new Biome {Id = 165, Name = "Mesa (Bryce)", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 166, Name = "Mesa Plateau F M", Temperature = 2.0f, Downfall = 0.0f},
			new Biome {Id = 167, Name = "Mesa Plateau M", Temperature = 2.0f, Downfall = 0.0f},

**Comment by NycuRO** [comment]
From MiNet. It's all biome of mcpe.

**Comment by NycuRO** [comment]
It's all list and temperature and downfall :+1:

**Comment by Muqsit** [comment]
End? Btw, I've made mushroom biomes but the thing is that the stem for mushroom trees is popular quartz for now! And the only tree that grows is the red one!

**Comment by Muqsit** [comment]
And Savannah is easy but Savannah trees generation is the hardest bit!

**Comment by NycuRO** [comment]
Not my code,it's MiNet.

**Comment by NycuRO** [comment]
Hmm,why not use :+1: 
						$this->chunk1->setBlockId($x, $y , $z, Block::ACACIA_WOOD); // 0
						$this->chunk1->setBlockId($x + 1, $y, $z + 1, Block::ACACIA_WOOD);

It's from SkyblockPE plugin....try doing this way for create Acacia Tree ;)

**Comment by gaoyichuan** [comment]
You think MCPE has all the biomes? Haha

**Comment by PeratX** [comment]
MCPE do not have these biomes yet!

**Comment by Rectex** [comment]
I want snow fall in my server. Witch biome support it?
