### ISSUE TITLE
<My server freeze random

### ISSUE THREAD

**Issue by Driesboy** [iTXTech/Genisys#697]
#### Issue description
if i start server and wait .. time the server freeze
no stop or crash

#### OS and versions

* Genisys: Genisys 1.1dev-208
* PHP: 7.0.1
* OS: Windows

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
Check your plugins! And try to turn off redstone to check if it is redstone's issue.

**Comment by Driesboy** [comment]
redstone is  disabled and i have 8 gb ram

**Comment by Driesboy** [comment]
i think it is combined slots
