### ISSUE TITLE
ImagicalMine?

### ISSUE THREAD

**Issue by legoboy0215** [iTXTech/Genisys#7]
Which one is better? In my opinion, probably ImagicalMine :P 
No offense, BTW. I heard people mention this project.

**Comment by aodzip** [comment]
Genisys have less bug
and it was a really good close source project in China with more features and less bug
But it is not as well- known as IM

**Comment by legoboy0215** [comment]
How is it closed source if its on Github XD

**Comment by aodzip** [comment]
I say 
It *was*
Now it is a opensource project

**Comment by aodzip** [comment]
I don't mean close

**Comment by legoboy0215** [comment]
Oh

**Comment by aodzip** [comment]
It was a sourceguridian protect peoject and sell around 600CNY(about 100$) on Internet and nearly every server hoster buy it in China

You can know it is really a good project from this

**Comment by yungtechboy1** [comment]
Yea Genisys is better
I switched from ImagineMine cause I get 100+ players easily and Genisys can handle the load better
ex:
ImagicalMine : 50players = 11TPS - 5TPS and 100% Laod
Genisys : 50Players on = 20TPS and 20% Load

**Comment by keithkfng** [comment]
@yungtechboy1 -_-

**Comment by PeratX** [comment]
@keithkfng How about making ImagicalMine and Genisys together. ImagicalGenisys?
It will be a really good project.

**Comment by keithkfng** [comment]
I'm not sure about the name... I mean, the names are pretty good as they are now. And ImagicalMIne has already become a technical term. So... yeah. I really like the idea of making it together, not so sure about the name. Maybe we should hold a vote on Twitter?

**Comment by keithkfng** [comment]
And @aodzip has already bought the domains for ImagicalMine. I really don't want to waste any more of @aodzip's money. He does everything for free...

**Comment by PeratX** [comment]
@keithkfng We should discuss more detailed.And I will also contact @aodzip

**Comment by PeratX** [comment]
If you can hold a vote,please do it NOW! @keithkfng

**Comment by keithkfng** [comment]
Done. You can check @ImagicalCorp's Twitter account for more information.

**Comment by PeratX** [comment]
@keithkfng I will. But do you know Twitter is blocked by China government...

**Comment by keithkfng** [comment]
Keep you updated - ImagicalMine has more votes than ImagicalGenisys XD

**Comment by keithkfng** [comment]
No... They're even now. Damn it LOL

**Comment by astersx** [comment]
Imagical mine have fall dead glich,  so :p,  i dont know if it fixed, but wen i created a issue it got closed becouse it was duplicate...  sooo 😝😝😝😝😝

**Comment by yungtechboy1** [comment]
IF they did merge then that would be the best of both worlds!

**Comment by da123rrell** [comment]
You should make the vote on imagicalmine's website or forum since twitter is banned on china. Btw is google still banned?

**Comment by CrayonDing** [comment]
Yes.Maybe we won't use it forever

**Comment by da123rrell** [comment]
They would be the best if nukkit fail. IF

**Comment by astersx** [comment]
Use vnp,  but China is a true Comunist,  even ban internet :|

**Comment by da123rrell** [comment]
Is google still banned there?

**Comment by PeratX** [comment]
Yes. We can't use Google, Facebook, Twitter and so on...

**Comment by legoboy0215** [comment]
I know that. Post it some where like the qq thing or whatever it is.
Also, how did you guys improve performance? Commits?

**Comment by PeratX** [comment]
Compare our code with official code and you will find it.

**Comment by keithkfng** [comment]
ImagicalMine is winning LOL

**Comment by aodzip** [comment]
Seems unfair
There is nearly no Chinese can see that vote.

Put the vote on GitHub is better

**Comment by dog194** [comment]
@keithkfng  unfair. We cannot use Twitter. If the vote was on Sina WeiBo, the situation must change. But it's unfair too.

**Comment by keithkfng** [comment]
LOL I don't have any of those accounts. You can put it on if you want. Although I'm taking a break off ImagicalMine for sometime... See you all in 2 days.

**Comment by legoboy0215** [comment]
I can try. Does Taiwan allow it?

**Comment by CrayonDing** [comment]
Yes.GFW cannot control Taiwan

**Comment by Muqsit** [comment]
Genisys - for its features and stability
ImagicalMine - because of the brand! XD

**Comment by PeratX** [comment]
@da123rrell Nukkit won't fail because I believe @MagicDroidX will make it better!

**Comment by astersx** [comment]
Genisys is the most stable version i ever used!!!  Keep the good work!!!!

**Comment by Muqsit** [comment]
Ya but I still prefer ImagicalMine...at least for the lobby. I use genisys because it supports potions.

**Comment by legoboy0215** [comment]
This? https://en.wikipedia.org/wiki/Great_Firewall
First time I ever knew that.

**Comment by da123rrell** [comment]
@peratx thats why i said IF

**Comment by PeratX** [comment]
@da123rrell : ) Keep your eyes on it.

**Comment by jasonczc** [comment]
It must be Genisys.
More features,more stable xD.

**Comment by linuzo** [comment]
Yep..  As owner of Kidzzone we are now using Genisys

**Comment by ZombiePower** [comment]
Well... The thing is, at @imagicalmine, we have multiple developers working on the project, which simply means, ImagicalMine is leading ahead. However, don't believe that I am trying to say that Genisys isn't any better. Well, after finished the bugs, our next aim to improve performance (which I can assure will happen). It's been a long time (1.5 months) since I did some coding (well.... I did a few snippets), and coding for ImagicalMine, is slowly allowing me to regain my potentials, so I can further assist the developers. 

Our key aim is to provide a lag-free, fully-optimised Minecraft PE experience on recognised and small servers. 

Good Luck to everyone :)

**Comment by keithkfng** [comment]
LOL everybody is helping each other here, you see.

**Comment by NiclasOlofsson** [comment]
"and it was a really good close source project in China with more features and less bug"

Do you realize that it's illegal to do that?

**Comment by ZombiePower** [comment]
@NiclasOlofsson agreed.

**Comment by legoboy0215** [comment]
Yep. When did the MiNet guy appear? XD

**Comment by da123rrell** [comment]
so now there are peoples from imagicalmine, nukkit, genisys, and minet here

**Comment by Snake1999** [comment]
Wow cool :3

**Comment by aodzip** [comment]
And ClearSky guys lol

**Comment by keithkfng** [comment]
XD

**Comment by thebigsmileXD** [comment]
Oh gerd.. Nukkit. The weird java stuff xd


aaand clearsky

**Comment by DesPlaysMC** [comment]
clearsky is dam fast but genisys has more features. if both advantages were merged together tho

**Comment by DarkWav** [comment]
the probably best thing would be ImagicalMine + PureEntities (A mob AI plugin wich is bette than genisy`s AIs) + Clearsky in one.
