### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#705]
#### Issue description

I have one router TP-Link 150mb/s and all server with Genisys not work to join. Chunks not loaded and i spawned in air. Yes,router problem. But,in imagicalmine and clearsky and Genisys Android hosted work to join. It's genisys problem,no? 
All server, ALL ALL SERVERS WITH GENISYS NOT WORK,but with Genisys Android work. Why not work to join server?
With data mobile work,but with wifi not work.. ( for data mobile i use block launcher )
#### OS and versions

* Genisys: 1.1dev - 209 and all version
* PHP: 7.0
* OS: All server....idk os is hosted servers..

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Driesboy** [comment]
i dont have this problem with 100mb/sec

**Comment by NycuRO** [comment]
I and others from Romania have this problem..

**Comment by Driesboy** [comment]
its not a genisys problem ok

**Comment by NycuRO** [comment]
It's a genisys. I'm not first person.

**Comment by Driesboy** [comment]
Work it for pocketmine?

Verstuurd vanaf mijn iPad

**Comment by Tolo0** [comment]
my friend had this problem with genisys to. with he's phone no chunks load. but on he's tablet. they do. on other servers that don't use genisys. he chunks load fine with he's phone.

**Comment by jerryzooyoyo** [comment]
![1459556900825](https://cloud.githubusercontent.com/assets/16357120/14223134/e8b3a95a-f8ac-11e5-80bc-da413cfcb834.jpg)
As you just see, All my server's players just wait for more than 100 seconds to join the server.
I don't know why this is happening. But hope you could fix it.
The old version of Genisys doesn't have this problem.
Please check it out=)

**Comment by gaoyichuan** [comment]
That's not Genisys' issue
