### ISSUE TITLE
Wrong Animated BrewingStand! 

### ISSUE THREAD

**Issue by GrownPHP** [iTXTech/Genisys#706]
#### Issue description
The Brewingstand is wrong Animated! 

#### Steps to reproduce the issue
Look into the creative Inventory. 

* Genisys: Genisys 1.1dev-175 「Ikaros」 implementing API version 2.0.0 for Minecraft: PE v0.14.0 alpha (protocol version 45)
* PHP: 7 
* OS: Windows

**Comment by ishitatsuyuki** [comment]
Invalid version "latest"

**Comment by Driesboy** [comment]
see on jenkins

**Comment by GrownPHP** [comment]
Updated Version/OS now..

**Comment by ishitatsuyuki** [comment]
Outdated.

**Comment by ishitatsuyuki** [comment]
More specifically, way outdated.
