### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#708]
#### OS and versions

* Genisys: #211
* PHP: 7.0.3
* OS: Linux

#### Crashdump, backtrace or other files
1.04 13:50:15 [Multicraft] Received stop command
01.04 13:50:14 [Multicraft] Server stopped
01.04 13:50:14 [Multicraft] Received stop command
01.04 13:50:14 [Multicraft] Server stopped
01.04 13:50:14 [Multicraft] Received stop command
01.04 13:50:13 [Multicraft] Server stopped
01.04 13:50:13 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:50:11 [Multicraft] Stopping server!
01.04 13:50:11 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:50:11 [Multicraft] Server shut down (starting)
01.04 13:50:11 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:50:11 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:50:11 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:50:11 [Multicraft] Updating eula.txt file
01.04 13:50:11 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:50:11 [Multicraft] Starting server!
01.04 13:50:11 [Multicraft] Loading server properties
01.04 13:50:06 [Multicraft] Server stopped
01.04 13:50:06 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:50:06 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:50:06 [Multicraft] Server shut down (starting)
01.04 13:50:06 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:50:06 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:50:06 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:50:05 [Multicraft] Updating eula.txt file
01.04 13:50:05 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:50:05 [Multicraft] Starting server!
01.04 13:50:05 [Multicraft] Loading server properties
01.04 13:50:05 [Multicraft] Received start command
01.04 13:49:40 [Multicraft] Server stopped
01.04 13:49:40 [Multicraft] Received stop command
01.04 13:49:40 [Multicraft] Server stopped
01.04 13:49:40 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:49:38 [Multicraft] Stopping server!
01.04 13:49:38 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:49:38 [Multicraft] Server shut down (starting)
01.04 13:49:38 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:49:38 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:49:38 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:49:38 [Multicraft] Updating eula.txt file
01.04 13:49:38 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:49:38 [Multicraft] Starting server!
01.04 13:49:38 [Multicraft] Loading server properties
01.04 13:49:38 [Multicraft] Received start command
01.04 13:48:13 [Multicraft] Server stopped
01.04 13:48:13 [Multicraft] Received stop command
01.04 13:48:12 [Multicraft] Server stopped
01.04 13:48:12 [Multicraft] Received stop command
01.04 13:48:12 [Multicraft] Server stopped
01.04 13:48:12 [Multicraft] Received stop command
01.04 13:48:12 [Multicraft] Server stopped
01.04 13:48:12 [Multicraft] Received stop command
01.04 13:48:11 [Multicraft] Server stopped
01.04 13:48:11 [Multicraft] Received stop command
01.04 13:48:11 [Multicraft] Server stopped
01.04 13:48:11 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:48:11 [Multicraft] Received stop command
01.04 13:48:11 [Multicraft] Stopping server!
01.04 13:48:11 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:48:11 [Multicraft] Server shut down (starting)
01.04 13:48:11 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:48:11 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:48:11 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:48:11 [Multicraft] Updating eula.txt file
01.04 13:48:11 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:48:11 [Multicraft] Starting server!
01.04 13:48:11 [Multicraft] Loading server properties
01.04 13:48:06 [Multicraft] Server stopped
01.04 13:48:06 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:48:06 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:48:06 [Multicraft] Server shut down (starting)
01.04 13:48:06 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:48:06 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:48:06 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:48:06 [Multicraft] Updating eula.txt file
01.04 13:48:06 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:48:06 [Multicraft] Starting server!
01.04 13:48:06 [Multicraft] Loading server properties
01.04 13:48:01 [Multicraft] Server stopped
01.04 13:48:01 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:47:59 [Multicraft] Stopping server!
01.04 13:47:59 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:47:59 [Multicraft] Server shut down (starting)
01.04 13:47:59 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:59 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:59 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:47:59 [Multicraft] Updating eula.txt file
01.04 13:47:59 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:47:59 [Multicraft] Starting server!
01.04 13:47:59 [Multicraft] Loading server properties
01.04 13:47:54 [Multicraft] Server stopped
01.04 13:47:54 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:47:52 [Multicraft] Stopping server!
01.04 13:47:52 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:47:52 [Multicraft] Server shut down (starting)
01.04 13:47:52 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:52 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:52 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:47:52 [Multicraft] Updating eula.txt file
01.04 13:47:52 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:47:52 [Multicraft] Starting server!
01.04 13:47:52 [Multicraft] Loading server properties
01.04 13:47:47 [Multicraft] Server stopped
01.04 13:47:47 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:47:45 [Multicraft] Stopping server!
01.04 13:47:45 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:47:45 [Multicraft] Server shut down (starting)
01.04 13:47:45 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:45 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:45 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:47:45 [Multicraft] Updating eula.txt file
01.04 13:47:45 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:47:45 [Multicraft] Starting server!
01.04 13:47:45 [Multicraft] Loading server properties
01.04 13:47:40 [Multicraft] Server stopped
01.04 13:47:40 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:47:38 [Multicraft] Stopping server!
01.04 13:47:38 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:47:38 [Multicraft] Server shut down (starting)
01.04 13:47:38 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:38 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:38 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:47:37 [Multicraft] Updating eula.txt file
01.04 13:47:37 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:47:37 [Multicraft] Starting server!
01.04 13:47:37 [Multicraft] Loading server properties
01.04 13:47:32 [Multicraft] Server stopped
01.04 13:47:32 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:47:30 [Multicraft] Stopping server!
01.04 13:47:30 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:47:30 [Multicraft] Server shut down (starting)
01.04 13:47:30 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:30 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:30 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:47:30 [Multicraft] Updating eula.txt file
01.04 13:47:30 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:47:30 [Multicraft] Starting server!
01.04 13:47:30 [Multicraft] Loading server properties
01.04 13:47:25 [Multicraft] Server stopped
01.04 13:47:25 [Multicraft] Looks like a crash, check the server console. Return value: 255
01.04 13:47:25 [Multicraft] Restarting crashed server in 5 seconds
01.04 13:47:25 [Multicraft] Server shut down (starting)
01.04 13:47:25 [Server] INFO Fatal error: require_once(): Failed opening required 'phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:25 [Server] INFO Warning: require_once(phar:///imagicalmine_0_14_0_PHP7.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/imagicalmine_0_14_0_PHP7.phar" has a broken signature in /imagicalmine_0_14_0_PHP7.phar on line 1
01.04 13:47:25 [Server] INFO Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
01.04 13:47:25 [Multicraft] Updating eula.txt file
01.04 13:47:25 [Multicraft] Loaded config for "Other: ImagicalMine 0.14 PHP7"
01.04 13:47:25 [Multicraft] Starting server!

**Comment by ishitatsuyuki** [comment]
Hello idiot, your phar is broken. Goodbye.

**Comment by erkam2002** [comment]
Ik i have it closed iam not Idiot -.-
