### ISSUE TITLE
Enchanting

### ISSUE THREAD

**Issue by Shadow166050** [iTXTech/Genisys#709]
#### Issue description
How Do You Make So Players Can Use Enchanting Without Op on server

#### OS and versions

* Genisys: build 211
* PHP: 7
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by gaoyichuan** [comment]
Change the permission for /enchant command.

**Comment by Shadow166050** [comment]
But If I change it won't they be able to do /enchant on any item they want?

**Comment by Muqsit** [comment]
Just give the player permission 'pocketmine.command.enchant'

This should be posted in the pocketmine forums since this is basically not an issue!

**Comment by Shadow166050** [comment]
I tried pocketmine.command.enchant and it didn't work. Also I asked
pocketmine and they said they can't help me because your a third party and
lastly I don't know where to post this.

Just give the player permission 'pocketmine.command.enchant'

This should be posted in the pocketmine forums since this is basically not
an issue!

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/iTXTech/Genisys/issues/709#issuecomment-204666333>
