### ISSUE TITLE
addCreativeItem for one person.

### ISSUE THREAD

**Issue by xpyctum** [iTXTech/Genisys#711]
#### Issue description
Do you have some ideas how to use addCreativeItem for one person? Why not do api for this? I think it's really interesting idea for creative servers.

**Comment by PeratX** [comment]
Will try

**Comment by xpyctum** [comment]
wow! Cool

**Comment by xpyctum** [comment]
#725

**Comment by xpyctum** [comment]
Hm, and this not works...
![](http://puu.sh/o4qOm/7323c40e53.png)
![](http://pp.vk.me/c630120/v630120517/23b10/YGrSKSpbiPk.jpg)

**Comment by xpyctum** [comment]
Fixed by using: Item::clearCreativeItems();
I think it's not important to use array_merge.

**Comment by xpyctum** [comment]
Watch video: http://puu.sh/o4rKD/47d282732f.mp4
