### ISSUE TITLE
chest bug

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#712]
**Issue** **description**
when storing a stack of a item all at once to a chest. it glitches back into your inventory.

**Comment by ishitatsuyuki** [comment]
Invalid version.

**Comment by Tolo0** [comment]
Genisys_1.1dev-211.phar

**Comment by Skyladd** [comment]
Confirmed

**Comment by gaoyichuan** [comment]
Can't reproduce using the latest source code. Try the latest build on Jenkins
