### ISSUE TITLE
Php bug

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#714]
#### Issue description

I have CENTOS 7 64BIT AND I HAVE A PROBLEM IN PHP.
AND IN UBUNTUU AND IN CENTOS 7 , PROBLEM : opcache not found ! Answer : " Use docker ". HOW USE DOCKER ? HOW HOW HOW? ONE VIDEO FOR USE DOCKER?! I DON'T KNOW HOW USE DOCKER! 
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Tolo0** [comment]
Maybe try switching to CentOS 6

**Comment by ishitatsuyuki** [comment]
YOU IDIOT? YOU CAN'T EVEN COPY COMMAND?

**Comment by ishitatsuyuki** [comment]
https://github.com/iTXTech/Genisys/wiki/Use-Docker-to-run-Genisys

**Comment by NycuRO** [comment]
Oh ,thanks......sorry ,i'm idiot. I'm use section php-docker-genisys :))))
