### ISSUE TITLE
Genisys.yml

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#715]
**Issue** **description**
the latest build doesn't generate the genisys.yml properly. 
it's blank. Nothing on it at all.

**Comment by ishitatsuyuki** [comment]
Invalid version.

**Comment by Tolo0** [comment]
I sed the latest build. meaning the latest version.

**Comment by ishitatsuyuki** [comment]
If you are not writing the exact version, you are possibly outdated. Write it. Or closing as invalid.

**Comment by Tolo0** [comment]
Genisys_1.1dev-211.phar

**Comment by CrayonDing** [comment]
If earlier version can generate the genisys.yml?

**Comment by PeratX** [comment]
Checked nothing is wrong. Check permission
