### ISSUE TITLE
Player damage glitch.

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#716]
#### Issue description
sometimes players don't recive damage from swords. and ther forced to relog to fix the glitch. not sure if it's just swords. could be more items like axe. sticks. bow.

#### Steps to reproduce the issue
I don't know.  it just randomly happens. 

#### OS and versions
* Genisys: Genisys_1.1dev-211.phar
* PHP: 7.0
* OS:

**Comment by PeratX** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/4110

**Comment by PeratX** [comment]
@Tolo0 maybe to far. Or maybe delay. Check pvp settings and difficulty

**Comment by Tolo0** [comment]
what difficulty lvl should I have?

**Comment by PeratX** [comment]
>=1

**Comment by Tolo0** [comment]
I have it set on 1. always have.

**Comment by Muqsit** [comment]
Are you still facing this problem? I'm not having this bug!
