### ISSUE TITLE
PvP Problem

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#72]
Player can "Double Click " on damage player  and the player takes a big knockback and more damage

**Comment by astersx** [comment]
cool,  i wanna check it

**Comment by astersx** [comment]
How to double click :(

**Comment by diamond-gold** [comment]
I think he meant being able to attack a few times in a second

**Comment by PocketKiller** [comment]
maybe he means when  you hit a player 2 times he gets a long knockback and more damage

**Comment by PeratX** [comment]
@PocketKiller would you like to join Genisys Development?

**Comment by PocketKiller** [comment]
@PeratX Okay, Thank you.

**Comment by PeratX** [comment]
@PocketKiller Check your e-mail : )
