### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#721]
Notice: Undefined offset: 0 in /home/src/pocketmine/Player.php on line 3398
[06:52:44] [RakLibServer thread/NOTICE]: Blocked 31.28.203.82 for 5 seconds

**Comment by ishitatsuyuki** [comment]
Hey, invalid version. Follow the template.

**Comment by PeratX** [comment]
Known W10 crafting issue. Same as W10 crafting. Close.
