### ISSUE TITLE
PHP DOCKER 

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Genisys#722]
#### Issue description

Please create one video how use docker. I executed commands and not have server,not install php and directory it's empty..
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
The commands are confirmed to work.

**Comment by NycuRO** [comment]
CREATE ONE VIDEO,FUCKER. NOT ALL IT'S " GENIOUS " !

**Comment by gaoyichuan** [comment]
STOP SPAMMING OR YOU WILL GET A BAN. IF YOU DON'T KNOW HOW TO USE DOCKER, GOOGLE IT, DON'T ASK US
