### ISSUE TITLE
Consistant crashing every 2-3 minutes. Please help!

### ISSUE THREAD

**Issue by FienixEC** [iTXTech/Genisys#726]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```
Genisys Crash Dump Wed Mar 30 14:30:42 CDT 2016

Error: Event is not Cancellable
File: /src/pocketmine/event/Event
Line: 56
Type: notice

Code:
[47]  }
[48] 
[49]  /**
[50]   * @return bool
[51]   *
[52]   * @throws \BadMethodCallException
[53]   */
[54]  public function isCancelled(){
[55]   if(!($this instanceof Cancellable)){
[56]    throw new \BadMethodCallException("Event is not Cancellable");
[57]   }
[58] 
[59]   /* @var Event $this /
[60]   return $this->isCancelled === true;
[61]  }
[62] 
[63]  /**
[64]   * @param bool $value
[65]   *
[66]   * @return bool

Backtrace:
#0 /src/pocketmine/entity/Creeper(35): pocketmine\entity\Creeper->setPowered(boolean )
#1 /src/pocketmine/entity/Entity(289): pocketmine\entity\Creeper->initEntity(boolean)
#2 /src/pocketmine/entity/Entity(455): pocketmine\entity\Entity->__construct(pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\FloatTag:0.08500000089407.pocketmine\nbt\tag\FloatTag:0.08500000089407.pocketmine\nbt\tag\FloatTag:0.08500000089407.pocketmine\nbt\tag\FloatTag:0.08500000089407.pocketmine\nbt\tag\FloatTag:0.08500000089407.}.pocketmine\nbt\tag\LongTag:-7424125556370633687.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:generic.maxHealth.pocketmine\nbt\tag\DoubleTag:20.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:generic.knockbackResistance.pocketmine\nbt\tag\DoubleTag:0.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:generic.movementSpeed.pocketmine\nbt\tag\DoubleTag:0.25.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:generic.followRange.pocketmine\nbt\tag\DoubleTag:16.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:Random spawn bonus.pocketmine\nbt\tag\LongTag:-7863135815497162301.pocketmine\nbt\tag\IntTag:1.pocketmine\nbt\tag\DoubleTag:0.041722233049623.pocketmine\nbt\tag\LongTag:4988071004127709377.}.}.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:generic.attackDamage.pocketmine\nbt\tag\DoubleTag:2.}.}.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:0.018420388256442.pocketmine\nbt\tag\DoubleTag:-0.078400001525879.pocketmine\nbt\tag\DoubleTag:0.043394201275808.}.pocketmine\nbt\tag\ShortTag:20.pocketmine\nbt\tag\IntTag:2.pocketmine\nbt\tag\StringTag:Creeper.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag

**Comment by FienixEC** [comment]
Also I keep getting this critical error issue in my console now

[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\entity\EntityTeleportEvent' to 'WorldProtect v2.2.0': Function name must be a string on aliuly\worldprotect\GmMgr2016-04-02 [15:11:07] [Server thread/CRITICAL]: Error: "Function name must be a string" (EXCEPTION) in "/src/pocketmine/inventory/PlayerInventory" at line 170

I'm using the latest build.

**Comment by ishitatsuyuki** [comment]
Paste your /version. Follow the template. Your plugin is buggy

**Comment by PeratX** [comment]
Your version is too old!

**Comment by FienixEC** [comment]
my version of what peratX?

**Comment by FienixEC** [comment]
please help?...guide me?

**Comment by ishitatsuyuki** [comment]
Way outdated.

**Comment by PeratX** [comment]
@FienixEC Use the latest version provided on Jenkins or GitLab-CI

**Comment by FienixEC** [comment]
Thanks so much!
