### ISSUE TITLE
Allow flight

### ISSUE THREAD

**Issue by astersx** [iTXTech/Genisys#73]
Allow flight is on,  so players can use fly mods,  in server config is off,  so please fix this!!! :(

**Comment by PeratX** [comment]
I will release my PNoCheat plugin later.

**Comment by astersx** [comment]
Yay,  ok!!  But why allow-flight function dont work on genysis? If you only remove auto-kick and enamble only pull back on ground function will be great!!!

I will wait for no cheat plugin :+1:

**Comment by Jelly9912** [comment]
@PeratX where you will share this?

**Comment by PeratX** [comment]
@Jelly9912 on Github

**Comment by astersx** [comment]
@PeratX  Pocketmine  auto disamble flying!! ! Why  Genisys cant? If you only disamble kicking for flying is cool i only wanna to pull back flying players!!!
