### ISSUE TITLE
Skin bug

### ISSUE THREAD

**Issue by TheGalaxyLord** [iTXTech/Genisys#730]
When you join the server sometimes it shows the player skin as yours until you go to another world and come back

**Comment by ishitatsuyuki** [comment]
Follow the template.

**Comment by NML32** [comment]
Confirmed, it's been happening for quite a while on my servers.

Reproduce: Join game
Crash Report: N/A

Genisys Build #215 
PHP 7
OS Linux

**Comment by PeratX** [comment]
This is an old issue. Will follow official repo
