### ISSUE TITLE
Jenkins offline?

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#732]
i go on this website : http://jenkins.mcper.cn/job/Genisys-master/  
and become this error!?!? 404 Not Found nginx

**Comment by ishitatsuyuki** [comment]
Under maintenance. Please use GitLab CI.

**Comment by ExerciseBook** [comment]
They moved the server to a new server just now

**Comment by erkam2002** [comment]
ok

**Comment by gaoyichuan** [comment]
Nono, not a server transfer.. Just maintaince
