### ISSUE TITLE
getTile()

### ISSUE THREAD

**Issue by GrownPHP** [iTXTech/Genisys#733]
#### Issue description
If I do my plugin into Server it says "Error: Call to member function getTile() on null" Everything is right in my Code,because when I change to another Serverversion like ImagicalMine,the error isn't there anymore

#### OS and versions

* Genisys: 1.1 dev-175
* PHP: 7
* OS: Windows

**Comment by gaoyichuan** [comment]
Upload the backtrace, and also try the latest build

**Comment by GrownPHP** [comment]
So thats a part of my code...
`$leavetile = $this->arena->plugin->getServer()->getLevelByName($this->arena->data['ReturnSignWorld'])->getTile(new Vector3($this->arena->data['ReturnSignX'], $this->arena->data['ReturnSignY'], $this->arena->data['ReturnSignZ']));`
And I used the newest Version..The same Error..

**Comment by GrownPHP** [comment]
And that is the full ERROR:
`2016-04-03 [07:46:14] [Server thread/CRITICAL]: Could not execute task McKaff_BowBash\Arena\ArenaSchedule: Call to a member function getTile() on null
2016-04-03 [07:46:14] [Server thread/CRITICAL]: Error: "Call to a member function getTile() on null" (EXCEPTION) in "/McKaff_BowBash/src/McKaff_BowBash/Arena/ArenaSchedule" at line 110
`

**Comment by gaoyichuan** [comment]
Completely plugin issue
