### ISSUE TITLE
Bug of Redston

### ISSUE THREAD

**Issue by zhouruixi** [iTXTech/Genisys#736]
#### Issue description
Both TNT and Redston Light have this problem and I haven't try more things

when I lighting redston first and put TNT on,it won't explode, but it will  explode if I put on TNT first and then lighting redston with a Redstone torches。

MC  WIN10 edition 0.14.0

* Genisys:0f7c71059664f2b9767a30b56fe6a64e3079dd0d
* PHP:7.0.2
* OS:debian 8 with https://github.com/iTXTech/PHP-Genisys/commit/aeaa7fcf102564f73cc5b37e43dd6627355a4825

**Comment by gaoyichuan** [comment]
I didn't get this in the latest source. Are you using Redstone BLOCK which is unimplemented?

**Comment by zhouruixi** [comment]
![redston](https://cloud.githubusercontent.com/assets/10471035/14239497/190219f2-fa6f-11e5-8bff-56fcfc3b7175.png)
Just like this

**Comment by gaoyichuan** [comment]
Oh, confirm it with the method shown in the photo

**Comment by zhouruixi** [comment]
It's not work wtth 红石灯，另外原先放置的TNT不会爆炸，而是凭空多出来一个点燃的TNT
为了描述清楚，还是用中文吧
Genisys： 258ac0a
