### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ibookcc** [iTXTech/Genisys#737]
1. 地狱可以放置水（可修复）
2. 铁桶装水铁桶图标不会变成水桶但是可以放水同理岩浆也是（不存在此错误）
3. 水流动问题, 放置水,如果水大范围的流动把源头的水填上水流不会消失, 岩浆尤其明显
4. 容器（箱子）问题, 在连续放入一个以上物品时物品会跳回背包,（可修复）
5. 地图生成有断面, 经过观察多为群系的交界线（不可修复）
6. 地狱门手持水桶点击地狱门紫色与门框相交的面,紫色方块会消失被替换成水, 岩浆同理（可修复）
7. 容器问题, 熔炉无法使用原木制作木炭
8. 经验球无法滚动, 甚至不掉落经验球, 汉化不彻底许多文字还是英文的(虽然我看得懂但是强迫症)（自己问题）

**Comment by ibookcc** [comment]
9. 腐肉不能吃

**Comment by ExerciseBook** [comment]
腐肉有害身体健康 #(滑稽)

**Comment by CrayonDing** [comment]
至于汉化问题。为什么不自己去提交个pr呢
