### ISSUE TITLE
Please Update Genisys to support Win10 MCPE v0.14.1

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#739]
#### Issue description
Windows 10 MCPE updated to v0.14.1 and can't join Genisys servers

#### Steps to reproduce the issue
Join Genisys server

#### OS and versions
* Genisys: v#228
* PHP: 7
* OS: Linux

#### Crashdump, backtrace or other files
N/A
Paste here
```

**Comment by gaoyichuan** [comment]
But we didn't get 0.14.1 on Android or iOS platforms.

**Comment by flaxues** [comment]
You could add support since LBSG already supports it...

**Comment by Driesboy** [comment]
you can use accepted protocols like IM

**Comment by NML32** [comment]
I thought there were other flavors of PM that allowed 0.14 and 0.14.1 at the same time.

**Comment by Tee7even** [comment]
>But we didn't get 0.14.1 on Android or iOS platforms.
>gaoyichuan closed this 6 hours ago

Nice. That's the way to do it.

**Comment by PeratX** [comment]
Will support. Please wait.
