### ISSUE TITLE
Please add a function to disable item-drop from item frame

### ISSUE THREAD

**Issue by Leo3418** [iTXTech/Genisys#741]
#### Issue description
Players can steal items in item frames, which was unexpected by OPs.
I'd appreciate it if you can add a boolean to toggle whether items in item frames can be taken by players.
Thank you very much.

#### Steps to reproduce the issue
Build an item frame, put anything on it, and long press on the frame.

#### OS and versions

* Genisys: 1.1dev #227 and later versions
* PHP: 7.0.3 Linux x86_64
* OS: CentOS 7.1 x64

#### Crashdump, backtrace or other files
```
(none)
```

**Comment by ishitatsuyuki** [comment]
Write plugins.
