### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by Varfalomey** [iTXTech/Genisys#742]
#### Issue description
1. When you shoot from the bow - is a departure minecraft timeout ( in the console is written ) .
2. When you dress a skeleton head - if the server is frozen ( this is solved reinstalling the map )

#### OS and versions
* Genisys: New
* PHP: 7
* OS: Ubuntu 14.04

**Comment by Varfalomey** [comment]
Check 1 bug on Simplexland.ru:19132 to spawn

**Comment by ishitatsuyuki** [comment]
Is is so hard to follow the template and write version properly?

**Comment by ishitatsuyuki** [comment]
Is it so hard to write a readable language?

**Comment by Varfalomey** [comment]
Если стрелять стрелой которая горит то у тебя может вылетить майнкрафт.
Если оденишь голову скелета - то сервер заморозиться.

**Comment by ishitatsuyuki** [comment]
And your version?

**Comment by Varfalomey** [comment]
самая новая, я её только что скачал.

**Comment by ishitatsuyuki** [comment]
Write or this issue will be ignored.

**Comment by PeratX** [comment]
@ishitatsuyuki Please be PATIENT!!!
