### ISSUE TITLE
Let's deal with Genisys's next codename!

### ISSUE THREAD

**Issue by PeratX** [iTXTech/Genisys#743]
As we know, a new version of MCPE is coming soon and Genisys is going to upgrade to 1.2. So we need a new codename. Write your opinion here!

**Comment by Jelly9912** [comment]
Spark, Prometheus, Crossfire

**Comment by MineBuilderFR** [comment]
Cookie

**Comment by SavionLegendZzz** [comment]
Prime

**Comment by tankisu01** [comment]
Second Null

**Comment by AryToNeX** [comment]
Augustus

**Comment by alex2534alex** [comment]
Ascension

**Comment by Skyladd** [comment]
Xeno

**Comment by TheClimbing** [comment]
Terminator

**Comment by Dergercol** [comment]
Why!? It is cool name. Will be better if u are will be create Cenisys

**Comment by KDOA808** [comment]
secondary

**Comment by Driesboy** [comment]
Prime Time

**Comment by Muqsit** [comment]
Polyphage? Cryptarch? idk lol

**Comment by tankisu01** [comment]
Cookie

**Comment by frankblob** [comment]
Viral

**Comment by GlitchPlayer** [comment]
Glitch

**Comment by PeratX** [comment]
Not a single word. Please write some more deep meanings.

**Comment by frankblob** [comment]
"Viral Main", then. 

Since it's time for Genisys to achieve a viral effect and become acknowledged as the main alternative to PM - to both mainstream PE users and mainstream PE server admins. Not just perceived as "for elite hackers", but for the general PE public.

A viral effect into the mainstream PE world. Hence 'main' and 'viral'.

**Comment by GlitchPlayer** [comment]
Sweet Cocoa

beacuse the new update will come with sweet features for mpce

**Comment by AryToNeX** [comment]
Continuing the greek mythology ("Ikaros"), I propose "Light of Zeus" because this core goes really fast even in small processors, so why not? And everybody can assign a meaning to this codename. @PeratX

**Comment by PeratX** [comment]
Yes. I take "Ikaros" from greek mythology and also influenced by comic "Heaven's Lost Property"

**Comment by jellyfishcoder** [comment]
What about: # **Expansive Horizons**
Because Genisys is really starting to grow a lot. But it can still be used interchangeably with the pocketmine phar, which makes it really easy to switch to it from pocketmine. Also, its under active development and open to suggestions, _cough cough not pocketmine cough cough._ So, I know the name is kinda generic, but I just think it sounds fitting.

**Comment by FaanMaario** [comment]
Prisme, Crisis Moon, Sunfish

**Comment by DavidJBrockway** [comment]
DiamondDriller

**Comment by Shamil0402** [comment]
Skynet!

**Comment by Bidou0418** [comment]
Steve :)

**Comment by larryTheCoder** [comment]
蘋果(Apple)派(Pie)

**Comment by AryToNeX** [comment]
@larryTheCoder let's clone nukkit eheh -.-

**Comment by larryTheCoder** [comment]
Hehe

**Comment by larryTheCoder** [comment]
How about this 火箭(Rocket)曲奇饼(Cookie)

**Comment by EvilPupil** [comment]
Continue Cenisys

**Comment by daniktheboss** [comment]
Nethermine, bucketmine, netherland, endworld, alphamine, alphagen, poppit. Poppy,

**Comment by ABAxStorm** [comment]
Volt

**Comment by dktapps** [comment]
It's about time we made a decision; 1.2 is here

**Comment by TheDiamondYT1** [comment]
NullPointerException

**About my choice**
Java.lang.NullPointerException

**Comment by JUSTaMod** [comment]
SHAHRIVAR   شهریور Persian
Meaning- Modern Persian form of Avestan Kshathra Vairya meaning "desirable power". In Zoroastrianism this was the name of a god of metal and a protector of the weak.

I think the "desirable power" meaning, describes everything Genisys stands for. Powerful server software, very desirable.

**Comment by daniktheboss** [comment]
Close issue?

**Comment by JUSTaMod** [comment]
@daniktheboss they need to confirm a name before closing. its still an "issue"

**Comment by Dog2puppy** [comment]
Friendly Apples

**Comment by GlitchPlayer** [comment]
Blue Stone

**Comment by JUSTaMod** [comment]
@PeratX are you going to choose a codename for 1.2? its been out awhile.... maybe wait until next major update...? idk what you peeps are doing. lol.

**Comment by gaoyichuan** [comment]
Removed some useless comments, just vote using github's feature

**Comment by PeratX** [comment]
Yes, let's vote!

**Comment by Driesboy** [comment]
no make a site

**Comment by PeratX** [comment]
I think twitter is a good choice, no server to setup a site!

**Comment by gaoyichuan** [comment]
Maybe gitter is better, twitter is outside of China :(

**Comment by TheDiamondYT1** [comment]
i could get my friend to host it.

**Comment by AryToNeX** [comment]
I think we can vote with the GitHub reactions, like :+1: and :-1:

**Comment by TheDiamondYT1** [comment]
Nice :+1:

**Comment by TheDiamondYT1** [comment]
Make a strawpoll

**Comment by TheClimbing** [comment]
"Doom"  Maybe?

**Comment by dktapps** [comment]
My vote? "Kyrios".
It fits nicely with the Greek trend. It means "lord" or "master". With reference to the fact that Genisys is the master of MCPE servers.

**Comment by PeratX** [comment]
@dktapps Nice!

**Comment by PeratX** [comment]
@AryToNeX Don't sad, wait for Genisys 1.3!

**Comment by AryToNeX** [comment]
@PeratX :(
But okay, I'll wait.
_Meanwhile a creeper is spawning near you._
