### ISSUE TITLE
Farms 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#748]
will farms be updated soon? Pumpkin and melon don't grow at all and the other seeds only grow using Bone meal.  not with light.

**Comment by PeratX** [comment]
chekc your chunk ticking

**Comment by Tolo0** [comment]
what do I set it to for farms to grow?

![screenshot_2016-04-07-11-10-39](https://cloud.githubusercontent.com/assets/13458191/14347965/94304a38-fcb1-11e5-88f8-ab853ef01505.png)
