### ISSUE TITLE
Bedrock Issue

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#750]
#### Issue description

When a player stands on bedrock they suffocate 
#### Steps to reproduce the issue

Stand on bedrock in survival mode
#### OS and versions

* Genisys: Build #230
* PHP: 7
* OS: Windows/Linux

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Skyladd** [comment]
Found issue- was plugin. Sorry!

**Comment by PeratX** [comment]
You are welcome :)
