### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by KDOA808** [iTXTech/Genisys#751]
Just qustion very a noob one...
Can geniisys can run plugsins that is lower to Api 2.0.0

And I can install this with Vps?
Thanks

**Comment by PeratX** [comment]
Yes.

**Comment by alex2534alex** [comment]
1 Yes.
2. Use [this](https://github.com/iTXTech/Genisys/files/207708/inst.txt) install script: place it to folder where you want to install Genisys. Then, in command line run "cd /path/to/folder", and then - "chmod 777 inst.txt", and then - "./inst.txt"
