### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by KDOA808** [iTXTech/Genisys#752]
hello i tried to install genisys and got this error do i need to download something?

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /home/kdoa/MCPE/bin/php7/bin/../lib/libcurl.so.4)

**Comment by PeratX** [comment]
compile by yourself.
wget https://raw.githubusercontent.com/iTXTech/php-build-scripts/master/compie.sh
chmod 777 compile.sh
./compile.sh

**Comment by KDOA808** [comment]
https://raw.githubusercontent.com/iTXTech/php-build-scripts/master/compie.sh

not found

**Comment by KDOA808** [comment]
fix

**Comment by KDOA808** [comment]
https://raw.githubusercontent.com/iTXTech/php-build-scripts/master/compile.sh
