### ISSUE TITLE
issue of  #736  still exist

### ISSUE THREAD

**Issue by zhouruixi** [iTXTech/Genisys#753]
对于红石灯，问题依旧；对于TNT，放置的TNT不会爆炸，而是凭空多出来一个点燃的TNT
为了描述清楚，就用中文啦~
Genisys： 258ac0a
mc win10   0.14.1

**Comment by gaoyichuan** [comment]
下次请按照模板发issue，谢谢

**Comment by zhouruixi** [comment]
因为链接到了之前的issue，环境完全相同，故没有按照格式发，之前描述的很清楚了。有点懒~见谅

**Comment by PeratX** [comment]
已修复
