### ISSUE TITLE
RakLibServer throws error on LoginPacket on android devices

### ISSUE THREAD

**Issue by frankblob** [iTXTech/Genisys#754]
#### Issue description
RakLibServer throws error on LoginPacket across android devices using client version 0.14.0

#### Steps to reproduce the issue
Install fresh Genisys (version 1.1dev-233 "Ikaros" with PHP7) on Ubuntu 14.04.4 and start the Genisys server. Attempt to connect with Android (5 and 6) MCPE client version 0.14.0.

#### Crashdump, backtrace or other files
[debug_genisys_dev233.txt](https://github.com/iTXTech/Genisys/files/208324/debug_genisys_dev233.txt)

**Comment by PeratX** [comment]
Can't see anything wrong.
