### ISSUE TITLE
Colored armor?

### ISSUE THREAD

**Issue by SavionLegendZzz** [iTXTech/Genisys#755]
THIS IS NOT AN ISSUE!

So i was going through my github notifications and i seen this: 
https://github.com/Nukkit/Nukkit/commit/d0a3ba194694908182fc02c3233687667777d9df

So i thought "That would be awesome in PHP" So here is my idea:
Port this to php.

Thanks, Savion.

**Comment by ishitatsuyuki** [comment]
This is not an issue? Should I close it?

If you are requesting a feature, describe what you want but not these junk.

**Comment by PeratX** [comment]
We already have! Check Armor::setColor()
