### ISSUE TITLE
NOT AN ISSUE- Is It Possible To Make the .cmd file loop like linux?

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#757]
#### Issue description

We need our start.cmd file to auto restart it's self just like in linux if you change loop to true. Is there any way to do this? Please answer back 
#### OS and versions

* Genisys:
* PHP:
* OS: Windows

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
NOT AN ISSUE - Closing.
No support requests here.
