### ISSUE TITLE
Unexpected PlayerQuitEvent

### ISSUE THREAD

**Issue by Dergercol** [iTXTech/Genisys#758]
When i use:
public function onKick(PlayerKickEvent $e){
    $e->setCancelled();
}
Works PlayerQuitEvent... Why?

And

When i use:
public function onKick(PlayerPreLoginEvent $e){
    $e->setCancelled();
}
Works PlayerQuitEvent... Why?

**Comment by PeratX** [comment]
What is your propose

**Comment by Dergercol** [comment]
You are call PlayerQuitEvent in PlayerQuitEvent When event setCancelled
Sorry for my english

**Comment by Muqsit** [comment]
That is what must happen :/
https://forums.pocketmine.net/threads/playerkickevent-and-playerquitevent.14637/

**Comment by PeratX** [comment]
@Muqsit Is Sugarcran ready?

**Comment by Muqsit** [comment]
@PeratX Not yet, I'm not getting enough time to work on it! :/ I've made a branch for it btw...
