### ISSUE TITLE
Non-op players can use color codes. Bug?

### ISSUE THREAD

**Issue by FaigerSYS** [iTXTech/Genisys#765]
Jenkins build: #246

![screenshot_2016-04-09-11-19-12](https://cloud.githubusercontent.com/assets/18305374/14402668/3f86841c-fe45-11e5-922b-68b94d859c60.png)

**Comment by PeratX** [comment]
Not bug. It should be. You can write a plugin to disable

**Comment by FaigerSYS** [comment]
Can u add permission to use this, without any plugins?

**Comment by Skyladd** [comment]
Essentialspe has this ability plus many more useful things. If you don't like it edit the plugin and keep it minimal.

**Comment by Driesboy** [comment]
or pure perms and pure chat
