### ISSUE TITLE
Future enhancements

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#766]
I really love you all and the hardwork you all have put into this! :D 
Without you people, PocketMine and Pocket Edition servers would be trash! ImagicalMine and ClearSky are buggy and laggy too! Genisys is literally the best and the stable one! I hope you add these in the future!
- [ ] Maps (with ItemFrame onActivate)
- [x] Fix the hotbar (When you scroll through the hotbar, it starts to bug and selects different slots very fast)
- [ ] Add Minecart with chest and TNT
- [x] Add red sandstone
- [ ] Enchantment effects

**Comment by Muqsit** [comment]
Red sandstone and Minecart variants would be easy! And oh, the hotbar issue is a very old issue. It was since PocketMine 1.5

**Comment by PeratX** [comment]
We will in the future. And thanks for your support!

**Comment by dog194** [comment]
160414-Silk Touch done

**Comment by dog194** [comment]
160415-FORTUNE done
If somethings missed. Plz let me know.

**Comment by Muqsit** [comment]
@dog194 Fire Aspect, Protection, Efficiency :3

**Comment by dog194** [comment]
"(ºДº*) @Muqsit i mean something for Fortune and Silk Touch. I will add another enchantment which i can.

**Comment by dog194** [comment]
"(ºДº*) @Muqsit i mean something for Fortune and Silk Touch. I will add another enchantment which i can.

**Comment by Muqsit** [comment]
public function onDamage(EntityDamageEvent $e){
        $p = $e->getEntity();
        if (!$p instanceof Player){
            return;
        }

        if ($e instanceof EntityDamageByEntityEvent){
            $pl = $e->getDamager();
            if (!$pl instanceof Player){
                return;
            }
            $it = $pl->getInventory()->getItemInHand();
            if (!$it->hasEnchantments()){
                return;
            }
            $en = $it->getEnchantments();
            foreach ($en as $ench){
                $lvl = $ench->getLevel();
                switch ($ench->getId()){
                    case 13:
                        if (!$e->isCancelled()){
                            $p->setOnFire($lvl*4);
                        }
                        break;

**Comment by dog194** [comment]
160419-Unbreaking for tools done (except bow)

**Comment by GlitchPlayer** [comment]
How about built-in economy?

**Comment by GlitchPlayer** [comment]
That would be awesome

**Comment by ishitatsuyuki** [comment]
@GlitchPlayer : This should never be done by a server, we basically implements vanilla functionality. A plugin is easier for management.

**Comment by GlitchPlayer** [comment]
Ok.

**Comment by GlitchPlayer** [comment]
Economy plugins nowadays are outdated

**Comment by jellyfishcoder** [comment]
The ability to show all of a plugins commands by typing in /plugin _insertnamehere_. I know its kinda simple, but it would be very convenient so you don't have to look up a list of commands. Also some way to list all enchantments, like /enchant list would be nice. Again, just because Im lazy and its a pain to have to A) memorise the enchantments, or B) go look in the code for the IDs.

**Comment by Skyladd** [comment]
@jellyfishcoder Plugin developers can easily add all of their commands on the event of using the main plugin command, thus this may not be needed for a server. @GlitchPlayer There are a couple of good ones like MassiveEconomy and another EconomyAPI one. It's also up to the plugin developer to support multiple economy plugins. MassiveEconomy is actually really easy to edit and customize

**Comment by jellyfishcoder** [comment]
@Skyladd I know they _COULD_ but most old plugins and some new ones don't.

**Comment by Skyladd** [comment]
Check red sandstone off the list someone.

**Comment by dktapps** [comment]
Checked off the glitchy hotbar by way of commit b15bcc1

**Comment by KennanFatt** [comment]
Add mesa biome for DEFAULT level generator

**Comment by ZedCee** [comment]
Fix grass and water blending

**Comment by CubeFromSpace** [comment]
This could be merged with @KeenanFatt's Mesa issue. It's #1431

**Comment by TDMidkwhatisxd** [comment]
If a pickaxe with silk touch break ice , ice will drop , but if player leave map and come again , ice is back!!
Players would get unlimited ice on my server , so i banned ice!! Some still break ice , on secret locations in hope i will unban it  :0  !!!

**Comment by dktapps** [comment]
Hopper will be added in the very near future.

**Comment by TDMidkwhatisxd** [comment]
There is a glich with silk touch pickaxe , if u break ice , exit/join game , or change world and come back , ice didnt break :(  ! It made be ban ice right after i added it O.O !

Aside from that , best fork ever!

**Comment by dktapps** [comment]
@TDMidkwhatisxd Stop spamming.
