### ISSUE TITLE
Convenient to find all "Genisys Custom API"

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#768]
Can u add all your "special API" for comfort to one page of Wiki?

**Comment by ishitatsuyuki** [comment]
Can't you just read the documentation? It's enough.

**Comment by alex2534alex** [comment]
It's not easy to review all documentation (or code) to find them...

**Comment by ishitatsuyuki** [comment]
We won't care about PocketMine-MP: we aren't always aware of keeping compatibility with others.

**Comment by gaoyichuan** [comment]
@ishitatsuyuki I think we do need a documation written by human, not the one generated by Doxygen. Especially for our unique API.
