### ISSUE TITLE
MobAI improvement

### ISSUE THREAD

**Issue by EpicSteve33** [iTXTech/Genisys#77]
Only cows and zombies spawn it would be cool If all spawned and zombies are very buggy but still pretty cool

**Comment by Syntaxious** [comment]
Are enchanting working?

**Comment by PeratX** [comment]
@Syntaxious we are working on it

**Comment by Syntaxious** [comment]
Ahh right, are you looking for the protocol?

**Comment by PeratX** [comment]
No.we have already know the protocol

**Comment by PeratX** [comment]
Just thinking how to write enchantment lists for items...

**Comment by PeratX** [comment]
Now it is in TODO List. Close

**Comment by EpicSteve33** [comment]
I forgot about this XD
