### ISSUE TITLE
Add anvil crafting recipe? Also maybe per world mob spawns? Thank you!!

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#772]
#### Issue description

Anvil recipe is sadly missing and zombies spawning in spawn is no good!
#### OS and versions

* Genisys:Build 249
* PHP:7
* OS:All

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Invalid version. One thing per issue.

**Comment by PeratX** [comment]
Listen to EntityGenerateEvent to control mob spawn.
