### ISSUE TITLE
Damage taken from falling onto slime blocks

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#773]
#### Issue description

Damage taken from falling onto slime blocks
#### Steps to reproduce the issue

Fall on a slime block
#### OS and versions

* Genisys:Build 249
* PHP:7
* OS:All

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Always write your version. Next time I will close your issue.

**Comment by Skyladd** [comment]
Okay- But this affects all versions

**Comment by ishitatsuyuki** [comment]
So what? People don't write version are commonly outdated.

**Comment by Skyladd** [comment]
I guess

**Comment by Skyladd** [comment]
Can you reopen the other issue or should i create 2 more

**Comment by ishitatsuyuki** [comment]
I will reopen after you write the valid version.

**Comment by Skyladd** [comment]
Done./

**Comment by KDOA808** [comment]
@ishitatsuyuki you misunderstand my comment earlier https://github.com/iTXTech/Genisys/issues/777

"please give link thanks sorry for being a noob"

didn't say your the noob sorry for my english. Just saying cause can't reply to say thanks issue was lock but THANKS AGAIN keep it up with the support.

**Comment by gaoyichuan** [comment]
should be fixed
