### ISSUE TITLE
picture frame possible glitch.

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#774]
#### Issue description
picture frames dropping items
#### Steps to reproduce the issue
a player switch to creative mode then place a picture frame then place any item in it. then switch back to survival mode. break the picture frame. and the item drops for them to pick up.

#### OS and versions
* Genisys: Genisys_1.1dev-250.phar
* PHP:
* OS:

**Comment by PeratX** [comment]
Make a plugin listen to ItemFrameDropItemEvent and setCancelled

**Comment by gaoyichuan** [comment]
@PeratX This is what item frames are designed to do...not a bug at all
