### ISSUE TITLE
sorry another error love the support

### ISSUE THREAD

**Issue by KDOA808** [iTXTech/Genisys#777]
installing genisys error in dedicated server(not in vps this time) https://www.dreamhost.com/hosting/dedicated/

Fatal error: Class 'Phar' not found in /home/kdaaa/PE/src/pocketmine/PocketMine.php on line 89
http://i.imgur.com/lrersfW.png

goal: wanted to host a server without lag :D

**Comment by ishitatsuyuki** [comment]
Heard that's dedicated. Then use docker.

**Comment by KDOA808** [comment]
@ishitatsuyuki please give link thanks

**Comment by ishitatsuyuki** [comment]
Read README noob

**Comment by ishitatsuyuki** [comment]
Just warning you: issue tracker isn't for support, use gitter/IRC for that. Although I will provide minimal answer, I'm not happy to have those on issue tracker.
