### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by svilex** [iTXTech/Genisys#779]
#### Issue description
Invisible players, that's all.

#### Steps to reproduce the issue
1. To avoid mistakes change gamemode to survival.
2. Teleport to a world that isn't the default one.
3. Tell someone to teleport to you.
4. Tell this someone to kill you.
5. Run from a plugin, on the PlayerDeathEvent function this code: `$killer->teleport($killer->getServer()->getDefaultLevel()->getSpawnLocation()); $p->teleport($p->getServer()->getDefaultLevel()->getSpawnLocation());` where $p is an instance of pocketmine/Player (the death player) and $killer is the killer.
6. Now click the respawn button on the death player screen.
7. From the plugin, make he respawn in the default level spawn using the `PlayerRespawnEvent->setRespawnPosition();`
8. Now the death player can't see the killer. The killer can see the death player

Should happens also teleporting to another level but i never tested.

#### OS and versions
* Genisys: [252](https://jenkins.mcper.cn/job/Genisys-master/252/) (the last at this date)
* PHP: 7.0.4
* OS: Linux Ubuntu 15.10

**Comment by svilex** [comment]
This happens very often, not only on my server

**Comment by PeratX** [comment]
Do not teleport in death event. should be in Respawn event. Teleport when not alive will not spawn to all!

**Comment by svilex** [comment]
>Do not teleport in death event. should be in Respawn event. Teleport when not alive will not spawn to all!

@PeratX maybe is because of this but i'm not sure. i'm teleporting on both events to the same location (i know is useless).

**Comment by Pub4Game** [comment]
@PeratX Maybe the same problem

https://github.com/Nukkit/Nukkit/issues/499

**Comment by KillerXtream** [comment]
Bug confirmed, @PeratX needs to add the bug label.
