### ISSUE TITLE
Issue setItemInHand()

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#787]
#### Issue description

When I use the function: setItemInHand it not work all the time. For example when I do the setItemInHand function in box 1 of MCPE its working. But sometimes in the box of the inventory from the center, the function does not work. Code : $ p-> getInventory () -> setItemInHand ()

#### OS and versions

* Genisys: Last Version
* PHP: 7
* OS: Linux
#### Crashdump, backtrace or other files
```
(No error in server.log)
```

**Comment by ishitatsuyuki** [comment]
Closing for invalid version.

Seems noobs never follow the template.
