### ISSUE TITLE
water bug

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#788]
#### Issue description
item ID: 9 water flows.  only item ID: 8 should flow.

#### Steps to reproduce the issue
placed both types of water and both flow.
#### OS and versions
* Genisys: Genisys_1.1dev-269.phar
* PHP: 7
* OS:

**Comment by PeratX** [comment]
Do not use this method! When water flows into still_water, still_water will become water!

**Comment by Tolo0** [comment]
That's not what I mean. I placed to water only and it wasn't still. so I tested flowing water to see if it was the same and it was. still water isn't still. it flows like flowing water.

**Comment by PeratX** [comment]
Fixed

**Comment by Tolo0** [comment]
ok thanks. also when I posted about farms not growing.  I didn't know thst you needed water lol. on the old builds u didn't need water.

**Comment by Tolo0** [comment]
@PeratX would it be possible for you to add to the genisys.yml the option to disable all flowing water and lava?  it's so annoying when players place water all over . iv had to ban buckets on my server becos of this lol.

**Comment by Tolo0** [comment]
disable the flow event for water only I mean.  so when a player places water with a bucket. it comes out as still water.

**Comment by ishitatsuyuki** [comment]
A plugin's job.

**Comment by Tolo0** [comment]
the genisys.yml can do alot of things like that. like disable mobs. weather burning. though maybe water could also be one of them.
