### ISSUE TITLE
So much, so high....

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#789]
![screenshot_2016-04-11-21-39-08](https://cloud.githubusercontent.com/assets/15706847/14438328/35d989e2-002e-11e6-9aa4-55b99d61ea3a.png)

**Comment by alex2534alex** [comment]
Map is generated just now. Build #269

**Comment by PeratX** [comment]
Do not use mobile phones to generate maps.

**Comment by alex2534alex** [comment]
All the same, it's bug

**Comment by gaoyichuan** [comment]
@PetatX Your sugarcane populator has bug
