### ISSUE TITLE
still water bug

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#792]
#### Issue description
still water. Can't be removed 

#### Steps to reproduce the issue
when placing still water. it can't be removed using a bucket or by placing a block on top. sorry to bug you again @PeratX 

![screenshot_2016-04-12-18-41-39](https://cloud.githubusercontent.com/assets/13458191/14470116/b0f5b982-00df-11e6-9184-30c046cababa.png)

**Comment by dog194** [comment]
Why do you use still water instead of a bucket?

**Comment by Tolo0** [comment]
becos I don't want players flooding my server.

**Comment by dog194** [comment]
@Tolo0  then just use plugin to make water not flow.
I think this is not our work.

**Comment by Tolo0** [comment]
ur going off topic. it has nothing to do with flowing water. after placing still water. it bugs and can't be removed.
