### ISSUE TITLE
iOS connection issues

### ISSUE THREAD

**Issue by KillerXtream** [iTXTech/Genisys#793]
#### Issue description

iOS clients crash (MCPE app crash) when joining servers with recent builds. Android is not affected.
#### Steps to reproduce the issue

Just join the server. When it says Building terrain... it crashes.

#### OS and versions

* Genisys: 246
* PHP: 7
* OS: CentOS 7.2 el2.krl13.1stab

#### Crashdump, backtrace or other files
```
Server do not crash, just the client.
```

**Comment by ishitatsuyuki** [comment]
It will be easier to resolve if you can debug your device...

**Comment by KillerXtream** [comment]
How?

**Comment by ishitatsuyuki** [comment]
Basically using XCode on OS X

**Comment by KillerXtream** [comment]
ah, i dont have macbook

**Comment by Muqsit** [comment]
But why aren't you using the latest build? It might probably fix this bug!

**Comment by KillerXtream** [comment]
Fixed with latest build and MCPE reinstall. Closed #793

**Comment by KillerXtream** [comment]
Issue reopened.

Started crashing again.

**Comment by xXSirGamesXx** [comment]
I have been having this crashing issue as well when joining my server.

**Comment by ProjectInfinity** [comment]
We've got several iOS users reporting on our forum that they cannot connect when we're running Genisys.

**Comment by PeratX** [comment]
More details, my players reported they are all fine

**Comment by PeratX** [comment]
You can try to set force chunk radius in genisys.yml
