### ISSUE TITLE
Minecraft PE 0.15.0 UPDATE?

### ISSUE THREAD

**Issue by RedstoneAlmeida** [iTXTech/Genisys#799]

**Comment by erkam2002** [comment]
?

**Comment by dktapps** [comment]
@erkam2002 the 0.15.0 MCPE beta has been started

**Comment by erkam2002** [comment]
wtf link?

**Comment by dktapps** [comment]
@erkam2002 play.google.com/apps/testing/com.mojang.minecraftpe

**Comment by RedstoneAlmeida** [comment]
Minecraft pe is updated to 0.15.0, genisys is update 0.15.0?

**Comment by erkam2002** [comment]
But no new items :'(

**Comment by Skyladd** [comment]
Genisys still has 0.14 items to add such as hoppers and fixing redstone bugs like redstone block not powering from all sides and stuff. I don't know what happened to imagicalmine but their redstone is pretty good, they are just missing the nether and mob spawns

**Comment by dktapps** [comment]
@Skyladd I think he meant the actual update itself has no new items. BTW this is Harry :3

**Comment by erkam2002** [comment]
Pls accept protocol for 0.15.0

**Comment by dktapps** [comment]
Protocol version for 0.15.0 is 60

**Comment by erkam2002** [comment]
Now?

**Comment by Driesboy** [comment]
Ok use my betatester plugin

**Comment by flaxues** [comment]
Awww I finally was thinking that mcpe will have authentication but it's only for realms...

https://twitter.com/_tomcc/status/720247445234393090

**Comment by XxPeaceHellxX** [comment]
Update 0.14.2 please
