### ISSUE TITLE
Huge fatal crash. Easily can reproduce (not a good thing)

### ISSUE THREAD

**Issue by Lucario2** [iTXTech/Genisys#80]
When you stack a collapsible item a certain amount of times and then break the bottom one- server crashes. works with carpet, cactus, snow ect...

**Comment by GalvinGao** [comment]
Please report or update a **CrashDump-*************.log** so we can see more details about the crash. The .log file can be founded as **where you install/run the server**. Thanks.

**Comment by Lucario2** [comment]
Sorry forget to show the dump.

Genisys Crash Dump Wed Jan 13 20:52:46 ACT 2016

Error: Maximum function nesting level of '100' reached, aborting!
File: /src/pocketmine/plugin/MethodEventExecutor
Line: 39
Type: E_ERROR

Code:

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(boolean)
#2 /src/pocketmine/plugin/PluginManager(676): pocketmine\plugin\RegisteredListener->callEvent(boolean)
#3 /src/pocketmine/Player(1063): pocketmine\plugin\PluginManager->callEvent(boolean)
#4 /src/pocketmine/Server(2127): pocketmine\Player->dataPacket(boolean)
#5 /src/pocketmine/level/Level(903): pocketmine\Server::broadcastPacket(boolean)
#6 /src/pocketmine/level/Level(1463): pocketmine\level\Level->sendBlocks(boolean)
#7 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#8 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#9 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#10 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#11 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#12 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#13 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#14 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#15 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#16 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#17 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#18 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#19 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#20 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#21 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#22 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#23 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#24 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#25 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#26 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#27 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#28 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#29 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#30 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#31 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#32 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#33 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#34 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#35 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#36 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#37 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#38 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#39 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#40 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#41 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#42 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#43 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#44 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#45 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#46 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#47 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#48 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#49 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#50 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#51 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#52 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#53 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#54 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#55 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#56 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#57 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#58 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#59 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#60 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#61 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#62 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#63 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#64 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#65 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#66 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#67 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#68 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#69 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#70 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#71 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#72 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#73 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#74 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#75 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#76 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#77 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#78 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#79 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#80 /src/pocketmine/level/Level(1073): pocketmine\block\Cactus->onUpdate(boolean)
#81 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#82 /src/pocketmine/block/Block(650): pocketmine\level\Level->setBlock(boolean)
#83 /src/pocketmine/level/Level(1666): pocketmine\block\Block->onBreak(boolean)
#84 /src/pocketmine/block/Cactus(76): pocketmine\level\Level->useBreakOn(boolean)
#85 /src/pocketmine/level/Level(1088): pocketmine\block\Cactus->onUpdate(boolean)
#86 /src/pocketmine/level/Level(1488): pocketmine\level\Level->updateAround(boolean)
#87 /src/pocketmine/block/SignPost(69): pocketmine\level\Level->setBlock(boolean)
#88 /src/pocketmine/level/Level(1836): pocketmine\block\SignPost->place(boolean)
#89 /src/pocketmine/Player(2506): pocketmine\level\Level->useItemOn(boolean)
#90 /src/pocketmine/network/RakLibInterface(143): pocketmine\Player->handleDataPacket(boolean)
#91 /src/raklib/server/ServerHandler(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#92 /src/pocketmine/network/RakLibInterface(82): raklib\server\ServerHandler->handlePacket(boolean)
#93 /src/pocketmine/network/Network(161): pocketmine\network\RakLibInterface->process(boolean)
#94 /src/pocketmine/Server(2832): pocketmine\network\Network->processInterfaces(boolean)
#95 /src/pocketmine/Server(2549): pocketmine\Server->tick(boolean)
#96 /src/pocketmine/Server(2427): pocketmine\Server->tickProcessor(boolean)
#97 /src/pocketmine/Server(1965): pocketmine\Server->start(boolean)
#98 /src/pocketmine/PocketMine(456): pocketmine\Server->__construct(boolean)
#99 /src/pocketmine/PocketMine(0): {main}(boolean)

Genisys version: 1.0dev #0 [Protocol 38; API 1.13.1]
uname -a: Windows NT BASEMENT 6.3 build 9200 (Windows 8.1 Home Premium Edition) i586
PHP version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
加载的插件:
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
BlockLocations 1.0.2 by Array for API(s) 1.7.1
BlockMan 1.0.0 by SuperMarcus for API(s) 1.10.0
BouncyBlocks 1.1 by Darunia18 for API(s) 1.9.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
CapsLimit 1.0.0 by deot for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CommandTracker 1.0.1 by Scott Handley for API(s) 1.10.0
ContactManager 1.0.1 by basprohop for API(s) 1.10.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EasyMOTD 1.0a by LDX for API(s) 1.12.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
Farms 1.0-non-alpha by hm for API(s) 1.4.1
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
FireBlade 1.0.2 by aliuly for API(s) 1.10.0
FloatingTexter 1.0 by Heromine/Jon for API(s) 1.12.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
ItemSneaking 1.3.0 by GmWM for API(s) 1.12.0
JoinCommands 1.4.1 by PixelGuy75 for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
mcg76_SimplePortal 2.0.3 by minecraftgenius76 for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
MoreCommands 1.1.3 by  for API(s) 1.10.0, 1.11.0, 1.12.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
OreFinder 1 by Falk for API(s) 1.0.0
PaintMyLawn 1.2.0 by shoghicp for API(s) 1.0.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
PurePerms 1.0.8 by 64FF00 for API(s) 1.9.0
ReasonWL 1.1 by CreeperFace for API(s) 1.12.0
Sheep 4.0.3 by KnownUnown for API(s) 1.0.0
SignModifier 1.0.0 by wolfdale for API(s) 1.3.1
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
TimeZones 2.0.1 by HotFireyDeath/Chopstick Software for API(s) 1.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 1.12.0
UUIDAuth 1.0-Test by hm for API(s) 1.0.0, 1.4.0, 1.12.0, 1.13.0, 2.0.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by Lucario2** [comment]
Apparently, this has something to do with my plugins file and listeners. This may be world edit art.

**Comment by Lucario2** [comment]
Or there is something wrong with the calculation of the blocks and it caused it to crash.

**Comment by PeratX** [comment]
@Lucario2 It is easy to solve. Disable xdebug extension in you php.ini

**Comment by astersx** [comment]
Yep this is only for windows users!!!

**Comment by Lucario2** [comment]
Thank you. Question. How might you know all of this?

**Comment by PeratX** [comment]
@Lucario2 Whe  I was working on Redstone, I caught this fault

**Comment by astersx** [comment]
I run a server for almost 1 year , i will be more than a noob to not know some tricks :)

**Comment by Lucario2** [comment]
I run it for more than a year how do u mess with the files and know what
your doing

**Comment by astersx** [comment]
Becouse,  i see discutions,  and what is going on!!  And becouse i read before editing!!!  Before i edit,  i look to every function to see what is it doing to server!!  So i dont make mistakes!!!

**Comment by Lucario2** [comment]
Oh, lol. Got me.

**Comment by astersx** [comment]
What server u run?

**Comment by Lucario2** [comment]
Pocketmine. I use a complete rewrite of it called genisys

**Comment by astersx** [comment]
server ip=))))))))

**Comment by Lucario2** [comment]
74.108.59.89 port 19134

**Comment by astersx** [comment]
not domain? im owner of buildmcpe.eu
04:05. morning,  omg i almost pulled a all night =))
need sleep

**Comment by Lucario2** [comment]
No domain. Lol

**Comment by Lucario2** [comment]
Hosted off my PC. I know it's stupid. But I like it. You can criticize me
of u want...

**Comment by astersx** [comment]
Yep this is ..... .  And laggy!! Use a vps,  cheaper!!!
If you run on pc = Energy bills,  internet bill!!!
On vps = 3-15 euro

**Comment by Lucario2** [comment]
I use $

**Comment by astersx** [comment]
Is $,  sorry i always say euro

**Comment by Lucario2** [comment]
Lol.

**Comment by astersx** [comment]
Hope @PeratX  or others devs here wont kill us for using this as a chat =))

**Comment by Lucario2** [comment]
They will ban me kik me at Lucariomcpe plz and this never happened

**Comment by astersx** [comment]
And a server with domain is safer!!  Ip can change but domain cant change :)

**Comment by Lucario2** [comment]
KIK ME LUCARIOMCPE

**Comment by astersx** [comment]
oh ok =))
i tought u say kick =))
