### ISSUE TITLE
SetMaxPlayerCount() and SetPlayerCount

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#801]
#### Issue description

$e->setPlayerCount(); don't work and $e->setMaxPlayerCount() in QueryRegenerateEvent
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
Query info does not change? Or do you mean motd.

**Comment by MineBuilderFR** [comment]
Query dos not change
