### ISSUE TITLE
Experience bug

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#804]
#### Issue description

Experience isnt saved right.

#### Steps to reproduce the issue

Get some exp.
You now have lets say 30 exp.
Use enchanting table or anvil to lower exp.
You now have lets say 20 exp.
re-log...
You now have 30 exp again and enchanted/named item.

#### OS and versions

* Genisys: 282
* PHP: 7
* OS: windows

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
Known issue. This is because client calculate itslef.
