### ISSUE TITLE
Did not fix...

### ISSUE THREAD

**Issue by Dergercol** [iTXTech/Genisys#810]
U are forgot... PeratX

<pre>[15:26:07] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'CTF v0.1': Call to a member function getAttribute() on null on ctf\main
[15:26:07] [Server thread/CRITICAL]: Error: "Call to a member function getAttribute() on null" (EXCEPTION) in "/src/pocketmine/entity/Effect" at line 310
</pre>

**Comment by Dergercol** [comment]
And why did u change client version?

**Comment by PeratX** [comment]
Plugin error. Do not report again.

**Comment by Dergercol** [comment]
Test it now. Look at 310 line. I disabled all plugins!!

**Comment by ishitatsuyuki** [comment]
Exactly plugin issue: if not paste the log.

**Comment by Dergercol** [comment]
Cool! I fixed /pocketmine/entity/Effect.php
You are forgot if....
It is so annoyed.
You even did not write my error.

**Comment by Dergercol** [comment]
You are even did not fixed...
