### ISSUE TITLE
Anti-cheat threathhold on arrows

### ISSUE THREAD

**Issue by Dergercol** [iTXTech/Genisys#812]
I think, it is too strong anticheat.... Try shoot by bow. It will be very unusual

**Comment by Dergercol** [comment]
Shoot and move

**Comment by Dergercol** [comment]
If u wont move, it will be works good.

**Comment by ishitatsuyuki** [comment]
@Muqsit - Correctly use the "bug" label: only mark it if you fully understand the bug and think it's reproducible. I can't even understand this alien language.

**Comment by Muqsit** [comment]
@ishitatsuyuki I have confirmed it. This happens.
Shoot an arrow while you're moving and the arrow event will be cancelled. There won't be any arrow sent. But if you stay still (don't move) and shoot an arrow, it works fine.

**Comment by Lucario2** [comment]
So fix it..

**Comment by PeratX** [comment]
I cannot reproduce this issue when moving

**Comment by dog194** [comment]
Maybe you just move too fast. Then pick the arrow before shoot.
