### ISSUE TITLE
Can't Join server!

### ISSUE THREAD

**Issue by Fer0c** [iTXTech/Genisys#82]
I run on php7.

**Comment by PeratX** [comment]
Do not let server generate world. Use an exist world instead. We are working on it now : )

**Comment by PeratX** [comment]
The latest commits fixed this.

**Comment by Fer0c** [comment]
I checked it,but next bug occured.
[Server thread/CRITICAL]: Unable to find the Weakref extension.
[12:38:16] [Server thread/CRITICAL]: Please use the installer provided on the homepage, or recompile PHP again.
This warning appeared again and again when I recompile.

**Comment by Fer0c** [comment]
The latest don't fix the bug .

**Comment by PeratX** [comment]
do not use the version on jenkins.

**Comment by PeratX** [comment]
cant join server. Is always locating server ?

**Comment by Fer0c** [comment]
No.

**Comment by Fer0c** [comment]
Sorry I was checking . The bug was fixed!

**Comment by gaoyichuan** [comment]
@PeratX In my server it's it. Always shows 'Locating Server'. But server log shows I joined the game.

**Comment by PeratX** [comment]
@gaoyichuan use the latest build on jenkins.
