### ISSUE TITLE
Enchantment Table & Anvil

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#821]
#### Issue description

Enchantment Table: Cannot enchant items. When I enchant an item and drag it to my inventory, it will have no enchantments.

Anvil: Cannot mix enchanted books with tools.

#### OS and versions

* Genisys: 1.1dev, 1.7.2
* PHP: 7.0.5
* OS: Ubuntu 14 (64-bit)

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
MinecraftPE or Win10PE?
I just have a test. Nothing wrong in Enchantment Table. I enchant an Diamond Pickaxe successfully.
For Anvil. We will work on it in the future.

**Comment by ishitatsuyuki** [comment]
Closing for invalid version.

**Comment by GenisysFTW** [comment]
Sorry, it was fixed
