### ISSUE TITLE
Mob spawned but invisible

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/Genisys#823]
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Lastest Genysis version.

Hello,
If I try to spawn a zombie using : 

`        $nbt = new CompoundTag("", [
            "Pos" => new ListTag("Pos", [
                new DoubleTag("", 12),
                new DoubleTag("", 8),
                new DoubleTag("", 0.5)
            ]),
            "Motion" => new ListTag("Motion", [
                new DoubleTag("", 0),
                new DoubleTag("", 0),
                new DoubleTag("", 0)
            ]),
            "Rotation" => new ListTag("Rotation", [
                new FloatTag("", lcg_value() * 360),
                new FloatTag("", 0)
            ]),
        ]);



        $this->playMob = new Zombie($level->getChunk($level->getSpawnLocation()->x,$level->getSpawnLocation()->z),$nbt);`

The zombie IS spawned (I check with /status command) but it won't appear to players. I tried to schedule a repeating spawnToAll for this zombie.

The exact same code on ImagicalMine works (the player sees the zombie).



```

**Comment by PeratX** [comment]
$this->playMob->spawnToAll();

**Comment by Guillaume351** [comment]
Already done, still doesn't work (I failed the description I'm editing it)

**Comment by Guillaume351** [comment]
Please re-open when you see the update. as I say, the exact same code works on ImagicalMine and the zombie is spawned but not visible, even if I spawnToAll  every second

**Comment by PeratX** [comment]
Whole file please

**Comment by Guillaume351** [comment]
The onEnable : 

`        $this->getServer()->getNetwork()->setName(TextFormat::AQUA."Cookie ". TextFormat::YELLOW ."Build". TextFormat::GREEN." MicroBattles");
        $this->lock = false;
        $this->counter = 0;
        $level = $this->getServer()->getDefaultLevel();
        $this->getServer()->getScheduler()->scheduleRepeatingTask(new messageBroadcast($this),20*25);
        $this->getServer()->getScheduler()->scheduleRepeatingTask(new stopServerTask($this),20 * 600);
       // $spawn = new Vector3(132,16,132);
        //$this->getServer()->getDefaultLevel()->setSpawnLocation($spawn);


        $moreInfoR1 =$level->getTile(new Vector3(0,10,12));
        $moreInfoR2 =$level->getTile(new Vector3(0,9,12));
        $moreInfoR3 =$level->getTile(new Vector3(0,8,12));

        if($moreInfoR1 instanceof Sign and $moreInfoR2 instanceof Sign and $moreInfoR3 instanceof Sign){
            $moreInfoR1->setText(TextFormat::WHITE."Cookie Build",TextFormat::GREEN."MicroBattles",TextFormat::WHITE."www.cookie-build.com",TextFormat::GREEN."Lobby by @ThatBreeezy ");

            $moreInfoR2->setText(TextFormat::RED."Owner and developer",TextFormat::RED."@Guillaume351",TextFormat::WHITE."Support :","support@cookie-build.com");

            $moreInfoR3->setText(TextFormat::WHITE."Our Android app is",TextFormat::WHITE."available !",TextFormat::WHITE."Cookie Build Network",TextFormat::WHITE."(Google Play Store");
        }

        $this->infoKit1 = $level->getTile(new Vector3(12,10,-2));
        $this->buyKit1 = $level->getTile(new Vector3(12,9,-2));
        $this->selectKit1 = $level->getTile(new Vector3(12,8,-2));

        $this->infoKit2 = $level->getTile(new Vector3(12,10,-1));
        $this->buyKit2 = $level->getTile(new Vector3(12,9,-1));
        $this->selectKit2 = $level->getTile(new Vector3(12,8,-1));


        $this->infoKit3 = $level->getTile(new Vector3(12,10,1));
        $this->buyKit3 = $level->getTile(new Vector3(12,9,1));
        $this->selectKit3 = $level->getTile(new Vector3(12,8,1));

        $this->infoKit4 = $level->getTile(new Vector3(12,10,2));
        $this->buyKit4 = $level->getTile(new Vector3(12,9,2));
        $this->selectKit4 = $level->getTile(new Vector3(12,8,2));


        $nbt = new CompoundTag("", [
            "Pos" => new ListTag("Pos", [
                new DoubleTag("", 12),
                new DoubleTag("", 8),
                new DoubleTag("", 0.5)
            ]),
            "Motion" => new ListTag("Motion", [
                new DoubleTag("", 0),
                new DoubleTag("", 0),
                new DoubleTag("", 0)
            ]),
            "Rotation" => new ListTag("Rotation", [
                new FloatTag("", lcg_value() * 360),
                new FloatTag("", 0)
            ]),
        ]);



        $this->playMob = new Zombie($level->getChunk($level->getSpawnLocation()->getX(),$level->getSpawnLocation()->getZ()),$nbt);

    //    $this->playMob->teleport(new Vector3(1,9,0));
        $this->playMob->spawnToAll();
 
        $this->playMob->canCollide = false;
        $this->playMob->setRotation(45,45);
        $this->playMob->setNameTag(TextFormat::WHITE."TAP TO PLAY");












        $this->game = [1=>new Game(1,0,true),2=>new Game(2,0,true),3=>new Game(3,0,true),4=>new Game(4,0,true),
            5=>new Game(5,0,true),6=>new Game(6,0,true),7=>new Game(7,0,true),8=>new Game(8,0,true)];

                                //1 BLUE, 2 RED, 3 YELLOW, 4 GREEN
        $this->pedestrals["1-1"] = new Vector3(-11.5,41,-6.6);
        $this->pedestrals["1-2"] = new Vector3(-7.5,41,12.5);
        $this->pedestrals["1-3"] = new Vector3(8.5,41,-11.5);
        $this->pedestrals["1-4"] = new Vector3(12.5,41,8.5);

        $this->pedestrals["2-1"] = new Vector3(117.5,19,114.5);
        $this->pedestrals["2-2"] = new Vector3(117.5,19,125);
        $this->pedestrals["2-3"] = new Vector3(107.5,19,125);
        $this->pedestrals["2-4"] = new Vector3(107.5,19,114.5);

        $this->pedestrals["3-1"] = new Vector3(123,25,133);
        $this->pedestrals["3-2"] = new Vector3(132,25,124);
        $this->pedestrals["3-3"] = new Vector3(131,25,132);
        $this->pedestrals["3-4"] = new Vector3(123,25,124);

        $this->pedestrals["4-1"] = new Vector3(7,44,5);
        $this->pedestrals["4-2"] = new Vector3(-7,44,5);
        $this->pedestrals["4-3"] = new Vector3(-5,44,-7);
        $this->pedestrals["4-4"] = new Vector3(11,44,-6);

        $this->pedestrals["5-1"] = new Vector3(-11.5,41,-6.6);
        $this->pedestrals["5-2"] = new Vector3(-7.5,41,12.5);
        $this->pedestrals["5-3"] = new Vector3(8.5,41,-11.5);
        $this->pedestrals["5-4"] = new Vector3(12.5,41,8.5);

        $this->pedestrals["6-1"] = new Vector3(123,25,133);
        $this->pedestrals["6-2"] = new Vector3(132,25,124);
        $this->pedestrals["6-3"] = new Vector3(131,25,132);
        $this->pedestrals["6-4"] = new Vector3(123,25,124);

        $this->pedestrals["7-1"] = new Vector3(7,44,5);
        $this->pedestrals["7-2"] = new Vector3(-7,44,5);
        $this->pedestrals["7-3"] = new Vector3(-5,44,-7);
        $this->pedestrals["7-4"] = new Vector3(11,44,-6);

        $this->pedestrals["8-1"] = new Vector3(117.5,19,114.5);
        $this->pedestrals["8-2"] = new Vector3(117.5,19,125);
        $this->pedestrals["8-3"] = new Vector3(107.5,19,125);
        $this->pedestrals["8-4"] = new Vector3(107.5,19,114.5);

        $this->getServer()->getPluginManager()->registerEvents($this, $this);
        $this->getServer()->getPluginManager()->registerEvents(new onPlayerJoin($this), $this);
        $this->getServer()->getPluginManager()->registerEvents(new onPlayerKick($this), $this);
       // $this->getServer()->getDefaultLevel()->setSpawn($spawn);

        $this->extractWorld(1);
        $this->extractWorld(2);
        $this->extractWorld(3);
        $this->extractWorld(4);
        $this->extractWorld(5);
        $this->extractWorld(6);
        $this->extractWorld(7);
        $this->extractWorld(8);

        $this->getServer()->getScheduler()->scheduleRepeatingTask(new checkIfPlayerWon($this), 20);
        $this->getServer()->getScheduler()->scheduleRepeatingTask(new tellPlayerTeam($this),10);
        $this->getServer()->getScheduler()->scheduleRepeatingTask(new reloadDatabaseTask($this), 20*30);

        foreach ($this->getServer()->getLevels() as $w){
            $w->checkTime();
            $w->setTime(8000);
            $w->stopTime();
            $w->checkTime();

        }

        $this->getServer()->broadcastMessage(TextFormat::GREEN."MicroBattles Plugin Successfully loaded");


`

And the onPlayerJoin : 

`        $player = $event->getPlayer();
        $iPlayer = $player;
      //  $this->plugin->iPlayers[$player->getId()] = new IPlayer($player);
       // $iPlayer = $this->plugin->iPlayers[$player->getId()];


        $pos = new Vector3(16,20,-4);
       // $text ="";
    $title = "▄▀▀▄─▄▀▀▄─▄▀▀▄─█─▄▀─█─█▀▀───█▀▄─█──█─█─█───█▀▄
█──▄─█──█─█──█─█▀▄──█─█▀▀───█▀█─█──█─█─█───█─█
─▀▀───▀▀───▀▀──▀──▀─▀─▀▀▀───▀▀───▀▀──▀─▀▀▀─▀▀─
";

        $text = "█▄─▄█─█─▄▀▀▄─█▀▄─▄▀▀▄─█▀▄─▄▀▄─▀█▀─▀█▀─█───█▀▀─▄▀▀
█─▀─█─█─█──▄─██▀─█──█─█▀█─█▀█──█───█──█───█▀▀──▀▄
▀───▀─▀──▀▀──▀─▀──▀▀──▀▀──▀─▀──▀───▀──▀▀▀─▀▀▀─▀▀─
";


        $particle2 = new FloatingTextParticle($pos,$text,$title);
        $this->plugin->getServer()->getDefaultLevel()->addParticle($particle2,[$player]);


        $pos = new Vector3(-12,7,0.5);


        $iPlayer->setInGame(false);

        $playerName = strtolower($player->getName());
        if(!isset($this->plugin->playerData[$playerName])){
            $this->plugin->playerData[$playerName] = $this->plugin->getData($player);
            if($this->plugin->playerData[$playerName]["miniBattleVip"] == 1){
                $this->plugin->vips[$playerName] = 1;
                $iPlayer->setVip(1);

            }

            if($this->plugin->playerData[$playerName]["isYoutuber"] == 1){
                $this->plugin->vips[$playerName] = 0;
                $iPlayer->setVip(0);
            }

            if($this->plugin->playerData[$playerName]["allVip"] == 1){
                $this->plugin->vips[$playerName] = 3;
                $iPlayer->setVip(3);

            }
        }else{

            $this->plugin->playerData[$playerName] = $this->plugin->getData($player);
            if($this->plugin->playerData[$playerName]["miniBattleVip"] == 1){
                $this->plugin->vips[$playerName] = 1;
                $iPlayer->setVip(1);

            }

            if($this->plugin->playerData[$playerName]["isYoutuber"] == 1){
                $this->plugin->vips[$playerName] = 0;
                $iPlayer->setVip(0);
            }

            if($this->plugin->playerData[$playerName]["allVip"] == 1){
                $this->plugin->vips[$playerName] = 3;
                $iPlayer->setVip(3);

            }



        }




        $player->teleport($this->plugin->getServer()->getDefaultLevel()->getSpawnLocation());
       // $this->getOwner()->getServer()->getScheduler()->scheduleDelayedTask(new teleportPlayerTask($this->plugin, $event->getPlayer()), 15);
        $iPlayer->setInGame(false);
        $event->setJoinMessage(null);
        $player->getInventory()->clearAll();
        $player->getInventory()->sendContents($player);
        $player->getInventory()->sendArmorContents($player);



        $player->setHealth(20);
        $player->setFood(20);
        $player->setFoodEnabled(false);

        $player->removeAllEffects();

        if (isset($this->plugin->playerData[$event->getPlayer()->getName()]) == false) {
            $data = $this->plugin->getData($event->getPlayer());
            $this->plugin->playerData[$player->getName()] = $data;
            if (isset($data["playerName"]) and $data["playerName"] != "") {
                $this->plugin->playerKits[$event->getPlayer()->getName()] = $data["playerMicroKit"];
            } else {
                $this->plugin->link->query("INSERT INTO data (playerName) VALUES ('" . $event->getPlayer()->getName() . "')");
                $this->plugin->playerKits[$event->getPlayer()->getName()] = $data["playerMicroKit"];
            }

        }


        if ($player->getName() == "Guillaume351") {
            $player->setDisplayName(TextFormat::RED . "[Owner] " . $event->getPlayer()->getName());


            $player->setNameTag($iPlayer->getDisplayName());

            $this->plugin->getServer()->broadcastMessage(TextFormat::GREEN . $player->getDisplayName() . " joined the game !");
        }

        $this->plugin->regenerateDisplayName($player);
        $data = $this->plugin->playerData[$player->getName()];
        $kits = "";
        if($data["hasKitClimber"]){
            $kits .= "climber\n";
        }
        if($data["hasKitArrow"]){
            $kits .= "arrow\n";
        }
        if($data["hasKitMobility"]){
            $kits .= "mobility\n";
        }
        if($data["hasKitKnockback"]){
            $kits .= "knockback\n";
        }

        if($kits == ""){
            $kits = "None\n";
        }
        $player->kits = $kits;



        $player->coins = $data["playerCoins"];

        $pos = new Vector3(-12,10,0.5);
        $text = "Welcome on Cookie Build !\nYour coins : ". TextFormat::YELLOW.$this->plugin->playerData[$player->getName()]["playerCoins"].
            TextFormat::GREEN."\nYour kits :\n".TextFormat::YELLOW.$kits.TextFormat::GREEN."Selected kit :\n".TextFormat::YELLOW.$data["playerMicroKit"];
        $title = TextFormat::GREEN."Hello ".$player->getDisplayName().TextFormat::RESET;

        $particle = new FloatingTextParticle($pos,$text,$title);
        $this->plugin->getServer()->getDefaultLevel()->addParticle($particle,[$player]);
        $player->setStatParticle($particle);


        if ($this->plugin->lock == true) {
            $player->kick(TextFormat::RED . "Server is updating.",false);
        }

        foreach ($this->plugin->getServer()->getDefaultLevel()->getPlayers() as $p) {

                $player->sendPopup(TextFormat::YELLOW . $player->getName() . " joined the game !");

        }
        $player->sendMessage(TextFormat::GREEN."Welcome on ".TextFormat::AQUA."Cookie ". TextFormat::YELLOW ."Build". TextFormat::GREEN." MicroBattles !");
       $mob = $this->plugin->playMob;
        if($mob instanceof Zombie)
        {
            $mob->spawnTo($player);
        }
       
`

**Comment by PeratX** [comment]
You don;t need to spwan to a player manualy.

**Comment by Guillaume351** [comment]
I tried to spawn manually because it didn't work with spawnToAll

**Comment by PeratX** [comment]
check your spawn position
