### ISSUE TITLE
Item Frame protection

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#825]
#### Issue description

Using iProtector, Item frames aren't protected. Many servers use iProtector to protect areas. Can you make item frames compatible with iProtector areas?
#### OS and versions

* Genisys: 1.1dev (API 1.7.2)
* PHP: 7.0.5
* OS: Ubuntu 14 (64-bit)

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
I think you should send this issue to the plugins' antuor instead of us.

**Comment by gaoyichuan** [comment]
Report the issue to the plugin's developer
