### ISSUE TITLE
Genisys ticks

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#828]
#### Issue description

When there is a lot of glow stone or monster spawners in a specific area, the area starts to tick-lag.
#### Steps to reproduce the issue

Spawn a lot of glowstone or monster spawner (not mobs, just the spawner!)
#### OS and versions

* Genisys: 1.7.2
* PHP: 7.0.5
* OS: Ubuntu 14.04 (64-bit)

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Closing for invalid version.

**Comment by gaoyichuan** [comment]
What's 1.7.2?

**Comment by PeratX** [comment]
GeniAPI Version
