### ISSUE TITLE
Console: Item Iron Hoe (292:221)x1

### ISSUE THREAD

**Issue by markkrueg** [iTXTech/Genisys#835]
#### Issue description
Console is filled with Iron Hoe messages even though debug is set to 1. Maybe some debug code got left in by accident?

#### Steps to reproduce the issue
Use an Iron Hoe to till a grass block into farmland. Message below is printed in console.

#### OS and versions
* Genisys: build from source as of commit 8582c36
(likely existed before this commit)
* PHP: 7.0.3
* OS: Ubuntu Server 14.04.4 LTS

#### Crashdump, backtrace or other files
The following appears in console. It doesn't exist on a separate "info" log line. It just appears inserted into the console. I do not believe it is being written to the server.log file.
```
Item Iron Hoe (292:221)x1Item Iron Hoe (292:222)x1Item Iron Hoe (292:222)x1Item Iron Hoe (292:223)x1Item Iron Hoe (292:223)x1Item Iron Hoe (292:224)x1Item Iron Hoe (292:224)x1Item Iron Hoe (292:225)x1Item Iron Hoe (292:225)x1Item Iron Hoe (292:226)x1Item Iron Hoe (292:226)x1Item Iron Hoe (292:227)x1
```

**Comment by dog194** [comment]
oh. maybe i forget to delet something. i will check tomorrow. It 2a.m. now.XD

**Comment by dog194** [comment]
emm..Sorry for this. I add it when rewrite tools' durability system but forget to delete. :(

**Comment by SurvivalHive** [comment]
we are humons... its ok ;) xD
