### ISSUE TITLE
Either Segfault on Main OS or instant exit via Docker

### ISSUE THREAD

**Issue by Renual1337** [iTXTech/Genisys#837]
# Issue Description

Hello guys,

On our virtual machines everything is fine, but we're having an issue with Genysis running inside Docker or directly inside the Host OS.

# How to reproduce

Well we've included a screenshot/gif video down below, it's litterally just running it.

# Configuration
PHP Version: 7
Host OS: CentOS 7.2 64 bit
Ram: 64GB ram
Processor: Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz

Basically when we run it inside Docker it instantly exits out;

https://gyazo.com/1886c5c6e72ce403ada7aa714e90605a and as you can see near the end when i check which ports are bound, 19132 isn't bound either.

When you go in the server.log theres nothing special there, only what's already printed in the cmd. No crash reports either.

When we run it directly on the host OS it simply does the same thing and near the end it Segmentation fault's.

**Comment by PeratX** [comment]
Yes. Only happens on CPUs with super-threading. (mainly Xeon E5)
Solution: turn off super-threading.
This is a bug of php.
Report at bugs.php.net

**Comment by Renual1337** [comment]
Thanks for responding so quickly.

Does that not impose significant performance penalties? (To disable it)

Is there a workaround?

**Comment by PeratX** [comment]
I don't know

**Comment by Renual1337** [comment]
Hi,

We've now disabled it on a machine and it does get through the boot stage now but it never gets to binding. It simply says [10:56:13] [Server thread/INFO]: Done (0.275s)! For help, type "help" or "?" at the end but a netstat shows that its not actually bound.

**Comment by ishitatsuyuki** [comment]
PHP sucks. pthreads sucks. It's a upstream bug so we can do nothing with it.

**Comment by Renual1337** [comment]
Hi, 

Thanks for getting back to us. What do you suggest we do in the meantime? We've already disabled HyperThreading with no results.

**Comment by ishitatsuyuki** [comment]
What's your docker run command line? I think you didn't exposed ports. See the documentation for details.

**Comment by Renual1337** [comment]
We ran it directly now, without docker.

**Comment by ishitatsuyuki** [comment]
Can you check if Genisys is still running (possibly with `Genisys> ` prompt) or crashed and get back into a shell?

**Comment by Renual1337** [comment]
Hi I just tried with Docker aswell, same problem.

If you'd like I can PM you the machine info and you can take a look for yourself.

**Comment by ishitatsuyuki** [comment]
I know that it may crash a few times but after at most 20 tries it will at least start correctly once.

**Comment by Renual1337** [comment]
Hi,

I haven't really been able to get it to boot through like ever on this machine.

**Comment by ishitatsuyuki** [comment]
Let me ask again: does it exits or runs after `Done!`?
If you're not sure, take a screenshot after the following message.

**Comment by Renual1337** [comment]
It doesn't exit, it just sits there. I've verified that it's not bound to a port by opening another shell session and using netstat

**Comment by ishitatsuyuki** [comment]
You have something wrong with your network. If it's sitting there, either your netstat is not checking UDP or you have specified wrong port.

**Comment by Renual1337** [comment]
Hi there,

It's litterally a cleanly installed at OVH.com, I'm pretty sure the machine itself is fine. Would you like to take a look if I send you the info?

**Comment by ishitatsuyuki** [comment]
Seems you're running the hard-use-firewall CentOS. Have you configured firewalld properly? Can you try our rival's software?

**Comment by Renual1337** [comment]
PocketMine gives the same problems. And no we're running Ubuntu.

**Comment by ishitatsuyuki** [comment]
I don't think netstat can show UDP. Can you try a real client and check your firewall again?

**Comment by Renual1337** [comment]
Hey,

Netstat does in fact display udp listeners, regardless ive tried to connect
but with no success. Theres no firewall running whatsoever. Would you
please just take a look if I give you a root login for a machine, its much
easier if you can see it for yourself.

**Comment by ishitatsuyuki** [comment]
If you don't mind, add this public key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkXf4hmqH+IRU6ET9d0bxCpyVrzPP/zyhyGlDee9tJNmq1yAEglkEcR/5E/jEIlhqOadoEZaaB0KQtWM+LtCq1pjNi5q8stK37Ygu04zxQnIwn9PkYONWS7HybUjbQzrQ1gdgSNzx+FJyvlLrxkFhaFditFG0J7hY/gkc7iX2bx8dIAB2aMlI9QHLHI1wA6ZRXkFLTVhtNuJL9A8tcy2T9D3YK5X+ngjlL2i2HIscWFiEERHtLul40d5Ctb7mYBpyKHtbldY2AaB3+8RqJz3RpafVJVDaD8F8pZuUMsn3COeqSWSYGZHOhjnp6sObrmMdnQyHXQLyJ+cJ3t3jog6NT ishitatsuyuki@X1Yoga.local
```

**Comment by Renual1337** [comment]
Yep it's done, IP is

149.56.107.42

I apologize for the delay, was asleep. I quickly cleaned out some files too
so go ahead and try, the machine is non-production so you can do whatever
you need to try.

**Comment by ishitatsuyuki** [comment]
I was able to run and connect. You seems to misconfigured Docker.

When you're changing options, destroy the original one by docker rm.

**Comment by Renual1337** [comment]
Thats pretty odd, I copied the command on the docker instruction page and
used the newest build on GitLab.

Let me confirm that it works, just a minute please.

**Comment by ishitatsuyuki** [comment]
I have stopped the container: start it by the command written on the wiki.
You can delete my key now.

**Comment by Renual1337** [comment]
Confirmed that works indeed. Did you change anything in the config or did
it just work?

**Comment by ishitatsuyuki** [comment]
I just removed your old container and started a new one with the instructions I have written on wiki.

**Comment by Renual1337** [comment]
That's pretty interesting, considering I copied those exact same
instructions and it didn't work for me.

I must've done something wrong somewhere. It basically said it was done but
it kind of looked like it was exiting out right after but it wasn't
actually because if I typed "stop" it'd exit then.

Are there any common mistakes made by people that could lead to this?
