### ISSUE TITLE
Question about /bancidbyname, /bancid

### ISSUE THREAD

**Issue by Naniiii** [iTXTech/Genisys#839]
Hello. I want to ask something about the /bancid command.  Even though I managed to ban some people yesterday they found a way to bypass the ban and log in again. Is the command defective or the client id randomly changes? And how they are changing their client IDs? Thank you.

**Comment by dog194** [comment]
use /bancidbyname

**Comment by Naniiii** [comment]
... -.-. You didn't even read my question. The commands are placed in the title which means *I already know them*. The question is not about *How to use them*. It is about *How are they escaping the CID ban".

**Comment by PeratX** [comment]
/sdcard/games/com.mojang/clientId.txt

**Comment by Naniiii** [comment]
And when you change it your client id changes too? It is that simple?

**Comment by Naniiii** [comment]
I knew there was a simple way to change that. People had always told me that it was a *device ban* but never believed it because you simply can't do that.

**Comment by Naniiii** [comment]
Thanks.
