### ISSUE TITLE
HELP on /fill command

### ISSUE THREAD

**Issue by InstaGamer** [iTXTech/Genisys#840]
Hi! Could you help me on how to use /fill command. By the way LEET is using Genisys and its so cool less laggy and has a lot of features like redstone, potions, minecart, rails, boats, and more. Keep up the good work Genisys Team hope in the future you will add a lot of stuffs and commands like /powertool command and all items in MCPE.

**Comment by ishitatsuyuki** [comment]
Bye! No support requests in issue tracker, unless it's a bug or you have a feature request.

**Comment by InstaGamer** [comment]
How to use /fill command?
