### ISSUE TITLE
MonsterSpawner Lag

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#849]
I use the latest build. I run a script that downloads master.zip, extracts it and etc. I also confirmed it's the latest one.

Monster Spawners have been causing alot of lag on my server lately. This is a very old issue. Could you please recheck the MonsterSpawner.php tile?

![we](https://cloud.githubusercontent.com/assets/18363310/14762418/5f8bd5bc-0982-11e6-94df-20c587ac1cca.PNG)

**Comment by Muqsit** [comment]
I can confirm... :3
http://timings.aikar.co/?url=16006935

**Comment by CLiu13** [comment]
Same here.

**Comment by gaoyichuan** [comment]
Please follow the template next time
