### ISSUE TITLE
Server Killed for No Reason

### ISSUE THREAD

**Issue by atTheDisco** [iTXTech/Genisys#851]
#### Issue description
The shutdown of the server without error

#### Steps to reproduce the issue
After 5-6 minutes, the server itself is shutting down for no reason.. and not just "Killed" in the console it says. I do not understand the problem. For 3-4 days I am receiving the same error

#### OS and versions

* Genisys: 1.1dev #0 [Protocol 46; API 2.0.0]
* PHP: 7.0.3
* OS: Linux

#### Crashdump, backtrace or other files (not crash dump, but error)
```
[14:21:29] [Server thread/INFO]: » E***1 => GG!
[14:21:32] [Server thread/INFO]: m***a**p***R[/78.***.167.***:12660] logged out due to client disconnect
[14:21:35] [Server thread/INFO]: a****li[/88.***.27.***:19132] [ClientID: 1263822651601808384] logged in with entity id 449 at (WarsLobi, 1403, 41, 82)
[14:21:36] [Server thread/INFO]: m***a***ro**[/78.***.167.***:12660] [ClientID: -6368652571898206184] logged in with entity id 452 at (WarsLobi, 1403, 41, 82)
[14:21:42] [Server thread/INFO]: M*Mi***S[/88.***.76.***:19132] logged out due to client disconnect
Killed
[root@h42 server]#
```

**Comment by Muqsit** [comment]
Send your plugins. This doesn't happen on my server :/

**Comment by atTheDisco** [comment]
```
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.13.0, 2.0.0
BanClient 1.0.1 by luca28pet for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
SurvivalGamesV3 3.0.3 by Imagical for API(s) 1.0.0, 2.0.0, 3.0.0
TAGBlock 0.8-Alpha by ifteam for API(s) 1.13.0, 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
AntiSpam 1.0 by MamayAdesu for API(s) 1.2.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
MapReset 1.0.0 by OyunGG for API(s) 1.0.0
ChatFilter 1.1 by onebone for API(s) 1.1.0, 1.2.0, 1.2.1
Lightning 0.4 by Rexius for API(s) 1.13.0
NoAdvertisingPE 1.0.0 by Vaivez66 for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ChatLogin 1.4 by EvolSoft for API(s) 1.11.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
Slapper 1.2.9.3 by jojoe77777 for API(s) 1.12.0
DevHub 1 by Ferhat B. for API(s) 1.1.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0
```

**Comment by PeratX** [comment]
This is after CommandReader update @ishitatsuyuki

**Comment by ishitatsuyuki** [comment]
@PeratX at least not my fault: either this is an old issue or pthreads has further bugs

**Comment by atTheDisco** [comment]
so? How do I fix the error?

**Comment by Muqsit** [comment]
Download an older version

**Comment by Muqsit** [comment]
Download the latest version

**Comment by atTheDisco** [comment]
I've already downloaded the latest version, but still the problem continues...

```
[17:12:05] [Server thread/INFO]: » K***rDoc**r => sdlan
<server> K**nR* issued server command: /huh
[17:12:16] [Server thread/INFO]: K***rDoc**r[/78.***.5*.*:19132] logged out due to client disconnect
<server> K**nR* issued server command: /hub
[17:12:20] [Server thread/NOTICE]: Player data not found for "jinn", creating new profile
[17:12:20] [Server thread/INFO]: jinn[/88.***.2*4.***:19132] [ClientID: 6584544644690589632] logged in with entity id 346 at (WarsLobi, 1403, 41, 82)
[17:12:26] [Server thread/INFO]: KillerDoctor[/**.***.54.*:19132] [ClientID: -6436487752330267960] logged in with entity id 365 at (WarsLobi, 1403, 41, 82)
[17:12:30] [Server thread/INFO]: » m***afa_*G_***al => kit nasıl alinir
Killed
[root@h42 server]#
```

**Comment by Muqsit** [comment]
The bug never happened on my server. Maybe it's one of your plugin's fault?

**Comment by atTheDisco** [comment]
I don't know may be. How do I know which plugin? I don't get any crash without.

**Comment by Muqsit** [comment]
I'm assuming it's:
MapReset 1.0.0 by OyunGG for API(s) 1.0.0

**Comment by atTheDisco** [comment]
I uninstalled but still the problem continues. Current plugins;
`
EssentialsPE v1.1.3, BanClient v1.0.1, ManyWorlds v2.0.3, AlwaysSpawn v2.2.2, VIPSlots v0.0.4, PurePerms v1.2.2, TAGBlock v0.8-Alpha, EconomyAPI v2.0.9, AntiSpam v1.0, TimeCommander v2, ClearLagg v1.1.0, ServerAuth v2.13, ChatFilter v1.1, Lightning v0.4, NoAdvertisingPE v1.0.0, Broadcaster v1.16, ChatLogin v1.4, CustomAlerts v1.5, Slapper v1.2.9.3, DevHub v1, SurvivalGamesV3 3.0.3, ConsoleLogger v1.0.2, PureChat v1.3.3, BattleKits v1.0.4
`

**Comment by Muqsit** [comment]
It's one of these:
DevHub v1
ChatLogin v1.4
ChatFilter v1.1
BanClient v1.0.1

**Comment by atTheDisco** [comment]
Again I uninstalled but still the problem continues. I have to delete what other plugins? This is a very frustrating situation...

**Comment by Muqsit** [comment]
I think you're using an old version of Genisys.

**Comment by atTheDisco** [comment]
No, I downloaded the latest source. There must be some other solution for this.

**Comment by PeratX** [comment]
Genisys will not kill itself.It must be caused by some external programs.
