### ISSUE TITLE
Command line hangs at "Stopping other threads" when using /stop

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#852]
EDIT: Enabling debug messages reveals that it hangs at "Stopping CommandReader thread"

#### Issue description
Genisys 1.1dev-326 Ikaros - The command line hangs forever at "Stopping other threads" when /stop is used.

#### Steps to reproduce the issue
Use /stop to kill the server

#### OS and versions
* Genisys: 1.1dev-326 Ikaros
* PHP: 7.0.4
* OS: Windows 10

**Comment by ishitatsuyuki** [comment]
Hmm... Windows is too crappy on it's console API. Currently it's hard to workaround this in PHP.

Note that you can exit by doing a Enter.

**Comment by PeratX** [comment]
This is your problem @ishitatsuyuki

**Comment by GlitchPlayer** [comment]
Try manually pressing Enter button
