### ISSUE TITLE
Corrupt map?

### ISSUE THREAD

**Issue by beetree** [iTXTech/Genisys#853]
Any idea what is causing this crash: http://leet.cc/crashdumps/crash1.log

Thanks!

/b3

**Comment by beetree** [comment]
Here is a description of a potential root cause: http://forum.leet.cc/topic/13835/found-source-of-crashes-ios

**Comment by Muqsit** [comment]
The crashdump has got this:
`Error: Human must have a valid skin set`

**Comment by beetree** [comment]
Yes, what does that mean? Someone has a faulty skin? The server shouldn't crash from that though, right? I mean, it's hard to control who tries to connect to the server...

**Comment by PeratX** [comment]
Check NPC Plugins
