### ISSUE TITLE
Redstone enhancement

### ISSUE THREAD

**Issue by gizanopatrica** [iTXTech/Genisys#854]
#### Issue description

Hello! I'm a new Genisys user and I'm having some trouble with redstone. I'm trying to build a circuit like this, and it works completely fine in MCPE:
![image](https://cloud.githubusercontent.com/assets/18654806/14776579/bc903030-0b0a-11e6-8814-bbb484edc8a3.png)
But when I build it in Genisys, it doesn't work, and comes out like this:
![image](https://cloud.githubusercontent.com/assets/18654806/14776600/d67f9620-0b0a-11e6-8261-6cb5441a40f6.png)
#### Steps to reproduce the issue

Just build what I built in the picture!
#### OS and versions

- Genisys: latest source(I run it from the source)
- PHP: 7.0.2
- OS: Ubuntu 15.04
#### Crashdump, backtrace or other files

```
Paste here
```

**Comment by GlitchPlayer** [comment]
Genisys is not exactly as MCPE. Though genisys is not accurate on redstone.

**Comment by dog194** [comment]
The most developers of Genisys are student now. So until summer holiday they donot have much time to develop. And Genisys is not exactly as MCPE. All the items's function need the develpers to write and make it can be used. So this issue may be done in the future.

**Comment by Muqsit** [comment]
Pull requests are appreciated. If you know a way of fixing this, let us know it!

**Comment by PeratX** [comment]
Will have time in July

**Comment by AryToNeX** [comment]
Btw this is not the only redstone-related problem.
A stupid problem is that you can't activate a redstone lamp with a lever activated in the bottom side of the lamp.

**Comment by gaoyichuan** [comment]
Have you enabled redstone in genisys.yml?

**Comment by GlitchPlayer** [comment]
Also powered and activator rails do not activate when redstone activates them

**Comment by Nitrofish** [comment]
Yeah, can't seem to use redstone torches to activate powered rails which I need for the multi level mines I have created.

**Comment by CubeFromSpace** [comment]
It involves PC's old Redstone rendering as you couldn't go down through one step if it was covered

**Comment by dktapps** [comment]
Hoppers will be added in the very near future.

**Comment by Yoyu666** [comment]
@dktapps  soon XD

**Comment by CubeFromSpace** [comment]
This might explain better what I said earlier:
http://minecraft.gamepedia.com/Tutorials/Quasi-connectivity

**Comment by CubeFromSpace** [comment]
Also note that it says that it isn't in PE, so what likely happened is that the developers added something from PC into a PE server. I hope that I actually helped.

**Comment by XFuryMCPE** [comment]
Bump? Lol
