### ISSUE TITLE
bug start Revert "Improve command reader" 

### ISSUE THREAD

**Issue by dansafran** [iTXTech/Genisys#855]
Warning: zlib_decode(): data error in phar://C:/Users/Dansafran/Desktop/jeux/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/nbt/NBT.php on line 473

Notice: Undefined property: pocketmine\nbt\tag\EndTag::$Data in phar://C:/Users/Dansafran/Desktop/jeux/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/level/format/generic/BaseLevelProvider.php on line 52

Server has stopped
zend_mm_heap corrupted
bin\php\php.exe: Exit 1

![Uploading IMG_0552.JPG…]() 

Genisys:1.1dev-326 Ikaros

Windows 8 

PHP: 7.0.0

**Comment by ishitatsuyuki** [comment]
Don't change the title in a foolish manner.

**Comment by ishitatsuyuki** [comment]
Closing: your map is broken.
