### ISSUE TITLE
questing

### ISSUE THREAD

**Issue by seetch** [iTXTech/Genisys#862]
1. Hello, please add that regardless of the setting OP players to do these things!

```
#Set if enable limited creative (cannot drop item, cannot interact Chests and so on)
 limited-creative: false
```

2) Where can I find this file?
```
 #Choose if read recipes from json
 recipes-from-json: false
```

**Comment by Driesboy** [comment]
you have set it to false and than the file dont generate

**Comment by seetch** [comment]
@Driesboy What did you mean?

**Comment by Muqsit** [comment]
You can edit genisys.yml to your liking.

**Comment by gaoyichuan** [comment]
As for 2), the file is
`
src/pocketmine/resources/recipes.json
`
