### ISSUE TITLE
Farms don't grow.

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#863]
I reported this issue awhile ago and it got closed. but it hasn't been fixed.

#### Issue description
farms don't grow at all.
#### Steps to reproduce the issue
plant seed. Nothing happens. Bone meal works on wheat only.
#### OS and versions
* Genisys: Genisys_1.1dev-331.phar
* PHP: 7
* OS: Linux

**Comment by Skull3x** [comment]
I can take care of that for you, search organization and go to users. Then
view all the plugin's they've posted / created. They have a few farm
related plugin's but you'll have to use for example : bool or : string
depending on what's in the code

**Comment by Skull3x** [comment]
http://github.com/organization

**Comment by Tolo0** [comment]
but isn't this a genisys build issue?  so a plugin shouldn't be needed 😕

**Comment by Skull3x** [comment]
Eh
​

**Comment by PeratX** [comment]
Check your pocketmine.yml chunk-ticking.per-tick and radius. They should be a non-zero number.

**Comment by Tolo0** [comment]
but that isn't a fix. Pumpkins and melons should grow when using Bone meal. but they don't.  and changing the ticks won't solve that.

**Comment by dog194** [comment]
@Tolo0 Bone meal only make Pumpkins stem mrlong stem and other crops grop. Make sure the setting "chunk-ticking.per-tick" > 0. Tested crops will grow auto.

**Comment by Tolo0** [comment]
like that? 


chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 10
 #Radius of chunks around a player to tick
 tick-radius: 10
 light-updates: false
 clear-tick-list: true

**Comment by dog194** [comment]
right

**Comment by Tolo0** [comment]
it worked. Sorry for guys 😅
