### ISSUE TITLE
Chunks don't load 

### ISSUE THREAD

**Issue by Xlecronia** [iTXTech/Genisys#865]
When a player joins the game, the chunks don't load and is stuck (can't move) in void. 
Only occurs to a few players. 

This is my version -> This server is running Genisys 1.1dev-00cf8a4 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.x alpha (protocol version 46)

**Comment by GlitchPlayer** [comment]
00cf8a4? Are you using latest version?

**Comment by ishitatsuyuki** [comment]
Outdated.

**Comment by Muqsit** [comment]
*Only occurs to a few players*
Because of their / host's network connection. Genisys loads chunks really fast. Try checking your ping!

**Comment by Xlecronia** [comment]
Alright thanks!
