### ISSUE TITLE
0.14.2 update

### ISSUE THREAD

**Issue by beetree** [iTXTech/Genisys#869]
Assuming you're already working on it. Need an urgent update to support 0.14.2.

Thanks!

**Comment by Leo3418** [comment]
Because 0.14.2 implemented some new protocols/API or something else (probably a preparation for Realms), even if you add protocol version 60 for 0.14.2 in source, players are not able to place or break blocks. It seems that this version upgrade requires more effort. So don't hurry.

**Comment by Driesboy** [comment]
I have already contact mojang

**Comment by CLiu13** [comment]
https://github.com/Nukkit/Nukkit/commit/8f18813820c241190f3ba18d54dc1119cb89303d This might help alot!

**Comment by andrew33212** [comment]
Ok so when are we looking at for this new update can u tell how many days this will take around ???

**Comment by GlitchPlayer** [comment]
After network protocol have been known

**Comment by CLiu13** [comment]
Network protocol is already known, take a look at the commit I posted earlier from Intyre.

**Comment by GlitchPlayer** [comment]
That's nice, so the update will be expecting to be released this day?

**Comment by CLiu13** [comment]
I guess I can try to make a PR!

**Comment by GlitchPlayer** [comment]
That's good
@CLiu13

**Comment by GlitchPlayer** [comment]
@CLiu13 Can you compile it into phar so I can test it?

**Comment by CLiu13** [comment]
I cannot compile into a .phar at the moment; however, if you check out https://github.com/CLiu13/Genisys   you can just take the src folder and load the server from that.

**Comment by beetree** [comment]
Confirmed working. A little bit buggy with hotbar, but works well enough. Putting into production.

Thanks @CLiu13 . I owe you big time! Please reach out to info (at) leet (dot...) cc. Would love to get to know you better...!

/b3

**Comment by CLiu13** [comment]
Email sent! Glad to hear that the fix worked, but all credit goes to @Intyre and the other developers who implemented it first. :)
