### ISSUE TITLE
I can not start the server

### ISSUE THREAD

**Issue by MrDoni98** [iTXTech/Genisys#87]
./start.sh
Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
[11:53:32] [Server thread/CRITICAL]: Unable to find the Weakref extension.
[11:53:32] [Server thread/CRITICAL]: Please use the installer provided on the homepage, or recompile PHP again.

**Comment by MrDoni98** [comment]
i use https://github.com/iTXTech/PHP-Genisys

**Comment by SleepSpace9** [comment]
In your **php.ini** (located in .../php7/bin) try to provide an absolute path to the file *opcache.so*.

So replace the following line:
zend_extension=opcache.so

with:
zend_extension=*???*/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so
(where *???* must be replaced with the absolute path to your php7 directory)
