### ISSUE TITLE
0.14.2 can't break and place blocks

### ISSUE THREAD

**Issue by jerryzooyoyo** [iTXTech/Genisys#870]
#### Issue description

As you see, after updating my cellphone's MCPE to 0.14.2, I couldn't break or place any block and item. Even when I tried to run a server without any plugin, I still couldn't break and place blocks.

#### Steps to reproduce the issue

1. -->Use the protocol 60.
2. -->Use MCPE 0.14.2 and join the server.
3. -->Try to place or break any block. Or try to touch any block.

#### OS and versions

* Genisys: [http://github.com/iTXTech/Genisys/tree/a97a591d7e7ed8317a7af3aac9c864aeb0fea78a](url)

I am using the source code to run. Latest version.
* PHP: php 7.0.4  (Using this binary) [http://github.com/iTXTech/PHP-Genisys](url)
* OS: Windows Server 2012

#### Crashdump, backtrace or other files

![478735](https://cloud.githubusercontent.com/assets/16357120/14854403/37a6fa66-0cc2-11e6-91ee-965c8227ce39.jpg)

**Comment by ishitatsuyuki** [comment]
0.14.2 is unsupported. Duplicate.
