### ISSUE TITLE
chunk not loading 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#871]
iv been getting reports from some players that when they log on. they can't see anything. like the chunks aren't loading around them. but on other servers it works fine. is they a way I can fix this?

This server is running Genisys 1.1dev "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.x alpha (protocol version 46)

**Comment by ishitatsuyuki** [comment]
Your version is 100% outdated. Goodbye.

**Comment by Tolo0** [comment]
I updated to the latest version and still having the same problem

**Comment by Muqsit** [comment]
It depends on your bandwidth speed, RAM, CPU cores and processor

**Comment by Tolo0** [comment]
on the client side? or the server software?

**Comment by Muqsit** [comment]
On both the sides

**Comment by Tolo0** [comment]
well it's only like 1/10 that have reported this problem. so I guess it's on he's end. thanks for your time. and for not being rude. I appreciate it.

**Comment by Muqsit** [comment]
lol
