### ISSUE TITLE
Disconected:timeout

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#875]
Very often players are disconnected from the server due to timeout .
The more players , the more such timeouts.

In console:

[22:08:18] [Server thread/INFO]: lichner[/93.77.77.52:19132] отключился: timeout

* Genisys: 1.1 335 build
* PHP: 7
* OS: windows 7

**Comment by XShockinFireX** [comment]
this happens to me alot.

**Comment by PeratX** [comment]
This is related to network(unstable)
