### ISSUE TITLE
Generic Reason

### ISSUE THREAD

**Issue by FIRERO** [iTXTech/Genisys#883]
Hi, I have a problem. I start my server with putty. I enter screen -S g then cd g and ./start.sh When I'm in console, the server work, when I go out from console, the server doesnt work. After then I do this " I enter screen -S g then cd g and ./start.sh" but the server doesnt work and there is a string with error RakLib in the console.  After reboot vds... I Do this "I enter screen -S g then cd g and ./start.sh When I'm in console, the server work, when I go out from console, the server doesnt work"

**Comment by ishitatsuyuki** [comment]
use tmux. closing stdin will result in terminate.

**Comment by gaoyichuan** [comment]
I think it's because that your port has already be binded, so ranklib can't bind on that port
