### ISSUE TITLE
SendTip() doesn't Work.

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#886]
#### OS and versions

* Genisys:last version
* PHP:7
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by DavidJBrockway** [comment]
can i have more info plz

**Comment by MineBuilderFR** [comment]
When i use $p->sendTip(); in MCPE 0.14.2 , It doesn't Work . In 0.14.1 It Work

**Comment by SleepSpace9** [comment]
Yes, confirmed. No error message, but no message showed as tip (you only see the missing message at the server console).

**Comment by CLiu13** [comment]
Popups seem to have taken the place of tips.

**Comment by MineBuilderFR** [comment]
oh no .. It is possible to send a popup at the same time ? EX:

$p-> sendPopup ( "test1");
$p-> sendMesage ( "\ntest2"); ? 

( For two line at the same time  ? )

**Comment by MineBuilderFR** [comment]
Ex : 
$p->sendPopup('test1");
$p->sendPopup("\ntest2"); *

**Comment by SleepSpace9** [comment]
I think there has changed something [here](https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/network/protocol/TextPacket.php).

**Comment by PeratX** [comment]
Please do not report issue related to protocol changes

**Comment by MineBuilderFR** [comment]
Yes , except that when I joined the server in 0.14.1 TIP appears, but not in 0.14.2 :/

**Comment by MineBuilderFR** [comment]
Ok Peratx

**Comment by Muqsit** [comment]
God...I hate 0.14.2
