### ISSUE TITLE
MCPE App Crashing Upon Join

### ISSUE THREAD

**Issue by DALTONTASTIC** [iTXTech/Genisys#887]
#### OS and versions

* Genisys: #337
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

Yo fam wtf is happening? I can't even join my Genisys server because my MCPE app either crashes as soon as I tap connect, or waits until I'm connected for 0.0000001 seconds and then crashes. No errors in console or error log. For a little bit the 0.14.2 Genisys was working fine, and this issue only started occuring after I used a villager spawn egg to add 5 villagers to my map. I crashed while placing the third one and haven't been able to join ever since.

**Comment by Muqsit** [comment]
That shouldn't be happening!

![ew](https://cloud.githubusercontent.com/assets/15074389/14898156/10c542be-0d8e-11e6-965d-d04eb7087d84.PNG)

**Comment by DALTONTASTIC** [comment]
Are you using #337? That's the latest version I could find on Jenkins

**Comment by DavidJBrockway** [comment]
No it a player issue related to player data loading from server to app also it is mcpe new protocall and loading packets

**Comment by Muqsit** [comment]
Your player data is corrupted. This doesn't happen in fresh genisys

**Comment by DALTONTASTIC** [comment]
Well seeing as I cleared all player files and restarted the server without any resolution: your reply doesn't seem feasible.

**Comment by Thunder33345** [comment]
i suggest some protocol changes crashed mcpe

**Comment by ImagicalGamer** [comment]
Did Genisys update their protocols? I had the same issue before we updated the IM protocols

**Comment by DALTONTASTIC** [comment]
I reinstalled Minecraft and it fixed it. Maybe it's only a temporary solution we'll have to wait and see. The thing is that many people are getting the same bug as me.

**Comment by DALTONTASTIC** [comment]
Okay it's crashing again. Basically if you wanna play online reinstall MCPE before joining a server every single time.

**Comment by Muqsit** [comment]
No wonder why everyone hates 0.14.2 :/
So this issue isn't linked to Genisys right?

**Comment by DALTONTASTIC** [comment]
I'm guessing no, but maybe? It only happens on multiplayer and only on some servers.

**Comment by gaoyichuan** [comment]
villager bug, should be fixed
