### ISSUE TITLE
Anvils. :/ 

### ISSUE THREAD

**Issue by LordJoshie** [iTXTech/Genisys#888]
#### OS and versions

- Genisys: Yes (latest build)
- PHP: 7
- OS: I'm on Android... but this is for all. & I host off Ubuntu.
#### Crashdump, backtrace or other files

```
Paste here
```

Wow... this is interesting. these little things I gotta fill out to post an issue. 

Okay, I'm just wondering when Anvils will be improved ? Along with Enchanting. 
I'm currently using a modified version of MagicServer which allows SilkTouch & Fortune to work. & Fire Aspect & KnockBack. & many other Enchants.
But my issue is... using the anvil. it just ejects the materials I add to rename an item. & you can't combine tools to fix them :/  this is an issue. 
Not anything major, I'm  just curious when it'll be taken care of to improve the survival playability of the server 

hands down tho, Genisys is KEY.

**Comment by Jelly9912** [comment]
Hello, i have a question, how did you installed php7 on android device?

**Comment by LordJoshie** [comment]
lmfao.... whoops. no. I host on Ubuntu. I didn't understand wtf info
they're asking for.... so I just said, uh... I play on Android. but I host
off of Ubuntu.

make sense ?

**Comment by PeratX** [comment]
@Jelly9912 Check Genisys-Android
@LordJoshie Turn on allow-anvilandenchanttable in genisys.yml

**Comment by LordJoshie** [comment]
oh wow... durr. I know. I'm not stupid. It's just shotty a.f & spews it out
the back the anvil or enchant table. like... grr. not supposed to happen. :/

**Comment by Muqsit** [comment]
My server is hosted on Ubuntu but players can play on iOS, Android and Windows 10~ It makes sense.

Anvils will be fixed soon. If you know how to fix the issue, you can create a pull request!

**Comment by LordJoshie** [comment]
:(  I don't know how. it just pops em out. I have no clue why. doesn't show
on console. just...pops em out.

**Comment by Jelly9912** [comment]
@PeratX i know that this issue isn't about genisys on android, but i have strange error... just check it out
![screenshot_2016-04-29-11-20-19](https://cloud.githubusercontent.com/assets/13715380/14912466/c33e8f5e-0dfc-11e6-9dad-86f8f38ef334.png)

**Comment by PeratX** [comment]
ignore it

**Comment by LordJoshie** [comment]
awhh, sadface. but my renaming things on anvil don't work. wubwub.

**Comment by LordJoshie** [comment]
Also... Perat, I admire all the coding you do for Genisys. just so you know. I watch for updates everyday. :)  Genisys is my favorite thing on the internet. :P

**Comment by PeratX** [comment]
Thanks! I will try my best xD

**Comment by LordJoshie** [comment]
<3  XD  yayy  thanks !!

**Comment by gaoyichuan** [comment]
Invalid version, please write your Genisys number, latest is not a valid version

**Comment by TheAppleGamer** [comment]
Where did you get magic server? I can't seem to find it anywhere

**Comment by LordJoshie** [comment]
it's hard to find... but I have my ways.

uhm... I can share my copy.

I edited it.

-Fortune = Iron/Gold ore -> Ingots & more than normal.
-SilkTouch = Actually works. LOL.
& many other sweet enchants working.
all seem to work, except Thorns. :/ dunno why.

**Comment by TheAppleGamer** [comment]
@LordJoshie Could you share a copy please? The people on my server have been complaining about enchantments lol

**Comment by LordJoshie** [comment]
@gaoyichuan Uhm... well, the latest build. & it is valid, cuz it's not like it's fixed yet. derp...

**Comment by LordJoshie** [comment]
@TheAppleGamer add me on Kik. Dark.Miner

**Comment by TheAppleGamer** [comment]
@LordJoshie Alright let me boot up my Nvidia Shield

**Comment by LordJoshie** [comment]
Jellin... I use a Nexus5 for EVERYTHING. sucks so much, cuz I get lag when loading down with open apps... vnc, mc, shou.tv(cuz I also stream)

**Comment by PeratX** [comment]
Working on this these days :)

**Comment by LordJoshie** [comment]
<3  Thanks Perat  <3 Yayy!!

**Comment by PeratX** [comment]
@LordJoshie Done! Try it!

**Comment by LordJoshie** [comment]
Okay ! I'll run the latest build and report back :D

**Comment by LordJoshie** [comment]
I was able to rename, but nothing else. 
STILL THO. THAT'S HUGE  my players care more about naming than fixing    cuz I made a rank with /fixit :P

**Comment by PeratX** [comment]
OK, working on fix !

**Comment by LordJoshie** [comment]
in the build I ran, 0fa4 - I had a BAD memory issue. Only me in a test server and it was using up to a 1gb of memory. :$

**Comment by LordJoshie** [comment]
also, I was wondering about Enchanting Table glitches ... where it doesn't give what you expect, and it only gives single enchants  

And with Anvils, will you be able to combine enchants ?

**Comment by Muqsit** [comment]
@LordJoshie I've tested this with the latest build. Doesn't seem to happen. Enchantment tables work perfectly and are able to give multiple enchants.

**Comment by LordJoshie** [comment]
Yes ! I noticed also, the Enchant tables are much much better. amazing work
!  The anvils though, however, do not allow combination of items or
repairing of items. :(

But ! I know Genisys will likely get it done before anyone else, which is
awesome and why I choose Genisys <3 :D

Yay.
On Jul 2, 2016 9:38 PM, "Muqsit Rayyan" <notifications@github.com> wrote:

@LordJoshie <https://github.com/LordJoshie> I've tested this with the
latest build. Doesn't seem to happen. Enchantment tables work perfectly and
are able to give multiple enchants.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/iTXTech/Genisys/issues/888#issuecomment-230130437>, or mute
the thread
<https://github.com/notifications/unsubscribe/AQkQCP7SiWmnCUtx_xHoc5qV2b-HJKe2ks5qRxKggaJpZM4ISdH6>
.

**Comment by ParkChanSol** [comment]
Me, too

**Comment by dktapps** [comment]
I've made some progress into anvils on the Win10 branch. I'm sorry to say that anvils combining items/enchantments is going to be a challenge, because they require the server to send recipes. I _have_ however managed to fix the bug where they close immediately when you take items out of them.
