### ISSUE TITLE
Enchanting consume too much Player's exp

### ISSUE THREAD

**Issue by dog194** [iTXTech/Genisys#889]
#### Issue description

Enchanting consume too much Player's exp
#### Steps to reproduce the issue

Enchant on EnchantmentTable.
Login out
Login in
#### OS and versions

* Genisys:340?
* PHP:7
* OS:win

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by PeratX** [comment]
说好了你自己解决的呢

**Comment by dog194** [comment]
0.0 说好的我不知道这几个东西的结构哇

**Comment by dog194** [comment]
0.0 还是issue召唤比较有用 私聊窗口老是被无视

**Comment by dog194** [comment]
实测 扣了10倍 0.0

**Comment by PeratX** [comment]
你自己看看吧，我测试下了没错

**Comment by dog194** [comment]
使用341
新建角色
xp 角色 9000 直升60级 退出重新 还是60级
give 获得一个钻石镐 跟 青金石一组
使用附魔显示时运3 30级附魔。。。于是就扣了30级 剩下30级 还获得了一个效率5的稿子(迷。。) 退出重进还是30
再次give 15级附魔。。扣了15级。。。
所以你是直接按照等级扣了。。。应该扣 1 2 3 级。。你

**Comment by PeratX** [comment]
卧槽？好像真是这样

**Comment by dog194** [comment]
@PeratX  0.0 实测 扣除少1级    1级附魔不扣 2级附魔扣1级 3级附魔扣2级
同时 如果附魔结果产生两个属性。。只保留了后面一个 于是就把玩家本来要的属性刷掉了

**Comment by dog194** [comment]
少扣1级问题先改了 0.0 你看看 那个属性被刷掉的问题呗
