### ISSUE TITLE
Link for mcpe server 0.14.2?

### ISSUE THREAD

**Issue by MhikeiMPC** [iTXTech/Genisys#892]
MCPE 0.14.2 slipped through my eyes (never knew it came out) then i see alot of people has been kicked due to outdated server. Is there a link to the new Genisys 0.14.2? Only me and a few people that didnt update can join since we never updated to 0.14.2.

**Comment by ishitatsuyuki** [comment]
Idiot. Read README.

**Comment by Muqsit** [comment]
https://github.com/iTXTech/Genisys/archive/master.zip

**Comment by ishitatsuyuki** [comment]
@Muqsit Hmm... since he's an idiot, why not give him a phar?

**Comment by MhikeiMPC** [comment]
Don't call me an idiot because i made a mistake. we are humans not machines. Dont judge me until you're perfect bitch @ishitatsuyuki

**Comment by ishitatsuyuki** [comment]
@MhikeiMPC Don't judge me until you read the README. You're just violating what an issue is.

**Comment by MhikeiMPC** [comment]
@ishitatsuyuki I wasn't judging you. You are assuming because I didn't read the readme I'm an idiot and I need a phar. You're probably just one of those depressed people who take their frustration out on others. Just shut up and go on with your daily life. At the end of the day, I got what I wanted while you did nothing but spread your hate.

**Comment by gaoyichuan** [comment]
Locked & Blocked
