### ISSUE TITLE
Client crash, reproduced

### ISSUE THREAD

**Issue by beetree** [iTXTech/Genisys#893]
This world: http://leet.cc/crashworld.tgz

Go to `(world, -11.6626, 4, -101.6172)` and fly around and you will crash (e.g. the MCPE client will crash, no error messages server-side).

If you remove the villager at `(world, 42.3, 5, -82.5673)` and the villager at `(world, 69.6934, 3, -107.4929)` the crashing stops. The hypothesis is that villagers is handled differently in Genisys than in PocketMine and therefore maps created in PocketMine (that has villagers) cause crashes.

Assuming the cause is "old villagers", it would be great to get something fixed in Genisys so that old maps work.

Thanks!

/b3

**Comment by ishitatsuyuki** [comment]
Thanks for the details, I will be happy if you have got the /version.

**Comment by beetree** [comment]
`Genisys 1.1dev "Ikaros" implementing API 2.0.0 ... (protocol version 60)`

**Comment by beetree** [comment]
It's a ~2 days old pull from repo.

**Comment by beetree** [comment]
I think it's this one: https://github.com/iTXTech/Genisys/commit/9d804088b3b995fb124c7cf5f79201898f76e53c

**Comment by ishitatsuyuki** [comment]
We got 0.14.2 changes recently. I'm not sure if it's already fixed.

**Comment by DALTONTASTIC** [comment]
Would this explain why I keep crashing? because I spawned in villagers

**Comment by PeratX** [comment]
Fixed

**Comment by beetree** [comment]
Thanks @PeratX , appreciate it a lot!
