### ISSUE TITLE
Tips do not show up

### ISSUE THREAD

**Issue by blui22** [iTXTech/Genisys#894]
#### Issue description

It does not show tips on 0.14.2. I tested the tips on 0.14.1, an it works, but on 0.14.2 tips do not show up.
#### Steps to reproduce the issue

Send a tip to a MCPE client running0.14.2
#### OS and versions

* Genisys: latest
* PHP:7
* OS:Windows 10

#### Crashdump, backtrace or other files
```
No crash dump
```

**Comment by ishitatsuyuki** [comment]
I have heard this is a feature not bug.
