### ISSUE TITLE
Powered and Activator Rails can't be activated

### ISSUE THREAD

**Issue by GlitchPlayer** [iTXTech/Genisys#897]
#### Issue description

Powered and Activator rails do not activate by any redstone.

#### Steps to reproduce the issue

1. Place a Powered or Activator rail
2. Place any redstone you like to activate.
3. You will find it can't be activated

#### OS and versions

* Genisys: Genisys_1.1dev-348
* PHP: 7
* OS: Windows Home

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by DavidJBrockway** [comment]
did you enable redstone in the server config

**Comment by PeratX** [comment]
Not implemented (included in redstone improvement in README.md)
