### ISSUE TITLE
Corrupted Map

### ISSUE THREAD

**Issue by CLiu13** [iTXTech/Genisys#898]
#### Issue description
Any PC map that I try to import shows up as corrupted. Errors I receive include zlib_decode() data errors, corrupted chunks, undefined properties in nbt/tag/EndTag::$Data, and file_get_contents permission denied errors. Maps that I have imported before successfully can no longer be imported successfully.

#### Steps to reproduce the issue
1. Download a PC map, e.x. http://www.planetminecraft.com/project/minecraft-hublobby-spawn-100x100-download/
2. Place the downloaded map into the worlds folder
3. Start the server, and go to the world
4. Errors will show up on console, and map may or may not load on client

#### OS and versions
* Genisys: "This server is running Genisys 1.1dev-348 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.2 alpha (protocol version 60)" Build number 348 from Jenkins.
* PHP: 7
* OS: Ubuntu 14.04

#### Crashdump, backtrace or other files
N/A

Side note: Please do not close this issue by saying, "Your map is corrupted. Get a better map!" I used to be able to import PC maps without trouble.

List of "fixes" I have tried so far:
- chmod -R +X (insert server directory here)
- Deleting level.dat and having Genisys regenerate it

**Comment by CLiu13** [comment]
Can someone test this out, and tell me the results? Very appreciated :)

**Comment by PeratX** [comment]
Once I import a map from leveldb. ldb->anvil->mcr and everything is good. level.dat is generated by Genisys.

**Comment by CLiu13** [comment]
Maps that I download usually are already in mcr. What should I do then?

**Comment by PainTR** [comment]
Do not upload maps with root user

**Comment by Driesboy** [comment]
i dont have that problem and i use 2 pc maps

**Comment by HyGlobalHD** [comment]
i'm using more than 5 map from MCPC and doesn't have any problem...

**Comment by Shamil0402** [comment]
Try to open your map in Minecraft PC and in MCEDit.
A long time ago I have some problems with a MCregions, chuncks dont loading, but it already fixed.
Now i am using an Anvil map:)



Sorry for my bad english:)

**Comment by gaoyichuan** [comment]
Some PC maps may contain blocks or items which MCPE doesn't support. Use MCPC to open it and have a check

**Comment by CLiu13** [comment]
So, just to sum up the comments above, I should remove any non-MCPE items, maybe use Anvil instead, and not upload maps with the root user (although I do not do this). 

However, did anyone test the map from the link I posted above? It seems as if any map in MCRegion format won't work for me.

**Comment by TheAppleGamer** [comment]
Load the world up in PC and load chunks. After that deleted everything in the world folder, except for level.dat and region folder. Place it in pocketmine worlds and it should be loaded up

**Comment by CLiu13** [comment]
This solution helps with some of the issues (zlib, tags, and permissions) but corrupted chunks are still present. How would I fix that then?

**Comment by CLiu13** [comment]
I hate to be repetitive, but has anyone tried the map from this link: http://www.planetminecraft.com/project/minecraft-hublobby-spawn-100x100-download/

It is just a random map I chose from the internet, and it doesn't work for me. I want to see if this is just an issue that I have, or other people are having this issue.

If the map doesn't work, and you were able to fix it somehow, could you please tell me how? I would very much appreciate that 👍

**Comment by KDOA808** [comment]
@CLiu13 got an error to and it crashes the server I have different map but it does say corrupted map or chunks

**Comment by gaoyichuan** [comment]
@KDOA808 @CLiu13 Can you give us a crashdump or backtrace? Thanks a lot

**Comment by CLiu13** [comment]
There isn't a crash dump (doesn't crash the server, the map just doesn't load), but I can take pictures of the console errors and post them here soon.

**Comment by PeratX** [comment]
Paste error report here

**Comment by CLiu13** [comment]
Here is a small sample of the errors messages that I get (the messages are repeated constantly). I removed the file paths for my own reasons 😄 . I am using the map from this link: http://www.planetminecraft.com/project/minecraft-hublobby-spawn-100x100-download/

*BEGIN SERVER ERROR TEXT*

[19:22:40] [Server thread/INFO]: Preparing level "HubSpawn [By: DoomGary]"

Warning: zlib_decode(): data error in **REMOVED FILE PATH**PocketMine-MP.phar/src/pocketmine/nbt/NBT.php on line 473
[19:22:40] [Server thread/ERROR]: Corrupted chunk detected

Warning: zlib_decode(): data error in **REMOVED FILE PATH**PocketMine-MP.phar/src/pocketmine/nbt/NBT.php on line 473
[19:22:40] [Server thread/ERROR]: Corrupted chunk detected
[19:22:40] [Server thread/ERROR]: Corrupted chunk header detected

**Comment by Shamil0402** [comment]
![screenshot_2016-05-04-00-44-01](https://cloud.githubusercontent.com/assets/10086234/14999408/c321a3a6-1191-11e6-8985-8425f997e4e0.png)
![help](https://cloud.githubusercontent.com/assets/10086234/14999422/dd6c11ce-1191-11e6-9ca6-e318ff3d8369.png)

I downloaded your map , and I have no problems with it )


Also, I send my server assembly with your card , I hope it will help you.


https://yadi.sk/d/5txacQCOrTkTg


(it's too big for GitHab)

**Comment by CLiu13** [comment]
Thank you very much! I will download your server setup, test it out, and compare it to my current one.  :)

**Comment by CLiu13** [comment]
I do not know why, but I am still getting the same errors. I am using exactly everything that you have provided, except that I am using Linux PHP binaries instead of Windows. Perhaps that is the error? Can anyone else confirm this?

**Comment by gaoyichuan** [comment]
Linux is less buggy than windows... Maybe your Genisys version is different with Shamil0402's?

**Comment by CLiu13** [comment]
No, I used the Genisys.phar that he provided.

**Comment by ishitatsuyuki** [comment]
Seems there is no reply. Please close it if you no longer have the problem.

**Comment by CLiu13** [comment]
My apologies, I forgot to close this issue. The problem has been resolved.
