### ISSUE TITLE
CPU LOAD

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#899]
Genisys uses only 25 % of the CPU.

Genisys writes that it is loaded by 100 % as can be seen from the screenshots and TPS also fell , but as seen in the task manager it only uses 25 % of CPU .
How to do so would Genisys use all 100 % of the CPU , or is it bug?

* Genisys: BUILD 348
* PHP: 7
* OS: windows 7
![tps](https://cloud.githubusercontent.com/assets/10086234/14939355/9bd8a24c-0f4b-11e6-935e-820b66bb0095.png)

![tps 2](https://cloud.githubusercontent.com/assets/10086234/14939325/87f31ae2-0f4a-11e6-9ade-abc21cecc760.png)

**Comment by ishitatsuyuki** [comment]
You're on quad-core. That's all.

**Comment by Shamil0402** [comment]
Is there support for quad-core?
