### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Subtleoliver** [iTXTech/Genisys#90]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar: /PocketMine-MP.phar/src/pocketmine/Server.php on line 68

Nothing more comes up.

**Comment by PeratX** [comment]
do not use phar on Jenkins. use the lastest commit on github

**Comment by PeratX** [comment]
Now you can use the latest build on Jenkins XD
