### ISSUE TITLE
ForceOp danger!!!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#900]
Force op is popular now,  in my server players op themselfes,  good thing is that my op.txt cant be edited, and after restart all ops are delleted!!!

Why i post this issue? You should add a way to remove op!! I mean,  op to no have any power 👍 , or commands!!! THat will be helpfull!!
I will try tO do something 👍 !!!

**Comment by ishitatsuyuki** [comment]
Your language is funny enough to be marked as spam.

**Comment by TDMidkwhatisxd** [comment]
So rude -.-

**Comment by TDMidkwhatisxd** [comment]
I will code myself a anti force-op!!  IT seems u use genisys to make hacks for kids!!

**Comment by Muqsit** [comment]
You don't need to. Use PlanB with TimeCommander.

**Comment by TDMidkwhatisxd** [comment]
omg this is a awesome ideea :3

**Comment by Muqsit** [comment]
Yeah, but it's not a problem with genisys. You shouldn't be posting things like this.

**Comment by TDMidkwhatisxd** [comment]
I planned tO add,  ban for all ops,  and admins would use pureperms

**Comment by TDMidkwhatisxd** [comment]
I know,  but they made fun of me :(,  is so rude

**Comment by gaoyichuan** [comment]
Please upload a more detailed information. Such as how they got op

**Comment by TDMidkwhatisxd** [comment]
I dont have the hack!!!  But some got the forceOP hack,  and really works, some got forcegamemode  to change creative!!! ("I dont mean  simple cheats that can be found on toolbox,  i mean real hacks")
For example,  my factions pvp server,  got ruined by someone who op countless players, and i just delleted the server, that was long ago!!")

There is not proof of that,  is what i saw!!   But you really should add option to block commands on OP!!
If someone will op themselfes,  they will cant use any commands,  wen i have time i will block commands using pureperms!!!

And a option if allow /gamemode command!!!!
And if someone wanna this , can put true in genisys.yml
I get confirmation that these hacks exist by reading anticheat description on im!!
Otherwise i would not bother you with this 👍 , belive me,  i wont waste my time to lie here!!! 

Sorry that my language is funny,  i learn english just by playing games!!  Hope you understand what i wrote!!!

**Comment by kabluinc** [comment]
The latest update to pureperms has an option in config to disable /op in-game = problem solved

**Comment by TDMidkwhatisxd** [comment]
Depends how forceOP work :|

**Comment by gaoyichuan** [comment]
I think this can be all done by PurePerms plugin

**Comment by XxDXM-hippiexX** [comment]
I've had this problem as well on different server software's..is this really a hack?..it seems to happen to often for it to be a simple mod. I made a anti op plugin a while ago and it kicks them if they are op or have the wrong rank..many people have reported getting kicked due to this reason and have no idea how they got op.

**Comment by TDMidkwhatisxd** [comment]
it really need anti-op -.- !!  Even with timecomander and plan b,  they get 60 seconds to mess with server!!
Is simple,  IsOp=kick!!!

**Comment by TDMidkwhatisxd** [comment]
Someone put a blue flower in spawn garden 😂😂!!!  But this prove they still enjoy,  the force op!!!

**Comment by gaoyichuan** [comment]
The simple **IsOp=kick** approach absolutely can't work. It can greatly bother the real OPs

**Comment by TDMidkwhatisxd** [comment]
This is why we can use pureperms,  and /op command has a fault,  i guess,  i do /op name  , i locked op.txt  so the name is not show in op.txt !! But still the "name" still have op until server restart!!!  So /op read only once op.txt at loading,  so i guess  forceop use this single session , becouse op.txt is not always checked...  !!!
