### ISSUE TITLE
Quad-core support...

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#901]
At maximum load is only 25 % of the CPU .

#### Steps to reproduce the issue
1) Start the server
2) Put a lot of TNT and set fire
3) write /status and see on TPS

#### OS and versions
* Genisys: Сервер использует Genisys 1.1dev-349「 Ikaros」 , версия API 2.0.0 для Minecraft: PE v0.14.2 alpha (версия протокола 60)
* PHP: 7 
* OS: windows 7 64x bit
* CPU: intel core i5-6400 2,7 GGhz
![2](https://cloud.githubusercontent.com/assets/10086234/14942018/3060690a-0fb9-11e6-922f-958f54696a3d.png)
![1](https://cloud.githubusercontent.com/assets/10086234/14942019/3076cdda-0fb9-11e6-9e9a-39a651e27e8f.png)

**Comment by ishitatsuyuki** [comment]
This is impossible with current design.

**Comment by ishitatsuyuki** [comment]
At the time it supports quad-core, it should be no-longer PHP.

**Comment by GlitchPlayer** [comment]
Mine has quad core but load is only 10%-15%
