### ISSUE TITLE
Commands aren't executed in console

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#902]
#### Issue description
The issue is back where commands aren't executed in console after the server has been running for a while.

#### Steps to reproduce the issue
Launch the server let it run for a while (maybe 1/2 hr to an hour) then type commands in the console. Nothing will happen, can't even run the stop command.

#### OS and versions
* Genisys: [Server thread/INFO]: This server is running Genisys 1.1dev-348 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.2 alpha (protocol version 60)
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files
N/A
Paste here
```

**Comment by ishitatsuyuki** [comment]
Windows sucks. Don't use that.

What terminal are you using?

**Comment by NML32** [comment]
Terminal?

**Comment by NML32** [comment]
Why did you close this? I'm running PM server on Windows which is allowed and I thought supportes

**Comment by NML32** [comment]
Supported*

**Comment by gaoyichuan** [comment]
Windows sucks
