### ISSUE TITLE
Please update the Dye names?

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#903]
#### Issue description

All dyes like 351:4 "Lapis Lazuli" all say Dye as the names, please update them? Thank YOUUU
#### OS and versions

* Genisys: #349
* PHP:7
* OS:all

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
Would you mind pasting all the names of dye.

**Comment by ishitatsuyuki** [comment]
@dog194 here's a list from the wiki (ordered by ID)
Ink Sac, Rose Red, Cactus Green, Cocoa Beans, Lapis Lazuli, Cyan Dye, Light Gray Dye, Gray Dye, Pink Dye, Lime Dye, Dandelion Yellow, Light Blue Dye, Magenta Dye, Orange Dye, Bone Meal.
