### ISSUE TITLE
Gear VR - Notice: Undefined offset: 0 in phar://C:/Users/Citrix/Desktop/PocketMine/PocketMine-MP.phar/src/pocketmine/Player.php on line 3502

### ISSUE THREAD

**Issue by StainedPupil** [iTXTech/Genisys#904]
#### Issue description
When Crafting items from the Gear VR edition (Pocket Edition works fine), the error in the subject appears and crafting is impossible as it reverts to items before crafting

#### Steps to reproduce the issue
Connect to server and craft anything in the Gear VR edition of the game. 
NOTE : Crafting in Gear VR uses the original PC crafting as of the PE edition seems to use an automated crafting system.

#### OS and versions

* Genisys:  1.1dev-349 "Ikaros"
* PHP: 7
* OS: Windows 10

**Comment by PeratX** [comment]
Yes. This is a known issue. Already in W10 BUGS. Close
