### ISSUE TITLE
Items put into chests from creative mode disappear

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#905]
#### Issue description

If you put items into chests while in creative the items arent in the chest if you go back in there.
#### OS and versions

* Genisys:#350
* PHP:7
* OS:all

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by gaoyichuan** [comment]
Have you enabled limited creative ?

**Comment by Skyladd** [comment]
No its disabled, otherwise i couldnt access chests at all

**Comment by Shamil0402** [comment]
I noticed that too )

**Comment by PeratX** [comment]
Should be fixed.
