### ISSUE TITLE
Water bottles duplicate when filling and when used in brewing

### ISSUE THREAD

**Issue by Kelton01** [iTXTech/Genisys#906]
#### Issue description

A water bottle can be duplicated when creating an awkward potion out of one bottle. You add one bottle and get out 3. Also when you fill up an empty bottle you will be given a full bottle but also keep the empty one.
#### Steps to reproduce the issue
For brewing:
1: put nether wart and a water bottle into brewing stand.
2: wait a few seconds and out comes 3 awkward potions.

For filling up a bottle:
1: fill up a bottle

#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dog194** [comment]
Please add the version of Genisys.

**Comment by Kelton01** [comment]
1.1 Dev-343

**Comment by dog194** [comment]
Try to fix bug "when filling".

**Comment by dog194** [comment]
[src.txt](https://github.com/iTXTech/Genisys/files/248060/src.txt)
1 change src.txt to src.rar
2 unzip.
3 replace the file Cauldron.php.
4 Reopen your server.
If you donot know how to do this. You can wait someone add this to Genisys.
