### ISSUE TITLE
Chunks dont load on respawn.

### ISSUE THREAD

**Issue by LilCrispy2o9** [iTXTech/Genisys#908]
#### Issue description
When I change the respawn location of a player thats in a different world, the chunks dont load for that player at all and the player is frozen. I have tried spawnToAll() already.

#### Steps to reproduce the issue
setRespawnLocation to world other than the default world.

#### OS and versions

* Genisys:Genisys 1.1dev348
* PHP: 7
* OS: Ubuntu

#### Crashdump, backtrace or other files
N/A
Paste here
```

**Comment by gaoyichuan** [comment]
Have you edited pocketmine.yml to enable auto loading of your new worlds? You should list them in the file

**Comment by LilCrispy2o9** [comment]
Yes the world is loaded. And listed in the pocketmine.yml

**Comment by PeratX** [comment]
setRespawnLocation & restart server

**Comment by LilCrispy2o9** [comment]
I dont want to restart the server, that will ruin the whole purpose of this

**Comment by SleepSpace9** [comment]
I had a similar problem and solved it by changing **chunk-radius** parameter in *genisys.yml* from **-1** to **5**.
