### ISSUE TITLE
server, console and chat hanging frequently

### ISSUE THREAD

**Issue by kabluinc** [iTXTech/Genisys#916]
Ever since the update to 0.14.2 my server hangs every so often. the whole console can be seen as frozen and no one can join the server. if ur in the server while it started hanging, you can move but other players look frozen to you. everything including chat freezes but you can move and build.

i have got the latest phar build and every build that was 0.14.1 never has this hange/freeze issuue. 
after the hanging/freezing stops the whole server crashes most of the time

please fix this issue

**Comment by PeratX** [comment]
This is related to your plugin. And please follow template or next time your issue will be directly CLOSED.

**Comment by kabluinc** [comment]
can i give u a list of plugins i use
