### ISSUE TITLE
Wolves and Ocelots cannot be tamed!

### ISSUE THREAD

**Issue by MhikeiMPC** [iTXTech/Genisys#917]
#### Issue description
Wolves and Ocelots cannot be tamed. Kids on my server are raging out because they cannot tame wolves or ocelots.

#### Steps to reproduce the issue
Try to tame an Ocelot or Wolf.

#### OS and versions

* Genisys:This server is running Genisys 1.1dev-360 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.2 alpha (protocol version 60)
* PHP: 7.0.3
* OS: Windows 7 32-Bit SP1

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Do not add unneeded emotion to an issue. Use Local LAN play if you just want to have a perfect server.

We're never affiliated with Mojang AB, and so we can't have all features perfect.

**Comment by Skyladd** [comment]
@ishitatsuyuki I know its off topic, but how do i find references about double chests? i need it for my plugin :P

**Comment by ishitatsuyuki** [comment]
@Skyladd post questions on gitter or IRC. The next time you spam will get blocked.

**Comment by MhikeiMPC** [comment]
Sorry i never knew i am new to github and i thought it was a bug.
