### ISSUE TITLE
Possibly add hopper? Or start to?

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#918]
#### Issue description

I know that hoppers may be hard, but imagicalmine has them "to an extent". Now that 0.15.0 is coming I just think it would be cool to have all or most of the 0.14.0 items? If not, it's okay. But we are all greatful for all the work you guys do.
#### OS and versions

* Genisys:#360
* PHP:7
* OS:All

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by SkygridRex** [comment]
Could be, So... Let's take CraftBukkit Code and remake for php

**Comment by ishitatsuyuki** [comment]
Nope: CraftBukkit is just a mod to vanilla server. It contains no MC core code. Translating them are just copying decompiled Minecraft and thus illegal.

**Comment by SkygridRex** [comment]
@ishitatsuyuki Genius... Another funcional Idea?

**Comment by ishitatsuyuki** [comment]
We are just busy. It's not very hard.

**Comment by SkygridRex** [comment]
Suppose I'll do it. Hopper must be added on entity folder or blocks folder?

**Comment by Muqsit** [comment]
Tile, block, item, inventory

**Comment by PeratX** [comment]
1.2
