### ISSUE TITLE
Villagers vanished when players attack them.

### ISSUE THREAD

**Issue by Managon-pop** [iTXTech/Genisys#919]
#### Issue description

Villager Vanished.
#### OS and versions

* Genisys:1.1dev「Ikaros」(API 2.0.0)
* PHP:7
* OS: Mac note air

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by ishitatsuyuki** [comment]
Your version is invalid. Please update.

**Comment by Managon-pop** [comment]
I updated. but villagers vanished...

**Comment by ishitatsuyuki** [comment]
Please update your description.

**Comment by Managon-pop** [comment]
Wow! They don't vanished. Thanks.
