### ISSUE TITLE
zend_mm_heap corrupted error on shutdown

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#921]
#### Issue description
Every time I use /stop on my server, I get this message:
```
Server has stopped
zend_mm_heap corrupted
bin\php\php.exe: Exit 1
```

#### Steps to reproduce the issue
Use /stop

#### OS and versions
* Genisys: 1.1dev-364
* PHP: 7.0.4
* OS: Windows 10

**Comment by ishitatsuyuki** [comment]
We have nothing to do. pthreads sucks.

**Comment by ishitatsuyuki** [comment]
This is indicating serious issue, but as long as it works, we have nothing to do until pthreads upstream fix all corruptions.

**Comment by dktapps** [comment]
@ishitatsuyuki fair point I guess. It doesn't appear to affect anything, but nobody had reported it yet so I thought I'd better

**Comment by GlitchPlayer** [comment]
I have it too, and started on PocketMine.
