### ISSUE TITLE
Insanely high CPU usage

### ISSUE THREAD

**Issue by Renual1337** [iTXTech/Genisys#923]
#### Issue description

Until yesterday we were running on a selfly maintained build from April 21 which had some manually merged updates in it. We run a commercial hosting provider using Genisys as our server software. Now yesterday evening we upgraded to the latest version and since then our CPU usage seems to be extremely high. Last weekend there were about 400 players playing overall on our systems and we things were humming along nicely, now yesterday evening we rolled out the new build and basically we woke up to our autoscaling system having scaled up to over double the amount of VM's to host the servers. That being with only about 200 online. Basically for every 6 minecraft instances or so we needed a new 6 core VM until that got extremely hammerered too and that was only because our system already uses cgroups to limit the usage of each minecraft instance. Even an instance with nobody online will nearly max out an entire core.
We've ran the Timings service but to no avail, nothing special in there really. Not different to for example yesterday.

Do you guys have any idea?

#Steps to reproduce
We can let you guys take a look on our systems if need be.

#### OS and versions

Ubuntu 14.04
The PHP build that comes with genisys.
Version: https://gitlab.com/itxtech/genisys/builds/1276083

Thanks!

**Comment by Muqsit** [comment]
This is a weird issue. Can you possibly send us more CPU specs? (Processor & RAM?)

**Comment by ishitatsuyuki** [comment]
Taking a timing maybe can help.

**Comment by Renual1337** [comment]
Hi guys,

The boxes we usually use are Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz with 16GB ram.

Yes, these CPU's aren't that good we know this very well but maxing out an entire node with 2 players online just standing there is definitely an issue, we reverted to our internal build and things are normal again. We took some timings reports earlier, but nothing really out of the ordinary. Here's one https://timings.aikar.co/?url=16223701

While the TPS remained pretty solid throughout the entire time(as can be seen in the timings), the nodes were getting absolutely hammered. This was because our auto deployment system was only putting like 3-6 instances per machine because the server load was already going up so fast.

**Comment by PeratX** [comment]
PHP related

**Comment by Renual1337** [comment]
It only started since the last update though.

**Comment by Muqsit** [comment]
The CPU is really good. But maybe there's another process that's using more RAM. Type 'top' in the console to check which service is consuming the most RAM.

**Comment by Renual1337** [comment]
Hi,

Barely anything is using RAM. We're only using like 4 GB out of the 16 on the nodes and there's no swapping whatsoever.

**Comment by Muqsit** [comment]
If you're on Twitter, you can PM me @muqsitrayyan
