### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by XShockinFireX** [iTXTech/Genisys#926]
whenever i set a spawn on a block and log out and log back in, i spawn on the corner of the block.

**Comment by GlitchPlayer** [comment]
Every server has that

**Comment by XShockinFireX** [comment]
it never used to be like this on my server

**Comment by PeratX** [comment]
+0.5

**Comment by XShockinFireX** [comment]
Huh?

**Comment by GlitchPlayer** [comment]
Even the LBSG server dont spawn at the correct position
