### ISSUE TITLE
Stuck at building terrain

### ISSUE THREAD

**Issue by legoboy0215** [iTXTech/Genisys#931]
#### Issue description
When someone tries to join the server, it is always stuck at building terrain.

#### Steps to reproduce the issue
Start Genisys, then try to join/

#### OS and versions
 This server is running Genisys 1.1dev-d8be48f "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.2 alpha (protocol version 60)
* PHP: 7.0.3
* OS: Ubuntu

#### Crashdump, backtrace or other files
There are no files. Enabled debug, still nothing.

**Comment by ishitatsuyuki** [comment]
Check your network.

**Comment by Muqsit** [comment]
With 0.14.2, you won't get to see the green progress bar while building terrain...wait for a minute for the new world to generate.

**Comment by PeratX** [comment]
Yes. @Muqsit

**Comment by legoboy0215** [comment]
Lol  IK... I waited... Seriously... For 10. Anyways, I solved it.
