### ISSUE TITLE
Player::setExperience() and Player::setExp()

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#932]
Hii , can you reset : Player::setExperience() along with the option now : Player::setExp(). Because I was using a lot Player::setExperience() and his would avoid me having to update all Please

**Comment by ishitatsuyuki** [comment]
Use sed. That's all.

**Comment by gaoyichuan** [comment]
We can't and will NEVER change the API for convince of any single one.

**Comment by MineBuilderFR** [comment]
yes except that before it was setExperience( ) -_-

**Comment by ishitatsuyuki** [comment]
Use shell script and everything is solved.
