### ISSUE TITLE
UUID::fromString();

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [iTXTech/Genisys#933]
#### Issue description

Error when using UUID::fromString();
#### Steps to reproduce the issue

//was using this to test ways to save the uuid as string then get it back as uuid..
$id = $player->getUniqueId()->toString();
$uuid = UUID::fromString($id);

#### OS and versions

* Genisys: 369
* PHP: 7
* OS: windows 10 64 bit

Possibly i am missing something?..but i figured $x = toString so $x should be able to fromString();
#### Crashdump, backtrace or other files
```
Warning: hex2bin(): Hexadecimal input string must have an even length in C:\Users\admin\Downloads\PocketMine-MP\src\pocketmine\utils\UUID.php on line 54

[18:42:24] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerPreLoginEvent' to 'CyberParadoX v0.1': Must have exactly 16 bytes on DXM_Hippie\CyberParadoX\Listener\PocketmineEvents
[18:42:24] [Server thread/CRITICAL]: InvalidArgumentException: "Must have exactly 16 bytes" (EXCEPTION) in "/src/pocketmine/utils/UUID" at line 66

```

**Comment by Leo3418** [comment]
What if you try these:
```
$uuid = $player->getUniqueId();
settype($uuid, "string");
```
Then
```
settype($uuid, "object");
```

**Comment by XxDXM-hippiexX** [comment]
I will need to store it to a config or database.

**Comment by XxDXM-hippiexX** [comment]
Nvm..i see what you're saying. Will try it.

**Comment by PeratX** [comment]
use binary

**Comment by gaoyichuan** [comment]
Would you like to give us the string UUID you passed in?

**Comment by PeratX** [comment]
No details. Close

**Comment by XxDXM-hippiexX** [comment]
Sorry i have been inactive..but should it matter what the string is? its a uuid toString then from string..all api.

**Comment by gaoyichuan** [comment]
It said 'Hexadecimal input string must have an even length', so I think your UUID string is wrong

**Comment by XxDXM-hippiexX** [comment]
So a client side issue? UUID is client side right? and yes it was not a even amount of numbers was the problem..
