### ISSUE TITLE
Water tile issue

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#934]
Water tile issue
When breaking blocks on water shore or under water, the newly created blank space doesn't fill with water.
Normally it should fill with running water and then turn to still water when appropriate.
* Genisys:369
* PHP:7
* OS:

**Comment by gaoyichuan** [comment]
Tested and I didn't find the issue you are talking about. If you can, upload a screenshot.

**Comment by GlitchPlayer** [comment]
It might client issue, considering reconnecting first.

**Comment by Muqsit** [comment]
It happens when your chunk-ticking is set to 0 or a negative value!

**Comment by Bidou0418** [comment]
no it is not the problem
anyways, i posted this issue 3 times its enough.
i am fed up of having staff close the issue without testing or waiting for responses.
