### ISSUE TITLE
Dirt block issue

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#936]
Grass does not grow on dirt block.
* Genisys:369
* PHP:7
* OS:

**Comment by gaoyichuan** [comment]
Provide more details

**Comment by Bidou0418** [comment]
Here is a pic of grass not growing since a week or so and a pic of the water not filling broken blocks beside shore.
![img_0043](https://cloud.githubusercontent.com/assets/14065245/15078125/93d9ae50-1366-11e6-8003-a7bfef34a744.jpg)
![img_0044](https://cloud.githubusercontent.com/assets/14065245/15078130/9a1ab408-1366-11e6-953d-7ce8709d4c08.jpg)

**Comment by HotFireyDeath** [comment]
I have this same issue :)

**Comment by Muqsit** [comment]
Grass not growing since a week? OMG

**Comment by Bidou0418** [comment]
Nope, its at default, haven't touched the yml

**Comment by gaoyichuan** [comment]
Also I can't find the water issue, everything worked smoothly

**Comment by Bidou0418** [comment]
As you can see in the posted screen shots, the problem for the grass not growing on dirt blocs and the water tile issue is definitely present.

**Comment by Bidou0418** [comment]
@Muqsit 
Well after testing with Genisys 374 I decided to remove genisys altogether and installed dev 24 of pocketmine-mp.
guess what, no more problem.
i prefer not to create a new issue and hope you re-open the current instead
thank you
