### ISSUE TITLE
since php7 no LevelDB support?

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Genisys#94]
Since php7 (on x64 linux) it seems that my maps in LevelDB format are no longer recognized.

**Comment by PeratX** [comment]
Try to compile by yourself with https://github.com/PeratX/php-build-scripts

**Comment by xpyctum** [comment]
@PeratX Really? Leveldb not work in php7..? I don't know

**Comment by GalvinGao** [comment]
The LevelDB support is already added in **To-Do list**.

**Comment by Driesboy** [comment]
work leveldb now
