### ISSUE TITLE
Installer working badly...

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#940]
![screenshot_2016-05-07-07-28-22](https://cloud.githubusercontent.com/assets/15706847/15090177/7f4e9120-1425-11e6-9773-f2b88afe3f64.png)

**Comment by Muqsit** [comment]
Oh, the level type must be DEFAULT and not default

**Comment by ishitatsuyuki** [comment]
@Muqsit: Although we're no longer enforcing the approval, please use it if you don't have confidence that it won't cause a bug. Small changes like language or typo are fine though.

**Comment by Muqsit** [comment]
@ishitatsuyuki oohs, sorry. I fixed this bug btw.
#941
