### ISSUE TITLE
Bug with tags (/give command)

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#942]
I want to use tag CanDestroy for pickaxe. But it works badly. I don't know how are things with other tags, but this one is not-working. I got a pickaxe in this way: 
/give alex diamond_pickaxe 1 {CanDestroy:["stone"]}

Genisys ver.: Jenkins build 373

Steps:
1. https://cloud.githubusercontent.com/assets/15706847/15091773/7b488ece-145b-11e6-9678-b55870bfb2a2.png
2. https://youtu.be/cuWkjSI_150

**Comment by Leo3418** [comment]
It seems that Genisys does not support tags yet. Look at [this](https://github.com/iTXTech/Genisys/blob/42e04fb0852545f41bd4878ef7a18e49c4189529/src/pocketmine/command/defaults/GiveCommand.php)

**Comment by ishitatsuyuki** [comment]
@Leo3418 I checked that but I think it supports tags.

Can you debug if the tags are not stored or the adventure logic has problem?

**Comment by alex2534alex** [comment]
Tags stored. There no problems. Debugging shows nothing.

**Comment by alex2534alex** [comment]
Also, how can I view item tags?

**Comment by ishitatsuyuki** [comment]
I have meant debugging by adding extra code to dump the information...

Maybe a NBT viewer can show that. I'm not sure.

**Comment by alex2534alex** [comment]
Can you give me a kernel with already built-in extra code? Or files for replace.

**Comment by ishitatsuyuki** [comment]
If you have no programming skills, please wait for me to debug it.

**Comment by alex2534alex** [comment]
The skills I have, but not too high :P

**Comment by gaoyichuan** [comment]
I think we support the tag
In src/pocketmine/level/Level.php:
```php
               $tag = $item->getNamedTagEntry("CanDestroy");
                if($tag instanceof ListTag){
                        $canBreak = false;
                        foreach($tag as $v){
                                if($v instanceof StringTag){
                                        $entry = Item::fromString($v->getValue());
                                        if($entry->getId() > 0 and $entry->getBlock() !== null and $entry->getBlock()->getId() === $target->getId()){
                                                $canBreak = true;
                                                break;
                                        }
                                }
                        }
 ```

**Comment by Leo3418** [comment]
I don't know much about this, but what GiveCommand.php says is that the give command only takes three arguments, so the fourth argument tag is not read.

**Comment by alex2534alex** [comment]
Look at the screenshot, check of the fourth argument exists. If you don't know the initial array index is zero

https://cloud.githubusercontent.com/assets/15706847/15095982/45a5d82a-14ed-11e6-9595-9c347b5d89a3.png

**Comment by Leo3418** [comment]
Oh you're right... that's strange.

**Comment by ishitatsuyuki** [comment]
Just talking about the reason: the JSON parser got some problem.

Fix should coming soon.

**Comment by alex2534alex** [comment]
Why closed?

**Comment by ishitatsuyuki** [comment]
Because I fixed. Isn't it?

**Comment by alex2534alex** [comment]
Oh yes. I just do not see a note about it here, as it usually happens.
