### ISSUE TITLE
 "extractphar" don't work

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#945]
Genisys ver.: Jenkins build 373
OS: Linux x64

![qqq](https://cloud.githubusercontent.com/assets/15706847/15096312/7b9799f6-14fb-11e6-9c2f-5d515cc4c071.png)

**Comment by alex2534alex** [comment]
I thought that the server is hung, but actually not.

**Comment by GlitchPlayer** [comment]
Use instead "/ep plugin name"

**Comment by alex2534alex** [comment]
I want to extract corrupted plugin, it can't load. So i need to extract phar

**Comment by GlitchPlayer** [comment]
Then, find the plugin on github.

**Comment by alex2534alex** [comment]
...
This is issue. And your way willn't fix this issue -_-

**Comment by GlitchPlayer** [comment]
Then use the /ep command!!!! This command works completely fine on my server!

**Comment by GlitchPlayer** [comment]
Extracting the corrupted plugin is impossible. Find their developers and download the fresh plugin

**Comment by GlitchPlayer** [comment]
Also if Genisys couldn't load the plugin. That means the extract command couldn't find the plugin.

**Comment by alex2534alex** [comment]
/ep - this is /extractplugin .....
/extractplugin and /extractphar - they are not the same!

**Comment by GlitchPlayer** [comment]
Wait wait, so your trying to extract the SRC code of the plugin. But it couldn't be loaded?

**Comment by alex2534alex** [comment]
/extractphar - this extracts any phar file, not only plugins.
/extractplugin - this extracts any LOADED plugin......

**Comment by alex2534alex** [comment]
Yeah.....

**Comment by GlitchPlayer** [comment]
Can you show the vanilla server with help command?

**Comment by GlitchPlayer** [comment]
If it dosen't  shows the extractphar command. It might be a plugin command.

**Comment by alex2534alex** [comment]
No. I don't have any plug-ins installed.
https://cloud.githubusercontent.com/assets/15706847/15096418/34076f72-14ff-11e6-8b76-41e2cfc6fc87.png

Also, there is source of that command.....
![screenshot_2016-05-08-09-27-53](https://cloud.githubusercontent.com/assets/15706847/15096421/5ce04b6c-14ff-11e6-9b0d-185b41a01de3.png)

**Comment by GlitchPlayer** [comment]
Now, can you send the plugin? Imma try it on my server

**Comment by alex2534alex** [comment]
[Plugin.zip](https://github.com/iTXTech/Genisys/files/253779/Plugin.zip)

**Comment by CrayonDing** [comment]
Please use absolute path.And if can't success,there will be no message.

**Comment by alex2534alex** [comment]
I try. Well, please fix "no-message". This problem with "no-message" also existing in /whitelist .

**Comment by gaoyichuan** [comment]
/path/to/your/php/binary/phar extract -f your_file.phar
