### ISSUE TITLE
Problems with give command in creative

### ISSUE THREAD

**Issue by alex2534alex** [iTXTech/Genisys#946]
If I do "/give player item 1" in creative mode, I don't get item. BUT, if I relogin to game, it will be in my inventory. So, if I want to get item in creative with "give", I must relogin. It's uncomfortable.

**Comment by intagaming** [comment]
What about reopening your inventory ?

**Comment by gaoyichuan** [comment]
Isn't gamemode 1 creative?

**Comment by alex2534alex** [comment]
Yeah.

**Comment by alex2534alex** [comment]
It's useful if I want to give me item with tags, but that bug....

**Comment by alex2534alex** [comment]
Plz fix :3

**Comment by PeratX** [comment]
This is because PlayerInventory sendContents when player is in Survival
