### ISSUE TITLE
Additional Download Link

### ISSUE THREAD

**Issue by JustOneMoreBlock** [iTXTech/Genisys#948]
Can you provide a Jenkins phar file without any build numbers?

https://jenkins.mcper.cn/job/Genisys-master/lastSuccessfulBuild/artifact/artifact/Genisys_1.1dev-374.phar

Example:
https://jenkins.mcper.cn/job/Genisys-master/lastSuccessfulBuild/artifact/artifact/Genisys.phar

You would provide both phar files. However, the one without build numbers will allow hosts to instantly update phars.

**Comment by ishitatsuyuki** [comment]
Use Jenkins API.

**Comment by gaoyichuan** [comment]
I will work on a better way of maintaining phars in my summer holiday, wait patiently
