### ISSUE TITLE
Water does not flow to adjacent space created by broken block

### ISSUE THREAD

**Issue by Bidou0418** [iTXTech/Genisys#949]
Map generated water tiles do not flow to adjacent space created by broken block.
example; When breaking a water shore block it is supposed to fill with water but it doesn't.
To ensure this was a Genisys problem, I also tested using Pocketmine-MP dev24.
The problem is not present when using Pocketmine-MP,
![img_0048](https://cloud.githubusercontent.com/assets/14065245/15100678/d230efe2-152d-11e6-8297-900ad995ea86.jpg)

* Genisys:374
* PHP:7

Please do not dismiss before testing.
Thank you

**Comment by PeratX** [comment]
pocketmine.yml->chunk-ticking->per-tick and radius->a non-zero number

**Comment by Bidou0418** [comment]
chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 40
 #Radius of chunks around a player to tick
 tick-radius: 3
 light-updates: false
 clear-tick-list: true

nope that is not the problem @PeratX

**Comment by Bidou0418** [comment]
@PeratX 
Did you test?
please re-open issue so others can perhaps comment or help.
thank you
