### ISSUE TITLE
How To Download

### ISSUE THREAD

**Issue by YanSoo123** [iTXTech/Genisys#951]
How Do I download? can you guide me of the process of starting the server

**Comment by ishitatsuyuki** [comment]
Can you read the README? I'm warning you here that issue tracker is not for support requests.

**Comment by flaxues** [comment]
https://jenkins.mcper.cn/job/Genisys-master/

**Comment by ishitatsuyuki** [comment]
@flaxues You'd better not bumping closed issues. Stop spending time for helping "spammers".
