### ISSUE TITLE
CPU usage and overall performance is shit after 0.14.2

### ISSUE THREAD

**Issue by isoz** [iTXTech/Genisys#957]
#### Issue description
CPU usage after 0.14.2 is off the charts... performance went to shit... I don't have any specific thing to point out...
Before I could easily have up to 400 players over 3 servers and then the lag would appear, now even with minimal players, 5-20 in a single server it lags and moves you back.

#### OS and versions
* Genisys: Latest
* PHP: 7.0.2
* OS: Ubuntu 14.04

#### Crashdump, backtrace or other files
```
Nothing
```

**Comment by Driesboy** [comment]
same

**Comment by Tourin** [comment]
我也有相同的问题。下载最新的build版本的服务器端，然后开了红石和怪物AI后，两三个玩家玩一两小时服务器CPU就100%不够了，需要我装clearlagg手动清怪。

**Comment by isoz** [comment]
Tourin I appreciate your input but I restart my server every hour and I already have clearlagg going every 5 minutes.

**Comment by PeratX** [comment]
Please paste your timings here. Thanks.

**Comment by isoz** [comment]
My timings are fine. I haven't made a change in my servers in 2 months. We
went over this before.

**Comment by isoz** [comment]
If it's of any consolation I did the timings and what stands out is what I expected, login packet.
![Image of Yaktocat](http://i.imgur.com/ziaqZAA.png)
Every time the server restarts or theres more people joining all 4 servers lag a little bit, so there's something wrong with the logins and leaves...

**Comment by Driesboy** [comment]
same on my timings

**Comment by Tourin** [comment]
英文不好，我还是中文再问个问题，比如服务器刚开，cpu就占用百分之零点几，然后有玩家了一会儿，cpu到百分之十几，玩家下线之后，cpu并不下降，还是一直百分之十几在跑，怪物和动物的是不是不能自动回收清理的，需要我用clearlagg清理下，cpu才下降。

**Comment by Muqsit** [comment]
@isoz maybe it's a plugin. This doesn't happen to me :/

**Comment by isoz** [comment]
The timers didnt show any uncommon plugin usage and right now it doesn't seem you have a lot of people online.

**Comment by Bidou0418** [comment]
My server lags and overloads everyday since i upgraded to 14.2.
Not sure if its due to a change in genisys around version 339 or so, or if its due to the client update.
I also need to click my server link 2 or 3 times to connect to my server since then.
My server provider upgraded the ram but no changes.

**Comment by ishitatsuyuki** [comment]
If you can, please give a link to the timings so I can see about the details.

**Comment by isoz** [comment]
Ram doesnt mean much to mcpe. You need CPU

**Comment by Bidou0418** [comment]
@isoz 
what server authentication plugin would you recommend?
I am currently using HereAuth dev228

**Comment by ishitatsuyuki** [comment]
@Bidou0418 you have been warned for off topic discussion.
The next time you do that will result in block.

**Comment by Bidou0418** [comment]
@ishitatsuyuki 
sorry about that
I thought that perhaps the authentication plugin used might positively affect the login packets and improve all around performance.
I will refrain.

**Comment by Driesboy** [comment]
we can fix loginpacket when we disable multi join system

**Comment by isoz** [comment]
@Driesboy where do I find 'multi join system'

**Comment by Driesboy** [comment]
see my fork

**Comment by Driesboy** [comment]
for @gamecraftpe

**Comment by beetree** [comment]
I had an issue with CPU usage after I updated to the latest version today. Here's what I found out. See if this applies to any of you: https://github.com/iTXTech/Genisys/issues/991

**Comment by beetree** [comment]
The bug I was mentioning was just fixed.

**Comment by beetree** [comment]
Properly reverted in https://github.com/iTXTech/Genisys/commit/7f180f43dece0744414ba9dc2533eedba4d5f4a3

**Comment by isoz** [comment]
Why are you closing this @muqsit ? Just because bee said his issue is solved doesn't mean his issue has anything to do with ours, if you take the time to read you will realize it.

**Comment by isoz** [comment]
And why is rumbencraft noob'r'us part of genisys staff?

**Comment by Muqsit** [comment]
This 'bug' cannot be reproduced. I'm quite definite that it's just you that is facing this bug.

**Comment by isoz** [comment]
That does not answer my previous question. Why are you part of a
development team? Anybody with a brain who knows how to read can go through
your pocketmine post history and check all your shitposting and now you're
a dev?😂
To answer you, I do not have a bug, I'm simply complaining about
performance after p
0.14.2, could very well not be genisys and just the game but if that is
true genisys can no longer claim to hold 100+ players Payless as it does in
main page.
On May 21, 2016 06:45, "Muqsit Rayyan" <notifications@github.com> wrote:

This 'bug' cannot be reproduced. I'm quite definite that it's just you that
is facing this bug.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/iTXTech/Genisys/issues/957#issuecomment-220760355>

**Comment by ishitatsuyuki** [comment]
He's quite contributing to our project. We don't check too much history.

**Comment by Muqsit** [comment]
This is why parents don't let you marry people from the same family. Or @isoz would be the final result!

**Comment by PeratX** [comment]
Why? Because he contribute to Genisys. I will check this issue in July (no time these days)

**Comment by beetree** [comment]
@isoz I'm running servers at 80 players online at very loaded servers without an issue. I haven't experienced any performance degradation in 0.14.2. Have you tried benchmarking 0.14.1 against 0.14.2 using a fixed number of bots or something?

/b3

**Comment by isoz** [comment]
Beetree, I haven't tried that but I will, I have a large server so maybe I'll try to invite some players over to an older version and try to find differences, timers only report the login packet...

PeratX I understand that anyone can contribute to the project and that only makes it better, but I disagree that they should have power over closing/opening issues and other staff related activities when they barely know themselves what they are doing, up till 2 months ago that dude was trying to find the perfect "pocketmine.yml" settings lmfao.

**Comment by isoz** [comment]
Easier to see on weekends too due to high traffic...
I get some "Server thread/WARNING]: Can't keep up! Is the server overloaded?" which I never did before.
My server has 32GB of ram and an Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz it used to be enough to hold 400-600 players in multiple servers, now it doesn't matter if there is 40 or 200, sometimes it will lag and timeout people.

**Comment by ishitatsuyuki** [comment]
I suggest you try a 'perf top': it seems to be pretty useful.

**Comment by Bidou0418** [comment]
set async workers to 4 vs auto?

**Comment by isoz** [comment]
@ishitatsuyuki @PeratX you can close this now if you want.
While I still think the game performance declined after said version it seems my problem is because the map is getting too big, it's sitting at 7GB right now, I'm on SSD and have plenty of space not sure how pocketmine handles that, I'm resetting it and setting borders.

**Comment by legoboy0215** [comment]
Still happens to me.
