### ISSUE TITLE
MultiWorld problems

### ISSUE THREAD

**Issue by SirMaxime** [iTXTech/Genisys#958]
#### Issue description
When setting your home or faction  home in let's say World X and running the command to teleport  to that home while being in world Y will teleport you to the home coords but not in the world where the home is at.

#### Steps to reproduce the issue
Create a home with /sethome X in world 1.
Go to another world using a plugin like MultiWorld.
While in that world run the command  /home X

#### OS and versions
* Genisys: 1.1dev
* PHP: PHP7
* OS:CentOS

**Comment by dog194** [comment]
plugin's issue. not Genisys'.

**Comment by SirMaxime** [comment]
It works fine on PocketMine.

**Comment by Muqsit** [comment]
PocketMine's official repo is very backward.

**Comment by ishitatsuyuki** [comment]
@Muqsit: avoid meaningless comments, since they can lower the impression of the team.

**Comment by gaoyichuan** [comment]
You should contact the plugin's developer and submit this issue there. We won't take care of any plugin issue

**Comment by robske110** [comment]
If it works on pocketmine it seems to be your issue

**Comment by SirMaxime** [comment]
If it works fine on PocketMine and bugs on Genisys then it is a problem
with your Genisys.
Le 22 mai 2016 18:22, "Tim (robske_110)" <notifications@github.com> a
écrit :

**Comment by GlitchPlayer** [comment]
PocketMine and Genisys has different codes. If the plugin dev only make the plugin for PocketMine. So it wasn't tested on Genisys

**Comment by robske110** [comment]
Genisys should support pm plugins fully

**Comment by PeratX** [comment]
Yes it is. Genisys is fully support EssTP and FTeleport.

**Comment by PeratX** [comment]
The point is: no code, no truth.

**Comment by CrayonDing** [comment]
In fact ,Genisys is based on PM.I wonder why you think Genisys don.t support PM plugins fully

**Comment by robske110** [comment]
And again as earlier pointed out,  i think the plugin dev forgot to load the world
