### ISSUE TITLE
whitelist off/on not changing in server.properties

### ISSUE THREAD

**Issue by NML32** [iTXTech/Genisys#959]
#### Issue description
when running command whitelist on/of the setting isn't changed in server.properties

#### Steps to reproduce the issue
run whitelist on or whitelist off in the console

#### OS and versions
* Genisys:  Genisys 1.1dev-378 "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.2 alpha (protocol version 60)
* PHP: 7
* OS: Windows10

#### Crashdump, backtrace or other files
N/A
Paste here
```

**Comment by Shamil0402** [comment]
Try this command /whitelist off

**Comment by ishitatsuyuki** [comment]
This is by design: we don't write to YAML.

**Comment by NML32** [comment]
@PeratX Yes, after I shut the server down it makes and saves the setting.
@ishitatsuyuki it's not writing to a YAML file it's writing to server.properties file.
@Shamil0402 you can't use / in console.

**Comment by NML32** [comment]
Please fix this issue. I still don't know why the report was closed.

**Comment by Muqsit** [comment]
This is not a bug. It is meant to happen.
ALTERNATIVELY: When you /reload the server, the server will re-check for modifications done to server.properties file.

**Comment by NML32** [comment]
@Muqsit If you say so but on my Linux box it saves after the command is run without a reload. And I've tested with other versions of PM and it works without a reload. Just saying.
