### ISSUE TITLE
It crast on android note 4 pls fix it

### ISSUE THREAD

**Issue by lolcraftboy14** [iTXTech/Genisys#96]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [14:32:06] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [14:32:06] [Server thread/INFO]: 
[Server] 
[Server] 		 PocketMine-iTX Genisys is a fork of PocketMine-MP.
[Server] 		 Powered by iTX Technologies LLC.
[Server] 		 Version: 1.0dev-1
[Server] 		 Client Version: 0.13.1 alpha
[Server] 		 You could get the lastest code on https://github.com/iTXTech/Genisys
[Server] 		 Donate link: http://pl.zxda.net/plugins/203.html
[Server] 		 如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
[Server] 		
[Server] 
[Server] [14:32:06] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [14:32:07] [Server thread/INFO]: Loading genisys.yml...
[Server] [14:32:07] [Server thread/INFO]: Loading server properties...
[Server] [14:32:07] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [14:32:07] [Server thread/INFO]: Starting Minecraft: PE server version v0.13.1 alpha
[Server] [14:32:07] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [14:32:07] [Server thread/INFO]: This server is running Genisys version 1.0dev-1 "Amazing PHP7 !" (API 1.13.1)
[Server] [14:32:07] [Server thread/INFO]: Genisys is distributed under the LGPL License
[Server] [14:32:08] [Server thread/NOTICE]: Level "world" not found
[Server] [14:32:08] [Server thread/INFO]: Preparing level "world"
[Server] 
[Server] Fatal error: pocketmine\scheduler\AsyncTask cannot implement Collectable - it is not an interface in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/scheduler/AsyncTask.php on line 31
[Server] [14:32:08] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] [14:32:08] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/crashdumps/CrashDump_Sun_Jan_17-14.32.08-UTC_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[Server] [14:32:08] [Server thread/INFO]: Unloading level "world"
[Server] [14:32:08] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to Worker::stack() must be an instance of Collectable, instance of pocketmine\level\generator\GeneratorUnregisterTask given" (EXCEPTION) in "/src/pocketmine/scheduler/AsyncPool" at line 85
[Server] [14:32:08] [Server thread/EMERGENCY]: Crashed while crashing, killing process
[PocketMine] Server was stopped.

**Comment by lolcraftboy14** [comment]
A use php 7.0.0 c3

**Comment by lolcraftboy14** [comment]
More information 


Genisys Crash Dump Sun Jan 17 14:32:08 UTC 2016

Error: pocketmine\scheduler\AsyncTask cannot implement Collectable - it is not an interface
File: /src/pocketmine/scheduler/AsyncTask
Line: 31
Type: E_ERROR

Code:
[22] namespace pocketmine\scheduler;
[23] 
[24] use pocketmine\Server;
[25] 
[26] /**
[27]  * Class used to run async tasks in other threads.
[28]  *
[29]  * WARNING: Do not call PocketMine-MP API methods, or save objects from/on other Threads!!
[30]  */
[31] abstract class AsyncTask extends \Threaded implements \Collectable{
[32] 
[33] 	/** @var AsyncWorker $worker */
[34] 	public $worker = null;
[35] 
[36] 	private $result = null;
[37] 	private $serialized = false;
[38] 	private $cancelRun = false;
[39] 	/** @var int */
[40] 	private $taskId = null;
[41] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.0dev #1 [Protocol 38; API 1.13.1]
uname -a: Linux localhost 3.10.40-5932638 #1 SMP PREEMPT Wed Nov 11 12:36:22 KST 2015 armv7l
PHP version: 7.0.0RC3
Zend version: 3.0.0-dev
OS : Linux, android

Loaded plugins:
加载的插件:

**Comment by PeratX** [comment]
please use php7.0.2 with pthreads 3.1.5

**Comment by lolcraftboy14** [comment]
Were can y vind it fore android

**Comment by PeratX** [comment]
nowhere. But you can compile it by yourself.(cross compile)
