### ISSUE TITLE
Setup.exe has a virus

### ISSUE THREAD

**Issue by GlitchPlayer** [iTXTech/Genisys#963]
#### Issue description

Setup.exe has a virus
#### Steps to reproduce the issue

Download setup.exe from this github page
Run an antivirus scan
#### OS and versions

* Genisys:
* PHP:
* OS:

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by Leo3418** [comment]
Which antivirus software are you using?
I tested it with Windows Defender in Windows 10 and it reports the installer is safe.

**Comment by GlitchPlayer** [comment]
Dont use windows defender i tested on my Avast and tested on my friends,
360 security, Eset Antivirus, and, Norton

**Comment by Leo3418** [comment]
I think you'd better paste reports from your antivirus software here.

**Comment by GlitchPlayer** [comment]
K, imma post a screenshot

**Comment by GlitchPlayer** [comment]
Here's an screenshot
![image](https://cloud.githubusercontent.com/assets/16515013/15209593/8e01dda6-1864-11e6-8584-0334e5b66ea1.png)

Notice that I made a backup of its something goes bad.

**Comment by dog194** [comment]
The Setup.exe is write by "易语言" (A programming language in China). And because of this, a lot of Antivirus cannot recognize. At the same time. The setup will download PHP7 C++2012 genisys.phar. So  to some extent, it may be a virus. If is possible, you can download the code and have a check.

**Comment by GlitchPlayer** [comment]
Kk, but to be sure. Removing this on website is recommended since maybe the
host file might be infected

**Comment by PeratX** [comment]
This set-up is written in 'ELanguage'. It sometimes report to be a virus by some anti-virus programs. So if you do not trust us, just delete it.
