### ISSUE TITLE
xp

### ISSUE THREAD

**Issue by MaryVictoria** [iTXTech/Genisys#964]
Can't receive XL level
![screenshot_2016-05-13-03-06-27](https://cloud.githubusercontent.com/assets/16513171/15227150/6fa59a24-18b8-11e6-8e6e-dfb2dc8deac8.png)
![screenshot_2016-05-13-03-09-21](https://cloud.githubusercontent.com/assets/16513171/15227165/80577d9c-18b8-11e6-9b86-42e15eb11131.png)
![screenshot_2016-05-13-03-06-27](https://cloud.githubusercontent.com/assets/16513171/15227176/8c890aae-18b8-11e6-9789-87d17dec7b58.png)
![screenshot_2016-05-13-03-10-36](https://cloud.githubusercontent.com/assets/16513171/15227184/95ad3d6c-18b8-11e6-97fc-c80f54990c3e.png)

**Comment by Muqsit** [comment]
Just confirmed, doesn't happen!

**Comment by gaoyichuan** [comment]
That's impossible.. The command is written by me and I have tested many times.. Maybe check your plugins?
