### ISSUE TITLE
Question Not a Issue

### ISSUE THREAD

**Issue by EpicSteve33** [iTXTech/Genisys#965]
so I have a server and It's Running ImagicalMine, How did you guys make it so the server checks player movement? because It would be nice to have this on ImagicalMine, the only reason why I'm asking is because I don’t like genisys too much no offence to anyone, I prefer ImagicalMine

**Comment by EpicSteve33** [comment]
its kinda annoying to be pulled back and I want all PocketMine/ImagicalMine users to have a good time while playing on servers

**Comment by ishitatsuyuki** [comment]
These are disabled for performance. Next time you make a question in issue tracker, you will get blocked.

**Comment by gaoyichuan** [comment]
Then use your ImagicalMine, DON'T SPAM HERE!
