### ISSUE TITLE
Bugs in Nether

### ISSUE THREAD

**Issue by Efforto** [iTXTech/Genisys#967]
1.I can sleep well in Nether!!??WTF!????The bed should be exploded!!!
在地狱里睡觉什么鬼，床不是会爆炸的么
2.If you get into the nether door you'll not in the nether spawn, you'll in an unknown place, but if you re-in the game, everything looks fine:)
进地狱门之后还会到一个不知道什么鬼的地方，重进一次才好qwq
3.If you type /kill in nether, you'll get to the main world but the sky is red
地狱里输入/kill，回到原来的地方天空还是红的

PHP:7.0.3
OS:CentOS
Genisys version:Source

**Comment by gaoyichuan** [comment]
Enter your git hash if you use source code, thanks

**Comment by dog194** [comment]
1.服务器本来就跟单机不一样，所有功能都需要开发者编写。床不爆炸只是以为没有写判断是否爆炸的功能代码，所以请不要用这么激动的言论
2 3 传送鬼畜一般出现在网络不好的情况 经过测试网络通畅的时候并没有问题
ps 你可以看最近更新进度，毕竟开发者上学的上学（不务正业的不务正业）所以各种新特性请耐心等待 或者帮助我们提交pr

**Comment by CrayonDing** [comment]
所以 @Efforto 你完全可以直接用qq告诉我的。比这样方便得多。

**Comment by Efforto** [comment]
@dog194 这一点理解。。。
@gaoyichuan I download it yesterday but I dont remember it....= =

**Comment by Muqsit** [comment]
Dude chill, the team is coding Nether from scratch!

**Comment by jojoe77777** [comment]
> Dude chill, the team is coding Nether from scratch!

But they need to know issues or they can't fix them.
