### ISSUE TITLE
Working as standalone, not in Multicraft

### ISSUE THREAD

**Issue by jazzwhistle** [iTXTech/Genisys#97]
Hi, I'm delighted to finally get this working with PHP7 as a standalone server, but when I run it in multicraft I get this error, even with 0 plugins:

Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\Server::batchPackets() must be of the type array, object given, called in phar:///jar/Genisys_1.0dev-2.phar/src/pocketmine/Player.php on line 2038" (EXCEPTION) in "/src/pocketmine/Server" at line 2164

Any ideas? thanks!

**Comment by PocketKiller** [comment]
will check this

**Comment by PocketKiller** [comment]
try https://github.com/iTXTech/Genisys/commit/2d97b17a8663cf6f7116eec02d7adfb711fe911e

**Comment by jazzwhistle** [comment]
Thank you! It works great now, and only a few plugins cause problems. However... I'm running 10 servers on multicraft with Genisys & PHP7 - seven of them work perfectly, but 3 of the servers will not allow anyone connect... there's no errors displays in logs at debug 2, everything looks fine but they don't seem to have network access.

If I switch ports between a working and non-working server, the non-working one starts working... so I thought I'd found the problem, but my firewalld config is fine, and TCP and UDP are open for all the servers. Disabling the firewall has no effect anyway... so I'm stumped as to why some ports just won't work with PHP7 and the latest genisys build. Is there something about the way genisys + PHP7 manages the network that I should know? Thanks

**Comment by PocketKiller** [comment]
make sure on the firewall that **all ports you used** listed on the firewall list need to be ticked private only, try it out.

**Comment by jazzwhistle** [comment]
It doesn't work on those 3 servers even if the firewall is disabled!

**Comment by PeratX** [comment]
well,I think this not the fault of Genisys

**Comment by jazzwhistle** [comment]
Strange that PHP5 version works for all ports, and PHP7 version doesn't
work for some though, no?

**Comment by Lucario2** [comment]
Yeah I can help you with this. I own lucario's server and I do a bunch of crap like this so I will help you.

**Comment by Lucario2** [comment]
Contact me my kik is lucariomcpe

**Comment by jazzwhistle** [comment]
Thanks, the PHP7 problem if the port number > 32768 is fixed now too (https://github.com/PocketMine/PocketMine-MP/issues/3912)
