### ISSUE TITLE
[Help] Transfer Player <-

### ISSUE THREAD

**Issue by MineBuilderFR** [iTXTech/Genisys#970]
How to transfer Player with code?

-> Code Tested :

    $p = $event->getPlayer();
     $hash = $p["ip"] [$ip];
     $hash = $p["port"] [19132];
      PSynapse::transfer($hash);

------

      PSynapse::transfer($ip . ":" . $port);

------

Sorry , It is not issus just Help :/

**Comment by ishitatsuyuki** [comment]
No support requests. Synapse is still in development.
