### ISSUE TITLE
PlayerInteractEvent bug/Packet bug

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#972]
Left click the block with Windows 10 Edition, the Event shows PlayerInteractEvent::LEFT_CLICK_BLOCK
Right click the block with W10 Edition: PlayerInteractEvent::RIGHT_CLICK_BLOCK
Tap the block with Pocket Editon, the Event shows PlayerInteractEvent::RIGHT_CLICK_BLOCK
Holding to the block with PE, the Event shows PlayerInteractEvent::LEFT_CLICK_BLOCK
Isn't that something wrong ?

**Comment by jojoe77777** [comment]
...No? Looks fine to me..

**Comment by intagaming** [comment]
But while i left click/tap blocks in Windows 10 it said Left click, but tap on the MCPE it said Right click?
I thought that right click is Holding on MCPE ?

**Comment by jojoe77777** [comment]
> I thought that right click is Holding on MCPE ?

No, it's left click. Left click on Windows 10 breaks blocks, holding on MCPE breaks blocks. Right click a chest on Windows 10 and it opens, same for tapping it on MCPE.
