### ISSUE TITLE
Fix and add blocks

### ISSUE THREAD

**Issue by EnderKenji** [iTXTech/Genisys#973]
#### Issue description
Fix Iron Trap door and add RedSand Stones. Thanks

#### Steps to reproduce the issue
Trap door cant be place. Please fix ASAP :3

**Comment by Bidou0418** [comment]
Picture frames dont stay flat on wall.
once placed they turn sideways so you only see the edge.

**Comment by EnderKenji** [comment]
Fix this please? :o
