### ISSUE TITLE
Windows 10 crafting bug!

### ISSUE THREAD

**Issue by TDMGamingMC** [iTXTech/Genisys#975]
05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504
17.05 15:07:00 [Server] INFO Notice: Undefined offset: 0 in phar:///Genisys-b338.phar/src/pocketmine/Player.php on line 3504

this is what it saids when i try to craft

**Comment by PeratX** [comment]
Known issue. See W10 bugs. Will solve later(busy nowadays)
