### ISSUE TITLE
Server Wont Start

### ISSUE THREAD

**Issue by EpicSteve33** [iTXTech/Genisys#98]
I’m using the latest src and when I start my server it just closes with no error I think its a issue with php7 or something

**Comment by EpicSteve33** [comment]
![1453078545848805866457](https://cloud.githubusercontent.com/assets/12077835/12381272/300dbfbe-bd3b-11e5-90da-367c690eeeff.jpg)

How do I update to php7

**Comment by zhouruixi** [comment]
https://github.com/iTXTech/PHP-Genisys

**Comment by EpicSteve33** [comment]
./start.sh: line 54: /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin/php5/bin/php: Permission denied
./start.sh: line 54: exec: /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin/php5/bin/php: cannot execute: Permission denied

**Comment by MrDoni98** [comment]
chmod 755 start.sh

**Comment by EpicSteve33** [comment]
nothing happend

**Comment by zhouruixi** [comment]
chmod 777 -R  /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin

**Comment by EpicSteve33** [comment]
nothing is happening is this command for linux

**Comment by PeratX** [comment]
Their commands are right.

**Comment by SleepSpace9** [comment]
I think your php binary doesn't has execution permission, try the following:
```sh
chmod 755 /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin/php7/bin/php

**Comment by EpicSteve33** [comment]
epicsteve33@epicsteve-desktop:~/Desktop/Servers/KingdomCraft/1$ chmod 755 /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin/php7/bin/php
epicsteve33@epicsteve-desktop:~/Desktop/Servers/KingdomCraft/1$ ./start.sh
./start.sh: line 54: /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin/php7/bin/php: cannot execute binary file: Exec format error
./start.sh: line 54: /home/epicsteve33/Desktop/Servers/KingdomCraft/1/bin/php7/bin/php: Success
epicsteve33@epicsteve-desktop:~/Desktop/Servers/KingdomCraft/1$

**Comment by EpicSteve33** [comment]
wait on the folder where I got the php7 from its says "7.0.2_lin64" but i have a x32 machine dose that matter?

**Comment by EpicSteve33** [comment]
cannot execute binary file: Exec format error

**Comment by SleepSpace9** [comment]
Yes, this would be a good reason why your binary can't be executed. You need a PHP7-Package for 32bit (x86) platform.

**Comment by EpicSteve33** [comment]
how would I get this?

**Comment by PeratX** [comment]
Try the compile script

**Comment by SleepSpace9** [comment]
I downloaded it from there:
https://bintray.com/package/files/pocketmine/PocketMine/Unix-PHP-Binaries

You would need *PHP_7.0.0RC3_x86_Linux.tar.gz*. I think the files came from Shoghi's official pocketmine jenkins-page for php7 (http://jenkins.pocketmine.net/job/PHP-PocketMine-Linux/) which is currently offline.
Maybe there are newer versions, PeratX gave me a link for compiling php7 for my self and my special needs: https://github.com/PeratX/php-build-scripts

**Comment by EpicSteve33** [comment]
ok ill try it

**Comment by EpicSteve33** [comment]
it worked but now im having an issue with a plugin

**Comment by EpicSteve33** [comment]
Genisys Crash Dump Mon Jan 18 23:51:25 UTC 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: myzip:///plugins/Slapper_DEV.zip#Slapper_DEV/src/slapper/main
Line: 17
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[8] use pocketmine\entity\Entity;
[9] use pocketmine\event\entity\EntityDamageByEntityEvent;
[10] use pocketmine\event\entity\EntityDamageEvent;
[11] use pocketmine\event\Listener;
[12] use pocketmine\Item\Item;
[13] use pocketmine\nbt\tag\Byte;
[14] use pocketmine\nbt\tag\Compound;
[15] use pocketmine\nbt\tag\Double;
[16] use pocketmine\nbt\tag\Enum;
[17] use pocketmine\nbt\tag\Float;

**Comment by EpicSteve33** [comment]
is there anyway I could fix this myself

**Comment by EpicSteve33** [comment]
Its fix but Please Help me with plugin
