### ISSUE TITLE
Can't place blocks in Survival

### ISSUE THREAD

**Issue by legoboy0215** [iTXTech/Genisys#983]
#### Issue description
Title seriously says it all.

#### Steps to reproduce the issue
Join, break a block and place it.

#### OS and versions
This server is running Genisys 1.1dev-167baef "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.3 alpha (protocol version 70)
* Genisys: 1.1
* PHP: 7.0.2
* OS: Ubuntu

#### Crashdump, backtrace or other files
None

**Comment by jojoe77777** [comment]
I have this issue too, just happened after #981 (Whoops)

**Comment by legoboy0215** [comment]
Yes I can see that. Same thing that happened last time maybe?

**Comment by SuperCraftFacs** [comment]
Same, happening to me. The only server that is fun right now (that is mine) is like my creative server. A lot of people don't like creative servers. Well please fix this soon. 
Btw, Lego ur server is cool and u r a great dev <3

**Comment by legoboy0215** [comment]
Please don't go off-topic. You won't want to anger the staff here XD
