### ISSUE TITLE
0.14.3 support

### ISSUE THREAD

**Issue by Shamil0402** [iTXTech/Genisys#984]
Please update

**Comment by xpyctum** [comment]
Already -_-

**Comment by erkam2002** [comment]
Its not updated look at newest build!

**Comment by kabluinc** [comment]
it was updated but there were block placing problems when in s mode so reverted back to 0.14.2

**Comment by Skyladd** [comment]
Oh no the protocol changed. Hope they find it out soon

**Comment by CLiu13** [comment]
I will submit a formal PR very soon.

**Comment by Muqsit** [comment]
#988

**Comment by Bidou0418** [comment]
cool

**Comment by NML32** [comment]
Good news
