### ISSUE TITLE
LEET

### ISSUE THREAD

**Issue by Skyladd** [iTXTech/Genisys#985]
How do you Genisys developers feel about leet using your software? Did you agree to it or have they offered you anything? I understand it's a free license and all but you guys deserve something for your hard work. LEET is also 100% profit therfore it wouldn't hurt for them to contribute.

**Comment by ishitatsuyuki** [comment]
We're licensing under GPL. Genisys is free software; we don't add any annoying restrictions.

**Comment by Driesboy** [comment]
other licensing !

**Comment by ProjectInfinity** [comment]
@Skyladd Have you asked the PHP developers how they feel about Genisys using their language? Did they receive any offers or anything? I understand it's a free license, but those guys deserve something for their hard work.

**Comment by DWWf** [comment]
LOL

**Comment by gaoyichuan** [comment]
While, Chinese plugin developers just don't follow the license.. So..

**Comment by Skyladd** [comment]
Php is used in Google. It's used every where on the internet. That's like saying that html should get money from every website created.

**Comment by ishitatsuyuki** [comment]
Google doesn't use the sucking language PHP. PHP is a company and they know how to make money. They sell professional tools for PHP.

**Comment by jiang11** [comment]
Ooo HTML, every HTML site there is I get 1 dolla, I'm rich.
