### ISSUE TITLE
Send Tip Not working

### ISSUE THREAD

**Issue by biswarm22** [iTXTech/Genisys#987]
#### Issue description

he is how to fix https://github.com/ClearSkyTeam/ClearSky/commit/4bba525cf78cad4c5fb5f1aea25697f14c6bb357
#### Steps to reproduce the issue

Send a tip 
#### OS and versions

* Genisys: 5feed45 
* PHP: 7
* OS: windows 10

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by TheAppleGamer** [comment]
MCPE 0.14.2 broke sendTip(), please use sendPopup()
