### ISSUE TITLE
Error Starting Up

### ISSUE THREAD

**Issue by TheAppleGamer** [iTXTech/Genisys#990]
#### Issue description

Whenever I start up my server I get this error:
./start.sh : line 70: ./bin/php7/bin/php: cannot execute binary: Exec format error
#### OS and versions

* Genisys: Don't know
* PHP: 7
* OS: Linux Mint

**Comment by gaoyichuan** [comment]
Check your php binary

**Comment by TheAppleGamer** [comment]
There was nothing wrong with it

**Comment by ishitatsuyuki** [comment]
Your architecture is wrong. Use Docker for desktop 64-bit.

**Comment by TheAppleGamer** [comment]
I don't have a 64 bit Ubuntu, I am using a spare laptop

**Comment by ishitatsuyuki** [comment]
By saying "Desktop", I have meant PC, or exactly, amd64 architectures.

**Comment by TheAppleGamer** [comment]
What would I use to get it to work on 32 bit desktop

**Comment by ishitatsuyuki** [comment]
I highly recommend you to have a reinstall. If you have an computer which is too old for 64-bit, don't run a server.
