### ISSUE TITLE
Severe CPU usage increase

### ISSUE THREAD

**Issue by beetree** [iTXTech/Genisys#991]
I deployed most recent version from the repo, and now I'm experiencing a severe CPU usage increase.

I'll gather more information about it and update this issue.

Anyone else experiencing anything similar?

**Comment by beetree** [comment]
Caused by this: https://github.com/Muqsit/Genisys/commit/fe83fe05335967f0cf6af0400d2e67c3a2ede544

**Comment by gaoyichuan** [comment]
We won't provide support for forks.. Submit this issue to that repo please

**Comment by beetree** [comment]
Dude, I'm still testing :) Give me a second and I'll have a better report for you. For now, I just wanted to hear if anyone else had the issue.

You have a largely identical pull request here: https://github.com/iTXTech/Genisys/pull/988

Seems like you're about to bring the change to the main repo, hence why I'm creating the issue.

**Comment by beetree** [comment]
I believe I may have been able of recreating this. I did a "binary search" from May 30 repo until today's repo, and the commit that is causing it it: https://github.com/iTXTech/Genisys/commit/b5301daa4d8ad297f992e482cf24c0ad7e17631d

Then, I downloaded the latest version of the repo and changed the line in the commit back, and CPU usage went back to normal.

If you start a server from bash and pipe input on the command line, those lines of code are necessary. Can we please revert that commit?

/b3

**Comment by beetree** [comment]
Confirmed fixed in https://github.com/iTXTech/Genisys/commit/7f180f43dece0744414ba9dc2533eedba4d5f4a3
